-- PROPOSAL ONLY - DO NOT APPLY TO PRODUCTION
-- Target: a separate greenfield Celebix shared SaaS PostgreSQL database.
-- IDs are generated by Tenant Core; this proposal creates no extensions or privileged roles.

BEGIN;

CREATE TABLE saas_principals (
  id uuid PRIMARY KEY,
  issuer text NOT NULL,
  subject text NOT NULL,
  email text NOT NULL,
  email_verified boolean NOT NULL CHECK (email_verified),
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT saas_principals_issuer_subject_unique UNIQUE (issuer, subject),
  CONSTRAINT saas_principals_issuer_nonempty CHECK (btrim(issuer) <> ''),
  CONSTRAINT saas_principals_subject_nonempty CHECK (btrim(subject) <> '')
);

CREATE TABLE saas_stores (
  id uuid PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  status text NOT NULL CHECK (status IN ('provisioning', 'active', 'suspended', 'failed')),
  locale text NOT NULL CHECK (locale IN ('tr')),
  currency text NOT NULL CHECK (currency IN ('TRY')),
  theme_key text NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT saas_stores_slug_normalized CHECK (slug = lower(slug) AND slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  CONSTRAINT saas_stores_store_id_pair UNIQUE (id, slug)
);

CREATE TABLE saas_domains (
  id uuid PRIMARY KEY,
  store_id uuid NOT NULL REFERENCES saas_stores(id) ON DELETE CASCADE,
  normalized_hostname text NOT NULL UNIQUE,
  domain_type text NOT NULL CHECK (domain_type IN ('platform_subdomain', 'custom')),
  status text NOT NULL CHECK (status IN ('pending_verification', 'active', 'disabled')),
  canonical boolean NOT NULL DEFAULT false,
  cache_version bigint NOT NULL DEFAULT 1 CHECK (cache_version > 0),
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT saas_domains_hostname_normalized CHECK (
    normalized_hostname = lower(normalized_hostname)
    AND normalized_hostname !~ '[*:/]'
  ),
  CONSTRAINT saas_domains_store_domain_pair UNIQUE (store_id, id)
);

CREATE UNIQUE INDEX uq_saas_domains_active_canonical_per_store
  ON saas_domains (store_id)
  WHERE canonical AND status = 'active';

CREATE TABLE saas_memberships (
  id uuid PRIMARY KEY,
  principal_id uuid NOT NULL REFERENCES saas_principals(id) ON DELETE CASCADE,
  store_id uuid NOT NULL REFERENCES saas_stores(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('store_owner', 'admin', 'editor', 'analyst')),
  status text NOT NULL CHECK (status IN ('active', 'invited', 'revoked')),
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT saas_memberships_principal_store_role_unique UNIQUE (principal_id, store_id, role),
  CONSTRAINT saas_memberships_store_membership_pair UNIQUE (store_id, id)
);

CREATE TABLE saas_plans (
  id uuid PRIMARY KEY,
  plan_code text NOT NULL,
  version integer NOT NULL CHECK (version > 0),
  status text NOT NULL CHECK (status IN ('active', 'inactive', 'expired')),
  valid_from timestamptz NOT NULL,
  valid_until timestamptz,
  created_at timestamptz NOT NULL,
  CONSTRAINT saas_plans_code_version_unique UNIQUE (plan_code, version),
  CONSTRAINT saas_plans_identity_version_unique UNIQUE (id, plan_code, version),
  CONSTRAINT saas_plans_validity CHECK (valid_until IS NULL OR valid_until > valid_from)
);

CREATE TABLE saas_plan_features (
  plan_id uuid NOT NULL REFERENCES saas_plans(id) ON DELETE CASCADE,
  feature_key text NOT NULL CHECK (feature_key IN (
    'catalog',
    'orders',
    'customers',
    'content',
    'media',
    'analytics',
    'checkout',
    'custom_domains',
    'staff_management',
    'promotions',
    'integrations',
    'accounting',
    'marketplaces'
  )),
  enabled boolean NOT NULL DEFAULT false,
  PRIMARY KEY (plan_id, feature_key)
);

CREATE TABLE saas_plan_limits (
  plan_id uuid NOT NULL REFERENCES saas_plans(id) ON DELETE CASCADE,
  limit_key text NOT NULL CHECK (limit_key IN (
    'products',
    'staff',
    'storageBytes',
    'monthlyOrders',
    'customDomains'
  )),
  limit_value bigint NOT NULL CHECK (limit_value >= 0),
  PRIMARY KEY (plan_id, limit_key)
);

CREATE TABLE saas_subscriptions (
  id uuid PRIMARY KEY,
  store_id uuid NOT NULL REFERENCES saas_stores(id) ON DELETE CASCADE,
  plan_id uuid NOT NULL,
  plan_code text NOT NULL,
  plan_version integer NOT NULL,
  status text NOT NULL CHECK (status IN ('active', 'inactive', 'expired')),
  valid_from timestamptz NOT NULL,
  valid_until timestamptz,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT saas_subscriptions_plan_version_fk
    FOREIGN KEY (plan_id, plan_code, plan_version)
    REFERENCES saas_plans(id, plan_code, version),
  CONSTRAINT saas_subscriptions_store_subscription_pair UNIQUE (store_id, id),
  CONSTRAINT saas_subscriptions_validity CHECK (valid_until IS NULL OR valid_until > valid_from)
);

CREATE UNIQUE INDEX uq_saas_subscriptions_active_per_store
  ON saas_subscriptions (store_id)
  WHERE status = 'active';

CREATE TABLE saas_store_settings (
  id uuid PRIMARY KEY,
  store_id uuid NOT NULL REFERENCES saas_stores(id) ON DELETE CASCADE,
  key text NOT NULL,
  value jsonb NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT saas_store_settings_store_key_unique UNIQUE (store_id, key),
  CONSTRAINT saas_store_settings_key_nonempty CHECK (btrim(key) <> '')
);

CREATE TABLE saas_tenant_operations (
  id uuid PRIMARY KEY,
  idempotency_key text NOT NULL UNIQUE,
  payload_fingerprint char(64) NOT NULL,
  status text NOT NULL CHECK (status IN ('processing', 'committed', 'failed')),
  result_store_id uuid REFERENCES saas_stores(id),
  result_domain_id uuid,
  result_membership_id uuid,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT saas_tenant_operations_fingerprint_hex CHECK (payload_fingerprint ~ '^[a-f0-9]{64}$'),
  CONSTRAINT saas_tenant_operations_store_domain_fk
    FOREIGN KEY (result_store_id, result_domain_id)
    REFERENCES saas_domains(store_id, id),
  CONSTRAINT saas_tenant_operations_store_membership_fk
    FOREIGN KEY (result_store_id, result_membership_id)
    REFERENCES saas_memberships(store_id, id),
  CONSTRAINT saas_tenant_operations_committed_result CHECK (
    status <> 'committed'
    OR (result_store_id IS NOT NULL AND result_domain_id IS NOT NULL AND result_membership_id IS NOT NULL)
  )
);

CREATE INDEX idx_saas_memberships_principal_status ON saas_memberships (principal_id, status);
CREATE INDEX idx_saas_memberships_store_status ON saas_memberships (store_id, status);
CREATE INDEX idx_saas_domains_normalized_hostname ON saas_domains (normalized_hostname);
CREATE INDEX idx_saas_stores_slug ON saas_stores (slug);
CREATE INDEX idx_saas_subscriptions_store_status ON saas_subscriptions (store_id, status);
CREATE INDEX idx_saas_subscriptions_plan_version ON saas_subscriptions (plan_id, plan_code, plan_version);
CREATE INDEX idx_saas_store_settings_store_key ON saas_store_settings (store_id, key);
CREATE INDEX idx_saas_tenant_operations_idempotency_key ON saas_tenant_operations (idempotency_key);
CREATE INDEX idx_saas_tenant_operations_status_created_at ON saas_tenant_operations (status, created_at);
CREATE INDEX idx_saas_tenant_operations_result_store ON saas_tenant_operations (result_store_id);
CREATE INDEX idx_saas_tenant_operations_result_domain ON saas_tenant_operations (result_store_id, result_domain_id);
CREATE INDEX idx_saas_tenant_operations_result_membership ON saas_tenant_operations (result_store_id, result_membership_id);

INSERT INTO saas_plans (id, plan_code, version, status, valid_from, created_at)
VALUES (
  '00000000-0000-4000-8000-000000000001',
  'free_starter',
  1,
  'active',
  '2026-01-01T00:00:00Z',
  '2026-01-01T00:00:00Z'
);

INSERT INTO saas_plan_features (plan_id, feature_key, enabled)
VALUES
  ('00000000-0000-4000-8000-000000000001', 'catalog', true),
  ('00000000-0000-4000-8000-000000000001', 'orders', true),
  ('00000000-0000-4000-8000-000000000001', 'customers', true),
  ('00000000-0000-4000-8000-000000000001', 'content', true),
  ('00000000-0000-4000-8000-000000000001', 'media', true),
  ('00000000-0000-4000-8000-000000000001', 'analytics', true),
  ('00000000-0000-4000-8000-000000000001', 'checkout', true);

INSERT INTO saas_plan_limits (plan_id, limit_key, limit_value)
VALUES
  ('00000000-0000-4000-8000-000000000001', 'products', 100),
  ('00000000-0000-4000-8000-000000000001', 'staff', 1),
  ('00000000-0000-4000-8000-000000000001', 'storageBytes', 1000000000),
  ('00000000-0000-4000-8000-000000000001', 'monthlyOrders', 100),
  ('00000000-0000-4000-8000-000000000001', 'customDomains', 0);

-- RLS security model:
-- Untrusted application connections must use a non-bypass role.
-- app.current_store_id and app.current_principal_id are set only from authenticated server context.
-- A caller-provided store_id is never authority; application membership checks remain mandatory.
-- Any future maintenance/admin bypass role must be isolated from untrusted request paths.

ALTER TABLE saas_principals ENABLE ROW LEVEL SECURITY;
ALTER TABLE saas_principals FORCE ROW LEVEL SECURITY;
CREATE POLICY saas_principals_identity_isolation ON saas_principals
  USING (id = nullif((SELECT current_setting('app.current_principal_id', true)), '')::uuid)
  WITH CHECK (id = nullif((SELECT current_setting('app.current_principal_id', true)), '')::uuid);

ALTER TABLE saas_stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE saas_stores FORCE ROW LEVEL SECURITY;
CREATE POLICY saas_stores_tenant_isolation ON saas_stores
  USING (id = nullif((SELECT current_setting('app.current_store_id', true)), '')::uuid)
  WITH CHECK (id = nullif((SELECT current_setting('app.current_store_id', true)), '')::uuid);

ALTER TABLE saas_domains ENABLE ROW LEVEL SECURITY;
ALTER TABLE saas_domains FORCE ROW LEVEL SECURITY;
CREATE POLICY saas_domains_tenant_isolation ON saas_domains
  USING (store_id = nullif((SELECT current_setting('app.current_store_id', true)), '')::uuid)
  WITH CHECK (store_id = nullif((SELECT current_setting('app.current_store_id', true)), '')::uuid);

ALTER TABLE saas_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE saas_memberships FORCE ROW LEVEL SECURITY;
CREATE POLICY saas_memberships_tenant_isolation ON saas_memberships
  USING (store_id = nullif((SELECT current_setting('app.current_store_id', true)), '')::uuid)
  WITH CHECK (store_id = nullif((SELECT current_setting('app.current_store_id', true)), '')::uuid);

ALTER TABLE saas_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE saas_plans FORCE ROW LEVEL SECURITY;
CREATE POLICY saas_plans_active_read ON saas_plans FOR SELECT USING (status = 'active');

ALTER TABLE saas_plan_features ENABLE ROW LEVEL SECURITY;
ALTER TABLE saas_plan_features FORCE ROW LEVEL SECURITY;
CREATE POLICY saas_plan_features_read ON saas_plan_features FOR SELECT USING (enabled);

ALTER TABLE saas_plan_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE saas_plan_limits FORCE ROW LEVEL SECURITY;
CREATE POLICY saas_plan_limits_read ON saas_plan_limits FOR SELECT USING (limit_value >= 0);

ALTER TABLE saas_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE saas_subscriptions FORCE ROW LEVEL SECURITY;
CREATE POLICY saas_subscriptions_tenant_isolation ON saas_subscriptions
  USING (store_id = nullif((SELECT current_setting('app.current_store_id', true)), '')::uuid)
  WITH CHECK (store_id = nullif((SELECT current_setting('app.current_store_id', true)), '')::uuid);

ALTER TABLE saas_store_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE saas_store_settings FORCE ROW LEVEL SECURITY;
CREATE POLICY saas_store_settings_tenant_isolation ON saas_store_settings
  USING (store_id = nullif((SELECT current_setting('app.current_store_id', true)), '')::uuid)
  WITH CHECK (store_id = nullif((SELECT current_setting('app.current_store_id', true)), '')::uuid);

ALTER TABLE saas_tenant_operations ENABLE ROW LEVEL SECURITY;
ALTER TABLE saas_tenant_operations FORCE ROW LEVEL SECURITY;
CREATE POLICY saas_tenant_operations_tenant_isolation ON saas_tenant_operations
  USING (result_store_id = nullif((SELECT current_setting('app.current_store_id', true)), '')::uuid)
  WITH CHECK (result_store_id = nullif((SELECT current_setting('app.current_store_id', true)), '')::uuid);

COMMIT;
