DO $f$
DECLARE actor record; result text; role_name text; dashboard_signature text := 'saas.merchant_analytics_dashboard(uuid,uuid,uuid,uuid,text,bigint,timestamp with time zone,text)'; series_signature text := 'saas.merchant_analytics_series(uuid,timestamp with time zone,timestamp with time zone,text)'; top_signature text := 'saas.merchant_analytics_top_products(uuid,timestamp with time zone,timestamp with time zone)';
BEGIN
  IF to_regprocedure(dashboard_signature) IS NULL THEN RAISE EXCEPTION 'MERCHANT_ANALYTICS_API_MISSING'; END IF;
  IF EXISTS(SELECT 1 FROM pg_catalog.pg_proc p CROSS JOIN LATERAL pg_catalog.aclexplode(COALESCE(p.proacl,pg_catalog.acldefault('f',p.proowner))) acl WHERE p.oid=dashboard_signature::regprocedure AND acl.grantee=0 AND acl.privilege_type='EXECUTE') OR NOT has_function_privilege('celebix_saas_app',dashboard_signature,'EXECUTE') THEN RAISE EXCEPTION 'MERCHANT_ANALYTICS_DASHBOARD_ACL_INVALID'; END IF;
  FOREACH role_name IN ARRAY ARRAY['celebix_saas_workflow','celebix_saas_host_resolver','celebix_saas_bootstrap','celebix_saas_observability','celebix_saas_migrator'] LOOP
    IF has_function_privilege(role_name,dashboard_signature,'EXECUTE') OR has_function_privilege(role_name,series_signature,'EXECUTE') OR has_function_privilege(role_name,top_signature,'EXECUTE') THEN RAISE EXCEPTION 'MERCHANT_ANALYTICS_ACL_LEAK:%',role_name; END IF;
  END LOOP;
  IF has_function_privilege('celebix_saas_app',series_signature,'EXECUTE') OR has_function_privilege('celebix_saas_app',top_signature,'EXECUTE') OR EXISTS(SELECT 1 FROM pg_catalog.pg_proc p CROSS JOIN LATERAL pg_catalog.aclexplode(COALESCE(p.proacl,pg_catalog.acldefault('f',p.proowner))) acl WHERE p.oid IN(series_signature::regprocedure,top_signature::regprocedure) AND acl.grantee=0 AND acl.privilege_type='EXECUTE') THEN RAISE EXCEPTION 'MERCHANT_ANALYTICS_HELPER_LEAK'; END IF;
  FOR actor IN SELECT m.role,m.store_id,m.principal_id,m.id AS membership_id,s.plan_id,s.plan_code,s.plan_version FROM saas.memberships m JOIN saas.subscriptions s ON s.store_id=m.store_id AND s.status='active' JOIN saas.plans p ON p.id=s.plan_id AND p.plan_code=s.plan_code AND p.version=s.plan_version AND p.status='active' JOIN saas.plan_features f ON f.plan_id=p.id AND f.feature_key='analytics' AND f.enabled WHERE m.status='active' AND m.role IN('store_owner','admin','editor','analyst') AND s.valid_from<='2026-07-22T19:00:00Z' AND (s.valid_until IS NULL OR s.valid_until>'2026-07-22T19:00:00Z') AND p.valid_from<='2026-07-22T19:00:00Z' AND (p.valid_until IS NULL OR p.valid_until>'2026-07-22T19:00:00Z') LOOP
    SELECT saas.merchant_action_authority_error(actor.store_id,actor.principal_id,actor.membership_id,actor.plan_id,actor.plan_code,actor.plan_version,'2026-07-22T19:00:00Z','analytics','analytics.read') INTO result;
    IF result IS NOT NULL THEN RAISE EXCEPTION 'MERCHANT_ANALYTICS_ROLE_DENIED:%:%',actor.role,result; END IF;
  END LOOP;
  IF position('analytics.write' IN pg_get_functiondef('saas.merchant_action_authority_error(uuid,uuid,uuid,uuid,text,bigint,timestamp with time zone,text,text)'::regprocedure))>0 THEN RAISE EXCEPTION 'MERCHANT_ANALYTICS_ACTION_BROADENED'; END IF;
END $f$;
