-- Reviewed schema-208 extension. No operator identity or money is seeded.
BEGIN;
DO $role$ BEGIN
 IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='celebix_saas_platform_operator') THEN
  IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='celebix_saas_platform_operator' AND NOT rolcanlogin AND NOT rolinherit AND NOT rolbypassrls AND NOT rolsuper AND NOT rolcreatedb AND NOT rolcreaterole AND NOT rolreplication) THEN RAISE EXCEPTION 'PLATFORM_ROLE_ATTRIBUTES_INVALID';END IF;
 ELSE CREATE ROLE celebix_saas_platform_operator NOLOGIN NOINHERIT NOBYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;END IF;
END $role$;
SET LOCAL ROLE celebix_saas_owner;
GRANT USAGE ON SCHEMA saas TO celebix_saas_platform_operator;
CREATE TABLE saas.platform_operators(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),issuer text NOT NULL CHECK(length(issuer) BETWEEN 1 AND 2048 AND issuer=btrim(issuer)),subject text NOT NULL CHECK(length(subject) BETWEEN 1 AND 512 AND subject=btrim(subject)),
 principal_id uuid NOT NULL REFERENCES saas.principals(id),email text NOT NULL CHECK(email='sdkahmetcelebi@icloud.com'),active boolean NOT NULL DEFAULT false,version bigint NOT NULL DEFAULT 1 CHECK(version BETWEEN 1 AND 9007199254740991),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),UNIQUE(issuer,subject));
CREATE UNIQUE INDEX platform_sole_active_operator ON saas.platform_operators((true)) WHERE active;
CREATE TABLE saas.platform_store_versions(store_id uuid PRIMARY KEY REFERENCES saas.stores(id),version bigint NOT NULL DEFAULT 0 CHECK(version BETWEEN 0 AND 9007199254740991));
CREATE TABLE saas.platform_audit(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),operator_id uuid NOT NULL REFERENCES saas.platform_operators(id),store_id uuid REFERENCES saas.stores(id),action text NOT NULL,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE saas.platform_command_results(operator_id uuid NOT NULL REFERENCES saas.platform_operators(id),idempotency_key text NOT NULL CHECK(length(idempotency_key) BETWEEN 1 AND 128),request jsonb NOT NULL,result jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(operator_id,idempotency_key));
CREATE TABLE saas.platform_billing_periods(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),store_id uuid NOT NULL REFERENCES saas.stores(id),label text NOT NULL CHECK(length(label) BETWEEN 1 AND 160 AND label=btrim(label)),starts_on date NOT NULL,ends_on date NOT NULL,due_on date NOT NULL,amount_cents bigint NOT NULL CHECK(amount_cents BETWEEN 1 AND 9007199254740991),currency text NOT NULL DEFAULT 'TRY' CHECK(currency='TRY'),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),UNIQUE(store_id,id),CHECK(ends_on>=starts_on));
CREATE TABLE saas.platform_billing_adjustments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),store_id uuid NOT NULL,period_id uuid NOT NULL,delta_cents bigint NOT NULL CHECK(delta_cents BETWEEN -9007199254740991 AND 9007199254740991 AND delta_cents<>0),reason text NOT NULL CHECK(length(reason) BETWEEN 1 AND 2000 AND reason=btrim(reason)),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),FOREIGN KEY(store_id,period_id) REFERENCES saas.platform_billing_periods(store_id,id));
CREATE TABLE saas.platform_receipts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),store_id uuid NOT NULL,period_id uuid NOT NULL,amount_cents bigint NOT NULL CHECK(amount_cents BETWEEN 1 AND 9007199254740991),method text NOT NULL CHECK(method IN('cash','bank_transfer','card')),reference text NOT NULL CHECK(length(reference) BETWEEN 1 AND 200),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),FOREIGN KEY(store_id,period_id) REFERENCES saas.platform_billing_periods(store_id,id),UNIQUE(store_id,id));
CREATE TABLE saas.platform_receipt_reversals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),store_id uuid NOT NULL,receipt_id uuid NOT NULL UNIQUE,reason text NOT NULL CHECK(length(reason) BETWEEN 1 AND 2000 AND reason=btrim(reason)),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),FOREIGN KEY(store_id,receipt_id) REFERENCES saas.platform_receipts(store_id,id));
CREATE TABLE saas.platform_ownership_invitations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),store_id uuid NOT NULL REFERENCES saas.stores(id),target_principal_id uuid NOT NULL REFERENCES saas.principals(id),target_issuer text NOT NULL,target_subject text NOT NULL,role text NOT NULL CHECK(role IN('store_owner','admin','editor','analyst','cashier')),kind text NOT NULL CHECK(kind IN('invite','transfer')),previous_owner_disposition text CHECK(previous_owner_disposition IN('admin','revoked')),created_by uuid NOT NULL REFERENCES saas.platform_operators(id),token_hash bytea NOT NULL UNIQUE,expires_at timestamptz NOT NULL,accepted_at timestamptz,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),CHECK(kind<>'transfer' OR (role='store_owner' AND previous_owner_disposition IS NOT NULL)));
CREATE TABLE saas.platform_plan_publications(plan_id uuid PRIMARY KEY REFERENCES saas.plans(id),transaction_id bigint NOT NULL);
CREATE TABLE saas.platform_plan_prices(plan_id uuid PRIMARY KEY REFERENCES saas.plans(id),monthly_price_cents bigint CHECK(monthly_price_cents BETWEEN 0 AND 9007199254740991),yearly_price_cents bigint CHECK(yearly_price_cents BETWEEN 0 AND 9007199254740991));
CREATE TABLE saas.platform_209_restore(signature text PRIMARY KEY,definition text NOT NULL);
INSERT INTO saas.platform_209_restore SELECT 'saas.reject_plan_version_mutation()',pg_get_functiondef('saas.reject_plan_version_mutation()'::regprocedure);
DO $security$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['platform_operators','platform_store_versions','platform_audit','platform_command_results','platform_billing_periods','platform_billing_adjustments','platform_receipts','platform_receipt_reversals','platform_ownership_invitations','platform_plan_publications','platform_plan_prices','platform_209_restore'] LOOP
 EXECUTE format('ALTER TABLE saas.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE saas.%I FORCE ROW LEVEL SECURITY',t);EXECUTE format('REVOKE ALL ON saas.%I FROM PUBLIC,celebix_saas_platform_operator,celebix_saas_app,celebix_saas_identity,celebix_saas_workflow,celebix_saas_bootstrap',t);
 END LOOP;
END $security$;
CREATE FUNCTION saas.platform_append_only() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $fn$ BEGIN RAISE EXCEPTION 'PLATFORM_APPEND_ONLY';END $fn$;
DO $immutable$ DECLARE t text;BEGIN FOREACH t IN ARRAY ARRAY['platform_audit','platform_command_results','platform_billing_periods','platform_billing_adjustments','platform_receipts','platform_receipt_reversals','platform_plan_prices'] LOOP EXECUTE format('CREATE TRIGGER platform_append_only BEFORE UPDATE OR DELETE ON saas.%I FOR EACH ROW EXECUTE FUNCTION saas.platform_append_only()',t);END LOOP;END $immutable$;
CREATE FUNCTION saas.platform_operator_identity_guard() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $fn$ BEGIN IF TG_OP='DELETE' OR NEW.id IS DISTINCT FROM OLD.id OR NEW.issuer IS DISTINCT FROM OLD.issuer OR NEW.subject IS DISTINCT FROM OLD.subject OR NEW.principal_id IS DISTINCT FROM OLD.principal_id OR NEW.email IS DISTINCT FROM OLD.email OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN RAISE EXCEPTION 'PLATFORM_OPERATOR_IDENTITY_IMMUTABLE';END IF;RETURN NEW;END $fn$;
CREATE TRIGGER platform_operator_identity_guard BEFORE UPDATE OR DELETE ON saas.platform_operators FOR EACH ROW EXECUTE FUNCTION saas.platform_operator_identity_guard();
CREATE FUNCTION saas.platform_operator_require_active(p_operator uuid) RETURNS saas.platform_operators LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $fn$
DECLARE o saas.platform_operators;BEGIN
 SELECT x.* INTO o FROM saas.platform_operators x JOIN saas.principals p ON p.id=x.principal_id AND p.issuer=x.issuer AND p.subject=x.subject AND p.email_verified AND lower(p.email)=x.email WHERE x.id=p_operator AND x.active;
 IF NOT FOUND THEN RAISE EXCEPTION 'operator_denied' USING ERRCODE='42501';END IF;RETURN o;
END $fn$;
CREATE FUNCTION saas.platform_operator_resolve(p_issuer text,p_subject text) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $fn$
DECLARE o saas.platform_operators;BEGIN SELECT * INTO o FROM saas.platform_operators WHERE issuer=p_issuer AND subject=p_subject AND active;PERFORM saas.platform_operator_require_active(o.id);RETURN jsonb_build_object('id',o.id,'issuer',o.issuer,'subject',o.subject,'principalId',o.principal_id,'email',o.email,'active',o.active,'version',o.version);END $fn$;
-- Existing freeze triggers retain their identities and forbid all edits. Only fresh publication inserts can pass.
CREATE OR REPLACE FUNCTION saas.reject_plan_version_mutation() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,saas AS $fn$
BEGIN IF TG_OP='INSERT' AND TG_TABLE_NAME IN('plan_features','plan_limits') THEN IF EXISTS(SELECT 1 FROM saas.platform_plan_publications WHERE plan_id=NEW.plan_id AND transaction_id=txid_current()) THEN RETURN NEW;END IF;END IF;RAISE EXCEPTION 'PLAN_VERSION_IMMUTABLE';END $fn$;
CREATE FUNCTION saas.platform_last_owner_guard() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,saas AS $fn$
DECLARE sid uuid;BEGIN sid:=CASE WHEN TG_OP='DELETE' THEN OLD.store_id ELSE NEW.store_id END;PERFORM pg_advisory_xact_lock(hashtextextended('platform-owner:'||sid::text,0));
 IF TG_OP IN('UPDATE','DELETE') AND OLD.role='store_owner' AND OLD.status='active' AND (TG_OP='DELETE' OR NEW.role<>'store_owner' OR NEW.status<>'active' OR NEW.store_id<>OLD.store_id) AND NOT EXISTS(SELECT 1 FROM saas.memberships WHERE store_id=OLD.store_id AND id<>OLD.id AND role='store_owner' AND status='active') THEN RAISE EXCEPTION 'last_owner';END IF;RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
END $fn$;
CREATE TRIGGER platform_last_owner_guard BEFORE INSERT OR UPDATE OR DELETE ON saas.memberships FOR EACH ROW EXECUTE FUNCTION saas.platform_last_owner_guard();
CREATE FUNCTION saas.platform_store_usage(p_store uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $fn$
 SELECT jsonb_build_object('products',(SELECT count(*) FROM saas.products WHERE store_id=p_store AND status<>'archived'),'staff',(SELECT count(*) FROM saas.memberships m WHERE store_id=p_store AND status='active' AND role<>'store_owner' AND coalesce(to_jsonb(m)->>'support_session_id','')=''),'storageBytes',(SELECT coalesce(sum(byte_size),0) FROM saas.product_media WHERE store_id=p_store AND status IN('active','pending','archived'))+(SELECT coalesce(sum(byte_size),0) FROM saas.storefront_assets WHERE store_id=p_store AND status IN('active','pending','archived')),'monthlyOrders',(SELECT count(*) FROM saas.orders WHERE store_id=p_store AND created_at>=date_trunc('month',now())),'customDomains',(SELECT count(*) FROM (SELECT hostname FROM saas.store_domains WHERE store_id=p_store AND hostname_type='custom_domain' AND status<>'disabled' UNION SELECT normalized_hostname FROM saas.domains WHERE store_id=p_store AND domain_type='custom' AND status<>'disabled') d))
$fn$;
CREATE FUNCTION saas.platform_subscription_projection(p_store uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $fn$
 SELECT jsonb_build_object('id',id,'storeId',store_id,'planId',plan_id,'planCode',plan_code,'planVersion',plan_version,'status',status,'validFrom',valid_from,'validUntil',valid_until) FROM saas.subscriptions WHERE store_id=p_store AND status='active' LIMIT 1
$fn$;
CREATE FUNCTION saas.platform_period_projection(p_period uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $fn$
 SELECT jsonb_build_object('id',p.id,'storeId',p.store_id,'label',p.label,'startsOn',p.starts_on,'endsOn',p.ends_on,'dueOn',p.due_on,'amountCents',p.amount_cents+coalesce(adjustments.delta,0),'originalAmountCents',p.amount_cents,'adjustmentCents',coalesce(adjustments.delta,0),'collectedCents',coalesce(c.collected,0),'remainingCents',p.amount_cents+coalesce(adjustments.delta,0)-coalesce(c.collected,0),'currency',p.currency,'version',coalesce(v.version,0)) FROM saas.platform_billing_periods p LEFT JOIN saas.platform_store_versions v ON v.store_id=p.store_id LEFT JOIN LATERAL(SELECT sum(r.amount_cents) AS collected FROM saas.platform_receipts r WHERE r.period_id=p.id AND NOT EXISTS(SELECT 1 FROM saas.platform_receipt_reversals x WHERE x.receipt_id=r.id)) c ON true LEFT JOIN LATERAL(SELECT sum(delta_cents) AS delta FROM saas.platform_billing_adjustments WHERE period_id=p.id) adjustments ON true WHERE p.id=p_period
$fn$;
CREATE FUNCTION saas.platform_merchant_sales_projection(p_store uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $fn$
 SELECT jsonb_build_object('available',true,'currency','TRY','totalCents',coalesce(sum(total_cents),0),'webCents',coalesce(sum(total_cents) FILTER(WHERE source IN('storefront','quick_link')),0),'posCents',coalesce(sum(total_cents) FILTER(WHERE source='in_store'),0),'orderCount',count(*),'excludedCurrencyOrders',(SELECT count(*) FROM saas.orders WHERE currency<>'TRY' AND (p_store IS NULL OR store_id=p_store)))
 FROM saas.orders o WHERE currency='TRY' AND (p_store IS NULL OR store_id=p_store) AND status NOT IN('cancelled','refunded') AND ((source IN('storefront','quick_link') AND payment_status='completed') OR (source='in_store' AND EXISTS(SELECT 1 FROM saas.in_store_sales x WHERE x.store_id=o.store_id AND x.order_id=o.id AND x.status='completed')))
$fn$;
CREATE FUNCTION saas.platform_store_projection(p_store uuid,p_details boolean) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $fn$
DECLARE result jsonb;BEGIN SELECT jsonb_build_object('id',s.id,'name',s.name,'slug',s.slug,'status',s.status,'version',coalesce(v.version,0),'createdAt',s.created_at,'adminHost',(SELECT hostname FROM saas.admin_domains WHERE store_id=s.id AND status='active' AND verified_at IS NOT NULL ORDER BY canonical DESC,created_at LIMIT 1),'adminOrigin',(SELECT 'https://'||hostname FROM saas.admin_domains WHERE store_id=s.id AND status='active' AND verified_at IS NOT NULL ORDER BY canonical DESC,created_at LIMIT 1),'subscription',saas.platform_subscription_projection(s.id),'merchantSales',CASE WHEN s.currency='TRY' THEN saas.platform_merchant_sales_projection(s.id) ELSE jsonb_build_object('available',false,'currency',s.currency) END,'usage',saas.platform_store_usage(s.id),'domains',coalesce((SELECT jsonb_agg(jsonb_build_object('id',id,'hostname',normalized_hostname,'status',status,'canonical',canonical) ORDER BY normalized_hostname) FROM (SELECT id,hostname AS normalized_hostname,status,is_primary AS canonical FROM saas.store_domains WHERE store_id=s.id UNION ALL SELECT d.id,d.normalized_hostname,d.status,d.canonical FROM saas.domains d WHERE d.store_id=s.id AND NOT EXISTS(SELECT 1 FROM saas.store_domains current_domain WHERE current_domain.store_id=d.store_id AND current_domain.hostname=d.normalized_hostname)) domains),'[]'::jsonb),'adminDomains',coalesce((SELECT jsonb_agg(jsonb_build_object('id',id,'hostname',hostname,'status',status,'canonical',canonical,'verifiedAt',verified_at) ORDER BY canonical DESC,hostname) FROM saas.admin_domains WHERE store_id=s.id),'[]'::jsonb),'memberships',coalesce((SELECT jsonb_agg(jsonb_build_object('id',m.id,'principalId',m.principal_id,'email',p.email,'role',m.role,'status',m.status) ORDER BY m.created_at) FROM saas.memberships m JOIN saas.principals p ON p.id=m.principal_id WHERE m.store_id=s.id AND coalesce(to_jsonb(m)->>'support_session_id','')=''),'[]'::jsonb)) INTO result FROM saas.stores s LEFT JOIN saas.platform_store_versions v ON v.store_id=s.id WHERE s.id=p_store;
 IF result IS NULL THEN RAISE EXCEPTION 'record_not_found';END IF;
 IF to_regprocedure('saas.platform_sales_policy_get(uuid,uuid)') IS NOT NULL THEN result:=result||jsonb_build_object('salesPolicy',coalesce((SELECT jsonb_build_object('storeId',p.store_id,'paused',p.paused,'version',p.version,'reason',p.reason,'updatedAt',p.updated_at) FROM saas.store_sales_policy p WHERE p.store_id=p_store),jsonb_build_object('storeId',p_store,'paused',false,'version',1)));END IF;
 IF p_details THEN result:=result||jsonb_build_object('periods',coalesce((SELECT jsonb_agg(saas.platform_period_projection(id) ORDER BY starts_on DESC) FROM saas.platform_billing_periods WHERE store_id=p_store),'[]'::jsonb),'adjustments',coalesce((SELECT jsonb_agg(jsonb_build_object('id',id,'periodId',period_id,'deltaCents',delta_cents,'reason',reason,'createdAt',created_at) ORDER BY created_at DESC) FROM saas.platform_billing_adjustments WHERE store_id=p_store),'[]'::jsonb),'receipts',coalesce((SELECT jsonb_agg(jsonb_build_object('id',r.id,'periodId',r.period_id,'amountCents',r.amount_cents,'method',r.method,'reference',r.reference,'createdAt',r.created_at,'reversed',EXISTS(SELECT 1 FROM saas.platform_receipt_reversals x WHERE x.receipt_id=r.id)) ORDER BY r.created_at DESC) FROM saas.platform_receipts r WHERE r.store_id=p_store),'[]'::jsonb),'invitations',coalesce((SELECT jsonb_agg(jsonb_build_object('id',id,'targetPrincipalId',target_principal_id,'role',role,'kind',kind,'expiresAt',expires_at,'acceptedAt',accepted_at)) FROM saas.platform_ownership_invitations WHERE store_id=p_store),'[]'::jsonb));END IF;RETURN result;
END $fn$;
CREATE FUNCTION saas.platform_read(p_operator uuid,p_resource text,p_query jsonb) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $fn$
DECLARE items jsonb; sid uuid; envelope jsonb:=jsonb_build_object('available',true,'observedAt',statement_timestamp());BEGIN
 PERFORM saas.platform_operator_require_active(p_operator);IF p_query IS NULL OR jsonb_typeof(p_query)<>'object' OR pg_column_size(p_query)>8192 OR p_query-ARRAY['storeId','limit','email','q','status','from','to','after']<>'{}'::jsonb THEN RAISE EXCEPTION 'invalid_input';END IF;
 IF p_query ? 'limit' AND ((p_query->>'limit')!~'^[0-9]{1,3}$' OR (p_query->>'limit')::integer NOT BETWEEN 1 AND 200) THEN RAISE EXCEPTION 'invalid_input';END IF;
 IF EXISTS(SELECT 1 FROM jsonb_each(p_query) WHERE jsonb_typeof(value) NOT IN('string','number')) THEN RAISE EXCEPTION 'invalid_input';END IF;
 sid:=(p_query->>'storeId')::uuid;
 IF p_resource='store-detail' THEN RETURN envelope||jsonb_build_object('store',saas.platform_store_projection(sid,true));
 ELSIF p_resource='stores' THEN SELECT coalesce(jsonb_agg(saas.platform_store_projection(id,false) ORDER BY created_at DESC),'[]'::jsonb) INTO items FROM saas.stores WHERE (sid IS NULL OR id=sid) AND (p_query->>'q' IS NULL OR strpos(lower(name||' '||slug),lower(p_query->>'q'))>0) AND (p_query->>'status' IS NULL OR status=p_query->>'status');
 ELSIF p_resource='usage' THEN SELECT coalesce(jsonb_agg(jsonb_build_object('storeId',id,'usage',saas.platform_store_usage(id))),'[]'::jsonb) INTO items FROM saas.stores WHERE sid IS NULL OR id=sid;
 ELSIF p_resource='memberships' THEN SELECT coalesce(jsonb_agg(jsonb_build_object('id',m.id,'storeId',m.store_id,'principalId',m.principal_id,'email',p.email,'role',m.role,'status',m.status,'version',coalesce(v.version,0))),'[]'::jsonb) INTO items FROM saas.memberships m JOIN saas.principals p ON p.id=m.principal_id LEFT JOIN saas.platform_store_versions v ON v.store_id=m.store_id WHERE (sid IS NULL OR m.store_id=sid) AND coalesce(to_jsonb(m)->>'support_session_id','')='';
 ELSIF p_resource='invitations' THEN
  IF p_query ? 'email' AND (jsonb_typeof(p_query->'email')<>'string' OR length(p_query->>'email') NOT BETWEEN 3 AND 320 OR p_query->>'email'<>lower(btrim(p_query->>'email'))) THEN RAISE EXCEPTION 'invalid_input';END IF;
  SELECT coalesce(jsonb_agg(jsonb_build_object('id',id,'storeId',store_id,'targetPrincipalId',target_principal_id,'role',role,'kind',kind,'expiresAt',expires_at,'acceptedAt',accepted_at)),'[]'::jsonb) INTO items FROM saas.platform_ownership_invitations WHERE sid IS NULL OR store_id=sid;
  RETURN envelope||jsonb_build_object('items',items,'candidates',coalesce((SELECT jsonb_agg(jsonb_build_object('id',id,'email',email,'verified',email_verified)) FROM saas.principals WHERE email_verified AND email=p_query->>'email'),'[]'::jsonb));
 ELSIF p_resource='plans' THEN SELECT coalesce(jsonb_agg(jsonb_build_object('id',p.id,'code',p.plan_code,'version',p.version,'status',p.status,'monthlyPriceCents',(SELECT monthly_price_cents FROM saas.platform_plan_prices WHERE plan_id=p.id),'yearlyPriceCents',(SELECT yearly_price_cents FROM saas.platform_plan_prices WHERE plan_id=p.id),'features',(SELECT jsonb_object_agg(feature_key,enabled ORDER BY feature_ordinal) FROM saas.plan_features WHERE plan_id=p.id),'limits',(SELECT jsonb_object_agg(limit_key,effective_limit ORDER BY limit_ordinal) FROM saas.plan_limits WHERE plan_id=p.id)) ORDER BY p.plan_code,p.version),'[]'::jsonb) INTO items FROM saas.plans p;
 ELSIF p_resource='subscriptions' THEN SELECT coalesce(jsonb_agg(saas.platform_subscription_projection(id)) FILTER(WHERE saas.platform_subscription_projection(id) IS NOT NULL),'[]'::jsonb) INTO items FROM saas.stores WHERE sid IS NULL OR id=sid;
 ELSIF p_resource='billing' THEN SELECT coalesce(jsonb_agg(saas.platform_period_projection(id) ORDER BY starts_on DESC),'[]'::jsonb) INTO items FROM saas.platform_billing_periods WHERE (sid IS NULL OR store_id=sid) AND (p_query->>'q' IS NULL OR strpos(lower(label),lower(p_query->>'q'))>0) AND (p_query->>'from' IS NULL OR starts_on>=(p_query->>'from')::date) AND (p_query->>'to' IS NULL OR starts_on<=(p_query->>'to')::date);
 ELSIF p_resource='audit' THEN SELECT coalesce(jsonb_agg(jsonb_build_object('id',id,'operatorId',operator_id,'storeId',store_id,'action',action,'payload',payload,'createdAt',created_at) ORDER BY created_at DESC),'[]'::jsonb) INTO items FROM (SELECT * FROM saas.platform_audit WHERE (sid IS NULL OR store_id=sid) AND (p_query->>'q' IS NULL OR strpos(lower(action||' '||payload::text),lower(p_query->>'q'))>0) AND (p_query->>'from' IS NULL OR created_at>=(p_query->>'from')::timestamptz) AND (p_query->>'to' IS NULL OR created_at<(p_query->>'to')::date+interval '1 day') AND (p_query->>'after' IS NULL OR created_at<(p_query->>'after')::timestamptz) ORDER BY created_at DESC LIMIT least(coalesce((p_query->>'limit')::integer,100),200)) a;
 ELSIF p_resource='operations' THEN SELECT coalesce(jsonb_agg(jsonb_build_object('id',id,'storeId',result_store_id,'status',status,'createdAt',created_at,'updatedAt',updated_at,'retryable',false) ORDER BY created_at DESC),'[]'::jsonb) INTO items FROM (SELECT * FROM saas.tenant_operations WHERE sid IS NULL OR result_store_id=sid ORDER BY created_at DESC LIMIT 100) o;
 ELSIF p_resource='support-sessions' AND to_regprocedure('saas.platform_support_list(uuid,jsonb)') IS NOT NULL THEN EXECUTE 'SELECT saas.platform_support_list($1,$2)' INTO items USING p_operator,p_query;RETURN envelope||items;
 ELSIF p_resource='overview' THEN RETURN envelope||jsonb_build_object('storeCount',(SELECT count(*) FROM saas.stores),'activeStoreCount',(SELECT count(*) FROM saas.stores WHERE status='active'),'pendingSetupCount',(SELECT count(*) FROM saas.stores WHERE status='provisioning'),'attentionIssueCount',(SELECT count(*) FROM saas.registration_onboarding_jobs WHERE state='attention_required')+(SELECT count(*) FROM (SELECT store_id,hostname FROM saas.store_domains WHERE status='pending' UNION SELECT store_id,hostname FROM saas.admin_domains WHERE status='pending_verification' UNION SELECT store_id,normalized_hostname FROM saas.domains WHERE status='pending_verification') pending_domains),'upcomingDueCount',(SELECT count(*) FROM saas.platform_billing_periods WHERE due_on BETWEEN current_date AND current_date+7 AND (saas.platform_period_projection(id)->>'remainingCents')::numeric>0),'merchantSales',saas.platform_merchant_sales_projection(NULL),'currency','TRY','receivableCents',(SELECT coalesce(sum((saas.platform_period_projection(id)->>'remainingCents')::bigint),0) FROM saas.platform_billing_periods),'collectedCents',(SELECT coalesce(sum(amount_cents),0) FROM saas.platform_receipts r WHERE NOT EXISTS(SELECT 1 FROM saas.platform_receipt_reversals x WHERE x.receipt_id=r.id)),'overdueCents',(SELECT coalesce(sum((saas.platform_period_projection(id)->>'remainingCents')::bigint),0) FROM saas.platform_billing_periods WHERE due_on<current_date),'financialSetupRequired',(SELECT count(*) FROM saas.stores s WHERE NOT EXISTS(SELECT 1 FROM saas.platform_billing_periods WHERE store_id=s.id)));
 ELSE RAISE EXCEPTION 'invalid_input';END IF;RETURN envelope||jsonb_build_object('items',items);
EXCEPTION WHEN invalid_text_representation OR datetime_field_overflow OR invalid_datetime_format OR numeric_value_out_of_range THEN RAISE EXCEPTION 'invalid_input';
END $fn$;
CREATE FUNCTION saas.platform_command(p_operator uuid,p_action text,p_payload jsonb,p_expected_version bigint,p_idempotency_key text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,saas AS $fn$
DECLARE sid uuid; ver bigint; request jsonb; prior saas.platform_command_results; result jsonb; entity uuid; period saas.platform_billing_periods; receipt saas.platform_receipts; amount bigint; plan saas.plans; target saas.principals; token text; usage jsonb; feature text; limits text[]:=ARRAY['products','staff','storageBytes','monthlyOrders','customDomains']; features text[]:=ARRAY['catalog','orders','customers','content','media','analytics','checkout','custom_domains','staff_management','promotions','integrations','accounting','marketplaces']; i integer;BEGIN
 PERFORM saas.platform_operator_require_active(p_operator);
 IF p_payload IS NULL OR jsonb_typeof(p_payload)<>'object' OR pg_column_size(p_payload)>16384 OR p_expected_version IS NULL OR p_expected_version NOT BETWEEN 0 AND 9007199254740990 OR p_idempotency_key IS NULL OR length(p_idempotency_key) NOT BETWEEN 1 AND 128 OR p_idempotency_key<>btrim(p_idempotency_key) OR p_idempotency_key~'[[:cntrl:]]' THEN RAISE EXCEPTION 'invalid_input';END IF;
 request:=jsonb_build_object('action',p_action,'payload',CASE WHEN p_action='support.issue' THEN (p_payload-'handoff')||jsonb_build_object('handoffHash',encode(sha256(convert_to(p_payload->>'handoff','UTF8')),'hex')) ELSE p_payload END,'expectedVersion',p_expected_version);PERFORM pg_advisory_xact_lock(hashtextextended('platform-replay:'||p_operator::text||':'||p_idempotency_key,0));SELECT * INTO prior FROM saas.platform_command_results WHERE operator_id=p_operator AND idempotency_key=p_idempotency_key;
 IF FOUND THEN IF prior.request<>request THEN RAISE EXCEPTION 'operation_mismatch';END IF;result:=jsonb_set(prior.result,'{outcome}','"replayed"');IF p_action='support.issue' THEN result:=jsonb_set(result,'{result,handoff}',to_jsonb(p_payload->>'handoff'));END IF;RETURN result;END IF;
 IF p_action IN('support.issue','support.revoke','sales.pause','sales.resume') THEN
  IF p_action='support.issue' THEN IF p_payload-ARRAY['storeId','adminHost','host','reason','handoff']<>'{}' OR NOT(p_payload ?& ARRAY['storeId','reason','handoff']) OR NOT(p_payload ? 'adminHost' OR p_payload ? 'host') THEN RAISE EXCEPTION 'invalid_input';END IF;EXECUTE 'SELECT saas.platform_support_issue($1,$2,$3,$4,$5,$6,$7)' INTO result USING p_operator,(p_payload->>'storeId')::uuid,coalesce(p_payload->>'adminHost',p_payload->>'host'),p_payload->>'reason',p_expected_version,p_idempotency_key,p_payload->>'handoff';
  ELSIF p_action='support.revoke' THEN IF p_payload-ARRAY['sessionId']<>'{}' OR NOT(p_payload ? 'sessionId') THEN RAISE EXCEPTION 'invalid_input';END IF;EXECUTE 'SELECT saas.platform_support_revoke($1,$2,$3,$4)' INTO result USING p_operator,(p_payload->>'sessionId')::uuid,p_expected_version,p_idempotency_key;
  ELSE IF p_payload-ARRAY['storeId','reason']<>'{}' OR NOT(p_payload ?& ARRAY['storeId','reason']) THEN RAISE EXCEPTION 'invalid_input';END IF;EXECUTE 'SELECT saas.platform_sales_policy_set($1,$2,$3,$4,$5,$6)' INTO result USING p_operator,(p_payload->>'storeId')::uuid,p_action='sales.pause',p_payload->>'reason',p_expected_version,p_idempotency_key;END IF;
  result:=jsonb_build_object('outcome',CASE WHEN result->>'replayed'='true' THEN 'replayed' ELSE 'committed' END,'version',(result->>'version')::bigint,'result',result);
  INSERT INTO saas.platform_command_results(operator_id,idempotency_key,request,result) VALUES(p_operator,p_idempotency_key,request,result#-ARRAY['result','handoff']);RETURN result;
 END IF;
 IF p_action='plan.publish' THEN
  IF p_payload-ARRAY['code','features','limits','monthlyPriceCents','yearlyPriceCents']<>'{}' OR NOT(p_payload ?& ARRAY['code','features','limits']) OR jsonb_typeof(p_payload->'features')<>'object' OR jsonb_typeof(p_payload->'limits')<>'object' OR NOT(p_payload->'features' ?& features) OR (p_payload->'features')-features<>'{}' OR NOT(p_payload->'limits' ?& limits) OR (p_payload->'limits')-limits<>'{}' THEN RAISE EXCEPTION 'invalid_input';END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended('platform-plan:'||(p_payload->>'code'),0));SELECT coalesce(max(version),0) INTO ver FROM saas.plans WHERE plan_code=p_payload->>'code';IF ver<>p_expected_version THEN RAISE EXCEPTION 'version_conflict';END IF;entity:=gen_random_uuid();
  INSERT INTO saas.plans(id,plan_code,version,status,valid_from,created_at,updated_at) VALUES(entity,p_payload->>'code',ver+1,'active',now(),now(),now());INSERT INTO saas.platform_plan_publications VALUES(entity,txid_current());
  FOR i IN 1..array_length(features,1) LOOP IF jsonb_typeof(p_payload->'features'->features[i])<>'boolean' THEN RAISE EXCEPTION 'invalid_input';END IF;INSERT INTO saas.plan_features VALUES(entity,features[i],i,(p_payload->'features'->>features[i])::boolean);END LOOP;
  FOR i IN 1..array_length(limits,1) LOOP IF jsonb_typeof(p_payload->'limits'->limits[i])<>'number' OR (p_payload->'limits'->>limits[i])::numeric<>trunc((p_payload->'limits'->>limits[i])::numeric) OR (p_payload->'limits'->>limits[i])::numeric NOT BETWEEN 0 AND 9007199254740991 THEN RAISE EXCEPTION 'invalid_input';END IF;INSERT INTO saas.plan_limits(plan_id,limit_key,limit_ordinal,limit_value) VALUES(entity,limits[i],i,(p_payload->'limits'->>limits[i])::numeric);END LOOP;DELETE FROM saas.platform_plan_publications WHERE plan_id=entity;
  FOREACH feature IN ARRAY ARRAY['monthlyPriceCents','yearlyPriceCents'] LOOP IF p_payload ? feature AND p_payload->feature<>'null'::jsonb AND (jsonb_typeof(p_payload->feature)<>'number' OR (p_payload->>feature)::numeric<>trunc((p_payload->>feature)::numeric) OR (p_payload->>feature)::numeric NOT BETWEEN 0 AND 9007199254740991) THEN RAISE EXCEPTION 'invalid_input';END IF;END LOOP;
  INSERT INTO saas.platform_plan_prices VALUES(entity,(p_payload->>'monthlyPriceCents')::bigint,(p_payload->>'yearlyPriceCents')::bigint);ver:=ver+1;result:=jsonb_build_object('planId',entity);
 ELSE
  sid:=(p_payload->>'storeId')::uuid;IF NOT EXISTS(SELECT 1 FROM saas.stores WHERE id=sid) THEN RAISE EXCEPTION 'record_not_found';END IF;INSERT INTO saas.platform_store_versions(store_id) VALUES(sid) ON CONFLICT DO NOTHING;SELECT version INTO ver FROM saas.platform_store_versions WHERE store_id=sid FOR UPDATE;IF ver<>p_expected_version THEN RAISE EXCEPTION 'version_conflict';END IF;
  IF p_action='billing.period.create' THEN
   IF p_payload-ARRAY['storeId','label','startsOn','endsOn','dueOn','amountCents']<>'{}' OR NOT(p_payload ?& ARRAY['label','startsOn','endsOn','dueOn','amountCents']) THEN RAISE EXCEPTION 'invalid_input';END IF;
   IF jsonb_typeof(p_payload->'amountCents')<>'number' OR (p_payload->>'amountCents')::numeric<>trunc((p_payload->>'amountCents')::numeric) THEN RAISE EXCEPTION 'invalid_input';END IF;
   INSERT INTO saas.platform_billing_periods(store_id,label,starts_on,ends_on,due_on,amount_cents) VALUES(sid,p_payload->>'label',(p_payload->>'startsOn')::date,(p_payload->>'endsOn')::date,(p_payload->>'dueOn')::date,(p_payload->>'amountCents')::bigint) RETURNING id INTO entity;result:=jsonb_build_object('periodId',entity);
  ELSIF p_action='billing.period.adjust' THEN
   IF p_payload-ARRAY['storeId','periodId','deltaCents','reason']<>'{}' OR NOT(p_payload ?& ARRAY['periodId','deltaCents','reason']) OR jsonb_typeof(p_payload->'deltaCents')<>'number' OR (p_payload->>'deltaCents')::numeric<>trunc((p_payload->>'deltaCents')::numeric) OR (p_payload->>'deltaCents')::numeric NOT BETWEEN -9007199254740991 AND 9007199254740991 OR (p_payload->>'deltaCents')::numeric=0 OR jsonb_typeof(p_payload->'reason')<>'string' OR length(btrim(p_payload->>'reason')) NOT BETWEEN 1 AND 2000 THEN RAISE EXCEPTION 'invalid_input';END IF;
   SELECT * INTO period FROM saas.platform_billing_periods WHERE store_id=sid AND id=(p_payload->>'periodId')::uuid;IF NOT FOUND THEN RAISE EXCEPTION 'record_not_found';END IF;amount:=(p_payload->>'deltaCents')::bigint;
   IF (saas.platform_period_projection(period.id)->>'amountCents')::numeric+amount NOT BETWEEN 0 AND 9007199254740991 THEN RAISE EXCEPTION 'invalid_input';END IF;
   IF (saas.platform_period_projection(period.id)->>'remainingCents')::numeric+amount<0 THEN RAISE EXCEPTION 'charge_below_collected';END IF;
   INSERT INTO saas.platform_billing_adjustments(store_id,period_id,delta_cents,reason) VALUES(sid,period.id,amount,btrim(p_payload->>'reason')) RETURNING id INTO entity;result:=jsonb_build_object('adjustmentId',entity,'periodId',period.id);
  ELSIF p_action='billing.receipt.record' THEN
   IF p_payload-ARRAY['storeId','periodId','amountCents','method','reference']<>'{}' OR NOT(p_payload ?& ARRAY['periodId','amountCents','method','reference']) OR jsonb_typeof(p_payload->'amountCents')<>'number' OR (p_payload->>'amountCents')::numeric<>trunc((p_payload->>'amountCents')::numeric) THEN RAISE EXCEPTION 'invalid_input';END IF;
   SELECT * INTO period FROM saas.platform_billing_periods WHERE store_id=sid AND id=(p_payload->>'periodId')::uuid;IF NOT FOUND THEN RAISE EXCEPTION 'record_not_found';END IF;amount:=(p_payload->>'amountCents')::bigint;
   IF amount<1 OR amount>(saas.platform_period_projection(period.id)->>'remainingCents')::bigint THEN RAISE EXCEPTION 'overpayment';END IF;INSERT INTO saas.platform_receipts(store_id,period_id,amount_cents,method,reference) VALUES(sid,period.id,amount,p_payload->>'method',p_payload->>'reference') RETURNING id INTO entity;result:=jsonb_build_object('receiptId',entity,'periodId',period.id);
  ELSIF p_action='billing.receipt.reverse' THEN
   IF p_payload-ARRAY['storeId','receiptId','reason']<>'{}' OR NOT(p_payload ?& ARRAY['receiptId','reason']) THEN RAISE EXCEPTION 'invalid_input';END IF;SELECT * INTO receipt FROM saas.platform_receipts WHERE store_id=sid AND id=(p_payload->>'receiptId')::uuid;IF NOT FOUND THEN RAISE EXCEPTION 'record_not_found';END IF;IF EXISTS(SELECT 1 FROM saas.platform_receipt_reversals WHERE receipt_id=receipt.id) THEN RAISE EXCEPTION 'already_reversed';END IF;INSERT INTO saas.platform_receipt_reversals(store_id,receipt_id,reason) VALUES(sid,receipt.id,p_payload->>'reason') RETURNING id INTO entity;result:=jsonb_build_object('reversalId',entity,'periodId',receipt.period_id);
  ELSIF p_action='subscription.assign' THEN
   IF p_payload-ARRAY['storeId','planId']<>'{}' OR NOT(p_payload ? 'planId') THEN RAISE EXCEPTION 'invalid_input';END IF;SELECT * INTO plan FROM saas.plans WHERE id=(p_payload->>'planId')::uuid AND status='active' AND valid_from<=now() AND (valid_until IS NULL OR valid_until>now());IF NOT FOUND THEN RAISE EXCEPTION 'record_not_found';END IF;
   usage:=saas.platform_store_usage(sid);FOR i IN 1..array_length(limits,1) LOOP IF NOT EXISTS(SELECT 1 FROM saas.plan_limits WHERE plan_id=plan.id AND limit_key=limits[i] AND effective_limit>=(usage->>limits[i])::bigint) THEN RAISE EXCEPTION 'limit_below_usage';END IF;END LOOP;
   IF EXISTS(SELECT 1 FROM saas.in_store_sales WHERE store_id=sid AND status IN('payment_pending','payment_received')) THEN FOREACH feature IN ARRAY ARRAY['orders','checkout','catalog'] LOOP IF NOT EXISTS(SELECT 1 FROM saas.plan_features WHERE plan_id=plan.id AND feature_key=feature AND enabled) THEN RAISE EXCEPTION 'pending_pos_blocks_downgrade';END IF;END LOOP;END IF;
   IF (EXISTS(SELECT 1 FROM saas.accounting_receivables WHERE store_id=sid AND sale_cents-return_cents-collected_cents>0) OR EXISTS(SELECT 1 FROM saas.in_store_sales WHERE store_id=sid AND status IN('payment_pending','payment_received') AND contract_version=3 AND initial_collection_cents<total_cents)) AND NOT EXISTS(SELECT 1 FROM saas.plan_features WHERE plan_id=plan.id AND feature_key='accounting' AND enabled) THEN RAISE EXCEPTION 'open_debt_blocks_downgrade';END IF;
   UPDATE saas.subscriptions SET status='inactive',updated_at=greatest(clock_timestamp(),updated_at) WHERE store_id=sid AND status='active';INSERT INTO saas.subscriptions(id,store_id,plan_id,plan_code,plan_version,status,valid_from,created_at,updated_at) VALUES(gen_random_uuid(),sid,plan.id,plan.plan_code,plan.version,'active',now(),now(),now()) RETURNING id INTO entity;result:=jsonb_build_object('subscriptionId',entity,'planId',plan.id);
  ELSIF p_action='membership.update' THEN
   IF p_payload-ARRAY['storeId','membershipId','role','status']<>'{}' OR NOT(p_payload ?& ARRAY['membershipId','role','status']) OR p_payload->>'role' NOT IN('store_owner','admin','editor','analyst','cashier') OR p_payload->>'status' NOT IN('active','invited','revoked') THEN RAISE EXCEPTION 'invalid_input';END IF;
   IF NOT EXISTS(SELECT 1 FROM saas.memberships m WHERE store_id=sid AND id=(p_payload->>'membershipId')::uuid AND coalesce(to_jsonb(m)->>'support_session_id','')='') THEN RAISE EXCEPTION 'record_not_found';END IF;
   IF p_payload->>'role'='store_owner' AND NOT EXISTS(SELECT 1 FROM saas.memberships WHERE id=(p_payload->>'membershipId')::uuid AND role='store_owner' AND status='active') THEN RAISE EXCEPTION 'ownership_acceptance_required';END IF;
   IF p_payload->>'status'='active' AND EXISTS(SELECT 1 FROM saas.memberships WHERE id=(p_payload->>'membershipId')::uuid AND status='invited') THEN RAISE EXCEPTION 'invitation_acceptance_required';END IF;
   IF p_payload->>'role'<>'store_owner' AND p_payload->>'status'='active' AND EXISTS(SELECT 1 FROM saas.memberships WHERE id=(p_payload->>'membershipId')::uuid AND (role='store_owner' OR status<>'active')) AND NOT EXISTS(SELECT 1 FROM saas.plan_limits l JOIN saas.subscriptions sub ON sub.plan_id=l.plan_id WHERE sub.store_id=sid AND sub.status='active' AND l.limit_key='staff' AND l.effective_limit>(saas.platform_store_usage(sid)->>'staff')::bigint) THEN RAISE EXCEPTION 'staff_limit_reached';END IF;
   UPDATE saas.memberships SET role=p_payload->>'role',status=p_payload->>'status',updated_at=greatest(clock_timestamp(),updated_at) WHERE id=(p_payload->>'membershipId')::uuid AND store_id=sid RETURNING id INTO entity;result:=jsonb_build_object('membershipId',entity);
  ELSIF p_action='ownership.invite' THEN
   IF p_payload-ARRAY['storeId','targetPrincipalId','role','kind','previousOwnerDisposition']<>'{}' OR NOT(p_payload ?& ARRAY['targetPrincipalId','role','kind']) THEN RAISE EXCEPTION 'invalid_input';END IF;SELECT * INTO target FROM saas.principals WHERE id=(p_payload->>'targetPrincipalId')::uuid AND email_verified;IF NOT FOUND THEN RAISE EXCEPTION 'verified_identity_required';END IF;token:=gen_random_uuid()::text||gen_random_uuid()::text;
   INSERT INTO saas.platform_ownership_invitations(store_id,target_principal_id,target_issuer,target_subject,role,kind,previous_owner_disposition,created_by,token_hash,expires_at) VALUES(sid,target.id,target.issuer,target.subject,p_payload->>'role',p_payload->>'kind',p_payload->>'previousOwnerDisposition',p_operator,sha256(convert_to(token,'UTF8')),now()+interval '7 days') RETURNING id INTO entity;result:=jsonb_build_object('invitationId',entity,'acceptanceToken',token,'expiresAt',now()+interval '7 days');
  ELSE RAISE EXCEPTION 'invalid_input';END IF;
  ver:=ver+1;UPDATE saas.platform_store_versions SET version=ver WHERE store_id=sid;
 END IF;
 INSERT INTO saas.platform_audit(operator_id,store_id,action,payload) VALUES(p_operator,sid,p_action,p_payload);
 result:=jsonb_build_object('outcome','committed','version',ver,'result',result);INSERT INTO saas.platform_command_results(operator_id,idempotency_key,request,result) VALUES(p_operator,p_idempotency_key,request,result);RETURN result;
EXCEPTION WHEN invalid_text_representation OR datetime_field_overflow OR invalid_datetime_format OR numeric_value_out_of_range OR check_violation OR not_null_violation THEN RAISE EXCEPTION 'invalid_input';
END $fn$;
-- Trusted identity server calls this only after verifying issuer/subject. Invitation freezes that identity at creation.
CREATE FUNCTION saas.platform_ownership_accept(p_token text,p_issuer text,p_subject text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,saas AS $fn$
DECLARE invite saas.platform_ownership_invitations; ver bigint; mid uuid; current_plan uuid; desired_staff bigint;BEGIN
 IF p_token IS NULL OR length(p_token)<>72 THEN RAISE EXCEPTION 'invalid_input';END IF;
 SELECT * INTO invite FROM saas.platform_ownership_invitations WHERE token_hash=sha256(convert_to(p_token,'UTF8')) FOR UPDATE;IF NOT FOUND OR invite.expires_at<=now() OR invite.target_issuer<>p_issuer OR invite.target_subject<>p_subject THEN RAISE EXCEPTION 'invitation_denied';END IF;
 PERFORM saas.platform_operator_require_active(invite.created_by);IF NOT EXISTS(SELECT 1 FROM saas.principals WHERE id=invite.target_principal_id AND issuer=p_issuer AND subject=p_subject AND email_verified) THEN RAISE EXCEPTION 'verified_identity_required';END IF;
 IF invite.accepted_at IS NOT NULL THEN RETURN jsonb_build_object('outcome','replayed','storeId',invite.store_id);END IF;
 INSERT INTO saas.platform_store_versions(store_id) VALUES(invite.store_id) ON CONFLICT DO NOTHING;SELECT version INTO ver FROM saas.platform_store_versions WHERE store_id=invite.store_id FOR UPDATE;PERFORM pg_advisory_xact_lock(hashtextextended('platform-owner:'||invite.store_id::text,0));
 SELECT plan_id INTO current_plan FROM saas.subscriptions WHERE store_id=invite.store_id AND status='active';
 desired_staff:=(saas.platform_store_usage(invite.store_id)->>'staff')::bigint-(SELECT count(*) FROM saas.memberships m WHERE store_id=invite.store_id AND principal_id=invite.target_principal_id AND status='active' AND role<>'store_owner' AND coalesce(to_jsonb(m)->>'support_session_id','')='')+CASE WHEN invite.role='store_owner' THEN 0 ELSE 1 END;
 IF invite.kind='transfer' AND invite.previous_owner_disposition='admin' THEN desired_staff:=desired_staff+(SELECT count(*) FROM saas.memberships WHERE store_id=invite.store_id AND principal_id<>invite.target_principal_id AND role='store_owner' AND status='active');END IF;
 IF desired_staff>0 AND NOT EXISTS(SELECT 1 FROM saas.plan_limits WHERE plan_id=current_plan AND limit_key='staff' AND effective_limit>=desired_staff) THEN RAISE EXCEPTION 'staff_limit_reached';END IF;
 IF EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid='saas.memberships'::regclass AND attname='support_session_id' AND NOT attisdropped) THEN
 EXECUTE 'INSERT INTO saas.memberships(id,principal_id,store_id,role,status,created_at,updated_at) VALUES(gen_random_uuid(),$1,$2,$3,''active'',now(),now()) ON CONFLICT(principal_id,store_id) WHERE support_session_id IS NULL DO UPDATE SET role=excluded.role,status=''active'',updated_at=greatest(clock_timestamp(),saas.memberships.updated_at) RETURNING id' INTO mid USING invite.target_principal_id,invite.store_id,invite.role;
 ELSE INSERT INTO saas.memberships(id,principal_id,store_id,role,status,created_at,updated_at) VALUES(gen_random_uuid(),invite.target_principal_id,invite.store_id,invite.role,'active',now(),now()) ON CONFLICT(principal_id,store_id) DO UPDATE SET role=excluded.role,status='active',updated_at=greatest(clock_timestamp(),saas.memberships.updated_at) RETURNING id INTO mid; END IF;
 IF invite.kind='transfer' THEN UPDATE saas.memberships SET role=CASE WHEN invite.previous_owner_disposition='admin' THEN 'admin' ELSE role END,status=CASE WHEN invite.previous_owner_disposition='revoked' THEN 'revoked' ELSE 'active' END,updated_at=greatest(clock_timestamp(),updated_at) WHERE store_id=invite.store_id AND principal_id<>invite.target_principal_id AND role='store_owner' AND status='active';END IF;
 UPDATE saas.platform_ownership_invitations SET accepted_at=clock_timestamp() WHERE id=invite.id;UPDATE saas.platform_store_versions SET version=version+1 WHERE store_id=invite.store_id;
 INSERT INTO saas.platform_audit(operator_id,store_id,action,payload) VALUES(invite.created_by,invite.store_id,'ownership.accept',jsonb_build_object('invitationId',invite.id,'principalId',invite.target_principal_id,'membershipId',mid,'previousOwnerDisposition',invite.previous_owner_disposition));RETURN jsonb_build_object('outcome','committed','storeId',invite.store_id,'membershipId',mid,'version',ver+1);
END $fn$;
CREATE FUNCTION saas.platform_ownership_accept_context(p_store uuid,p_principal uuid,p_membership uuid,p_plan uuid,p_code text,p_version bigint,p_now timestamptz,p_token text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,saas AS $fn$
DECLARE principal saas.principals;BEGIN
 IF p_now IS NULL OR abs(extract(epoch FROM clock_timestamp()-p_now))>60 OR NOT EXISTS(SELECT 1 FROM saas.memberships m JOIN saas.stores s ON s.id=m.store_id JOIN saas.subscriptions sub ON sub.store_id=s.id WHERE s.id=p_store AND s.status='active' AND m.id=p_membership AND m.principal_id=p_principal AND m.status='active' AND coalesce(to_jsonb(m)->>'support_session_id','')='' AND sub.status='active' AND sub.plan_id=p_plan AND sub.plan_code=p_code AND sub.plan_version=p_version AND sub.valid_from<=clock_timestamp() AND (sub.valid_until IS NULL OR sub.valid_until>clock_timestamp())) THEN RAISE EXCEPTION 'membership_denied' USING ERRCODE='42501';END IF;
 SELECT * INTO principal FROM saas.principals WHERE id=p_principal AND email_verified;IF NOT FOUND THEN RAISE EXCEPTION 'verified_identity_required';END IF;RETURN saas.platform_ownership_accept(p_token,principal.issuer,principal.subject);
END $fn$;
DO $acl$ DECLARE f regprocedure;BEGIN FOR f IN SELECT p.oid::regprocedure FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='saas' AND (p.proname LIKE 'platform_%' OR p.proname='reject_plan_version_mutation') LOOP EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,celebix_saas_app,celebix_saas_identity,celebix_saas_workflow,celebix_saas_bootstrap,celebix_saas_platform_operator',f);END LOOP;END $acl$;
GRANT EXECUTE ON FUNCTION saas.platform_read(uuid,text,jsonb),saas.platform_command(uuid,text,jsonb,bigint,text),saas.platform_operator_resolve(text,text) TO celebix_saas_platform_operator;
GRANT EXECUTE ON FUNCTION saas.platform_ownership_accept_context(uuid,uuid,uuid,uuid,text,bigint,timestamptz,text) TO celebix_saas_app;
GRANT EXECUTE ON FUNCTION saas.platform_ownership_accept(text,text,text) TO celebix_saas_identity;
COMMIT;
