-- Manual sales V4. New writes remain disabled until both reader applications are released.
BEGIN;
SET LOCAL ROLE celebix_saas_owner;
CREATE TABLE saas.manual_sales_v4_restore(signature text PRIMARY KEY,definition text NOT NULL,before_hash text NOT NULL,after_hash text);
ALTER TABLE saas.manual_sales_v4_restore ENABLE ROW LEVEL SECURITY;
ALTER TABLE saas.manual_sales_v4_restore FORCE ROW LEVEL SECURITY;
CREATE POLICY manual_sales_v4_restore_owner ON saas.manual_sales_v4_restore TO celebix_saas_owner USING(true) WITH CHECK(true);
REVOKE ALL ON saas.manual_sales_v4_restore FROM PUBLIC,celebix_saas_app,celebix_saas_identity,celebix_saas_workflow,celebix_saas_migrator;
INSERT INTO saas.manual_sales_v4_restore SELECT p.oid::regprocedure::text,pg_get_functiondef(p.oid),md5(pg_get_functiondef(p.oid)),NULL FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='saas' AND p.proname IN('in_store_sales_mutate','in_store_sales_mutate_v2','in_store_sales_mutate_v3','in_store_sales_get','in_store_sales_get_v2','in_store_sales_get_v3','in_store_sales_list','in_store_sales_list_v2','in_store_sales_list_v3','in_store_sales_bootstrap','in_store_sales_bootstrap_v2','in_store_sales_bootstrap_v3','in_store_sales_get_operation','in_store_sales_get_operation_v2','in_store_sales_get_operation_v3','in_store_credit_snapshot_guard','in_store_order_guard','orders_transition_status','orders_update_shipping','accounting_filters_valid','accounting_read','accounting_mutate','accounting_customer_projection');
ALTER TABLE saas.accounting_release_state ADD COLUMN manual_sales_v4_enabled boolean NOT NULL DEFAULT false;
ALTER TABLE saas.in_store_sales DROP CONSTRAINT in_store_v3_contract_version,DROP CONSTRAINT in_store_v3_payment_stage,DROP CONSTRAINT in_store_sales_lifecycle,DROP CONSTRAINT in_store_sales_check1,
 ADD COLUMN sales_channel text NOT NULL DEFAULT 'manual' CHECK(sales_channel IN('manual','social')),
 ADD COLUMN social_platform text CHECK(social_platform IN('instagram','facebook','x','pinterest','tiktok','whatsapp','other')),
 ADD COLUMN social_reference text CHECK(social_reference IS NULL OR length(social_reference) BETWEEN 1 AND 500),
 ADD COLUMN fulfillment_method text NOT NULL DEFAULT 'pickup' CHECK(fulfillment_method IN('pickup','shipping')),
 ADD COLUMN shipping_address jsonb,ADD COLUMN billing_address jsonb,
 ADD COLUMN shipping_cents bigint NOT NULL DEFAULT 0 CHECK(shipping_cents BETWEEN 0 AND 9007199254740991),
 ADD COLUMN payment_parts jsonb NOT NULL DEFAULT '[]' CHECK(jsonb_typeof(payment_parts)='array'),
 ADD COLUMN prepare_operation_id uuid,ADD COLUMN payment_plan_version bigint,ADD COLUMN abort_requested boolean NOT NULL DEFAULT false,
 ADD COLUMN accounting_receivable_id uuid,
 ADD CONSTRAINT in_store_v4_contract_version CHECK(contract_version IN(1,2,3,4)),
 ADD CONSTRAINT in_store_v4_total CHECK(total_cents=subtotal_cents-discount_cents+shipping_cents AND total_cents BETWEEN 0 AND 9007199254740991),
 ADD CONSTRAINT in_store_v4_payment_stage CHECK(contract_version IN(1,4) OR status NOT IN('payment_pending','payment_received','completed') OR payment_method IS NOT NULL OR contract_version=3 AND initial_collection_cents=0),
 ADD CONSTRAINT in_store_sales_lifecycle CHECK((status IN('draft','held','payment_pending','cancelled') AND payment_received_at IS NULL AND completed_at IS NULL AND order_id IS NULL AND order_number IS NULL) OR(status='payment_received' AND payment_received_at IS NOT NULL AND completed_at IS NULL AND order_id IS NULL AND order_number IS NULL) OR(status='completed' AND (payment_received_at IS NOT NULL OR contract_version IN(3,4) AND initial_collection_cents=0) AND completed_at IS NOT NULL AND order_number IS NOT NULL)),
 ADD CONSTRAINT in_store_v4_receivable FOREIGN KEY(store_id,accounting_receivable_id) REFERENCES saas.accounting_receivables(store_id,id);
CREATE TABLE saas.in_store_payment_receipts_v4(
 id uuid PRIMARY KEY,store_id uuid NOT NULL,sale_id uuid NOT NULL,part_id uuid NOT NULL,prepare_operation_id uuid NOT NULL,
 operation_id uuid NOT NULL UNIQUE,actor_membership_id uuid NOT NULL,amount_cents bigint NOT NULL CHECK(amount_cents BETWEEN 1 AND 9007199254740991),payment_method text NOT NULL CHECK(payment_method IN('cash','card','bank_transfer')),slip_reference text,
 received_at timestamptz NOT NULL,event_id uuid NOT NULL UNIQUE,account_id uuid NOT NULL,
 UNIQUE(store_id,id),UNIQUE(store_id,sale_id,part_id),FOREIGN KEY(store_id,sale_id) REFERENCES saas.in_store_sales(store_id,id),FOREIGN KEY(store_id,actor_membership_id) REFERENCES saas.memberships(store_id,id),FOREIGN KEY(store_id,event_id) REFERENCES saas.accounting_events(store_id,id),FOREIGN KEY(store_id,account_id) REFERENCES saas.accounting_accounts(store_id,id));
CREATE TABLE saas.in_store_payment_returns_v4(
 receipt_id uuid PRIMARY KEY,store_id uuid NOT NULL,event_id uuid NOT NULL UNIQUE,operation_id uuid NOT NULL UNIQUE,actor_membership_id uuid NOT NULL,returned_at timestamptz NOT NULL,reason text NOT NULL CHECK(length(reason) BETWEEN 1 AND 2000),
 FOREIGN KEY(store_id,receipt_id) REFERENCES saas.in_store_payment_receipts_v4(store_id,id),FOREIGN KEY(store_id,event_id) REFERENCES saas.accounting_events(store_id,id),FOREIGN KEY(store_id,actor_membership_id) REFERENCES saas.memberships(store_id,id));
CREATE TABLE saas.in_store_obsolete_payment_reconciliations_v4(operation_id uuid PRIMARY KEY,store_id uuid NOT NULL,sale_id uuid NOT NULL,original_operation_id uuid NOT NULL UNIQUE,prepare_operation_id uuid NOT NULL,part_id uuid NOT NULL,amount_cents bigint NOT NULL CHECK(amount_cents>0),payment_method text NOT NULL CHECK(payment_method IN('cash','card','bank_transfer')),actor_membership_id uuid NOT NULL,reconciled_at timestamptz NOT NULL,reason text NOT NULL CHECK(reason='physical_return_confirmed'),FOREIGN KEY(store_id,sale_id) REFERENCES saas.in_store_sales(store_id,id),FOREIGN KEY(store_id,actor_membership_id) REFERENCES saas.memberships(store_id,id));
DO $tables$ DECLARE t text;BEGIN FOREACH t IN ARRAY ARRAY['in_store_payment_receipts_v4','in_store_payment_returns_v4','in_store_obsolete_payment_reconciliations_v4'] LOOP EXECUTE format('ALTER TABLE saas.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE saas.%I FORCE ROW LEVEL SECURITY',t);EXECUTE format('CREATE POLICY manual_sales_v4_owner ON saas.%I TO celebix_saas_owner USING(true) WITH CHECK(true)',t);EXECUTE format('REVOKE ALL ON saas.%I FROM PUBLIC,celebix_saas_app,celebix_saas_identity,celebix_saas_workflow,celebix_saas_migrator',t);EXECUTE format('CREATE TRIGGER manual_sales_v4_immutable BEFORE UPDATE OR DELETE ON saas.%I FOR EACH ROW EXECUTE FUNCTION saas.accounting_immutable()',t);END LOOP;END $tables$;
CREATE FUNCTION saas.in_store_payment_parts_valid_v4(p_parts jsonb) RETURNS boolean LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,saas AS $f$
DECLARE part jsonb;BEGIN
 IF p_parts IS NULL OR jsonb_typeof(p_parts)<>'array' OR jsonb_array_length(p_parts)>100 THEN RETURN false;END IF;
 FOR part IN SELECT value FROM jsonb_array_elements(p_parts) LOOP
 IF jsonb_typeof(part)<>'object' OR (SELECT count(*) FROM jsonb_object_keys(part))<>3 OR NOT(part?&ARRAY['partId','paymentMethod','amountCents']) OR jsonb_typeof(part->'partId')<>'string' OR part->>'partId'!~'^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$' OR jsonb_typeof(part->'paymentMethod')<>'string' OR part->>'paymentMethod' NOT IN('cash','card','bank_transfer') OR jsonb_typeof(part->'amountCents')<>'number' OR (part->>'amountCents')::numeric<>trunc((part->>'amountCents')::numeric) OR (part->>'amountCents')::numeric NOT BETWEEN 1 AND 9007199254740991 THEN RETURN false;END IF;
 END LOOP;
 RETURN jsonb_array_length(p_parts)=(SELECT count(DISTINCT value->>'partId') FROM jsonb_array_elements(p_parts)) AND coalesce((SELECT sum((value->>'amountCents')::numeric) FROM jsonb_array_elements(p_parts)),0)<=9007199254740991;
 EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN RETURN false;
END $f$;
CREATE FUNCTION saas.in_store_address_valid_v4(p_address jsonb) RETURNS boolean LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,saas AS $f$
DECLARE k text;v jsonb;BEGIN IF p_address IS NULL OR jsonb_typeof(p_address)<>'object' OR NOT(p_address?&ARRAY['recipientName','line1','city','country']) THEN RETURN false;END IF;
 FOR k,v IN SELECT key,value FROM jsonb_each(p_address) LOOP IF k NOT IN('recipientName','line1','line2','district','city','postalCode','country') OR jsonb_typeof(v)<>'string' OR length(v#>>'{}') NOT BETWEEN 1 AND (CASE WHEN k IN('line1','line2') THEN 300 WHEN k='postalCode' THEN 32 WHEN k='country' THEN 2 ELSE 200 END) OR v#>>'{}'<>btrim(v#>>'{}') OR v#>>'{}'~'[[:cntrl:]]' THEN RETURN false;END IF;END LOOP;RETURN p_address->>'country'~'^[A-Z]{2}$';END $f$;
CREATE FUNCTION saas.in_store_quote_v4(p_store uuid,p_member uuid,p_now timestamptz,p_intent jsonb,p_existing jsonb DEFAULT '[]') RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
DECLARE r record;selected saas.customers%ROWTYPE;snapshot jsonb;initial bigint;shipping bigint;due date;base jsonb;method text;parts jsonb;old_total bigint;new_total bigint;BEGIN
 IF p_intent IS NULL OR jsonb_typeof(p_intent)<>'object' OR (SELECT count(*) FROM jsonb_object_keys(p_intent))<>15 OR NOT(p_intent?&ARRAY['locationId','items','discount','customerName','note','customerId','dueDate','paymentParts','salesChannel','socialPlatform','socialReference','fulfillmentMethod','shippingAddress','billingAddress','shippingCents']) OR pg_column_size(p_intent)>65536 OR NOT saas.in_store_payment_parts_valid_v4(p_intent->'paymentParts') THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;
 IF p_intent->>'salesChannel' IS NULL OR p_intent->>'fulfillmentMethod' IS NULL OR p_intent->>'salesChannel' NOT IN('manual','social') OR p_intent->>'fulfillmentMethod' NOT IN('pickup','shipping') OR p_intent->>'salesChannel'='manual' AND (p_intent->>'socialPlatform' IS NOT NULL OR p_intent->>'socialReference' IS NOT NULL) OR p_intent->>'salesChannel'='social' AND (p_intent->>'socialPlatform' IS NULL OR p_intent->>'socialPlatform' NOT IN('instagram','facebook','x','pinterest','tiktok','whatsapp','other')) OR p_intent->>'socialReference' IS NOT NULL AND (jsonb_typeof(p_intent->'socialReference')<>'string' OR length(p_intent->>'socialReference') NOT BETWEEN 1 AND 500 OR p_intent->>'socialReference'<>btrim(p_intent->>'socialReference') OR p_intent->>'socialReference'~'[[:cntrl:]]') THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;
 IF p_intent->>'shippingCents' IS NULL OR jsonb_typeof(p_intent->'shippingCents')<>'number' OR (p_intent->>'shippingCents')::numeric<>trunc((p_intent->>'shippingCents')::numeric) OR (p_intent->>'shippingCents')::numeric NOT BETWEEN 0 AND 9007199254740991 THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;shipping:=(p_intent->>'shippingCents')::bigint;
 IF p_intent->>'fulfillmentMethod'='pickup' AND (shipping<>0 OR p_intent->>'shippingAddress' IS NOT NULL OR p_intent->>'billingAddress' IS NOT NULL) OR p_intent->>'fulfillmentMethod'='shipping' AND (NOT saas.in_store_address_valid_v4(p_intent->'shippingAddress') OR p_intent->>'billingAddress' IS NOT NULL AND NOT saas.in_store_address_valid_v4(p_intent->'billingAddress')) THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;
 IF p_intent->>'customerId' IS NOT NULL THEN IF jsonb_typeof(p_intent->'customerId')<>'string' OR p_intent->>'customerId'!~'^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$' THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;SELECT * INTO selected FROM saas.customers WHERE store_id=p_store AND id=(p_intent->>'customerId')::uuid;IF NOT FOUND THEN RETURN QUERY SELECT 'not_found',NULL::jsonb;RETURN;END IF;IF selected.status<>'active' OR selected.archived_at IS NOT NULL THEN RETURN QUERY SELECT 'customer_archived',NULL::jsonb;RETURN;END IF;snapshot:=saas.in_store_pos_customer_projection(selected);END IF;
 IF p_intent->>'customerName' IS NOT NULL AND (jsonb_typeof(p_intent->'customerName')<>'string' OR length(p_intent->>'customerName') NOT BETWEEN 1 AND (CASE WHEN p_intent->>'customerId' IS NULL THEN 200 ELSE 201 END) OR p_intent->>'customerName'<>btrim(p_intent->>'customerName') OR p_intent->>'customerName'~'[[:cntrl:]]') THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;
 IF p_intent->>'dueDate' IS NOT NULL THEN IF p_intent->>'dueDate'!~'^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;due:=(p_intent->>'dueDate')::date;IF due::text<>p_intent->>'dueDate' THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;END IF;
 SELECT CASE WHEN count(DISTINCT value->>'paymentMethod')=1 THEN min(value->>'paymentMethod') ELSE NULL END,coalesce(sum((value->>'amountCents')::bigint),0) INTO method,initial FROM jsonb_array_elements(p_intent->'paymentParts');
 base:=jsonb_build_object('locationId',p_intent->'locationId','items',p_intent->'items','discount',p_intent->'discount','customerName',CASE WHEN snapshot IS NULL THEN p_intent->'customerName' ELSE 'null'::jsonb END,'note',p_intent->'note','paymentMethod',CASE WHEN method='bank_transfer' THEN 'cash' ELSE method END);
 SELECT * INTO r FROM saas.in_store_quote_v2(p_store,p_member,p_now,base,p_existing);IF r.outcome<>'found' THEN RETURN QUERY SELECT r.outcome::text,NULL::jsonb;RETURN;END IF;
 IF (r.result_payload->>'totalCents')::numeric+shipping>9007199254740991 THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;
 new_total:=(r.result_payload->>'totalCents')::bigint+shipping;parts:=p_intent->'paymentParts';
 SELECT coalesce(sum((value->>'lineNetCents')::bigint),0)+shipping INTO old_total FROM jsonb_array_elements(p_existing);
 IF new_total>0 AND jsonb_array_length(p_existing)>0 AND jsonb_array_length(parts)=1 AND initial=old_total AND new_total<>old_total THEN parts:=jsonb_set(parts,'{0,amountCents}',to_jsonb(new_total));initial:=new_total;
 ELSIF initial>new_total AND jsonb_array_length(p_existing)>0 AND p_existing IS DISTINCT FROM r.result_payload->'items' THEN parts:='[]';initial:=0;method:=NULL;
 ELSIF initial>new_total THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;
 RETURN QUERY SELECT 'found',r.result_payload||jsonb_build_object('totalCents',(r.result_payload->>'totalCents')::bigint+shipping,'shippingCents',shipping,'paymentParts',parts,'customer',snapshot,'initialCollectionCents',initial,'paymentMethod',method,'dueDate',due);
 EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range OR datetime_field_overflow THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;
END $f$;
CREATE FUNCTION saas.in_store_projection_v4_value(p_sale jsonb) RETURNS jsonb LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,saas AS $f$
 SELECT CASE WHEN p_sale IS NULL THEN NULL ELSE saas.in_store_projection_v3_value(p_sale)||jsonb_build_object('salesChannel',coalesce(p_sale->'salesChannel','"manual"'),'socialPlatform',p_sale->'socialPlatform','socialReference',p_sale->'socialReference','fulfillmentMethod',coalesce(p_sale->'fulfillmentMethod','"pickup"'),'shippingAddress',p_sale->'shippingAddress','billingAddress',p_sale->'billingAddress','shippingCents',coalesce(p_sale->'shippingCents','0'),'paymentParts',coalesce(p_sale->'paymentParts','[]'),'prepareOperationId',p_sale->'prepareOperationId','abortRequested',coalesce(p_sale->'abortRequested','false'),'totals',(p_sale->'totals')||jsonb_build_object('shippingCents',coalesce(p_sale->'shippingCents','0'))) END
$f$;
CREATE FUNCTION saas.in_store_sales_projection_v4(p_store uuid,p_sale uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
 SELECT saas.in_store_projection_v4_value(saas.in_store_sales_projection_v3(p_store,p_sale)||jsonb_build_object('salesChannel',s.sales_channel,'socialPlatform',s.social_platform,'socialReference',s.social_reference,'fulfillmentMethod',s.fulfillment_method,'shippingAddress',s.shipping_address,'billingAddress',s.billing_address,'shippingCents',s.shipping_cents,'prepareOperationId',s.prepare_operation_id,'abortRequested',s.abort_requested,'finance',CASE WHEN s.status='completed' THEN saas.accounting_order_finance(p_store,s.order_id) ELSE NULL END,'paymentParts',coalesce((SELECT jsonb_agg(part||jsonb_build_object('receiptId',receipt.id,'receivedAt',saas.orders_json_timestamp(receipt.received_at),'actorMembershipId',receipt.actor_membership_id,'refundEventId',returned.event_id,'returnedAt',saas.orders_json_timestamp(returned.returned_at)) ORDER BY ordinal) FROM jsonb_array_elements(s.payment_parts) WITH ORDINALITY plan(part,ordinal) LEFT JOIN saas.in_store_payment_receipts_v4 receipt ON receipt.store_id=s.store_id AND receipt.sale_id=s.id AND receipt.part_id=(part->>'partId')::uuid LEFT JOIN saas.in_store_payment_returns_v4 returned ON returned.store_id=receipt.store_id AND returned.receipt_id=receipt.id),'[]'))) FROM saas.in_store_sales s WHERE s.store_id=p_store AND s.id=p_sale
$f$;
CREATE FUNCTION saas.accounting_post_pos_sale_v4(p_store uuid,p_sale uuid,p_order uuid,p_operation uuid,p_actor uuid,p_now timestamptz) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
DECLARE sale saas.in_store_sales%ROWTYPE;receivable uuid;event uuid;receipt record;BEGIN
 PERFORM pg_advisory_xact_lock(hashtextextended('saas.accounting.store:'||p_store::text,0));SELECT * INTO STRICT sale FROM saas.in_store_sales WHERE store_id=p_store AND id=p_sale;
 IF sale.contract_version<>4 OR sale.abort_requested OR NOT EXISTS(SELECT 1 FROM saas.orders WHERE store_id=p_store AND id=p_order AND source='in_store' AND total_cents=sale.total_cents) THEN RAISE EXCEPTION 'ACCOUNTING_POS_V4_INVALID';END IF;
 receivable:=saas.inventory_deterministic_uuid('accounting','saas.accounting.receivable:'||p_store::text||':'||p_order::text);event:=saas.inventory_deterministic_uuid('accounting','saas.accounting.sale:'||p_operation::text);
 INSERT INTO saas.accounting_receivables(id,store_id,customer_id,customer_snapshot,order_id,channel,currency,sale_cents,collected_cents,occurred_at,due_date) VALUES(receivable,p_store,sale.customer_id,coalesce(sale.customer_snapshot,'{}'),p_order,'POS','TRY',sale.total_cents,sale.initial_collection_cents,p_now,sale.due_date);
 INSERT INTO saas.accounting_events(id,store_id,operation_id,kind,currency,amount_cents,customer_id,order_id,channel,actor_membership_id,occurred_at,created_at,metadata) VALUES(event,p_store,p_operation,'sale','TRY',sale.total_cents,sale.customer_id,p_order,'POS',p_actor,p_now,p_now,jsonb_build_object('saleId',p_sale,'salesChannel',sale.sales_channel));
 FOR receipt IN SELECT r.* FROM saas.in_store_payment_receipts_v4 r WHERE r.store_id=p_store AND r.sale_id=p_sale LOOP INSERT INTO saas.accounting_allocations VALUES(p_store,receipt.event_id,receivable,'collect',receipt.amount_cents);END LOOP;
 UPDATE saas.in_store_sales SET accounting_receivable_id=receivable WHERE store_id=p_store AND id=p_sale;
 PERFORM saas.accounting_bump_customer(p_store,sale.customer_id,'TRY');PERFORM saas.accounting_sync_order(p_store,p_order,p_now);RETURN saas.accounting_order_finance(p_store,p_order);
END $f$;

-- Clone the CURRENT V3 body (including platform support and discard217), then apply exact reviewed anchors.
DO $v4$ DECLARE definition text;before text;BEGIN
 definition:=pg_get_functiondef('saas.in_store_sales_mutate_v3(uuid,uuid,uuid,uuid,text,bigint,timestamptz,uuid,text,uuid,bigint,text,jsonb)'::regprocedure);
 definition:=replace(replace(replace(definition,'in_store_sales_mutate_v3','in_store_sales_mutate_v4'),'in_store_sales_projection_v3','in_store_sales_projection_v4'),'in_store_quote_v3','in_store_quote_v4');
 before:=definition;definition:=replace(definition,$old$'confirm_payment','complete'$old$,$new$'confirm_payment','complete','revise_payments','abort','return_payment','reconcile_payment'$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','''confirm_payment'',''complete'',''cancel'',''takeover''';END IF;
 before:=definition;definition:=replace(definition,$old$position integer:=0; selected_location uuid;$old$,$new$position integer:=0; selected_location uuid; part jsonb; receipt_v4 saas.in_store_payment_receipts_v4%ROWTYPE; customer_v4 saas.customers%ROWTYPE; account_v4 uuid; event_v4 uuid; receipt_id_v4 uuid; initial_v4 bigint; method_v4 text; parts_v4 jsonb; due_v4 date; original_prepare_v4 jsonb;original_part_v4 jsonb;$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','position integer:=0; selected_location uuid;';END IF;
 before:=definition;definition:=replace(definition,$old$  IF p_expected_version$old$,$new$  IF NOT (SELECT manual_sales_v4_enabled FROM saas.accounting_release_state WHERE singleton) THEN RETURN QUERY SELECT 'feature_not_enabled',NULL::jsonb;RETURN;END IF;
  IF p_expected_version$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %',' IF p_kind=''create'' THEN
  IF p_expected_version';END IF;
 before:=definition;definition:=replace(definition,$old$IF selected.version<>p_expected_version OR p_now<selected.updated_at THEN$old$,$new$IF (selected.version<>p_expected_version AND NOT(p_expected_version<=selected.version AND (p_kind='return_payment' AND selected.abort_requested OR p_kind='reconcile_payment' OR p_kind='confirm_payment' AND selected.prepare_operation_id=(p_args->>'prepareOperationId')::uuid AND EXISTS(SELECT 1 FROM saas.in_store_operations history CROSS JOIN LATERAL jsonb_array_elements(history.result_payload#>'{sale,paymentParts}') old_part JOIN LATERAL jsonb_array_elements(selected.payment_parts) current_part ON current_part->>'partId'=old_part->>'partId' AND current_part->>'paymentMethod'=old_part->>'paymentMethod' AND current_part->>'amountCents'=old_part->>'amountCents' WHERE history.store_id=p_store_id AND history.sale_id=p_sale_id AND (history.result_payload#>>'{sale,version}')::bigint=p_expected_version AND history.result_payload#>>'{sale,prepareOperationId}'=p_args->>'prepareOperationId' AND old_part->>'partId'=p_args->>'partId')))) OR p_now<selected.updated_at THEN$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','IF selected.version<>p_expected_version OR p_now<selected.updated';END IF;
 before:=definition;definition:=replace(definition,$old$IF selected.contract_version<3 AND p_kind<>'update' THEN$old$,$new$IF selected.contract_version<>4 AND p_kind<>'update' THEN$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','IF selected.contract_version<3 AND p_kind<>''update'' THEN';END IF;
 before:=definition;definition:=replace(definition,$old$  intent_payload:=CASE WHEN p_kind='update'$old$,$new$  IF selected.contract_version<>4 AND p_kind='update' AND NOT (SELECT manual_sales_v4_enabled FROM saas.accounting_release_state WHERE singleton) THEN RETURN QUERY SELECT 'feature_not_enabled',NULL::jsonb;RETURN;END IF;
  intent_payload:=CASE WHEN p_kind='update'$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','  intent_payload:=CASE WHEN p_kind=''update''';END IF;
 before:=definition;definition:=replace(definition,$old$   IF (quote.result_payload->>'initialCollectionCents')::bigint>0 AND intent_payload->>'paymentMethod' IS NULL THEN RETURN QUERY SELECT 'payment_method_required',NULL::jsonb;RETURN;END IF;$old$,$new$   -- Payment/customer authority is checked after price-change reconciliation.$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','   IF (quote.result_payload->>''initialCollectionCents'')::bigint>0';END IF;
 before:=definition;definition:=replace(definition,$old$IF p_kind<>'complete' OR selected.status<>'payment_received' THEN$old$,$new$IF p_kind='reconcile_payment' AND manager THEN NULL;
 ELSIF p_kind NOT IN('complete','abort','return_payment','revise_payments') OR selected.status NOT IN('payment_pending','payment_received') THEN$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','IF p_kind<>''complete'' OR selected.status<>''payment_received'' THEN';END IF;
 before:=definition;definition:=replace(definition,$old$contract_version=3,payment_method=intent_payload->>'paymentMethod'$old$,$new$contract_version=4,payment_method=quote.result_payload->>'paymentMethod',sales_channel=intent_payload->>'salesChannel',social_platform=intent_payload->>'socialPlatform',social_reference=intent_payload->>'socialReference',fulfillment_method=intent_payload->>'fulfillmentMethod',shipping_address=nullif(intent_payload->'shippingAddress','null'),billing_address=coalesce(nullif(intent_payload->'billingAddress','null'),nullif(intent_payload->'shippingAddress','null')),shipping_cents=(intent_payload->>'shippingCents')::bigint,payment_parts=intent_payload->'paymentParts'$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','contract_version=3,payment_method=intent_payload->>''paymentMethod';END IF;
 before:=definition;definition:=replace(definition,$old$discount_cents,total_cents,created_at,updated_at)$old$,$new$discount_cents,total_cents,shipping_cents,created_at,updated_at)$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','discount_cents,total_cents,created_at,updated_at)';END IF;
 before:=definition;definition:=replace(definition,$old$(quote.result_payload->>'totalCents')::bigint,p_now,p_now);$old$,$new$(quote.result_payload->>'totalCents')::bigint,(intent_payload->>'shippingCents')::bigint,p_now,p_now);$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','(quote.result_payload->>''totalCents'')::bigint,p_now,p_now);';END IF;
 before:=definition;definition:=replace(definition,$old$status='payment_pending',price_provenance=quote.result_payload->'priceProvenance' WHERE id=p_sale_id;$old$,$new$status='payment_pending',prepare_operation_id=p_operation_id,payment_plan_version=selected.version+1,abort_requested=false,price_provenance=quote.result_payload->'priceProvenance' WHERE id=p_sale_id;$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','status=''payment_pending'',price_provenance=quote.result_payload->''';END IF;
 before:=definition;definition:=replace(definition,$old$ ELSIF p_kind='confirm_payment' THEN
  IF selected.status<>'payment_pending' OR selected.initial_collection_cents=0 OR (SELECT count(*) FROM jsonb_object_keys(p_args))<>2 OR NOT(p_args ? 'slipReference') OR (p_args->'slipReference'<>'null'::jsonb AND (jsonb_typeof(p_args->'slipReference')<>'string' OR length(p_args->>'slipReference') NOT BETWEEN 1 AND 100 OR p_args->>'slipReference'<>btrim(p_args->>'slipReference') OR p_args->>'slipReference'~'[[:cntrl:]]')) THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
  IF NOT(p_args ? 'paymentMethod') OR (p_args->'paymentMethod'<>'null'::jsonb AND (jsonb_typeof(p_args->'paymentMethod')<>'string' OR p_args->>'paymentMethod' NOT IN('card','cash','bank_transfer'))) THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;
  IF selected.payment_method IS NOT NULL AND p_args->>'paymentMethod' IS NOT NULL AND selected.payment_method<>p_args->>'paymentMethod' THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
  IF selected.payment_method IS NULL THEN
   IF p_args->>'paymentMethod' IS NULL THEN RETURN QUERY SELECT 'payment_method_required',NULL::jsonb;RETURN;END IF;
   UPDATE saas.in_store_sales SET payment_method=p_args->>'paymentMethod',contract_version=3 WHERE id=p_sale_id;
  END IF;
  INSERT INTO saas.in_store_payment_attestations(sale_id,store_id,actor_membership_id,amount_cents,slip_reference,received_at,payment_method) VALUES(p_sale_id,p_store_id,p_membership_id,selected.initial_collection_cents,p_args->>'slipReference',p_now,coalesce(selected.payment_method,p_args->>'paymentMethod'));
  UPDATE saas.in_store_sales SET status='payment_received',payment_received_at=p_now WHERE id=p_sale_id;
$old$,$new$ ELSIF p_kind='confirm_payment' THEN
  IF selected.status NOT IN('payment_pending','payment_received') OR selected.abort_requested OR p_args IS NULL OR (SELECT count(*) FROM jsonb_object_keys(p_args))<>3 OR NOT(p_args?&ARRAY['partId','prepareOperationId','slipReference']) OR selected.prepare_operation_id IS DISTINCT FROM (p_args->>'prepareOperationId')::uuid OR p_args->>'partId' IS NULL OR p_args->'slipReference'<>'null' AND (jsonb_typeof(p_args->'slipReference')<>'string' OR length(p_args->>'slipReference') NOT BETWEEN 1 AND 100 OR p_args->>'slipReference'<>btrim(p_args->>'slipReference') OR p_args->>'slipReference'~'[[:cntrl:]]') THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
  SELECT value INTO part FROM jsonb_array_elements(selected.payment_parts) WHERE value->>'partId'=p_args->>'partId';
  IF part IS NULL OR EXISTS(SELECT 1 FROM saas.in_store_payment_receipts_v4 WHERE store_id=p_store_id AND sale_id=p_sale_id AND part_id=(part->>'partId')::uuid) THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended('saas.accounting.store:'||p_store_id::text,0));
  account_v4:=saas.accounting_default_account(p_store_id,'TRY',part->>'paymentMethod',p_now);
  PERFORM 1 FROM saas.accounting_accounts WHERE store_id=p_store_id AND id=account_v4 FOR UPDATE;
  IF(SELECT balance_cents::numeric+(part->>'amountCents')::numeric>9007199254740991 FROM saas.accounting_accounts WHERE store_id=p_store_id AND id=account_v4) THEN RETURN QUERY SELECT 'amount_overflow',NULL::jsonb;RETURN;END IF;
  event_v4:=saas.inventory_deterministic_uuid('accounting','saas.accounting.manual-receipt:'||p_operation_id::text);receipt_id_v4:=saas.inventory_deterministic_uuid('in-store-receipt-v4',p_sale_id::text||':'||(part->>'partId'));
  INSERT INTO saas.accounting_events(id,store_id,operation_id,kind,currency,amount_cents,account_id,customer_id,channel,payment_method,actor_membership_id,occurred_at,created_at,metadata) VALUES(event_v4,p_store_id,p_operation_id,'collection','TRY',(part->>'amountCents')::bigint,account_v4,selected.customer_id,'POS',part->>'paymentMethod',p_membership_id,p_now,p_now,jsonb_build_object('saleId',p_sale_id,'partId',part->'partId','salesChannel',selected.sales_channel,'pendingSale',true));
  INSERT INTO saas.accounting_account_movements VALUES(p_store_id,event_v4,account_v4,(part->>'amountCents')::bigint);
  UPDATE saas.accounting_accounts SET balance_cents=balance_cents+(part->>'amountCents')::bigint,version=version+1 WHERE store_id=p_store_id AND id=account_v4;
  INSERT INTO saas.in_store_payment_receipts_v4 VALUES(receipt_id_v4,p_store_id,p_sale_id,(part->>'partId')::uuid,selected.prepare_operation_id,p_operation_id,p_membership_id,(part->>'amountCents')::bigint,part->>'paymentMethod',p_args->>'slipReference',p_now,event_v4,account_v4);
  UPDATE saas.in_store_sales SET status=CASE WHEN (SELECT count(*) FROM saas.in_store_payment_receipts_v4 WHERE store_id=p_store_id AND sale_id=p_sale_id)=jsonb_array_length(selected.payment_parts) THEN 'payment_received' ELSE 'payment_pending' END,payment_received_at=CASE WHEN (SELECT count(*) FROM saas.in_store_payment_receipts_v4 WHERE store_id=p_store_id AND sale_id=p_sale_id)=jsonb_array_length(selected.payment_parts) THEN p_now ELSE NULL END WHERE id=p_sale_id;
  PERFORM saas.accounting_bump_customer(p_store_id,selected.customer_id,'TRY');
$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %',' ELSIF p_kind=''confirm_payment'' THEN
  IF selected.status<>''payme';END IF;
 before:=definition;definition:=replace(definition,$old$  IF selected.initial_collection_cents<selected.total_cents AND NOT saas.accounting_credit_enabled() THEN RETURN QUERY SELECT 'feature_not_enabled',NULL::jsonb;RETURN;END IF;$old$,$new$  IF selected.abort_requested THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','  IF selected.initial_collection_cents<selected.total_cents AND N';END IF;
 before:=definition;definition:=replace(definition,$old$  IF NOT (selected.initial_collection_cents=0 AND selected.status='payment_pending') AND NOT (selected.initial_collection_cents>0 AND selected.status='payment_received' AND EXISTS(SELECT 1 FROM saas.in_store_payment_attestations WHERE sale_id=p_sale_id AND store_id=p_store_id AND amount_cents=selected.initial_collection_cents AND payment_method=selected.payment_method)) THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
  IF selected.initial_collection_cents=0 AND NOT saas.in_store_can_sell_on_credit(p_store_id,p_membership_id) THEN RETURN QUERY SELECT 'credit_denied',NULL::jsonb;RETURN;END IF;
  SELECT * INTO receipt FROM saas.in_store_payment_attestations WHERE sale_id=p_sale_id AND store_id=p_store_id;
$old$,$new$  IF selected.status NOT IN('payment_pending','payment_received') OR EXISTS(SELECT 1 FROM jsonb_array_elements(selected.payment_parts) frozen_part LEFT JOIN saas.in_store_payment_receipts_v4 r ON r.store_id=p_store_id AND r.sale_id=p_sale_id AND r.part_id=(frozen_part->>'partId')::uuid LEFT JOIN saas.in_store_payment_returns_v4 returned ON returned.store_id=r.store_id AND returned.receipt_id=r.id WHERE r.id IS NULL OR returned.receipt_id IS NOT NULL) OR coalesce((SELECT sum(amount_cents) FROM saas.in_store_payment_receipts_v4 WHERE store_id=p_store_id AND sale_id=p_sale_id),0)<>selected.initial_collection_cents THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
  IF selected.initial_collection_cents<selected.total_cents AND selected.customer_id IS NULL THEN RETURN QUERY SELECT 'customer_required',NULL::jsonb;RETURN;END IF;
  -- Existing prepared debt authority is frozen; a release rollback cannot strand received money.
$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','  IF NOT (selected.initial_collection_cents=0 AND selected.status';END IF;
 before:=definition;definition:=replace(definition,$old$payment_status,shipping_address,created_at,updated_at,paid_at)$old$,$new$payment_status,shipping_address,billing_address,created_at,updated_at,paid_at)$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','payment_status,shipping_address,created_at,updated_at,paid_at)';END IF;
 before:=definition;definition:=replace(definition,$old$'TRY',selected.subtotal_cents,0,selected.discount_cents,selected.total_cents,'delivered'$old$,$new$'TRY',selected.subtotal_cents,selected.shipping_cents,selected.discount_cents,selected.total_cents,CASE WHEN selected.fulfillment_method='shipping' THEN 'pending' ELSE 'delivered' END$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','''TRY'',selected.subtotal_cents,0,selected.discount_cents,selected.';END IF;
 before:=definition;definition:=replace(definition,$old$THEN 'completed' ELSE 'pending' END,NULL,coalesce(selected.payment_received_at,p_now),p_now,$old$,$new$THEN 'completed' ELSE 'pending' END,selected.shipping_address,selected.billing_address,coalesce(selected.payment_received_at,p_now),p_now,$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','THEN ''completed'' ELSE ''pending'' END,NULL,p_now,p_now,';END IF;
 before:=definition;definition:=replace(definition,$old$  PERFORM saas.accounting_post_pos_sale(p_store_id,target_order,p_operation_id,selected.customer_id,coalesce(selected.customer_snapshot,'{}'::jsonb),selected.total_cents,selected.initial_collection_cents,'TRY',selected.payment_method,selected.due_date,p_membership_id,p_now,receipt.received_at,receipt.actor_membership_id);$old$,$new$  PERFORM saas.accounting_post_pos_sale_v4(p_store_id,p_sale_id,target_order,p_operation_id,p_membership_id,p_now);$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','  PERFORM saas.accounting_post_pos_sale(p_store_id,target_order,p';END IF;
 before:=definition;definition:=replace(definition,$old$OR EXISTS(SELECT 1 FROM saas.in_store_payment_attestations WHERE sale_id=p_sale_id) THEN$old$,$new$OR EXISTS(SELECT 1 FROM saas.in_store_payment_attestations WHERE sale_id=p_sale_id) OR EXISTS(SELECT 1 FROM saas.in_store_payment_receipts_v4 WHERE store_id=p_store_id AND sale_id=p_sale_id) THEN$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','OR EXISTS(SELECT 1 FROM saas.in_store_payment_attestations WHERE ';END IF;
 before:=definition;definition:=replace(definition,$old$SET status='draft' WHERE id=p_sale_id;$old$,$new$SET status='draft',prepare_operation_id=NULL,abort_requested=false WHERE id=p_sale_id;$new$);IF before=definition THEN RAISE EXCEPTION 'MANUAL_V4_ANCHOR_MISSING: %','SET status=''draft'' WHERE id=p_sale_id;';END IF;


definition:=replace(definition,$old$ ELSIF p_kind='cancel' THEN$old$,$new$ ELSIF p_kind='reconcile_payment' THEN
  IF NOT manager THEN RETURN QUERY SELECT 'membership_denied',NULL::jsonb;RETURN;END IF;
  IF (SELECT count(*) FROM jsonb_object_keys(p_args))<>3 OR NOT(p_args?&ARRAY['originalOperationId','prepareOperationId','partId']) OR p_operation_id=(p_args->>'originalOperationId')::uuid THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;
  IF EXISTS(SELECT 1 FROM saas.in_store_operations WHERE operation_id=(p_args->>'originalOperationId')::uuid) OR EXISTS(SELECT 1 FROM saas.in_store_obsolete_payment_reconciliations_v4 WHERE original_operation_id=(p_args->>'originalOperationId')::uuid) THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
  SELECT prepared.result_payload->'sale' INTO original_prepare_v4 FROM saas.in_store_operations prepared WHERE prepared.store_id=p_store_id AND prepared.sale_id=p_sale_id AND prepared.operation_id=(p_args->>'prepareOperationId')::uuid AND prepared.operation_kind='prepare' AND prepared.result_payload->>'priceChanged'='false' AND prepared.result_payload#>>'{sale,contractVersion}'='4';
  IF original_prepare_v4 IS NULL THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
  SELECT historical_part INTO original_part_v4 FROM saas.in_store_operations history CROSS JOIN LATERAL jsonb_array_elements(history.result_payload#>'{sale,paymentParts}') historical_part WHERE history.store_id=p_store_id AND history.sale_id=p_sale_id AND history.operation_kind IN('prepare','revise_payments') AND history.result_payload#>>'{sale,prepareOperationId}'=p_args->>'prepareOperationId' AND historical_part->>'partId'=p_args->>'partId' ORDER BY history.committed_at,history.operation_id LIMIT 1;
  IF original_part_v4 IS NULL OR EXISTS(SELECT 1 FROM saas.in_store_payment_receipts_v4 WHERE store_id=p_store_id AND sale_id=p_sale_id AND part_id=(p_args->>'partId')::uuid) OR selected.prepare_operation_id=(p_args->>'prepareOperationId')::uuid AND EXISTS(SELECT 1 FROM jsonb_array_elements(selected.payment_parts) current_part WHERE current_part->>'partId'=original_part_v4->>'partId' AND current_part->>'paymentMethod'=original_part_v4->>'paymentMethod' AND current_part->>'amountCents'=original_part_v4->>'amountCents') THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
  INSERT INTO saas.in_store_obsolete_payment_reconciliations_v4 VALUES(p_operation_id,p_store_id,p_sale_id,(p_args->>'originalOperationId')::uuid,(p_args->>'prepareOperationId')::uuid,(p_args->>'partId')::uuid,(original_part_v4->>'amountCents')::bigint,original_part_v4->>'paymentMethod',p_membership_id,p_now,'physical_return_confirmed');
 ELSIF p_kind='revise_payments' THEN
  IF selected.status NOT IN('payment_pending','payment_received') OR selected.abort_requested OR (SELECT count(*) FROM jsonb_object_keys(p_args))<>3 OR NOT(p_args?&ARRAY['paymentParts','customerId','dueDate']) OR NOT saas.in_store_payment_parts_valid_v4(p_args->'paymentParts') THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
  parts_v4:=p_args->'paymentParts';
  IF EXISTS(SELECT 1 FROM jsonb_array_elements(parts_v4) proposed_part JOIN saas.in_store_operations history ON history.store_id=p_store_id AND history.sale_id=p_sale_id AND history.operation_kind IN('prepare','revise_payments') AND history.result_payload#>>'{sale,prepareOperationId}'=selected.prepare_operation_id::text CROSS JOIN LATERAL jsonb_array_elements(history.result_payload#>'{sale,paymentParts}') prior_part WHERE prior_part->>'partId'=proposed_part->>'partId' AND (prior_part->>'paymentMethod'<>proposed_part->>'paymentMethod' OR prior_part->>'amountCents'<>proposed_part->>'amountCents')) THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
  IF EXISTS(SELECT 1 FROM saas.in_store_payment_receipts_v4 received LEFT JOIN LATERAL (SELECT value FROM jsonb_array_elements(parts_v4) WHERE value->>'partId'=received.part_id::text) proposed ON true WHERE received.store_id=p_store_id AND received.sale_id=p_sale_id AND (proposed.value IS NULL OR (proposed.value->>'amountCents')::bigint<>received.amount_cents OR proposed.value->>'paymentMethod'<>received.payment_method)) THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
  SELECT coalesce(sum((value->>'amountCents')::bigint),0),CASE WHEN count(DISTINCT value->>'paymentMethod')=1 THEN min(value->>'paymentMethod') ELSE NULL END INTO initial_v4,method_v4 FROM jsonb_array_elements(parts_v4);
  IF initial_v4>selected.total_cents THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;
  IF selected.customer_id IS NOT NULL AND selected.customer_id IS DISTINCT FROM (p_args->>'customerId')::uuid THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
  IF p_args->>'customerId' IS NOT NULL THEN SELECT * INTO customer_v4 FROM saas.customers WHERE store_id=p_store_id AND id=(p_args->>'customerId')::uuid;IF NOT FOUND THEN RETURN QUERY SELECT 'not_found',NULL::jsonb;RETURN;END IF;IF customer_v4.status<>'active' OR customer_v4.archived_at IS NOT NULL THEN RETURN QUERY SELECT 'customer_archived',NULL::jsonb;RETURN;END IF;END IF;
  IF initial_v4<selected.total_cents THEN IF NOT saas.accounting_credit_enabled() THEN RETURN QUERY SELECT 'feature_not_enabled',NULL::jsonb;RETURN;END IF;IF NOT saas.in_store_can_sell_on_credit(p_store_id,p_membership_id) THEN RETURN QUERY SELECT 'credit_denied',NULL::jsonb;RETURN;END IF;IF customer_v4.id IS NULL OR customer_v4.phone IS NULL OR customer_v4.first_name='' OR customer_v4.last_name='' THEN RETURN QUERY SELECT 'customer_required',NULL::jsonb;RETURN;END IF;END IF;
  due_v4:=(p_args->>'dueDate')::date;IF p_args->>'dueDate' IS NOT NULL AND due_v4::text<>p_args->>'dueDate' THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;
  PERFORM set_config('saas.in_store.v4_revision',p_store_id::text||':'||p_sale_id::text,true);
  UPDATE saas.in_store_sales SET payment_parts=parts_v4,payment_plan_version=selected.version+1,payment_method=method_v4,initial_collection_cents=initial_v4,customer_id=customer_v4.id,customer_snapshot=CASE WHEN selected.customer_id IS NOT NULL THEN selected.customer_snapshot WHEN customer_v4.id IS NULL THEN NULL ELSE saas.in_store_pos_customer_projection(customer_v4) END,due_date=due_v4,intent=intent||jsonb_build_object('paymentParts',parts_v4,'customerId',customer_v4.id,'dueDate',due_v4),status=CASE WHEN initial_v4>0 AND (SELECT count(*) FROM saas.in_store_payment_receipts_v4 WHERE store_id=p_store_id AND sale_id=p_sale_id)=jsonb_array_length(parts_v4) THEN 'payment_received' ELSE 'payment_pending' END,payment_received_at=CASE WHEN initial_v4>0 AND (SELECT count(*) FROM saas.in_store_payment_receipts_v4 WHERE store_id=p_store_id AND sale_id=p_sale_id)=jsonb_array_length(parts_v4) THEN (SELECT max(received_at) FROM saas.in_store_payment_receipts_v4 WHERE store_id=p_store_id AND sale_id=p_sale_id) ELSE NULL END WHERE id=p_sale_id;
  PERFORM set_config('saas.in_store.v4_revision','',true);
 ELSIF p_kind='abort' THEN
  IF NOT manager THEN RETURN QUERY SELECT 'membership_denied',NULL::jsonb;RETURN;END IF;
  IF selected.status NOT IN('payment_pending','payment_received') OR p_args<>'{}' THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
  IF NOT EXISTS(SELECT 1 FROM saas.in_store_payment_receipts_v4 received LEFT JOIN saas.in_store_payment_returns_v4 returned ON returned.store_id=received.store_id AND returned.receipt_id=received.id WHERE received.store_id=p_store_id AND received.sale_id=p_sale_id AND returned.receipt_id IS NULL) THEN
   UPDATE saas.in_store_inventory_reservations SET status='released',released_at=p_now,updated_at=p_now,version=version+1 WHERE sale_id=p_sale_id AND status='held';
   UPDATE saas.in_store_sales SET abort_requested=true,status='cancelled',payment_received_at=NULL WHERE id=p_sale_id;
  ELSE UPDATE saas.in_store_sales SET abort_requested=true WHERE id=p_sale_id;END IF;
 ELSIF p_kind='return_payment' THEN
  IF NOT manager THEN RETURN QUERY SELECT 'membership_denied',NULL::jsonb;RETURN;END IF;
  IF selected.status NOT IN('payment_pending','payment_received') OR NOT selected.abort_requested OR (SELECT count(*) FROM jsonb_object_keys(p_args))<>2 OR NOT(p_args?&ARRAY['partId','reason']) OR jsonb_typeof(p_args->'reason')<>'string' OR length(p_args->>'reason') NOT BETWEEN 1 AND 2000 OR p_args->>'reason'<>btrim(p_args->>'reason') OR p_args->>'reason'~'[[:cntrl:]]' THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
  SELECT * INTO receipt_v4 FROM saas.in_store_payment_receipts_v4 WHERE store_id=p_store_id AND sale_id=p_sale_id AND part_id=(p_args->>'partId')::uuid;
  IF NOT FOUND OR EXISTS(SELECT 1 FROM saas.in_store_payment_returns_v4 WHERE receipt_id=receipt_v4.id) THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended('saas.accounting.store:'||p_store_id::text,0));
  PERFORM 1 FROM saas.accounting_accounts WHERE store_id=p_store_id AND id=receipt_v4.account_id FOR UPDATE;
  IF(SELECT balance_cents<receipt_v4.amount_cents FROM saas.accounting_accounts WHERE store_id=p_store_id AND id=receipt_v4.account_id) THEN RETURN QUERY SELECT 'insufficient_funds',NULL::jsonb;RETURN;END IF;
  event_v4:=saas.inventory_deterministic_uuid('accounting','saas.accounting.manual-pending-return:'||p_operation_id::text);
  INSERT INTO saas.accounting_events(id,store_id,operation_id,kind,currency,amount_cents,account_id,customer_id,channel,payment_method,note,actor_membership_id,occurred_at,created_at,metadata) VALUES(event_v4,p_store_id,p_operation_id,'refund','TRY',receipt_v4.amount_cents,receipt_v4.account_id,selected.customer_id,'POS',receipt_v4.payment_method,p_args->>'reason',p_membership_id,p_now,p_now,jsonb_build_object('saleId',p_sale_id,'partId',receipt_v4.part_id,'receiptId',receipt_v4.id,'salesChannel',selected.sales_channel,'pendingSale',true));
  INSERT INTO saas.accounting_account_movements VALUES(p_store_id,event_v4,receipt_v4.account_id,-receipt_v4.amount_cents);
  UPDATE saas.accounting_accounts SET balance_cents=balance_cents-receipt_v4.amount_cents,version=version+1 WHERE store_id=p_store_id AND id=receipt_v4.account_id;
  INSERT INTO saas.in_store_payment_returns_v4 VALUES(receipt_v4.id,p_store_id,event_v4,p_operation_id,p_membership_id,p_now,p_args->>'reason');
  IF NOT EXISTS(SELECT 1 FROM saas.in_store_payment_receipts_v4 received LEFT JOIN saas.in_store_payment_returns_v4 returned ON returned.store_id=received.store_id AND returned.receipt_id=received.id WHERE received.store_id=p_store_id AND received.sale_id=p_sale_id AND returned.receipt_id IS NULL) THEN
   UPDATE saas.in_store_inventory_reservations SET status='released',released_at=p_now,updated_at=p_now,version=version+1 WHERE sale_id=p_sale_id AND status='held';
   UPDATE saas.in_store_sales SET status='cancelled',payment_received_at=NULL WHERE id=p_sale_id;
  END IF;
  IF EXISTS(SELECT 1 FROM saas.in_store_sales WHERE id=p_sale_id AND status<>'cancelled') THEN UPDATE saas.in_store_sales SET status='payment_pending',payment_received_at=NULL WHERE id=p_sale_id;END IF;
  PERFORM saas.accounting_bump_customer(p_store_id,selected.customer_id,'TRY');
 ELSIF p_kind='cancel' THEN$new$);

 definition:=replace(definition,$old$   IF (quote.result_payload->>'initialCollectionCents')::bigint<(quote.result_payload->>'totalCents')::bigint THEN
    IF NOT saas.accounting_credit_enabled() THEN RETURN QUERY SELECT 'feature_not_enabled',NULL::jsonb;RETURN;END IF;
    IF NOT saas.in_store_can_sell_on_credit(p_store_id,p_membership_id) THEN RETURN QUERY SELECT 'credit_denied',NULL::jsonb;RETURN;END IF;
   END IF;$old$,'');
 definition:=replace(definition,$old$   -- Global inventory and selected location$old$,$new$   IF ((quote.result_payload->>'initialCollectionCents')::bigint<(quote.result_payload->>'totalCents')::bigint OR intent_payload->>'fulfillmentMethod'='shipping') AND (quote.result_payload->'customer'->>'phone' IS NULL OR quote.result_payload->'customer'->>'firstName'='' OR quote.result_payload->'customer'->>'lastName'='') THEN RETURN QUERY SELECT 'customer_required',NULL::jsonb;RETURN;END IF;
   IF (quote.result_payload->>'initialCollectionCents')::bigint<(quote.result_payload->>'totalCents')::bigint THEN IF NOT saas.accounting_credit_enabled() THEN RETURN QUERY SELECT 'feature_not_enabled',NULL::jsonb;RETURN;END IF;IF NOT saas.in_store_can_sell_on_credit(p_store_id,p_membership_id) THEN RETURN QUERY SELECT 'credit_denied',NULL::jsonb;RETURN;END IF;END IF;
   -- Global inventory and selected location$new$);
 definition:=replace(definition,$old$SET initial_collection_cents=(quote.result_payload->>'initialCollectionCents')::bigint,customer_snapshot=$old$,$new$SET payment_parts=quote.result_payload->'paymentParts',payment_method=quote.result_payload->>'paymentMethod',intent=jsonb_set(intent,'{paymentParts}',quote.result_payload->'paymentParts'),initial_collection_cents=(quote.result_payload->>'initialCollectionCents')::bigint,customer_snapshot=$new$);
 definition:=replace(definition,$old$payment_parts=intent_payload->'paymentParts'$old$,$new$payment_parts=quote.result_payload->'paymentParts'$new$);
 definition:=replace(definition,$old$intent=intent_payload,price_provenance=$old$,$new$intent=jsonb_set(intent_payload,'{paymentParts}',quote.result_payload->'paymentParts'),price_provenance=$new$);

 definition:=replace(definition,$old$ PERFORM pg_advisory_xact_lock_shared(hashtextextended('saas.accounting.release',0));$old$,$new$ IF p_kind='reconcile_payment' THEN IF NOT saas.in_store_is_manager(p_store_id,p_membership_id) THEN RETURN QUERY SELECT 'membership_denied',NULL::jsonb;RETURN;END IF;PERFORM pg_advisory_xact_lock(hashtextextended('saas.in_store.operation:'||(p_args->>'originalOperationId'),0));END IF;
 PERFORM pg_advisory_xact_lock_shared(hashtextextended('saas.accounting.release',0));$new$);
 definition:=replace(definition,$old$ manager:=saas.in_store_is_manager(p_store_id,p_membership_id);$old$,$new$ IF p_kind='confirm_payment' AND EXISTS(SELECT 1 FROM saas.in_store_obsolete_payment_reconciliations_v4 WHERE original_operation_id=p_operation_id) THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
 manager:=saas.in_store_is_manager(p_store_id,p_membership_id);$new$);
 EXECUTE definition;END $v4$;
-- Additive V4 ABI; legacy operation snapshots are never rewritten.
DO $facades$ DECLARE fn record;definition text;BEGIN
 FOR fn IN SELECT p.oid,p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='saas' AND p.proname IN('in_store_sales_create_v3','in_store_sales_update_v3','in_store_sales_hold_v3','in_store_sales_prepare_v3','in_store_sales_complete_v3','in_store_sales_cancel_v3','in_store_sales_discard_v3','in_store_sales_takeover_v3','in_store_sales_get_v3','in_store_sales_get_operation_v3','in_store_sales_list_v3','in_store_sales_bootstrap_v3','in_store_sales_list_staff_v3','in_store_sales_recover_staff_v3','in_store_sales_set_staff_v3') LOOP
  definition:=pg_get_functiondef(fn.oid);
  definition:=replace(replace(replace(replace(definition,'in_store_sales_mutate_v3','in_store_sales_mutate_v4'),'in_store_sales_projection_v3','in_store_sales_projection_v4'),'in_store_projection_v3_value','in_store_projection_v4_value'),'_v3','_v4');
  -- The staff projection itself is shared; only its versioned read facade is new.
  definition:=replace(definition,'in_store_staff_projection_v4','in_store_staff_projection_v3');
  IF fn.proname='in_store_sales_bootstrap_v3' THEN definition:=replace(definition,'sum(subtotal_cents)','sum(subtotal_cents+shipping_cents)');definition:=replace(definition,$old$'creditSalesAvailable',saas.accounting_credit_enabled()$old$,$new$'creditSalesAvailable',saas.accounting_credit_enabled(),'manualSalesV4Available',(SELECT manual_sales_v4_enabled FROM saas.accounting_release_state WHERE singleton)$new$);END IF;
  EXECUTE definition;
 END LOOP;
END $facades$;
CREATE FUNCTION saas.in_store_sales_confirm_payment_v4(p_store_id uuid,p_principal_id uuid,p_membership_id uuid,p_plan_id uuid,p_plan_code text,p_plan_version bigint,p_now timestamptz,p_operation_id uuid,p_fingerprint text,p_sale_id uuid,p_expected_version bigint,p_part_id uuid,p_prepare_operation_id uuid,p_slip_reference text) RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$ SELECT * FROM saas.in_store_sales_mutate_v4(p_store_id,p_principal_id,p_membership_id,p_plan_id,p_plan_code,p_plan_version,p_now,p_operation_id,p_fingerprint,p_sale_id,p_expected_version,'confirm_payment',jsonb_build_object('partId',p_part_id,'prepareOperationId',p_prepare_operation_id,'slipReference',p_slip_reference)) $f$;
CREATE FUNCTION saas.in_store_sales_revise_payments_v4(p_store_id uuid,p_principal_id uuid,p_membership_id uuid,p_plan_id uuid,p_plan_code text,p_plan_version bigint,p_now timestamptz,p_operation_id uuid,p_fingerprint text,p_sale_id uuid,p_expected_version bigint,p_parts jsonb,p_customer_id uuid,p_due_date date) RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$ SELECT * FROM saas.in_store_sales_mutate_v4(p_store_id,p_principal_id,p_membership_id,p_plan_id,p_plan_code,p_plan_version,p_now,p_operation_id,p_fingerprint,p_sale_id,p_expected_version,'revise_payments',jsonb_build_object('paymentParts',p_parts,'customerId',p_customer_id,'dueDate',p_due_date)) $f$;
CREATE FUNCTION saas.in_store_sales_abort_v4(p_store_id uuid,p_principal_id uuid,p_membership_id uuid,p_plan_id uuid,p_plan_code text,p_plan_version bigint,p_now timestamptz,p_operation_id uuid,p_fingerprint text,p_sale_id uuid,p_expected_version bigint) RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$ SELECT * FROM saas.in_store_sales_mutate_v4(p_store_id,p_principal_id,p_membership_id,p_plan_id,p_plan_code,p_plan_version,p_now,p_operation_id,p_fingerprint,p_sale_id,p_expected_version,'abort','{}') $f$;
CREATE FUNCTION saas.in_store_sales_return_payment_v4(p_store_id uuid,p_principal_id uuid,p_membership_id uuid,p_plan_id uuid,p_plan_code text,p_plan_version bigint,p_now timestamptz,p_operation_id uuid,p_fingerprint text,p_sale_id uuid,p_expected_version bigint,p_part_id uuid,p_reason text) RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$ SELECT * FROM saas.in_store_sales_mutate_v4(p_store_id,p_principal_id,p_membership_id,p_plan_id,p_plan_code,p_plan_version,p_now,p_operation_id,p_fingerprint,p_sale_id,p_expected_version,'return_payment',jsonb_build_object('partId',p_part_id,'reason',p_reason)) $f$;
CREATE FUNCTION saas.in_store_sales_reconcile_payment_v4(p_store_id uuid,p_principal_id uuid,p_membership_id uuid,p_plan_id uuid,p_plan_code text,p_plan_version bigint,p_now timestamptz,p_operation_id uuid,p_fingerprint text,p_sale_id uuid,p_expected_version bigint,p_original_operation_id uuid,p_prepare_operation_id uuid,p_part_id uuid) RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$ SELECT * FROM saas.in_store_sales_mutate_v4(p_store_id,p_principal_id,p_membership_id,p_plan_id,p_plan_code,p_plan_version,p_now,p_operation_id,p_fingerprint,p_sale_id,p_expected_version,'reconcile_payment',jsonb_build_object('originalOperationId',p_original_operation_id,'prepareOperationId',p_prepare_operation_id,'partId',p_part_id)) $f$;
-- Freeze V4 price/delivery/channel while allowing only the checked pending-part revision.
DO $guard$ DECLARE definition text;BEGIN
 definition:=pg_get_functiondef('saas.in_store_credit_snapshot_guard()'::regprocedure);
 definition:=replace(definition,'OLD.contract_version=3','OLD.contract_version IN(3,4)');
 definition:=replace(definition,$old$BEGIN$old$,$new$BEGIN
 IF OLD.contract_version=4 AND OLD.status IN('payment_pending','payment_received','completed') THEN
  IF (OLD.sales_channel,OLD.social_platform,OLD.social_reference,OLD.fulfillment_method,OLD.shipping_address,OLD.billing_address,OLD.shipping_cents,OLD.prepare_operation_id) IS DISTINCT FROM (NEW.sales_channel,NEW.social_platform,NEW.social_reference,NEW.fulfillment_method,NEW.shipping_address,NEW.billing_address,NEW.shipping_cents,NEW.prepare_operation_id) AND NEW.status<>'draft' THEN RAISE EXCEPTION 'IN_STORE_V4_SNAPSHOT_IMMUTABLE';END IF;
  IF current_setting('saas.in_store.v4_revision',true)=OLD.store_id::text||':'||OLD.id::text AND OLD.status IN('payment_pending','payment_received') AND NOT OLD.abort_requested AND OLD.items=NEW.items AND OLD.total_cents=NEW.total_cents AND OLD.intent-ARRAY['paymentParts','customerId','dueDate']=NEW.intent-ARRAY['paymentParts','customerId','dueDate'] THEN RETURN NEW;END IF;
  IF OLD.payment_parts IS DISTINCT FROM NEW.payment_parts THEN RAISE EXCEPTION 'IN_STORE_V4_PARTS_IMMUTABLE';END IF;
 END IF;
$new$);
 EXECUTE definition;
END $guard$;
-- Old clients must not mutate or silently truncate V4, while old idempotent replays still run first.
DO $legacy$ DECLARE fn record;definition text;anchor text;BEGIN
 FOR fn IN SELECT p.oid,p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='saas' AND p.proname IN('in_store_sales_mutate','in_store_sales_mutate_v2','in_store_sales_mutate_v3') LOOP
  definition:=pg_get_functiondef(fn.oid);anchor:='  IF selected.owner_membership_id<>p_membership_id';
  IF position(anchor IN definition)=0 THEN RAISE EXCEPTION 'MANUAL_V4_LEGACY_GUARD_ANCHOR: %',fn.proname;END IF;
  definition:=replace(definition,anchor,$new$  IF selected.contract_version=4 THEN RETURN QUERY SELECT 'client_upgrade_required',NULL::jsonb;RETURN;END IF;
$new$||anchor);EXECUTE definition;
 END LOOP;
 FOR fn IN SELECT p.oid,p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='saas' AND p.proname IN('in_store_sales_get','in_store_sales_get_v2','in_store_sales_get_v3') LOOP
  definition:=pg_get_functiondef(fn.oid);anchor:=' IF selected.owner_membership_id<>p_membership_id';
  IF position(anchor IN definition)=0 THEN RAISE EXCEPTION 'MANUAL_V4_LEGACY_GET_ANCHOR: %',fn.proname;END IF;
  definition:=replace(definition,anchor,$new$ IF selected.contract_version=4 THEN RETURN QUERY SELECT 'client_upgrade_required',NULL::jsonb;RETURN;END IF;
$new$||anchor);EXECUTE definition;
 END LOOP;
 FOR fn IN SELECT p.oid,p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='saas' AND p.proname IN('in_store_sales_list','in_store_sales_list_v2','in_store_sales_list_v3','in_store_sales_bootstrap','in_store_sales_bootstrap_v2','in_store_sales_bootstrap_v3') LOOP
  definition:=pg_get_functiondef(fn.oid);anchor:=' manager:=saas.in_store_is_manager';
  IF position(anchor IN definition)=0 THEN RAISE EXCEPTION 'MANUAL_V4_LEGACY_LIST_ANCHOR: %',fn.proname;END IF;
  definition:=replace(definition,'FROM saas.in_store_sales WHERE store_id=p_store_id','FROM saas.in_store_sales WHERE contract_version<4 AND store_id=p_store_id');EXECUTE definition;
 END LOOP;
 FOR fn IN SELECT p.oid,p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='saas' AND p.proname IN('in_store_sales_get_operation','in_store_sales_get_operation_v2','in_store_sales_get_operation_v3') LOOP
  definition:=pg_get_functiondef(fn.oid);anchor:=' IF prior.sale_id IS NULL';
  IF position(anchor IN definition)=0 THEN RAISE EXCEPTION 'MANUAL_V4_LEGACY_OPERATION_ANCHOR: %',fn.proname;END IF;
  definition:=replace(definition,anchor,$new$ IF prior.result_payload#>>'{sale,contractVersion}'='4' THEN RETURN QUERY SELECT 'client_upgrade_required',NULL::jsonb;RETURN;END IF;
$new$||anchor);EXECUTE definition;
 END LOOP;
END $legacy$;
-- Fulfillment only: in_store stock is already consumed by V4 completion.
DO $shipping$ DECLARE fn record;definition text;anchor text;BEGIN
 definition:=pg_get_functiondef('saas.in_store_order_guard()'::regprocedure);
 definition:=replace(definition,'BEGIN',$new$BEGIN
 IF OLD.source='in_store' AND current_setting('saas.in_store.v4_shipping',true)=OLD.store_id::text||':'||OLD.id::text AND EXISTS(SELECT 1 FROM saas.in_store_sales WHERE store_id=OLD.store_id AND order_id=OLD.id AND contract_version=4 AND fulfillment_method='shipping' AND status='completed') AND NEW.status IN('pending','confirmed','preparing','shipped','delivered') AND to_jsonb(NEW)-ARRAY['status','shipping_address','tracking','version','updated_at']=to_jsonb(OLD)-ARRAY['status','shipping_address','tracking','version','updated_at'] AND NEW.version=OLD.version+1 AND NEW.updated_at>=OLD.updated_at THEN RETURN NEW;END IF;
$new$);EXECUTE definition;
 FOR fn IN SELECT p.oid,p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='saas' AND p.proname IN('orders_transition_status','orders_update_shipping') LOOP
 definition:=pg_get_functiondef(fn.oid);anchor:=$old$  IF current_order.source='in_store' THEN RETURN QUERY SELECT 'invalid_transition'::text,NULL::jsonb; RETURN; END IF;$old$;
 IF position(anchor IN definition)=0 THEN RAISE EXCEPTION 'MANUAL_V4_SHIPPING_RPC_ANCHOR: %',fn.proname;END IF;
 definition:=replace(definition,anchor,$new$  IF current_order.source='in_store' THEN
   IF NOT EXISTS(SELECT 1 FROM saas.in_store_sales WHERE store_id=p_store_id AND order_id=p_order_id AND contract_version=4 AND fulfillment_method='shipping' AND status='completed')$new$||CASE WHEN fn.proname='orders_transition_status' THEN $new$ OR p_next_status IN('cancelled','refunded')$new$ ELSE $new$ OR current_order.status IN('cancelled','refunded')$new$ END||$new$ THEN RETURN QUERY SELECT 'invalid_transition'::text,NULL::jsonb;RETURN;END IF;
   PERFORM set_config('saas.in_store.v4_shipping',p_store_id::text||':'||p_order_id::text,true);
  END IF;$new$);EXECUTE definition;
 END LOOP;
END $shipping$;
CREATE FUNCTION saas.accounting_sales_channel_matches_v4(p_store uuid,p_receivable uuid,p_order uuid,p_metadata jsonb,p_channel text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
 SELECT p_channel IS NULL OR EXISTS(SELECT 1 FROM saas.in_store_sales s WHERE s.store_id=p_store AND s.sales_channel=p_channel AND (s.accounting_receivable_id=p_receivable OR s.order_id=p_order OR s.id::text=p_metadata->>'saleId')) OR p_channel='manual' AND EXISTS(SELECT 1 FROM saas.orders WHERE store_id=p_store AND id=p_order AND source='manual')
$f$;
CREATE FUNCTION saas.accounting_pending_receipt_v4(p_store uuid,p_event uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
 SELECT EXISTS(SELECT 1 FROM saas.in_store_payment_receipts_v4 r JOIN saas.in_store_sales s ON s.store_id=r.store_id AND s.id=r.sale_id WHERE r.store_id=p_store AND r.event_id=p_event AND s.status<>'completed')
$f$;
CREATE FUNCTION saas.accounting_event_sales_channel_matches_v4(p_store uuid,p_event uuid,p_channel text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
 SELECT p_channel IS NULL OR EXISTS(SELECT 1 FROM saas.accounting_events e LEFT JOIN saas.accounting_events original ON original.store_id=e.store_id AND original.id=e.reverses_event_id WHERE e.store_id=p_store AND e.id=p_event AND (saas.accounting_sales_channel_matches_v4(p_store,NULL,coalesce(original.order_id,e.order_id),coalesce(original.metadata,e.metadata),p_channel) OR EXISTS(SELECT 1 FROM saas.accounting_allocations a JOIN saas.accounting_receivables r ON r.store_id=a.store_id AND r.id=a.receivable_id WHERE a.store_id=p_store AND a.event_id=coalesce(original.id,e.id) AND saas.accounting_sales_channel_matches_v4(p_store,r.id,r.order_id,NULL,p_channel))))
$f$;
DO $accounting$ DECLARE definition text;anchor text;BEGIN
 definition:=pg_get_functiondef('saas.accounting_filters_valid(jsonb)'::regprocedure);
 definition:=replace(definition,$old$'dateFrom','dateTo','channel','currency'$old$,$new$'dateFrom','dateTo','channel','salesChannel','currency'$new$);
 definition:=replace(definition,$old$ ELSIF k='currency'$old$,$new$ ELSIF k='salesChannel' THEN IF v#>>'{}' NOT IN('manual','social') THEN RETURN false;END IF;
 ELSIF k='currency'$new$);EXECUTE definition;
 definition:=pg_get_functiondef('saas.accounting_mutate(uuid,uuid,uuid,uuid,text,bigint,timestamptz,uuid,text,text,jsonb)'::regprocedure);
 anchor:=$old$ IF original.kind IN('sale','reversal')$old$;
 IF position(anchor IN definition)=0 THEN RAISE EXCEPTION 'MANUAL_V4_REVERSE_GUARD_ANCHOR';END IF;
 definition:=replace(definition,anchor,$new$ IF EXISTS(SELECT 1 FROM saas.in_store_payment_receipts_v4 pending_receipt JOIN saas.in_store_sales s ON s.store_id=pending_receipt.store_id AND s.id=pending_receipt.sale_id LEFT JOIN saas.in_store_payment_returns_v4 returned ON returned.store_id=pending_receipt.store_id AND returned.receipt_id=pending_receipt.id WHERE pending_receipt.store_id=p_store AND (pending_receipt.event_id=original.id OR returned.event_id=original.id) AND s.status<>'completed') THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
 IF original.kind IN('sale','reversal')$new$);
 definition:=replace(definition,$old$ IF customer IS NOT NULL THEN SELECT version INTO current_version FROM saas.accounting_customer_versions$old$,$new$ IF order_id_value IS NULL THEN SELECT min(allocated.order_id::text)::uuid INTO order_id_value FROM saas.accounting_allocations allocation JOIN saas.accounting_receivables allocated ON allocated.store_id=allocation.store_id AND allocated.id=allocation.receivable_id WHERE allocation.store_id=p_store AND allocation.event_id=original.id HAVING count(DISTINCT allocated.order_id)=1 AND count(*) FILTER(WHERE allocated.order_id IS NULL)=0;END IF;
 IF customer IS NOT NULL THEN SELECT version INTO current_version FROM saas.accounting_customer_versions$new$);
 definition:=replace(definition,$old$ PERFORM saas.accounting_bump_customer(p_store,customer,currency_code);$old$,$new$ IF p_kind='reverse' THEN PERFORM saas.accounting_bump_customer(p_store,affected.customer_id,currency_code) FROM (SELECT DISTINCT allocated.customer_id FROM saas.accounting_allocations allocation JOIN saas.accounting_receivables allocated ON allocated.store_id=allocation.store_id AND allocated.id=allocation.receivable_id WHERE allocation.store_id=p_store AND allocation.event_id=original.id AND allocated.customer_id IS NOT NULL AND allocated.customer_id IS DISTINCT FROM customer) affected;END IF;
 PERFORM saas.accounting_bump_customer(p_store,customer,currency_code);$new$);EXECUTE definition;
 definition:=pg_get_functiondef('saas.accounting_read(uuid,uuid,uuid,uuid,text,bigint,timestamptz,text,jsonb)'::regprocedure);
 -- Partial allocation reporting is preserved; an unallocated pending collection contributes its physical amount.
 definition:=replace(definition,$old$THEN coalesce((SELECT sum(a.amount_cents::numeric)$old$,$new$THEN CASE WHEN saas.accounting_pending_receipt_v4(p_store,e.id) AND e.channel=p_filters->>'channel' THEN e.amount_cents::numeric ELSE coalesce((SELECT sum(a.amount_cents::numeric)$new$);
 definition:=replace(definition,$old$allocated.channel=p_filters->>'channel'),0) WHEN e.kind='reversal'$old$,$new$allocated.channel=p_filters->>'channel' AND saas.accounting_sales_channel_matches_v4(p_store,allocated.id,allocated.order_id,NULL,p_filters->>'salesChannel')),0) END WHEN e.kind='reversal'$new$);
 definition:=replace(definition,$old$OR coalesce(orig.kind,e.kind)='collection' AND EXISTS($old$,$new$OR coalesce(orig.kind,e.kind)='collection' AND (saas.accounting_pending_receipt_v4(p_store,e.id) AND e.channel=p_filters->>'channel' OR EXISTS($new$);
 definition:=replace(definition,$old$channel_debt.channel=p_filters->>'channel'))$old$,$new$channel_debt.channel=p_filters->>'channel')))$new$);
 anchor:=$old$WHERE e.store_id=p_store AND e.occurred_at>=start_at$old$;
 IF position(anchor IN definition)=0 THEN RAISE EXCEPTION 'MANUAL_V4_ACCOUNTING_EVENT_ANCHOR';END IF;
 definition:=replace(definition,anchor,$new$WHERE e.store_id=p_store AND saas.accounting_event_sales_channel_matches_v4(p_store,e.id,p_filters->>'salesChannel') AND e.occurred_at>=start_at$new$);
 definition:=replace(definition,$old$WHERE r.store_id=p_store AND (customer IS NULL$old$,$new$WHERE r.store_id=p_store AND saas.accounting_sales_channel_matches_v4(p_store,r.id,r.order_id,NULL,p_filters->>'salesChannel') AND (customer IS NULL$new$);
 definition:=replace(definition,$old$WHERE payment.received_at>=start_at$old$,$new$WHERE NOT(p_filters?'salesChannel') AND payment.received_at>=start_at$new$);
 definition:=replace(definition,$old$WHERE s.store_id=p_store AND s.status='completed'$old$,$new$WHERE s.store_id=p_store AND (NOT(p_filters?'salesChannel') OR s.sales_channel=p_filters->>'salesChannel') AND s.status='completed'$new$);
 -- Open balance totals are filtered by the same receivable dimension.
 definition:=replace(definition,$old$FROM saas.accounting_receivables WHERE store_id=p_store AND (NOT(p_filters?'currency')$old$,$new$FROM saas.accounting_receivables WHERE store_id=p_store AND saas.accounting_sales_channel_matches_v4(p_store,id,order_id,NULL,p_filters->>'salesChannel') AND (NOT(p_filters?'currency')$new$);
 definition:=replace(definition,$old$AND currency=code.currency AND$old$,$new$AND currency=code.currency AND saas.accounting_sales_channel_matches_v4(p_store,id,order_id,NULL,p_filters->>'salesChannel') AND$new$);
 EXECUTE definition;
 -- Customer history follows final allocations when a pending receipt was originally anonymous.
 definition:=pg_get_functiondef('saas.accounting_customer_projection(uuid,uuid,text)'::regprocedure);
 definition:=replace(definition,$old$FROM saas.accounting_events WHERE store_id=p_store AND customer_id=p_customer AND currency=p_currency$old$,$new$FROM saas.accounting_events WHERE store_id=p_store AND (customer_id=p_customer OR EXISTS(SELECT 1 FROM saas.accounting_allocations a JOIN saas.accounting_receivables r ON r.store_id=a.store_id AND r.id=a.receivable_id WHERE a.store_id=p_store AND a.event_id=accounting_events.id AND r.customer_id=p_customer)) AND currency=p_currency$new$);EXECUTE definition;
END $accounting$;
-- Projection context is read-only; the immutable ledger metadata remains intact.
CREATE FUNCTION saas.accounting_manual_event_context_v4(p_store uuid,p_event uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
 SELECT jsonb_build_object('saleStatus',s.status,'pendingSale',s.status<>'completed') FROM saas.in_store_payment_receipts_v4 r JOIN saas.in_store_sales s ON s.store_id=r.store_id AND s.id=r.sale_id LEFT JOIN saas.in_store_payment_returns_v4 returned ON returned.store_id=r.store_id AND returned.receipt_id=r.id WHERE r.store_id=p_store AND (r.event_id=p_event OR returned.event_id=p_event)
$f$;
DO $projection$ DECLARE definition text;BEGIN
 INSERT INTO saas.manual_sales_v4_restore SELECT 'saas.accounting_event_projection(uuid,uuid)',pg_get_functiondef('saas.accounting_event_projection(uuid,uuid)'::regprocedure),md5(pg_get_functiondef('saas.accounting_event_projection(uuid,uuid)'::regprocedure)),NULL;
 definition:=pg_get_functiondef('saas.accounting_event_projection(uuid,uuid)'::regprocedure);
 definition:=replace(definition,$old$'metadata',e.metadata$old$,$new$'metadata',e.metadata||coalesce(saas.accounting_manual_event_context_v4(p_store,e.id),'{}')$new$);EXECUTE definition;
END $projection$;
-- Seal internals, and grant only the versioned domain RPC entrypoints.
DO $seal$ DECLARE fn record;BEGIN
 FOR fn IN SELECT p.oid,p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='saas' AND p.proname=ANY(ARRAY['in_store_payment_parts_valid_v4','in_store_address_valid_v4','in_store_quote_v4','in_store_projection_v4_value','in_store_sales_projection_v4','accounting_post_pos_sale_v4','in_store_sales_mutate_v4','in_store_sales_create_v4','in_store_sales_update_v4','in_store_sales_hold_v4','in_store_sales_prepare_v4','in_store_sales_complete_v4','in_store_sales_cancel_v4','in_store_sales_discard_v4','in_store_sales_takeover_v4','in_store_sales_get_v4','in_store_sales_get_operation_v4','in_store_sales_list_v4','in_store_sales_bootstrap_v4','in_store_sales_list_staff_v4','in_store_sales_recover_staff_v4','in_store_sales_set_staff_v4','in_store_sales_confirm_payment_v4','in_store_sales_revise_payments_v4','in_store_sales_abort_v4','in_store_sales_return_payment_v4','in_store_sales_reconcile_payment_v4','accounting_sales_channel_matches_v4','accounting_pending_receipt_v4','accounting_event_sales_channel_matches_v4','accounting_manual_event_context_v4']) LOOP
  EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,celebix_saas_app,celebix_saas_identity,celebix_saas_workflow,celebix_saas_migrator',fn.oid::regprocedure);
  IF fn.proname LIKE 'in_store_sales_%' AND fn.proname NOT IN('in_store_sales_mutate_v4','in_store_sales_projection_v4') THEN EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO celebix_saas_app',fn.oid::regprocedure);END IF;
 END LOOP;
 UPDATE saas.manual_sales_v4_restore SET after_hash=md5(pg_get_functiondef(signature::regprocedure));
END $seal$;
COMMIT;
