-- Private immutable money evidence. No historic accounts or payments are fabricated.
BEGIN;
SET LOCAL ROLE celebix_saas_owner;
SELECT pg_advisory_xact_lock(hashtextextended('saas.accounting.release',0));
CREATE TABLE saas.accounting_release_state(singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton),credit_sales_enabled boolean NOT NULL DEFAULT false,version bigint NOT NULL DEFAULT 1 CHECK(version BETWEEN 1 AND 9007199254740991),updated_at timestamptz NOT NULL);
INSERT INTO saas.accounting_release_state VALUES(true,false,1,transaction_timestamp());
CREATE TABLE saas.accounting_migration_restore(signature text PRIMARY KEY,definition text NOT NULL);
ALTER TABLE saas.in_store_staff_grants ADD COLUMN can_collect_receivables boolean NOT NULL DEFAULT false;
-- Retain old staff writes during a staggered reader rollout.
DO $patch$ DECLARE r record; d text; BEGIN
 FOR r IN SELECT oid::regprocedure::text signature,pg_get_functiondef(oid) definition FROM pg_proc WHERE pronamespace='saas'::regnamespace AND proname='in_store_sales_set_staff_v2' LOOP
 INSERT INTO saas.accounting_migration_restore VALUES(r.signature,r.definition);d:=replace(r.definition,'INSERT INTO saas.in_store_staff_grants VALUES','INSERT INTO saas.in_store_staff_grants(store_id,membership_id,enabled,location_ids,discount_limit_bps,version,updated_at,can_edit_price) VALUES');EXECUTE d;
 END LOOP;
END $patch$;
CREATE TABLE saas.accounting_accounts(id uuid PRIMARY KEY,store_id uuid NOT NULL REFERENCES saas.stores(id),name text NOT NULL CHECK(length(name) BETWEEN 1 AND 200 AND name=btrim(name) AND name!~'[[:cntrl:]]'),account_type text NOT NULL CHECK(account_type IN('cash','bank','card')),currency text NOT NULL CHECK(currency~'^[A-Z]{3}$'),balance_cents bigint NOT NULL DEFAULT 0 CHECK(balance_cents BETWEEN 0 AND 9007199254740991),version bigint NOT NULL DEFAULT 1 CHECK(version BETWEEN 1 AND 9007199254740991),system_default boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL,UNIQUE(store_id,id));
CREATE UNIQUE INDEX accounting_accounts_default ON saas.accounting_accounts(store_id,currency,account_type) WHERE system_default;
CREATE TABLE saas.accounting_customer_versions(store_id uuid NOT NULL,customer_id uuid NOT NULL,currency text NOT NULL CHECK(currency~'^[A-Z]{3}$'),version bigint NOT NULL DEFAULT 0 CHECK(version BETWEEN 0 AND 9007199254740991),PRIMARY KEY(store_id,customer_id,currency),FOREIGN KEY(store_id,customer_id) REFERENCES saas.customers(store_id,id));
CREATE TABLE saas.accounting_receivables(id uuid PRIMARY KEY,store_id uuid NOT NULL REFERENCES saas.stores(id),customer_id uuid,customer_snapshot jsonb NOT NULL CHECK(jsonb_typeof(customer_snapshot)='object'),order_id uuid,channel text CHECK(channel IN('POS','WEB')),currency text NOT NULL CHECK(currency~'^[A-Z]{3}$'),sale_cents bigint NOT NULL CHECK(sale_cents BETWEEN 0 AND 9007199254740991),collected_cents bigint NOT NULL DEFAULT 0 CHECK(collected_cents BETWEEN 0 AND 9007199254740991),return_cents bigint NOT NULL DEFAULT 0 CHECK(return_cents BETWEEN 0 AND sale_cents),refunded_cents bigint NOT NULL DEFAULT 0 CHECK(refunded_cents BETWEEN 0 AND greatest(collected_cents-sale_cents+return_cents,0)),occurred_at timestamptz NOT NULL,due_date date,version bigint NOT NULL DEFAULT 1 CHECK(version BETWEEN 1 AND 9007199254740991),UNIQUE(store_id,id),UNIQUE(store_id,order_id),FOREIGN KEY(store_id,customer_id) REFERENCES saas.customers(store_id,id),FOREIGN KEY(store_id,order_id) REFERENCES saas.orders(store_id,id));
CREATE INDEX accounting_receivables_fifo ON saas.accounting_receivables(store_id,customer_id,currency,occurred_at,id);
CREATE TABLE saas.accounting_events(id uuid PRIMARY KEY,store_id uuid NOT NULL REFERENCES saas.stores(id),operation_id uuid NOT NULL,kind text NOT NULL CHECK(kind IN('sale','collection','opening_debt','account_opening','expense','transfer','card_settlement','return_credit','refund','reversal')),currency text NOT NULL CHECK(currency~'^[A-Z]{3}$'),amount_cents bigint NOT NULL CHECK(amount_cents BETWEEN 0 AND 9007199254740991),account_id uuid,customer_id uuid,order_id uuid,channel text CHECK(channel IN('WEB','POS')),payment_method text CHECK(payment_method IN('cash','card','bank_transfer')),note text CHECK(note IS NULL OR(length(note) BETWEEN 1 AND 2000 AND note=btrim(note) AND note!~'[[:cntrl:]]')),category text,document_number text,actor_membership_id uuid NOT NULL,occurred_at timestamptz NOT NULL,created_at timestamptz NOT NULL,reverses_event_id uuid UNIQUE,metadata jsonb NOT NULL DEFAULT '{}',UNIQUE(store_id,id),FOREIGN KEY(store_id,account_id) REFERENCES saas.accounting_accounts(store_id,id),FOREIGN KEY(store_id,customer_id) REFERENCES saas.customers(store_id,id),FOREIGN KEY(store_id,order_id) REFERENCES saas.orders(store_id,id),FOREIGN KEY(store_id,actor_membership_id) REFERENCES saas.memberships(store_id,id),FOREIGN KEY(store_id,reverses_event_id) REFERENCES saas.accounting_events(store_id,id));
CREATE INDEX accounting_events_period ON saas.accounting_events(store_id,occurred_at,id);
CREATE TABLE saas.accounting_allocations(store_id uuid NOT NULL,event_id uuid NOT NULL,receivable_id uuid NOT NULL,effect text NOT NULL CHECK(effect IN('collect','return','refund','charge')),amount_cents bigint NOT NULL CHECK(amount_cents BETWEEN -9007199254740991 AND 9007199254740991 AND amount_cents<>0),PRIMARY KEY(event_id,receivable_id,effect),FOREIGN KEY(store_id,event_id) REFERENCES saas.accounting_events(store_id,id),FOREIGN KEY(store_id,receivable_id) REFERENCES saas.accounting_receivables(store_id,id));
CREATE TABLE saas.accounting_account_movements(store_id uuid NOT NULL,event_id uuid NOT NULL,account_id uuid NOT NULL,amount_cents bigint NOT NULL CHECK(amount_cents BETWEEN -9007199254740991 AND 9007199254740991),PRIMARY KEY(event_id,account_id),FOREIGN KEY(store_id,event_id) REFERENCES saas.accounting_events(store_id,id),FOREIGN KEY(store_id,account_id) REFERENCES saas.accounting_accounts(store_id,id));
CREATE TABLE saas.accounting_operations(operation_id uuid PRIMARY KEY,store_id uuid NOT NULL REFERENCES saas.stores(id),actor_membership_id uuid NOT NULL,kind text NOT NULL,payload_fingerprint text NOT NULL CHECK(payload_fingerprint~'^[a-f0-9]{64}$'),result_payload jsonb NOT NULL,committed_at timestamptz NOT NULL,FOREIGN KEY(store_id,actor_membership_id) REFERENCES saas.memberships(store_id,id));
CREATE FUNCTION saas.accounting_immutable() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,saas AS $f$ BEGIN RAISE EXCEPTION 'ACCOUNTING_IMMUTABLE';END $f$;
DO $tables$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['accounting_release_state','accounting_migration_restore','accounting_accounts','accounting_customer_versions','accounting_receivables','accounting_events','accounting_allocations','accounting_account_movements','accounting_operations'] LOOP
 EXECUTE format('ALTER TABLE saas.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE saas.%I FORCE ROW LEVEL SECURITY',t);EXECUTE format('REVOKE ALL ON saas.%I FROM PUBLIC,celebix_saas_app,celebix_saas_identity,celebix_saas_bootstrap,celebix_saas_workflow,celebix_saas_host_resolver,celebix_saas_observability',t);
 END LOOP;
 FOREACH t IN ARRAY ARRAY['accounting_events','accounting_allocations','accounting_account_movements','accounting_operations'] LOOP EXECUTE format('CREATE TRIGGER accounting_immutable BEFORE UPDATE OR DELETE ON saas.%I FOR EACH ROW EXECUTE FUNCTION saas.accounting_immutable()',t);END LOOP;
END $tables$;
CREATE FUNCTION saas.accounting_credit_enabled() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$ SELECT credit_sales_enabled FROM saas.accounting_release_state WHERE singleton $f$;
CREATE FUNCTION saas.accounting_authority_error(p_store uuid,p_principal uuid,p_member uuid,p_plan uuid,p_code text,p_version bigint,p_now timestamptz,p_collection boolean DEFAULT false) RETURNS text LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
DECLARE role_name text;err text;BEGIN
 IF p_now IS NULL OR NOT isfinite(p_now) THEN RETURN 'invalid_input';END IF;
 SELECT role INTO role_name FROM saas.memberships WHERE store_id=p_store AND id=p_member AND principal_id=p_principal AND status='active';
 IF role_name='cashier' AND p_collection THEN
 err:=saas.in_store_authority_error(p_store,p_principal,p_member,p_plan,p_code,p_version,p_now);
 IF err IS NOT NULL THEN RETURN err;END IF;
 IF NOT EXISTS(SELECT 1 FROM saas.in_store_staff_grants WHERE store_id=p_store AND membership_id=p_member AND enabled AND can_collect_receivables) THEN RETURN 'membership_denied';END IF;RETURN NULL;
 END IF;
 IF role_name IS NULL OR role_name NOT IN('store_owner','admin') THEN RETURN 'membership_denied';END IF;
 RETURN saas.merchant_action_authority_error(p_store,p_principal,p_member,p_plan,p_code,p_version,p_now,'orders','orders.payment');
END $f$;
CREATE FUNCTION saas.accounting_timezone(p_store uuid) RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
 SELECT coalesce((SELECT config->>'timezone' FROM saas.merchant_admin_records WHERE store_id=p_store AND record_kind='general_setting' AND status='active' AND config?'timezone' ORDER BY updated_at DESC,id DESC LIMIT 1),'Europe/Istanbul') $f$;
CREATE FUNCTION saas.accounting_account_projection(p_store uuid,p_id uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
 SELECT jsonb_build_object('id',id,'name',name,'type',account_type,'currency',currency,'balanceCents',balance_cents,'version',version,'createdAt',saas.orders_json_timestamp(created_at)) FROM saas.accounting_accounts WHERE store_id=p_store AND id=p_id $f$;
CREATE FUNCTION saas.accounting_receivable_projection(p_store uuid,p_id uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
 SELECT jsonb_build_object('id',r.id,'customerId',r.customer_id,'customerName',coalesce(nullif(r.customer_snapshot->>'name',''),nullif(concat_ws(' ',c.first_name,c.last_name),''),'Mağaza müşterisi'),'customerPhone',CASE WHEN r.customer_snapshot?'phone' THEN r.customer_snapshot->>'phone' ELSE c.phone END,'customerArchived',coalesce(c.status='archived',false),'orderId',r.order_id,'orderNumber',o.order_number,'channel',r.channel,'currency',r.currency,'saleCents',r.sale_cents,'collectedCents',r.collected_cents,'returnCents',r.return_cents,'refundedCents',r.refunded_cents,'dueCents',greatest(r.sale_cents-r.return_cents-r.collected_cents,0),'refundDueCents',greatest(r.collected_cents-r.sale_cents+r.return_cents-r.refunded_cents,0),'occurredAt',saas.orders_json_timestamp(r.occurred_at),'dueDate',r.due_date,'version',r.version) FROM saas.accounting_receivables r LEFT JOIN saas.customers c ON c.store_id=r.store_id AND c.id=r.customer_id LEFT JOIN saas.orders o ON o.store_id=r.store_id AND o.id=r.order_id WHERE r.store_id=p_store AND r.id=p_id $f$;
CREATE FUNCTION saas.accounting_event_projection(p_store uuid,p_id uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
 SELECT jsonb_build_object('id',e.id,'kind',e.kind,'currency',e.currency,'amountCents',e.amount_cents,'accountId',e.account_id,'customerId',e.customer_id,'orderId',e.order_id,'channel',e.channel,'paymentMethod',e.payment_method,'note',e.note,'category',e.category,'documentNumber',e.document_number,'actorMembershipId',e.actor_membership_id,'occurredAt',saas.orders_json_timestamp(e.occurred_at),'createdAt',saas.orders_json_timestamp(e.created_at),'reversesEventId',e.reverses_event_id,'reversed',EXISTS(SELECT 1 FROM saas.accounting_events rev WHERE rev.store_id=p_store AND rev.reverses_event_id=e.id),'allocations',coalesce((SELECT jsonb_agg(jsonb_build_object('receivableId',a.receivable_id,'orderId',r.order_id,'amountCents',a.amount_cents) ORDER BY r.occurred_at,r.id) FROM saas.accounting_allocations a JOIN saas.accounting_receivables r ON r.store_id=a.store_id AND r.id=a.receivable_id WHERE a.store_id=p_store AND a.event_id=e.id),'[]'::jsonb),'metadata',e.metadata) FROM saas.accounting_events e WHERE e.store_id=p_store AND e.id=p_id $f$;
CREATE FUNCTION saas.accounting_customer_projection(p_store uuid,p_customer uuid,p_currency text) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
 SELECT jsonb_build_object('customerId',c.id,'customerName',concat_ws(' ',c.first_name,c.last_name),'customerPhone',c.phone,'customerArchived',c.status='archived','currency',p_currency,'version',coalesce((SELECT version FROM saas.accounting_customer_versions WHERE store_id=p_store AND customer_id=p_customer AND currency=p_currency),0),'dueCents',coalesce((SELECT sum(greatest(sale_cents-return_cents-collected_cents,0)) FROM saas.accounting_receivables WHERE store_id=p_store AND customer_id=p_customer AND currency=p_currency),0),'refundDueCents',coalesce((SELECT sum(greatest(collected_cents-sale_cents+return_cents-refunded_cents,0)) FROM saas.accounting_receivables WHERE store_id=p_store AND customer_id=p_customer AND currency=p_currency),0),'receivables',coalesce((SELECT jsonb_agg(saas.accounting_receivable_projection(p_store,id) ORDER BY occurred_at,id) FROM saas.accounting_receivables WHERE store_id=p_store AND customer_id=p_customer AND currency=p_currency),'[]'::jsonb),'events',coalesce((SELECT jsonb_agg(saas.accounting_event_projection(p_store,id) ORDER BY occurred_at DESC,id DESC) FROM saas.accounting_events WHERE store_id=p_store AND customer_id=p_customer AND currency=p_currency),'[]'::jsonb)) FROM saas.customers c WHERE c.store_id=p_store AND c.id=p_customer $f$;
CREATE FUNCTION saas.accounting_order_finance(p_store uuid,p_order uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
 SELECT jsonb_build_object('status',CASE WHEN sale_cents-return_cents-collected_cents<=0 THEN 'paid' WHEN collected_cents>0 THEN 'partial' ELSE 'unpaid' END,'collectedCents',collected_cents,'dueCents',greatest(sale_cents-return_cents-collected_cents,0),'refundDueCents',greatest(collected_cents-sale_cents+return_cents-refunded_cents,0),'version',version,'receipts',coalesce((SELECT jsonb_agg(jsonb_build_object('id',e.id,'amountCents',a.amount_cents,'paymentMethod',e.payment_method,'receivedAt',saas.orders_json_timestamp(e.occurred_at),'actorMembershipId',e.actor_membership_id,'reversed',EXISTS(SELECT 1 FROM saas.accounting_events rev WHERE rev.store_id=p_store AND rev.reverses_event_id=e.id)) ORDER BY e.occurred_at,e.id) FROM saas.accounting_events e JOIN saas.accounting_allocations a ON a.store_id=e.store_id AND a.event_id=e.id WHERE a.receivable_id=r.id AND e.store_id=p_store AND e.kind='collection'),'[]'::jsonb)) FROM saas.accounting_receivables r WHERE store_id=p_store AND order_id=p_order $f$;
CREATE FUNCTION saas.accounting_default_account(p_store uuid,p_currency text,p_method text,p_now timestamptz) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
DECLARE account uuid;t text;BEGIN
 t:=CASE p_method WHEN 'bank_transfer' THEN 'bank' ELSE p_method END;IF t IS NULL OR t NOT IN('cash','bank','card') THEN RAISE EXCEPTION 'ACCOUNTING_METHOD_REQUIRED';END IF;
 SELECT id INTO account FROM saas.accounting_accounts WHERE store_id=p_store AND currency=p_currency AND account_type=t AND system_default;
 IF account IS NULL THEN account:=saas.inventory_deterministic_uuid('accounting','saas.accounting.default:'||p_store::text||':'||p_currency||':'||t);INSERT INTO saas.accounting_accounts(id,store_id,name,account_type,currency,system_default,created_at) VALUES(account,p_store,CASE t WHEN 'cash' THEN 'Kasa' WHEN 'card' THEN 'Kart tahsilatları' ELSE 'Banka' END,t,p_currency,true,p_now);END IF;RETURN account;
END $f$;
CREATE FUNCTION saas.accounting_bump_customer(p_store uuid,p_customer uuid,p_currency text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$ BEGIN IF p_customer IS NOT NULL THEN INSERT INTO saas.accounting_customer_versions VALUES(p_store,p_customer,p_currency,1) ON CONFLICT(store_id,customer_id,currency) DO UPDATE SET version=saas.accounting_customer_versions.version+1;END IF;END $f$;
INSERT INTO saas.accounting_migration_restore SELECT 'saas.in_store_order_guard()',pg_get_functiondef('saas.in_store_order_guard()'::regprocedure);
CREATE OR REPLACE FUNCTION saas.in_store_order_guard() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
BEGIN
 IF OLD.source='in_store' AND current_setting('saas.accounting.sync_order',true)=OLD.store_id::text||':'||OLD.id::text
 AND to_jsonb(NEW)-ARRAY['payment_status','paid_at','version','updated_at']=to_jsonb(OLD)-ARRAY['payment_status','paid_at','version','updated_at']
 AND NEW.version=OLD.version+1 AND NEW.updated_at>=OLD.updated_at
 AND EXISTS(SELECT 1 FROM saas.accounting_receivables r WHERE r.store_id=OLD.store_id AND r.order_id=OLD.id AND NEW.payment_status=CASE WHEN r.sale_cents-r.return_cents-r.collected_cents<=0 THEN 'completed' ELSE 'pending' END)
 THEN RETURN NEW;END IF;
 IF OLD.source='in_store' AND (NEW.source<>OLD.source OR NEW.status<>OLD.status OR NEW.payment_status<>OLD.payment_status OR NEW.shipping_address IS DISTINCT FROM OLD.shipping_address OR NEW.tracking IS DISTINCT FROM OLD.tracking OR NEW.subtotal_cents<>OLD.subtotal_cents OR NEW.discount_cents<>OLD.discount_cents OR NEW.total_cents<>OLD.total_cents) THEN RAISE check_violation USING MESSAGE='IN_STORE_ORDER_IMMUTABLE';END IF;RETURN NEW;
END $f$;
CREATE FUNCTION saas.accounting_sync_order(p_store uuid,p_order uuid,p_now timestamptz) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
DECLARE previous text;BEGIN
 IF p_order IS NOT NULL THEN
 previous:=current_setting('saas.accounting.sync_order',true);PERFORM set_config('saas.accounting.sync_order',p_store::text||':'||p_order::text,true);
 UPDATE saas.orders o SET payment_status=CASE WHEN r.sale_cents-r.return_cents-r.collected_cents<=0 THEN 'completed' ELSE 'pending' END,paid_at=CASE WHEN r.sale_cents-r.return_cents-r.collected_cents<=0 THEN (SELECT max(e.occurred_at) FROM saas.accounting_events e JOIN saas.accounting_allocations a ON a.store_id=e.store_id AND a.event_id=e.id WHERE a.receivable_id=r.id AND e.kind='collection' AND NOT EXISTS(SELECT 1 FROM saas.accounting_events rev WHERE rev.store_id=p_store AND rev.reverses_event_id=e.id)) ELSE NULL END,version=o.version+1,updated_at=greatest(o.updated_at,p_now) FROM saas.accounting_receivables r WHERE o.store_id=p_store AND o.id=p_order AND r.store_id=p_store AND r.order_id=p_order;
 PERFORM set_config('saas.accounting.sync_order',coalesce(previous,''),true);
 END IF;
END $f$;
CREATE FUNCTION saas.accounting_post_pos_sale(p_store uuid,p_order uuid,p_operation uuid,p_customer uuid,p_snapshot jsonb,p_total bigint,p_initial bigint,p_currency text,p_method text,p_due date,p_actor uuid,p_posted_at timestamptz,p_received_at timestamptz,p_receipt_actor uuid DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
DECLARE r uuid;event uuid;receipt uuid;account uuid;BEGIN
 PERFORM pg_advisory_xact_lock_shared(hashtextextended('saas.accounting.release',0));PERFORM pg_advisory_xact_lock(hashtextextended('saas.catalog.store:'||p_store::text,0));PERFORM pg_advisory_xact_lock(hashtextextended('saas.accounting.store:'||p_store::text,0));
 IF EXISTS(SELECT 1 FROM saas.accounting_receivables WHERE store_id=p_store AND order_id=p_order) THEN RETURN saas.accounting_order_finance(p_store,p_order);END IF;
 IF p_total IS NULL OR p_initial IS NULL OR p_total<0 OR p_total>9007199254740991 OR p_initial<0 OR p_initial>p_total OR p_currency!~'^[A-Z]{3}$' OR jsonb_typeof(coalesce(p_snapshot,'{}'))<>'object' OR p_initial>0 AND (p_method IS NULL OR p_method NOT IN('cash','card','bank_transfer') OR p_received_at IS NULL OR NOT isfinite(p_received_at)) OR NOT EXISTS(SELECT 1 FROM saas.orders WHERE store_id=p_store AND id=p_order AND currency=p_currency AND total_cents=p_total) OR NOT EXISTS(SELECT 1 FROM saas.memberships WHERE store_id=p_store AND id=p_actor AND status='active') OR p_posted_at IS NULL OR NOT isfinite(p_posted_at) THEN RAISE EXCEPTION 'ACCOUNTING_POS_INVALID';END IF;
 IF p_initial<p_total AND (p_customer IS NULL OR NOT EXISTS(SELECT 1 FROM saas.customers WHERE store_id=p_store AND id=p_customer AND p_snapshot->>'phone' IS NOT NULL)) THEN RAISE EXCEPTION 'ACCOUNTING_CREDIT_CUSTOMER_REQUIRED';END IF;
 r:=saas.inventory_deterministic_uuid('accounting','saas.accounting.receivable:'||p_store::text||':'||p_order::text);event:=saas.inventory_deterministic_uuid('accounting','saas.accounting.sale:'||p_operation::text);
 INSERT INTO saas.accounting_receivables(id,store_id,customer_id,customer_snapshot,order_id,channel,currency,sale_cents,collected_cents,occurred_at,due_date) VALUES(r,p_store,p_customer,coalesce(p_snapshot,'{}'),p_order,'POS',p_currency,p_total,p_initial,p_posted_at,p_due);
 INSERT INTO saas.accounting_events(id,store_id,operation_id,kind,currency,amount_cents,customer_id,order_id,channel,actor_membership_id,occurred_at,created_at) VALUES(event,p_store,p_operation,'sale',p_currency,p_total,p_customer,p_order,'POS',p_actor,p_posted_at,p_posted_at);
 IF p_initial>0 THEN
 account:=saas.accounting_default_account(p_store,p_currency,p_method,p_posted_at);receipt:=saas.inventory_deterministic_uuid('accounting','saas.accounting.initial-receipt:'||p_operation::text);
 INSERT INTO saas.accounting_events(id,store_id,operation_id,kind,currency,amount_cents,account_id,customer_id,order_id,channel,payment_method,actor_membership_id,occurred_at,created_at) VALUES(receipt,p_store,p_operation,'collection',p_currency,p_initial,account,p_customer,p_order,'POS',p_method,coalesce(p_receipt_actor,p_actor),p_received_at,p_posted_at);
 INSERT INTO saas.accounting_allocations VALUES(p_store,receipt,r,'collect',p_initial);INSERT INTO saas.accounting_account_movements VALUES(p_store,receipt,account,p_initial);UPDATE saas.accounting_accounts SET balance_cents=balance_cents+p_initial,version=version+1 WHERE store_id=p_store AND id=account;
 END IF;
 PERFORM saas.accounting_bump_customer(p_store,p_customer,p_currency);PERFORM saas.accounting_sync_order(p_store,p_order,p_posted_at);RETURN saas.accounting_order_finance(p_store,p_order);
END $f$;
CREATE FUNCTION saas.accounting_intent_valid(p_kind text,p_args jsonb) RETURNS boolean LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,saas AS $f$
DECLARE required text[];k text;v jsonb;parsed_date date;BEGIN
 required:=CASE p_kind
 WHEN 'collect' THEN ARRAY['customerId','orderId','amountCents','currency','paymentMethod','accountId','expectedVersion','note'] WHEN 'openingDebt' THEN ARRAY['customerId','amountCents','currency','occurredOn','note','expectedVersion'] WHEN 'saveAccount' THEN ARRAY['name','type','currency'] WHEN 'openBalance' THEN ARRAY['accountId','amountCents','occurredOn','note','expectedVersion'] WHEN 'expense' THEN ARRAY['accountId','amountCents','currency','category','note','occurredOn','expectedVersion'] WHEN 'transfer' THEN ARRAY['fromAccountId','toAccountId','amountCents','expectedVersion','toExpectedVersion','note'] WHEN 'settleCard' THEN ARRAY['fromAccountId','toAccountId','amountCents','commissionCents','expectedVersion','toExpectedVersion','note'] WHEN 'reverse' THEN ARRAY['eventId','reason','expectedVersion'] WHEN 'returnCredit' THEN ARRAY['orderId','amountCents','reason','expectedVersion'] WHEN 'refund' THEN ARRAY['orderId','accountId','amountCents','paymentMethod','reason','expectedVersion'] ELSE NULL END;
 IF required IS NULL OR p_args IS NULL OR jsonb_typeof(p_args)<>'object' OR pg_column_size(p_args)>16384 OR NOT(p_args?&required) OR EXISTS(SELECT 1 FROM jsonb_object_keys(p_args) key WHERE NOT key=ANY(required) AND NOT(p_kind='expense' AND key='documentNumber')) THEN RETURN false;END IF;
 FOR k,v IN SELECT key,value FROM jsonb_each(p_args) LOOP
 IF right(k,2)='Id' THEN IF v='null'::jsonb AND p_kind='collect' AND k IN('orderId','accountId') THEN CONTINUE;END IF;IF jsonb_typeof(v)<>'string' OR v#>>'{}'!~'^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$' THEN RETURN false;END IF;
 ELSIF k IN('amountCents','commissionCents','expectedVersion','toExpectedVersion') THEN IF jsonb_typeof(v)<>'number' OR (v#>>'{}')::numeric<>trunc((v#>>'{}')::numeric) OR ((v#>>'{}')::numeric < (CASE WHEN k='commissionCents' OR k='expectedVersion' AND p_kind='openingDebt' OR k='amountCents' AND p_kind='openBalance' THEN 0 ELSE 1 END) OR (v#>>'{}')::numeric>9007199254740991) THEN RETURN false;END IF;
 ELSIF k='currency' THEN IF jsonb_typeof(v)<>'string' OR v#>>'{}'!~'^[A-Z]{3}$' THEN RETURN false;END IF;
 ELSIF k='paymentMethod' THEN IF jsonb_typeof(v)<>'string' OR v#>>'{}' NOT IN('cash','card','bank_transfer') THEN RETURN false;END IF;
 ELSIF k='type' THEN IF jsonb_typeof(v)<>'string' OR v#>>'{}' NOT IN('cash','card','bank') THEN RETURN false;END IF;
 ELSIF k='occurredOn' THEN IF jsonb_typeof(v)<>'string' OR v#>>'{}'!~'^\d{4}-\d{2}-\d{2}$' THEN RETURN false;END IF;parsed_date:=(v#>>'{}')::date;IF to_char(parsed_date,'YYYY-MM-DD')<>v#>>'{}' THEN RETURN false;END IF;
 ELSE IF v='null'::jsonb AND (k='note' AND p_kind='collect' OR k='documentNumber') THEN CONTINUE;END IF;IF jsonb_typeof(v)<>'string' OR (length(v#>>'{}')<1 OR length(v#>>'{}')>(CASE WHEN k='name' THEN 200 WHEN k IN('category','documentNumber') THEN 100 ELSE 2000 END)) OR v#>>'{}'<>btrim(v#>>'{}') OR v#>>'{}'~'[[:cntrl:]]' THEN RETURN false;END IF;
 END IF;END LOOP;
 IF p_kind IN('transfer','settleCard') AND (p_args->>'fromAccountId'=p_args->>'toAccountId' OR p_kind='settleCard' AND (p_args->>'commissionCents')::bigint>(p_args->>'amountCents')::bigint) THEN RETURN false;END IF;RETURN true;
 EXCEPTION WHEN invalid_text_representation OR datetime_field_overflow OR numeric_value_out_of_range THEN RETURN false;
END $f$;
CREATE FUNCTION saas.accounting_filters_valid(p_filters jsonb) RETURNS boolean LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,saas AS $f$
DECLARE k text;v jsonb;BEGIN
 IF p_filters IS NULL OR jsonb_typeof(p_filters)<>'object' OR pg_column_size(p_filters)>4096 OR EXISTS(SELECT 1 FROM jsonb_object_keys(p_filters) key WHERE key NOT IN('dateFrom','dateTo','channel','currency','query','customerId','orderId','amountCents')) THEN RETURN false;END IF;
 FOR k,v IN SELECT key,value FROM jsonb_each(p_filters) LOOP
 IF k='amountCents' THEN IF jsonb_typeof(v)<>'number' OR (v#>>'{}')::numeric<>trunc((v#>>'{}')::numeric) OR (v#>>'{}')::numeric NOT BETWEEN 1 AND 9007199254740991 THEN RETURN false;END IF;CONTINUE;END IF;
 IF jsonb_typeof(v)<>'string' THEN RETURN false;END IF;
 IF k IN('dateFrom','dateTo') THEN IF v#>>'{}'!~'^\d{4}-\d{2}-\d{2}$' OR to_char((v#>>'{}')::date,'YYYY-MM-DD')<>v#>>'{}' THEN RETURN false;END IF;
 ELSIF k='channel' THEN IF v#>>'{}' NOT IN('POS','WEB') THEN RETURN false;END IF;
 ELSIF k='currency' THEN IF v#>>'{}'!~'^[A-Z]{3}$' THEN RETURN false;END IF;
 ELSIF right(k,2)='Id' THEN IF v#>>'{}'!~'^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$' THEN RETURN false;END IF;
 ELSE IF length(v#>>'{}') NOT BETWEEN 1 AND 200 OR v#>>'{}'<>btrim(v#>>'{}') OR v#>>'{}'~'[[:cntrl:]]' THEN RETURN false;END IF;END IF;END LOOP;
 IF p_filters?'dateFrom' AND p_filters?'dateTo' AND p_filters->>'dateFrom'>p_filters->>'dateTo' THEN RETURN false;END IF;RETURN true;
 EXCEPTION WHEN invalid_text_representation OR datetime_field_overflow OR numeric_value_out_of_range THEN RETURN false;
END $f$;
-- paid_at includes an old created_at fallback. Only recorded receipt/capture
-- evidence can supply a WEB amount or date to accounting reports.
CREATE FUNCTION saas.accounting_web_payment_evidence(p_store uuid) RETURNS TABLE(order_id uuid,currency text,amount_cents bigint,received_at timestamptz) LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
 WITH evidence AS(
 SELECT a.settled_order_id order_id,a.currency,a.expected_payment_amount amount_cents,a.succeeded_at received_at,1 priority,a.id proof_id FROM saas.checkout_payment_attempts a WHERE a.store_id=p_store AND a.status='succeeded' AND a.succeeded_at IS NOT NULL AND a.settled_order_id IS NOT NULL
 UNION ALL
 SELECT s.order_id,a.currency,a.amount_minor,coalesce((SELECT min(e.occurred_at) FROM saas.payment_attempt_events e WHERE e.store_id=p_store AND e.attempt_id=a.id AND e.to_status='captured' AND e.source IN('callback','reconciliation')),s.terminal_at),2,a.id FROM saas.storefront_hosted_checkout_sessions s JOIN saas.payment_attempts a ON a.store_id=s.store_id AND a.id=s.payment_attempt_id WHERE s.store_id=p_store AND s.status='captured' AND s.terminal_at IS NOT NULL AND a.status IN('captured','partially_refunded','refunded')
 UNION ALL
 SELECT b.order_id,a.currency,a.amount_minor,coalesce((SELECT min(e.occurred_at) FROM saas.payment_attempt_events e WHERE e.store_id=p_store AND e.attempt_id=a.id AND e.to_status='captured' AND e.source IN('callback','reconciliation')),b.settled_at),2,a.id FROM saas.quick_order_hosted_payment_bridges b JOIN saas.payment_attempts a ON a.store_id=b.store_id AND a.id=b.attempt_id WHERE b.store_id=p_store AND b.status='captured' AND b.settled_at IS NOT NULL AND a.status IN('captured','partially_refunded','refunded')
 UNION ALL
 SELECT e.order_id,o.currency,o.total_cents,e.created_at,3,e.id FROM saas.order_events e JOIN saas.orders o ON o.store_id=e.store_id AND o.id=e.order_id WHERE e.store_id=p_store AND e.event_type='payment_transition' AND e.to_value='completed'
 )
 SELECT DISTINCT ON(e.order_id) e.order_id,e.currency,e.amount_cents,e.received_at FROM evidence e JOIN saas.orders o ON o.store_id=p_store AND o.id=e.order_id AND o.currency=e.currency WHERE o.source IN('storefront','quick_link') AND e.received_at IS NOT NULL ORDER BY e.order_id,e.priority,e.received_at,e.proof_id
$f$;
CREATE FUNCTION saas.accounting_read(p_store uuid,p_principal uuid,p_member uuid,p_plan uuid,p_code text,p_version bigint,p_now timestamptz,p_kind text,p_filters jsonb) RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
DECLARE err text;start_at timestamptz;end_at timestamptz;tz text;customer uuid;currency_code text;result jsonb;preview_debt record;leftover bigint;alloc jsonb:='[]';take bigint;BEGIN
 err:=saas.accounting_authority_error(p_store,p_principal,p_member,p_plan,p_code,p_version,p_now,p_kind IN('receivables','customerAccount','orderFinance','previewCollection','collectionAccounts'));IF err IS NOT NULL THEN RETURN QUERY SELECT err,NULL::jsonb;RETURN;END IF;
 IF NOT saas.accounting_filters_valid(p_filters) OR p_kind NOT IN('overview','receivables','customerAccount','accounts','collectionAccounts','expenses','orderFinance','previewCollection') THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;
 tz:=saas.accounting_timezone(p_store);IF NOT EXISTS(SELECT 1 FROM pg_timezone_names WHERE name=tz) THEN RETURN QUERY SELECT 'unavailable',NULL::jsonb;RETURN;END IF;
 start_at:=CASE WHEN p_filters?'dateFrom' THEN (p_filters->>'dateFrom')::date::timestamp AT TIME ZONE tz ELSE '-infinity'::timestamptz END;end_at:=CASE WHEN p_filters?'dateTo' THEN ((p_filters->>'dateTo')::date+1)::timestamp AT TIME ZONE tz ELSE 'infinity'::timestamptz END;
 customer:=(p_filters->>'customerId')::uuid;currency_code:=coalesce(p_filters->>'currency',(SELECT currency FROM saas.stores WHERE id=p_store));
 IF p_kind IN('customerAccount','previewCollection') THEN
 IF customer IS NULL OR NOT EXISTS(SELECT 1 FROM saas.customers WHERE store_id=p_store AND id=customer) THEN RETURN QUERY SELECT 'not_found',NULL::jsonb;RETURN;END IF;
 IF EXISTS(SELECT 1 FROM saas.accounting_receivables WHERE store_id=p_store AND customer_id=customer AND currency=currency_code HAVING sum(greatest(sale_cents-return_cents-collected_cents,0))>9007199254740991 OR sum(greatest(collected_cents-sale_cents+return_cents-refunded_cents,0))>9007199254740991) THEN RETURN QUERY SELECT 'amount_overflow',NULL::jsonb;RETURN;END IF;
 result:=saas.accounting_customer_projection(p_store,customer,currency_code);
 IF p_kind='previewCollection' THEN
 IF NOT(p_filters?'amountCents') THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;leftover:=(p_filters->>'amountCents')::bigint;
 FOR preview_debt IN SELECT * FROM saas.accounting_receivables WHERE store_id=p_store AND customer_id=customer AND currency=currency_code AND (NOT(p_filters?'orderId') OR order_id=(p_filters->>'orderId')::uuid) ORDER BY occurred_at,id LOOP take:=least(leftover,greatest(preview_debt.sale_cents-preview_debt.return_cents-preview_debt.collected_cents,0));IF take>0 THEN alloc:=alloc||jsonb_build_array(jsonb_build_object('receivableId',preview_debt.id,'orderId',preview_debt.order_id,'amountCents',take));leftover:=leftover-take;END IF;END LOOP;
 IF leftover>0 THEN RETURN QUERY SELECT 'overpayment',NULL::jsonb;RETURN;END IF;result:=jsonb_build_object('customerId',customer,'currency',currency_code,'version',result->'version','dueCents',result->'dueCents','allocations',alloc);
 END IF;
 ELSIF p_kind='orderFinance' THEN IF NOT(p_filters?'orderId') OR NOT EXISTS(SELECT 1 FROM saas.orders WHERE store_id=p_store AND id=(p_filters->>'orderId')::uuid) THEN RETURN QUERY SELECT 'not_found',NULL::jsonb;RETURN;END IF;result:=saas.accounting_order_finance(p_store,(p_filters->>'orderId')::uuid);
 ELSIF p_kind='receivables' THEN SELECT jsonb_build_object('receivables',coalesce(jsonb_agg(saas.accounting_receivable_projection(p_store,r.id) ORDER BY r.occurred_at,r.id),'[]'::jsonb)) INTO result FROM saas.accounting_receivables r LEFT JOIN saas.customers c ON c.store_id=r.store_id AND c.id=r.customer_id LEFT JOIN saas.orders o ON o.store_id=r.store_id AND o.id=r.order_id WHERE r.store_id=p_store AND (customer IS NULL OR r.customer_id=customer) AND (NOT(p_filters?'orderId') OR r.order_id=(p_filters->>'orderId')::uuid) AND (NOT(p_filters?'channel') OR r.channel=p_filters->>'channel') AND (NOT(p_filters?'currency') OR r.currency=p_filters->>'currency') AND r.occurred_at>=start_at AND r.occurred_at<end_at AND (NOT(p_filters?'query') OR concat_ws(' ',c.first_name,c.last_name,c.phone,o.order_number) ILIKE '%'||replace(replace(replace(p_filters->>'query','\','\\'),'%','\%'),'_','\_')||'%');
 ELSIF p_kind='collectionAccounts' THEN SELECT jsonb_build_object('accounts',coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'type',account_type,'currency',currency) ORDER BY created_at,id),'[]'::jsonb)) INTO result FROM saas.accounting_accounts WHERE store_id=p_store;
 ELSIF p_kind='accounts' THEN SELECT jsonb_build_object('accounts',coalesce((SELECT jsonb_agg(saas.accounting_account_projection(p_store,id) ORDER BY created_at,id) FROM saas.accounting_accounts WHERE store_id=p_store),'[]'::jsonb),'events',coalesce((SELECT jsonb_agg(saas.accounting_event_projection(p_store,id) ORDER BY occurred_at DESC,id DESC) FROM (SELECT id,occurred_at FROM saas.accounting_events WHERE store_id=p_store AND account_id IS NOT NULL AND occurred_at>=start_at AND occurred_at<end_at ORDER BY occurred_at DESC,id DESC LIMIT 200) recent),'[]'::jsonb)) INTO result;
 ELSIF p_kind='expenses' THEN SELECT jsonb_build_object('expenses',coalesce(jsonb_agg(saas.accounting_event_projection(p_store,id) ORDER BY occurred_at DESC,id DESC),'[]'::jsonb)) INTO result FROM saas.accounting_events WHERE store_id=p_store AND kind IN('expense','card_settlement') AND occurred_at>=start_at AND occurred_at<end_at AND (NOT(p_filters?'currency') OR currency=p_filters->>'currency');
 ELSE
 -- WEB receipts use recorded transition/provider evidence, with no inferred account or commission.
 WITH events AS(
 SELECT coalesce(orig.kind,e.kind) kind,e.currency,CASE WHEN coalesce(orig.kind,e.kind)='collection' AND p_filters?'channel' THEN coalesce((SELECT sum(a.amount_cents::numeric) FROM saas.accounting_allocations a JOIN saas.accounting_receivables allocated ON allocated.store_id=a.store_id AND allocated.id=a.receivable_id WHERE a.store_id=p_store AND a.event_id=e.id AND a.effect='collect' AND allocated.channel=p_filters->>'channel'),0) WHEN e.kind='reversal' THEN -e.amount_cents::numeric ELSE e.amount_cents::numeric END amount,coalesce(orig.metadata,e.metadata) metadata,CASE WHEN e.kind='reversal' THEN -1 ELSE 1 END sign
 FROM saas.accounting_events e LEFT JOIN saas.accounting_events orig ON orig.store_id=e.store_id AND orig.id=e.reverses_event_id
 WHERE e.store_id=p_store AND e.occurred_at>=start_at AND e.occurred_at<end_at AND (NOT(p_filters?'channel') OR coalesce(orig.kind,e.kind)<>'collection' AND e.channel=p_filters->>'channel' OR coalesce(orig.kind,e.kind)='collection' AND EXISTS(SELECT 1 FROM saas.accounting_allocations channel_alloc JOIN saas.accounting_receivables channel_debt ON channel_debt.store_id=channel_alloc.store_id AND channel_debt.id=channel_alloc.receivable_id WHERE channel_alloc.store_id=p_store AND channel_alloc.event_id=e.id AND channel_alloc.effect='collect' AND channel_debt.channel=p_filters->>'channel')) AND (NOT(p_filters?'currency') OR e.currency=p_filters->>'currency')
 ),web AS(
 SELECT payment.currency,sum(payment.amount_cents::numeric) amount FROM saas.accounting_web_payment_evidence(p_store) payment WHERE payment.received_at>=start_at AND payment.received_at<end_at AND (NOT(p_filters?'channel') OR p_filters->>'channel'='WEB') AND (NOT(p_filters?'currency') OR payment.currency=p_filters->>'currency') AND NOT EXISTS(SELECT 1 FROM saas.accounting_receivables r WHERE r.store_id=p_store AND r.order_id=payment.order_id) GROUP BY payment.currency
 ),legacy_pos_sales AS(
 SELECT o.currency,sum(s.total_cents::numeric) amount FROM saas.in_store_sales s JOIN saas.orders o ON o.store_id=s.store_id AND o.id=s.order_id WHERE s.store_id=p_store AND s.status='completed' AND s.completed_at>=start_at AND s.completed_at<end_at AND (NOT(p_filters?'channel') OR p_filters->>'channel'='POS') AND (NOT(p_filters?'currency') OR o.currency=p_filters->>'currency') AND NOT EXISTS(SELECT 1 FROM saas.accounting_receivables r WHERE r.store_id=p_store AND r.order_id=s.order_id) GROUP BY o.currency
 ),legacy_pos_receipts AS(
 SELECT o.currency,sum(a.amount_cents::numeric) amount FROM saas.in_store_payment_attestations a JOIN saas.in_store_sales s ON s.store_id=a.store_id AND s.id=a.sale_id JOIN saas.orders o ON o.store_id=s.store_id AND o.id=s.order_id WHERE s.store_id=p_store AND s.status='completed' AND a.received_at>=start_at AND a.received_at<end_at AND (NOT(p_filters?'channel') OR p_filters->>'channel'='POS') AND (NOT(p_filters?'currency') OR o.currency=p_filters->>'currency') AND NOT EXISTS(SELECT 1 FROM saas.accounting_receivables r WHERE r.store_id=p_store AND r.order_id=s.order_id) GROUP BY o.currency
 ),codes AS(SELECT currency FROM events UNION SELECT currency FROM web UNION SELECT currency FROM legacy_pos_sales UNION SELECT currency FROM legacy_pos_receipts UNION SELECT currency FROM saas.accounting_receivables WHERE store_id=p_store AND (NOT(p_filters?'currency') OR currency=p_filters->>'currency')),
 sums AS(SELECT code.currency,
 coalesce((SELECT sum(amount) FROM events WHERE currency=code.currency AND kind='sale'),0)+coalesce((SELECT amount FROM web WHERE currency=code.currency),0)+coalesce((SELECT amount FROM legacy_pos_sales WHERE currency=code.currency),0) sales,
 coalesce((SELECT sum(amount) FROM events WHERE currency=code.currency AND kind='collection'),0)+coalesce((SELECT amount FROM web WHERE currency=code.currency),0)+coalesce((SELECT amount FROM legacy_pos_receipts WHERE currency=code.currency),0) receipts,
 coalesce((SELECT sum(amount) FROM events WHERE currency=code.currency AND kind='return_credit'),0) returns,coalesce((SELECT sum(amount) FROM events WHERE currency=code.currency AND kind='refund'),0) refunds,coalesce((SELECT sum(amount) FROM events WHERE currency=code.currency AND kind='expense'),0) expenses,coalesce((SELECT sum((metadata->>'commissionCents')::numeric*sign) FROM events WHERE currency=code.currency AND kind='card_settlement'),0) commission,
 coalesce((SELECT sum(greatest(sale_cents-return_cents-collected_cents,0)::numeric) FROM saas.accounting_receivables WHERE store_id=p_store AND currency=code.currency AND (NOT(p_filters?'channel') OR channel=p_filters->>'channel')),0) due,
 coalesce((SELECT sum(greatest(sale_cents-return_cents-collected_cents,0)::numeric) FROM saas.accounting_receivables WHERE store_id=p_store AND currency=code.currency AND due_date<(p_now AT TIME ZONE tz)::date AND (NOT(p_filters?'channel') OR channel=p_filters->>'channel')),0) overdue,
 coalesce((SELECT sum(greatest(collected_cents-sale_cents+return_cents-refunded_cents,0)::numeric) FROM saas.accounting_receivables WHERE store_id=p_store AND currency=code.currency AND (NOT(p_filters?'channel') OR channel=p_filters->>'channel')),0) refund_due,coalesce((SELECT amount FROM web WHERE currency=code.currency),0) web_payments FROM codes code)
 SELECT CASE WHEN EXISTS(SELECT 1 FROM sums WHERE greatest(abs(sales),abs(receipts),abs(returns),abs(refunds),abs(expenses),abs(commission),due,overdue,refund_due,web_payments)>9007199254740991) THEN NULL ELSE jsonb_build_object('currencies',coalesce((SELECT jsonb_agg(jsonb_build_object('currency',currency,'salesCents',sales,'collectionsCents',receipts,'returnCents',returns,'refundsCents',refunds,'expensesCents',expenses,'commissionCents',commission,'dueCents',due,'overdueCents',overdue,'refundDueCents',refund_due,'recordedWebPaymentsCents',web_payments) ORDER BY currency) FROM sums),'[]'::jsonb),'accounts',coalesce((SELECT jsonb_agg(saas.accounting_account_projection(p_store,id) ORDER BY created_at,id) FROM saas.accounting_accounts WHERE store_id=p_store),'[]'::jsonb),'recentEvents',coalesce((SELECT jsonb_agg(saas.accounting_event_projection(p_store,id) ORDER BY occurred_at DESC,id DESC) FROM(SELECT e.id,e.occurred_at FROM saas.accounting_events e WHERE e.store_id=p_store AND e.occurred_at>=start_at AND e.occurred_at<end_at AND (NOT(p_filters?'channel') OR e.channel=p_filters->>'channel') AND (NOT(p_filters?'currency') OR e.currency=p_filters->>'currency') ORDER BY e.occurred_at DESC,e.id DESC LIMIT 100) recent),'[]'::jsonb)) END INTO result;
 IF result IS NULL THEN RETURN QUERY SELECT 'amount_overflow',NULL::jsonb;RETURN;END IF;
 END IF;RETURN QUERY SELECT 'found',result;
END $f$;
CREATE FUNCTION saas.accounting_mutate(p_store uuid,p_principal uuid,p_member uuid,p_plan uuid,p_code text,p_plan_version bigint,p_now timestamptz,p_operation uuid,p_fingerprint text,p_kind text,p_args jsonb) RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
DECLARE err text;prior saas.accounting_operations%ROWTYPE;account saas.accounting_accounts%ROWTYPE;target saas.accounting_accounts%ROWTYPE;debt saas.accounting_receivables%ROWTYPE;original saas.accounting_events%ROWTYPE;r record;event uuid;customer uuid;order_id_value uuid;account_id_value uuid;currency_code text;amount bigint;commission bigint:=0;current_version bigint;leftover bigint;take bigint;occurred timestamptz;kind_value text;note_value text;method text;channel_value text;reverses uuid;metadata_value jsonb:='{}';result jsonb;projection jsonb;refundable bigint;
BEGIN
 err:=saas.accounting_authority_error(p_store,p_principal,p_member,p_plan,p_code,p_plan_version,p_now,p_kind='collect');IF err IS NOT NULL THEN RETURN QUERY SELECT err,NULL::jsonb;RETURN;END IF;
 IF p_operation IS NULL OR p_fingerprint IS NULL OR p_fingerprint!~'^[a-f0-9]{64}$' OR NOT saas.accounting_intent_valid(p_kind,p_args) THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;
 PERFORM pg_advisory_xact_lock_shared(hashtextextended('saas.accounting.release',0));PERFORM pg_advisory_xact_lock(hashtextextended('saas.accounting.operation:'||p_operation::text,0));PERFORM pg_advisory_xact_lock(hashtextextended('saas.catalog.store:'||p_store::text,0));PERFORM pg_advisory_xact_lock(hashtextextended('saas.accounting.store:'||p_store::text,0));
 PERFORM 1 FROM saas.memberships WHERE store_id=p_store AND id=p_member FOR SHARE;PERFORM 1 FROM saas.stores WHERE id=p_store FOR SHARE;PERFORM 1 FROM saas.subscriptions WHERE store_id=p_store AND plan_id=p_plan FOR SHARE;PERFORM 1 FROM saas.in_store_staff_grants WHERE store_id=p_store AND membership_id=p_member FOR SHARE;
 -- Recheck durable role/grant after waiting; revocation never grants a queued writer.
 err:=saas.accounting_authority_error(p_store,p_principal,p_member,p_plan,p_code,p_plan_version,p_now,p_kind='collect');IF err IS NOT NULL THEN RETURN QUERY SELECT err,NULL::jsonb;RETURN;END IF;
 SELECT * INTO prior FROM saas.accounting_operations WHERE operation_id=p_operation;
 IF FOUND THEN IF prior.store_id=p_store AND prior.kind=p_kind AND prior.payload_fingerprint=p_fingerprint AND (prior.actor_membership_id=p_member OR saas.in_store_is_manager(p_store,p_member)) THEN RETURN QUERY SELECT 'operation_replayed',prior.result_payload||jsonb_build_object('replayed',true);ELSE RETURN QUERY SELECT 'operation_mismatch',NULL::jsonb;END IF;RETURN;END IF;
 event:=saas.inventory_deterministic_uuid('accounting','saas.accounting.event:'||p_operation::text);amount:=(p_args->>'amountCents')::bigint;customer:=(p_args->>'customerId')::uuid;order_id_value:=(p_args->>'orderId')::uuid;account_id_value:=(p_args->>'accountId')::uuid;currency_code:=p_args->>'currency';note_value:=coalesce(p_args->>'note',p_args->>'reason');method:=p_args->>'paymentMethod';occurred:=CASE WHEN p_args?'occurredOn' THEN (p_args->>'occurredOn')::date::timestamp AT TIME ZONE saas.accounting_timezone(p_store) ELSE p_now END;
 IF occurred>p_now THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;
 IF p_kind IN('collect','openingDebt') THEN
 IF NOT EXISTS(SELECT 1 FROM saas.customers WHERE store_id=p_store AND id=customer) THEN RETURN QUERY SELECT 'not_found',NULL::jsonb;RETURN;END IF;
 SELECT version INTO current_version FROM saas.accounting_customer_versions WHERE store_id=p_store AND customer_id=customer AND currency=currency_code FOR UPDATE;
 IF coalesce(current_version,0)<>(p_args->>'expectedVersion')::bigint THEN RETURN QUERY SELECT 'version_conflict',NULL::jsonb;RETURN;END IF;
 IF EXISTS(SELECT 1 FROM saas.accounting_receivables WHERE store_id=p_store AND customer_id=customer AND currency=currency_code HAVING sum(sale_cents::numeric)+coalesce(amount,0)>9007199254740991 OR sum(collected_cents::numeric)+coalesce(amount,0)>9007199254740991) THEN RETURN QUERY SELECT 'amount_overflow',NULL::jsonb;RETURN;END IF;
 END IF;
 IF p_kind='saveAccount' THEN account_id_value:=saas.inventory_deterministic_uuid('accounting','saas.accounting.account:'||p_operation::text);INSERT INTO saas.accounting_accounts(id,store_id,name,account_type,currency,created_at) VALUES(account_id_value,p_store,p_args->>'name',p_args->>'type',currency_code,p_now);
 ELSE
 IF p_kind IN('openBalance','expense','refund') THEN
 SELECT * INTO account FROM saas.accounting_accounts WHERE store_id=p_store AND id=account_id_value FOR UPDATE;IF NOT FOUND THEN RETURN QUERY SELECT 'not_found',NULL::jsonb;RETURN;END IF;
 IF p_kind<>'refund' AND account.version<>(p_args->>'expectedVersion')::bigint THEN RETURN QUERY SELECT 'version_conflict',NULL::jsonb;RETURN;END IF;
 IF currency_code IS NOT NULL AND account.currency<>currency_code THEN RETURN QUERY SELECT 'currency_mismatch',NULL::jsonb;RETURN;END IF;currency_code:=account.currency;
 ELSIF p_kind IN('transfer','settleCard') THEN
 SELECT * INTO account FROM saas.accounting_accounts WHERE store_id=p_store AND id=(p_args->>'fromAccountId')::uuid FOR UPDATE;SELECT * INTO target FROM saas.accounting_accounts WHERE store_id=p_store AND id=(p_args->>'toAccountId')::uuid FOR UPDATE;
 IF account.id IS NULL OR target.id IS NULL THEN RETURN QUERY SELECT 'not_found',NULL::jsonb;RETURN;END IF;
 IF account.version<>(p_args->>'expectedVersion')::bigint OR target.version<>(p_args->>'toExpectedVersion')::bigint THEN RETURN QUERY SELECT 'version_conflict',NULL::jsonb;RETURN;END IF;
 IF account.currency<>target.currency THEN RETURN QUERY SELECT 'currency_mismatch',NULL::jsonb;RETURN;END IF;
 IF p_kind='settleCard' AND (account.account_type<>'card' OR target.account_type<>'bank') THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;
 commission:=coalesce((p_args->>'commissionCents')::bigint,0);currency_code:=account.currency;account_id_value:=account.id;metadata_value:=jsonb_build_object('toAccountId',target.id,'grossCents',amount,'netCents',amount-commission,'commissionCents',commission);
 END IF;
 IF p_kind IN('returnCredit','refund') THEN
 SELECT * INTO debt FROM saas.accounting_receivables WHERE store_id=p_store AND order_id=order_id_value FOR UPDATE;IF NOT FOUND THEN RETURN QUERY SELECT 'not_found',NULL::jsonb;RETURN;END IF;
 IF debt.version<>(p_args->>'expectedVersion')::bigint THEN RETURN QUERY SELECT 'version_conflict',NULL::jsonb;RETURN;END IF;
 IF currency_code IS NOT NULL AND currency_code<>debt.currency THEN RETURN QUERY SELECT 'currency_mismatch',NULL::jsonb;RETURN;END IF;currency_code:=debt.currency;customer:=debt.customer_id;channel_value:=debt.channel;
 IF p_kind='returnCredit' AND amount>debt.sale_cents-debt.return_cents THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;
 IF p_kind='refund' AND amount>greatest(debt.collected_cents-debt.sale_cents+debt.return_cents-debt.refunded_cents,0) THEN RETURN QUERY SELECT 'overpayment',NULL::jsonb;RETURN;END IF;
 END IF;
 IF p_kind='collect' THEN
 IF order_id_value IS NOT NULL AND NOT EXISTS(SELECT 1 FROM saas.accounting_receivables WHERE store_id=p_store AND order_id=order_id_value AND customer_id=customer AND currency=currency_code) THEN RETURN QUERY SELECT 'not_found',NULL::jsonb;RETURN;END IF;
 IF amount>(SELECT coalesce(sum(greatest(sale_cents-return_cents-collected_cents,0)),0) FROM saas.accounting_receivables WHERE store_id=p_store AND customer_id=customer AND currency=currency_code AND (order_id_value IS NULL OR order_id=order_id_value)) THEN RETURN QUERY SELECT 'overpayment',NULL::jsonb;RETURN;END IF;
 IF account_id_value IS NULL THEN account_id_value:=saas.accounting_default_account(p_store,currency_code,method,p_now);END IF;
 SELECT * INTO account FROM saas.accounting_accounts WHERE store_id=p_store AND id=account_id_value FOR UPDATE;IF NOT FOUND THEN RETURN QUERY SELECT 'not_found',NULL::jsonb;RETURN;END IF;
 IF account.currency<>currency_code THEN RETURN QUERY SELECT 'currency_mismatch',NULL::jsonb;RETURN;END IF;
 IF account.account_type<>(CASE method WHEN 'bank_transfer' THEN 'bank' ELSE method END) THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;
 -- A customer receipt can span POS/WEB only when real receivables exist. Channel follows allocations.
 WITH fifo_debts AS(SELECT channel,coalesce(sum(greatest(sale_cents-return_cents-collected_cents,0)::numeric) OVER(ORDER BY occurred_at,id ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING),0) prior_due FROM saas.accounting_receivables WHERE store_id=p_store AND customer_id=customer AND currency=currency_code AND (order_id_value IS NULL OR order_id=order_id_value) AND sale_cents-return_cents-collected_cents>0) SELECT CASE WHEN count(DISTINCT channel)=1 AND count(*) FILTER(WHERE channel IS NULL)=0 THEN min(channel) ELSE NULL END INTO channel_value FROM fifo_debts WHERE prior_due<amount;
 END IF;
 IF p_kind IN('collect','openBalance') AND account.balance_cents::numeric+amount>9007199254740991 OR p_kind IN('expense','refund','transfer','settleCard') AND account.balance_cents<amount OR p_kind IN('transfer','settleCard') AND target.balance_cents::numeric+amount-commission>9007199254740991 THEN RETURN QUERY SELECT CASE WHEN p_kind IN('expense','refund','transfer','settleCard') AND account.balance_cents<amount THEN 'insufficient_funds' ELSE 'amount_overflow' END,NULL::jsonb;RETURN;END IF;
 IF p_kind='refund' AND account.account_type<>(CASE method WHEN 'bank_transfer' THEN 'bank' ELSE method END) THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;
 IF p_kind='reverse' THEN
 SELECT * INTO original FROM saas.accounting_events WHERE store_id=p_store AND id=(p_args->>'eventId')::uuid;IF NOT FOUND THEN RETURN QUERY SELECT 'not_found',NULL::jsonb;RETURN;END IF;
 IF original.kind IN('sale','reversal') OR EXISTS(SELECT 1 FROM saas.accounting_events WHERE store_id=p_store AND reverses_event_id=original.id) THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
 customer:=original.customer_id;currency_code:=original.currency;order_id_value:=original.order_id;account_id_value:=original.account_id;amount:=original.amount_cents;channel_value:=original.channel;reverses:=original.id;metadata_value:=jsonb_build_object('reversedKind',original.kind);
 IF customer IS NOT NULL THEN SELECT version INTO current_version FROM saas.accounting_customer_versions WHERE store_id=p_store AND customer_id=customer AND currency=currency_code FOR UPDATE;
 ELSIF order_id_value IS NOT NULL THEN SELECT version INTO current_version FROM saas.accounting_receivables WHERE store_id=p_store AND order_id=order_id_value FOR UPDATE;
 ELSE SELECT version INTO current_version FROM saas.accounting_accounts WHERE store_id=p_store AND id=account_id_value FOR UPDATE;END IF;
 IF current_version IS NULL OR current_version<>(p_args->>'expectedVersion')::bigint THEN RETURN QUERY SELECT 'version_conflict',NULL::jsonb;RETURN;END IF;
 FOR r IN SELECT m.*,a.balance_cents FROM saas.accounting_account_movements m JOIN saas.accounting_accounts a ON a.store_id=m.store_id AND a.id=m.account_id WHERE m.store_id=p_store AND m.event_id=original.id ORDER BY m.account_id FOR UPDATE OF a LOOP IF r.balance_cents::numeric-r.amount_cents NOT BETWEEN 0 AND 9007199254740991 THEN RETURN QUERY SELECT 'insufficient_funds',NULL::jsonb;RETURN;END IF;END LOOP;
 FOR r IN SELECT a.*,d.sale_cents,d.collected_cents,d.return_cents,d.refunded_cents FROM saas.accounting_allocations a JOIN saas.accounting_receivables d ON d.store_id=a.store_id AND d.id=a.receivable_id WHERE a.store_id=p_store AND a.event_id=original.id ORDER BY d.id FOR UPDATE OF d LOOP
 IF r.effect='collect' AND (r.collected_cents<r.amount_cents OR r.refunded_cents>greatest(r.collected_cents-r.amount_cents-r.sale_cents+r.return_cents,0)) OR r.effect='return' AND (r.return_cents<r.amount_cents OR r.refunded_cents>greatest(r.collected_cents-r.sale_cents+r.return_cents-r.amount_cents,0)) OR r.effect='refund' AND r.refunded_cents<r.amount_cents OR r.effect='charge' AND (r.collected_cents>0 OR r.return_cents>0) THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb;RETURN;END IF;
 END LOOP;
 END IF;
 kind_value:=CASE p_kind WHEN 'collect' THEN 'collection' WHEN 'reverse' THEN 'reversal' WHEN 'openingDebt' THEN 'opening_debt' WHEN 'openBalance' THEN 'account_opening' WHEN 'settleCard' THEN 'card_settlement' WHEN 'returnCredit' THEN 'return_credit' ELSE p_kind END;
 INSERT INTO saas.accounting_events(id,store_id,operation_id,kind,currency,amount_cents,account_id,customer_id,order_id,channel,payment_method,note,category,document_number,actor_membership_id,occurred_at,created_at,reverses_event_id,metadata) VALUES(event,p_store,p_operation,kind_value,currency_code,amount,account_id_value,customer,order_id_value,channel_value,method,note_value,p_args->>'category',p_args->>'documentNumber',p_member,occurred,p_now,reverses,metadata_value);
 IF p_kind='openingDebt' THEN
 INSERT INTO saas.accounting_receivables(id,store_id,customer_id,customer_snapshot,currency,sale_cents,occurred_at) SELECT event,p_store,customer,jsonb_build_object('name',concat_ws(' ',first_name,last_name),'phone',phone),currency_code,amount,occurred FROM saas.customers WHERE store_id=p_store AND id=customer;
 INSERT INTO saas.accounting_allocations VALUES(p_store,event,event,'charge',amount);
 ELSIF p_kind='collect' THEN
 leftover:=amount;FOR debt IN SELECT * FROM saas.accounting_receivables WHERE store_id=p_store AND customer_id=customer AND currency=currency_code AND (order_id_value IS NULL OR order_id=order_id_value) ORDER BY occurred_at,id FOR UPDATE LOOP take:=least(leftover,greatest(debt.sale_cents-debt.return_cents-debt.collected_cents,0));IF take>0 THEN INSERT INTO saas.accounting_allocations VALUES(p_store,event,debt.id,'collect',take);UPDATE saas.accounting_receivables SET collected_cents=collected_cents+take,version=version+1 WHERE store_id=p_store AND id=debt.id;PERFORM saas.accounting_sync_order(p_store,debt.order_id,p_now);leftover:=leftover-take;END IF;EXIT WHEN leftover=0;END LOOP;
 INSERT INTO saas.accounting_account_movements VALUES(p_store,event,account_id_value,amount);UPDATE saas.accounting_accounts SET balance_cents=balance_cents+amount,version=version+1 WHERE store_id=p_store AND id=account_id_value;
 ELSIF p_kind IN('returnCredit','refund') THEN
 INSERT INTO saas.accounting_allocations VALUES(p_store,event,debt.id,CASE p_kind WHEN 'refund' THEN 'refund' ELSE 'return' END,amount);
 UPDATE saas.accounting_receivables SET return_cents=return_cents+CASE WHEN p_kind='returnCredit' THEN amount ELSE 0 END,refunded_cents=refunded_cents+CASE WHEN p_kind='refund' THEN amount ELSE 0 END,version=version+1 WHERE store_id=p_store AND id=debt.id;
 IF p_kind='refund' THEN INSERT INTO saas.accounting_account_movements VALUES(p_store,event,account_id_value,-amount);UPDATE saas.accounting_accounts SET balance_cents=balance_cents-amount,version=version+1 WHERE store_id=p_store AND id=account_id_value;END IF;PERFORM saas.accounting_sync_order(p_store,order_id_value,p_now);
 ELSIF p_kind IN('openBalance','expense','transfer','settleCard') THEN
 INSERT INTO saas.accounting_account_movements VALUES(p_store,event,account_id_value,CASE p_kind WHEN 'openBalance' THEN amount ELSE -amount END);UPDATE saas.accounting_accounts SET balance_cents=balance_cents+CASE p_kind WHEN 'openBalance' THEN amount ELSE -amount END,version=version+1 WHERE store_id=p_store AND id=account_id_value;
 IF p_kind IN('transfer','settleCard') THEN INSERT INTO saas.accounting_account_movements VALUES(p_store,event,target.id,amount-commission);UPDATE saas.accounting_accounts SET balance_cents=balance_cents+amount-commission,version=version+1 WHERE store_id=p_store AND id=target.id;END IF;
 ELSE
 FOR r IN SELECT * FROM saas.accounting_allocations WHERE store_id=p_store AND event_id=original.id LOOP
 INSERT INTO saas.accounting_allocations VALUES(p_store,event,r.receivable_id,r.effect,-r.amount_cents);
 UPDATE saas.accounting_receivables SET collected_cents=collected_cents-CASE WHEN r.effect='collect' THEN r.amount_cents ELSE 0 END,return_cents=return_cents-CASE WHEN r.effect='return' THEN r.amount_cents ELSE 0 END,refunded_cents=refunded_cents-CASE WHEN r.effect='refund' THEN r.amount_cents ELSE 0 END,sale_cents=sale_cents-CASE WHEN r.effect='charge' THEN r.amount_cents ELSE 0 END,version=version+1 WHERE store_id=p_store AND id=r.receivable_id;
 PERFORM saas.accounting_sync_order(p_store,(SELECT order_id FROM saas.accounting_receivables WHERE store_id=p_store AND id=r.receivable_id),p_now);
 END LOOP;
 FOR r IN SELECT * FROM saas.accounting_account_movements WHERE store_id=p_store AND event_id=original.id LOOP INSERT INTO saas.accounting_account_movements VALUES(p_store,event,r.account_id,-r.amount_cents);UPDATE saas.accounting_accounts SET balance_cents=balance_cents-r.amount_cents,version=version+1 WHERE store_id=p_store AND id=r.account_id;END LOOP;
 END IF;
 PERFORM saas.accounting_bump_customer(p_store,customer,currency_code);
 END IF;
 result:=jsonb_build_object('operationId',p_operation,'replayed',false,'event',CASE WHEN p_kind='saveAccount' THEN NULL ELSE saas.accounting_event_projection(p_store,event) END,'account',CASE WHEN saas.in_store_is_manager(p_store,p_member) THEN saas.accounting_account_projection(p_store,account_id_value) ELSE NULL END,'customerAccount',saas.accounting_customer_projection(p_store,customer,currency_code),'finance',saas.accounting_order_finance(p_store,order_id_value));
 -- Keep the exact frozen operation payload for ambiguous-commit recovery.
 INSERT INTO saas.accounting_operations VALUES(p_operation,p_store,p_member,p_kind,p_fingerprint,result,p_now);RETURN QUERY SELECT 'committed',result;
END $f$;
CREATE FUNCTION saas.accounting_get_operation(p_store uuid,p_principal uuid,p_member uuid,p_plan uuid,p_code text,p_version bigint,p_now timestamptz,p_operation uuid,p_expected_fingerprint text DEFAULT NULL) RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
DECLARE err text;prior saas.accounting_operations%ROWTYPE;BEGIN
 err:=saas.accounting_authority_error(p_store,p_principal,p_member,p_plan,p_code,p_version,p_now,true);IF err IS NOT NULL THEN RETURN QUERY SELECT err,NULL::jsonb;RETURN;END IF;
 IF p_operation IS NULL OR p_expected_fingerprint IS NOT NULL AND p_expected_fingerprint!~'^[a-f0-9]{64}$' THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb;RETURN;END IF;
 SELECT * INTO prior FROM saas.accounting_operations WHERE operation_id=p_operation AND store_id=p_store AND (actor_membership_id=p_member OR saas.in_store_is_manager(p_store,p_member));
 IF NOT FOUND THEN RETURN QUERY SELECT 'found',NULL::jsonb;RETURN;END IF;
 IF NOT saas.in_store_is_manager(p_store,p_member) AND prior.kind<>'collect' THEN RETURN QUERY SELECT 'membership_denied',NULL::jsonb;RETURN;END IF;
 IF p_expected_fingerprint IS NOT NULL AND prior.payload_fingerprint<>p_expected_fingerprint THEN RETURN QUERY SELECT 'operation_mismatch',NULL::jsonb;RETURN;END IF;
 RETURN QUERY SELECT 'found',prior.result_payload||jsonb_build_object('replayed',true);
END $f$;
DO $grants$ DECLARE r record;BEGIN
 FOR r IN SELECT oid::regprocedure::text signature,proname FROM pg_proc WHERE pronamespace='saas'::regnamespace AND proname LIKE 'accounting_%' LOOP
 EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,celebix_saas_app,celebix_saas_identity,celebix_saas_bootstrap,celebix_saas_workflow,celebix_saas_host_resolver,celebix_saas_observability',r.signature);
 IF r.proname IN('accounting_read','accounting_mutate','accounting_get_operation') THEN EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO celebix_saas_app',r.signature);END IF;
 END LOOP;
END $grants$;
COMMIT;
