-- Self-contained acceptance. The fixture and all awards/orders roll back.
BEGIN;
\ir 202610100226_lucky_wheel_fixtures.sql
SET LOCAL statement_timeout='120s';
DO $access$ DECLARE t text;draw integer;BEGIN
 FOREACH t IN ARRAY ARRAY['lucky_wheel_campaigns','lucky_wheel_campaign_versions','lucky_wheel_rewards','lucky_wheel_awards','lucky_wheel_admin_operations','lucky_wheel_events','lucky_wheel_prize_counters','lucky_wheel_request_limits'] LOOP
 IF NOT(SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid=to_regclass('saas.'||t)) OR has_table_privilege('celebix_saas_app','saas.'||t,'SELECT,INSERT,UPDATE,DELETE') OR has_table_privilege('celebix_saas_host_resolver','saas.'||t,'SELECT,INSERT,UPDATE,DELETE') THEN RAISE EXCEPTION 'WHEEL_PRIVATE_ACCESS:%',t;END IF;END LOOP;
 IF has_function_privilege('celebix_saas_app','saas.lucky_wheel_spin_v1(text,text,timestamptz,uuid,uuid,bigint,text,text,boolean,text)','EXECUTE') OR has_function_privilege('celebix_saas_host_resolver','saas.lucky_wheel_campaign_save_v1(uuid,uuid,uuid,uuid,text,bigint,timestamptz,uuid,text,uuid,bigint,text,boolean,jsonb)','EXECUTE') OR has_function_privilege('public','saas.lucky_wheel_code_eligible_v1(uuid,uuid,jsonb,timestamptz)','EXECUTE') THEN RAISE EXCEPTION 'WHEEL_ENTRYPOINT_ACCESS';END IF;
 IF EXISTS(SELECT 1 FROM saas.lucky_wheel_function_baseline b JOIN pg_proc p ON p.oid=to_regprocedure(b.identity) WHERE md5(pg_get_functiondef(p.oid))<>b.patched_hash OR p.proowner<>b.owner_oid OR p.proacl::text IS DISTINCT FROM b.acl) THEN RAISE EXCEPTION 'WHEEL_NATIVE_AUTH_DRIFT';END IF;
FOR draw IN 1..1000 LOOP IF saas.lucky_wheel_random_bps_v1() NOT BETWEEN 0 AND 9999 THEN RAISE EXCEPTION 'WHEEL_RANDOM_BOUNDS';END IF;END LOOP;
END $access$;
DO $tests$
DECLARE st uuid:='22600000-0000-4000-8000-000000000001';principal uuid:='22600000-0000-4000-8000-000000000011';membership uuid:='22600000-0000-4000-8000-000000000021';plan uuid:='22600000-0000-4000-8000-000000000010';n timestamptz:=date_trunc('milliseconds',clock_timestamp());source uuid:=gen_random_uuid();rule jsonb;config jsonb;campaign uuid;op uuid:=gen_random_uuid();result jsonb;r record;r2 record;a saas.lucky_wheel_awards;context jsonb;eval jsonb;reserve_op uuid:=gen_random_uuid();order_id uuid:=gen_random_uuid();group_id uuid;fp text;batch uuid:=gen_random_uuid();batch_code text;new_config jsonb;legacy uuid:=gen_random_uuid();old_label text;old_rule jsonb;managed uuid;revocation jsonb;row_id uuid:='22600000-0000-4000-8000-000000000052';
BEGIN
 rule:=jsonb_build_object('schemaVersion',1,'benefit',jsonb_build_object('kind','percentage','percentageBps',500),'targets',jsonb_build_object('mode','all','include','[]'::jsonb,'exclude','[]'::jsonb),'audience',jsonb_build_object('mode','everyone'),'trigger',jsonb_build_object('kind','code','codes',jsonb_build_array('SOURCE')),'schedule',jsonb_build_object('timezone','Europe/Istanbul','startsAt',saas.merchant_admin_timestamp(n-interval '1 hour'),'endsAt',saas.merchant_admin_timestamp(n+interval '2 hours')),'limits',jsonb_build_object('totalUsage',NULL,'perCustomerUsage',NULL,'budgetMinor',NULL,'orderMaximumMinor',NULL),'conditions',jsonb_build_object('minimumBasketMinor',0,'minimumQuantity',0,'minimumProductQuantity',0,'salesChannels',jsonb_build_array('storefront')),'combinationPolicy',jsonb_build_object('kind','none'),'priority',1,'marginPolicy',jsonb_build_object('kind','warn'),'progressMessagePolicy',jsonb_build_object('enabled',false));
 INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES(source,st,'Source %5','active',1,rule,n,n);INSERT INTO saas.promotion_versions(id,store_id,promotion_id,version,rule_document,created_at) VALUES(gen_random_uuid(),st,source,1,rule,n);
 config:=jsonb_build_object('schemaVersion',1,'heading','Fixture','body','Contact first','appearance',jsonb_build_object('sliceA','#ffffff','sliceB','#eeeeee','background','#ffffff','accent','#ff8800'),'collectMode','either','repeatDays',7,'couponHours',24,'marketingOptInLabel','Fixture opt-in v1','devices',jsonb_build_object('desktop',true,'mobile',true),'allowedPaths','[]'::jsonb,'scrollPercent',NULL,'startsAt',NULL,'endsAt',NULL,'prizes',(SELECT jsonb_agg(jsonb_build_object('id',gen_random_uuid(),'promotionId',source,'weightBps',2500,'issuanceLimit',10)) FROM generate_series(1,4)));
 SELECT * INTO r FROM saas.lucky_wheel_campaign_save_v1(st,principal,membership,plan,'wheel_fixture',1,n,gen_random_uuid(),repeat('1',64),NULL,NULL,'Fixture wheel',true,config);IF r.outcome<>'saved' THEN RAISE EXCEPTION 'WHEEL_SAVE:%',r.outcome;END IF;campaign:=(r.result_payload->>'id')::uuid;
 INSERT INTO saas.merchant_admin_records(id,store_id,record_kind,name,config,status,version,created_at,updated_at) VALUES(legacy,st,'lucky_wheel','Old free text','{"prizeLabels":["Free-text prize"]}','active',1,n,n);
 SELECT * INTO r FROM saas.lucky_wheel_campaign_list_v1(st,principal,membership,plan,'wheel_fixture',1,n);IF jsonb_array_length(r.result_payload)<>2 OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements(r.result_payload) p WHERE p->>'id'=legacy::text AND p->'legacy'='true'::jsonb AND p->'config'='null'::jsonb AND p->'enabled'='false'::jsonb) THEN RAISE EXCEPTION 'WHEEL_LEGACY_PRESERVATION';END IF;
 INSERT INTO saas.merchant_admin_records(id,store_id,record_kind,name,config,status,version,created_at,updated_at,archived_at) SELECT gen_random_uuid(),st,'lucky_wheel','Legacy visibility fixture','{"prizeLabels":["Historical text"]}','archived',1,n,n,n FROM generate_series(1,199);
 SELECT * INTO r FROM saas.lucky_wheel_campaign_list_v1(st,principal,membership,plan,'wheel_fixture',1,n);IF jsonb_array_length(r.result_payload)<>201 THEN RAISE EXCEPTION 'WHEEL_FULL_LEGACY_VISIBILITY';END IF;
 SELECT * INTO r FROM saas.lucky_wheel_public_settings_v1('wheel-a.example.invalid',n);IF r.result_payload->'campaign'->>'id'<>campaign::text OR r.result_payload::text LIKE '%email%' OR r.result_payload::text LIKE '%couponCode%' THEN RAISE EXCEPTION 'WHEEL_PUBLIC_SETTINGS';END IF;
 SELECT * INTO r FROM saas.lucky_wheel_campaign_save_v1(st,principal,membership,plan,'wheel_fixture',1,n,gen_random_uuid(),repeat('2',64),NULL,NULL,'Second enabled',true,config);IF r.outcome<>'active_campaign_conflict' THEN RAISE EXCEPTION 'WHEEL_SINGLE_ENABLED';END IF;
 SELECT * INTO r FROM saas.lucky_wheel_spin_v1('wheel-a.example.invalid',repeat('a',64),n,op,campaign,1,'award@example.invalid',NULL,false,repeat('3',64));IF r.outcome<>'saved' THEN RAISE EXCEPTION 'WHEEL_SPIN:%',r.outcome;END IF;result:=r.result_payload;
 IF result->>'label'<>'%5 indirim' OR result->>'expiresAt'<>saas.merchant_admin_timestamp(n+interval '2 hours') OR result?'email' OR result?'phone' OR EXISTS(SELECT 1 FROM saas.email_marketing_consent_events ce WHERE ce.source='lucky_wheel') THEN RAISE EXCEPTION 'WHEEL_FIXED_RESULT_OR_NO_CONSENT';END IF;
 SELECT * INTO r FROM saas.lucky_wheel_spin_v1('wheel-a.example.invalid',repeat('a',64),n,op,campaign,1,'award@example.invalid',NULL,false,repeat('3',64));IF r.outcome<>'replayed' OR r.result_payload<>result THEN RAISE EXCEPTION 'WHEEL_EXACT_REPLAY';END IF;
 SELECT * INTO r FROM saas.lucky_wheel_spin_v1('wheel-a.example.invalid',repeat('a',64),n,gen_random_uuid(),campaign,1,'different@example.invalid',NULL,false,repeat('4',64));IF r.outcome<>'repeat_limited' OR(SELECT count(*) FROM saas.lucky_wheel_awards)<>1 THEN RAISE EXCEPTION 'WHEEL_VISITOR_WINDOW';END IF;
 SELECT * INTO r FROM saas.lucky_wheel_result_v1('wheel-a.example.invalid',repeat('b',64),n,campaign,op);IF r.result_payload IS NOT NULL THEN RAISE EXCEPTION 'WHEEL_OTHER_VISITOR_RECOVERY';END IF;SELECT * INTO r FROM saas.lucky_wheel_result_v1('wheel-b.example.invalid',repeat('a',64),n,campaign,op);IF r.result_payload IS NOT NULL THEN RAISE EXCEPTION 'WHEEL_OTHER_TENANT_RECOVERY';END IF;
 SELECT * INTO r FROM saas.lucky_wheel_spin_v1('wheel-a.example.invalid',repeat('b',64),n,gen_random_uuid(),campaign,1,'optin@example.invalid',NULL,true,repeat('5',64));IF r.outcome<>'saved' OR(SELECT count(*) FROM saas.email_marketing_consent_events ce WHERE ce.source='lucky_wheel' AND evidence_version='lucky-wheel-1')<>1 OR EXISTS(SELECT 1 FROM saas.email_marketing_sync_jobs) THEN RAISE EXCEPTION 'WHEEL_OPTIONAL_CONSENT_ATOMIC';END IF;
 SELECT * INTO a FROM saas.lucky_wheel_awards WHERE operation_id=op;SELECT managed_promotion_id,rule_document INTO managed,old_rule FROM saas.lucky_wheel_rewards WHERE id=a.reward_id;
 context:=jsonb_build_object('storeId',st,'customerId',NULL,'paidOrderCount',0,'customerSegmentIds','[]'::jsonb,'customerTagIds','[]'::jsonb,'cartLines',jsonb_build_array(jsonb_build_object('lineId',row_id,'position',0,'productId','22600000-0000-4000-8000-000000000050','variantId','22600000-0000-4000-8000-000000000051','quantity',1,'unitPriceMinor',10000,'unitCostMinor',5000,'currency','TRY','categoryIds','[]'::jsonb,'brandId',NULL,'collectionIds','[]'::jsonb)),'shippingMethodId',NULL,'paymentMethodId',NULL,'shippingBeforeDiscountMinor',0,'currency','TRY','storeLocalTime',saas.merchant_admin_timestamp(n),'salesChannel','storefront','submittedCodes',jsonb_build_array(a.coupon_code),'abandonedCart',NULL);
 eval:=saas.promotion_evaluate_v1(st,context,n);IF eval->>'discountTotalMinor'<>'500' OR jsonb_array_length(eval->'appliedPromotions')<>1 THEN RAISE EXCEPTION 'WHEEL_GUEST_EVALUATION:%',eval;END IF;
 IF saas.promotion_evaluate_v1(st,jsonb_set(context,'{salesChannel}','"quick_order"'),n)->>'discountTotalMinor'<>'0' THEN RAISE EXCEPTION 'WHEEL_WEB_ONLY';END IF;
 IF saas.promotion_evaluate_v1(st,jsonb_set(context,'{submittedCodes}','[]'),n)->>'discountTotalMinor'<>'0' THEN RAISE EXCEPTION 'WHEEL_CODE_SOURCE_NO_AUTOMATIC_DISCOUNT';END IF;
 -- A genuine ordinary batch keeps its existing authenticated-customer lane.
 fp:=saas.promotion_operation_fingerprint_v2('code_batch',st,jsonb_build_object('promotionId',source,'count',1,'prefix','REG','codeLength',20,'perCustomerUsage',1,'expiresAt',NULL));SELECT * INTO r FROM saas.promotion_create_code_batch_v1(st,principal,membership,plan,'wheel_fixture',1,n,gen_random_uuid(),fp,batch,source,1,'REG',20,1,NULL);IF r.outcome<>'created' THEN RAISE EXCEPTION 'WHEEL_BATCH_SETUP:%',r.outcome;END IF;SELECT code INTO batch_code FROM saas.promotion_codes WHERE batch_id=batch;
 IF saas.promotion_evaluator_code_facts(st,jsonb_set(context,'{submittedCodes}',jsonb_build_array(batch_code)),n)<>'{}'::jsonb THEN RAISE EXCEPTION 'WHEEL_ORDINARY_BATCH_GUEST_REGRESSION';END IF;
 -- Source edit creates different future promises; award snapshot remains byte-for-byte fixed.
 UPDATE saas.promotions SET rule_document=jsonb_set(rule_document,'{benefit,percentageBps}','2000'),version=2,updated_at=n WHERE store_id=st AND id=source;INSERT INTO saas.promotion_versions(id,store_id,promotion_id,version,rule_document,created_at) SELECT gen_random_uuid(),st,source,2,rule_document,n FROM saas.promotions WHERE store_id=st AND id=source;
 SELECT * INTO r FROM saas.lucky_wheel_campaign_save_v1(st,principal,membership,plan,'wheel_fixture',1,n,gen_random_uuid(),repeat('6',64),campaign,1,'Updated wheel',true,config);IF r.outcome<>'saved' OR(SELECT sum(issued) FROM saas.lucky_wheel_prize_counters)<>2 THEN RAISE EXCEPTION 'WHEEL_REVISION_AND_COUNTERS';END IF;IF saas.promotion_evaluate_v1(st,context,n)->>'discountTotalMinor'<>'500' THEN RAISE EXCEPTION 'WHEEL_OLD_AWARD_MUTATED';END IF;
 BEGIN UPDATE saas.promotions SET name='Tampered' WHERE store_id=st AND id=managed;RAISE EXCEPTION 'WHEEL_MANAGED_MUTATION_ALLOWED';EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'LUCKY_WHEEL_MANAGED_IMMUTABLE' THEN RAISE;END IF;END;
 -- A new award uses revised 20% conditions. Deleting its source blocks future spins but cannot change promised codes.
 SELECT * INTO r FROM saas.lucky_wheel_spin_v1('wheel-a.example.invalid',repeat('c',64),n,gen_random_uuid(),campaign,2,'third@example.invalid',NULL,false,repeat('a',64));IF r.outcome<>'saved' OR r.result_payload->>'label'<>'%20 indirim' THEN RAISE EXCEPTION 'WHEEL_NEW_REVISION_AWARD';END IF;new_config:=r.result_payload;
 SELECT * INTO r FROM saas.promotion_delete_v1(st,principal,membership,plan,'wheel_fixture',1,n,gen_random_uuid(),saas.promotion_delete_fingerprint_v1(st,source,2),source,2);IF r.outcome<>'deleted' THEN RAISE EXCEPTION 'WHEEL_SOURCE_DELETE:%',r.outcome;END IF;
 IF saas.promotion_evaluate_v1(st,jsonb_set(context,'{submittedCodes}',jsonb_build_array(new_config->>'couponCode')),n)->>'discountTotalMinor'<>'2000' THEN RAISE EXCEPTION 'WHEEL_SOURCE_DELETE_PROMISE';END IF;
 SELECT * INTO r FROM saas.lucky_wheel_spin_v1('wheel-a.example.invalid',repeat('d',64),n,gen_random_uuid(),campaign,2,'blocked@example.invalid',NULL,false,repeat('b',64));IF r.outcome<>'campaign_unavailable' THEN RAISE EXCEPTION 'WHEEL_SOURCE_DELETE_FUTURE';END IF;
 SELECT * INTO r FROM saas.lucky_wheel_campaign_save_v1(st,principal,membership,plan,'wheel_fixture',1,n,gen_random_uuid(),repeat('c',64),campaign,2,'Paused after removal',false,config);IF r.outcome<>'saved' OR r.result_payload->'enabled'<>'false'::jsonb THEN RAISE EXCEPTION 'WHEEL_SOURCE_DELETE_PAUSE:%',r.outcome;END IF;
 SELECT * INTO r FROM saas.lucky_wheel_spin_v1('wheel-a.example.invalid',repeat('d',64),n,gen_random_uuid(),campaign,2,'blocked@example.invalid',NULL,false,repeat('d',64));IF r.outcome<>'version_conflict' THEN RAISE EXCEPTION 'WHEEL_SAVE_SPIN_VERSION';END IF;
 -- Native reserve owns the code; repeated operation returns the same hold, other owned carts cannot acquire it.
 fp:=saas.promotion_operation_fingerprint_v2('reserve',st,jsonb_build_object('sourceKind','offline_checkout','sourceReference',order_id::text,'evaluatorContext',context));SELECT * INTO r FROM saas.promotion_reserve_group_v1(st,reserve_op,fp,'offline_checkout',order_id::text,context,n);IF r.outcome<>'reserved' THEN RAISE EXCEPTION 'WHEEL_NATIVE_RESERVE:%',r.outcome;END IF;group_id:=(r.result_payload->>'reservationGroupId')::uuid;
 SELECT * INTO r2 FROM saas.promotion_reserve_group_v1(st,reserve_op,fp,'offline_checkout',order_id::text,context,n);IF r2.outcome<>'operation_replayed' OR r2.result_payload<>r.result_payload THEN RAISE EXCEPTION 'WHEEL_OWNED_RESERVE_REPLAY';END IF;
 IF saas.promotion_evaluator_code_facts(st,context,n)<>'{}'::jsonb THEN RAISE EXCEPTION 'WHEEL_OTHER_CART_HOLD';END IF;
 SELECT * INTO r FROM saas.lucky_wheel_campaign_revoke_v1(st,principal,membership,plan,'wheel_fixture',1,n,gen_random_uuid(),repeat('7',64),campaign,3);IF r.outcome<>'saved' OR r.result_payload->>'held'<>'1' OR r.result_payload->>'revoked'<>'2' THEN RAISE EXCEPTION 'WHEEL_REVOKE_HOLD:%',r.result_payload;END IF;
 SELECT * INTO r FROM saas.lucky_wheel_campaign_delete_v1(st,principal,membership,plan,'wheel_fixture',1,n,gen_random_uuid(),repeat('8',64),campaign,3);IF r.outcome<>'saved' OR r.result_payload->'issuedCouponsPreserved'<>'true'::jsonb THEN RAISE EXCEPTION 'WHEEL_DELETE';END IF;
 INSERT INTO saas.orders(id,store_id,order_number,source,customer_name,customer_email,currency,subtotal_cents,shipping_cents,discount_cents,total_cents,status,payment_status,shipping_address,version,created_at,updated_at,paid_at) VALUES(order_id,st,'WHEEL-FIXTURE-ORDER','storefront','Fixture','purchase@example.invalid','TRY',10000,0,500,9500,'confirmed','completed','{}',1,n,n,n);
 INSERT INTO saas.order_items(id,store_id,order_id,product_id,variant_id,position,product_name,variant_name,unit_price_cents,quantity,discount_cents,line_total_cents,created_at) VALUES(row_id,st,order_id,'22600000-0000-4000-8000-000000000050','22600000-0000-4000-8000-000000000051',0,'Fixture product','Fixture variant',10000,1,500,9500,n);
 fp:=saas.promotion_operation_fingerprint_v2('commit',st,jsonb_build_object('reservationGroupId',group_id,'orderId',order_id));SELECT * INTO r FROM saas.promotion_commit_reservation_group_v1(st,gen_random_uuid(),fp,group_id,order_id,n);IF r.outcome<>'committed' THEN RAISE EXCEPTION 'WHEEL_NATIVE_COMMIT:%',r.outcome;END IF;
 IF saas.promotion_evaluate_v1(st,context,n)->>'discountTotalMinor'<>'0' OR(SELECT count(*) FROM saas.promotion_redemptions WHERE code_id=a.code_id)<>1 THEN RAISE EXCEPTION 'WHEEL_ONE_USE';END IF;
 SELECT * INTO r FROM saas.lucky_wheel_result_v1('wheel-a.example.invalid',repeat('a',64),n,campaign,op);IF r.result_payload->>'couponStatus'<>'used' OR r.result_payload->'ruleDocument'<>jsonb_set(old_rule,'{trigger}',jsonb_build_object('kind','code','codes',jsonb_build_array(a.coupon_code))) THEN RAISE EXCEPTION 'WHEEL_CLOSED_RECOVERY';END IF;
 SELECT * INTO r FROM saas.lucky_wheel_managed_promotions_v1(st,principal,membership,plan,'wheel_fixture',1,n,3,NULL,NULL);IF r.outcome<>'ok' OR r.result_payload->'hasMore'<>'true'::jsonb OR jsonb_array_length(r.result_payload->'items')<>3 OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements(r.result_payload->'items') p WHERE p->'deleted'='true'::jsonb) THEN RAISE EXCEPTION 'WHEEL_MANAGED_HISTORY_INDEX';END IF;
 SELECT saas.lucky_wheel_campaign_projection_v1(c,n) INTO result FROM saas.lucky_wheel_campaigns c WHERE c.id=campaign;IF result->'stats'->>'used'<>'1' OR result->'stats'->>'discountMinor'<>'500' OR result->'stats'->>'revenueMinor'<>'9500' THEN RAISE EXCEPTION 'WHEEL_ACTUAL_SALES_REPORT:%',result->'stats';END IF;
 UPDATE saas.orders SET payment_status='refunded',status='refunded',refunded_at=n WHERE id=order_id;SELECT saas.lucky_wheel_campaign_projection_v1(c,n) INTO result FROM saas.lucky_wheel_campaigns c WHERE c.id=campaign;IF result->'stats'->>'used'<>'1' OR result->'stats'->>'discountMinor'<>'0' OR result->'stats'->>'revenueMinor'<>'0' THEN RAISE EXCEPTION 'WHEEL_REFUND_REPORT';END IF;
 RAISE NOTICE 'native226 acceptance: private authority, legacy, awards/replay/recovery, guest WEB, immutable revisions, normal batch, reserve/replay/revoke/delete/commit, single-use, truthful refund reporting passed';
END $tests$;
ROLLBACK;
