BEGIN;
SET LOCAL ROLE celebix_saas_owner;
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='120s';
DROP TRIGGER catalog_search_products_changed ON saas.products;
DROP TRIGGER catalog_search_variants_changed ON saas.product_variants;
DROP TRIGGER catalog_search_categories_assigned ON saas.catalog_product_categories;
DROP TRIGGER catalog_search_resources_assigned ON saas.catalog_admin_resource_products;
DROP TRIGGER catalog_search_categories_changed ON saas.catalog_categories;
DROP TRIGGER catalog_search_resources_changed ON saas.catalog_admin_resources;
DROP TRIGGER catalog_search_stores_changed ON saas.stores;
DO $restore$ DECLARE row record; BEGIN FOR row IN SELECT * FROM saas.catalog_search_194_backup ORDER BY identity LOOP EXECUTE row.definition; END LOOP; END $restore$;
DROP FUNCTION saas.public_search_products(text,timestamptz,text,integer,text);
ALTER FUNCTION saas.public_search_products_before_catalog_search(text,timestamptz,text,integer,text) RENAME TO public_search_products;
GRANT EXECUTE ON FUNCTION saas.public_search_products(text,timestamptz,text,integer,text) TO celebix_saas_host_resolver;
DROP FUNCTION saas.public_catalog_search_scope(text,timestamptz);
DROP FUNCTION saas.catalog_search_claim(timestamptz,integer,uuid);
DROP FUNCTION saas.catalog_search_ack(uuid,uuid,uuid,bigint,timestamptz,text);
DROP FUNCTION saas.catalog_search_requeue_all(timestamptz);
DROP FUNCTION saas.catalog_search_candidates(uuid,text);
DROP FUNCTION saas.catalog_search_changed();
DROP FUNCTION saas.catalog_search_refresh(uuid,uuid);
DROP TABLE saas.catalog_search_outbox;
DROP TABLE saas.catalog_search_documents;
DROP TABLE saas.catalog_search_194_backup;
DROP FUNCTION saas.catalog_search_query_tokens(text);
DROP FUNCTION saas.catalog_search_normalize(text);
-- pg_trgm may be shared by other features; rollback retains the extension.
COMMIT;
