-- Phase 3C1 least-privilege customer management API.
BEGIN;
SET LOCAL ROLE celebix_saas_owner;

CREATE OR REPLACE FUNCTION saas.merchant_action_authority_error(p_store_id uuid,p_principal_id uuid,p_membership_id uuid,p_plan_id uuid,p_plan_code text,p_plan_version bigint,p_now timestamptz,p_required_feature text,p_required_action text)
RETURNS text LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
DECLARE membership_role text;
BEGIN
  IF p_store_id IS NULL OR p_principal_id IS NULL OR p_membership_id IS NULL OR p_plan_id IS NULL OR p_plan_code IS NULL OR p_plan_version IS NULL OR p_now IS NULL OR p_required_feature IS NULL OR p_required_action IS NULL OR p_required_action NOT IN ('orders.read','orders.manage','orders.fulfill','orders.payment','orders.note','carts.read','carts.manage','customers.read','customers.manage','customers.archive') THEN RETURN 'durable_authority_invalid'; END IF;
  IF NOT EXISTS(SELECT 1 FROM saas.stores s WHERE s.id=p_store_id AND s.status='active') THEN RETURN 'store_inactive'; END IF;
  SELECT m.role INTO membership_role FROM saas.memberships m WHERE m.id=p_membership_id AND m.store_id=p_store_id AND m.principal_id=p_principal_id AND m.status='active';
  IF membership_role IS NULL THEN RETURN 'membership_denied'; END IF;
  IF NOT EXISTS(SELECT 1 FROM saas.subscriptions s JOIN saas.plans p ON p.id=s.plan_id AND p.plan_code=s.plan_code AND p.version=s.plan_version WHERE s.store_id=p_store_id AND s.plan_id=p_plan_id AND s.plan_code=p_plan_code AND s.plan_version=p_plan_version AND s.status='active' AND s.valid_from<=p_now AND (s.valid_until IS NULL OR s.valid_until>p_now) AND p.status='active' AND p.valid_from<=p_now AND (p.valid_until IS NULL OR p.valid_until>p_now)) THEN RETURN 'durable_authority_invalid'; END IF;
  IF NOT EXISTS(SELECT 1 FROM saas.plan_features f WHERE f.plan_id=p_plan_id AND f.enabled AND f.feature_key=p_required_feature) THEN RETURN 'feature_not_enabled'; END IF;
  IF NOT (membership_role IN ('store_owner','admin') OR (membership_role='editor' AND p_required_action IN ('orders.read','orders.fulfill','orders.note','carts.read','customers.read','customers.manage')) OR (membership_role='analyst' AND p_required_action IN ('orders.read','carts.read','customers.read'))) THEN RETURN 'membership_denied'; END IF;
  RETURN NULL;
END $f$;

CREATE FUNCTION saas.customer_json_timestamp(p_value timestamptz) RETURNS text LANGUAGE sql IMMUTABLE STRICT SET search_path=pg_catalog,saas AS $f$ SELECT pg_catalog.to_char(p_value AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') $f$;

CREATE FUNCTION saas.customer_list_projection(p_store_id uuid,p_customer_id uuid) RETURNS jsonb LANGUAGE sql STABLE SET search_path=pg_catalog,saas AS $f$
  SELECT pg_catalog.jsonb_strip_nulls(pg_catalog.jsonb_build_object(
    'id',c.id,'status',c.status,'displayName',c.first_name||' '||c.last_name,'firstName',c.first_name,'lastName',c.last_name,'email',c.email,'phone',c.phone,
    'orderCount',(SELECT pg_catalog.count(*) FROM saas.orders o WHERE o.store_id=p_store_id AND o.customer_id=c.id),
    'totalSpentCents',COALESCE((SELECT pg_catalog.sum(o.total_cents) FROM saas.orders o WHERE o.store_id=p_store_id AND o.customer_id=c.id AND o.payment_status='completed'),0),
    'currency',s.currency,'lastOrderAt',(SELECT saas.customer_json_timestamp(pg_catalog.max(o.created_at)) FROM saas.orders o WHERE o.store_id=p_store_id AND o.customer_id=c.id),
    'tags',COALESCE((SELECT pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('id',t.id,'name',t.name,'color',t.color) ORDER BY t.name,t.id) FROM saas.customer_tag_assignments a JOIN saas.customer_tags t ON t.store_id=a.store_id AND t.id=a.tag_id WHERE a.store_id=p_store_id AND a.customer_id=c.id AND t.archived_at IS NULL),'[]'::jsonb),
    'version',c.version,'createdAt',saas.customer_json_timestamp(c.created_at),'updatedAt',saas.customer_json_timestamp(c.updated_at)
  )) FROM saas.customers c JOIN saas.stores s ON s.id=c.store_id WHERE c.store_id=p_store_id AND c.id=p_customer_id
$f$;

CREATE FUNCTION saas.customer_detail_projection(p_store_id uuid,p_customer_id uuid) RETURNS jsonb LANGUAGE sql STABLE SET search_path=pg_catalog,saas AS $f$
  SELECT base || pg_catalog.jsonb_build_object(
    'addresses',COALESCE((SELECT pg_catalog.jsonb_agg(pg_catalog.jsonb_strip_nulls(pg_catalog.jsonb_build_object('id',a.id,'label',a.label,'recipientName',a.recipient_name,'line1',a.line1,'line2',a.line2,'city',a.city,'district',a.district,'postalCode',a.postal_code,'country',a.country,'isDefault',a.is_default,'version',a.version)) ORDER BY a.is_default DESC,a.label,a.id) FROM saas.customer_addresses a WHERE a.store_id=p_store_id AND a.customer_id=p_customer_id),'[]'::jsonb),
    'consents',COALESCE((SELECT pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('channel',x.channel,'status',x.status,'recordedAt',saas.customer_json_timestamp(x.recorded_at)) ORDER BY x.channel) FROM saas.customer_consents x WHERE x.store_id=p_store_id AND x.customer_id=p_customer_id),'[]'::jsonb),
    'notes',COALESCE((SELECT pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('id',n.id,'text',n.note_text,'createdAt',saas.customer_json_timestamp(n.created_at)) ORDER BY n.created_at DESC,n.id DESC) FROM (SELECT * FROM saas.customer_notes WHERE store_id=p_store_id AND customer_id=p_customer_id AND archived_at IS NULL ORDER BY created_at DESC,id DESC LIMIT 100) n),'[]'::jsonb),
    'segments',COALESCE((SELECT pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('id',g.id,'name',g.name,'kind',g.segment_kind) ORDER BY g.name,g.id) FROM saas.customer_segment_memberships m JOIN saas.customer_segments g ON g.store_id=m.store_id AND g.id=m.segment_id WHERE m.store_id=p_store_id AND m.customer_id=p_customer_id AND g.archived_at IS NULL),'[]'::jsonb)
  ) FROM (SELECT saas.customer_list_projection(p_store_id,p_customer_id) base) q WHERE base IS NOT NULL
$f$;

CREATE FUNCTION saas.customer_mutation_projection(p_store_id uuid,p_customer_id uuid) RETURNS jsonb LANGUAGE sql STABLE SET search_path=pg_catalog,saas AS $f$
  SELECT pg_catalog.jsonb_build_object('id',c.id,'version',c.version,'status',c.status,'updatedAt',saas.customer_json_timestamp(c.updated_at)) FROM saas.customers c WHERE c.store_id=p_store_id AND c.id=p_customer_id
$f$;

CREATE FUNCTION saas.customers_summary(p_store_id uuid,p_principal_id uuid,p_membership_id uuid,p_plan_id uuid,p_plan_code text,p_plan_version bigint,p_now timestamptz)
RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$ DECLARE e text; BEGIN
 e:=saas.merchant_action_authority_error(p_store_id,p_principal_id,p_membership_id,p_plan_id,p_plan_code,p_plan_version,p_now,'customers','customers.read'); IF e IS NOT NULL THEN RETURN QUERY SELECT e,NULL::jsonb; RETURN; END IF;
 RETURN QUERY SELECT 'summarized',pg_catalog.jsonb_build_object('active',pg_catalog.count(*) FILTER(WHERE c.status='active'),'archived',pg_catalog.count(*) FILTER(WHERE c.status='archived'),'consentedEmail',pg_catalog.count(*) FILTER(WHERE EXISTS(SELECT 1 FROM saas.customer_consents x WHERE x.store_id=c.store_id AND x.customer_id=c.id AND x.channel='email' AND x.status='granted')),'totalSpentCents',COALESCE((SELECT pg_catalog.sum(o.total_cents) FROM saas.orders o WHERE o.store_id=p_store_id AND o.customer_id IS NOT NULL AND o.payment_status='completed'),0),'currency',s.currency,'asOf',saas.customer_json_timestamp(p_now)) FROM saas.stores s LEFT JOIN saas.customers c ON c.store_id=s.id WHERE s.id=p_store_id GROUP BY s.currency;
END $f$;

CREATE FUNCTION saas.customers_list(p_store_id uuid,p_principal_id uuid,p_membership_id uuid,p_plan_id uuid,p_plan_code text,p_plan_version bigint,p_now timestamptz,p_status text,p_search text,p_page_size bigint,p_cursor_updated_at timestamptz,p_cursor_id uuid)
RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$ DECLARE e text; BEGIN
 e:=saas.merchant_action_authority_error(p_store_id,p_principal_id,p_membership_id,p_plan_id,p_plan_code,p_plan_version,p_now,'customers','customers.read'); IF e IS NOT NULL THEN RETURN QUERY SELECT e,NULL::jsonb; RETURN; END IF;
 IF (p_status IS NOT NULL AND p_status NOT IN('active','archived')) OR p_page_size NOT BETWEEN 1 AND 100 OR (p_search IS NOT NULL AND (p_search<>pg_catalog.btrim(p_search) OR pg_catalog.char_length(p_search) NOT BETWEEN 1 AND 200 OR saas.customer_text_has_control(p_search))) OR ((p_cursor_updated_at IS NULL)<>(p_cursor_id IS NULL)) THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb; RETURN; END IF;
 RETURN QUERY WITH ordered AS (SELECT c.* FROM saas.customers c WHERE c.store_id=p_store_id AND (p_status IS NULL OR c.status=p_status) AND (p_status IS NOT NULL OR c.status='active') AND (p_search IS NULL OR c.first_name ILIKE '%'||p_search||'%' OR c.last_name ILIKE '%'||p_search||'%' OR COALESCE(c.email,'') ILIKE '%'||p_search||'%' OR COALESCE(c.phone,'') ILIKE '%'||p_search||'%') AND (p_cursor_id IS NULL OR (c.updated_at,c.id)<(p_cursor_updated_at,p_cursor_id)) ORDER BY c.updated_at DESC,c.id DESC LIMIT p_page_size+1), numbered AS(SELECT ordered.*,pg_catalog.row_number() OVER() ordinal FROM ordered), page AS(SELECT * FROM numbered WHERE ordinal<=p_page_size), last_page AS(SELECT * FROM page ORDER BY ordinal DESC LIMIT 1)
 SELECT 'listed',pg_catalog.jsonb_strip_nulls(pg_catalog.jsonb_build_object('items',COALESCE((SELECT pg_catalog.jsonb_agg(saas.customer_list_projection(p_store_id,page.id) ORDER BY page.ordinal) FROM page),'[]'::jsonb),'nextCursor',CASE WHEN (SELECT pg_catalog.count(*) FROM numbered)>p_page_size THEN (SELECT pg_catalog.jsonb_build_object('updatedAt',saas.customer_json_timestamp(last_page.updated_at),'id',last_page.id) FROM last_page) ELSE NULL END));
END $f$;

CREATE FUNCTION saas.customers_get(p_store_id uuid,p_principal_id uuid,p_membership_id uuid,p_plan_id uuid,p_plan_code text,p_plan_version bigint,p_now timestamptz,p_customer_id uuid)
RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$ DECLARE e text; BEGIN e:=saas.merchant_action_authority_error(p_store_id,p_principal_id,p_membership_id,p_plan_id,p_plan_code,p_plan_version,p_now,'customers','customers.read'); IF e IS NOT NULL THEN RETURN QUERY SELECT e,NULL::jsonb; RETURN; END IF; IF NOT EXISTS(SELECT 1 FROM saas.customers WHERE store_id=p_store_id AND id=p_customer_id) THEN RETURN QUERY SELECT 'customer_not_found',NULL::jsonb; RETURN; END IF; RETURN QUERY SELECT 'found',saas.customer_detail_projection(p_store_id,p_customer_id); END $f$;

CREATE FUNCTION saas.customers_save(p_store_id uuid,p_principal_id uuid,p_membership_id uuid,p_plan_id uuid,p_plan_code text,p_plan_version bigint,p_now timestamptz,p_operation_id uuid,p_fingerprint text,p_customer_id uuid,p_expected_version bigint,p_first_name text,p_last_name text,p_email text,p_phone text,p_addresses jsonb,p_consents jsonb)
RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$
DECLARE e text; existing saas.customer_operations%ROWTYPE; current_customer saas.customers%ROWTYPE; result jsonb; kind text; address_count int; consent_count int;
BEGIN
 e:=saas.merchant_action_authority_error(p_store_id,p_principal_id,p_membership_id,p_plan_id,p_plan_code,p_plan_version,p_now,'customers','customers.manage'); IF e IS NOT NULL THEN RETURN QUERY SELECT e,NULL::jsonb; RETURN; END IF;
 SELECT * INTO existing FROM saas.customer_operations WHERE store_id=p_store_id AND operation_id=p_operation_id; IF FOUND THEN IF existing.payload_fingerprint<>p_fingerprint THEN RETURN QUERY SELECT 'operation_mismatch',NULL::jsonb; ELSE RETURN QUERY SELECT 'operation_replayed',existing.result_payload; END IF; RETURN; END IF;
 IF p_fingerprint!~'^[a-f0-9]{64}$' OR p_first_name IS NULL OR p_last_name IS NULL OR p_first_name<>pg_catalog.btrim(p_first_name) OR p_last_name<>pg_catalog.btrim(p_last_name) OR pg_catalog.char_length(p_first_name) NOT BETWEEN 1 AND 100 OR pg_catalog.char_length(p_last_name) NOT BETWEEN 1 AND 100 OR saas.customer_text_has_control(p_first_name) OR saas.customer_text_has_control(p_last_name) OR (p_email IS NOT NULL AND (p_email<>pg_catalog.lower(p_email) OR p_email<>pg_catalog.btrim(p_email) OR p_email!~'^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$')) OR (p_phone IS NOT NULL AND p_phone!~'^\+[1-9][0-9]{7,14}$') OR pg_catalog.jsonb_typeof(p_addresses)<>'array' OR pg_catalog.jsonb_typeof(p_consents)<>'array' OR pg_catalog.pg_column_size(p_addresses)>32768 OR pg_catalog.pg_column_size(p_consents)>8192 THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb; RETURN; END IF;
 address_count:=pg_catalog.jsonb_array_length(p_addresses); consent_count:=pg_catalog.jsonb_array_length(p_consents); IF address_count>20 OR consent_count>3 THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb; RETURN; END IF;
 SELECT * INTO current_customer FROM saas.customers WHERE store_id=p_store_id AND id=p_customer_id FOR UPDATE;
 IF FOUND THEN kind:='update'; IF p_expected_version IS NULL OR current_customer.version<>p_expected_version OR current_customer.status<>'active' THEN RETURN QUERY SELECT CASE WHEN current_customer.status<>'active' THEN 'invalid_transition' ELSE 'version_conflict' END,NULL::jsonb; RETURN; END IF; UPDATE saas.customers SET first_name=p_first_name,last_name=p_last_name,email=p_email,phone=p_phone,version=version+1,updated_at=p_now WHERE store_id=p_store_id AND id=p_customer_id;
 ELSE kind:='create'; IF p_expected_version IS NOT NULL THEN RETURN QUERY SELECT 'customer_not_found',NULL::jsonb; RETURN; END IF; INSERT INTO saas.customers(id,store_id,status,first_name,last_name,email,phone,version,created_at,updated_at) VALUES(p_customer_id,p_store_id,'active',p_first_name,p_last_name,p_email,p_phone,1,p_now,p_now); END IF;
 DELETE FROM saas.customer_addresses WHERE store_id=p_store_id AND customer_id=p_customer_id; DELETE FROM saas.customer_consents WHERE store_id=p_store_id AND customer_id=p_customer_id;
 BEGIN
   INSERT INTO saas.customer_addresses(id,store_id,customer_id,label,recipient_name,line1,line2,city,district,postal_code,country,is_default,version,created_at,updated_at)
   SELECT x.id,p_store_id,p_customer_id,x.label,x.recipient_name,x.line1,x.line2,x.city,x.district,x.postal_code,x.country,x.is_default,1,p_now,p_now FROM pg_catalog.jsonb_to_recordset(p_addresses) x(id uuid,label text,recipient_name text,line1 text,line2 text,city text,district text,postal_code text,country char(2),is_default boolean);
   INSERT INTO saas.customer_consents(store_id,customer_id,channel,status,recorded_at) SELECT p_store_id,p_customer_id,x.channel,x.status,p_now FROM pg_catalog.jsonb_to_recordset(p_consents) x(channel text,status text);
 EXCEPTION WHEN check_violation OR not_null_violation OR unique_violation OR foreign_key_violation OR invalid_text_representation THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb; RETURN; END;
 result:=saas.customer_mutation_projection(p_store_id,p_customer_id); INSERT INTO saas.customer_operations(operation_id,store_id,customer_id,operation_kind,payload_fingerprint,result_payload,committed_at) VALUES(p_operation_id,p_store_id,p_customer_id,kind,p_fingerprint,result,p_now); RETURN QUERY SELECT 'committed',result;
EXCEPTION WHEN unique_violation THEN RETURN QUERY SELECT 'customer_conflict',NULL::jsonb;
END $f$;

CREATE FUNCTION saas.customers_archive(p_store_id uuid,p_principal_id uuid,p_membership_id uuid,p_plan_id uuid,p_plan_code text,p_plan_version bigint,p_now timestamptz,p_operation_id uuid,p_fingerprint text,p_customer_id uuid,p_expected_version bigint)
RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$ DECLARE e text; existing saas.customer_operations%ROWTYPE; current_version bigint; current_status text; result jsonb; BEGIN
 e:=saas.merchant_action_authority_error(p_store_id,p_principal_id,p_membership_id,p_plan_id,p_plan_code,p_plan_version,p_now,'customers','customers.archive'); IF e IS NOT NULL THEN RETURN QUERY SELECT e,NULL::jsonb; RETURN; END IF;
 SELECT * INTO existing FROM saas.customer_operations WHERE store_id=p_store_id AND operation_id=p_operation_id; IF FOUND THEN RETURN QUERY SELECT CASE WHEN existing.payload_fingerprint=p_fingerprint THEN 'operation_replayed' ELSE 'operation_mismatch' END,CASE WHEN existing.payload_fingerprint=p_fingerprint THEN existing.result_payload ELSE NULL END; RETURN; END IF;
 SELECT version,status INTO current_version,current_status FROM saas.customers WHERE store_id=p_store_id AND id=p_customer_id FOR UPDATE; IF NOT FOUND THEN RETURN QUERY SELECT 'customer_not_found',NULL::jsonb; RETURN; END IF; IF current_version<>p_expected_version THEN RETURN QUERY SELECT 'version_conflict',NULL::jsonb; RETURN; END IF; IF current_status<>'active' THEN RETURN QUERY SELECT 'invalid_transition',NULL::jsonb; RETURN; END IF;
 UPDATE saas.customers SET status='archived',archived_at=p_now,version=version+1,updated_at=p_now WHERE store_id=p_store_id AND id=p_customer_id; result:=saas.customer_mutation_projection(p_store_id,p_customer_id); INSERT INTO saas.customer_operations VALUES(p_operation_id,p_store_id,p_customer_id,'archive',p_fingerprint,result,p_now); RETURN QUERY SELECT 'committed',result;
END $f$;

CREATE FUNCTION saas.customers_add_note(p_store_id uuid,p_principal_id uuid,p_membership_id uuid,p_plan_id uuid,p_plan_code text,p_plan_version bigint,p_now timestamptz,p_operation_id uuid,p_fingerprint text,p_customer_id uuid,p_note_id uuid,p_note text)
RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$ DECLARE e text; existing saas.customer_operations%ROWTYPE; result jsonb; BEGIN
 e:=saas.merchant_action_authority_error(p_store_id,p_principal_id,p_membership_id,p_plan_id,p_plan_code,p_plan_version,p_now,'customers','customers.manage'); IF e IS NOT NULL THEN RETURN QUERY SELECT e,NULL::jsonb; RETURN; END IF;
 SELECT * INTO existing FROM saas.customer_operations WHERE store_id=p_store_id AND operation_id=p_operation_id; IF FOUND THEN RETURN QUERY SELECT CASE WHEN existing.payload_fingerprint=p_fingerprint THEN 'operation_replayed' ELSE 'operation_mismatch' END,CASE WHEN existing.payload_fingerprint=p_fingerprint THEN existing.result_payload ELSE NULL END; RETURN; END IF;
 IF p_note IS NULL OR p_note<>pg_catalog.btrim(p_note) OR pg_catalog.char_length(p_note) NOT BETWEEN 1 AND 2000 OR saas.customer_text_has_control(p_note) OR NOT EXISTS(SELECT 1 FROM saas.customers WHERE store_id=p_store_id AND id=p_customer_id AND status='active') THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb; RETURN; END IF;
 INSERT INTO saas.customer_notes VALUES(p_note_id,p_store_id,p_customer_id,p_membership_id,p_note,NULL,p_now); UPDATE saas.customers SET version=version+1,updated_at=p_now WHERE store_id=p_store_id AND id=p_customer_id; result:=saas.customer_mutation_projection(p_store_id,p_customer_id); INSERT INTO saas.customer_operations VALUES(p_operation_id,p_store_id,p_customer_id,'add_note',p_fingerprint,result,p_now); RETURN QUERY SELECT 'committed',result;
END $f$;

CREATE FUNCTION saas.customer_tags_list(p_store_id uuid,p_principal_id uuid,p_membership_id uuid,p_plan_id uuid,p_plan_code text,p_plan_version bigint,p_now timestamptz) RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$ DECLARE e text; BEGIN e:=saas.merchant_action_authority_error(p_store_id,p_principal_id,p_membership_id,p_plan_id,p_plan_code,p_plan_version,p_now,'customers','customers.read'); IF e IS NOT NULL THEN RETURN QUERY SELECT e,NULL::jsonb; RETURN; END IF; RETURN QUERY SELECT 'listed',pg_catalog.jsonb_build_object('items',COALESCE(pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('id',t.id,'name',t.name,'color',t.color,'customerCount',(SELECT pg_catalog.count(*) FROM saas.customer_tag_assignments a WHERE a.store_id=t.store_id AND a.tag_id=t.id),'version',t.version) ORDER BY t.name,t.id),'[]'::jsonb)) FROM saas.customer_tags t WHERE t.store_id=p_store_id AND t.archived_at IS NULL; END $f$;
CREATE FUNCTION saas.customer_segments_list(p_store_id uuid,p_principal_id uuid,p_membership_id uuid,p_plan_id uuid,p_plan_code text,p_plan_version bigint,p_now timestamptz) RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$ DECLARE e text; BEGIN e:=saas.merchant_action_authority_error(p_store_id,p_principal_id,p_membership_id,p_plan_id,p_plan_code,p_plan_version,p_now,'customers','customers.read'); IF e IS NOT NULL THEN RETURN QUERY SELECT e,NULL::jsonb; RETURN; END IF; RETURN QUERY SELECT 'listed',pg_catalog.jsonb_build_object('items',COALESCE(pg_catalog.jsonb_agg(pg_catalog.jsonb_strip_nulls(pg_catalog.jsonb_build_object('id',g.id,'name',g.name,'description',g.description,'kind',g.segment_kind,'customerCount',(SELECT pg_catalog.count(*) FROM saas.customer_segment_memberships m WHERE m.store_id=g.store_id AND m.segment_id=g.id),'version',g.version)) ORDER BY g.name,g.id),'[]'::jsonb)) FROM saas.customer_segments g WHERE g.store_id=p_store_id AND g.archived_at IS NULL; END $f$;

CREATE FUNCTION saas.customer_taxonomy_upsert(p_store_id uuid,p_principal_id uuid,p_membership_id uuid,p_plan_id uuid,p_plan_code text,p_plan_version bigint,p_now timestamptz,p_operation_id uuid,p_fingerprint text,p_kind text,p_id uuid,p_name text,p_secondary text,p_expected_version bigint)
RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$ DECLARE e text; current_version bigint; result jsonb; customer_anchor uuid; BEGIN
 e:=saas.merchant_action_authority_error(p_store_id,p_principal_id,p_membership_id,p_plan_id,p_plan_code,p_plan_version,p_now,'customers','customers.manage'); IF e IS NOT NULL THEN RETURN QUERY SELECT e,NULL::jsonb; RETURN; END IF;
 IF p_kind NOT IN('tag','segment') OR p_name IS NULL OR p_name<>pg_catalog.btrim(p_name) OR pg_catalog.char_length(p_name) NOT BETWEEN 1 AND (CASE WHEN p_kind='tag' THEN 64 ELSE 100 END) OR saas.customer_text_has_control(p_name) OR p_fingerprint!~'^[a-f0-9]{64}$' THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb; RETURN; END IF;
 SELECT id INTO customer_anchor FROM saas.customers WHERE store_id=p_store_id ORDER BY id LIMIT 1; IF customer_anchor IS NULL THEN RETURN QUERY SELECT 'customer_not_found',NULL::jsonb; RETURN; END IF;
 IF EXISTS(SELECT 1 FROM saas.customer_operations WHERE store_id=p_store_id AND operation_id=p_operation_id) THEN RETURN QUERY SELECT CASE WHEN o.payload_fingerprint=p_fingerprint THEN 'operation_replayed' ELSE 'operation_mismatch' END,CASE WHEN o.payload_fingerprint=p_fingerprint THEN o.result_payload ELSE NULL END FROM saas.customer_operations o WHERE o.store_id=p_store_id AND o.operation_id=p_operation_id; RETURN; END IF;
 IF p_kind='tag' THEN SELECT version INTO current_version FROM saas.customer_tags WHERE store_id=p_store_id AND id=p_id FOR UPDATE; IF FOUND THEN IF current_version<>p_expected_version THEN RETURN QUERY SELECT 'version_conflict',NULL::jsonb; RETURN; END IF; UPDATE saas.customer_tags SET name=p_name,color=p_secondary,version=version+1,updated_at=p_now WHERE store_id=p_store_id AND id=p_id; ELSE IF p_expected_version IS NOT NULL OR p_secondary!~'^#[0-9a-f]{6}$' THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb; RETURN; END IF; INSERT INTO saas.customer_tags VALUES(p_id,p_store_id,p_name,p_secondary,1,NULL,p_now,p_now); END IF; SELECT pg_catalog.jsonb_build_object('id',id,'name',name,'color',color,'customerCount',(SELECT pg_catalog.count(*) FROM saas.customer_tag_assignments a WHERE a.store_id=p_store_id AND a.tag_id=p_id),'version',version) INTO result FROM saas.customer_tags WHERE store_id=p_store_id AND id=p_id;
 ELSE SELECT version INTO current_version FROM saas.customer_segments WHERE store_id=p_store_id AND id=p_id FOR UPDATE; IF FOUND THEN IF current_version<>p_expected_version THEN RETURN QUERY SELECT 'version_conflict',NULL::jsonb; RETURN; END IF; UPDATE saas.customer_segments SET name=p_name,description=p_secondary,version=version+1,updated_at=p_now WHERE store_id=p_store_id AND id=p_id; ELSE IF p_expected_version IS NOT NULL THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb; RETURN; END IF; INSERT INTO saas.customer_segments VALUES(p_id,p_store_id,p_name,p_secondary,'manual',1,NULL,p_now,p_now); END IF; SELECT pg_catalog.jsonb_strip_nulls(pg_catalog.jsonb_build_object('id',id,'name',name,'description',description,'kind',segment_kind,'customerCount',(SELECT pg_catalog.count(*) FROM saas.customer_segment_memberships m WHERE m.store_id=p_store_id AND m.segment_id=p_id),'version',version)) INTO result FROM saas.customer_segments WHERE store_id=p_store_id AND id=p_id; END IF;
 INSERT INTO saas.customer_operations VALUES(p_operation_id,p_store_id,customer_anchor,CASE WHEN p_kind='tag' THEN 'upsert_tag' ELSE 'upsert_segment' END,p_fingerprint,result,p_now); RETURN QUERY SELECT 'committed',result;
EXCEPTION WHEN unique_violation OR check_violation THEN RETURN QUERY SELECT 'customer_conflict',NULL::jsonb;
END $f$;

CREATE FUNCTION saas.customer_set_taxonomy(p_store_id uuid,p_principal_id uuid,p_membership_id uuid,p_plan_id uuid,p_plan_code text,p_plan_version bigint,p_now timestamptz,p_operation_id uuid,p_fingerprint text,p_customer_id uuid,p_kind text,p_ids uuid[])
RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$ DECLARE e text; result jsonb; BEGIN
 e:=saas.merchant_action_authority_error(p_store_id,p_principal_id,p_membership_id,p_plan_id,p_plan_code,p_plan_version,p_now,'customers','customers.manage'); IF e IS NOT NULL THEN RETURN QUERY SELECT e,NULL::jsonb; RETURN; END IF;
 IF p_kind NOT IN('tag','segment') OR pg_catalog.coalesce(pg_catalog.array_length(p_ids,1),0)>50 OR p_fingerprint!~'^[a-f0-9]{64}$' THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb; RETURN; END IF;
 IF EXISTS(SELECT 1 FROM saas.customer_operations WHERE store_id=p_store_id AND operation_id=p_operation_id) THEN RETURN QUERY SELECT CASE WHEN o.payload_fingerprint=p_fingerprint THEN 'operation_replayed' ELSE 'operation_mismatch' END,CASE WHEN o.payload_fingerprint=p_fingerprint THEN o.result_payload ELSE NULL END FROM saas.customer_operations o WHERE o.store_id=p_store_id AND o.operation_id=p_operation_id; RETURN; END IF;
 IF NOT EXISTS(SELECT 1 FROM saas.customers WHERE store_id=p_store_id AND id=p_customer_id AND status='active') OR pg_catalog.coalesce(pg_catalog.array_length(p_ids,1),0)<>pg_catalog.coalesce((SELECT pg_catalog.count(DISTINCT id) FROM pg_catalog.unnest(p_ids) id),0) THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb; RETURN; END IF;
 IF p_kind='tag' THEN IF EXISTS(SELECT 1 FROM pg_catalog.unnest(p_ids) id WHERE NOT EXISTS(SELECT 1 FROM saas.customer_tags t WHERE t.store_id=p_store_id AND t.id=id AND t.archived_at IS NULL)) THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb; RETURN; END IF; DELETE FROM saas.customer_tag_assignments WHERE store_id=p_store_id AND customer_id=p_customer_id; INSERT INTO saas.customer_tag_assignments SELECT p_store_id,p_customer_id,id,p_now FROM pg_catalog.unnest(p_ids) id;
 ELSE IF EXISTS(SELECT 1 FROM pg_catalog.unnest(p_ids) id WHERE NOT EXISTS(SELECT 1 FROM saas.customer_segments g WHERE g.store_id=p_store_id AND g.id=id AND g.archived_at IS NULL)) THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb; RETURN; END IF; DELETE FROM saas.customer_segment_memberships WHERE store_id=p_store_id AND customer_id=p_customer_id; INSERT INTO saas.customer_segment_memberships SELECT p_store_id,p_customer_id,id,p_now FROM pg_catalog.unnest(p_ids) id; END IF;
 UPDATE saas.customers SET version=version+1,updated_at=p_now WHERE store_id=p_store_id AND id=p_customer_id; result:=saas.customer_mutation_projection(p_store_id,p_customer_id); INSERT INTO saas.customer_operations VALUES(p_operation_id,p_store_id,p_customer_id,CASE WHEN p_kind='tag' THEN 'set_tags' ELSE 'set_segments' END,p_fingerprint,result,p_now); RETURN QUERY SELECT 'committed',result;
END $f$;

CREATE FUNCTION saas.customers_export(p_store_id uuid,p_principal_id uuid,p_membership_id uuid,p_plan_id uuid,p_plan_code text,p_plan_version bigint,p_now timestamptz) RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$ DECLARE e text; BEGIN e:=saas.merchant_action_authority_error(p_store_id,p_principal_id,p_membership_id,p_plan_id,p_plan_code,p_plan_version,p_now,'customers','customers.read'); IF e IS NOT NULL THEN RETURN QUERY SELECT e,NULL::jsonb; RETURN; END IF; RETURN QUERY SELECT 'exported',pg_catalog.jsonb_build_object('items',COALESCE(pg_catalog.jsonb_agg(saas.customer_list_projection(p_store_id,c.id) ORDER BY c.created_at,c.id),'[]'::jsonb),'exportedAt',saas.customer_json_timestamp(p_now)) FROM (SELECT id,created_at FROM saas.customers WHERE store_id=p_store_id ORDER BY created_at,id LIMIT 1000) c; END $f$;

CREATE FUNCTION saas.customers_recover_operation(p_store_id uuid,p_principal_id uuid,p_membership_id uuid,p_plan_id uuid,p_plan_code text,p_plan_version bigint,p_now timestamptz,p_operation_id uuid,p_fingerprint text)
RETURNS TABLE(outcome text,result_payload jsonb) LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,saas AS $f$ DECLARE e text; BEGIN
 e:=saas.merchant_action_authority_error(p_store_id,p_principal_id,p_membership_id,p_plan_id,p_plan_code,p_plan_version,p_now,'customers','customers.read'); IF e IS NOT NULL THEN RETURN QUERY SELECT e,NULL::jsonb; RETURN; END IF;
 IF p_fingerprint!~'^[a-f0-9]{64}$' THEN RETURN QUERY SELECT 'invalid_input',NULL::jsonb; RETURN; END IF;
 RETURN QUERY SELECT CASE WHEN o.payload_fingerprint=p_fingerprint THEN 'operation_replayed' ELSE 'operation_mismatch' END,CASE WHEN o.payload_fingerprint=p_fingerprint THEN o.result_payload ELSE NULL END FROM saas.customer_operations o WHERE o.store_id=p_store_id AND o.operation_id=p_operation_id;
 IF NOT FOUND THEN RETURN QUERY SELECT 'operation_not_found',NULL::jsonb; END IF;
END $f$;

REVOKE ALL ON FUNCTION saas.customer_json_timestamp(timestamptz),saas.customer_list_projection(uuid,uuid),saas.customer_detail_projection(uuid,uuid),saas.customer_mutation_projection(uuid,uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION saas.customers_summary(uuid,uuid,uuid,uuid,text,bigint,timestamptz),saas.customers_list(uuid,uuid,uuid,uuid,text,bigint,timestamptz,text,text,bigint,timestamptz,uuid),saas.customers_get(uuid,uuid,uuid,uuid,text,bigint,timestamptz,uuid),saas.customers_save(uuid,uuid,uuid,uuid,text,bigint,timestamptz,uuid,text,uuid,bigint,text,text,text,text,jsonb,jsonb),saas.customers_archive(uuid,uuid,uuid,uuid,text,bigint,timestamptz,uuid,text,uuid,bigint),saas.customers_add_note(uuid,uuid,uuid,uuid,text,bigint,timestamptz,uuid,text,uuid,uuid,text),saas.customer_tags_list(uuid,uuid,uuid,uuid,text,bigint,timestamptz),saas.customer_segments_list(uuid,uuid,uuid,uuid,text,bigint,timestamptz),saas.customer_taxonomy_upsert(uuid,uuid,uuid,uuid,text,bigint,timestamptz,uuid,text,text,uuid,text,text,bigint),saas.customer_set_taxonomy(uuid,uuid,uuid,uuid,text,bigint,timestamptz,uuid,text,uuid,text,uuid[]),saas.customers_export(uuid,uuid,uuid,uuid,text,bigint,timestamptz),saas.customers_recover_operation(uuid,uuid,uuid,uuid,text,bigint,timestamptz,uuid,text) TO celebix_saas_app;
COMMIT;
