-- Current promotions entitlement gates visibility/new awards, never issued-result recovery.
BEGIN;
\ir 202610100226_lucky_wheel_fixtures.sql
SET LOCAL statement_timeout='120s';
DO $entitlement$
DECLARE st uuid:='22600000-0000-4000-8000-000000000001';principal uuid:='22600000-0000-4000-8000-000000000011';membership uuid:='22600000-0000-4000-8000-000000000021';plan uuid:='22600000-0000-4000-8000-000000000010';downgrade uuid:=gen_random_uuid();n timestamptz:=date_trunc('milliseconds',clock_timestamp());source uuid:=gen_random_uuid();campaign uuid;rule jsonb;config jsonb;r record;op uuid:=gen_random_uuid();award jsonb;context jsonb;source_ref uuid:=gen_random_uuid();
BEGIN
 rule:='{"schemaVersion":1,"benefit":{"kind":"percentage","percentageBps":500},"targets":{"mode":"all","include":[],"exclude":[]},"audience":{"mode":"everyone"},"trigger":{"kind":"code","codes":["LW-SOURCE-FIXTURE"]},"schedule":{"timezone":"Europe/Istanbul"},"limits":{"totalUsage":null,"perCustomerUsage":null,"budgetMinor":null,"orderMaximumMinor":null},"conditions":{"minimumBasketMinor":0,"minimumQuantity":0,"minimumProductQuantity":0,"salesChannels":["storefront"]},"combinationPolicy":{"kind":"none"},"priority":1,"marginPolicy":{"kind":"warn"},"progressMessagePolicy":{"enabled":false}}';
 INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES(source,st,'Entitlement code source','active',1,rule,n,n);INSERT INTO saas.promotion_versions(id,store_id,promotion_id,version,rule_document,created_at) VALUES(gen_random_uuid(),st,source,1,rule,n);
 config:=jsonb_build_object('schemaVersion',1,'heading','Entitlement fixture','body','','appearance',jsonb_build_object('sliceA','#ffffff','sliceB','#eeeeee','background','#ffffff','accent','#ff8800'),'collectMode','either','repeatDays',7,'couponHours',24,'marketingOptInLabel','Fixture opt-in','devices',jsonb_build_object('desktop',true,'mobile',true),'allowedPaths','[]'::jsonb,'scrollPercent',NULL,'startsAt',NULL,'endsAt',NULL,'prizes',(SELECT jsonb_agg(jsonb_build_object('id',gen_random_uuid(),'promotionId',source,'weightBps',2500,'issuanceLimit',NULL)) FROM generate_series(1,4)));
 SELECT * INTO r FROM saas.lucky_wheel_campaign_save_v1(st,principal,membership,plan,'wheel_fixture',1,n,gen_random_uuid(),repeat('e',64),NULL,NULL,'Entitlement fixture',true,config);IF r.outcome<>'saved' THEN RAISE EXCEPTION 'WHEEL_ENTITLEMENT_SETUP:%',r.outcome;END IF;campaign:=(r.result_payload->>'id')::uuid;
 SELECT * INTO r FROM saas.lucky_wheel_public_settings_v1('wheel-a.example.invalid',n);IF EXISTS(SELECT 1 FROM jsonb_array_elements(r.result_payload->'campaign'->'prizes') p WHERE p->'ruleDocument'->'trigger'?'codes') THEN RAISE EXCEPTION 'WHEEL_PUBLIC_UNISSUED_CODE';END IF;
 SELECT * INTO r FROM saas.lucky_wheel_spin_v1('wheel-a.example.invalid',repeat('e',64),n,op,campaign,1,'entitlement@example.invalid',NULL,false,repeat('f',64));IF r.outcome<>'saved' THEN RAISE EXCEPTION 'WHEEL_ENTITLEMENT_INITIAL:%',r.outcome;END IF;award:=r.result_payload;
 INSERT INTO saas.plans(id,plan_code,version,status,valid_from,created_at,updated_at) VALUES(downgrade,'wheel_no_promotions',1,'active','2020-01-01',n,n);INSERT INTO saas.platform_plan_publications VALUES(downgrade,txid_current());INSERT INTO saas.plan_features(plan_id,feature_key,feature_ordinal,enabled) VALUES(downgrade,'promotions',1,false);
 UPDATE saas.subscriptions SET plan_id=downgrade,plan_code='wheel_no_promotions',plan_version=1 WHERE store_id=st;
 SELECT * INTO r FROM saas.lucky_wheel_public_settings_v1('wheel-a.example.invalid',n);IF r.outcome<>'ok' OR r.result_payload->'campaign'<>'null'::jsonb THEN RAISE EXCEPTION 'WHEEL_ENTITLEMENT_VISIBILITY';END IF;
 SELECT * INTO r FROM saas.lucky_wheel_spin_v1('wheel-a.example.invalid',repeat('f',64),n,gen_random_uuid(),campaign,1,'blocked@example.invalid',NULL,false,repeat('a',64));IF r.outcome<>'campaign_unavailable' OR(SELECT count(*) FROM saas.lucky_wheel_awards WHERE campaign_id=campaign)<>1 THEN RAISE EXCEPTION 'WHEEL_ENTITLEMENT_NEW_AWARD:%',r.outcome;END IF;
 context:=jsonb_build_object('storeId',st,'customerId',NULL,'paidOrderCount',0,'customerSegmentIds','[]'::jsonb,'customerTagIds','[]'::jsonb,'cartLines',jsonb_build_array(jsonb_build_object('lineId',gen_random_uuid(),'position',0,'productId','22600000-0000-4000-8000-000000000050','variantId','22600000-0000-4000-8000-000000000051','quantity',1,'unitPriceMinor',10000,'unitCostMinor',5000,'currency','TRY','categoryIds','[]'::jsonb,'brandId',NULL,'collectionIds','[]'::jsonb)),'shippingMethodId',NULL,'paymentMethodId',NULL,'shippingBeforeDiscountMinor',0,'currency','TRY','storeLocalTime',saas.merchant_admin_timestamp(n),'salesChannel','storefront','submittedCodes',jsonb_build_array(award->>'couponCode'),'abandonedCart',NULL);
 SELECT * INTO r FROM saas.promotion_reserve_group_v1(st,gen_random_uuid(),saas.promotion_operation_fingerprint_v2('reserve',st,jsonb_build_object('sourceKind','offline_checkout','sourceReference',source_ref::text,'evaluatorContext',context)),'offline_checkout',source_ref::text,context,n);IF r.outcome<>'feature_unavailable' THEN RAISE EXCEPTION 'WHEEL_ENTITLEMENT_NATIVE_RESERVE_BYPASS:%',r.outcome;END IF;
 SELECT * INTO r FROM saas.lucky_wheel_result_v1('wheel-a.example.invalid',repeat('e',64),n,campaign,op);IF r.outcome<>'ok' OR r.result_payload<>award THEN RAISE EXCEPTION 'WHEEL_ENTITLEMENT_RECOVERY';END IF;
 SELECT * INTO r FROM saas.lucky_wheel_spin_v1('wheel-a.example.invalid',repeat('e',64),n,op,campaign,1,'entitlement@example.invalid',NULL,false,repeat('f',64));IF r.outcome<>'replayed' OR r.result_payload<>award THEN RAISE EXCEPTION 'WHEEL_ENTITLEMENT_REPLAY';END IF;
 RAISE NOTICE 'native226 entitlement acceptance: no unissued code in public settings; downgrade hides wheel and blocks new awards; native reserve preserves feature gate; issued award read/replay remains available passed';
END $entitlement$;
ROLLBACK;
