// Explicit isolated native226 clone only; no production connection or fixture copy.
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
const database='celebix_wheel226_20261010',container='celebix-phase2-isolated-restore-v4-c9ba9c0312e8';
const key=process.env.WHEEL_TEST_SSH_KEY;assert.ok(key,'WHEEL_TEST_SSH_KEY required');
const st='22600000-0000-4000-8000-000000000001',authority=[st,'22600000-0000-4000-8000-000000000011','22600000-0000-4000-8000-000000000021','22600000-0000-4000-8000-000000000010','wheel_fixture',1];
const lit=x=>x===null?'NULL':typeof x==='number'?String(x):typeof x==='boolean'?(x?'true':'false'):`'${String(x).replaceAll("'","''")}'`;
function launch(sql,label='control'){const child=spawn('ssh',['-i',key,'-o','BatchMode=yes','-o','StrictHostKeyChecking=yes','-o','ControlMaster=auto','-o','ControlPersist=60','-o','ControlPath=/tmp/celebix-wheel226-ssh-%C','root@46.225.183.57',`docker exec -i -e PGAPPNAME=wheel226-${label} ${container} psql -X -qAt -U postgres -d ${database} -v ON_ERROR_STOP=1`]);let output='',error='';child.stdout.on('data',d=>output+=d);child.stderr.on('data',d=>error+=d);child.stdin.end(sql);return new Promise(resolve=>child.on('close',code=>resolve({code,output,error})));}
async function query(sql,label){const r=await launch(sql,label);assert.equal(r.code,0,r.error);return r.output.trim().split('\n').filter(Boolean);}
const call=(name,values)=>`SELECT row_to_json(r) FROM saas.${name}(${values.map(lit).join(',')}) r;`;
const n=new Date().toISOString();
const rule={schemaVersion:1,benefit:{kind:'percentage',percentageBps:500},targets:{mode:'all',include:[],exclude:[]},audience:{mode:'everyone'},trigger:{kind:'code',codes:['FIXTURE-RACE']},schedule:{timezone:'Europe/Istanbul'},limits:{totalUsage:null,perCustomerUsage:null,budgetMinor:null,orderMaximumMinor:null},conditions:{minimumBasketMinor:0,minimumQuantity:0,minimumProductQuantity:0,salesChannels:['storefront']},combinationPolicy:{kind:'none'},priority:1,marginPolicy:{kind:'warn'},progressMessagePolicy:{enabled:false}};
const source=randomUUID();
const config=limit=>({schemaVersion:1,heading:'Isolated race fixture',body:'',appearance:{sliceA:'#ffffff',sliceB:'#eeeeee',background:'#ffffff',accent:'#ff8800'},collectMode:'either',repeatDays:7,couponHours:24,marketingOptInLabel:'Fixture only',devices:{desktop:true,mobile:true},allowedPaths:[],scrollPercent:null,startsAt:null,endsAt:null,prizes:Array.from({length:4},()=>({id:randomUUID(),promotionId:source,weightBps:2500,issuanceLimit:limit}))});
const prefix=`BEGIN;SET LOCAL ROLE celebix_saas_owner;SET LOCAL search_path=pg_catalog,saas;DO $g$ BEGIN IF current_database()<>${lit(database)} THEN RAISE EXCEPTION 'ISOLATED_REQUIRED';END IF;END $g$;`;
const fixtures=readFileSync(new URL('./202610100226_lucky_wheel_fixtures.sql',import.meta.url),'utf8');
const setup=await query(prefix+fixtures+`INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES(${lit(source)},${lit(st)},'Race source','active',1,${lit(JSON.stringify(rule))}::jsonb,${lit(n)},${lit(n)});INSERT INTO saas.promotion_versions(id,store_id,promotion_id,version,rule_document,created_at) VALUES(gen_random_uuid(),${lit(st)},${lit(source)},1,${lit(JSON.stringify(rule))}::jsonb,${lit(n)});`+call('lucky_wheel_campaign_save_v1',[...authority,n,randomUUID(),'1'.repeat(64),null,null,'Race window',true,JSON.stringify(config(100))])+'COMMIT;');
const campaign=JSON.parse(setup.at(-1)).result_payload;
async function active(label){for(let i=0;i<8;i++){const rows=await query(`SELECT count(*) FROM pg_stat_activity WHERE application_name=${lit('wheel226-'+label)} AND wait_event='PgSleep';`);if(rows[0]==='1')return;}throw Error('first transaction did not reach hold');}
async function blocked(label){for(let i=0;i<8;i++){const rows=await query(`SELECT count(*) FROM pg_stat_activity WHERE application_name=${lit('wheel226-'+label)} AND wait_event_type='Lock';`);if(rows[0]==='1')return;}throw Error('second transaction did not wait on native lock');}
const spin=(camp,visitor,operation,version=camp.version)=>call('lucky_wheel_spin_v1',['wheel-a.example.invalid',visitor,n,operation,camp.id,version,'race@example.invalid',null,false,'2'.repeat(64)]);
const operationA=randomUUID();
const a=launch(prefix+spin(campaign,'a'.repeat(64),operationA)+'SELECT pg_sleep(4);COMMIT;','spin-a');await active('spin-a');const b=launch(prefix+spin(campaign,'a'.repeat(64),randomUUID())+'COMMIT;','spin-b');await blocked('spin-b');const [ra,rb]=await Promise.all([a,b]);assert.equal(ra.code,0,ra.error);assert.equal(rb.code,0,rb.error);assert.equal(JSON.parse(ra.output.trim().split('\n')[0]).outcome,'saved');assert.equal(JSON.parse(rb.output.trim()).outcome,'repeat_limited');assert.equal((await query('SELECT count(*) FROM saas.lucky_wheel_awards;'))[0],'1');
const award=JSON.parse(ra.output.trim().split('\n')[0]).result_payload;
// Unrelated winning browsers race for the final visible slice quota. No silent reweighting.
await query(prefix+call('lucky_wheel_campaign_save_v1',[...authority,n,randomUUID(),'3'.repeat(64),campaign.id,1,'Race window',false,JSON.stringify(campaign.config)])+'COMMIT;');
const quotaRow=await query(prefix+call('lucky_wheel_campaign_save_v1',[...authority,n,randomUUID(),'4'.repeat(64),null,null,'Race quota',true,JSON.stringify(config(1))])+'COMMIT;');const quota=JSON.parse(quotaRow.at(-1)).result_payload;
const qa=launch(prefix+spin(quota,'b'.repeat(64),randomUUID())+'SELECT pg_sleep(4);COMMIT;','quota-a');await active('quota-a');const qb=launch(prefix+spin(quota,'c'.repeat(64),randomUUID())+'COMMIT;','quota-b');await blocked('quota-b');const [rqa,rqb]=await Promise.all([qa,qb]);assert.equal(rqa.code,0,rqa.error);assert.equal(rqb.code,0,rqb.error);assert.equal(JSON.parse(rqa.output.trim().split('\n')[0]).outcome,'saved');assert.equal(JSON.parse(rqb.output.trim()).outcome,'quota_exhausted');assert.equal((await query(`SELECT count(*) FROM saas.lucky_wheel_awards WHERE campaign_id=${lit(quota.id)};`))[0],'1');
// Two native order/cart authorities cannot reserve the same bearer code.
const lineId=randomUUID(),context={storeId:st,customerId:null,paidOrderCount:0,customerSegmentIds:[],customerTagIds:[],cartLines:[{lineId,position:0,productId:'22600000-0000-4000-8000-000000000050',variantId:'22600000-0000-4000-8000-000000000051',quantity:1,unitPriceMinor:10000,unitCostMinor:5000,currency:'TRY',categoryIds:[],brandId:null,collectionIds:[]}],shippingMethodId:null,paymentMethodId:null,shippingBeforeDiscountMinor:0,currency:'TRY',storeLocalTime:n,salesChannel:'storefront',submittedCodes:[award.couponCode],abandonedCart:null};
async function reserve(order,op){const payload={sourceKind:'offline_checkout',sourceReference:order,evaluatorContext:context};const fp=(await query(`SELECT saas.promotion_operation_fingerprint_v2('reserve',${lit(st)},${lit(JSON.stringify(payload))}::jsonb);`))[0];return call('promotion_reserve_group_v1',[st,op,fp,'offline_checkout',order,JSON.stringify(context),n]);}
const heldOrder=randomUUID(),reserveOp=randomUUID(),requestA=await reserve(heldOrder,reserveOp),requestB=await reserve(randomUUID(),randomUUID());const ca=launch(prefix+requestA+'SELECT pg_sleep(4);COMMIT;','code-a');await active('code-a');const cb=launch(prefix+requestB+'COMMIT;','code-b');await blocked('code-b');const [rca,rcb]=await Promise.all([ca,cb]);assert.equal(rca.code,0,rca.error);assert.equal(rcb.code,0,rcb.error);const hold=JSON.parse(rca.output.trim().split('\n')[0]);assert.equal(hold.outcome,'reserved');assert.equal(JSON.parse(rcb.output.trim()).outcome,'conditions_not_met');
// Native release returns the code to eligibility; another cart can reserve it once.
const group=hold.result_payload.reservationGroupId,releaseFp=(await query(`SELECT saas.promotion_operation_fingerprint_v2('release',${lit(st)},${lit(JSON.stringify({reservationGroupId:group}))}::jsonb);`))[0];const released=await query(prefix+call('promotion_release_reservation_group_v1',[st,randomUUID(),releaseFp,group,n])+'COMMIT;');assert.equal(JSON.parse(released.at(-1)).outcome,'released');const second=await query(prefix+await reserve(randomUUID(),randomUUID())+'COMMIT;');assert.equal(JSON.parse(second.at(-1)).outcome,'reserved');
// Save's new revision cannot be silently accepted by a racing old-version spin.
const sa=launch(prefix+call('lucky_wheel_campaign_save_v1',[...authority,n,randomUUID(),'5'.repeat(64),quota.id,1,'Race saved revision',false,JSON.stringify(quota.config)])+'SELECT pg_sleep(4);COMMIT;','save-a');await active('save-a');const sb=launch(prefix+spin(quota,'d'.repeat(64),randomUUID())+'COMMIT;','save-b');await blocked('save-b');const [rsa,rsb]=await Promise.all([sa,sb]);assert.equal(rsa.code,0,rsa.error);assert.equal(rsb.code,0,rsb.error);assert.equal(JSON.parse(rsb.output.trim()).outcome,'version_conflict');
const rollback=await launch(readFileSync(new URL('./202610100226_lucky_wheel.down.sql',import.meta.url),'utf8'));assert.notEqual(rollback.code,0);assert.match(rollback.error,/LUCKY_WHEEL_ROLLBACK_REFUSED_AFTER_USE/);
const receipt={database,sameVisitorOneAward:true,lastQuotaOneAward:true,oneCodeOneHold:true,releaseRestoresEligibility:true,saveSpinVersionConflict:true,rollbackRefusedAfterUse:true,fixtureRowsRemainOnlyInExplicitIsolatedDatabase:true};
if(process.env.WHEEL_TEST_RECEIPT_PATH)writeFileSync(process.env.WHEEL_TEST_RECEIPT_PATH,JSON.stringify(receipt,null,2)+'\n',{mode:0o600});
console.log(JSON.stringify(receipt));
