BEGIN;
SET LOCAL ROLE celebix_saas_owner;
DO $f$
DECLARE allowed text[] := ARRAY['discount','lucky_wheel','email_campaign','phone_campaign','whatsapp_campaign','blog_post','page','policy','marketplace_connection','general_setting','language_setting','payment_setting','shipping_setting','administrator_invite','accounting_profile','invoice_integration','seo_control','sitemap','social_preview','code_integration','indexing_request','notification_setting','hero_banner','promotion_banner','marquee_setting']; actual text[]; app_functions text[] := ARRAY['saas.merchant_admin_list(uuid,uuid,uuid,uuid,text,bigint,timestamp with time zone,text)','saas.merchant_admin_list_events(uuid,uuid,uuid,uuid,text,bigint,timestamp with time zone,text)','saas.merchant_admin_save(uuid,uuid,uuid,uuid,text,bigint,timestamp with time zone,uuid,text,uuid,bigint,text,text,jsonb,text)','saas.merchant_admin_archive(uuid,uuid,uuid,uuid,text,bigint,timestamp with time zone,uuid,text,uuid,bigint)','saas.merchant_admin_recover_operation(uuid,uuid,uuid,uuid,text,bigint,timestamp with time zone,uuid,text)']; helper_functions text[] := ARRAY['saas.merchant_admin_setting_text(jsonb,integer,integer)','saas.merchant_admin_setting_https_media_url(jsonb)','saas.merchant_admin_setting_destination(jsonb)','saas.merchant_admin_setting_email(jsonb)','saas.merchant_admin_setting_timestamp_value(jsonb)','saas.merchant_admin_setting_timestamp(jsonb)','saas.merchant_admin_required_action(text,boolean)','saas.merchant_admin_config_valid(text,jsonb)']; signature text; role_name text;
BEGIN
  SELECT pg_catalog.array_agg(match[1] ORDER BY match[1]) INTO actual FROM pg_catalog.pg_constraint c CROSS JOIN LATERAL pg_catalog.regexp_matches(pg_catalog.pg_get_constraintdef(c.oid),'''([^'']+)''','g') match WHERE c.conrelid='saas.merchant_admin_records'::regclass AND c.conname='merchant_admin_records_record_kind_check';
  IF actual IS DISTINCT FROM (SELECT pg_catalog.array_agg(value ORDER BY value) FROM pg_catalog.unnest(allowed) value) THEN RAISE EXCEPTION 'typed storefront record-kind constraint is not exact'; END IF;
  IF saas.merchant_admin_required_action('notification_setting',false)<>'configuration.read' OR saas.merchant_admin_required_action('marquee_setting',true)<>'configuration.manage' OR saas.merchant_admin_required_action('unrecognized',true) IS NOT NULL THEN RAISE EXCEPTION 'typed storefront action mapping invalid'; END IF;
  IF NOT saas.merchant_admin_config_valid('notification_setting','{"emailEnabled":true,"senderLabel":"Celebix","replyToEmail":"support@example.test"}'::jsonb) THEN RAISE EXCEPTION 'notification setting config rejected'; END IF;
  IF NOT saas.merchant_admin_config_valid('hero_banner','{"headline":"Hero","body":"Metin","imageUrl":"https://cdn.example.test/hero.webp","destination":"/hero","enabled":true}'::jsonb) THEN RAISE EXCEPTION 'hero banner config rejected'; END IF;
  IF NOT saas.merchant_admin_config_valid('promotion_banner','{"headline":"Promo","body":"Metin","destination":"/sale","startsAt":"2026-07-22T19:00:00.000Z","endsAt":"2026-08-22T19:00:00.000Z","enabled":true}'::jsonb) THEN RAISE EXCEPTION 'promotion banner config rejected'; END IF;
  IF NOT saas.merchant_admin_config_valid('marquee_setting','{"items":["Duyuru"],"icon":"truck","speed":"normal","direction":"left","animation":"continuous","enabled":true}'::jsonb) THEN RAISE EXCEPTION 'marquee setting config rejected'; END IF;
  IF saas.merchant_admin_config_valid('notification_setting','{"replyToEmail":".lead@example.test"}'::jsonb) OR saas.merchant_admin_config_valid('hero_banner','{"imageUrl":"https://cdn.example.test/a/../b"}'::jsonb) OR saas.merchant_admin_config_valid('hero_banner','{"destination":"/sale?next=%zz"}'::jsonb) OR saas.merchant_admin_config_valid('promotion_banner','{"startsAt":"2026-08-22T19:00:00.000Z","endsAt":"2026-07-22T19:00:00.000Z"}'::jsonb) OR saas.merchant_admin_config_valid('marquee_setting','{"items":[],"icon":"rocket"}'::jsonb) THEN RAISE EXCEPTION 'hostile typed storefront config accepted'; END IF;
  FOREACH signature IN ARRAY app_functions LOOP
    IF NOT has_function_privilege('celebix_saas_app',signature,'EXECUTE') THEN RAISE EXCEPTION 'application function privilege missing: %',signature; END IF;
    FOREACH role_name IN ARRAY ARRAY['celebix_saas_identity','celebix_saas_workflow','celebix_saas_host_resolver','celebix_saas_bootstrap','celebix_saas_observability','celebix_saas_migrator'] LOOP IF has_function_privilege(role_name,signature,'EXECUTE') THEN RAISE EXCEPTION 'application function privilege leaked: % %',role_name,signature; END IF; END LOOP;
  END LOOP;
  FOREACH signature IN ARRAY helper_functions LOOP
    FOREACH role_name IN ARRAY ARRAY['celebix_saas_app','celebix_saas_identity','celebix_saas_workflow','celebix_saas_host_resolver','celebix_saas_bootstrap','celebix_saas_observability','celebix_saas_migrator'] LOOP IF has_function_privilege(role_name,signature,'EXECUTE') THEN RAISE EXCEPTION 'helper function privilege leaked: % %',role_name,signature; END IF; END LOOP;
  END LOOP;
END $f$;
COMMIT;
