BEGIN;
SET LOCAL ROLE celebix_saas_owner;
SET LOCAL lock_timeout='5s';
DO $f$ BEGIN IF EXISTS(SELECT 1 FROM saas.content_authoring_operations) OR EXISTS(SELECT 1 FROM saas.content_authoring_origin_history) OR EXISTS(SELECT 1 FROM saas.content_authoring_settings) THEN RAISE EXCEPTION 'CONTENT_AUTHORING_ROLLBACK_REQUIRES_EMPTY_HISTORY'; END IF; END $f$;
DROP FUNCTION saas.content_authoring_begin(uuid,uuid,uuid,uuid,text,bigint,timestamptz,uuid,text,uuid,uuid,text,uuid,text,text,bigint,text);
DROP FUNCTION saas.content_authoring_get(uuid,uuid,uuid,uuid,text,bigint,timestamptz,uuid);
DROP FUNCTION saas.content_authoring_claim(uuid,uuid,uuid,uuid,text,bigint,timestamptz,uuid,bigint);
DROP FUNCTION saas.content_authoring_complete(uuid,uuid,uuid,uuid,text,bigint,timestamptz,uuid,uuid,bigint,jsonb,jsonb);
DROP FUNCTION saas.content_authoring_fail(uuid,uuid,uuid,uuid,text,bigint,timestamptz,uuid,uuid,bigint,text,text);
DROP FUNCTION saas.content_authoring_set_daily_limit(uuid,uuid,uuid,uuid,text,bigint,timestamptz,integer);
DROP FUNCTION saas.content_authoring_transition(uuid,uuid,uuid,uuid,text,bigint,timestamptz,text,uuid,bigint,uuid,jsonb);
DROP FUNCTION saas.content_authoring_payload(uuid);
DROP TABLE saas.content_authoring_origin_history;
DROP FUNCTION saas.content_authoring_origin_immutable();
DROP FUNCTION saas.content_authoring_origin_binding_guard();
DROP FUNCTION saas.content_authoring_usage_valid(jsonb);
DROP FUNCTION saas.content_authoring_draft_valid(jsonb,text);
DROP FUNCTION saas.content_authoring_nodes_count(jsonb);
DROP FUNCTION saas.content_authoring_text_valid(jsonb,integer,integer);
DROP FUNCTION saas.content_authoring_utf16_length(text);
DROP FUNCTION saas.content_authoring_object_valid(jsonb,text[],text[]);
DROP TABLE saas.content_authoring_operations;
DROP TABLE saas.content_authoring_settings;
COMMIT;
