BEGIN;
SET LOCAL ROLE celebix_saas_owner;
DROP FUNCTION IF EXISTS saas.orders_get_v2(uuid,uuid,uuid,uuid,text,bigint,timestamptz,uuid);
DROP FUNCTION IF EXISTS saas.orders_detail_projection_v2(uuid,uuid);
DROP FUNCTION IF EXISTS saas.orders_list_archived_v2(uuid,uuid,uuid,uuid,text,bigint,timestamptz,text,text,text,bigint,bigint,timestamptz,uuid);
DROP FUNCTION IF EXISTS saas.orders_list_v2(uuid,uuid,uuid,uuid,text,bigint,timestamptz,text,text,text,bigint,bigint,timestamptz,uuid);
DROP FUNCTION IF EXISTS saas.orders_list_scope_v2(uuid,uuid,uuid,uuid,text,bigint,timestamptz,text,text,text,bigint,bigint,timestamptz,uuid,boolean);
DROP FUNCTION IF EXISTS saas.orders_reader_metadata_v2(uuid,uuid);
DROP FUNCTION IF EXISTS saas.orders_search_matches_v2(text,text,text,text,text,text,text,text);
DROP FUNCTION IF EXISTS saas.orders_normalized_phone_v2(text);
COMMIT;
