import assert from "node:assert/strict";
import test from "node:test";
import type {TenantContext} from "@celebix/saas-contracts";
import type {QueryResult} from "pg";
import {PostgresCatalogWeightRepository,catalogWeightRepositoryErrorCode} from "./index.ts";
import type {PostgresClientLike,PostgresPoolLike} from "../postgres/pool.ts";

const STORE="10000000-0000-4000-8000-000000000001",PRINCIPAL="10000000-0000-4000-8000-000000000002",MEMBERSHIP="10000000-0000-4000-8000-000000000003",PLAN="10000000-0000-4000-8000-000000000004";
const PRODUCT="20000000-0000-4000-8000-000000000001",VARIANT="30000000-0000-4000-8000-000000000001",DECLARATION="40000000-0000-4000-8000-000000000001",OPERATION="50000000-0000-4000-8000-000000000001",NOW=new Date("2026-09-21T12:00:00.000Z");
function tenant(role:"store_owner"|"admin"|"editor"|"analyst"="store_owner"):TenantContext{return{schemaVersion:1,requestId:"private",principal:{id:PRINCIPAL,issuer:"https://id.test/oidc",subject:"private"},store:{id:STORE,slug:"store",status:"active"},membership:{id:MEMBERSHIP,role,status:"active"},entitlements:{schemaVersion:1,planId:PLAN,planCode:"growth",version:2,status:"active",features:["catalog"],limits:{products:100,staff:5,storageBytes:1024},validFrom:"2026-01-01T00:00:00.000Z"},locale:"tr-TR"}as TenantContext;}
const projection=(productId=PRODUCT)=>({profileMode:"general",productVersion:3,declarations:[{id:DECLARATION,productId,variantId:VARIANT,gramsMilli:3250,scope:"unspecified",salesUnit:"single",approximate:false,toleranceBasisPoints:null,source:"manual",sourceExcerpt:null,sourceDigest:null,sourceProductVersion:null,pricingVerified:false,version:1,updatedAt:"2026-09-21T12:00:00.000Z"}]});
class Client implements PostgresClientLike{queries:Array<{text:string;values?:unknown[]}>=[];releases:Array<unknown>=[];constructor(private result:{outcome:string;result_payload:unknown}){}async query(text:string,values?:unknown[]):Promise<QueryResult<Record<string,unknown>>>{this.queries.push({text,values});const rows=text.startsWith("SELECT outcome,result_payload FROM saas.")?[this.result]:[];return{rows,rowCount:rows.length}as unknown as QueryResult<Record<string,unknown>>;}release(value?:boolean|Error){this.releases.push(value);}}
class Pool implements PostgresPoolLike{constructor(private client:Client){}async connect(){return this.client;}}
function repository(client:Client){return new PostgresCatalogWeightRepository({pool:new Pool(client),role:"celebix_saas_app",timeouts:{poolCheckoutMs:10,statementMs:20,lockMs:30,idleTransactionMs:40},audit:()=>undefined});}

test("generic profile read sends only durable tenant authority and remains read-only",async()=>{const client=new Client({outcome:"found",result_payload:{profileMode:null,productVersion:3,declarations:[]}});const result=await repository(client).get({tenantContext:tenant("analyst"),now:NOW,productId:PRODUCT});assert.equal(result.profileMode,null);assert.equal(client.queries[0]?.text,"BEGIN READ ONLY");assert.deepEqual(client.queries[5]?.values,[STORE,PRINCIPAL,MEMBERSHIP,PLAN,"growth",2,NOW,PRODUCT]);assert.equal(client.queries.at(-1)?.text,"COMMIT");});

test("manual save is one versioned catalog-authorized write and carries no price or stock input",async()=>{const client=new Client({outcome:"saved",result_payload:projection()});const result=await repository(client).save({tenantContext:tenant("editor"),now:NOW,productId:PRODUCT,declarationId:DECLARATION,expectedVariantVersion:4,intent:{operationId:OPERATION,expectedProductVersion:3,expectedDeclarationVersion:0,target:{level:"variant",variantId:VARIANT},declaration:{gramsMilli:3250,scope:"unspecified",salesUnit:"single",approximate:false,toleranceBasisPoints:null}}});assert.equal(result.declarations[0]?.gramsMilli,3250);assert.equal(client.queries[0]?.text,"BEGIN ISOLATION LEVEL READ COMMITTED");const values=client.queries[5]?.values??[];assert.deepEqual(values.slice(0,8),[STORE,PRINCIPAL,MEMBERSHIP,PLAN,"growth",2,NOW,OPERATION]);assert.equal(values.includes(3250),true);assert.equal(values.filter(value=>typeof value==="object"&&value!==null).every(value=>value instanceof Date),true);assert.equal(client.queries.at(-1)?.text,"COMMIT");});

test("analyst mutation is denied before checkout and cross-product projections fail closed",async()=>{const denied=new Client({outcome:"saved",result_payload:projection()});await assert.rejects(()=>repository(denied).save({tenantContext:tenant("analyst"),now:NOW,productId:PRODUCT,declarationId:DECLARATION,expectedVariantVersion:4,intent:{operationId:OPERATION,expectedProductVersion:3,expectedDeclarationVersion:0,target:{level:"variant",variantId:VARIANT},declaration:{gramsMilli:3250,scope:"unspecified",salesUnit:"single",approximate:false,toleranceBasisPoints:null}}}),error=>catalogWeightRepositoryErrorCode(error)==="membership_denied");assert.equal(denied.queries.length,0);
  const corrupt=new Client({outcome:"found",result_payload:projection("90000000-0000-4000-8000-000000000001")});await assert.rejects(()=>repository(corrupt).get({tenantContext:tenant(),now:NOW,productId:PRODUCT}),error=>catalogWeightRepositoryErrorCode(error)==="unavailable");});
