import assert from "node:assert/strict";
import test from "node:test";

import { createCommerceAnalyticsHttpHandlers } from "./commerce-handler.ts";

const PANEL = "https://panel.saas-staging.celebix.site";
const COOKIE = "v1.key.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
const STORE = "10000000-0000-4000-8000-000000000001";
const NOW = new Date("2026-07-26T12:00:00.000Z");

function tenant() { return { schemaVersion: 1, requestId: STORE, principal: { id: "20000000-0000-4000-8000-000000000001", issuer: "https://id.test", subject: "safe" }, store: { id: STORE, slug: "store", status: "active" }, membership: { id: "30000000-0000-4000-8000-000000000001", role: "store_owner", status: "active" }, entitlements: { schemaVersion: 1, planId: "00000000-0000-4000-8000-000000000001", planCode: "growth", version: 1, status: "active", features: ["analytics"], limits: { products: 100, staff: 5, storageBytes: 1000 }, validFrom: "2026-01-01T00:00:00.000Z" }, locale: "tr-TR" }; }
function snapshot(start: Date, end: Date) { return { schemaVersion: 1, rangeStart: start.toISOString(), rangeEnd: end.toISOString(), currencies: [{ currency: "TRY", activeCarts: 4, candidateCarts: 1, eligibleCarts: 5, checkoutStarts: 3, checkoutAbandoned: 1, paymentFailures: 1, paidOrders: 2, grossRevenueMinor: 20000, refundedMinor: 1000, abandonedCarts: 3, abandonedValueMinor: 30000, recoveredCarts: 1, recoveredGrossMinor: 10000, recoveredRefundedMinor: 1000, recoveredNetMinor: 9000 }], attribution: [{ source: "atlas-qa", medium: "test", campaign: "cart-recovery", currency: "TRY", paidOrders: 2, grossRevenueMinor: 20000, abandonedCarts: 3, recoveredRevenueMinor: 10000 }], worker: { pending: 1, claimed: 0, retry: 0, deadLetter: 0, oldestPendingSeconds: 2, lastSuccessfulDelivery: NOW.toISOString(), deliveryLatencyMilliseconds: 25 }, settings: { candidateInactivityMinutes: 30, abandonedInactivityHours: 24, recoveryLinkHours: 72, automaticRecoveryEnabled: false, maximumMessageAttempts: 3, minimumMessageIntervalHours: 6, trackingPolicy: "anonymous_commerce", version: 1 } }; }
function request(path: string, cookie = true) { const headers = new Headers({ host: "store.admin.saas-staging.celebix.site" }); if (cookie) headers.set("cookie", `__Host-celebix_panel=${COOKIE}`); return new Request(`http://internal:3400${path}`, { headers }); }
function fixture(providerFails = false) { const calls: string[] = []; const runtime = { mode: "approved_staging", access: { readiness: { mode: "approved_staging" }, panelOrigin: PANEL, async resolveCredential() { return { kind: "authenticated", tenantContext: tenant() }; } }, analytics: { async commerceSnapshot(input: { rangeStart: Date; rangeEnd: Date }) { calls.push("commerce"); return snapshot(input.rangeStart, input.rangeEnd); }, async getConnectionAuthority() { calls.push("authority"); return { connectionId: "40000000-0000-4000-8000-000000000001", websiteId: "50000000-0000-4000-8000-000000000001", hostname: "store.example.test", status: "active", version: 1, lastVerifiedAt: NOW.toISOString() }; }, async dashboard() { calls.push("dashboard"); return { period: "month", rangeStart: "2026-07-01T00:00:00.000Z", rangeEnd: NOW.toISOString(), generatedAt: NOW.toISOString(), currency: "TRY", revenueCents: 20000, orders: { total: 2, paid: 2, cancelled: 0, refunded: 0 }, customers: { total: 2, newInPeriod: 2 }, catalog: { activeProducts: 1, lowStockVariants: 0 }, series: [], topProducts: [] }; } }, umami: { async summary() { calls.push("summary"); if (providerFails) throw new Error("private provider credential"); return { schemaVersion: 1, range: "30d", asOf: NOW.toISOString(), pageviews: 20, visitors: 10, visits: 12, bounces: 3, totalTimeSeconds: 100, activeVisitors: 1, bounceRateBasisPoints: 2500, averageVisitSeconds: 8, comparison: null, pageviewsSeries: [], visitsSeries: [] }; }, async metrics(input: { type: string }) { calls.push(`metrics:${input.type}`); if (providerFails) throw new Error("private provider credential"); return { schemaVersion: 1, range: "30d", type: input.type, asOf: NOW.toISOString(), items: [] }; } } }; return { calls, handlers: createCommerceAnalyticsHttpHandlers({ resolveRuntime: async () => runtime as never, now: () => new Date(NOW), requestId: () => STORE }) }; }

test("overview remains HTTP 200 with current PostgreSQL commerce truth when Umami is unavailable", async () => { const value = fixture(true); const response = await value.handlers.overview(request("/api/analytics/overview?range=30d")); assert.equal(response.status, 200); const body = await response.json(); assert.equal(body.status, "degraded"); assert.equal(body.traffic, null); assert.equal(body.commerce.currencies[0].grossRevenueMinor, 20000); assert.match(body.message, /Trafik verileri geçici olarak alınamıyor/); assert.doesNotMatch(JSON.stringify(body), /credential|websiteId|connectionId/); });
test("all commerce views are authenticated tenant reads with exact stable routes", async () => { const value = fixture(); for (const view of ["overview", "funnel", "abandoned-carts", "acquisition", "products", "status"] as const) { const response = await value.handlers[view](request(`/api/analytics/${view}?range=30d`)); assert.equal(response.status, 200, view); assert.equal((await response.json()).view, view); } assert.ok(value.calls.filter((value) => value === "commerce").length === 6); });
test("invalid dates, unknown query authority, private headers and missing sessions fail before data access", async () => { for (const path of ["/api/analytics/overview?range=365d", "/api/analytics/overview?range=30d&storeId=x", "/api/analytics/overview?from=2025-01-01&to=2026-07-26&timezone=Europe%2FIstanbul"]) { const value = fixture(); assert.equal((await value.handlers.overview(request(path))).status, 400); assert.deepEqual(value.calls, []); } const privateRequest = request("/api/analytics/overview?range=30d"); privateRequest.headers.set("x-store-id", STORE); assert.equal((await fixture().handlers.overview(privateRequest)).status, 400); assert.equal((await fixture().handlers.overview(request("/api/analytics/overview?range=30d", false))).status, 401); });
test("custom date range accepts at most thirteen months and returns no-store responses", async () => { const value = fixture(); const response = await value.handlers.overview(request("/api/analytics/overview?from=2026-01-01&to=2026-07-26&timezone=Europe%2FIstanbul")); assert.equal(response.status, 200); assert.equal(response.headers.get("cache-control"), "no-store"); assert.equal((await response.json()).range.timezone, "Europe/Istanbul"); });
test("funnel reads one Umami summary and one event metric budget while keeping paid orders canonical", async () => { const value = fixture(); const response = await value.handlers.funnel(request("/api/analytics/funnel?range=30d")); assert.equal(response.status, 200); const body = await response.json(); assert.equal(body.status, "complete"); assert.equal(body.traffic.summary.visitors, 10); assert.equal(body.traffic.events.type, "event"); assert.equal(body.commerce.currencies[0].paidOrders, 2); assert.deepEqual(value.calls, ["commerce", "authority", "summary", "metrics:event"]); });
