import assert from"node:assert/strict";import test from"node:test";import{createAnalyticsHttpHandlers}from"./handler.ts";
const ORIGIN="https://panel.saas-staging.celebix.site",TENANT_ADMIN_ORIGIN="https://store.admin.saas-staging.celebix.site",COOKIE="v1.key.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",ID="10000000-0000-4000-8000-000000000001",CONNECTION="40000000-0000-4000-8000-000000000001",WEBSITE="50000000-0000-4000-8000-000000000001",CANDIDATE_CONNECTION="40000000-0000-4000-8000-000000000099",CANDIDATE_WEBSITE="50000000-0000-4000-8000-000000000099",NOW=new Date("2026-07-26T12:00:00.000Z");
function tenant(){return{schemaVersion:1,requestId:ID,principal:{id:"20000000-0000-4000-8000-000000000001",issuer:"https://id.test",subject:"s"},store:{id:ID,slug:"store",status:"active"},membership:{id:"30000000-0000-4000-8000-000000000001",role:"store_owner",status:"active"},entitlements:{schemaVersion:1,planId:"00000000-0000-4000-8000-000000000001",planCode:"growth",version:1,status:"active",features:["analytics"],limits:{products:1,staff:1,storageBytes:1},validFrom:"2026-01-01T00:00:00.000Z"},locale:"tr-TR"}}
function connection(status="active",version=2){return{connectionId:CONNECTION,websiteId:WEBSITE,hostname:"store.example.test",status,version,lastVerifiedAt:NOW.toISOString()}}
function view(){return{schemaVersion:1,provider:"umami",status:"active",configured:true,hostname:"store.example.test",version:2,lastVerifiedAt:NOW.toISOString()}}
function fixture(patch:Record<string,unknown>={}){const calls:string[]=[];const analytics={async getConnection(){calls.push("get");return view()},async getConnectionAuthority(){calls.push("authority");return connection()},async beginConnection(){calls.push("begin");return{...connection("pending",1),outcome:"pending",replayed:false}},async activateConnection(){calls.push("activate");return{status:"active",version:2,updatedAt:NOW.toISOString(),replayed:false}},async disableConnection(){calls.push("disable");return{status:"disabled",version:3,updatedAt:NOW.toISOString(),replayed:false}},...patch.analytics as object};const umami={async createWebsite(){calls.push("create");return{id:WEBSITE,name:"Celebix store",domain:"store.example.test"}},async getWebsite(){calls.push("website");return null},async summary(){calls.push("summary");return{schemaVersion:1,range:"7d",asOf:NOW.toISOString(),pageviews:1,visitors:1,visits:1,bounces:0,totalTimeSeconds:1,activeVisitors:0,bounceRateBasisPoints:0,averageVisitSeconds:1,comparison:null,pageviewsSeries:[],visitsSeries:[]}},async metrics(){calls.push("metrics");return{schemaVersion:1,range:"7d",type:"path",asOf:NOW.toISOString(),items:[]}},...patch.umami as object};const access={readiness:{mode:"approved_staging"},panelOrigin:ORIGIN,async resolveCredential(){return patch.unauthenticated?{kind:"unauthenticated"}:{kind:"authenticated",tenantContext:tenant()}},async rotateCredential(){throw 0},async revokeCredential(){throw 0}};const runtime={mode:"approved_staging",access,analytics,umami,cache:{get(){return null},set(){},invalidateConnection(){}}};return{calls,handlers:createAnalyticsHttpHandlers({resolveRuntime:async()=>runtime as never,now:()=>NOW,requestId:()=>ID,uuid:(()=>{const ids=(patch.uuidValues as string[]|undefined)??[CONNECTION,WEBSITE];return()=>ids.shift()??ID})()})}}
function req(path:string,method="GET",body?:unknown,origin=ORIGIN,headers:HeadersInit={}){const h=new Headers(headers);h.set("cookie",`__Host-celebix_panel=${COOKIE}`);if(method==="POST"){h.set("origin",origin);h.set("content-type","application/json");h.set("idempotency-key",ID)}return new Request(`http://internal:3400${path}`,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)})}
test("authenticated connection read returns only the public DTO",async()=>{const f=fixture(),r=await f.handlers.connection.GET(req("/api/analytics/connection"));assert.equal(r.status,200);assert.deepEqual(await r.json(),view())});
test("missing session is unauthenticated",async()=>{const f=fixture({unauthenticated:true}),r=await f.handlers.connection.GET(req("/api/analytics/connection"));assert.equal(r.status,401)});
test("wrong origin is denied",async()=>assert.equal((await fixture().handlers.connection.POST(req("/api/analytics/connection","POST",{intent:"enable"},"https://evil.test"))).status,403));
test("comma and forwarded origin cannot rescue mutation",async()=>assert.equal((await fixture().handlers.connection.POST(req("/api/analytics/connection","POST",{intent:"enable"},`${ORIGIN}, https://evil.test`,{"x-forwarded-host":"panel.example.test"}))).status,403));
test("tenant admin analytics mutations survive internal proxy delivery and stay store-bound",async()=>{const accepted=fixture(),ok=await accepted.handlers.connection.POST(req("/api/analytics/connection","POST",{intent:"disable",expectedVersion:2},TENANT_ADMIN_ORIGIN,{"host":"customer-panel:3400"}));assert.equal(ok.status,200);assert.deepEqual(accepted.calls,["authority","disable"]);const rejected=fixture(),no=await rejected.handlers.connection.POST(req("/api/analytics/connection","POST",{intent:"disable",expectedVersion:2},"https://other-store.admin.saas-staging.celebix.site",{"host":"store.admin.saas-staging.celebix.site"}));assert.equal(no.status,403);assert.deepEqual(await no.json(),{code:"origin_denied"});assert.deepEqual(rejected.calls,[])});
test("unsupported method is rejected",async()=>assert.equal((await fixture().handlers.connection.POST(req("/api/analytics/connection","PUT"))).status,405));
test("content type and body schema are exact",async()=>{for(const body of [{},{intent:"enable",storeId:ID},{intent:"disable",expectedVersion:0}])assert.equal((await fixture().handlers.connection.POST(req("/api/analytics/connection","POST",body))).status,400)});
test("enable creates one provider website and activates once",async()=>{const f=fixture({analytics:{async getConnectionAuthority(){f.calls.push("authority");throw Object.assign(Error("missing"),{code:"not_configured"})}}}),r=await f.handlers.connection.POST(req("/api/analytics/connection","POST",{intent:"enable"}));assert.equal(r.status,200);assert.deepEqual(f.calls,["authority","begin","website","create","activate"])});
test("pending replay recovers through one provider GET",async()=>{const f=fixture({umami:{async getWebsite(){f.calls.push("website");return{id:WEBSITE,name:"Celebix store",domain:"store.example.test"}}}}),r=await f.handlers.connection.POST(req("/api/analytics/connection","POST",{intent:"enable"}));assert.equal(r.status,200);assert.equal(f.calls.includes("create"),false)});
test("pending replay reuses durable candidates and separates activation operation identity",async()=>{const inputs:Array<Record<string,unknown>>=[];const f=fixture({uuidValues:[CANDIDATE_CONNECTION,CANDIDATE_WEBSITE],analytics:{async getConnectionAuthority(){f.calls.push("authority");return connection("pending",1)},async beginConnection(input:Record<string,unknown>){f.calls.push("begin");inputs.push(input);return{...connection("pending",1),outcome:"pending",replayed:true}},async activateConnection(input:Record<string,unknown>){f.calls.push("activate");inputs.push(input);return{status:"active",version:2,updatedAt:NOW.toISOString(),replayed:false}}},umami:{async getWebsite(){f.calls.push("website");return{id:WEBSITE,name:"Celebix store",domain:"store.example.test"}}}}),r=await f.handlers.connection.POST(req("/api/analytics/connection","POST",{intent:"enable"}));assert.equal(r.status,200);assert.equal(inputs[0]?.connectionId,CONNECTION);assert.equal(inputs[0]?.websiteId,WEBSITE);assert.notEqual(inputs[1]?.operationId,ID)});
test("provider create uncertainty performs one read-only recovery",async()=>{const f=fixture({umami:{async createWebsite(){f.calls.push("create");throw Error("network")},async getWebsite(){f.calls.push("website");return f.calls.filter(x=>x==="website").length===1?null:{id:WEBSITE,name:"Celebix store",domain:"store.example.test"}}}}),r=await f.handlers.connection.POST(req("/api/analytics/connection","POST",{intent:"enable"}));assert.equal(r.status,200);assert.equal(f.calls.filter(x=>x==="create").length,1);assert.equal(f.calls.filter(x=>x==="website").length,2)});
test("disable derives the private connection server-side",async()=>{const f=fixture(),r=await f.handlers.connection.POST(req("/api/analytics/connection","POST",{intent:"disable",expectedVersion:2}));assert.equal(r.status,200);assert.deepEqual(f.calls,["authority","disable"])});
test("summary is authenticated and active-connection bound",async()=>{const f=fixture(),r=await f.handlers.summary.GET(req("/api/analytics/summary?range=7d"));assert.equal(r.status,200);assert.deepEqual(f.calls,["authority","summary"])});
test("metrics accept only exact range and type enums",async()=>{const f=fixture(),r=await f.handlers.metrics.GET(req("/api/analytics/metrics?range=7d&type=path"));assert.equal(r.status,200);assert.deepEqual(f.calls,["authority","metrics"])});
test("unknown query keys fail before provider",async()=>{const f=fixture(),r=await f.handlers.summary.GET(req("/api/analytics/summary?range=7d&storeId=x"));assert.equal(r.status,400);assert.equal(f.calls.includes("summary"),false)});
test("feature and subscription failures are finite",async()=>{const f=fixture({analytics:{async getConnection(){throw Object.assign(Error("private"),{code:"feature_not_enabled"})}}}),r=await f.handlers.connection.GET(req("/api/analytics/connection"));assert.equal(r.status,403);assert.deepEqual(await r.json(),{code:"feature_not_enabled"})});
test("provider failures expose no secrets",async()=>{const f=fixture({umami:{async summary(){throw Error("private-password")}}}),r=await f.handlers.summary.GET(req("/api/analytics/summary?range=7d"));assert.equal(r.status,503);assert.doesNotMatch(await r.text(),/private-password/)});
test("responses are no-store and contain no private authority",async()=>{const r=await fixture().handlers.connection.GET(req("/api/analytics/connection")),text=await r.text();assert.equal(r.headers.get("cache-control"),"no-store");assert.doesNotMatch(text,/tenant|principal|membership|websiteId|connectionId/i)});
