import assert from 'node:assert/strict';
import test from 'node:test';
const id = (n: number) => `22600000-0000-4000-8000-${String(n).padStart(12, '0')}`;
async function api() { const a = await import('./index.ts').catch(() => ({})); assert.equal(typeof (a as any).parseLuckyWheelConfig, 'function', 'strict wheel parser must exist'); return a as any; }
const rule = { schemaVersion: 1, benefit: { kind: 'percentage', percentageBps: 500 }, targets: { mode: 'all', include: [], exclude: [] }, audience: { mode: 'everyone' }, trigger: { kind: 'code', codes: ['SOURCE'] }, schedule: { timezone: 'Europe/Istanbul' }, limits: { totalUsage: null, perCustomerUsage: null, budgetMinor: null, orderMaximumMinor: null }, conditions: { minimumBasketMinor: 0, minimumQuantity: 0, minimumProductQuantity: 0, salesChannels: ['storefront'] }, combinationPolicy: { kind: 'none' }, priority: 1, marginPolicy: { kind: 'warn' }, progressMessagePolicy: { enabled: false } };
const config = { schemaVersion: 1, heading: 'Şansını dene', body: '', appearance: { sliceA: '#ffffff', sliceB: '#151515', background: '#ffffff', accent: '#ff8800' }, collectMode: 'either', repeatDays: 7, couponHours: 24, marketingOptInLabel: 'Kampanya mesajlarını almak istiyorum.', devices: { desktop: true, mobile: true }, allowedPaths: [], scrollPercent: null, startsAt: null, endsAt: null, prizes: [1, 2, 3, 4].map(n => ({ id: id(n), promotionId: id(n + 10), weightBps: 2500, issuanceLimit: null })) };
test('strict config accepts 4-8 positive integer weights summing to 10000 and rejects malformed nested settings', async () => { const a = await api(); assert.deepEqual(a.parseLuckyWheelConfig(config), config); for (const x of [{ ...config, extra: true }, { ...config, prizes: config.prizes.slice(0, 3) }, { ...config, prizes: config.prizes.map((p, n) => ({ ...p, weightBps: n === 0 ? 0 : 2500 })) }, { ...config, prizes: config.prizes.map(p => ({ ...p, weightBps: 2500.5 })) }, { ...config, appearance: { ...config.appearance, accent: 'red' } }, { ...config, devices: { desktop: false, mobile: false } }, { ...config, allowedPaths: ['/checkout'] }, { ...config, repeatDays: 91 }, { ...config, couponHours: 0 }, { ...config, startsAt: '2026-10-10T00:00:00.000Z', endsAt: '2026-10-09T00:00:00.000Z' }])
    assert.throws(() => a.parseLuckyWheelConfig(x)); });
test('source eligibility and labels come from real financial rules', async () => { const a = await api(); assert.equal(a.isLuckyWheelPromotionEligible(rule), true); assert.equal(a.luckyWheelRewardLabel(rule), '%5 indirim'); for (const patch of [{ audience: { mode: 'first_paid_order' } }, { limits: { ...rule.limits, perCustomerUsage: 1 } }, { limits: { ...rule.limits, totalUsage: 5 } }, { limits: { ...rule.limits, budgetMinor: 500 } }, { conditions: { ...rule.conditions, salesChannels: ['POS'] } }, { conditions: { ...rule.conditions, salesChannels: ['WEB'] } }, { benefit: { kind: 'fixed_amount', amountMinor: 1000, currency: 'EUR' } }])
    assert.equal(a.isLuckyWheelPromotionEligible({ ...rule, ...patch }), false); assert.equal(a.luckyWheelRewardLabel({ ...rule, benefit: { kind: 'fixed_amount', amountMinor: 1050, currency: 'TRY' } }), '10,50 ₺ indirim'); assert.deepEqual(a.luckyWheelRewardConditions({ ...rule, conditions: { ...rule.conditions, minimumBasketMinor: 5000 } }), ['En az 50,00 ₺ sepet tutarı.', 'Yalnız internet mağazasında geçerlidir.', 'Diğer indirimlerle birleştirilemez.']); });
test('spin has one normalized contact and rejects browser source identity or consent proof injection', async () => { const a = await api(), input = { campaignId: id(1), operationId: id(2), expectedVersion: 1, email: ' Person@Example.COM ', marketingConsent: false }; assert.equal(a.parseLuckyWheelSpinRequest(input).email, 'person@example.com'); for (const x of [{ ...input, email: '' }, { ...input, phone: '+905551111111' }, { ...input, source: 'wheel' }, { ...input, visitorDigest: 'a'.repeat(64) }, { ...input, marketingConsent: 'true' }, { ...input, expectedVersion: 0 }])
    assert.throws(() => a.parseLuckyWheelSpinRequest(x)); });
test('fixed result rejects label mismatch and impossible expiry/window; public output excludes private fields', async () => { const a = await api(), result = { operationId: id(1), campaignId: id(2), campaignVersion: 1, awardId: id(3), prizeId: id(4), label: '%5 indirim', couponCode: 'W-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', expiresAt: '2026-10-11T00:00:00.000Z', awardedAt: '2026-10-10T00:00:00.000Z', repeatEligibleAt: '2026-10-17T00:00:00.000Z', ruleDocument: { ...rule, trigger: { kind: 'code', codes: ['W-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'] } }, couponStatus: 'active' }; assert.deepEqual(a.parseLuckyWheelSpinResult(result), result); for (const x of [{ ...result, label: '%20 indirim' }, { ...result, email: 'person@example.com' }, { ...result, expiresAt: result.awardedAt }, { ...result, repeatEligibleAt: result.awardedAt }, { ...result, couponCode: 'W-ABCDEF' }, { ...result, couponCode: 'W-' + 'A'.repeat(31) }, { ...result, couponCode: 'W-' + 'A'.repeat(33) }])
    assert.throws(() => a.parseLuckyWheelSpinResult(x)); assert.deepEqual(a.parseLuckyWheelPublicSettings({ campaign: null }), { campaign: null }); assert.throws(() => a.parseLuckyWheelPublicSettings({ campaign: null, contacts: [] })); });
test('default config has six stable prize slots and truthful default rules', async () => { const a = await api(), c = a.createDefaultLuckyWheelConfig(); assert.equal(c.prizes.length, 6); assert.equal(c.prizes.reduce((s: any, p: any) => s + p.weightBps, 0), 10000); assert.equal(c.repeatDays, 7); assert.equal(c.couponHours, 24); assert.equal(c.collectMode, 'either'); assert.equal(c.scrollPercent, null); assert.equal(Object.isFrozen(c), true); });
test('public display rules contain no unissued source code and award rules contain only the issued code', async () => { const a = await api(), publicCampaign = { id: id(1), version: 1, heading: config.heading, body: config.body, appearance: config.appearance, collectMode: config.collectMode, repeatDays: config.repeatDays, couponHours: config.couponHours, marketingOptInLabel: config.marketingOptInLabel, devices: config.devices, allowedPaths: config.allowedPaths, scrollPercent: config.scrollPercent, prizes: config.prizes.map(p => ({ id: p.id, label: '%5 indirim', weightBps: p.weightBps, ruleDocument: { ...rule, trigger: { kind: 'automatic' } } })) }; assert.deepEqual(a.parseLuckyWheelPublicCampaign(publicCampaign), publicCampaign); assert.throws(() => a.parseLuckyWheelPublicCampaign({ ...publicCampaign, prizes: publicCampaign.prizes.map(p => ({ ...p, ruleDocument: rule })) })); const result = { operationId: id(1), campaignId: id(2), campaignVersion: 1, awardId: id(3), prizeId: id(4), label: '%5 indirim', couponCode: 'W-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', expiresAt: '2026-10-11T00:00:00.000Z', awardedAt: '2026-10-10T00:00:00.000Z', repeatEligibleAt: '2026-10-17T00:00:00.000Z', ruleDocument: { ...rule, trigger: { kind: 'code', codes: ['W-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'] } }, couponStatus: 'active' }; assert.deepEqual(a.parseLuckyWheelSpinResult(result), result); assert.throws(() => a.parseLuckyWheelSpinResult({ ...result, ruleDocument: rule })); });
