import type { OrderDetail, OrderEmailDeliverySummary, OrderPaymentStatus, OrderSource, OrderStatus } from "@celebix/saas-contracts";

export const FIXTURE_NOW = "2026-09-26T12:00:00.000Z";
const identity = (n: number) => `94000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
const names = ["Elif Yılmaz", "Deniz Aydın", "Ece Kaya", "Selin Demir", "Derya Aksoy", "Ada Yıldız", "İpek Arslan", "Merve Şahin", "Cem Öztürk", "Aslı Tekin", "Zeynep Koç", "Bora Çelik", "Nil Erdem", "Mina Güneş", "Oya Eren", "Ali Yalçın", "Seda Uçar", "Sarp Tan", "Lale Işık", "Ayça Sezer"];
const products = [ ["14 Ayar Altın Burgu Yüzük", "Ölçü 14", "YZK-014", 789000], ["14 Ayar Minimal Halka Küpe", "Sarı altın", "KPE-021", 569000], ["İnci Detaylı Altın Kolye", "45 cm", "KLY-008", 1249000], ["Altın İnce Zincir Bileklik", "17 cm", "BLK-012", 679000], ["22 Ayar Klasik Bilezik", "20 gram", "BLZ-020", 8240000] ] as const;
const states: readonly OrderStatus[] = ["confirmed", "preparing", "pending", "shipped", "delivered", "preparing", "confirmed", "delivered", "cancelled", "shipped", "pending", "refunded", "preparing", "delivered", "confirmed", "shipped", "pending", "delivered", "cancelled", "confirmed"];
const payments: readonly OrderPaymentStatus[] = ["completed", "completed", "pending", "completed", "completed", "processing", "failed", "completed", "failed", "completed", "processing", "refunded", "completed", "completed", "pending", "completed", "pending", "completed", "failed", "completed"];
const sources: readonly OrderSource[] = ["storefront", "storefront", "quick_link", "storefront", "in_store", "marketplace", "storefront", "manual_import", "manual", "storefront", "manual", "storefront", "storefront", "quick_link", "marketplace", "storefront", "manual", "in_store", "storefront", "storefront"];
export function createFixtureOrders(): OrderDetail[] {
  return names.map((name, i) => {
    const source = sources[i], createdAt = new Date(Date.UTC(2026, 8, 26 - Math.floor(i / 2), 11 - i % 5, 42 - i)).toISOString();
    const chosen = [products[i % products.length], ...(i === 0 || i === 3 || i === 7 ? [products[(i + 1) % products.length]] : [])];
    const items = chosen.map((p, j) => ({ id: identity(100 + i * 5 + j), position: j + 1, productName: p[0], variantName: p[1], sku: p[2], unitPriceCents: p[3], quantity: 1, discountCents: 0, lineTotalCents: p[3] }));
    const subtotalCents = items.reduce((n, p) => n + p.lineTotalCents, 0), shippingCents = source === "in_store" ? 0 : 7990, discountCents = i === 0 ? 25000 : 0;
    return { id: identity(i + 1), orderNumber: source === "manual_import" ? "30814" : source === "in_store" || source === "manual" ? `POS-${String(101 + i).padStart(7, "0")}` : `WEB-${String(1240 - i).padStart(6, "0")}`, source, customerName: source === "in_store" && i === 4 ? null : name, customerEmail: source === "in_store" && i === 4 ? null : `musteri${i + 1}@example.test`, customerPhone: source === "in_store" ? undefined : "+905550000000", currency: "TRY", totalCents: subtotalCents + shippingCents - discountCents, subtotalCents, shippingCents, discountCents, status: states[i], paymentStatus: payments[i], itemCount: items.length, version: 1, createdAt, updatedAt: createdAt, shippingAddress: source === "in_store" ? null : { recipientName: name, line1: "Örnek Mahallesi, Tasarım Sokak No: 12", line2: "Daire 4", district: "Kadıköy", city: "İstanbul", postalCode: "34710", country: "TR" }, tracking: ["shipped", "delivered"].includes(states[i]) && source !== "in_store" ? { carrier: "Örnek Kargo", trackingNumber: `DEMO${7023100 + i}`, shippedAt: createdAt } : undefined, items, notes: i === 0 ? [{ id: identity(600), body: "Hediye paketi hazırlanacak.", createdAt, updatedAt: createdAt }] : [], events: [{ id: identity(700 + i * 3), type: "created", message: "Sipariş oluşturuldu", createdAt }, { id: identity(701 + i * 3), type: "payment", message: "Ödeme kaydı güncellendi", createdAt }, { id: identity(702 + i * 3), type: "status", message: "Sipariş durumu güncellendi", createdAt }] };
  });
}
export function createFixtureNotifications(): OrderEmailDeliverySummary[] { return [ { id: identity(900), eventType: "order_received", recipientKind: "customer", recipientMask: "m••••@example.test", status: "delivered", occurredAt: FIXTURE_NOW, canRetry: false }, { id: identity(901), eventType: "payment_completed", recipientKind: "customer", recipientMask: "m••••@example.test", status: "failed", occurredAt: FIXTURE_NOW, canRetry: true } ]; }
