"use client";
import{useEffect,useState}from"react";
import{PanelLayoutClient}from"@/components/panel/PanelLayoutClient";
import{AccountingConsole}from"@/components/accounting/AccountingConsole";
import{InStoreSalesConsole}from"@/components/orders/InStoreSalesConsole";
import{MODEL}from"../mira-catalog/catalog-fixture";
const ID="9e000000-0000-4000-8000-000000000001",BANK="9e000000-0000-4000-8000-000000000002",date="2026-10-02T10:00:00.000Z";
const accounts=[{id:ID,name:"Mağaza kasası",type:"cash",currency:"TRY",balanceCents:1250000,version:1,createdAt:date},{id:BANK,name:"Ticari banka",type:"bank",currency:"TRY",balanceCents:3800000,version:1,createdAt:date},{id:"9e000000-0000-4000-8000-000000000003",name:"Harici POS",type:"card",currency:"TRY",balanceCents:800000,version:1,createdAt:date}];
const customer={id:ID,name:"Ayşe Kaya",firstName:"Ayşe",lastName:"Kaya",phone:"+905550001122",email:null,archived:false};
const debts=[{id:ID,customerId:ID,customerName:"Ayşe Kaya",customerPhone:customer.phone,customerArchived:false,orderId:ID,orderNumber:"POS-0000101",channel:"POS",currency:"TRY",saleCents:1100000,collectedCents:500000,returnCents:0,refundedCents:0,dueCents:600000,refundDueCents:0,occurredAt:date,dueDate:"2026-10-15",version:1},{id:BANK,customerId:BANK,customerName:"Deniz Yılmaz",customerPhone:"+905550002233",customerArchived:true,orderId:BANK,orderNumber:"POS-0000094",channel:"POS",currency:"TRY",saleCents:800000,collectedCents:800000,returnCents:800000,refundedCents:0,dueCents:0,refundDueCents:800000,occurredAt:"2026-09-28T08:30:00.000Z",dueDate:null,version:1}];
const events=[{id:ID,kind:"collection",currency:"TRY",amountCents:500000,accountId:ID,customerId:ID,orderId:ID,channel:"POS",paymentMethod:"cash",note:"Mağazada ilk tahsilat",category:null,documentNumber:null,metadata:{},actorMembershipId:ID,occurredAt:date,createdAt:date,reversesEventId:null,reversed:false,allocations:[]},{id:BANK,kind:"expense",currency:"TRY",amountCents:175000,accountId:BANK,customerId:null,orderId:null,channel:null,paymentMethod:"bank_transfer",note:"Ekim ofis kirası",category:"Kira",documentNumber:"GDR-2026-10",metadata:{},actorMembershipId:ID,occurredAt:date,createdAt:date,reversesEventId:null,reversed:false,allocations:[]}];
let sale={id:ID,saleNumber:"POS-fixture-101",contractVersion:3,status:"draft",version:1,locationId:ID,locationName:"Ana mağaza",ownerMembershipId:ID,ownerLabel:"Ayşe · Kasiyer",customerName:null,customerId:null,customer:null,initialCollectionCents:1100000,dueDate:null,finance:null,note:null,discount:null,paymentMethod:null,items:[{productId:ID,variantId:ID,productName:"Keten ceket",variantName:"Taş / M",sku:"KC-01-M",barcode:"000123",imageUrl:null,unitPriceCents:1100000,catalogUnitPriceCents:1100000,unitPriceOverrideCents:null,priceOverrideActorMembershipId:null,quantity:1,discountEligible:true,lineSubtotalCents:1100000,allocatedDiscountCents:0,lineNetCents:1100000}],totals:{subtotalCents:1100000,eligibleSubtotalCents:1100000,discountCents:0,totalCents:1100000},createdAt:date,updatedAt:date,paymentReceivedAt:null,completedAt:null,orderId:null,orderNumber:null};
export function AccountingCreditFixture({mode}:{mode:string}){const[ready,setReady]=useState(false);useEffect(()=>{const original=window.fetch;window.fetch=async(input,init)=>{const path=new URL(String(input),location.href).pathname,params=new URL(String(input),location.href).searchParams;let data:unknown=null;
 if(path==="/api/accounting/overview")data={currencies:[{currency:"TRY",salesCents:2250000,collectionsCents:1600000,returnCents:300000,refundsCents:0,expensesCents:175000,commissionCents:12000,dueCents:600000,overdueCents:150000,refundDueCents:800000,recordedWebPaymentsCents:600000}],accounts,recentEvents:events};
 else if(path==="/api/accounting/receivables")data={receivables:debts};else if(path==="/api/accounting/accounts"&&!init?.body)data={accounts,events};else if(path==="/api/accounting/expenses"&&!init?.body)data={expenses:events.filter(e=>e.kind==="expense")};else if(path.startsWith("/api/accounting/customers/"))data={customerId:ID,customerName:customer.name,customerPhone:customer.phone,customerArchived:false,currency:"TRY",version:1,dueCents:600000,refundDueCents:0,receivables:[debts[0]],events:[events[0]]};
 else if(path==="/api/accounting/collection-preview")data={customerId:ID,currency:"TRY",version:1,dueCents:600000,allocations:[{receivableId:ID,orderId:ID,amountCents:Number(params.get("amountCents"))}]};else if(path.startsWith("/api/accounting/operations"))data=null;else if(path.startsWith("/api/accounting/"))data={operationId:new Headers(init?.headers).get("idempotency-key"),replayed:false,event:events[0],account:null,customerAccount:null,finance:null};
 else if(path.endsWith("/in-store/bootstrap"))data={scopeKey:"browser-fixture-only",locations:[{id:ID,name:"Ana mağaza",isDefault:true}],permissions:{canSell:true,canEditPrice:true,canDiscount:true,discountLimitBps:9999,canResolve:true,canManageStaff:true,canSellOnCredit:true,canCollectReceivables:true,creditSalesAvailable:true},activeDraft:sale,heldSales:[],pendingSales:[],recentSales:[],summary:{completedCount:2,grossCents:1900000,discountCents:0,netCents:1900000,pendingPaymentCount:0}};
 else if(path.endsWith("/in-store/customers"))data={customers:[customer,{...customer,id:BANK,name:"Ayşe Demir",firstName:"Ayşe",lastName:"Demir",archived:true}]};else if(path.endsWith("/in-store/products"))data={products:[]};else if(path.endsWith("/in-store/sales")&&!init?.body)data={sales:[],nextCursor:null};else if(path.includes("/in-store/sales/")){if(init?.body){const body=JSON.parse(String(init.body));if(body.intent){const cents=body.intent.initialCollectionCents??1100000;sale={...sale,...body.intent,items:sale.items,customer:body.intent.customerId?customer:null,initialCollectionCents:cents,version:sale.version+1};}if(path.endsWith("/prepare"))sale={...sale,status:"payment_pending",version:sale.version+1};data={sale,replayed:false,priceChanged:false};}else data=sale;}
 else return original(input,init);
 if(path.includes("/in-store/")&&new Headers(init?.headers).get("x-celebix-in-store-version")==="4"){const additive=(value:typeof sale)=>({...value,salesChannel:"manual",socialPlatform:null,socialReference:null,fulfillmentMethod:"pickup",shippingAddress:null,billingAddress:null,shippingCents:0,paymentParts:[],prepareOperationId:null,abortRequested:false,totals:{...value.totals,shippingCents:0}});if(path.endsWith("/bootstrap")){const b=data as {permissions:Record<string,unknown>;activeDraft:typeof sale|null};data={...b,permissions:{...b.permissions,manualSalesV4Available:false},activeDraft:b.activeDraft?additive(b.activeDraft):null};}else if(path.includes("/sales/")){const r=data as {sale?:typeof sale};data=r.sale?{...r,sale:additive(r.sale)}:additive(data as typeof sale);}}
 return new Response(JSON.stringify({data}),{headers:{"content-type":"application/json"}});};setReady(true);return()=>{window.fetch=original;};},[]);return<PanelLayoutClient model={{...MODEL,storeSlug:"accounting-fixture",membershipLabel:"Yerel QA"}}>{ready?mode==="pos"?<InStoreSalesConsole/>:<AccountingConsole mode={mode as "overview"} canManage scopeKey="fixture:actor"/>:<p role="status">Test ekranı hazırlanıyor…</p>}</PanelLayoutClient>;}
