import assert from "node:assert/strict";
import { accessSync, constants, existsSync, mkdtempSync, mkdirSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import path from "node:path";
import { spawn, spawnSync } from "node:child_process";

const ROOT=path.resolve(import.meta.dirname,"../../.."),SQL=path.join(ROOT,"apps/owner/scripts/sql/saas"),DB="campaign_starter_composition";
const UP="202608010074_campaign_starter_composition.up.sql",DOWN="202608010074_campaign_starter_composition.down.sql",ASSERTIONS="202608010074_campaign_starter_composition_assertions.sql";
const STORE_A="10000000-0000-4000-8000-000000000074",STORE_B="10000000-0000-4000-8000-000000000075",HOST_A="campaign.starter.test",PLAN="00000000-0000-4000-8000-000000000001";
const PRINCIPAL_A="20000000-0000-4000-8000-000000000074",PRINCIPAL_B="20000000-0000-4000-8000-000000000075",MEMBERSHIP_A="30000000-0000-4000-8000-000000000074",MEMBERSHIP_B="30000000-0000-4000-8000-000000000075";
const ROOT_CATEGORY="40000000-0000-4000-8000-000000000074",CHILD_CATEGORY="40000000-0000-4000-8000-000000000075",OTHER_CATEGORY="40000000-0000-4000-8000-000000000076",INACTIVE_CATEGORY="40000000-0000-4000-8000-000000000077";
const HERO="50000000-0000-4000-8000-000000000074",MOBILE_HERO="50000000-0000-4000-8000-000000000075",CATEGORY_ASSET="50000000-0000-4000-8000-000000000076",OTHER_ASSET="50000000-0000-4000-8000-000000000077";
const PRODUCT="60000000-0000-4000-8000-000000000074",OTHER_PRODUCT="60000000-0000-4000-8000-000000000075",VARIANT="61000000-0000-4000-8000-000000000074",OTHER_VARIANT="61000000-0000-4000-8000-000000000075";
const COMPOSITION="70000000-0000-4000-8000-000000000074",NOW="2026-08-01T09:00:00.000Z";
let completed=0;const TOTAL=32;
let concurrentWinnerHeading;

function bin(name){const bundled=path.join(homedir(),".codex","tmp");let directories=[];try{directories=readdirSync(bundled,{withFileTypes:true}).filter((entry)=>entry.isDirectory()&&/^postgresql-[0-9.]+-install$/.test(entry.name)).map((entry)=>path.join(bundled,entry.name,"bin"));}catch{}for(const directory of [process.env.POSTGRES_BIN,...(process.env.PATH??"").split(path.delimiter),...directories]){if(!directory)continue;const candidate=path.join(directory,name);try{accessSync(candidate,constants.X_OK);return candidate;}catch{}}throw new Error(`DISPOSABLE_DB_EXECUTION_BLOCKED: missing ${name}`);}
function command(program,args,input="",allowFailure=false){const result=spawnSync(program,args,{cwd:ROOT,input,encoding:"utf8",env:{...process.env,LC_ALL:"C",LANG:"C"},maxBuffer:128*1024*1024});if(result.error)throw result.error;if(!allowFailure&&result.status!==0)throw new Error(`${path.basename(program)} failed\n${result.stderr}`);return result;}
function asyncCommand(program,args,input=""){return new Promise((resolve,reject)=>{const child=spawn(program,args,{cwd:ROOT,env:{...process.env,LC_ALL:"C",LANG:"C"}});let stdout="",stderr="";child.stdout.setEncoding("utf8");child.stderr.setEncoding("utf8");child.stdout.on("data",(chunk)=>stdout+=chunk);child.stderr.on("data",(chunk)=>stderr+=chunk);child.on("error",reject);child.on("close",(status)=>status===0?resolve({stdout,stderr,status}):reject(new Error(`${path.basename(program)} failed\n${stderr}`)));child.stdin.end(input);});}
function start(){const tools=Object.fromEntries(["initdb","pg_ctl","psql","pg_dump"].map((name)=>[name,bin(name)])),root=mkdtempSync(path.join(tmpdir(),"celebix-campaign-starter-")),data=path.join(root,"data"),socket=path.join(root,"socket"),port=20000+Math.floor(Math.random()*15000);mkdirSync(socket,{mode:0o700});command(tools.initdb,["-D",data,"--auth=trust","--username=postgres","--no-locale","--encoding=UTF8"]);command(tools.pg_ctl,["-D",data,"-o",`-k ${socket} -p ${port} -h ''`,"-l",path.join(root,"postgres.log"),"start"]);return{tools,root,data,socket,port,pid:Number.parseInt(readFileSync(path.join(data,"postmaster.pid"),"utf8"),10)};}
function stop(box){if(!box)return;command(box.tools.pg_ctl,["-D",box.data,"-m","fast","stop"],"",true);rmSync(box.root,{recursive:true,force:true});}
function psql(box,sql,database=DB,allowFailure=false){return command(box.tools.psql,["-h",box.socket,"-p",String(box.port),"-X","-qAt","-v","ON_ERROR_STOP=1","-U","postgres","-d",database],sql,allowFailure);}
function psqlAsync(box,sql){return asyncCommand(box.tools.psql,["-h",box.socket,"-p",String(box.port),"-X","-qAt","-v","ON_ERROR_STOP=1","-U","postgres","-d",DB],sql);}
function apply(box,file,database=DB){psql(box,readFileSync(path.join(SQL,file),"utf8"),database);}
function migrations(){const accepted=/(?:\.up|\.seed|\.freeze|_grants|_assertions|catalog_assertions)\.sql$/;return readdirSync(SQL).filter((file)=>{const sequence=Number.parseInt(file.slice(8,12),10);return Number.isSafeInteger(sequence)&&sequence<=71&&accepted.test(file)&&!file.includes(".down.");}).sort((left,right)=>{const a=Number.parseInt(left.slice(8,12),10),b=Number.parseInt(right.slice(8,12),10);if(a!==b)return a-b;const weight=(value)=>value.includes("assertions")?3:value.includes("freeze")||value.includes("grants")?2:1;return weight(left)-weight(right)||left.localeCompare(right);});}
function authority(store=STORE_A,principal=PRINCIPAL_A,membership=MEMBERSHIP_A){return `'${store}','${principal}','${membership}','${PLAN}','free_starter',1`;}
function createAsset(box,id,kind,operation,store=STORE_A,principal=PRINCIPAL_A,membership=MEMBERSHIP_A){const key=`stores/${store}/storefront/${kind}/${id}.webp`,url=`https://media.saas-staging.celebix.site/${key}`;return psql(box,`BEGIN;SET LOCAL ROLE celebix_saas_app;SELECT outcome FROM saas.storefront_asset_create(${authority(store,principal,membership)},1000000000,'${NOW}','${operation}','${"a".repeat(64)}','${id}','${kind}','${key}','${url}','image/webp','${kind}',1600,1000,2048);COMMIT;`).stdout.trim().split("\n").at(-1);}
function save(box,{kind="starter_theme_composition",config,id=COMPOSITION,operation,status="draft",expected=null,store=STORE_A,principal=PRINCIPAL_A,membership=MEMBERSHIP_A,fingerprint="b".repeat(64)}){return psql(box,`BEGIN;SET LOCAL ROLE celebix_saas_app;SELECT outcome FROM saas.merchant_admin_save(${authority(store,principal,membership)},'${NOW}','${operation}','${fingerprint}','${id}',${expected===null?"NULL":expected},'${kind}','Starter','${JSON.stringify(config).replaceAll("'","''")}'::jsonb,'${status}');COMMIT;`).stdout.trim().split("\n").at(-1);}
function campaign(box,host=HOST_A,database=DB){const output=psql(box,`BEGIN;SET LOCAL ROLE celebix_saas_host_resolver;SELECT outcome||'|'||COALESCE(result_payload::text,'null') FROM saas.public_campaign_home('${STORE_A}','${host}','${NOW}');COMMIT;`,database).stdout.trim().split("\n").at(-1),separator=output.indexOf("|");return{outcome:output.slice(0,separator),payload:JSON.parse(output.slice(separator+1))};}
function publication(box,database=DB){return JSON.parse(psql(box,`BEGIN;SET LOCAL ROLE celebix_saas_owner;SELECT pg_catalog.jsonb_build_object('recordId',record_id::text,'recordVersion',record_version,'config',config,'publishedAt',published_at) FROM saas.campaign_starter_publications WHERE store_id='${STORE_A}';COMMIT;`,database).stdout.trim().split("\n").at(-1));}
function invalidatedCampaign(box,{mutation,operation,fingerprint}){const config=JSON.stringify(composition()).replaceAll("'","''"),lines=psql(box,`BEGIN;SET LOCAL ROLE celebix_saas_owner;${mutation};SET LOCAL ROLE celebix_saas_host_resolver;SELECT 'campaign|'||outcome||'|'||COALESCE(result_payload::text,'null') FROM saas.public_campaign_home('${STORE_A}','${HOST_A}','${NOW}');SET LOCAL ROLE celebix_saas_app;SELECT 'publish|'||outcome FROM saas.merchant_admin_save(${authority()},'${NOW}','${operation}','${fingerprint}','${COMPOSITION}',4,'starter_theme_composition','Starter','${config}'::jsonb,'active');ROLLBACK;`).stdout.trim().split("\n"),publicLine=lines.find((line)=>line.startsWith("campaign|")),publishLine=lines.find((line)=>line.startsWith("publish|")),separator=publicLine.indexOf("|",9);return{campaign:{outcome:publicLine.slice(9,separator),payload:JSON.parse(publicLine.slice(separator+1))},publishOutcome:publishLine.slice(8)};}
function composition(overrides={}){return{schemaVersion:1,visual:{colorScheme:"neutral",headingStyle:"serif",cornerStyle:"soft",headerStyle:"overlay",productCardStyle:"editorial",productImageRatio:"portrait"},announcement:{enabled:true,items:["Güvenli alışveriş"],destination:"/pages/odeme-teslimat"},navigation:{rootCategoryIds:[ROOT_CATEGORY],featuredCategoryId:ROOT_CATEGORY,featuredAssetId:CATEGORY_ASSET},sections:[{kind:"hero",enabled:true,slides:[{eyebrow:"Yeni sezon",heading:"Zamansız seçkiler",body:"Yeni ürünleri keşfedin.",desktopAssetId:HERO,mobileAssetId:MOBILE_HERO,destination:"/products",productId:PRODUCT}]},{kind:"category_grid",enabled:true,heading:"Kategoriler",categoryIds:[ROOT_CATEGORY]},{kind:"product_row",enabled:true,heading:"Yeni ürünler",source:"latest",limit:8},{kind:"product_row",enabled:true,heading:"İndirimdekiler",source:"sale",limit:4},{kind:"product_row",enabled:true,heading:"Takılar",source:"category",categoryId:ROOT_CATEGORY,limit:4},{kind:"split_campaign",enabled:true,panels:[{heading:"Takılar",assetId:HERO,destination:"/categories/takilar"}]},{kind:"brand_story",enabled:true,eyebrow:"Hikâyemiz",heading:"Özenle seçildi",body:"Kalıcı tasarımlar.",assetId:HERO,destination:"/pages/hakkimizda"}],productDetail:{galleryStyle:"grid",showSku:true,showBrand:true,showRelatedProducts:true,mobileStickyPurchase:true},cart:{showCheckoutReadiness:true,showShippingProgress:true,trustMessage:"Güvenli ödeme"},...overrides};}
async function scenario(name,run){await run();completed+=1;console.log(`PASS ${completed}/${TOTAL} ${name}`);}

async function main(){let box;try{
 for(const file of [UP,DOWN,ASSERTIONS])assert.equal(existsSync(path.join(SQL,file)),true,file);box=start();psql(box,`CREATE DATABASE ${DB};`,"postgres");for(const file of migrations())apply(box,file);for(const file of ["202607310072_storefront_cart_checkout.up.sql","202608010073_storefront_checkout_readiness.up.sql","202608010073_storefront_checkout_readiness_assertions.sql"])apply(box,file);apply(box,UP);apply(box,ASSERTIONS);
 await scenario("PostgreSQL 16 installs migration 074",()=>assert.match(psql(box,"SHOW server_version;").stdout,/^16\./));
 await scenario("catalog assertions accept the exact finite API",()=>assert.equal(psql(box,"SELECT saas.merchant_admin_required_action('starter_theme_composition',true);").stdout.trim(),"configuration.manage"));
 await scenario("valid minimal composition passes SQL validation",()=>assert.equal(psql(box,`SELECT saas.campaign_starter_composition_valid('${JSON.stringify(composition({navigation:{rootCategoryIds:[]},sections:[{kind:"product_row",enabled:true,heading:"Yeni",source:"latest",limit:8}]}))}'::jsonb);`).stdout.trim(),"t"));
 await scenario("unknown and incomplete composition shapes fail closed",()=>{assert.equal(psql(box,"SELECT saas.campaign_starter_composition_valid('{\"schemaVersion\":1}'::jsonb);").stdout.trim(),"f");assert.equal(psql(box,`SELECT saas.campaign_starter_composition_valid('${JSON.stringify({...composition(),storeId:STORE_A})}'::jsonb);`).stdout.trim(),"f");});
 psql(box,`BEGIN;SET LOCAL ROLE celebix_saas_owner;
 INSERT INTO saas.stores(id,name,slug,status,locale,currency,theme_key,created_at,updated_at) VALUES('${STORE_A}','Pilot','pilot','active','tr','TRY','starter','2026-01-01','2026-01-01'),('${STORE_B}','Other','other','active','tr','TRY','starter','2026-01-01','2026-01-01');
 INSERT INTO saas.principals(id,issuer,subject,email,email_verified,created_at,updated_at) VALUES('${PRINCIPAL_A}','https://identity.example.test/oidc','a','a@example.test',true,'2026-01-01','2026-01-01'),('${PRINCIPAL_B}','https://identity.example.test/oidc','b','b@example.test',true,'2026-01-01','2026-01-01');
 INSERT INTO saas.memberships(id,principal_id,store_id,role,status,created_at,updated_at) VALUES('${MEMBERSHIP_A}','${PRINCIPAL_A}','${STORE_A}','store_owner','active','2026-01-01','2026-01-01'),('${MEMBERSHIP_B}','${PRINCIPAL_B}','${STORE_B}','store_owner','active','2026-01-01','2026-01-01');
 INSERT INTO saas.subscriptions(id,store_id,plan_id,plan_code,plan_version,status,valid_from,created_at,updated_at) VALUES('71000000-0000-4000-8000-000000000074','${STORE_A}','${PLAN}','free_starter',1,'active','2026-01-01','2026-01-01','2026-01-01'),('71000000-0000-4000-8000-000000000075','${STORE_B}','${PLAN}','free_starter',1,'active','2026-01-01','2026-01-01','2026-01-01');
 INSERT INTO saas.store_domains(id,store_id,hostname,hostname_type,status,is_primary,verified_at,created_at,updated_at,version) VALUES('72000000-0000-4000-8000-000000000074','${STORE_A}','${HOST_A}','custom_domain','active',true,'2026-01-01','2026-01-01','2026-01-01',1);
 INSERT INTO saas.catalog_categories(id,store_id,parent_id,name,slug,position,status,version,archived_at,created_at,updated_at) VALUES('${ROOT_CATEGORY}','${STORE_A}',NULL,'Takılar','takilar',0,'active',1,NULL,'2026-01-01','2026-01-01'),('${CHILD_CATEGORY}','${STORE_A}','${ROOT_CATEGORY}','Yüzükler','yuzukler',0,'active',1,NULL,'2026-01-01','2026-01-01'),('${INACTIVE_CATEGORY}','${STORE_A}',NULL,'Arşiv','arsiv',1,'archived',1,'2026-01-01','2026-01-01','2026-01-01'),('${OTHER_CATEGORY}','${STORE_B}',NULL,'Other','other',0,'active',1,NULL,'2026-01-01','2026-01-01');
 INSERT INTO saas.products(id,store_id,slug,title,description,status,currency,version,archived_at,created_at,updated_at) VALUES('${PRODUCT}','${STORE_A}','altin-bileklik','Altın Bileklik',NULL,'active','TRY',1,NULL,'2026-01-01','2026-01-01'),('${OTHER_PRODUCT}','${STORE_B}','other-product','Other Product',NULL,'active','TRY',1,NULL,'2026-01-01','2026-01-01');
 SELECT pg_catalog.set_config('saas.inventory.source_marker','catalog_adjustment',true);SELECT pg_catalog.set_config('saas.inventory.source_id','62000000-0000-4000-8000-000000000074',true);SELECT pg_catalog.set_config('saas.inventory.source_time','${NOW}',true);
 INSERT INTO saas.product_variants(id,product_id,store_id,title,sku,barcode,price_cents,compare_at_cents,cost_cents,stock_tracking,stock_quantity,status,attributes,version,archived_at,created_at,updated_at) VALUES('${VARIANT}','${PRODUCT}','${STORE_A}','Standart','PILOT-1',NULL,10000,12000,NULL,true,5,'active','{}',1,NULL,'2026-01-01','2026-01-01'),('${OTHER_VARIANT}','${OTHER_PRODUCT}','${STORE_B}','Standart','OTHER-1',NULL,5000,NULL,NULL,true,5,'active','{}',1,NULL,'2026-01-01','2026-01-01');
 SELECT pg_catalog.set_config('saas.inventory.source_marker','',true);SELECT pg_catalog.set_config('saas.inventory.source_id','',true);SELECT pg_catalog.set_config('saas.inventory.source_time','',true);
 INSERT INTO saas.catalog_product_categories(store_id,product_id,category_id,position) VALUES('${STORE_A}','${PRODUCT}','${ROOT_CATEGORY}',0);COMMIT;`);
 await scenario("fixture authority is isolated into two stores",()=>assert.equal(psql(box,"SELECT count(*) FROM saas.stores WHERE status='active';").stdout.trim(),"2"));
 await scenario("app creates only tenant-keyed public assets",()=>{assert.equal(createAsset(box,HERO,"hero","73000000-0000-4000-8000-000000000074"),"committed");assert.equal(createAsset(box,MOBILE_HERO,"hero","73000000-0000-4000-8000-000000000075"),"committed");assert.equal(createAsset(box,CATEGORY_ASSET,"category","73000000-0000-4000-8000-000000000076"),"committed");assert.equal(createAsset(box,OTHER_ASSET,"category","73000000-0000-4000-8000-000000000077",STORE_B,PRINCIPAL_B,MEMBERSHIP_B),"committed");});
 await scenario("category image authority is persisted before composition",()=>{assert.equal(save(box,{config:composition(),operation:"75000000-0000-4000-8000-000000000073",status:"active"}),"invalid_input");assert.equal(save(box,{kind:"category_showcase",config:{heading:"Kategoriler",enabled:true,items:[{categoryId:ROOT_CATEGORY,assetId:CATEGORY_ASSET}]},id:"74000000-0000-4000-8000-000000000074",operation:"75000000-0000-4000-8000-000000000074",status:"active"}),"saved");});
 await scenario("cross-store navigation category is denied",()=>assert.equal(save(box,{config:composition({navigation:{rootCategoryIds:[OTHER_CATEGORY]}}),operation:"75000000-0000-4000-8000-000000000075"}),"invalid_input"));
 await scenario("cross-store featured asset is denied",()=>assert.equal(save(box,{config:composition({navigation:{rootCategoryIds:[ROOT_CATEGORY],featuredCategoryId:ROOT_CATEGORY,featuredAssetId:OTHER_ASSET}}),operation:"75000000-0000-4000-8000-000000000076"}),"invalid_input"));
 await scenario("cross-store hotspot product is denied",()=>{const value=composition();value.sections[0].slides[0].productId=OTHER_PRODUCT;assert.equal(save(box,{config:value,operation:"75000000-0000-4000-8000-000000000077"}),"invalid_input");});
 await scenario("inactive reference is denied",()=>{const value=composition({navigation:{rootCategoryIds:[INACTIVE_CATEGORY]}});assert.equal(save(box,{config:value,operation:"75000000-0000-4000-8000-000000000078",status:"active"}),"invalid_input");});
 await scenario("draft composition saves through versioned authority",()=>assert.equal(save(box,{config:composition(),operation:"75000000-0000-4000-8000-000000000079",status:"draft"}),"saved"));
 await scenario("draft composition is invisible to public campaign resolver",()=>assert.equal(campaign(box).outcome,"not_found"));
 await scenario("draft read is tenant-authorized and exact",()=>{const payload=JSON.parse(psql(box,`BEGIN;SET LOCAL ROLE celebix_saas_app;SELECT result_payload FROM saas.merchant_admin_list(${authority()},'${NOW}','starter_theme_composition');COMMIT;`).stdout.trim().split("\n").at(-1)),record=payload.items[0];assert.equal(record.status,"draft");assert.equal(record.config.schemaVersion,1);});
 await scenario("optimistic publish advances the exact record",()=>{assert.equal(save(box,{config:composition(),operation:"75000000-0000-4000-8000-000000000080",status:"active",expected:1,fingerprint:"c".repeat(64)}),"saved");const published=campaign(box);assert.equal(published.outcome,"found");assert.equal(published.payload.presentation.sections.find((section)=>section.kind==="hero").slides[0].heading,"Zamansız seçkiler");const edited=composition();edited.sections[0].slides[0].heading="Yeni yayın başlığı";assert.equal(save(box,{config:edited,operation:"75000000-0000-4000-8000-000000000084",status:"draft",expected:2,fingerprint:"2".repeat(64)}),"saved");assert.deepEqual(campaign(box),published);assert.equal(save(box,{config:edited,operation:"75000000-0000-4000-8000-000000000085",status:"active",expected:3,fingerprint:"3".repeat(64)}),"saved");const next=campaign(box);assert.equal(next.outcome,"found");assert.equal(next.payload.presentation.sections.find((section)=>section.kind==="hero").slides[0].heading,"Yeni yayın başlığı");assert.notDeepEqual(next,published);});
 await scenario("public campaign projection is schema-v2 only",()=>{const resolved=campaign(box);assert.equal(resolved.outcome,"found");assert.equal(resolved.payload.presentation.schemaVersion,2);const detail=JSON.parse(psql(box,`BEGIN;SET LOCAL ROLE celebix_saas_host_resolver;SELECT result_payload FROM saas.public_get_product_by_slug('${STORE_A}','${HOST_A}','${NOW}','altin-bileklik');COMMIT;`).stdout.trim().split("\n").at(-1));assert.deepEqual(detail.categoryPath,[{name:"Takılar",slug:"takilar"}]);const related=JSON.parse(psql(box,`BEGIN;SET LOCAL ROLE celebix_saas_host_resolver;SELECT result_payload FROM saas.public_storefront_related_products('${STORE_A}','${HOST_A}','${NOW}','altin-bileklik',4);COMMIT;`).stdout.trim().split("\n").at(-1));assert.deepEqual(related,[]);});
 await scenario("public projection contains no private references or object keys",()=>assert.doesNotMatch(JSON.stringify(campaign(box).payload),/assetId|categoryId|productId|object_key|objectKey/i));
 await scenario("navigation preserves bounded root-child hierarchy",()=>{const item=campaign(box).payload.presentation.navigation.items[0];assert.equal(item.slug,"takilar");assert.deepEqual(item.children.map((child)=>child.slug),["yuzukler"]);const invalidated=invalidatedCampaign(box,{mutation:`UPDATE saas.catalog_categories SET status='archived',archived_at='${NOW}',updated_at='${NOW}',version=version+1 WHERE store_id='${STORE_A}' AND id='${ROOT_CATEGORY}'`,operation:"75000000-0000-4000-8000-000000000086",fingerprint:"4".repeat(64)}),degraded=invalidated.campaign;assert.equal(degraded.outcome,"found");assert.deepEqual(degraded.payload.presentation.navigation.items,[]);assert.equal(degraded.payload.presentation.sections.some((section)=>section.kind==="category_grid"),false);assert.equal(degraded.payload.presentation.sections.some((section)=>section.kind==="product_row"&&section.source==="category"),false);assert.equal(degraded.payload.presentation.sections.some((section)=>section.kind==="hero"),true);assert.equal(invalidated.publishOutcome,"invalid_input");const featuredInvalidated=invalidatedCampaign(box,{mutation:`UPDATE saas.storefront_assets SET status='archived',archived_at='${NOW}',updated_at='${NOW}',version=version+1 WHERE store_id='${STORE_A}' AND id='${CATEGORY_ASSET}'`,operation:"75000000-0000-4000-8000-000000000089",fingerprint:"7".repeat(64)}),featuredItem=featuredInvalidated.campaign.payload.presentation.navigation.items[0];assert.equal(featuredItem.slug,"takilar");assert.equal("featured" in featuredItem,false);assert.equal(featuredInvalidated.publishOutcome,"invalid_input");});
 await scenario("hero resolves only canonical public R2 metadata",()=>{const slide=campaign(box).payload.presentation.sections.find((section)=>section.kind==="hero").slides[0];assert.equal(slide.desktopImage.url.includes(`/hero/${HERO}.webp`),true);assert.equal(slide.mobileImage.width,1600);const invalidated=invalidatedCampaign(box,{mutation:`UPDATE saas.storefront_assets SET status='archived',archived_at='${NOW}',updated_at='${NOW}',version=version+1 WHERE store_id='${STORE_A}' AND id='${HERO}'`,operation:"75000000-0000-4000-8000-000000000087",fingerprint:"5".repeat(64)}),degraded=invalidated.campaign;assert.equal(degraded.outcome,"found");assert.equal(degraded.payload.presentation.sections.some((section)=>section.kind==="hero"),false);assert.equal(degraded.payload.presentation.sections.some((section)=>section.kind==="split_campaign"),false);const story=degraded.payload.presentation.sections.find((section)=>section.kind==="brand_story");assert.deepEqual(story,{kind:"brand_story",eyebrow:"Hikâyemiz",heading:"Özenle seçildi",body:"Kalıcı tasarımlar.",destination:"/pages/hakkimizda"});assert.equal(degraded.payload.presentation.sections.some((section)=>section.kind==="category_grid"),true);assert.equal(degraded.payload.presentation.sections.filter((section)=>section.kind==="product_row").length,3);assert.equal(invalidated.publishOutcome,"invalid_input");const mobileInvalidated=invalidatedCampaign(box,{mutation:`UPDATE saas.storefront_assets SET status='archived',archived_at='${NOW}',updated_at='${NOW}',version=version+1 WHERE store_id='${STORE_A}' AND id='${MOBILE_HERO}'`,operation:"75000000-0000-4000-8000-000000000090",fingerprint:"8".repeat(64)}),mobileSlide=mobileInvalidated.campaign.payload.presentation.sections.find((section)=>section.kind==="hero").slides[0];assert.equal(mobileSlide.heading,"Yeni yayın başlığı");assert.ok(mobileSlide.desktopImage);assert.equal("mobileImage" in mobileSlide,false);assert.equal(mobileInvalidated.publishOutcome,"invalid_input");});
 await scenario("hotspot resolves persisted product and price",()=>{const hotspot=campaign(box).payload.presentation.sections.find((section)=>section.kind==="hero").slides[0].hotspot;assert.deepEqual(hotspot,{productSlug:"altin-bileklik",title:"Altın Bileklik",priceCents:10000,currency:"TRY"});const invalidated=invalidatedCampaign(box,{mutation:`UPDATE saas.products SET status='archived',archived_at='${NOW}',updated_at='${NOW}',version=version+1 WHERE store_id='${STORE_A}' AND id='${PRODUCT}'`,operation:"75000000-0000-4000-8000-000000000088",fingerprint:"6".repeat(64)}),degraded=invalidated.campaign;assert.equal(degraded.outcome,"found");const degradedSlide=degraded.payload.presentation.sections.find((section)=>section.kind==="hero").slides[0];assert.equal("hotspot" in degradedSlide,false);assert.equal(degradedSlide.heading,"Yeni yayın başlığı");assert.equal(degraded.payload.presentation.sections.filter((section)=>section.kind==="product_row").length,3);assert.equal(degraded.payload.productRows.every((row)=>row.items.length===0),true);assert.equal(invalidated.publishOutcome,"invalid_input");});
 await scenario("latest product row is bounded and active",()=>{const row=campaign(box).payload.productRows.find((entry)=>entry.key==="latest-0");assert.deepEqual(row.items.map((item)=>item.slug),["altin-bileklik"]);assert.ok(row.items.length<=8);});
 await scenario("sale product row derives compare-at authority",()=>{const row=campaign(box).payload.productRows.find((entry)=>entry.key==="sale-1");assert.equal(row.items[0].compareAtCents,12000);assert.ok(row.items.length<=4);});
 await scenario("category row resolves only related products",()=>{const row=campaign(box).payload.productRows.find((entry)=>entry.key==="category-2");assert.deepEqual(row.items.map((item)=>item.slug),["altin-bileklik"]);});
 await scenario("wrong hostname cannot reuse public store authority",()=>assert.equal(campaign(box,"other.starter.test").outcome,"not_found"));
 await scenario("app and resolver roles have no direct table access",()=>{assert.notEqual(psql(box,"SET ROLE celebix_saas_app;SELECT count(*) FROM saas.merchant_admin_records;",DB,true).status,0);assert.notEqual(psql(box,"SET ROLE celebix_saas_host_resolver;SELECT count(*) FROM saas.products;",DB,true).status,0);});
 await scenario("same operation replays without a second write",()=>assert.equal(save(box,{config:composition(),operation:"75000000-0000-4000-8000-000000000080",status:"active",expected:1,fingerprint:"c".repeat(64)}),"operation_replayed"));
 await scenario("operation fingerprint mismatch is denied",()=>assert.equal(save(box,{config:composition(),operation:"75000000-0000-4000-8000-000000000080",status:"active",expected:1,fingerprint:"d".repeat(64)}),"operation_mismatch"));
 await scenario("concurrent same-version publish produces one winner",async()=>{const writers=[{operation:"75000000-0000-4000-8000-000000000081",fingerprint:"e".repeat(64),heading:"Eşzamanlı yayın A"},{operation:"75000000-0000-4000-8000-000000000082",fingerprint:"f".repeat(64),heading:"Eşzamanlı yayın B"}].map((writer)=>{const value=composition();value.sections[0].slides[0].heading=writer.heading;return{...writer,config:value};}),sql=(writer)=>`BEGIN;SET LOCAL ROLE celebix_saas_app;SELECT outcome FROM saas.merchant_admin_save(${authority()},'${NOW}','${writer.operation}','${writer.fingerprint}','${COMPOSITION}',4,'starter_theme_composition','Starter','${JSON.stringify(writer.config).replaceAll("'","''")}'::jsonb,'active');SELECT pg_sleep(0.2);COMMIT;`;const results=await Promise.all(writers.map((writer)=>psqlAsync(box,sql(writer))));const outcomes=results.map((result)=>result.stdout.trim().split("\n")[0]);assert.deepEqual([...outcomes].sort(),["saved","version_conflict"]);const winnerIndex=outcomes.indexOf("saved"),loserIndex=outcomes.indexOf("version_conflict"),winner=writers[winnerIndex],loser=writers[loserIndex],snapshot=publication(box),resolved=campaign(box);concurrentWinnerHeading=winner.heading;assert.equal(snapshot.recordId,COMPOSITION);assert.equal(snapshot.recordVersion,5);assert.deepEqual(snapshot.config,winner.config);assert.notDeepEqual(snapshot.config,loser.config);assert.equal(snapshot.config.sections[0].slides[0].heading,winner.heading);assert.equal(resolved.payload.presentation.sections.find((section)=>section.kind==="hero").slides[0].heading,winner.heading);assert.notEqual(resolved.payload.presentation.sections.find((section)=>section.kind==="hero").slides[0].heading,loser.heading);});
 await scenario("stale expected version remains a finite conflict",()=>assert.equal(save(box,{config:composition(),operation:"75000000-0000-4000-8000-000000000083",status:"active",expected:4,fingerprint:"1".repeat(64)}),"version_conflict"));
 await scenario("logical backup restores durable active composition",()=>{const sourceSnapshot=publication(box),sourceCampaign=campaign(box),dump=command(box.tools.pg_dump,["-h",box.socket,"-p",String(box.port),"-U","postgres","-d",DB]).stdout;psql(box,"CREATE DATABASE campaign_starter_restore;","postgres");psql(box,dump,"campaign_starter_restore");const restoredSnapshot=publication(box,"campaign_starter_restore"),restoredCampaign=campaign(box,HOST_A,"campaign_starter_restore");assert.deepEqual(restoredSnapshot,sourceSnapshot);assert.equal(restoredSnapshot.recordId,COMPOSITION);assert.equal(restoredSnapshot.recordVersion,5);assert.equal(restoredSnapshot.config.sections[0].slides[0].heading,concurrentWinnerHeading);assert.equal(restoredCampaign.payload.presentation.sections.find((section)=>section.kind==="hero").slides[0].heading,concurrentWinnerHeading);assert.deepEqual(restoredCampaign,sourceCampaign);});
 apply(box,DOWN);
 await scenario("rollback restores migration 073 behavior",()=>{assert.equal(psql(box,"SELECT pg_catalog.to_regprocedure('saas.public_campaign_home(uuid,text,timestamp with time zone)') IS NULL;").stdout.trim(),"t");assert.equal(psql(box,"SELECT pg_catalog.to_regprocedure('saas.public_storefront_related_products(uuid,text,timestamp with time zone,text,integer)') IS NULL;").stdout.trim(),"t");assert.equal(psql(box,"SELECT pg_catalog.to_regprocedure('saas.public_get_product_by_slug(uuid,text,timestamp with time zone,text)') IS NOT NULL;").stdout.trim(),"t");assert.equal(psql(box,"SELECT saas.merchant_admin_config_valid('starter_theme_composition','{}'::jsonb);").stdout.trim(),"f");assert.equal(psql(box,"SELECT count(*) FROM saas.merchant_admin_records WHERE record_kind='starter_theme_composition';").stdout.trim(),"0");});
 apply(box,UP);apply(box,ASSERTIONS);
 await scenario("reapply restores the exact migration 074 API and cleanup precondition",()=>{assert.equal(psql(box,"SELECT pg_catalog.to_regprocedure('saas.public_campaign_home(uuid,text,timestamp with time zone)') IS NOT NULL;").stdout.trim(),"t");assert.equal(psql(box,`SELECT saas.campaign_starter_composition_valid('${JSON.stringify(composition({navigation:{rootCategoryIds:[]},sections:[{kind:"product_row",enabled:true,heading:"Yeni",source:"latest",limit:8}]}))}'::jsonb);`).stdout.trim(),"t");assert.equal(psql(box,"SELECT count(*) FROM pg_catalog.pg_stat_activity WHERE datname=current_database() AND pid<>pg_catalog.pg_backend_pid();").stdout.trim(),"0");});
 assert.equal(completed,TOTAL);console.log(`${TOTAL}/${TOTAL} PASS`);
 }finally{const root=box?.root,pid=box?.pid;stop(box);assert.equal(root?existsSync(root):false,false);if(pid){try{process.kill(pid,0);assert.fail("postgres process still alive");}catch(error){if(error?.code!=="ESRCH")throw error;}}console.log("DISPOSABLE_POSTGRES_CLEANUP PASS");}}
await main();
