import type { DashboardStoreSummary, OperationsSummary } from "@/lib/control-plane";
import type { OwnerAuthContext } from "@/lib/owner-auth";
import { getMissingOwnerSupabaseEnvNames } from "@/lib/owner-supabase-shared";
import { isOwnerPreviewMode } from "@/lib/preview-mode";

const PREVIEW_TIMESTAMP = "2026-06-04T18:30:00.000Z";

function createSubscription(status: "active" | "expiring" | "unconfigured") {
  if (status === "unconfigured") {
    return {
      isConfigured: false,
      startDate: null,
      durationMonths: null,
      endDate: null,
      totalDays: null,
      elapsedDays: null,
      daysRemaining: null,
      progressPercent: null,
      cadenceLabel: "Paket tanımlanmadı",
      countdownLabel: "Takip başlatılmadı",
      status,
    } as const;
  }

  return {
    isConfigured: true,
    startDate: "2026-01-01",
    durationMonths: 12,
    endDate: "2026-12-31",
    totalDays: 365,
    elapsedDays: status === "expiring" ? 340 : 155,
    daysRemaining: status === "expiring" ? 25 : 210,
    progressPercent: status === "expiring" ? 93 : 42,
    cadenceLabel: "Yıllık paket",
    countdownLabel: status === "expiring" ? "25 gün kaldı" : "210 gün kaldı",
    status,
  } as const;
}

function createDomainMigration() {
  return {
    state: "idle",
    previousStorefrontDomain: null,
    previousAdminDomain: null,
    storefrontDomain: null,
    adminDomain: null,
    startedAt: null,
    completedAt: null,
    lastError: null,
    authoritySyncMessage: null,
    adminDeploymentStatus: null,
    storefrontDeploymentStatus: null,
    rollbackState: "not_needed",
    rollbackCompletedAt: null,
    rollbackError: null,
    hasHistory: false,
  } as const;
}

function createSteps(
  entries: Array<{
    key:
      | "owner_supabase_auth"
      | "auth_setup"
      | "analytics_setup"
      | "payment_setup"
      | "admin_deploy"
      | "storefront_deploy";
    label: string;
    status: "completed" | "running" | "pending" | "failed" | "blocked";
    message?: string | null;
    blocking?: boolean;
    updatedAt?: string | null;
  }>,
) {
  return entries.map((entry) => ({
    key: entry.key,
    label: entry.label,
    status: entry.status,
    blocking: entry.blocking ?? false,
    message: entry.message ?? null,
    updatedAt: entry.updatedAt ?? PREVIEW_TIMESTAMP,
  }));
}

export function hasOwnerPreviewDataFallback(): boolean {
  return (
    isOwnerPreviewMode() &&
    getMissingOwnerSupabaseEnvNames({ requireServiceRole: true }).length > 0
  );
}

export function getPreviewOwnerAuthContext(): OwnerAuthContext {
  return {
    user: {
      id: "preview-owner-super-admin",
      email: "preview@celebix.co",
      app_metadata: {},
      user_metadata: { full_name: "Preview Owner" },
      aud: "authenticated",
      created_at: PREVIEW_TIMESTAMP,
    } as OwnerAuthContext["user"],
    profile: {
      id: "preview-owner-super-admin",
      email: "preview@celebix.co",
      full_name: "Preview Owner",
      role: "super_admin",
      is_active: true,
    },
  };
}

export function getPreviewDashboardStores(): DashboardStoreSummary[] {
  return [
    {
      id: "preview-derycraft",
      slug: "derycraft",
      name: "DeryCraft",
      status: "active",
      databaseMode: "light_postgres",
      themeKey: "derycraft",
      themeLabel: "DeryCraft",
      storefrontDomain: "derycraft.com.tr",
      adminDomain: "admin.derycraft.com.tr",
      storefrontAppDir: "apps/derycraft-storefront",
      storefrontStatus: "active",
      productCount: 248,
      orderCount: 1842,
      customerCount: 1296,
      pendingOrderCount: 6,
      totalRevenue: 486520,
      averageOrderValue: 264,
      lastSyncedAt: "2026-06-04T18:20:00.000Z",
      supabaseDashboardUrl: null,
      commissionRate: null,
      totalAffiliateRate: 8,
      affiliateCount: 2,
      storeAdminCount: 4,
      management: {
        clientCompanyName: "DeryCraft Deri Atölyesi",
        clientContactName: "Ece Demir",
        clientContactEmail: "ops@derycraft.com.tr",
        clientContactPhone: "+90 212 000 00 00",
        internalOwner: "Platform Ops",
        lifecycleStage: "live",
        priority: "high",
        nextAction: "Google ve Apple connector hazır olduğunda auth geçişini gözden geçir.",
        launchTarget: "2026-06",
        ownerNotes: null,
        billingStatus: "healthy",
        subscription: createSubscription("active"),
      },
      setup: {
        auth: {
          provider: "logto",
          status: "configured",
          mode: "logto_ready_placeholder",
        },
        analytics: {
          provider: "umami",
          status: "configured",
          mode: "umami_ready_placeholder",
          websiteId: "preview-derycraft",
        },
        payments: {
          status: "configured",
          defaultProvider: "bank_transfer",
        },
      },
      health: {
        supabaseReady: true,
        r2Ready: true,
        storefrontReady: true,
        storefrontRuntimeConsistent: true,
        storefrontDataReady: true,
        homepageOk: true,
        categoriesOk: true,
        productsOk: true,
        starterSeedReady: true,
        settingsOk: true,
        blogPostsOk: true,
        storefrontDataMessage: null,
        adminCoverage: true,
        secretCoverage: true,
        secretAuthorityReady: true,
        legacyAuthConfigured: false,
        adminDeploymentReady: true,
        adminRuntimeConsistent: true,
        adminRuntimeMessage: null,
        adminRuntimeUrl: "https://admin.derycraft.com.tr",
        metricsFreshnessMinutes: 4,
        score: 96,
        label: "hazir",
      },
      consistency: {
        blocking: false,
        issueCount: 0,
        blockingIssueCount: 0,
        issues: [],
        checkedAt: "2026-06-04T18:18:00.000Z",
      },
      provisioning: {
        state: "ready",
        lastError: null,
        lastRunAt: "2026-06-04T17:45:00.000Z",
        failedStepCount: 0,
        blockingStepCount: 0,
        pendingStepCount: 0,
        steps: createSteps([
          { key: "admin_deploy", label: "Admin deployment", status: "completed" },
          { key: "storefront_deploy", label: "Storefront deployment", status: "completed" },
          { key: "auth_setup", label: "Auth setup", status: "completed" },
        ]),
      },
      domainMigration: createDomainMigration(),
    },
    {
      id: "preview-atelier-nova",
      slug: "atelier-nova",
      name: "Atelier Nova",
      status: "active",
      databaseMode: "light_postgres",
      themeKey: "atelier-nova",
      themeLabel: "Atelier Nova",
      storefrontDomain: "ateliernova.co",
      adminDomain: "admin.ateliernova.co",
      storefrontAppDir: "apps/atelier-nova-storefront",
      storefrontStatus: "scaffolded",
      productCount: 96,
      orderCount: 412,
      customerCount: 301,
      pendingOrderCount: 12,
      totalRevenue: 132880,
      averageOrderValue: 322,
      lastSyncedAt: "2026-06-04T17:55:00.000Z",
      supabaseDashboardUrl: null,
      commissionRate: null,
      totalAffiliateRate: 0,
      affiliateCount: 0,
      storeAdminCount: 2,
      management: {
        clientCompanyName: "Atelier Nova",
        clientContactName: "Merve Kaya",
        clientContactEmail: "hello@ateliernova.co",
        clientContactPhone: "+90 850 000 00 01",
        internalOwner: "Launch Team",
        lifecycleStage: "launch_ready",
        priority: "normal",
        nextAction: "Analytics website id tamamlanınca yayına alma kontrolü yapılacak.",
        launchTarget: "2026-06",
        ownerNotes: null,
        billingStatus: "healthy",
        subscription: createSubscription("active"),
      },
      setup: {
        auth: {
          provider: "logto",
          status: "configured",
          mode: "logto_ready_placeholder",
        },
        analytics: {
          provider: "umami",
          status: "pending_analytics_setup",
          mode: "umami_ready_placeholder",
          requiredAction: "Website id tanımlanmalı",
          blocking: true,
        },
        payments: {
          status: "configured",
          defaultProvider: "bank_transfer",
        },
      },
      health: {
        supabaseReady: true,
        r2Ready: true,
        storefrontReady: false,
        storefrontRuntimeConsistent: false,
        storefrontDataReady: true,
        homepageOk: true,
        categoriesOk: true,
        productsOk: true,
        starterSeedReady: true,
        settingsOk: true,
        blogPostsOk: false,
        storefrontDataMessage: "Storefront build tamamlandı, canlı runtime henüz doğrulanmadı.",
        adminCoverage: true,
        secretCoverage: true,
        secretAuthorityReady: true,
        legacyAuthConfigured: false,
        adminDeploymentReady: true,
        adminRuntimeConsistent: true,
        adminRuntimeMessage: null,
        adminRuntimeUrl: "https://admin.ateliernova.co",
        metricsFreshnessMinutes: 11,
        score: 82,
        label: "operasyonel",
      },
      consistency: {
        blocking: false,
        issueCount: 1,
        blockingIssueCount: 0,
        issues: [
          {
            code: "admin_runtime_drift",
            severity: "warning",
            source: "admin_runtime",
            message: "Storefront runtime son build sonrası bir kez daha doğrulanmalı.",
          },
        ],
        checkedAt: "2026-06-04T17:54:00.000Z",
      },
      provisioning: {
        state: "pending_analytics",
        lastError: null,
        lastRunAt: "2026-06-04T17:40:00.000Z",
        failedStepCount: 0,
        blockingStepCount: 1,
        pendingStepCount: 1,
        steps: createSteps([
          { key: "admin_deploy", label: "Admin deployment", status: "completed" },
          { key: "storefront_deploy", label: "Storefront deployment", status: "completed" },
          {
            key: "analytics_setup",
            label: "Analytics setup",
            status: "blocked",
            blocking: true,
            message: "Website id bekleniyor.",
          },
        ]),
      },
      domainMigration: createDomainMigration(),
    },
    {
      id: "preview-luna-home",
      slug: "luna-home",
      name: "Luna Home",
      status: "active",
      databaseMode: "full_supabase",
      themeKey: "luna-home",
      themeLabel: "Luna Home",
      storefrontDomain: "lunahome.com",
      adminDomain: "admin.lunahome.com",
      storefrontAppDir: "apps/luna-home-storefront",
      storefrontStatus: "active",
      productCount: 182,
      orderCount: 967,
      customerCount: 704,
      pendingOrderCount: 23,
      totalRevenue: 278940,
      averageOrderValue: 288,
      lastSyncedAt: "2026-06-04T16:52:00.000Z",
      supabaseDashboardUrl: null,
      commissionRate: 12,
      totalAffiliateRate: 12,
      affiliateCount: 1,
      storeAdminCount: 3,
      management: {
        clientCompanyName: "Luna Home",
        clientContactName: "Selin Acar",
        clientContactEmail: "finance@lunahome.com",
        clientContactPhone: "+90 850 000 00 02",
        internalOwner: "Migration Desk",
        lifecycleStage: "growth",
        priority: "high",
        nextAction: "Legacy auth ve ödeme istisnası için geçiş planı hazırlanmalı.",
        launchTarget: "2026-07",
        ownerNotes: null,
        billingStatus: "follow_up",
        subscription: createSubscription("expiring"),
      },
      setup: {
        auth: {
          provider: "supabase",
          status: "configured",
          mode: "legacy_supabase_auth",
        },
        analytics: {
          provider: "umami",
          status: "configured",
          mode: "umami_ready_placeholder",
          websiteId: "preview-luna-home",
        },
        payments: {
          status: "pending_payment_setup",
          defaultProvider: "bank_transfer",
          requiredAction: "Ödeme doğrulama akışı bekleniyor",
          blocking: true,
        },
      },
      health: {
        supabaseReady: true,
        r2Ready: true,
        storefrontReady: true,
        storefrontRuntimeConsistent: true,
        storefrontDataReady: true,
        homepageOk: true,
        categoriesOk: true,
        productsOk: true,
        starterSeedReady: true,
        settingsOk: true,
        blogPostsOk: true,
        storefrontDataMessage: null,
        adminCoverage: true,
        secretCoverage: true,
        secretAuthorityReady: false,
        legacyAuthConfigured: true,
        adminDeploymentReady: true,
        adminRuntimeConsistent: false,
        adminRuntimeMessage: "Admin runtime auth provider etiketi eski authority ile eşleşmiyor.",
        adminRuntimeUrl: "https://admin.lunahome.com",
        metricsFreshnessMinutes: 26,
        score: 69,
        label: "kurulum",
      },
      consistency: {
        blocking: false,
        issueCount: 1,
        blockingIssueCount: 0,
        issues: [
          {
            code: "admin_runtime_drift",
            severity: "warning",
            source: "admin_runtime",
            message: "Legacy auth authority yüzünden admin runtime yeniden gözden geçirilmeli.",
          },
        ],
        checkedAt: "2026-06-04T16:45:00.000Z",
      },
      provisioning: {
        state: "pending_payment",
        lastError: null,
        lastRunAt: "2026-06-04T16:21:00.000Z",
        failedStepCount: 0,
        blockingStepCount: 1,
        pendingStepCount: 1,
        steps: createSteps([
          { key: "storefront_deploy", label: "Storefront deployment", status: "completed" },
          { key: "auth_setup", label: "Auth setup", status: "completed" },
          {
            key: "payment_setup",
            label: "Payment setup",
            status: "blocked",
            blocking: true,
            message: "Ödeme doğrulama bekleniyor.",
          },
        ]),
      },
      domainMigration: createDomainMigration(),
    },
    {
      id: "preview-north-studio",
      slug: "north-studio",
      name: "North Studio",
      status: "paused",
      databaseMode: "light_postgres",
      themeKey: "north-studio",
      themeLabel: "North Studio",
      storefrontDomain: "northstudio.shop",
      adminDomain: "admin.northstudio.shop",
      storefrontAppDir: "apps/north-studio-storefront",
      storefrontStatus: "not_started",
      productCount: 24,
      orderCount: 58,
      customerCount: 41,
      pendingOrderCount: 0,
      totalRevenue: 18420,
      averageOrderValue: 317,
      lastSyncedAt: "2026-06-04T15:12:00.000Z",
      supabaseDashboardUrl: null,
      commissionRate: null,
      totalAffiliateRate: 0,
      affiliateCount: 0,
      storeAdminCount: 1,
      management: {
        clientCompanyName: "North Studio",
        clientContactName: "Bora Çetin",
        clientContactEmail: "ops@northstudio.shop",
        clientContactPhone: "+90 850 000 00 03",
        internalOwner: "Recovery Squad",
        lifecycleStage: "building",
        priority: "critical",
        nextAction: "Admin runtime ve auth authority onarımı olmadan yayına alınmayacak.",
        launchTarget: "2026-07",
        ownerNotes: null,
        billingStatus: "hold",
        subscription: createSubscription("unconfigured"),
      },
      setup: {
        auth: {
          provider: "logto",
          status: "pending_auth_setup",
          mode: "logto_ready_placeholder",
          requiredAction: "Connector ve tenant bağlama bekleniyor",
          blocking: true,
        },
        analytics: {
          provider: "umami",
          status: "pending_analytics_setup",
          mode: "umami_ready_placeholder",
          requiredAction: "Website id oluşturulmalı",
          blocking: true,
        },
        payments: {
          status: "pending_payment_setup",
          defaultProvider: "none",
          requiredAction: "Ödeme yöntemi belirlenmeli",
          blocking: true,
        },
      },
      health: {
        supabaseReady: true,
        r2Ready: false,
        storefrontReady: false,
        storefrontRuntimeConsistent: false,
        storefrontDataReady: false,
        homepageOk: false,
        categoriesOk: false,
        productsOk: false,
        starterSeedReady: false,
        settingsOk: false,
        blogPostsOk: false,
        storefrontDataMessage: "Storefront runtime henüz doğrulanmadı.",
        adminCoverage: false,
        secretCoverage: false,
        secretAuthorityReady: false,
        legacyAuthConfigured: false,
        adminDeploymentReady: false,
        adminRuntimeConsistent: false,
        adminRuntimeMessage: "Admin domain authority ile deploy kaydı eşleşmiyor.",
        adminRuntimeUrl: null,
        metricsFreshnessMinutes: 92,
        score: 34,
        label: "kritik",
      },
      consistency: {
        blocking: true,
        issueCount: 2,
        blockingIssueCount: 2,
        issues: [
          {
            code: "admin_env_missing",
            severity: "blocking",
            source: "admin_env",
            message: "Admin deploy authority eksik olduğu için runtime doğrulaması yapılamıyor.",
          },
          {
            code: "owner_domain_mismatch",
            severity: "blocking",
            source: "owner_store",
            message: "Owner kaydı ile beklenen admin domain farklı görünüyor.",
          },
        ],
        checkedAt: "2026-06-04T15:10:00.000Z",
      },
      provisioning: {
        state: "failed",
        lastError: "Auth authority ve admin deploy kaydı birlikte onarılmalı.",
        lastRunAt: "2026-06-04T14:50:00.000Z",
        failedStepCount: 2,
        blockingStepCount: 2,
        pendingStepCount: 3,
        steps: createSteps([
          {
            key: "admin_deploy",
            label: "Admin deployment",
            status: "failed",
            blocking: true,
            message: "Admin deploy authority bulunamadı.",
          },
          {
            key: "auth_setup",
            label: "Auth setup",
            status: "failed",
            blocking: true,
            message: "Auth connector bağlanamadı.",
          },
          {
            key: "analytics_setup",
            label: "Analytics setup",
            status: "pending",
            message: "Auth onarımı sonrası tekrar denenecek.",
          },
        ]),
      },
      domainMigration: createDomainMigration(),
    },
  ];
}

export function getPreviewOperationsSummary(
  stores: DashboardStoreSummary[] = getPreviewDashboardStores(),
): OperationsSummary {
  return {
    totals: {
      readyStores: stores.filter((store) => store.health.label === "hazir").length,
      missingSupabase: stores.filter((store) => !store.health.supabaseReady).length,
      missingR2: stores.filter((store) => !store.health.r2Ready).length,
      missingAdmins: stores.filter((store) => !store.health.adminCoverage).length,
      secretDrift: stores.filter((store) => !store.health.secretAuthorityReady).length,
      adminRuntimeIssues: stores.filter(
        (store) => !store.health.adminRuntimeConsistent || !store.health.adminDeploymentReady,
      ).length,
      consistencyBlockingStores: stores.filter((store) => store.consistency.blocking).length,
      pendingStorefronts: stores.filter((store) => store.storefrontStatus !== "active").length,
      orphanedCleanupRuns: 1,
    },
    rows: stores.map((store) => ({
      id: store.id,
      slug: store.slug,
      name: store.name,
      status: store.status,
      storefrontStatus: store.storefrontStatus,
      storefrontDomain: store.storefrontDomain,
      adminDomain: store.adminDomain,
      health: store.health,
      consistency: store.consistency,
      pendingOrderCount: store.pendingOrderCount,
      lastSyncedAt: store.lastSyncedAt,
      supabaseProjectRef: null,
      r2BucketName: store.health.r2Ready ? `${store.slug}-assets` : null,
      provisioning: store.provisioning,
    })),
    cleanupRuns: [
      {
        id: "cleanup-preview-north-studio",
        slug: "north-studio",
        storeName: "North Studio",
        status: "orphaned",
        authorityDeletedAt: null,
        resolvedAt: null,
        createdAt: "2026-06-04T14:12:00.000Z",
        updatedAt: "2026-06-04T15:01:00.000Z",
        orphanedTargetCount: 2,
        targets: [
          { type: "deployment", identifier: "north-studio-admin", status: "failed" },
          { type: "dns", identifier: "admin.northstudio.shop", status: "missing" },
        ],
      },
    ],
    recentActivity: [
      {
        id: "preview-log-1",
        action: "repair_store_deployment_authorities",
        targetType: "store",
        targetId: "north-studio",
        targetLabel: "North Studio",
        actorName: "Preview Owner",
        createdAt: "2026-06-04T17:58:00.000Z",
        details: {},
      },
      {
        id: "preview-log-2",
        action: "store_provisioning_enqueued",
        targetType: "store",
        targetId: "atelier-nova",
        targetLabel: "Atelier Nova",
        actorName: "Launch Team",
        createdAt: "2026-06-04T17:22:00.000Z",
        details: {},
      },
      {
        id: "preview-log-3",
        action: "store_payment_setup_pending",
        targetType: "store",
        targetId: "luna-home",
        targetLabel: "Luna Home",
        actorName: "Migration Desk",
        createdAt: "2026-06-04T16:33:00.000Z",
        details: {},
      },
      {
        id: "preview-log-4",
        action: "store_runtime_verified",
        targetType: "store",
        targetId: "derycraft",
        targetLabel: "DeryCraft",
        actorName: "Platform Ops",
        createdAt: "2026-06-04T15:48:00.000Z",
        details: {},
      },
    ],
  };
}
