import assert from 'node:assert/strict';
import test from 'node:test';
import { parseAccountingIntent } from './validation.ts';
const id='11111111-1111-4111-8111-111111111111';
const collect={customerId:id,orderId:null,amountCents:200000,currency:'TRY',paymentMethod:'cash',accountId:null,expectedVersion:2,note:null};
test('later customer receipt preserves exact integer cents and aggregate version',()=>{assert.deepEqual(parseAccountingIntent('collect',collect),collect);});
test('finance intent rejects extra authority fields, decimals, missing payment and unsafe integers',()=>{for(const value of [{...collect,storeId:id},{...collect,amountCents:2.3},{...collect,amountCents:Number.MAX_SAFE_INTEGER+1},{...collect,paymentMethod:null},{...collect,expectedVersion:0}])assert.throws(()=>parseAccountingIntent('collect',value));});
test('opening debt validates actual calendar dates and has no revenue or stock fields',()=>{const value={customerId:id,amountCents:10000,currency:'TRY',occurredOn:'2026-09-30',note:'Opening debt',expectedVersion:0};assert.deepEqual(parseAccountingIntent('openingDebt',value),value);assert.throws(()=>parseAccountingIntent('openingDebt',{...value,occurredOn:'2026-02-30'}));});
test('settlement rejects commission above gross and equal source target accounts',()=>{const value={fromAccountId:id,toAccountId:'22222222-2222-4222-8222-222222222222',amountCents:10000,commissionCents:250,expectedVersion:1,toExpectedVersion:1,note:'Settlement'};assert.deepEqual(parseAccountingIntent('settleCard',value),value);assert.throws(()=>parseAccountingIntent('settleCard',{...value,commissionCents:10001}));assert.throws(()=>parseAccountingIntent('settleCard',{...value,toAccountId:id}));});

test('strict finance responses reject string money, unknown status and unsafe versions',async()=>{const{parseAccountingOrderFinance,parseAccountingReceivable}=await import('./response.ts');const finance={status:'partial',collectedCents:500000,dueCents:600000,refundDueCents:0,version:1,receipts:[]};assert.deepEqual(parseAccountingOrderFinance(finance),finance);for(const value of [{...finance,collectedCents:'500000'},{...finance,status:'complete'},{...finance,version:0},{...finance,dueCents:Number.MAX_SAFE_INTEGER+1},{...finance,status:'paid'}])assert.throws(()=>parseAccountingOrderFinance(value));assert.throws(()=>parseAccountingReceivable({id}));});

test('customer account accepts maximum CRM names joined with one space',async()=>{const{parseAccountingCustomerAccount}=await import('./response.ts');const name='A'.repeat(100)+' '+'B'.repeat(100);const account={customerId:id,customerName:name,customerPhone:null,customerArchived:false,currency:'TRY',version:0,dueCents:0,refundDueCents:0,receivables:[],events:[]};assert.equal(parseAccountingCustomerAccount(account).customerName.length,201);assert.throws(()=>parseAccountingCustomerAccount({...account,customerName:name+'C'}));});
