import { accountingExact,accountingInteger,accountingUuid } from './validation.ts';
import type { AccountingAccount,AccountingAccounts,AccountingCollectionAccounts,AccountingCollectionPreview,AccountingCurrencySummary,AccountingCustomerAccount,AccountingEvent,AccountingExpenses,AccountingMutationResult,AccountingOrderFinance,AccountingOverview,AccountingReceivable,AccountingReceivables,AccountingReceipt,AccountingAllocation } from './types.ts';
function fail():never {throw new TypeError('invalid_accounting_response');}
const str=(v:unknown,max=2000):string=>{if(typeof v!=='string'||v.length<1||v.length>max||/[\u0000-\u001f\u007f]/.test(v))fail();return v;};
const nullable=<T>(v:unknown,parse:(v:unknown)=>T):T|null=>v===null?null:parse(v);
const bool=(v:unknown):boolean=>{if(typeof v!=='boolean')fail();return v;};
const money=(v:unknown)=>accountingInteger(v,0);
const signed=(v:unknown):number=>{if(!Number.isSafeInteger(v))fail();return v as number;};
const timestamp=(v:unknown):string=>{const s=str(v,24);if(s.length!==24||!Number.isFinite(Date.parse(s))||new Date(s).toISOString()!==s)fail();return s;};
const date=(v:unknown):string=>{const s=str(v,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(Date.parse(s+'T00:00:00.000Z'))||new Date(s+'T00:00:00.000Z').toISOString().slice(0,10)!==s)fail();return s;};
const currency=(v:unknown):string=>{const s=str(v,3);if(!/^[A-Z]{3}$/.test(s))fail();return s;};
const enumeration=<const T extends string>(v:unknown,allowed:readonly T[]):T=>{if(typeof v!=='string'||!allowed.includes(v as T))fail();return v as T;};
const list=<T>(v:unknown,parse:(v:unknown)=>T):readonly T[]=>{if(!Array.isArray(v)||v.length>100000)fail();return Object.freeze(v.map(parse));};
function jsonRecord(v:unknown):Readonly<Record<string,unknown>> {if(typeof v!=='object'||v===null||Array.isArray(v)||![Object.prototype,null].includes(Object.getPrototypeOf(v)))fail();const visit=(x:unknown,depth:number):unknown=>{if(depth>16)fail();if(x===null||typeof x==='boolean'||typeof x==='string')return x;if(typeof x==='number')return signed(x);if(Array.isArray(x))return Object.freeze(x.map(y=>visit(y,depth+1)));if(typeof x==='object'&&x!==null){const out:Record<string,unknown>={};for(const[k,d]of Object.entries(Object.getOwnPropertyDescriptors(x))){if(!('value'in d)||!d.enumerable)fail();out[k]=visit(d.value,depth+1);}return Object.freeze(out);}fail();};return visit(v,0) as Readonly<Record<string,unknown>>;}
export function parseAccountingAllocation(v:unknown):AccountingAllocation{const b=accountingExact(v,['receivableId','orderId','amountCents']);return Object.freeze({receivableId:accountingUuid(b.receivableId),orderId:nullable(b.orderId,accountingUuid),amountCents:signed(b.amountCents)});}
export function parseAccountingReceipt(v:unknown):AccountingReceipt{const b=accountingExact(v,['id','amountCents','paymentMethod','receivedAt','actorMembershipId','reversed']);return Object.freeze({id:accountingUuid(b.id),amountCents:accountingInteger(b.amountCents,1),paymentMethod:enumeration(b.paymentMethod,['cash','card','bank_transfer']),receivedAt:timestamp(b.receivedAt),actorMembershipId:accountingUuid(b.actorMembershipId),reversed:bool(b.reversed)});}
export function parseAccountingOrderFinance(v:unknown):AccountingOrderFinance{const b=accountingExact(v,['status','collectedCents','dueCents','refundDueCents','version','receipts']);const result={status:enumeration(b.status,['unpaid','partial','paid']),collectedCents:money(b.collectedCents),dueCents:money(b.dueCents),refundDueCents:money(b.refundDueCents),version:accountingInteger(b.version,1),receipts:list(b.receipts,parseAccountingReceipt)};if(result.status==='paid'&&result.dueCents!==0||result.status==='unpaid'&&(result.collectedCents!==0||result.dueCents===0)||result.status==='partial'&&(result.collectedCents===0||result.dueCents===0))fail();return Object.freeze(result);}
export function parseAccountingReceivable(v:unknown):AccountingReceivable{const b=accountingExact(v,['id','customerId','customerName','customerPhone','customerArchived','orderId','orderNumber','channel','currency','saleCents','collectedCents','returnCents','refundedCents','dueCents','refundDueCents','occurredAt','dueDate','version']);const result={id:accountingUuid(b.id),customerId:nullable(b.customerId,accountingUuid),customerName:str(b.customerName,201),customerPhone:nullable(b.customerPhone,x=>str(x,30)),customerArchived:bool(b.customerArchived),orderId:nullable(b.orderId,accountingUuid),orderNumber:nullable(b.orderNumber,x=>str(x,100)),channel:nullable(b.channel,x=>enumeration(x,['WEB','POS'])),currency:currency(b.currency),saleCents:money(b.saleCents),collectedCents:money(b.collectedCents),returnCents:money(b.returnCents),refundedCents:money(b.refundedCents),dueCents:money(b.dueCents),refundDueCents:money(b.refundDueCents),occurredAt:timestamp(b.occurredAt),dueDate:nullable(b.dueDate,date),version:accountingInteger(b.version,1)};if(result.returnCents>result.saleCents||result.dueCents!==Math.max(result.saleCents-result.returnCents-result.collectedCents,0)||result.refundDueCents!==Math.max(result.collectedCents-result.saleCents+result.returnCents-result.refundedCents,0))fail();return Object.freeze(result);}
export function parseAccountingEvent(v:unknown):AccountingEvent{const b=accountingExact(v,['id','kind','currency','amountCents','accountId','customerId','orderId','channel','paymentMethod','note','category','documentNumber','actorMembershipId','occurredAt','createdAt','reversesEventId','reversed','allocations','metadata']);return Object.freeze({id:accountingUuid(b.id),kind:enumeration(b.kind,['sale','collection','opening_debt','account_opening','expense','transfer','card_settlement','return_credit','refund','reversal']),currency:currency(b.currency),amountCents:money(b.amountCents),accountId:nullable(b.accountId,accountingUuid),customerId:nullable(b.customerId,accountingUuid),orderId:nullable(b.orderId,accountingUuid),channel:nullable(b.channel,x=>enumeration(x,['WEB','POS'])),paymentMethod:nullable(b.paymentMethod,x=>enumeration(x,['cash','card','bank_transfer'])),note:nullable(b.note,str),category:nullable(b.category,x=>str(x,100)),documentNumber:nullable(b.documentNumber,x=>str(x,100)),actorMembershipId:accountingUuid(b.actorMembershipId),occurredAt:timestamp(b.occurredAt),createdAt:timestamp(b.createdAt),reversesEventId:nullable(b.reversesEventId,accountingUuid),reversed:bool(b.reversed),allocations:list(b.allocations,parseAccountingAllocation),metadata:jsonRecord(b.metadata)});}
export function parseAccountingAccount(v:unknown):AccountingAccount{const b=accountingExact(v,['id','name','type','currency','balanceCents','version','createdAt']);return Object.freeze({id:accountingUuid(b.id),name:str(b.name,200),type:enumeration(b.type,['cash','bank','card']),currency:currency(b.currency),balanceCents:money(b.balanceCents),version:accountingInteger(b.version,1),createdAt:timestamp(b.createdAt)});}
export function parseAccountingCustomerAccount(v:unknown):AccountingCustomerAccount{const b=accountingExact(v,['customerId','customerName','customerPhone','customerArchived','currency','version','dueCents','refundDueCents','receivables','events']);const result={customerId:accountingUuid(b.customerId),customerName:str(b.customerName,201),customerPhone:nullable(b.customerPhone,x=>str(x,30)),customerArchived:bool(b.customerArchived),currency:currency(b.currency),version:money(b.version),dueCents:money(b.dueCents),refundDueCents:money(b.refundDueCents),receivables:list(b.receivables,parseAccountingReceivable),events:list(b.events,parseAccountingEvent)};if(result.receivables.some(r=>r.customerId!==result.customerId||r.currency!==result.currency)||result.events.some(r=>r.customerId!==result.customerId||r.currency!==result.currency))fail();return Object.freeze(result);}
export function parseAccountingMutationResult(v:unknown):AccountingMutationResult{const b=accountingExact(v,['operationId','replayed','event','account','customerAccount','finance']);return Object.freeze({operationId:accountingUuid(b.operationId),replayed:bool(b.replayed),event:nullable(b.event,parseAccountingEvent),account:nullable(b.account,parseAccountingAccount),customerAccount:nullable(b.customerAccount,parseAccountingCustomerAccount),finance:nullable(b.finance,parseAccountingOrderFinance)});}
export function parseAccountingCurrencySummary(v:unknown):AccountingCurrencySummary{const b=accountingExact(v,['currency','salesCents','collectionsCents','returnCents','refundsCents','expensesCents','commissionCents','dueCents','overdueCents','refundDueCents','recordedWebPaymentsCents']);return Object.freeze({currency:currency(b.currency),salesCents:signed(b.salesCents),collectionsCents:signed(b.collectionsCents),returnCents:signed(b.returnCents),refundsCents:signed(b.refundsCents),expensesCents:signed(b.expensesCents),commissionCents:signed(b.commissionCents),dueCents:money(b.dueCents),overdueCents:money(b.overdueCents),refundDueCents:money(b.refundDueCents),recordedWebPaymentsCents:money(b.recordedWebPaymentsCents)});}
export function parseAccountingOverview(v:unknown):AccountingOverview{const b=accountingExact(v,['currencies','accounts','recentEvents']);return Object.freeze({currencies:list(b.currencies,parseAccountingCurrencySummary),accounts:list(b.accounts,parseAccountingAccount),recentEvents:list(b.recentEvents,parseAccountingEvent)});}
export function parseAccountingReceivables(v:unknown):AccountingReceivables{const b=accountingExact(v,['receivables']);return Object.freeze({receivables:list(b.receivables,parseAccountingReceivable)});}
export function parseAccountingAccounts(v:unknown):AccountingAccounts{const b=accountingExact(v,['accounts','events']);return Object.freeze({accounts:list(b.accounts,parseAccountingAccount),events:list(b.events,parseAccountingEvent)});}
export function parseAccountingCollectionAccounts(v:unknown):AccountingCollectionAccounts{const b=accountingExact(v,['accounts']);return Object.freeze({accounts:list(b.accounts,v=>{const a=accountingExact(v,['id','name','type','currency']);return Object.freeze({id:accountingUuid(a.id),name:str(a.name,200),type:enumeration(a.type,['cash','bank','card']),currency:currency(a.currency)});})});}
export function parseAccountingExpenses(v:unknown):AccountingExpenses{const b=accountingExact(v,['expenses']);return Object.freeze({expenses:list(b.expenses,parseAccountingEvent)});}
export function parseAccountingCollectionPreview(v:unknown):AccountingCollectionPreview{const b=accountingExact(v,['customerId','currency','version','dueCents','allocations']);return Object.freeze({customerId:accountingUuid(b.customerId),currency:currency(b.currency),version:money(b.version),dueCents:money(b.dueCents),allocations:list(b.allocations,parseAccountingAllocation)});}
