export const ACCOUNTING_MUTATIONS = ['collect','openingDebt','saveAccount','openBalance','expense','transfer','settleCard','reverse','returnCredit','refund'] as const;
export type AccountingMutation = typeof ACCOUNTING_MUTATIONS[number];
export type AccountingPaymentMethod = 'cash'|'card'|'bank_transfer';
export type AccountingChannel = 'WEB'|'POS';
export interface AccountingFilters { readonly dateFrom?:string; readonly dateTo?:string; readonly channel?:AccountingChannel; readonly salesChannel?:'manual'|'social'; readonly currency?:string; readonly query?:string; readonly customerId?:string; readonly orderId?:string; }
export interface AccountingReceipt { readonly id:string; readonly amountCents:number; readonly paymentMethod:AccountingPaymentMethod; readonly receivedAt:string; readonly actorMembershipId:string; readonly reversed:boolean; }
export interface AccountingOrderFinance { readonly status:'unpaid'|'partial'|'paid'; readonly collectedCents:number; readonly dueCents:number; readonly refundDueCents:number; readonly version:number; readonly receipts:readonly AccountingReceipt[]; }
export interface AccountingAllocation { readonly receivableId:string; readonly orderId:string|null; readonly amountCents:number; }
export interface AccountingReceivable { readonly id:string; readonly customerId:string|null; readonly customerName:string; readonly customerPhone:string|null; readonly customerArchived:boolean; readonly orderId:string|null; readonly orderNumber:string|null; readonly channel:AccountingChannel|null; readonly currency:string; readonly saleCents:number; readonly collectedCents:number; readonly returnCents:number; readonly refundedCents:number; readonly dueCents:number; readonly refundDueCents:number; readonly occurredAt:string; readonly dueDate:string|null; readonly version:number; }
export interface AccountingEvent { readonly id:string; readonly kind:string; readonly currency:string; readonly amountCents:number; readonly accountId:string|null; readonly customerId:string|null; readonly orderId:string|null; readonly channel:AccountingChannel|null; readonly paymentMethod:AccountingPaymentMethod|null; readonly note:string|null; readonly category:string|null; readonly documentNumber:string|null; readonly metadata:Readonly<Record<string,unknown>>; readonly actorMembershipId:string; readonly occurredAt:string; readonly createdAt:string; readonly reversesEventId:string|null; readonly reversed:boolean; readonly allocations:readonly AccountingAllocation[]; }
export interface AccountingCustomerAccount { readonly customerId:string; readonly customerName:string; readonly customerPhone:string|null; readonly customerArchived:boolean; readonly currency:string; readonly version:number; readonly dueCents:number; readonly refundDueCents:number; readonly receivables:readonly AccountingReceivable[]; readonly events:readonly AccountingEvent[]; }
export interface AccountingAccount { readonly id:string; readonly name:string; readonly type:'cash'|'bank'|'card'; readonly currency:string; readonly balanceCents:number; readonly version:number; readonly createdAt:string; }
export interface AccountingCurrencySummary { readonly currency:string; readonly salesCents:number; readonly collectionsCents:number; readonly returnCents:number; readonly refundsCents:number; readonly expensesCents:number; readonly commissionCents:number; readonly dueCents:number; readonly overdueCents:number; readonly refundDueCents:number; readonly recordedWebPaymentsCents:number; }
export interface AccountingOverview { readonly currencies:readonly AccountingCurrencySummary[]; readonly accounts:readonly AccountingAccount[]; readonly recentEvents:readonly AccountingEvent[]; }
export interface AccountingReceivables { readonly receivables:readonly AccountingReceivable[]; }
export interface AccountingAccounts { readonly accounts:readonly AccountingAccount[]; readonly events:readonly AccountingEvent[]; }
export interface AccountingExpenses { readonly expenses:readonly AccountingEvent[]; }
export interface AccountingCollectionPreview { readonly customerId:string; readonly currency:string; readonly version:number; readonly dueCents:number; readonly allocations:readonly AccountingAllocation[]; }
export interface AccountingMutationResult { readonly operationId:string; readonly replayed:boolean; readonly event:AccountingEvent|null; readonly account:AccountingAccount|null; readonly customerAccount:AccountingCustomerAccount|null; readonly finance:AccountingOrderFinance|null; }
export interface AccountingCollectionIntent { readonly customerId:string; readonly orderId:string|null; readonly amountCents:number; readonly currency:string; readonly paymentMethod:AccountingPaymentMethod; readonly accountId:string|null; readonly expectedVersion:number; readonly note:string|null; }
export interface AccountingOpeningDebtIntent { readonly customerId:string; readonly amountCents:number; readonly currency:string; readonly occurredOn:string; readonly note:string; readonly expectedVersion:number; }
export interface AccountingSaveAccountIntent { readonly name:string; readonly type:'cash'|'bank'|'card'; readonly currency:string; }
export interface AccountingOpeningBalanceIntent { readonly accountId:string; readonly amountCents:number; readonly occurredOn:string; readonly note:string; readonly expectedVersion:number; }
export interface AccountingExpenseIntent { readonly accountId:string; readonly amountCents:number; readonly currency:string; readonly category:string; readonly documentNumber?:string|null; readonly note:string; readonly occurredOn:string; readonly expectedVersion:number; }
export interface AccountingTransferIntent { readonly fromAccountId:string; readonly toAccountId:string; readonly amountCents:number; readonly expectedVersion:number; readonly toExpectedVersion:number; readonly note:string; }
export interface AccountingCardSettlementIntent extends AccountingTransferIntent { readonly commissionCents:number; }
export interface AccountingReversalIntent { readonly eventId:string; readonly reason:string; readonly expectedVersion:number; }
export interface AccountingReturnCreditIntent { readonly orderId:string; readonly amountCents:number; readonly reason:string; readonly expectedVersion:number; }
export interface AccountingRefundIntent { readonly orderId:string; readonly accountId:string; readonly amountCents:number; readonly paymentMethod:AccountingPaymentMethod; readonly reason:string; readonly expectedVersion:number; }
export interface AccountingIntentMap { collect:AccountingCollectionIntent; openingDebt:AccountingOpeningDebtIntent; saveAccount:AccountingSaveAccountIntent; openBalance:AccountingOpeningBalanceIntent; expense:AccountingExpenseIntent; transfer:AccountingTransferIntent; settleCard:AccountingCardSettlementIntent; reverse:AccountingReversalIntent; returnCredit:AccountingReturnCreditIntent; refund:AccountingRefundIntent; }

export interface AccountingCollectionAccounts { readonly accounts:readonly Pick<AccountingAccount,'id'|'name'|'type'|'currency'>[]; }
