import { ACCOUNTING_MUTATIONS, type AccountingIntentMap, type AccountingMutation, type AccountingFilters } from './types.ts';
const ID=/^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/;
function fail():never {throw new TypeError('invalid_accounting_input');}
export function accountingExact(value:unknown,required:readonly string[],optional:readonly string[]=[]):Record<string,unknown>{if(typeof value!=='object'||value===null||Array.isArray(value)||![Object.prototype,null].includes(Object.getPrototypeOf(value)))fail();const descriptors=Object.getOwnPropertyDescriptors(value),allowed=new Set([...required,...optional]);if(required.some(k=>!Object.hasOwn(descriptors,k))||Reflect.ownKeys(descriptors).some(k=>typeof k!=='string'||!allowed.has(k)))fail();const copy:Record<string,unknown>={};for(const k of Object.keys(descriptors)){const d=descriptors[k]!;if(!('value'in d)||!d.enumerable)fail();copy[k]=d.value;}return copy;}
export function accountingUuid(v:unknown):string {if(typeof v!=='string'||!ID.test(v))fail();return v;}
export function accountingInteger(v:unknown,min=0):number {if(!Number.isSafeInteger(v)||(v as number)<min)fail();return v as number;}
function text(v:unknown,max=2000):string {if(typeof v!=='string'||v.length<1||v.length>max||v!==v.trim()||/[\u0000-\u001f\u007f]/.test(v))fail();return v;}
function date(v:unknown):string {if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v+'T00:00:00.000Z'))||new Date(v+'T00:00:00.000Z').toISOString().slice(0,10)!==v)fail();return v;}
const keys:Record<AccountingMutation,readonly string[]>={collect:['customerId','orderId','amountCents','currency','paymentMethod','accountId','expectedVersion','note'],openingDebt:['customerId','amountCents','currency','occurredOn','note','expectedVersion'],saveAccount:['name','type','currency'],openBalance:['accountId','amountCents','occurredOn','note','expectedVersion'],expense:['accountId','amountCents','currency','category','note','occurredOn','expectedVersion'],transfer:['fromAccountId','toAccountId','amountCents','expectedVersion','toExpectedVersion','note'],settleCard:['fromAccountId','toAccountId','amountCents','commissionCents','expectedVersion','toExpectedVersion','note'],reverse:['eventId','reason','expectedVersion'],returnCredit:['orderId','amountCents','reason','expectedVersion'],refund:['orderId','accountId','amountCents','paymentMethod','reason','expectedVersion']};
export function parseAccountingIntent<K extends AccountingMutation>(kind:K,value:unknown):Readonly<AccountingIntentMap[K]>{if(!ACCOUNTING_MUTATIONS.includes(kind))fail();const b=accountingExact(value,keys[kind],kind==='expense'?['documentNumber']:[]);for(const [k,v]of Object.entries(b)){if(k.endsWith('Id')){if(v===null&&((kind==='collect'&&['orderId','accountId'].includes(k))))continue;accountingUuid(v);}else if(['amountCents','commissionCents'].includes(k))accountingInteger(v,k==='commissionCents'?0:kind==='openBalance'?0:1);else if(['expectedVersion','toExpectedVersion'].includes(k))accountingInteger(v,kind==='openingDebt'?0:1);else if(k==='currency'){if(typeof v!=='string'||! /^[A-Z]{3}$/.test(v))fail();}else if(k==='paymentMethod'){if(!['cash','card','bank_transfer'].includes(v as string))fail();}else if(k==='type'){if(!['cash','bank','card'].includes(v as string))fail();}else if(k==='occurredOn')date(v);else if((k==='note'&&kind==='collect'||k==='documentNumber')&&v===null)continue;else text(v,k==='name'?200:k==='category'||k==='documentNumber'?100:2000);}
if(kind==='transfer'||kind==='settleCard'){if(b.fromAccountId===b.toAccountId)fail();if(kind==='settleCard'&&(b.commissionCents as number)>(b.amountCents as number))fail();}return Object.freeze(b) as unknown as Readonly<AccountingIntentMap[K]>;}
export function parseAccountingFilters(value:unknown):Readonly<AccountingFilters>{const b=accountingExact(value,[],['dateFrom','dateTo','channel','currency','query','customerId','orderId']);for(const[k,v]of Object.entries(b)){if(k.endsWith('Id'))accountingUuid(v);else if(k==='dateFrom'||k==='dateTo')date(v);else if(k==='channel'){if(!['WEB','POS'].includes(v as string))fail();}else if(k==='currency'){if(typeof v!=='string'||! /^[A-Z]{3}$/.test(v))fail();}else text(v,200);}if(b.dateFrom&&b.dateTo&&b.dateFrom>b.dateTo)fail();return Object.freeze(b) as AccountingFilters;}
