[start]
runImage = "node:20-bookworm"
onlyIncludeFiles = [
  "package.json",
  "package-lock.json",
  "apps/admin",
  "apps/owner",
  "apps/storefront-deri-kordon",
  "packages/platform-config",
  "stores"
]
