import { parseCustomerDetail,parseCustomerListItem,parseCustomerMutationResult,parseCustomerSegment,parseCustomerSummary,parseCustomerTag,parseCustomerWorkspace,type TenantContext } from "@celebix/saas-contracts";import { CustomerRepositoryError,type CustomerErrorCode } from "@celebix/saas-data";import type { ServerPanelAccessResult } from "../server-panel-access/access.ts";import type { ServerCustomerRuntime } from "../server-customers/runtime.ts";import { readOrderPanelSessionCookie } from "../order-http/request-input.ts";import { approvedPanelMutationOriginForStore } from "../panel-origin-authority.ts";import { createCustomerRequestAuthorityValidator,type CustomerRequestExpectation } from "./request-authority.ts";import { readCustomerArchiveInput,readCustomerIdsInput,readCustomerListInput,readCustomerNoteInput,readCustomerPathId,readCustomerSaveInput,readCustomerTaxonomyInput } from "./request-input.ts";
const BASE="/api/customers",REQUEST_ID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;const STATUS:Readonly<Record<CustomerErrorCode,number>>=Object.freeze({invalid_input:400,unauthenticated:401,membership_denied:403,store_inactive:403,feature_not_enabled:403,customer_not_found:404,customer_conflict:409,invalid_transition:409,version_conflict:409,operation_mismatch:409,durable_authority_invalid:409,unavailable:503});type Deps=Readonly<{resolveRuntime():Promise<ServerCustomerRuntime|null>;now():Date;requestId():string}>;type Authorized=Readonly<{runtime:ServerCustomerRuntime;tenantContext:TenantContext;now:Date}>;function json(v:unknown,status=200,h?:HeadersInit){const headers=new Headers(h);headers.set("cache-control","no-store");headers.set("x-content-type-options","nosniff");return Response.json(v,{status,headers})}function error(code:string,status:number,h?:HeadersInit){return json({code},status,h)}function isResponse(v:unknown):v is Response{return v instanceof Response}function privateHeaders(r:Request){for(const[name]of r.headers)if(name==="authorization"||name.startsWith("x-celebix")||["x-store-id","x-tenant-id","x-principal-id","x-membership-id","x-plan-id","x-database-url"].includes(name))return true;return false}
function repoError(e:unknown){return e instanceof CustomerRepositoryError?error(e.code,STATUS[e.code]):error("unavailable",503)}
async function authorize(d:Deps,r:Request,e:CustomerRequestExpectation):Promise<Response|Authorized>{let runtime;try{runtime=await d.resolveRuntime()}catch{return error("unavailable",503)}if(!runtime)return error("unavailable",503);let decision;try{decision=createCustomerRequestAuthorityValidator({panelOrigin:runtime.access.panelOrigin}).validate(r,e)}catch{return error("unavailable",503)}if(decision==="method_not_allowed")return error("method_not_allowed",405,{allow:e.method});if(decision==="origin_denied")return error("origin_denied",403);if(decision!=="approved"||privateHeaders(r))return error("invalid_input",400);const cookie=readOrderPanelSessionCookie(r);if(cookie.kind!=="present")return error("unauthenticated",401);let now:Date,requestId:string;try{now=d.now();requestId=d.requestId()}catch{return error("unavailable",503)}if(!(now instanceof Date)||!Number.isFinite(now.getTime())||!REQUEST_ID.test(requestId))return error("unavailable",503);let access:ServerPanelAccessResult;try{access=await runtime.access.resolveCredential({credential:cookie.credential,requestId,now:new Date(now)})}catch{return error("unavailable",503)}if(access.kind==="unauthenticated")return error("unauthenticated",401);if(access.kind==="unauthorized")return error("membership_denied",403);if(access.kind!=="authenticated")return error("unavailable",503);if(e.method==="POST"&&!approvedPanelMutationOriginForStore(r,runtime.access.panelOrigin,access.tenantContext.store.slug))return error("origin_denied",403);return Object.freeze({runtime,tenantContext:access.tenantContext,now:new Date(now)})}
async function execute(fn:()=>Promise<unknown>,parser:(v:unknown)=>unknown){try{return json(parser(await fn()))}catch(e){return repoError(e)}}function listEnvelope(v:unknown,parser:(v:unknown)=>unknown){if(typeof v!=="object"||v===null||Array.isArray(v))throw TypeError();const r=v as Record<string,unknown>,keys=Object.keys(r).sort().join(",");if(!Array.isArray(r.items)||(keys!=="items"&&keys!=="items,nextCursor")||(r.nextCursor!==undefined&&(typeof r.nextCursor!=="string"||!/^[A-Za-z0-9_-]{1,1024}$/.test(r.nextCursor))))throw TypeError();return Object.freeze({items:Object.freeze(r.items.map(parser)),...(r.nextCursor?{nextCursor:r.nextCursor}:{})})}
export function createCustomerHttpHandlers(d:Deps){if(!d||typeof d.resolveRuntime!=="function"||typeof d.now!=="function"||typeof d.requestId!=="function")throw Error("customer_http_handler_invalid");const auth=(r:Request,e:CustomerRequestExpectation)=>authorize(d,r,e);return Object.freeze({
 async summary(r:Request){const a=await auth(r,{method:"GET",pathname:`${BASE}/summary`,query:"forbidden"});return isResponse(a)?a:execute(()=>a.runtime.customers.getSummary({tenantContext:a.tenantContext,now:a.now}),parseCustomerSummary)},
 async list(r:Request){const a=await auth(r,{method:"GET",pathname:BASE,query:"allowed"});if(isResponse(a))return a;const input=readCustomerListInput(r);return input.kind==="valid"?execute(()=>a.runtime.customers.list({tenantContext:a.tenantContext,now:a.now,...input.value}),v=>listEnvelope(v,parseCustomerListItem)):error("invalid_input",400)},
 async get(r:Request,raw:unknown){const id=readCustomerPathId(raw);if(!id)return error("invalid_input",400);const a=await auth(r,{method:"GET",pathname:`${BASE}/${id}`,query:"forbidden"});return isResponse(a)?a:execute(()=>a.runtime.customers.get({tenantContext:a.tenantContext,now:a.now,customerId:id}),parseCustomerDetail)},
 async workspace(r:Request,raw:unknown){const id=readCustomerPathId(raw);if(!id)return error("invalid_input",400);const a=await auth(r,{method:"GET",pathname:`${BASE}/${id}/workspace`,query:"forbidden"});return isResponse(a)?a:execute(()=>a.runtime.customers.getWorkspace({tenantContext:a.tenantContext,now:a.now,customerId:id}),parseCustomerWorkspace)},
 async create(r:Request){const a=await auth(r,{method:"POST",pathname:BASE,query:"forbidden"});if(isResponse(a))return a;const input=await readCustomerSaveInput(r,false);return input.kind==="valid"?execute(()=>a.runtime.customers.save({tenantContext:a.tenantContext,now:a.now,...input.value} as never),parseCustomerMutationResult):error("invalid_input",400)},
 async update(r:Request,raw:unknown){const id=readCustomerPathId(raw);if(!id)return error("invalid_input",400);const a=await auth(r,{method:"POST",pathname:`${BASE}/${id}`,query:"forbidden"});if(isResponse(a))return a;const input=await readCustomerSaveInput(r,true);return input.kind==="valid"?execute(()=>a.runtime.customers.save({tenantContext:a.tenantContext,now:a.now,customerId:id,...input.value} as never),parseCustomerMutationResult):error("invalid_input",400)},
 async archive(r:Request,raw:unknown){const id=readCustomerPathId(raw);if(!id)return error("invalid_input",400);const a=await auth(r,{method:"POST",pathname:`${BASE}/${id}/archive`,query:"forbidden"});if(isResponse(a))return a;const input=await readCustomerArchiveInput(r);return input.kind==="valid"?execute(()=>a.runtime.customers.archive({tenantContext:a.tenantContext,now:a.now,customerId:id,...input.value}),parseCustomerMutationResult):error("invalid_input",400)},
 async addNote(r:Request,raw:unknown){const id=readCustomerPathId(raw);if(!id)return error("invalid_input",400);const a=await auth(r,{method:"POST",pathname:`${BASE}/${id}/notes`,query:"forbidden"});if(isResponse(a))return a;const input=await readCustomerNoteInput(r);return input.kind==="valid"?execute(()=>a.runtime.customers.addNote({tenantContext:a.tenantContext,now:a.now,customerId:id,...input.value}),parseCustomerMutationResult):error("invalid_input",400)},
 async tags(r:Request){const a=await auth(r,{method:"GET",pathname:`${BASE}/tags`,query:"forbidden"});return isResponse(a)?a:execute(()=>a.runtime.customers.listTags({tenantContext:a.tenantContext,now:a.now}),v=>{if(!Array.isArray(v))throw TypeError();return Object.freeze({items:Object.freeze(v.map(parseCustomerTag))})})},
 async saveTag(r:Request){const a=await auth(r,{method:"POST",pathname:`${BASE}/tags`,query:"forbidden"});if(isResponse(a))return a;const input=await readCustomerTaxonomyInput(r,"tag");return input.kind==="valid"?execute(()=>a.runtime.customers.upsertTag({tenantContext:a.tenantContext,now:a.now,...input.value} as never),parseCustomerTag):error("invalid_input",400)},
 async segments(r:Request){const a=await auth(r,{method:"GET",pathname:`${BASE}/segments`,query:"forbidden"});return isResponse(a)?a:execute(()=>a.runtime.customers.listSegments({tenantContext:a.tenantContext,now:a.now}),v=>{if(!Array.isArray(v))throw TypeError();return Object.freeze({items:Object.freeze(v.map(parseCustomerSegment))})})},
 async saveSegment(r:Request){const a=await auth(r,{method:"POST",pathname:`${BASE}/segments`,query:"forbidden"});if(isResponse(a))return a;const input=await readCustomerTaxonomyInput(r,"segment");return input.kind==="valid"?execute(()=>a.runtime.customers.upsertSegment({tenantContext:a.tenantContext,now:a.now,...input.value} as never),parseCustomerSegment):error("invalid_input",400)},
 async setTags(r:Request,raw:unknown){return setTaxonomy(r,raw,"tags")},async setSegments(r:Request,raw:unknown){return setTaxonomy(r,raw,"segments")},
 async export(r:Request){const a=await auth(r,{method:"GET",pathname:`${BASE}/export`,query:"forbidden"});return isResponse(a)?a:execute(()=>a.runtime.customers.export({tenantContext:a.tenantContext,now:a.now}),v=>{if(typeof v!=="object"||v===null||Array.isArray(v))throw TypeError();const x=v as Record<string,unknown>;if(!Array.isArray(x.items)||typeof x.exportedAt!=="string"||Object.keys(x).sort().join(",")!=="exportedAt,items")throw TypeError();return Object.freeze({items:Object.freeze(x.items.map(parseCustomerListItem)),exportedAt:x.exportedAt})})}
 });async function setTaxonomy(r:Request,raw:unknown,kind:"tags"|"segments"){const id=readCustomerPathId(raw);if(!id)return error("invalid_input",400);const a=await auth(r,{method:"POST",pathname:`${BASE}/${id}/${kind}`,query:"forbidden"});if(isResponse(a))return a;const input=await readCustomerIdsInput(r);return input.kind==="valid"?execute(()=>kind==="tags"?a.runtime.customers.setTags({tenantContext:a.tenantContext,now:a.now,customerId:id,...input.value}):a.runtime.customers.setSegments({tenantContext:a.tenantContext,now:a.now,customerId:id,...input.value}),parseCustomerMutationResult):error("invalid_input",400)}}
