import {parseContentOutline} from '../../../packages/saas-contracts/src/content-resource-authoring/validation.ts';
import {PostgresContentResourceAuthoringRepository} from '../../../packages/saas-data/src/content-resource-authoring/repository.ts';
import assert from 'node:assert/strict';
import {createHash, randomUUID} from 'node:crypto';
import {existsSync, mkdtempSync, mkdirSync, readFileSync, readdirSync, rmSync} from 'node:fs';
import {homedir} from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import pg from 'pg';
import {acceptedMerchantContentHrefs,rejectedMerchantContentHrefs} from '../../../packages/saas-contracts/src/merchant-content/href-vectors.fixture.ts';
import {parseSaveMerchantContentRequest} from '../../../packages/saas-contracts/src/merchant-content/validation.ts';
import {normalizeMerchantContentBody} from '../../../packages/platform-config/src/merchant-content-body.ts';
import {parseMerchantAdminRecord} from '../../../packages/saas-contracts/src/merchant-admin/validation.ts';
import {parseMerchantContentDocument} from '../../../packages/saas-contracts/src/merchant-content/validation.ts';
import {PostgresMerchantContentRepository} from '../../../packages/saas-data/src/merchant-content/repository.ts';
import {PostgresContentResearchRepository} from '../../../packages/saas-data/src/content-research/repository.ts';

// Native, Unix-socket-only disposable cluster. Never reads a DSN or an existing database.
const ROOT=path.resolve(import.meta.dirname,'../../..'), SQL=path.join(ROOT,'apps/owner/scripts/sql/saas');
const BIN=path.join(homedir(),'.codex/tmp/postgresql-16.14-install/bin');
const UP='202609290176_content_research_evidence.up.sql', DOWN=UP.replace('.up.','.down.');
const DB='content_research_fixture';let NOW='2026-09-29T12:00:00.000Z';
const STORE='10000000-0000-4000-8000-000000000174', FOREIGN='10000000-0000-4000-8000-000000000175';
const PRINCIPAL='20000000-0000-4000-8000-000000000174', MEMBERSHIP='30000000-0000-4000-8000-000000000174';
const PLAN='00000000-0000-4000-8000-000000000001', HOST='content-fixture.example.test';
const id=n=>`a0000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const hash=value=>createHash('sha256').update(value).digest('hex');
const lit=value=>value===null?'NULL':`'${String(value).replaceAll("'","''")}'`;
const json=value=>`${lit(JSON.stringify(value))}::jsonb`;
const A=(principal=PRINCIPAL,membership=MEMBERSHIP,store=STORE)=>`${lit(store)}::uuid,${lit(principal)}::uuid,${lit(membership)}::uuid,'${PLAN}'::uuid,'free_starter',1,'${NOW}'::timestamptz`;
let root, socket, data, port, count=0;
function command(name,args,input='',allowFailure=false){const result=spawnSync(path.join(BIN,name),args,{cwd:ROOT,input,encoding:'utf8',timeout:120000,env:{...process.env,LC_ALL:'C',LANG:'C'},maxBuffer:64*1024*1024});if(result.error)throw result.error;if(!allowFailure&&result.status!==0)throw Error(`${name}: ${result.stderr}`);return result;}
function sql(source,db=DB,allowFailure=false){return command('psql',['-h',socket,'-p',String(port),'-U','postgres','-d',db,'-X','-qAt','-v','ON_ERROR_STOP=1'],source,allowFailure);}
const scalar=source=>sql(source).stdout.trim();
const query=source=>JSON.parse(scalar(source));
const owner=source=>sql(`BEGIN;SET LOCAL ROLE celebix_saas_owner;${source};COMMIT;`);
function apply(file){sql(readFileSync(path.join(SQL,file),'utf8'));}
function rpc(call,role='celebix_saas_app'){return query(`BEGIN;SET LOCAL ROLE ${role};SET LOCAL statement_timeout='5s';SET LOCAL lock_timeout='2s';SELECT jsonb_build_object('outcome',outcome,'payload',result_payload) FROM ${call};COMMIT;`);}
function generic({record=id(1),version=null,config={slug:'legacy-page',locale:'tr',body:'Short legacy',published:false},operation=randomUUID(),name='Legacy',kind='page',status='draft',authority=A()}={}){return rpc(`saas.merchant_admin_save(${authority},'${operation}','${hash(operation)}','${record}',${version??'NULL'},'${kind}',${lit(name)},${json(config)},'${status}')`);}
function request(document=null,body='<p>Typed body</p>'){return {draftId:id(90),recordId:document?.id??null,expectedVersion:document?.version??null,expectedBodyDigest:document?.bodyDigest??null,kind:'page',bodyAction:'replace',values:{name:'Typed page',slug:'typed-page',locale:'tr',body,excerpt:null,seoTitle:null,seoDescription:null,published:false,status:'draft'},origins:{}};}
function save(value,operation=randomUUID(),authority=A(),fingerprint=hash(JSON.stringify(value))){return rpc(`saas.merchant_content_save(${authority},'${operation}','${fingerprint}',${json(value)})`);}
function get(record,authority=A(),kind='page'){const result=rpc(`saas.merchant_content_get(${authority},'${kind}','${record}')`);if(result.outcome==='found')parseMerchantContentDocument(result.payload);return result;}
const recover=(operation,fingerprint,authority=A())=>rpc(`saas.merchant_content_recover_operation(${authority},'${operation}','${fingerprint}')`);
async function check(name,run){NOW=new Date(Date.parse(NOW)+61000).toISOString();await run();console.log(`PASS ${++count} ${name}`);}
async function main(){
 try{
  root=mkdtempSync('/tmp/celebix-content-research-');socket=path.join(root,'socket');data=path.join(root,'data');port=24000+Math.floor(Math.random()*10000);mkdirSync(socket,{mode:0o700});
  command('initdb',['-D',data,'--auth=trust','--username=postgres','--no-locale','--encoding=UTF8']);command('pg_ctl',['-D',data,'-o',`-k ${socket} -p ${port} -h ''`,'-l',path.join(root,'postgres.log'),'start']);
  sql(`CREATE DATABASE ${DB};`,'postgres');
  const files=readdirSync(SQL).filter(f=>{const n=Number(f.slice(8,12));return (n<=128||[130,142,144,149,150,153,154,158,162,163,164,165,170,171,172,173,174].includes(n))&&!f.includes('seed_guzide')&&/(?:\.up|\.seed|\.freeze|_grants)\.sql$/.test(f)}).sort((a,b)=>Number(a.slice(8,12))-Number(b.slice(8,12))||a.localeCompare(b));
  for(const file of files)apply(file);
  owner(`INSERT INTO saas.stores(id,name,slug,status,locale,currency,theme_key,created_at,updated_at) VALUES('${STORE}','Content fixture','content-fixture','active','tr','TRY','starter','2026-01-01','2026-01-01'),('${FOREIGN}','Foreign fixture','foreign-fixture','active','tr','TRY','starter','2026-01-01','2026-01-01');
   INSERT INTO saas.principals(id,issuer,subject,email,email_verified,created_at,updated_at) VALUES('${PRINCIPAL}','https://identity.example.test','content-owner','owner@example.test',true,'2026-01-01','2026-01-01'),('${id(20)}','https://identity.example.test','other-owner','other@example.test',true,'2026-01-01','2026-01-01');
   INSERT INTO saas.memberships(id,principal_id,store_id,role,status,created_at,updated_at) VALUES('${MEMBERSHIP}','${PRINCIPAL}','${STORE}','store_owner','active','2026-01-01','2026-01-01'),('${id(21)}','${id(20)}','${STORE}','store_owner','active','2026-01-01','2026-01-01');
   INSERT INTO saas.subscriptions(id,store_id,plan_id,plan_code,plan_version,status,valid_from,created_at,updated_at) VALUES('${id(70)}','${STORE}','${PLAN}','free_starter',1,'active','2026-01-01','2026-01-01','2026-01-01');
   INSERT INTO saas.store_domains(id,store_id,hostname,hostname_type,status,is_primary,verified_at,created_at,updated_at,version) VALUES('${id(71)}','${STORE}','${HOST}','custom_domain','active',true,'2026-01-01','2026-01-01','2026-01-01',1)`);

  apply('202609290175_content_resource_authoring.up.sql');
  const oldHelper=scalar("SELECT pg_get_functiondef('saas.content_authoring_shared_admission(uuid,uuid,timestamptz)'::regprocedure)");
  const originalFunctions=()=>query("SELECT jsonb_object_agg(oid::text,jsonb_build_object('definition',pg_get_functiondef(oid),'acl',proacl::text,'owner',proowner::regrole::text)) FROM pg_proc WHERE pronamespace='saas'::regnamespace AND (proname LIKE 'merchant_content_%' OR proname LIKE 'content_authoring_%' OR proname LIKE 'content_resource_%') AND proname<>'content_authoring_shared_admission'");
  const beforeFunctions=originalFunctions();
  apply(UP);
  const target={kind:'page',draftId:id(90),recordId:null,recordVersion:null};const fp='a'.repeat(64);
  const begin=(op=randomUUID(),requestTarget=target,authority=A())=>rpc(`saas.content_research_begin(${authority},'${op}','${fp}',${json(requestTarget)})`);
  const get=op=>rpc(`saas.content_research_get(${A()},'${op}')`);
  const claim=g=>rpc(`saas.content_research_claim(${A()},'${g.operationId}',${g.version})`);
  const fail=(g,code='content_research_response_invalid',usage={sourcesAttempted:1,fetchedBytes:0,extractedBytes:0,elapsedMs:10},state=g.dispatchState,token=g.claimToken)=>rpc(`saas.content_research_fail(${A()},'${g.operationId}',${g.version},${lit(token)}::uuid,${lit(code)},${lit(state)},${json(usage)})`);
  const source={id:randomUUID(),originalUrl:'https://source.example.test/',finalUrl:'https://source.example.test/',title:'Source',fetchedAt:'2026-09-29T12:00:00.000Z',contentSha256:hash('Evidence text'),extractedText:'Evidence text',byteCount:13};
  const completedUsage={sourcesAttempted:1,fetchedBytes:13,extractedBytes:13,elapsedMs:20};
  const complete=(g,sources=[source],usage=completedUsage)=>rpc(`saas.content_research_complete(${A()},'${g.operationId}',${g.version},'${g.claimToken}',${json(sources)},${json(usage)})`);
  await check('private relation and helper cannot be called by app role',()=>{for(const table of ['content_research_operations','content_research_sources'])assert.match(sql(`SET ROLE celebix_saas_app;SELECT * FROM saas.${table}`,DB,true).stderr,/permission denied/);assert.match(sql(`SET ROLE celebix_saas_app;SELECT saas.content_research_transition(${A()},'get','${randomUUID()}',NULL,NULL,'{}'::jsonb)`,DB,true).stderr,/permission denied/);});
  await check('original product and content functions ACLs remain exact',()=>{assert.deepEqual(originalFunctions(),beforeFunctions);});
  await check('claim, evidence completion, terminal replay and safe projection',()=>{const started=begin();assert.equal(started.outcome,'pending');assert.equal(begin(started.payload.operationId).outcome,'existing-status');const claimed=claim(started.payload);assert.equal(claimed.outcome,'claimed');const done=complete(claimed.payload);assert.equal(done.outcome,'completed');assert.equal(done.payload.sources[0].extractedText,'Evidence text');assert.equal(get(started.payload.operationId).payload.status,'completed');assert.equal(complete(claimed.payload).outcome,'completed');assert.equal(complete(claimed.payload,[{...source,extractedText:'Other'}]).outcome,'version_conflict');});
  await check('source hash, URL, duplicate IDs and metered usage validated before evidence write',()=>{const started=claim(begin().payload).payload;for(const bad of [[{...source,contentSha256:'b'.repeat(64)}],[{...source,finalUrl:'https://localhost/'}],[{...source,byteCount:14}]])assert.equal(complete(started,bad).outcome,'invalid_input');assert.equal(complete(started,[source,source],{sourcesAttempted:2,fetchedBytes:26,extractedBytes:26,elapsedMs:20}).outcome,'invalid_input');assert.equal(get(started.operationId).payload.status,'pending');assert.equal(fail(started).outcome,'failed');assert.equal(scalar(`SELECT count(*) FROM saas.content_research_sources WHERE operation_id='${started.operationId}'`),'0');});
  await check('source one success and source two error retains measured usage but no partial evidence',()=>{const g=claim(begin().payload).payload;const usage={sourcesAttempted:2,fetchedBytes:13,extractedBytes:13,elapsedMs:123};const result=fail(g,'content_research_timeout',usage,'unknown');assert.equal(result.outcome,'failed');assert.equal(result.payload.status,'unknown');assert.deepEqual(result.payload.sources,[]);assert.deepEqual(result.payload.usage,usage);assert.equal(scalar(`SELECT count(*) FROM saas.content_research_sources WHERE operation_id='${g.operationId}'`),'0');});
  await check('cross-actor, same actor in another store, and revoked authority cannot reveal private source',()=>{const g=claim(begin().payload).payload;assert.equal(complete(g).outcome,'completed');assert.equal(rpc(`saas.content_research_get(${A(id(20),id(21))},'${g.operationId}')`).outcome,'operation_not_found');owner(`INSERT INTO saas.memberships(id,principal_id,store_id,role,status,created_at,updated_at) VALUES('${id(22)}','${PRINCIPAL}','${FOREIGN}','store_owner','active','2026-01-01','2026-01-01');INSERT INTO saas.subscriptions(id,store_id,plan_id,plan_code,plan_version,status,valid_from,created_at,updated_at) VALUES('${id(72)}','${FOREIGN}','${PLAN}','free_starter',1,'active','2026-01-01','2026-01-01','2026-01-01')`);const foreign=A(PRINCIPAL,id(22),FOREIGN);assert.equal(rpc(`saas.content_research_get(${foreign},'${g.operationId}')`).outcome,'operation_not_found');const ownForeign=begin(randomUUID(),target,foreign);assert.equal(ownForeign.outcome,'pending');assert.equal(rpc(`saas.content_research_fail(${foreign},'${ownForeign.payload.operationId}',1,NULL,'cancelled','not_dispatched','{"sourcesAttempted":0,"fetchedBytes":0,"extractedBytes":0,"elapsedMs":0}'::jsonb)`).outcome,'failed');owner(`UPDATE saas.memberships SET status='revoked' WHERE id='${MEMBERSHIP}'`);assert.equal(get(g.operationId).outcome,'membership_denied');owner(`UPDATE saas.memberships SET status='active' WHERE id='${MEMBERSHIP}'`);});
  await check('same operation mismatches cannot charge again and stale claim cannot dispatch',()=>{const op=randomUUID(),g=begin(op).payload;assert.equal(begin(op,{...target,draftId:randomUUID()}).outcome,'operation_mismatch');assert.equal(rpc(`saas.content_research_claim(${A()},'${op}',2)`).outcome,'version_conflict');const claimed=claim(g).payload;assert.equal(claim(g).outcome,'version_conflict');assert.equal(claim(claimed).outcome,'dispatch_already_claimed');assert.equal(fail(claimed).outcome,'failed');});
  await check('existing document version is checked again before first network claim',()=>{const doc=save(request()).payload;const t={...target,recordId:doc.id,recordVersion:doc.version};const pending=begin(randomUUID(),t).payload;assert.equal(save(request(doc)).outcome,'saved');assert.equal(claim(pending).outcome,'version_conflict');assert.equal(fail(pending,'cancelled',{sourcesAttempted:0,fetchedBytes:0,extractedBytes:0,elapsedMs:0},'not_dispatched',null).outcome,'failed');});
  await check('null failure code or dispatch state cannot create an invalid terminal operation',()=>{const g=claim(begin().payload).payload;assert.equal(fail(g,null).outcome,'invalid_input');assert.equal(fail(g,'content_research_timeout',{sourcesAttempted:0,fetchedBytes:0,extractedBytes:0,elapsedMs:0},null).outcome,'invalid_input');assert.equal(get(g.operationId).payload.status,'pending');assert.equal(fail(g).outcome,'failed');});
  await check('evidence insert failure rolls back source and terminal usage together',()=>{const g=claim(begin().payload).payload;owner("CREATE FUNCTION saas.fixture_research_source_fail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'fixture_source_failure'; END $$;CREATE TRIGGER fixture_research_source_fail BEFORE INSERT ON saas.content_research_sources FOR EACH ROW EXECUTE FUNCTION saas.fixture_research_source_fail()");assert.match(sql(`SET ROLE celebix_saas_app;SELECT * FROM saas.content_research_complete(${A()},'${g.operationId}',${g.version},'${g.claimToken}',${json([source])},${json(completedUsage)})`,DB,true).stderr,/fixture_source_failure/);owner('DROP TRIGGER fixture_research_source_fail ON saas.content_research_sources;DROP FUNCTION saas.fixture_research_source_fail()');assert.equal(get(g.operationId).payload.status,'pending');assert.deepEqual(get(g.operationId).payload.usage,{sourcesAttempted:0,fetchedBytes:0,extractedBytes:0,elapsedMs:0});assert.equal(scalar(`SELECT count(*) FROM saas.content_research_sources WHERE operation_id='${g.operationId}'`),'0');assert.equal(complete(g).outcome,'completed');});
  await check('concurrent research begins admit only one active store actor',async()=>{const clients=[new pg.Client({host:socket,port,user:'postgres',database:DB}),new pg.Client({host:socket,port,user:'postgres',database:DB})];try{await Promise.all(clients.map(c=>c.connect()));const operations=[randomUUID(),randomUUID()];const outcomes=await Promise.all(clients.map(async(c,i)=>{await c.query('BEGIN');await c.query('SET LOCAL ROLE celebix_saas_app');const r=await c.query(`SELECT outcome FROM saas.content_research_begin(${A()},'${operations[i]}','${fp}',${json(target)})`);await c.query('COMMIT');return{outcome:r.rows[0].outcome,id:operations[i]};}));assert.deepEqual(outcomes.map(x=>x.outcome).sort(),['operation_busy','pending']);const active=outcomes.find(x=>x.outcome==='pending');assert.equal(fail(get(active.id).payload,'cancelled',{sourcesAttempted:0,fetchedBytes:0,extractedBytes:0,elapsedMs:0},'not_dispatched',null).outcome,'failed');}finally{await Promise.all(clients.map(c=>c.end()));}});
  await check('lost COMMIT acknowledgment never retries a new network reservation',async()=>{const pool=new pg.Pool({host:socket,port,user:'postgres',database:DB,max:2}),operation=randomUUID();let lost=true,begins=0,audits=0;const wrapped={async connect(){const client=await pool.connect();return{async query(text,values){if(text.includes('saas.content_research_begin'))begins++;const result=await client.query(text,values);if(text==='COMMIT'&&lost){lost=false;throw Error('lost_ack');}return result;},release(destroy){client.release(destroy);}};}};const tenantContext={schemaVersion:1,requestId:id(80),principal:{id:PRINCIPAL,issuer:'https://identity.example.test',subject:'content-owner'},store:{id:STORE,slug:'content-fixture',status:'active'},membership:{id:MEMBERSHIP,role:'store_owner',status:'active'},entitlements:{schemaVersion:1,planId:PLAN,planCode:'free_starter',version:1,status:'active',features:['catalog'],limits:{products:100,staff:5,storageBytes:1024},validFrom:'2026-01-01T00:00:00.000Z'},locale:'tr'};try{const repo=new PostgresContentResearchRepository({pool:wrapped,role:'celebix_saas_app',timeouts:{poolCheckoutMs:1000,statementMs:1000,lockMs:500,idleTransactionMs:2000},audit(){audits++;}});await assert.rejects(repo.begin({tenantContext,now:new Date(NOW),operationId:operation,requestFingerprint:fp,target}),{code:'commit_unknown'});assert.equal(begins,1);assert.equal(audits,1);const observed=await repo.get({tenantContext,now:new Date(NOW),operationId:operation});assert.equal(observed.status,'pending');assert.equal(fail(observed,'cancelled',{sourcesAttempted:0,fetchedBytes:0,extractedBytes:0,elapsedMs:0},'not_dispatched',null).outcome,'failed');}finally{await pool.end();}});
  await check('expired dispatched research is unknown with retained fence and unknown usage, never zero',()=>{NOW=new Date(Date.parse(NOW)+86400000).toISOString();const g=claim(begin().payload).payload;NOW=new Date(Date.parse(NOW)+30000).toISOString();const observed=get(g.operationId).payload;assert.equal(observed.status,'unknown');assert.equal(observed.dispatchState,'unknown');assert.equal(observed.claimToken,g.claimToken);assert.equal(observed.usage,null);assert.equal(claim(g).outcome,'version_conflict');assert.equal(begin(g.operationId).outcome,'existing-status');});
  await check('shared active blocks model request and retrieval has separate daily accounting',()=>{const g=begin().payload;const model=rpc(`saas.content_authoring_begin_shared(${A()},'${randomUUID()}','${fp}','${target.draftId}',NULL,'${'b'.repeat(64)}','${randomUUID()}','deepseek','deepseek-flash',1,'v4')`);assert.equal(model.outcome,'operation_busy');assert.equal(fail(g,'cancelled',{sourcesAttempted:0,fetchedBytes:0,extractedBytes:0,elapsedMs:0},'not_dispatched',null).outcome,'failed');});
  await check('retrieval has independent six-minute and ten-UTC-day limits; replay is free',()=>{NOW=new Date(Date.parse(NOW)+86400000).toISOString();const ids=[];for(let i=0;i<6;i++){const g=begin().payload;ids.push(g.operationId);assert.equal(fail(g,'cancelled',{sourcesAttempted:0,fetchedBytes:0,extractedBytes:0,elapsedMs:0},'not_dispatched',null).outcome,'failed');}assert.equal(begin().outcome,'rate_limited');assert.equal(begin(ids[0]).outcome,'existing-status');NOW=new Date(Date.parse(NOW)+61000).toISOString();for(let i=0;i<4;i++){const g=begin().payload;assert.equal(fail(g,'cancelled',{sourcesAttempted:0,fetchedBytes:0,extractedBytes:0,elapsedMs:0},'not_dispatched',null).outcome,'failed');}assert.equal(begin().outcome,'quota_exceeded');assert.equal(begin(ids[0]).outcome,'existing-status');assert.equal(scalar(`SELECT saas.content_authoring_shared_admission('${STORE}','${PRINCIPAL}','${NOW}')`),'');NOW=new Date(Date.parse(NOW)+86400000).toISOString();assert.equal(begin().outcome,'pending');});
  await check('down disables writer without erasing evidence and up restores it',()=>{const rows=()=>query(`SELECT jsonb_build_object('operations',(SELECT jsonb_agg(to_jsonb(o) ORDER BY id) FROM saas.content_research_operations o),'sources',(SELECT jsonb_agg(to_jsonb(s) ORDER BY operation_id,ordinal) FROM saas.content_research_sources s))`);const before=rows();apply(DOWN);assert.deepEqual(rows(),before);assert.equal(begin().outcome,'unavailable');assert.equal(get(before.operations[0].id).outcome,'found');assert.equal(scalar("SELECT pg_get_functiondef('saas.content_authoring_shared_admission(uuid,uuid,timestamptz)'::regprocedure)"),oldHelper);apply(UP);assert.deepEqual(rows(),before);const g=begin();assert.equal(g.outcome,'pending');});
  console.log(`PASS native content research: ${count} scenarios`);
 }finally{if(data&&existsSync(path.join(data,'postmaster.pid')))command('pg_ctl',['-D',data,'-m','fast','stop'],'',true);if(root)rmSync(root,{recursive:true,force:true});}
}
await main();
