/** Shared portable-link vectors for the normalizer, typed contract, and storage parity tests. */
export const acceptedMerchantContentHrefs = [
    'https://example.test/path?q=1#section',
    'HTTP://Sub.Example.test:8080/a',
    'https://xn--bcher-kva.example/a',
    'http://localhost:3000/',
    'https://example.test:0/',
    'https://example.test:65535/',
    '/content/example',
    '/',
    '#section',
    'mailto:help@example.test',
    'tel:+902121234567;ext=42',
] as const;

export const rejectedMerchantContentHrefs = [
    '',
    'https://[::1]/',
    'https://127.0.0.1/',
    'https://example.test:65536/',
    'https://example.test:99999/',
    'https://example.test:000443/',
    'https://example%0a.test/',
    'https://%65xample.test/',
    'https://exa_mple.test/',
    'https://example..test/',
    'https://-example.test/',
    'https://example.test./',
    'https://user:pass@example.test/',
    'https://@example.test/',
    'https://bücher.example/',
    '//example.test',
    'javascript:alert(1)',
    'https://example.test/a b',
    'https://example.test/a\u00a0b',
    'https://example.test/a\u2028b',
    'https://example.test/a\\b',
    `https://${'a'.repeat(64)}.test/`,
    `https://${`${'a'.repeat(63)}.`.repeat(3)}${'a'.repeat(62)}/`,
] as const;
