import { buildDefaultStarterPresentation, type PublicStorefront, type PublicStarterThemePresentationV3, type PublicStorefrontDesign, type PublicProduct } from "@celebix/saas-contracts";
import { LILYUM_STOREFRONT_ID } from "../../../../../apps/storefront-shared/themes/lilyum/theme.ts";
const origin = `https://media.saas-staging.celebix.site/stores/${LILYUM_STOREFRONT_ID}`;
const image = (path: string, altText: string) => ({ url: `${origin}/${path}`, altText, mediaType: "image/jpeg" as const, width: 800, height: 800 });
const seedProducts: PublicProduct[] = [
  { id: "cdefacc9-ad05-5cc6-b625-af3dea821bd6", slug: "pembe-lilyum-gerbera", title: "Pembe Lilyum Gerbera", priceCents: 96000, compareAtCents: 134000, media: [{ ...image("products/cdefacc9-ad05-5cc6-b625-af3dea821bd6/53a193ee-6136-8393-8566-d39622fde8b9.jpg", "Pembe Lilyum Gerbera"), id:"53a193ee-6136-4393-8566-d39622fde8b9", productId: "cdefacc9-ad05-5cc6-b625-af3dea821bd6", sortOrder: 0 }], currency: "TRY", status: "active", available: true, variants: [{ id: "11111111-1111-4111-8111-111111111111", title: "Standart", sku: "QA", priceCents: 96000, available: true, stockTracking: true, stockQuantity: 50, attributes: {} }] },
  { id: "af2f9dcd-83ec-5b09-8b46-cce535fa84ae", slug: "we-are-the-best-2-dal-beyaz-orkide-aranjmani", title: "We Are The Best 2 Dal Beyaz Orkide Aranjmanı", priceCents: 169899, compareAtCents: 219900, media: [{ ...image("products/af2f9dcd-83ec-5b09-8b46-cce535fa84ae/0656495d-7d9f-8d80-84f1-fc5ecca7e932.webp", "Beyaz Orkide"), mediaType: "image/webp", id: "0656495d-7d9f-4d80-84f1-fc5ecca7e932", productId: "af2f9dcd-83ec-5b09-8b46-cce535fa84ae", sortOrder: 0 }], currency: "TRY", status: "active", available: true, variants: [{ id: "11111111-1111-4111-8111-111111111111", title: "Standart", sku: "QA", priceCents: 96000, available: true, stockTracking: true, stockQuantity: 50, attributes: {} }] },
  { id: "21db2b3d-9c25-50bf-890e-4dd61cb5c83c", slug: "kokulu-beyaz-lilyum-tasarim-aranjmani-mo29wp7z", title: "Kokulu Beyaz Lilyum Tasarım Aranjmanı", priceCents: 124900, compareAtCents: 159900, media: [{ ...image("products/21db2b3d-9c25-50bf-890e-4dd61cb5c83c/927050b0-da8f-863e-8ece-76ae32d30832.webp", "Kokulu Beyaz Lilyum"), mediaType: "image/webp", id: "927050b0-da8f-463e-8ece-76ae32d30832", productId: "21db2b3d-9c25-50bf-890e-4dd61cb5c83c", sortOrder: 0 }], currency: "TRY", status: "active", available: true, variants: [{ id: "11111111-1111-4111-8111-111111111111", title: "Standart", sku: "QA", priceCents: 96000, available: true, stockTracking: true, stockQuantity: 50, attributes: {} }] },
];
export const products = seedProducts.map(product => ({ ...product, variants: product.variants.map(variant => ({ ...variant, priceCents: product.priceCents })) }));
const base = buildDefaultStarterPresentation({ name: "Lilyum Flora Ordu" });
const logo = image("design/c9c0df33-d646-59a4-ba36-a538b32d2a31.jpg", "Lilyum Flora logosu");
export const presentation: PublicStarterThemePresentationV3 = {
  ...base, logo, supportEmail: "destek@lilyumflora.net", announcement: { items: ["Ordu İçerisine 60 Dakika İçinde Teslim"] },
  navigation: { items: ["Lilyumlar", "Güller", "Orkideler", "Kutuda Güller", "Buketler", "Saksı Bitkileri"].map((name,index) => ({ name, slug: ["lilyumlar", "guller", "orkideler", "kutuda-guller", "buketler", "saksi-bitkileri"][index], children: [] })) },
  sections: [
    { kind: "banner", layout: "single", autoplay: false, presentation: "image_only", slides: [{ slideId: "qa", enabled: true, headline: "Lilyum Flora Ordu", body: "", desktopImage: image("storefront/hero/e89e5b56-0c5a-5a96-b33d-4daf6234c84c.jpg", "Lilyum Flora banner 1"), mobileImage: null, destination: "/products" }] },
    { kind: "category_grid", heading: "Koleksiyonlarımız", layout: "duo", items: [
      { name: "Lilyumlar", slug: "lilyumlar", image: image("storefront/category/ff72d131-f251-5fcb-92df-601d3fd1117a.webp", "Lilyumlar") },
      { name: "Orkideler", slug: "orkideler", image: image("storefront/category/38dea7f7-ee2a-50de-9793-1f430e3af96b.png", "Orkideler") },
      { name: "Kutuda Güller", slug: "kutuda-guller", image: image("storefront/category/0e00ab0c-1aff-5175-a987-128d470bbddc.jpg", "Kutuda Güller") },
      { name: "Saksı Bitkileri", slug: "saksi-bitkileri", image: image("storefront/category/3ade2b3c-11d6-522d-8cc0-ead71d1baff8.jpg", "Saksı Bitkileri") },
    ] }, { kind: "product_row", key: "selected", heading: "Lilyumlar", source: "manual", limit: 4 },
  ],
  footer: { tone: "dark", social: [{ network: "instagram", url: "https://www.instagram.com/lilyumflora.ordu/" }], newsletter: { enabled: false, heading: "", body: "", consentLabel: "" }, groups: [{ heading: "Bilgi", links: [{ label: "Hakkımızda", destination: "/pages/hakkimizda" }, { label: "İletişim", destination: "/pages/iletisim" }, { label: "SSS", destination: "/pages/sss" }] }, { heading: "Politikalar", links: [{ label: "KVKK", destination: "/policies/kvkk" }, { label: "İade & Değişim", destination: "/policies/returns-exchanges" }] }] },
};
const font = { family: "Poppins", category: "sans-serif", availableWeights: ["400", "500", "600", "700"], source: "google" } as const;
export const design: PublicStorefrontDesign = { schemaVersion: 2, publicationVersion: 2, publishedAt: "2026-10-03T00:00:00Z", brand: { logo, favicon: null, primaryColor: "#FF5A00", accentColor: "#171717", backgroundColor: "#FFFFFF", textColor: "#171717", fontFamily: "inter" }, hero: { enabled: false, slides: [] }, announcement: { enabled: true, items: ["Ordu İçerisine 60 Dakika İçinde Teslim"], icon: "none", speed: "normal", direction: "left", animation: "continuous" }, promotion: { enabled: false, headline: "", body: "", destination: null, startsAt: null, endsAt: null }, typography: { headingFont: font, bodyFont: font, headingWeight: "700", bodyWeight: "400", headingSizePx: 40, bodySizePx: 16 } };
export const storefront: PublicStorefront = { schemaVersion: 2, id: LILYUM_STOREFRONT_ID, name: "Lilyum Flora Ordu", slug: "lilyum-flora", hostname: "lilyumflora.net", primaryHostname: "lilyumflora.net", canonicalUrl: "https://lilyumflora.net", currency: "TRY", locale: "tr", themeKey: "starter", presentation };
