import assert from 'node:assert/strict';
import test from 'node:test';
import {createDefaultStoreEngagementConfig} from '../../../saas-contracts/src/store-engagement/index.ts';
import type {TenantContext} from '@celebix/saas-contracts';
const id='21500000-0000-4000-8000-000000000001',now=new Date('2026-10-04T18:00:00.000Z');
const campaign={id,kind:'popup',name:'Hoş geldiniz',enabled:true,version:1,config:createDefaultStoreEngagementConfig(),updatedAt:now.toISOString()};
const context={schemaVersion:1,requestId:'test',principal:{id,issuer:'https://test.invalid',subject:'test'},store:{id,slug:'test',status:'active'},membership:{id,role:'store_owner',status:'active'},entitlements:{schemaVersion:1,planId:id,planCode:'starter',version:1,status:'active',features:['catalog'],limits:{products:10,staff:1,storageBytes:100},validFrom:'2026-01-01T00:00:00.000Z'},locale:'tr-TR'} as TenantContext;
async function api(){const value=await import('./index.ts').catch(()=>({}));assert.equal(typeof (value as any).PostgresPublicStoreEngagementRepository,'function','repository must exist');return value as any;}
const options=(pool:any,role='celebix_saas_host_resolver')=>({pool,role,timeouts:{poolCheckoutMs:1000,statementMs:1000,lockMs:1000,idleTransactionMs:1000}});
function setup(payload:unknown,outcome='ok',failCommit=false){const calls:{text:string;values?:readonly unknown[]}[]=[],released:boolean[]=[];let connections=0;const pool={connect:async()=>{const connection=connections++;return {query:async(text:string,values?:readonly unknown[])=>{calls.push({text,values});if(text==='COMMIT'&&failCommit&&connection===0)throw Error('connection lost');return {rowCount:1,rows:text.includes('FROM saas.store_engagement_')?[{outcome:text.includes('operation_get')?'replayed':outcome,result_payload:payload}]:[]};},release(destroy=false){released.push(destroy);}};}};return {pool,calls,released};}
test('capture normalizes contacts and binds only host/cart authority; rejects forged identity before checkout',async()=>{const a=await api(),s=setup({contactCaptured:true,couponCode:'WELCOME'},'captured'),r=new a.PostgresPublicStoreEngagementRepository(options(s.pool));const base={hostname:'store.example.com',cartTokenDigest:'a'.repeat(64),now,operationId:id,campaignId:id,email:' PERSON@Example.COM ',marketingConsent:false};assert.deepEqual(await r.capture(base),{contactCaptured:true,couponCode:'WELCOME'});const call=s.calls.find(x=>x.text.includes('contact_capture('));assert.equal(call?.values?.[5],'person@example.com');assert.equal(s.calls.some(x=>x.text==='SET LOCAL ROLE celebix_saas_host_resolver'),true);s.calls.length=0;await assert.rejects(r.capture({...base,customerId:id}));assert.equal(s.calls.length,0);});
test('uncertain COMMIT destroys original connection and recovers exact operation without second write',async()=>{const a=await api(),s=setup(campaign,'saved',true),r=new a.PostgresStoreEngagementAdminRepository(options(s.pool,'celebix_saas_app'));assert.deepEqual(await r.save({tenantContext:context,now,operationId:id,kind:'popup',name:campaign.name,enabled:true,config:campaign.config}),campaign);assert.equal(s.calls.filter(x=>x.text.includes('campaign_save(')).length,1);assert.equal(s.calls.filter(x=>x.text.includes('admin_operation_get(')).length,1);assert.deepEqual(s.released,[true,false]);const write=s.calls.find(x=>x.text.includes('campaign_save(')),read=s.calls.find(x=>x.text.includes('admin_operation_get('));assert.equal(write?.values?.[8],read?.values?.[8]);});
test('failed operation rolls back, typed conflict preserves retry and no recovery query',async()=>{const a=await api(),s=setup(null,'version_conflict'),r=new a.PostgresStoreEngagementAdminRepository(options(s.pool,'celebix_saas_app'));await assert.rejects(r.save({tenantContext:context,now,operationId:id,campaignId:id,expectedVersion:1,kind:'popup',name:campaign.name,enabled:true,config:campaign.config}),(e:any)=>e.code==='version_conflict');assert.equal(s.calls.some(x=>x.text==='ROLLBACK'),true);assert.equal(s.calls.some(x=>x.text.includes('operation_get(')),false);});
test('public settings read uses read-only transaction and rejects invalid resolved image',async()=>{const a=await api(),s=setup({popups:[{...campaign,imageUrl:'javascript:alert(1)',couponCode:null}],cartCapture:null}),r=new a.PostgresPublicStoreEngagementRepository(options(s.pool));await assert.rejects(r.publicSettings({hostname:'store.example.com',now}));assert.equal(s.calls.some(x=>x.text==='BEGIN READ ONLY'),true);assert.throws(()=>new a.PostgresPublicStoreEngagementRepository(options(s.pool,'celebix_saas_app')));});
test('capture conflicts commit only the native durable quota and return typed error',async()=>{const a=await api(),s=setup(null,'contact_conflict'),r=new a.PostgresPublicStoreEngagementRepository(options(s.pool));await assert.rejects(r.capture({hostname:'store.example.com',cartTokenDigest:'a'.repeat(64),now,operationId:id,campaignId:id,email:'person@example.com',marketingConsent:false}),(e:any)=>e.code==='contact_conflict');assert.equal(s.calls.some(x=>x.text==='COMMIT'),true);assert.equal(s.calls.some(x=>x.text==='ROLLBACK'),false);});
test('popup deletion recovers an uncertain commit with the exact operation without deleting twice',async()=>{
 const a=await api(),receipt={campaignId:id,deleted:true},s=setup(receipt,'saved',true),r=new a.PostgresStoreEngagementAdminRepository(options(s.pool,'celebix_saas_app'));
 assert.equal(typeof r.deletePopup,'function','popup deletion must be a durable repository operation');
 assert.deepEqual(await r.deletePopup({tenantContext:context,now,operationId:id,campaignId:id,expectedVersion:3}),receipt);
 const calls=s.calls.filter(x=>x.text.includes('popup_delete('));assert.equal(calls.length,1);
 assert.deepEqual(calls[0]?.values?.slice(9),[id,3]);
 const recovery=s.calls.find(x=>x.text.includes('admin_operation_get('));assert.equal(recovery?.values?.[7],id);assert.equal(recovery?.values?.[8],calls[0]?.values?.[8]);
 assert.deepEqual(s.released,[true,false]);
});
test('popup deletion rejects forged scope and invalid versions before connecting and rejects unrelated receipts',async()=>{
 const a=await api(),s=setup({campaignId:'21500000-0000-4000-8000-000000000002',deleted:true},'saved'),r=new a.PostgresStoreEngagementAdminRepository(options(s.pool,'celebix_saas_app'));
 assert.equal(typeof r.deletePopup,'function');const input={tenantContext:context,now,operationId:id,campaignId:id,expectedVersion:1};
 for(const value of[{...input,storeId:id},{...input,expectedVersion:0},{...input,campaignId:'invalid'}])await assert.rejects(r.deletePopup(value));
 assert.equal(s.calls.length,0);await assert.rejects(r.deletePopup(input),(error:any)=>error.code==='unavailable');
});
