import {createHash} from 'node:crypto';
import type {TenantContext} from '@celebix/saas-contracts';
import {parseStoreEngagementCampaign,parseStoreEngagementConfig,parseStoreEngagementPublicSettings,parseStoreEngagementCaptureRequest,parseStoreEngagementCaptureResult,parseStoreEngagementDeleteResult,storeEngagementUuid,type StoreEngagementCampaign,type StoreEngagementCampaignKind,type StoreEngagementConfig,type StoreEngagementPublicSettings,type StoreEngagementCaptureResult,type StoreEngagementDeleteResult} from '../../../saas-contracts/src/store-engagement/index.ts';
import {catalogAuthority} from '../catalog/validation.ts';
import {acquirePostgresClient,type PostgresPoolLike,type PostgresTimeoutOptions} from '../postgres/pool.ts';

export type StoreEngagementRepositoryOptions=Readonly<{pool:PostgresPoolLike;role:'celebix_saas_app'|'celebix_saas_host_resolver';timeouts:PostgresTimeoutOptions}>;
export type StoreEngagementSaveInput=Readonly<{tenantContext:TenantContext;now:Date;operationId:string;campaignId?:string;expectedVersion?:number;kind:StoreEngagementCampaignKind;name:string;enabled:boolean;config:StoreEngagementConfig}>;
export type StoreEngagementCaptureInput=Readonly<{hostname:string;cartTokenDigest:string;now:Date;operationId:string;campaignId:string;email?:string;phone?:string;marketingConsent:boolean}>;
export type StoreEngagementDeleteInput=Readonly<{tenantContext:TenantContext;now:Date;operationId:string;campaignId:string;expectedVersion:number}>;
export interface StoreEngagementAdminRepository{list(input:Readonly<{tenantContext:TenantContext;now:Date}>):Promise<readonly StoreEngagementCampaign[]>;save(input:StoreEngagementSaveInput):Promise<StoreEngagementCampaign>;deletePopup(input:StoreEngagementDeleteInput):Promise<StoreEngagementDeleteResult>}
export interface PublicStoreEngagementRepository{publicSettings(input:Readonly<{hostname:string;now:Date}>):Promise<StoreEngagementPublicSettings>;capture(input:StoreEngagementCaptureInput):Promise<StoreEngagementCaptureResult>}
export const STORE_ENGAGEMENT_ERROR_CODES=['invalid_input','unauthenticated','store_inactive','membership_denied','feature_not_enabled','durable_authority_invalid','role_denied','not_found','invalid_reference','promotion_unavailable','version_conflict','operation_mismatch','operation_not_found','contact_conflict','rate_limited','limit_exceeded','cart_unavailable','campaign_unavailable','unavailable','commit_uncertain'] as const;
export type StoreEngagementErrorCode=typeof STORE_ENGAGEMENT_ERROR_CODES[number];
export class StoreEngagementRepositoryError extends Error{constructor(readonly code:StoreEngagementErrorCode){super(`store_engagement_${code}`);this.name='StoreEngagementRepositoryError';}}
function fail(code:StoreEngagementErrorCode='invalid_input'):never{throw new StoreEngagementRepositoryError(code);}
function exact(value:unknown,required:readonly string[],optional:readonly string[]=[]){if(typeof value!=='object'||value===null||Array.isArray(value))fail();const row=value as Record<string,unknown>,allowed=new Set([...required,...optional]);if(required.some(x=>!Object.hasOwn(row,x))||Object.keys(row).some(x=>!allowed.has(x)))fail();return row;}
function host(value:unknown){if(typeof value!=='string'||value!==value.toLowerCase()||value.length>253||!/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/u.test(value))fail();return value;}
function date(value:unknown){if(!(value instanceof Date)||!Number.isFinite(value.getTime()))fail();return new Date(value.getTime());}
function fingerprint(value:unknown):string{function sorted(x:unknown):unknown{if(Array.isArray(x))return x.map(sorted);if(x&&typeof x==='object')return Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b,'en')).map(([k,v])=>[k,sorted(v)]));return x;}return createHash('sha256').update(JSON.stringify(sorted(value))).digest('hex');}
type Call=Readonly<{name:string;args:readonly unknown[];casts:readonly string[];commitErrors?:readonly StoreEngagementErrorCode[]}>;
class Repository{
 constructor(protected readonly options:StoreEngagementRepositoryOptions,role:StoreEngagementRepositoryOptions['role']){if(options.role!==role||typeof options.pool?.connect!=='function'||Object.keys(options.timeouts??{}).length!==4||Object.values(options.timeouts).some(x=>!Number.isSafeInteger(x)||x<1||x>60000))fail('unavailable');}
 private async transaction(call:Call,readOnly:boolean):Promise<unknown>{const client=await acquirePostgresClient(this.options.pool,this.options.timeouts.poolCheckoutMs);let began=false,committing=false,destroy=false;try{await client.query(readOnly?'BEGIN READ ONLY':'BEGIN');began=true;for(const[key,value]of [['statement_timeout',this.options.timeouts.statementMs],['lock_timeout',this.options.timeouts.lockMs],['idle_in_transaction_session_timeout',this.options.timeouts.idleTransactionMs]] as const)await client.query('SELECT pg_catalog.set_config($1,$2,true)',[key,`${value}ms`]);await client.query(`SET LOCAL ROLE ${this.options.role}`);const result=await client.query(`SELECT outcome,result_payload FROM saas.${call.name}(${call.casts.map((cast,i)=>`$${i+1}::${cast}`).join(',')})`,[...call.args]);if(result.rowCount!==1||result.rows.length!==1)fail('unavailable');const row=result.rows[0] as {outcome:unknown;result_payload:unknown};let deferredError:StoreEngagementRepositoryError|undefined;if(!['ok','saved','captured','replayed'].includes(row.outcome as string)){if(STORE_ENGAGEMENT_ERROR_CODES.includes(row.outcome as StoreEngagementErrorCode)){if(!readOnly&&call.commitErrors?.includes(row.outcome as StoreEngagementErrorCode))deferredError=new StoreEngagementRepositoryError(row.outcome as StoreEngagementErrorCode);else fail(row.outcome as StoreEngagementErrorCode);}else fail('unavailable');}committing=true;await client.query('COMMIT');committing=false;began=false;if(deferredError)throw deferredError;return row.result_payload;}catch(error){if(committing){destroy=true;throw new StoreEngagementRepositoryError(readOnly?'unavailable':'commit_uncertain');}if(began)try{await client.query('ROLLBACK');}catch{destroy=true;}if(error instanceof StoreEngagementRepositoryError)throw error;throw new StoreEngagementRepositoryError('unavailable');}finally{client.release(destroy||undefined);}}
 protected async read(call:Call){return this.transaction(call,true);}
 protected async write(call:Call,recovery:Call){try{return await this.transaction(call,false);}catch(error){if(!(error instanceof StoreEngagementRepositoryError)||error.code!=='commit_uncertain')throw error;try{return await this.read(recovery);}catch{throw new StoreEngagementRepositoryError('commit_uncertain');}}}
}
const authorityCasts=['uuid','uuid','uuid','uuid','text','bigint','timestamptz'] as const;
function authority(context:TenantContext,now:Date){try{const a=catalogAuthority(context,now);return [a.storeId,a.principalId,a.membershipId,a.planId,a.planCode,a.planVersion,a.now] as const;}catch(error){const code=(error as {code?:StoreEngagementErrorCode}).code;if(code&&STORE_ENGAGEMENT_ERROR_CODES.includes(code))fail(code);fail('invalid_input');}}
export class PostgresStoreEngagementAdminRepository extends Repository implements StoreEngagementAdminRepository{
 constructor(options:StoreEngagementRepositoryOptions){super(options,'celebix_saas_app');}
 async list(input:Readonly<{tenantContext:TenantContext;now:Date}>){exact(input,['tenantContext','now']);const args=authority(input.tenantContext,input.now),value=await this.read({name:'store_engagement_campaign_list',args,casts:authorityCasts});if(!Array.isArray(value)||value.length>21)fail('unavailable');try{return Object.freeze(value.map(parseStoreEngagementCampaign));}catch{fail('unavailable');}}
 async save(input:StoreEngagementSaveInput){exact(input,['tenantContext','now','operationId','kind','name','enabled','config'],['campaignId','expectedVersion']);const a=authority(input.tenantContext,input.now);let operationId,config,campaignId:string|null=null;try{operationId=storeEngagementUuid(input.operationId);config=parseStoreEngagementConfig(input.config);if(input.campaignId!==undefined)campaignId=storeEngagementUuid(input.campaignId);}catch{fail();}if(!['popup','cart_capture'].includes(input.kind)||typeof input.enabled!=='boolean'||typeof input.name!=='string'||input.name!==input.name.trim()||input.name.length<1||input.name.length>160||/[\u0000-\u001f\u007f-\u009f]/u.test(input.name)||(campaignId===null)!==(input.expectedVersion===undefined)||input.expectedVersion!==undefined&&(!Number.isSafeInteger(input.expectedVersion)||input.expectedVersion<1))fail();const f=fingerprint({principalId:a[1],campaignId,expectedVersion:input.expectedVersion??null,kind:input.kind,name:input.name,enabled:input.enabled,config});const value=await this.write({name:'store_engagement_campaign_save',args:[...a,operationId,f,campaignId,input.expectedVersion??null,input.kind,input.name,input.enabled,JSON.stringify(config)],casts:[...authorityCasts,'uuid','text','uuid','bigint','text','text','boolean','jsonb']},{name:'store_engagement_admin_operation_get',args:[...a,operationId,f],casts:[...authorityCasts,'uuid','text']});try{return parseStoreEngagementCampaign(value);}catch{fail('unavailable');}}
 async deletePopup(input:StoreEngagementDeleteInput){
  exact(input,['tenantContext','now','operationId','campaignId','expectedVersion']);const a=authority(input.tenantContext,input.now);let operationId,campaignId;
  try{operationId=storeEngagementUuid(input.operationId);campaignId=storeEngagementUuid(input.campaignId);}catch{fail();}
  if(!Number.isSafeInteger(input.expectedVersion)||input.expectedVersion<1)fail();
  const f=fingerprint({principalId:a[1],action:'delete_popup',campaignId,expectedVersion:input.expectedVersion});
  const value=await this.write({name:'store_engagement_popup_delete',args:[...a,operationId,f,campaignId,input.expectedVersion],casts:[...authorityCasts,'uuid','text','uuid','bigint']},{name:'store_engagement_admin_operation_get',args:[...a,operationId,f],casts:[...authorityCasts,'uuid','text']});
  try{const result=parseStoreEngagementDeleteResult(value);if(result.campaignId!==campaignId)fail('unavailable');return result;}catch{fail('unavailable');}
 }
}
export class PostgresPublicStoreEngagementRepository extends Repository implements PublicStoreEngagementRepository{
 constructor(options:StoreEngagementRepositoryOptions){super(options,'celebix_saas_host_resolver');}
 async publicSettings(input:Readonly<{hostname:string;now:Date}>){exact(input,['hostname','now']);const value=await this.read({name:'store_engagement_public_settings',args:[host(input.hostname),date(input.now)],casts:['text','timestamptz']});try{return parseStoreEngagementPublicSettings(value);}catch{fail('unavailable');}}
 async capture(input:StoreEngagementCaptureInput){exact(input,['hostname','cartTokenDigest','now','operationId','campaignId','marketingConsent'],['email','phone']);const hostname=host(input.hostname),now=date(input.now);if(typeof input.cartTokenDigest!=='string'||!/^[a-f0-9]{64}$/u.test(input.cartTokenDigest))fail();let contact;try{contact=parseStoreEngagementCaptureRequest({operationId:input.operationId,campaignId:input.campaignId,marketingConsent:input.marketingConsent,...(input.email===undefined?{}:{email:input.email}),...(input.phone===undefined?{}:{phone:input.phone})});}catch{fail();}const f=fingerprint(contact);const value=await this.write({name:'email_marketing_contact_capture',commitErrors:['invalid_input','contact_conflict','rate_limited','campaign_unavailable','promotion_unavailable'],args:[hostname,input.cartTokenDigest,now,contact.operationId,contact.campaignId,contact.email??null,contact.phone??null,contact.marketingConsent,f],casts:['text','text','timestamptz','uuid','uuid','text','text','boolean','text']},{name:'store_engagement_public_operation_get',args:[hostname,input.cartTokenDigest,now,contact.operationId,f],casts:['text','text','timestamptz','uuid','text']});try{return parseStoreEngagementCaptureResult(value);}catch{fail('unavailable');}}
}
