import assert from 'node:assert/strict';
import test from 'node:test';
import type { TenantContext } from '@celebix/saas-contracts';
const id = '22600000-0000-4000-8000-000000000001', now = new Date('2026-10-10T00:00:00.000Z');
const context = { schemaVersion: 1, requestId: 'test', principal: { id, issuer: 'https://test.invalid', subject: 'test' }, store: { id, slug: 'test', status: 'active' }, membership: { id, role: 'store_owner', status: 'active' }, entitlements: { schemaVersion: 1, planId: id, planCode: 'starter', version: 1, status: 'active', features: ['catalog'], limits: { products: 10, staff: 1, storageBytes: 100 }, validFrom: '2026-01-01T00:00:00.000Z' }, locale: 'tr-TR' } as TenantContext;
async function api() { const a = await import('./index.ts').catch(() => ({})); assert.equal(typeof (a as any).PostgresPublicLuckyWheelRepository, 'function', 'wheel repository must exist'); return a as any; }
const options = (pool: any, role = 'celebix_saas_host_resolver') => ({ pool, role, timeouts: { poolCheckoutMs: 1000, statementMs: 1000, lockMs: 1000, idleTransactionMs: 1000 } });
function setup(payload: unknown, outcome = 'ok', uncertain = false) { const calls: {
    text: string;
    values?: readonly unknown[];
}[] = [], released: boolean[] = []; let connections = 0; return { calls, released, pool: { connect: async () => { const n = connections++; return { query: async (text: string, values?: readonly unknown[]) => { calls.push({ text, values }); if (text === 'COMMIT' && uncertain && n === 0)
                throw Error('person@example.com SECRET'); return { rowCount: 1, rows: text.includes('FROM saas.lucky_wheel_') ? [{ outcome, result_payload: payload }] : [] }; }, release(destroy = false) { released.push(destroy); } }; } } }; }
const rule = { schemaVersion: 1, benefit: { kind: 'percentage', percentageBps: 500 }, targets: { mode: 'all', include: [], exclude: [] }, audience: { mode: 'everyone' }, trigger: { kind: 'code', codes: ['W-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'] }, schedule: { timezone: 'Europe/Istanbul' }, limits: { totalUsage: null, perCustomerUsage: null, budgetMinor: null, orderMaximumMinor: null }, conditions: { minimumBasketMinor: 0, minimumQuantity: 0, minimumProductQuantity: 0, salesChannels: ['storefront'] }, combinationPolicy: { kind: 'none' }, priority: 1, marginPolicy: { kind: 'warn' }, progressMessagePolicy: { enabled: false } };
const result = { operationId: id, campaignId: id, campaignVersion: 1, awardId: id, prizeId: id, label: '%5 indirim', couponCode: 'W-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', expiresAt: '2026-10-11T00:00:00.000Z', awardedAt: now.toISOString(), repeatEligibleAt: '2026-10-17T00:00:00.000Z', ruleDocument: rule, couponStatus: 'active' };
const spin = { hostname: 'store.example.com', visitorDigest: 'a'.repeat(64), now, operationId: id, campaignId: id, expectedVersion: 1, email: ' Person@Example.COM ', marketingConsent: false };
test('spin binds trusted host and visitor, normalizes contact, rejects forged source before checkout', async () => { const a = await api(), s = setup(result), r = new a.PostgresPublicLuckyWheelRepository(options(s.pool)); assert.deepEqual(await r.spin(spin), result); assert.equal(s.calls.some(x => x.text === 'SET LOCAL ROLE celebix_saas_host_resolver'), true); assert.equal(s.calls.find(x => x.text.includes('spin_v1('))?.values?.[6], 'person@example.com'); s.calls.length = 0; for (const x of [{ ...spin, source: 'wheel' }, { ...spin, storeId: id }, { ...spin, visitorDigest: 'bad' }, { ...spin, hostname: 'Store.example.com' }])
    await assert.rejects(r.spin(x)); assert.equal(s.calls.length, 0); });
test('uncertain spin commit recovers one operation with fingerprint without second issuance', async () => { const a = await api(), s = setup(result, 'ok', true), r = new a.PostgresPublicLuckyWheelRepository(options(s.pool)); assert.deepEqual(await r.spin(spin), result); assert.equal(s.calls.filter(x => x.text.includes('spin_v1(')).length, 1); const write = s.calls.find(x => x.text.includes('spin_v1(')), recover = s.calls.find(x => x.text.includes('operation_get_v1(')); assert.equal(write?.values?.[9], recover?.values?.[4]); assert.deepEqual(s.released, [true, false]); });
test('wrong award operation and unexpected PII responses become safe unavailable', async () => { const a = await api(); for (const payload of [{ ...result, operationId: '22600000-0000-4000-8000-000000000002' }, { ...result, email: 'person@example.com' }]) {
    const s = setup(payload), r = new a.PostgresPublicLuckyWheelRepository(options(s.pool));
    await assert.rejects(r.spin(spin), (e: any) => e.code === 'unavailable' && !e.message.includes('person@'));
} });
test('result recovery is read-only and scoped to campaign plus visitor', async () => { const a = await api(), s = setup(null), r = new a.PostgresPublicLuckyWheelRepository(options(s.pool)); assert.equal(await r.result({ hostname: spin.hostname, visitorDigest: spin.visitorDigest, now, campaignId: id }), null); assert.equal(s.calls.some(x => x.text === 'BEGIN READ ONLY'), true); assert.deepEqual(s.calls.find(x => x.text.includes('result_v1('))?.values, [spin.hostname, spin.visitorDigest, now, id, null]); assert.throws(() => new a.PostgresPublicLuckyWheelRepository(options(s.pool, 'celebix_saas_app'))); });
test('admin validates authority and mutation receipts, fingerprint includes revoke action', async () => { const a = await api(), s = setup({ campaignId: id, revoked: 2, held: 1 }), r = new a.PostgresLuckyWheelAdminRepository(options(s.pool, 'celebix_saas_app')); assert.deepEqual(await r.revokeCoupons({ tenantContext: context, now, operationId: id, campaignId: id, expectedVersion: 2 }), { campaignId: id, revoked: 2, held: 1 }); assert.equal(s.calls.some(x => x.text === 'SET LOCAL ROLE celebix_saas_app'), true); s.calls.length = 0; await assert.rejects(r.revokeCoupons({ tenantContext: context, now, operationId: id, campaignId: id, expectedVersion: 0 })); assert.equal(s.calls.length, 0); });
test('managed promotion index includes immutable old and deleted sources and uses bounded cursor authority', async () => { const a = await api(), payload = { items: [{ promotionId: id, campaignId: id, campaignName: 'Çark', issued: 3, used: 1, deleted: true }], hasMore: false, nextCursor: null }, s = setup(payload), r = new a.PostgresLuckyWheelAdminRepository(options(s.pool, 'celebix_saas_app')); assert.equal(typeof r.managedPromotions, 'function'); assert.deepEqual(await r.managedPromotions({ tenantContext: context, now, limit: 20 }), payload); assert.deepEqual(s.calls.find(x => x.text.includes('managed_promotions_v1('))?.values?.slice(7), [20, null, null]); s.calls.length = 0; await assert.rejects(r.managedPromotions({ tenantContext: context, now, cursor: 'forged' })); assert.equal(s.calls.length, 0); });
test('rejected spin commits only native attempt limit and returns a safe typed error', async () => { const a = await api(), s = setup(null, 'rate_limited'), r = new a.PostgresPublicLuckyWheelRepository(options(s.pool)); await assert.rejects(r.spin(spin), (e: any) => e.code === 'rate_limited'); assert.equal(s.calls.some(x => x.text === 'COMMIT'), true); assert.equal(s.calls.some(x => x.text === 'ROLLBACK'), false); });
test('combined list preserves the existing 200 legacy rows alongside native campaigns', async () => {
    const a = await api(), payload = Array.from({length: 101}, (_, i) => ({id: `22600000-0000-4000-8000-${String(i + 1).padStart(12, '0')}`, name: 'Historical wheel', enabled: false, status: 'archived', version: 1, config: null, prizes: [], blockedReason: 'legacy_configuration', stats: {issued: 0, used: 0, discountMinor: 0, revenueMinor: 0, currency: 'TRY'}, createdAt: now.toISOString(), updatedAt: now.toISOString(), legacy: true, legacyConfig: {prizeLabels: ['Historical text']}})), s = setup(payload), r = new a.PostgresLuckyWheelAdminRepository(options(s.pool, 'celebix_saas_app'));
    assert.deepEqual(await r.list({tenantContext: context, now}), payload);
});
test('constructor captures fixed role and exact bounded timeouts before options can drift', async () => {
    const a = await api(), s = setup({campaign: null}), supplied = options(s.pool), r = new a.PostgresPublicLuckyWheelRepository(supplied);
    supplied.role = 'celebix_saas_app'; supplied.timeouts.statementMs = 0;
    assert.deepEqual(await r.publicSettings({hostname: spin.hostname, now}), {campaign: null});
    assert.equal(s.calls.some(x => x.text === 'SET LOCAL ROLE celebix_saas_host_resolver'), true);
    assert.equal(s.calls.find(x => x.values?.[0] === 'statement_timeout')?.values?.[1], '1000ms');
    assert.throws(() => new a.PostgresPublicLuckyWheelRepository({...options(s.pool), timeouts: {poolCheckoutMs: 1000, statementMs: 1000, lockMs: 1000, unknown: 1000}}));
});
