import {parseLuckyWheelConfig,parseLuckyWheelCampaign,parseLuckyWheelHistoryResult,parseLuckyWheelDeleteResult,parseLuckyWheelRevokeResult,parseLuckyWheelManagedPromotionIndex,type LuckyWheelConfig,type LuckyWheelCampaign,type LuckyWheelHistoryResult,type LuckyWheelDeleteResult,type LuckyWheelRevokeResult,type LuckyWheelManagedPromotionIndex} from '@celebix/saas-contracts';
export type LuckyWheelSaveInput=Readonly<{campaignId?:string;expectedVersion?:number;name:string;enabled:boolean;config:LuckyWheelConfig}>;
export type LuckyWheelMutationInput=Readonly<{campaignId:string;expectedVersion:number}>;
export type LuckyWheelPendingMutation=LuckyWheelMutationInput & Readonly<{action:'delete'|'revoke-coupons'}>;
type Intent=Readonly<{action:'save';input:LuckyWheelSaveInput}>|Readonly<{action:'delete'|'revoke-coupons';input:LuckyWheelMutationInput}>;
type Fence=Intent & Readonly<{fingerprint:string;operationId:string}>;
type Storage=Pick<globalThis.Storage,'getItem'|'setItem'|'removeItem'>;
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const MESSAGES:Readonly<Record<string,string>>={invalid_input:'Bilgileri kontrol edin.',unauthenticated:'Oturumunuz sona erdi. Yeniden giriş yapın.',membership_denied:'Bu işlem için yetkiniz yok.',origin_denied:'Güvenlik doğrulaması başarısız oldu.',store_inactive:'Mağaza şu anda etkin değil.',feature_not_enabled:'Bu araç planınızda etkin değil.',rate_limited:'Biraz sonra tekrar deneyin.',not_found:'Kayıt bulunamadı.',version_conflict:'Kayıt başka bir oturumda değişti. Formunuz korunuyor; güncel kaydı yükleyin.',operation_mismatch:'İşlem güvenle tekrarlanamadı.',active_campaign_conflict:'Mağazada başka bir açık çark var. Önce mevcut çarkı kapatın.',legacy_configuration:'Eski metin ödülleri gerçek kupona dönüştürülmez. Yeni çark oluşturun.',promotion_unavailable:'Bağlı indirim artık uygun değil.',invalid_reference:'Bağlı indirim kullanılamıyor.',campaign_unavailable:'Kampanya katılıma kapalı.',quota_exhausted:'Bir ödülün dağıtım sınırı doldu.',limit_exceeded:'Kampanya sınırına ulaştınız.',unresolved:'Önceki işlem sonucu belirsiz. Aynı işlemi doğrulayın.',storage_unavailable:'Tarayıcı kayıt güvencesi oluşturulamadı. Tarayıcı depolamasını açıp sayfayı yenileyin.',unavailable:'İşlem sonucu doğrulanamadı. Aynı bilgilerle tekrar deneyin.'};
export class LuckyWheelApiError extends Error{constructor(readonly code='unavailable',readonly status=503){super(MESSAGES[code]??MESSAGES.unavailable);this.name='LuckyWheelApiError'}}
function exact(value:unknown,required:readonly string[],optional:readonly string[]=[]):Record<string,unknown>{if(typeof value!=='object'||value===null||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)throw Error();const keys=Object.keys(value);if(required.some(k=>!Object.hasOwn(value,k))||keys.some(k=>![...required,...optional].includes(k)))throw Error();return value as Record<string,unknown>}
function canonical(value:unknown):string{if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>JSON.stringify(k)+':'+canonical(v)).join(',')+'}';return JSON.stringify(value)}
async function fingerprint(value:unknown){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(value)))),byte=>byte.toString(16).padStart(2,'0')).join('')}
function saveInput(value:unknown):LuckyWheelSaveInput{try{const row=exact(value,['name','enabled','config'],['campaignId','expectedVersion']);if(typeof row.name!=='string'||!row.name||row.name!==row.name.trim()||row.name.length>160||/[\u0000-\u001f\u007f-\u009f]/u.test(row.name)||typeof row.enabled!=='boolean'||(row.campaignId===undefined)!==(row.expectedVersion===undefined))throw Error();if(row.campaignId!==undefined)mutationInput({campaignId:row.campaignId,expectedVersion:row.expectedVersion});return{...(row.campaignId===undefined?{}:{campaignId:row.campaignId as string,expectedVersion:row.expectedVersion as number}),name:row.name,enabled:row.enabled,config:parseLuckyWheelConfig(row.config)}}catch{throw new LuckyWheelApiError('invalid_input',400)}}
function mutationInput(value:unknown):LuckyWheelMutationInput{try{const row=exact(value,['campaignId','expectedVersion']);if(typeof row.campaignId!=='string'||!UUID.test(row.campaignId)||!Number.isSafeInteger(row.expectedVersion)||(row.expectedVersion as number)<1)throw Error();return{campaignId:row.campaignId,expectedVersion:row.expectedVersion as number}}catch{throw new LuckyWheelApiError('invalid_input',400)}}
async function json(response:Response):Promise<unknown>{const length=response.headers.get('content-length');if(response.headers.get('content-type')?.split(';')[0]?.trim()!=='application/json'||(length!==null&&(!/^\d+$/.test(length)||Number(length)>1048576))||!response.body)throw new LuckyWheelApiError();const reader=response.body.getReader(),chunks:Uint8Array[]=[];let size=0;try{while(true){const next=await reader.read();if(next.done)break;size+=next.value.byteLength;if(size>1048576){await reader.cancel();throw Error()}chunks.push(next.value)}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes))}catch{throw new LuckyWheelApiError()}}
function responseError(status:number,value:unknown){let code='unavailable';try{const row=exact(value,['code']);const allowed=status===400?['invalid_input']:status===401?['unauthenticated']:status===403?['membership_denied','origin_denied','store_inactive','feature_not_enabled']:status===404?['not_found']:status===409?['version_conflict','operation_mismatch','active_campaign_conflict','legacy_configuration','promotion_unavailable','invalid_reference','campaign_unavailable','quota_exhausted','limit_exceeded']:status===429?['rate_limited']:[];if(typeof row.code==='string'&&allowed.includes(row.code))code=row.code}catch{}return new LuckyWheelApiError(code,status)}
export function createLuckyWheelApi(options:Readonly<{fetch?:typeof fetch;randomUUID?:()=>string;scope?:string;storage?:Storage}>={}){
 const fetcher=options.fetch??((url,init)=>fetch(url,init)),uuid=options.randomUUID??(()=>crypto.randomUUID());if(options.scope!==undefined&&!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(options.scope))throw new LuckyWheelApiError('invalid_input',400);
 const key=options.scope===undefined?undefined:`celebix.wheel.mutation.v1:${options.scope}`;let storage=options.storage,fence:Fence|undefined,storageFailed=false,pending=false;
 if(key){try{storage??=typeof window==='undefined'?undefined:window.sessionStorage;if(!storage&&typeof window!=='undefined')throw Error();const raw=storage?.getItem(key);if(raw){if(raw.length>24000)throw Error();const row=exact(JSON.parse(raw),['action','input','fingerprint','operationId']);if(!['save','delete','revoke-coupons'].includes(String(row.action))||typeof row.fingerprint!=='string'||!/^[a-f0-9]{64}$/.test(row.fingerprint)||typeof row.operationId!=='string'||!UUID.test(row.operationId))throw Error();fence={action:row.action,input:row.action==='save'?saveInput(row.input):mutationInput(row.input),fingerprint:row.fingerprint,operationId:row.operationId} as Fence}}catch{storageFailed=true}}
 function persist(value:Fence){if(storageFailed)throw new LuckyWheelApiError('storage_unavailable');try{if(key&&storage){const raw=JSON.stringify(value);storage.setItem(key,raw);if(storage.getItem(key)!==raw)throw Error()}fence=value}catch{storageFailed=true;throw new LuckyWheelApiError('storage_unavailable')}}
 function clear(){try{if(key&&storage){storage.removeItem(key);if(storage.getItem(key)!==null)throw Error()}fence=undefined}catch{storageFailed=true}}
 async function verify(){if(storageFailed)throw new LuckyWheelApiError('storage_unavailable');if(fence&&await fingerprint({action:fence.action,input:fence.input})!==fence.fingerprint){storageFailed=true;throw new LuckyWheelApiError('storage_unavailable')}}
 async function mutate<T>(intent:Intent,parser:(value:unknown)=>T):Promise<T>{if(pending)throw new LuckyWheelApiError('unresolved');pending=true;try{await verify();const hash=await fingerprint(intent);if(fence&&fence.fingerprint!==hash)throw new LuckyWheelApiError('unresolved');const operationId=fence?.operationId??uuid();if(!UUID.test(operationId))throw new LuckyWheelApiError('invalid_input',400);persist({...intent,fingerprint:hash,operationId} as Fence);const response=await fetcher('/api/discounts/lucky-wheel'+(intent.action==='save'?'':'/'+intent.action),{method:'POST',cache:'no-store',credentials:'same-origin',headers:{accept:'application/json','content-type':'application/json','idempotency-key':operationId},body:JSON.stringify(intent.input)});const value=await json(response);if(!response.ok){const error=responseError(response.status,value);if(!['unavailable','operation_mismatch'].includes(error.code))clear();throw error}const result=parser(value);clear();return result}catch(error){if(error instanceof LuckyWheelApiError)throw error;throw new LuckyWheelApiError()}finally{pending=false}}
 return Object.freeze({
  hasUnresolved:()=>Boolean(fence)||storageFailed,
  async pendingIntent():Promise<LuckyWheelSaveInput|null>{await verify();return fence?.action==='save'?fence.input:null},
  async pendingMutation():Promise<LuckyWheelPendingMutation|null>{await verify();return fence&&fence.action!=='save'?{action:fence.action,...fence.input}:null},
  async list(signal?:AbortSignal):Promise<readonly LuckyWheelCampaign[]>{try{const response=await fetcher('/api/discounts/lucky-wheel',{cache:'no-store',credentials:'same-origin',headers:{accept:'application/json'},signal});const value=await json(response);if(!response.ok)throw responseError(response.status,value);const rows=exact(value,['campaigns']).campaigns;if(!Array.isArray(rows)||rows.length>200)throw Error();const campaigns=rows.map(parseLuckyWheelCampaign);if(new Set(campaigns.map(c=>c.id)).size!==campaigns.length)throw Error();return campaigns}catch(error){if(error instanceof LuckyWheelApiError)throw error;throw new LuckyWheelApiError()}},
  async managedPromotions(input:Readonly<{limit?:number;cursor?:string|null}>={}):Promise<LuckyWheelManagedPromotionIndex>{
   const limit=input.limit??100,cursor=input.cursor??null;if(!Number.isSafeInteger(limit)||limit<1||limit>200||cursor!==null&&(typeof cursor!=='string'||cursor.length>200))throw new LuckyWheelApiError('invalid_input',400);
   try{const query=new URLSearchParams({limit:String(limit)});if(cursor)query.set('cursor',cursor);const response=await fetcher('/api/discounts/lucky-wheel/managed-promotions?'+query,{cache:'no-store',credentials:'same-origin',headers:{accept:'application/json'}}),value=await json(response);if(!response.ok)throw responseError(response.status,value);const result=parseLuckyWheelManagedPromotionIndex(exact(value,['managedPromotions']).managedPromotions);if(result.items.length>limit)throw Error();return result}catch(error){if(error instanceof LuckyWheelApiError)throw error;throw new LuckyWheelApiError()}
  },
  async history(campaignId:string):Promise<LuckyWheelHistoryResult>{if(!UUID.test(campaignId))throw new LuckyWheelApiError('invalid_input',400);try{const response=await fetcher(`/api/discounts/lucky-wheel/${campaignId}/history`,{cache:'no-store',credentials:'same-origin',headers:{accept:'application/json'}});const value=await json(response);if(!response.ok)throw responseError(response.status,value);return parseLuckyWheelHistoryResult(exact(value,['history']).history)}catch(error){if(error instanceof LuckyWheelApiError)throw error;throw new LuckyWheelApiError()}},
  save(raw:LuckyWheelSaveInput):Promise<LuckyWheelCampaign>{const input=saveInput(raw);return mutate({action:'save',input},value=>{const campaign=parseLuckyWheelCampaign(exact(value,['campaign']).campaign);if(campaign.legacy||campaign.name!==input.name||campaign.enabled!==input.enabled||canonical(campaign.config)!==canonical(input.config)||(input.campaignId?campaign.id!==input.campaignId||campaign.version!==input.expectedVersion!+1:campaign.version!==1))throw Error();return campaign})},
  deleteCampaign(raw:LuckyWheelMutationInput):Promise<LuckyWheelDeleteResult>{const input=mutationInput(raw);return mutate({action:'delete',input},value=>{const result=parseLuckyWheelDeleteResult(exact(value,['deletion']).deletion);if(result.campaignId!==input.campaignId)throw Error();return result})},
  revokeCoupons(raw:LuckyWheelMutationInput):Promise<LuckyWheelRevokeResult>{const input=mutationInput(raw);return mutate({action:'revoke-coupons',input},value=>{const result=parseLuckyWheelRevokeResult(exact(value,['revocation']).revocation);if(result.campaignId!==input.campaignId)throw Error();return result})},
 });
}
const clients=new Map<string,ReturnType<typeof createLuckyWheelApi>>();
export function scopedLuckyWheelApi(scope:string){let client=clients.get(scope);if(!client){client=createLuckyWheelApi({scope});clients.set(scope,client)}return client}
