import assert from 'node:assert/strict';
import test from 'node:test';
import {createLuckyWheelApi,LuckyWheelApiError} from './client.ts';
import {wheelFixture,WHEEL_ID,OP_ID} from './fixtures.ts';
const input=()=>({name:'Karşılama',enabled:true,config:wheelFixture().config!});
function storage(){const rows=new Map<string,string>();return{getItem:(k:string)=>rows.get(k)??null,setItem:(k:string,v:string)=>{rows.set(k,v)},removeItem:(k:string)=>{rows.delete(k)}}}
test('uncertain save retains exact form operation across reload and blocks changed intent',async()=>{const memory=storage(),calls:RequestInit[]=[];let attempts=0;const fetcher=async(_url:unknown,init?:RequestInit)=>{calls.push(init!);if(++attempts===1)throw Error('timeout');return Response.json({campaign:wheelFixture()})};const first=createLuckyWheelApi({storage:memory,scope:'fixture',fetch:fetcher as typeof fetch,randomUUID:()=>OP_ID});await assert.rejects(first.save(input()));assert.deepEqual(await first.pendingIntent(),input());const resumed=createLuckyWheelApi({storage:memory,scope:'fixture',fetch:fetcher as typeof fetch,randomUUID:()=>WHEEL_ID});await assert.rejects(resumed.save({...input(),name:'Başka'}),(e:unknown)=>e instanceof LuckyWheelApiError&&e.code==='unresolved');assert.equal(calls.length,1);await resumed.save(input());assert.equal(new Headers(calls[1].headers).get('idempotency-key'),OP_ID);assert.equal(resumed.hasUnresolved(),false)});
test('delete retains independent recovery and issued coupons preserved receipt is required',async()=>{const memory=storage();let count=0;const api=createLuckyWheelApi({storage:memory,scope:'fixture',randomUUID:()=>OP_ID,fetch:async()=>{if(++count===1)throw Error();return Response.json({deletion:{campaignId:WHEEL_ID,deleted:true,issuedCouponsPreserved:true}})}});const mutation={campaignId:WHEEL_ID,expectedVersion:1};await assert.rejects(api.deleteCampaign(mutation));assert.deepEqual(await api.pendingMutation(),{action:'delete',...mutation});await assert.rejects(api.revokeCoupons(mutation));assert.equal(count,1);await api.deleteCampaign(mutation);assert.equal(api.hasUnresolved(),false)});
test('known conflict clears mutation fence while original form remains available to caller',async()=>{const api=createLuckyWheelApi({randomUUID:()=>OP_ID,fetch:async()=>Response.json({code:'version_conflict'},{status:409})});const form=input();await assert.rejects(api.save(form),(e:unknown)=>e instanceof LuckyWheelApiError&&e.code==='version_conflict');assert.equal(api.hasUnresolved(),false);assert.equal(form.name,'Karşılama')});
