import assert from 'node:assert/strict';
import test from 'node:test';
import {createLuckyWheelHandlers} from './handler.ts';
import {wheelFixture,WHEEL_ID,OP_ID} from '../lucky-wheel-ui/fixtures.ts';
import type {ServerLuckyWheelRuntime} from '../server-lucky-wheel/runtime.ts';
const NOW=new Date('2026-10-10T10:00:00Z'), PATH='/api/discounts/lucky-wheel';
function harness(role='store_owner',overrides:Record<string,unknown>={}){
 const calls:unknown[]=[];const context={store:{id:WHEEL_ID,slug:'siora',status:'active'},membership:{role,status:'active'},entitlements:{status:'active',features:['promotions']}};
 const wheel={list:async(input:unknown)=>{calls.push(input);return[wheelFixture()]},save:async(input:unknown)=>{calls.push(input);return wheelFixture()},deleteCampaign:async(input:unknown)=>{calls.push(input);return{campaignId:WHEEL_ID,deleted:true,issuedCouponsPreserved:true}},history:async(input:unknown)=>{calls.push(input);return{items:[],hasMore:false}},revokeCoupons:async(input:unknown)=>{calls.push(input);return{campaignId:WHEEL_ID,revoked:0,held:0}},...overrides};
 const runtime={access:{panelOrigin:'https://panel.saas-staging.celebix.site',resolveCredential:async()=>({kind:'authenticated',tenantContext:context})},luckyWheel:wheel} as unknown as ServerLuckyWheelRuntime;
 return{calls,context,handlers:createLuckyWheelHandlers({resolveRuntime:async()=>runtime,now:()=>NOW,requestId:()=>OP_ID})};
}
function request(body?:unknown,suffix='',headers:HeadersInit={}){return new Request('http://internal:3400'+PATH+suffix,{method:body===undefined?'GET':'POST',headers:{cookie:`__Host-celebix_panel=v1.panel.current.${Buffer.alloc(32,1).toString('base64url')}`,origin:'https://panel.saas-staging.celebix.site','content-type':'application/json','idempotency-key':OP_ID,...headers},...(body===undefined?{}:{body:JSON.stringify(body)})})}
const input=()=>({name:'Karşılama',enabled:true,config:wheelFixture().config});
test('authenticated direct save preserves all fields and trusted scope',async()=>{const h=harness();const r=await h.handlers.save(request(input()));assert.equal(r.status,200);assert.deepEqual(await r.json(),{campaign:wheelFixture()});assert.deepEqual(h.calls,[{tenantContext:h.context,now:NOW,operationId:OP_ID,...input()}]);assert.equal(r.headers.get('cache-control'),'no-store')});
test('session origin role idempotency version and unknown fields reject before write',async()=>{const h=harness();for(const value of[{...input(),storeId:WHEEL_ID},{...input(),campaignId:WHEEL_ID},{...input(),expectedVersion:1},{...input(),campaignId:WHEEL_ID,expectedVersion:0}])assert.equal((await h.handlers.save(request(value))).status,400);assert.equal((await h.handlers.save(request(input(),'',{cookie:''}))).status,401);assert.equal((await h.handlers.save(request(input(),'',{origin:'https://evil.invalid'}))).status,403);assert.equal((await h.handlers.save(request(input(),'',{'idempotency-key':''}))).status,400);assert.equal((await harness('cashier').handlers.save(request(input()))).status,403);assert.equal(h.calls.length,0)});
test('delete and revoke are separate checked receipts with history retained',async()=>{const h=harness(), mutation={campaignId:WHEEL_ID,expectedVersion:1};assert.deepEqual(await(await h.handlers.deleteCampaign(request(mutation,'/delete'))).json(),{deletion:{campaignId:WHEEL_ID,deleted:true,issuedCouponsPreserved:true}});assert.deepEqual(await(await h.handlers.revokeCoupons(request(mutation,'/revoke-coupons'))).json(),{revocation:{campaignId:WHEEL_ID,revoked:0,held:0}});assert.equal((await h.handlers.history(request(undefined,`/${WHEEL_ID}/history`),WHEEL_ID)).status,200);assert.equal(h.calls.length,3)});
test('invalid or mismatched repository responses fail closed without leaking internals',async()=>{for(const override of[{save:async()=>({...wheelFixture(),id:'invalid'})},{deleteCampaign:async()=>({campaignId:OP_ID,deleted:true,issuedCouponsPreserved:true})},{history:async()=>({items:[],hasMore:false,contacts:['secret']})}]){const h=harness('store_owner',override);const r=override.save?await h.handlers.save(request(input())):override.deleteCampaign?await h.handlers.deleteCampaign(request({campaignId:WHEEL_ID,expectedVersion:1},'/delete')):await h.handlers.history(request(undefined,`/${WHEEL_ID}/history`),WHEEL_ID);assert.equal(r.status,503);assert.deepEqual(await r.json(),{code:'unavailable'})}});
