import { parseSaveSeoResourceRequest,parseSaveSeoSettingsRequest,parseSaveSeoLinkRequest,parseNotifySeoRequest,seoExact,seoKind,seoUuid, type SeoResource, type SeoSettings, type SeoOverview, type SeoLink, type SeoNotification } from '@celebix/saas-contracts';
import { acquirePostgresClient, type PostgresClientLike } from '../postgres/pool.ts';
import { authority } from '../merchant-content/validation.ts';
import { merchantAdminFingerprint } from '../merchant-admin/canonical.ts';
import { SEO_ERROR_CODES,SeoRepositoryError,type SeoErrorCode } from './errors.ts';
import type { SeoRepository,SeoAuthorityInput,SeoOperationInput,PostgresSeoRepositoryOptions,PublicSeoRepository,PostgresPublicSeoRepositoryOptions,SeoWorkerRepository,PostgresSeoWorkerRepositoryOptions } from './types.ts';
const A='$1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz';
function fail(code:SeoErrorCode='invalid_input'):never {throw new SeoRepositoryError(code);}
function checked<T>(parse:()=>T):T {try{return parse();}catch(e){if(e instanceof SeoRepositoryError)throw e;fail();}}
function date(v:unknown):Date {if(!(v instanceof Date)||Object.getPrototypeOf(v)!==Date.prototype||!Number.isFinite(v.getTime()))fail();return v;}
function hostname(v:unknown):string {if(typeof v!=='string'||v.length>253||!/^([a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/.test(v))fail();return v;}
function release(c:PostgresClientLike,destroy=false){try{c.release(destroy||undefined);}catch{}}
abstract class Base {
 protected options:PostgresSeoRepositoryOptions|PostgresPublicSeoRepositoryOptions|PostgresSeoWorkerRepositoryOptions;
 constructor(options:PostgresSeoRepositoryOptions|PostgresPublicSeoRepositoryOptions|PostgresSeoWorkerRepositoryOptions,role:string){checked(()=>{const r=seoExact(options,['pool','role','timeouts'],role==='celebix_saas_app'?['audit']:[]);if(r.role!==role||!r.pool||typeof (r.pool as {connect?:unknown}).connect!=='function'||role==='celebix_saas_app'&&typeof r.audit!=='function')fail();const t=seoExact(r.timeouts,['poolCheckoutMs','statementMs','lockMs','idleTransactionMs']);for(const n of Object.values(t))if(!Number.isSafeInteger(n)||(n as number)<1||(n as number)>60000)fail();});this.options={...options,timeouts:{...options.timeouts}};}
 protected async query(c:PostgresClientLike,text:string,values?:unknown[]){let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([c.query(text,values),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new SeoRepositoryError('unavailable')),this.options.timeouts.statementMs);})]);}finally{if(timer)clearTimeout(timer);}}
 protected async run<T>(text:string,values:unknown[],write=false):Promise<{payload:T;replayed:boolean}>{let c:PostgresClientLike;try{c=await acquirePostgresClient(this.options.pool,this.options.timeouts.poolCheckoutMs);}catch{fail('unavailable');}let terminal=false;try{await this.query(c,write?'BEGIN ISOLATION LEVEL READ COMMITTED':'BEGIN READ ONLY');for(const [key,n] of [['statement_timeout',this.options.timeouts.statementMs],['lock_timeout',this.options.timeouts.lockMs],['idle_in_transaction_session_timeout',this.options.timeouts.idleTransactionMs]] as const)await this.query(c,`SELECT pg_catalog.set_config('${key}',$1,true)`,[`${n}ms`]);await this.query(c,`SET LOCAL ROLE ${this.options.role}`);const result=await this.query(c,text,values);if(result.rowCount!==1||result.rows.length!==1)fail('unavailable');const row=result.rows[0]!;if(typeof row.outcome!=='string')fail('unavailable');if((SEO_ERROR_CODES as readonly string[]).includes(row.outcome))fail(row.outcome as SeoErrorCode);if(!['found','listed','saved','operation_replayed','finished','claimed'].includes(row.outcome))fail('unavailable');if(row.result_payload===null||typeof row.result_payload!=='object')fail('unavailable');const payload=row.result_payload as T;try{await this.query(c,'COMMIT');terminal=true;release(c);}catch{terminal=true;release(c,true);if(write){if('audit' in this.options){try{const p=this.options.audit({type:'seo_commit_unknown'});if(p)void p.catch(()=>undefined);}catch{}}fail('commit_unknown');}fail('unavailable');}return{payload,replayed:row.outcome==='operation_replayed'};}catch(e){if(!terminal){try{await this.query(c,'ROLLBACK');}catch{}release(c,true);}if(e instanceof SeoRepositoryError)throw e;fail('unavailable');}}
}
export class PostgresSeoRepository extends Base implements SeoRepository {
 constructor(options:PostgresSeoRepositoryOptions){super(options,'celebix_saas_app');}
 private args(input:SeoAuthorityInput,write=false){return checked(()=>{let a;try{a=authority(input.tenantContext,input.now,write);}catch(e){const code=(e as {code?:string}).code;fail((SEO_ERROR_CODES as readonly string[]).includes(code??'')?code as SeoErrorCode:code==='durable_authority_invalid'?'feature_not_enabled':'invalid_input');}return[a.storeId,a.principalId,a.membershipId,a.planId,a.planCode,a.planVersion,a.now];});}
 private async read<T>(input:SeoAuthorityInput,action:string,request:unknown={}):Promise<T>{return(await this.run<T>(`SELECT outcome,result_payload FROM saas.seo_admin_read(${A},$8::text,$9::jsonb)`,[...this.args(input),action,JSON.stringify(request)])).payload;}
 private async write<T>(input:SeoOperationInput,action:string,request:unknown){const values=this.args(input,true);const id=checked(()=>seoUuid(input.operationId));const fp=merchantAdminFingerprint('seo/'+action+'/v1',values[0] as string,request);const query=`SELECT outcome,result_payload FROM saas.seo_admin_mutate(${A},$8::uuid,$9::text,$10::text,$11::jsonb)`;try{const r=await this.run<T>(query,[...values,id,fp,action,JSON.stringify(request)],true);return {...r.payload,replayed:r.replayed};}catch(e){if(e instanceof SeoRepositoryError&&e.code==='commit_unknown'){try{const r=await this.run<T>(`SELECT outcome,result_payload FROM saas.seo_admin_recover(${A},$8::uuid,$9::text,$10::text)`,[...values,id,fp,action]);return{...r.payload,replayed:true};}catch{fail('commit_unknown');}}throw e;}}
 overview(input:SeoAuthorityInput){return this.read<SeoOverview>(input,'overview');}
 resources(input:Parameters<SeoRepository['resources']>[0]){const request=checked(()=>{const r=seoExact(input,['tenantContext','now'],['kind','query','missing','cursor','limit']);if(r.kind!==undefined)seoKind(r.kind);if(r.query!==undefined&&(typeof r.query!=='string'||r.query.length>200||/[\u0000-\u001f]/.test(r.query)))fail();if(r.missing!==undefined&&typeof r.missing!=='boolean')fail();if(r.cursor!==undefined&&(typeof r.cursor!=='string'||!/^\d{1,9}$/.test(r.cursor)))fail();const limit=r.limit??50;if(!Number.isInteger(limit)||(limit as number)<1||(limit as number)>100)fail();return{kind:r.kind??null,query:r.query??null,missing:r.missing??false,cursor:r.cursor??null,limit};});return this.read<{items:SeoResource[];nextCursor:string|null;total:number}>(input,'resources',request);}
 saveResource(input:Parameters<SeoRepository['saveResource']>[0]){return this.write<{resource:SeoResource}>(input,'resource',checked(()=>parseSaveSeoResourceRequest(input.request)));}
 settings(input:SeoAuthorityInput){return this.read<SeoSettings>(input,'settings');}
 saveSettings(input:Parameters<SeoRepository['saveSettings']>[0]){return this.write<{settings:SeoSettings}>(input,'settings',checked(()=>parseSaveSeoSettingsRequest(input.request)));}
 links(input:SeoAuthorityInput){return this.read<{items:SeoLink[]}>(input,'links');}
 saveLink(input:Parameters<SeoRepository['saveLink']>[0]){return this.write<{link:SeoLink|null}>(input,'link',checked(()=>parseSaveSeoLinkRequest(input.request)));}
 notifications(input:SeoAuthorityInput){return this.read<{items:SeoNotification[]}>(input,'notifications');}
 notify(input:Parameters<SeoRepository['notify']>[0]){return this.write<{queued:number}>(input,'notify',checked(()=>parseNotifySeoRequest(input.request)));}
 startCheck(input:SeoOperationInput){return this.write<{checked:number;total:number;status:string}>(input,'check',{});}
}
export class PostgresPublicSeoRepository extends Base implements PublicSeoRepository {
 constructor(options:PostgresPublicSeoRepositoryOptions){super(options,'celebix_saas_host_resolver');}
 private args(input:{hostname:string;now:Date}){return[hostname(input.hostname),date(input.now)];}
 async get(input:Parameters<PublicSeoRepository['get']>[0]){return(await this.run<Awaited<ReturnType<PublicSeoRepository['get']>>>('SELECT outcome,result_payload FROM saas.seo_public_get($1::text,$2::timestamptz,$3::text,$4::uuid)',[...this.args(input),checked(()=>seoKind(input.kind)),checked(()=>seoUuid(input.id))])).payload;}
 async settings(input:Parameters<PublicSeoRepository['settings']>[0]){return(await this.run<SeoSettings>('SELECT outcome,result_payload FROM saas.seo_public_settings($1::text,$2::timestamptz)',this.args(input))).payload;}
 async key(input:Parameters<PublicSeoRepository['key']>[0]){return(await this.run<{key:string|null}>('SELECT outcome,result_payload FROM saas.seo_public_key($1::text,$2::timestamptz)',this.args(input))).payload;}
}
export class PostgresSeoWorkerRepository extends Base implements SeoWorkerRepository {
 constructor(options:PostgresSeoWorkerRepositoryOptions){super(options,'celebix_saas_workflow');}
 async claim(input:Parameters<SeoWorkerRepository['claim']>[0]){if(!Number.isInteger(input.limit)||input.limit<1||input.limit>25||typeof input.workerId!=='string'||!/^[a-zA-Z0-9_.:-]{1,100}$/.test(input.workerId))fail();return(await this.run<Awaited<ReturnType<SeoWorkerRepository['claim']>>>('SELECT outcome,result_payload FROM saas.seo_worker_claim($1::timestamptz,$2::integer,$3::text)',[date(input.now),input.limit,input.workerId],true)).payload;}
 async finishNotification(input:Parameters<SeoWorkerRepository['finishNotification']>[0]){checked(()=>{seoUuid(input.id);seoUuid(input.leaseId);date(input.now);if(!['received','verification_pending','retrying','failed'].includes(input.status)||input.httpStatus!==null&&(!Number.isInteger(input.httpStatus)||input.httpStatus<100||input.httpStatus>599)||input.error!==null&&(typeof input.error!=='string'||input.error.length>1000))fail();});const next=input.nextAttemptAt instanceof Date?date(input.nextAttemptAt).toISOString():input.nextAttemptAt;await this.run('SELECT outcome,result_payload FROM saas.seo_worker_finish_notification($1::uuid,$2::uuid,$3::timestamptz,$4::jsonb)',[input.id,input.leaseId,input.now,JSON.stringify({status:input.status,httpStatus:input.httpStatus,error:input.error,nextAttemptAt:next})],true);}
 async finishCheck(input:Parameters<SeoWorkerRepository['finishCheck']>[0]){checked(()=>{seoUuid(input.id);seoUuid(input.leaseId);date(input.now);if(!Array.isArray(input.issues)||input.issues.length>20||input.error!==null&&(typeof input.error!=='string'||input.error.length>1000))fail();});await this.run('SELECT outcome,result_payload FROM saas.seo_worker_finish_check($1::uuid,$2::uuid,$3::timestamptz,$4::jsonb)',[input.id,input.leaseId,input.now,JSON.stringify({issues:input.issues,error:input.error})],true);}
}
