import assert from "node:assert/strict";
import { accessSync, constants, mkdtempSync, mkdirSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { REQUIRED_NATIVE_TOOLS, assertSafeEnvironment } from "../../saas-phase2/postgres/disposable-harness.mjs";

const ROOT = path.resolve(import.meta.dirname, "../../..");
const SQL = path.join(ROOT, "apps/owner/scripts/sql/saas");
const DB = "promotions_studio_126";
const TOTAL = 43;
let completed = 0;
const STORE = "10000000-0000-4000-8000-000000000126";
const PERCENT = "40000000-0000-4000-8000-000000000126";
const FIXED = "40000000-0000-4000-8000-000000000127";
const SHIPPING = "40000000-0000-4000-8000-000000000128";
const TIER = "40000000-0000-4000-8000-000000000129";
const BUNDLE = "40000000-0000-4000-8000-000000000130";
const BUY = "40000000-0000-4000-8000-000000000131";
const GIFT = "40000000-0000-4000-8000-000000000132";
const OTHER_STORE = "20000000-0000-4000-8000-000000000126";
const OTHER_PRODUCT = "50000000-0000-4000-8000-000000000129";
const CATEGORY = "50000000-0000-4000-8000-000000000130";
const BRAND = "50000000-0000-4000-8000-000000000131";
const COLLECTION = "50000000-0000-4000-8000-000000000132";
function bin(name) { for (const directory of [process.env.POSTGRES_BIN, ...(process.env.PATH ?? "").split(path.delimiter), ...(() => { try { return readdirSync(path.join(homedir(), ".codex", "tmp"), { withFileTypes: true }).filter((entry) => entry.isDirectory() && /^postgresql-16[.]/.test(entry.name)).map((entry) => path.join(homedir(), ".codex", "tmp", entry.name, "bin")); } catch { return []; } })()]) { if (!directory) continue; try { const candidate = path.join(directory, name); accessSync(candidate, constants.X_OK); return candidate; } catch {} } throw new Error(`DISPOSABLE_DB_EXECUTION_BLOCKED: missing ${name}`); }
function command(program, args, input = "", allowFailure = false) { const result = spawnSync(program, args, { cwd: ROOT, input, encoding: "utf8", env: { ...process.env, LC_ALL: "C", LANG: "C" } }); if (result.error) throw result.error; if (!allowFailure && result.status !== 0) throw new Error(`${path.basename(program)} failed\\n${result.stderr}`); return result; }
function start() { assertSafeEnvironment(); const tools = Object.fromEntries([...new Set([...REQUIRED_NATIVE_TOOLS,"initdb","pg_ctl","psql"])].map((name) => [name, bin(name)])); const root = mkdtempSync(path.join(tmpdir(), "cx-promotions-studio-")); const data = path.join(root, "data"), socket = path.join(root, "socket"), port = 21000 + Math.floor(Math.random() * 10000); mkdirSync(socket, { mode: 0o700 }); command(tools.initdb, ["-D", data, "--auth=trust", "--username=postgres", "--no-locale", "--encoding=UTF8"]); command(tools.pg_ctl, ["-D", data, "-o", `-k ${socket} -p ${port} -h ''`, "-l", path.join(root, "postgres.log"), "start"]); return { tools, root, data, socket, port }; }
function stop(box) { if (box) { command(box.tools.pg_ctl, ["-D", box.data, "-m", "fast", "stop"], "", true); rmSync(box.root, { recursive: true, force: true }); } }
function psql(box, source, database = DB, allowFailure = false) { return command(box.tools.psql, ["-h", box.socket, "-p", String(box.port), "-X", "-qAt", "-v", "ON_ERROR_STOP=1", "-U", "postgres", "-d", database], source, allowFailure); }
function apply(box, file) { psql(box, readFileSync(path.join(SQL, file), "utf8")); }
function scalar(box, source) { return psql(box, source).stdout.trim().split(String.fromCharCode(10)).at(-1) ?? ""; }
function scenario(name, callback) { callback(); completed += 1; process.stdout.write([`PASS ${completed}/${TOTAL} ${name}`, ""].join(String.fromCharCode(10))); }
function migrationsThrough125() {
  const accepted = /(?:[.]up|[.]seed|[.]freeze|_grants|_assertions|catalog_assertions)[.]sql$/;
  return readdirSync(SQL).filter((file) => {
    if (!/^2026\d{8}_.+[.]sql$/.test(file) || file.includes('.down.') || file.includes('rollback') || file.includes('forward_recovery') || file === '202607300073_seed_guzide_pilot_admin_domain.up.sql') return false;
    const sequence = Number.parseInt(file.slice(8, 12), 10);
    return Number.isSafeInteger(sequence) && sequence <= 125 && (sequence <= 71 ? accepted.test(file) : file.endsWith('.up.sql'));
  }).sort((left,right) => { const sequence=Number.parseInt(left.slice(8,12),10)-Number.parseInt(right.slice(8,12),10); const weight=(file)=>file.includes('assertions')?3:file.includes('freeze')||file.includes('grants')?2:1; return sequence||weight(left)-weight(right)||left.localeCompare(right); });
}
function rule(benefit) { return JSON.stringify({schemaVersion:1,benefit,targets:{mode:"all",include:[],exclude:[]},audience:{mode:"everyone"},trigger:{kind:"automatic"},schedule:{timezone:"Europe/Istanbul"},limits:{totalUsage:null,perCustomerUsage:null,budgetMinor:null,orderMaximumMinor:null},conditions:{minimumBasketMinor:0,minimumQuantity:0,minimumProductQuantity:0},combinationPolicy:{kind:"none"},priority:0,marginPolicy:{kind:"warn"},progressMessagePolicy:{enabled:false}}).replaceAll("'", "''"); }
function validRuleDocument() { return JSON.parse(rule({kind:"percentage",percentageBps:1000})); }
function validates(box, value) { return scalar(box, `SELECT saas.promotion_rule_document_valid('${JSON.stringify(value).replaceAll("'", "''")}'::jsonb)`); }
function seed(box) {
  psql(box, `INSERT INTO saas.stores(id,name,slug,status,locale,currency,theme_key,created_at,updated_at) VALUES ('${STORE}','Promotions Studio','promotions-studio','active','tr','TRY','starter','2026-01-01','2026-01-01');`);
  psql(box, `INSERT INTO saas.stores(id,name,slug,status,locale,currency,theme_key,created_at,updated_at) VALUES ('${OTHER_STORE}','Other Promotions Studio','other-promotions-studio','active','tr','TRY','starter','2026-01-01','2026-01-01');
    INSERT INTO saas.products(id,store_id,slug,title,status,currency,created_at,updated_at) VALUES
      ('${LINE}','${STORE}','promotion-line','Promotion line','active','TRY','2026-01-01','2026-01-01'),
      ('${OTHER_PRODUCT}','${OTHER_STORE}','other-promotion-line','Other promotion line','active','TRY','2026-01-01','2026-01-01');
    ALTER TABLE saas.product_variants DISABLE TRIGGER product_variants_inventory_reconcile;
    INSERT INTO saas.product_variants(id,product_id,store_id,title,price_cents,cost_cents,stock_tracking,stock_quantity,status,created_at,updated_at) VALUES
      ('${LINE}','${LINE}','${STORE}','Promotion variant',100,40,false,0,'active','2026-01-01','2026-01-01'),
      ('${OTHER_PRODUCT}','${OTHER_PRODUCT}','${OTHER_STORE}','Other promotion variant',100,40,false,0,'active','2026-01-01','2026-01-01');
    ALTER TABLE saas.product_variants ENABLE TRIGGER product_variants_inventory_reconcile;
    INSERT INTO saas.catalog_categories(id,store_id,parent_id,name,slug,position,depth,status,created_at,updated_at) VALUES('${CATEGORY}','${STORE}',NULL,'Promotion category','promotion-category',0,1,'active','2026-01-01','2026-01-01');
    INSERT INTO saas.catalog_product_categories(store_id,product_id,category_id,position) VALUES('${STORE}','${LINE}','${CATEGORY}',0);
    INSERT INTO saas.catalog_admin_resources(id,store_id,resource_kind,name,slug,config,status,version,created_at,updated_at) VALUES
      ('${BRAND}','${STORE}','brand','Promotion brand','promotion-brand','{}','active',1,'2026-01-01','2026-01-01'),
      ('${COLLECTION}','${STORE}','collection','Promotion collection','promotion-collection','{}','active',1,'2026-01-01','2026-01-01');
    INSERT INTO saas.catalog_admin_resource_products(store_id,resource_id,product_id,position) VALUES
      ('${STORE}','${BRAND}','${LINE}',0),('${STORE}','${COLLECTION}','${LINE}',0);
    INSERT INTO saas.customers(id,store_id,status,first_name,last_name,email,created_at,updated_at) VALUES('${LINE}','${STORE}','active','Promotion','Customer','promotion-customer@test.invalid','2026-01-01','2026-01-01');
    INSERT INTO saas.customer_tags(id,store_id,name,color,created_at,updated_at) VALUES('${LINE}','${STORE}','Promotion tag','#111111','2026-01-01','2026-01-01');
    INSERT INTO saas.customer_segments(id,store_id,name,created_at,updated_at) VALUES('${LINE}','${STORE}','Promotion segment','2026-01-01','2026-01-01');
    INSERT INTO saas.customer_tag_assignments(store_id,customer_id,tag_id,assigned_at) VALUES('${STORE}','${LINE}','${LINE}','2026-01-01');
    INSERT INTO saas.customer_segment_memberships(store_id,customer_id,segment_id,assigned_at) VALUES('${STORE}','${LINE}','${LINE}','2026-01-01');`);
  const rules = [[PERCENT,{kind:"percentage",percentageBps:1000}],[FIXED,{kind:"fixed_amount",amountMinor:50,currency:"TRY"}],[SHIPPING,{kind:"free_shipping"}],[TIER,{kind:"quantity_tiers",tiers:[{minimumQuantity:2,percentageBps:1000}]}],[BUNDLE,{kind:"bundle_price",bundleQuantity:3,bundlePriceMinor:200,currency:"TRY"}],[BUY,{kind:"buy_x_get_y",buyQuantity:2,receiveQuantity:1,discountPercentageBps:10000,reward:{strategy:"same_product_cheapest"}}],[GIFT,{kind:"gift",giftVariantId:"50000000-0000-4000-8000-000000000126"}]];
  for (const [id, benefit] of rules) psql(box, `INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES ('${id}','${STORE}','${benefit.kind}','paused',1,'${rule(benefit)}'::jsonb,'2026-01-01','2026-01-01');`);
}
function activate(box, id) { psql(box, `UPDATE saas.promotions SET status=CASE WHEN id='${id}' THEN 'active' ELSE 'paused' END WHERE store_id='${STORE}';`); }
const LINE = "50000000-0000-4000-8000-000000000126";
function context(overrides = {}) { return {
  storeId: STORE, customerId: null, paidOrderCount: 0, customerSegmentIds: [], customerTagIds: [],
  cartLines: [{ lineId: LINE, position: 0, productId: LINE, variantId: LINE, quantity: 3, unitPriceMinor: 100, unitCostMinor: 40, currency: "TRY", categoryIds: [], brandId: null, collectionIds: [] }],
  shippingMethodId: null, paymentMethodId: null, shippingBeforeDiscountMinor: 40, currency: "TRY",
  storeLocalTime: "2026-09-05T00:00:00.000Z", salesChannel: "storefront", submittedCodes: [], abandonedCart: null, ...overrides,
}; }
function evaluate(box, overrides = {}) { return JSON.parse(scalar(box, `SELECT saas.promotion_evaluate_v1('${STORE}','${JSON.stringify(context(overrides)).replaceAll("'", "''")}'::jsonb,'2026-09-05T00:00:00Z')`)); }
function parseContract(value) { const parser = command(process.execPath, ["--experimental-strip-types", "--input-type=module", "-e", "import { parsePromotionEvaluatorResult } from './packages/saas-contracts/src/promotions/index.ts'; const chunks=[]; for await (const chunk of process.stdin) chunks.push(chunk); parsePromotionEvaluatorResult(JSON.parse(Buffer.concat(chunks).toString('utf8')));"], JSON.stringify(value), true); assert.equal(parser.status, 0, parser.stderr); }
function discount(box) { return String(evaluate(box).discountTotalMinor); }
let box;
try {
  box = start();
  command(box.tools.psql, ["-h", box.socket, "-p", String(box.port), "-X", "-q", "-U", "postgres", "-d", "postgres", "-c", `CREATE DATABASE ${DB}`]);
  for (const migration of migrationsThrough125()) apply(box, migration);
  scenario("migration 126 applies after the accepted additive chain", () => apply(box, "202609050126_promotions_studio.up.sql"));
  apply(box, "202609050126_promotions_studio_assertions.sql");
  seed(box);
  scenario("exact eleven promotion relations exist", () => assert.equal(scalar(box, "SELECT count(*) FROM pg_class WHERE relnamespace='saas'::regnamespace AND relname IN ('promotions','promotion_versions','promotion_targets','promotion_codes','promotion_code_batches','promotion_usage_reservations','promotion_redemptions','promotion_audit_events','promotion_operations','order_promotion_snapshots','order_discount_allocations')"), "11"));
  scenario("evaluator is installed", () => assert.equal(scalar(box, "SELECT pg_catalog.to_regprocedure('saas.promotion_evaluate_v1(uuid,jsonb,timestamp with time zone)') IS NOT NULL"), "t"));
  scenario("tenant policies are forced", () => assert.equal(scalar(box, "SELECT count(*) FROM pg_class WHERE relnamespace='saas'::regnamespace AND relname LIKE 'promotion%' AND relrowsecurity AND relforcerowsecurity"), "9"));
  scenario("app has narrow RPC execution and no direct promotion table writes", () => { assert.equal(scalar(box,"SELECT pg_catalog.has_function_privilege('celebix_saas_app','saas.promotion_list_v1(uuid,uuid,uuid,uuid,text,bigint,timestamp with time zone,text,text[],integer)'::regprocedure,'EXECUTE')"),"t"); assert.equal(scalar(box,"SELECT pg_catalog.has_table_privilege('celebix_saas_app','saas.promotions','INSERT,UPDATE,DELETE')"),"f"); assert.equal(scalar(box,"SELECT pg_catalog.has_function_privilege('celebix_saas_identity','saas.promotion_list_v1(uuid,uuid,uuid,uuid,text,bigint,timestamp with time zone,text,text[],integer)'::regprocedure,'EXECUTE')"),"f"); });
  scenario("every promotion helper and RPC revokes PUBLIC execute", () => assert.equal(scalar(box, "SELECT count(*) FROM pg_catalog.pg_proc p WHERE p.pronamespace='saas'::regnamespace AND p.proname LIKE 'promotion_%' AND pg_catalog.has_function_privilege('public',p.oid,'EXECUTE')"), "0"));
  scenario("rule validation rejects malformed documents", () => assert.equal(scalar(box, "SELECT saas.promotion_rule_document_valid('{}'::jsonb)"), "f"));
  scenario("code normalization rejects whitespace and canonically folds Turkish letters", () => { assert.equal(scalar(box, "SELECT COALESCE(saas.promotion_normalize_code(' indirim-20 '),'')"),""); assert.equal(scalar(box, "SELECT saas.promotion_normalize_code('İndirim-20')"),"INDIRIM-20"); });
  scenario("code normalization rejects non-ASCII lookalikes", () => { assert.equal(scalar(box, "SELECT COALESCE(saas.promotion_normalize_code('KODß'),'')"), ""); assert.equal(scalar(box, "SELECT COALESCE(saas.promotion_normalize_code('KODΣ'),'')"), ""); });
  scenario("strict rule validation rejects bad nested values before evaluator casts", () => { const bad = rule({kind:"percentage",percentageBps:1000}).replace('"percentageBps":1000', '"percentageBps":"bad"'); assert.equal(scalar(box, `SELECT saas.promotion_rule_document_valid('${bad}'::jsonb)`), "f"); assert.equal(evaluate(box,{cartLines:[],shippingBeforeDiscountMinor:0}).discountTotalMinor,0); });
  scenario("operations use a SHA-256 fingerprint", () => assert.equal(scalar(box, "SELECT saas.promotion_operation_fingerprint('create','{}'::jsonb)"), "71e89af0bd175d9da125da99ba0742ecb9c2c259f88b03f362ce0108fcc253cc"));
  scenario("draft rules never apply", () => assert.equal(scalar(box, "SELECT saas.promotion_evaluate_v1('00000000-0000-4000-8000-000000000001','{\"storeId\":\"00000000-0000-4000-8000-000000000001\",\"customerId\":null,\"paidOrderCount\":0,\"customerSegmentIds\":[],\"customerTagIds\":[],\"cartLines\":[],\"shippingMethodId\":null,\"paymentMethodId\":null,\"shippingBeforeDiscountMinor\":0,\"currency\":\"TRY\",\"storeLocalTime\":\"2026-09-05T00:00:00.000Z\",\"salesChannel\":\"storefront\",\"submittedCodes\":[],\"abandonedCart\":null}'::jsonb,'2026-09-05T00:00:00Z')->>'discountTotalMinor'"), "0"));
  scenario("percentage promotion uses integer minor units", () => { activate(box,PERCENT); assert.equal(discount(box),"30"); });
  scenario("fixed promotion caps at eligible cart value", () => { activate(box,FIXED); assert.equal(discount(box),"50"); });
  scenario("shipping promotion is bounded by shipping", () => { activate(box,SHIPPING); assert.equal(discount(box),"40"); });
  scenario("quantity tier selects the reached percentage", () => { activate(box,TIER); assert.equal(discount(box),"30"); });
  scenario("bundle price calculates a bounded saving", () => { activate(box,BUNDLE); assert.equal(discount(box),"100"); });
  scenario("buy X get Y discounts the deterministic cheapest unit", () => { activate(box,BUY); assert.equal(discount(box),"100"); });
  scenario("gift produces zero-paid immutable gift effect", () => { activate(box,GIFT); assert.equal(evaluate(box,{cartLines:[],shippingBeforeDiscountMinor:0}).gifts[0].paidMinor,0); });
  scenario("evaluator output has separated shipping and reconciled line effects", () => { activate(box,SHIPPING); const value=evaluate(box,{cartLines:[{...context().cartLines[0],quantity:1}]}); assert.equal(value.shippingDiscountTotalMinor,40); assert.equal(value.lineDiscountTotalMinor,0); assert.equal(value.discountTotalMinor,40); assert.equal(value.grandTotalMinor,100); assert.equal(value.eligiblePromotionIds.length,1); assert.equal(value.shippingEffects.length,1); });
  scenario("down migration refuses without emergency setting", () => assert.notEqual(psql(box, readFileSync(path.join(SQL, "202609050126_promotions_studio.down.sql"), "utf8"), DB, true).status, 0));
  scenario("allowed-empty emergency down removes functions before relations", () => { psql(box, `DELETE FROM saas.promotions WHERE store_id='${STORE}'`); const down = readFileSync(path.join(SQL, "202609050126_promotions_studio.down.sql"), "utf8").replace("BEGIN;", "BEGIN; SET LOCAL saas.promotions_studio_emergency_drop = 'approved-pre-restore';"); const result=psql(box, down, DB, true); if (result.status!==0) throw new Error(result.stderr); apply(box, "202609050126_promotions_studio.up.sql"); });
  scenario("migration is replay-safe", () => apply(box, "202609050126_promotions_studio.up.sql"));
  scenario("assertions replay safely", () => apply(box, "202609050126_promotions_studio_assertions.sql"));
  scenario("rule validation rejects duplicate nested collections and unordered tiers", () => { const id="50000000-0000-4000-8000-000000000126", second="50000000-0000-4000-8000-000000000127"; const duplicateTarget=validRuleDocument(); duplicateTarget.targets={mode:"selected",include:[{kind:"product",id},{kind:"product",id}],exclude:[]}; const duplicateAudience=validRuleDocument(); duplicateAudience.audience={mode:"customer_tags",referenceIds:[id,id]}; const duplicateCodes=validRuleDocument(); duplicateCodes.trigger={kind:"code",codes:["SAVE","SAVE"]}; const duplicatePayment=validRuleDocument(); duplicatePayment.conditions={...duplicatePayment.conditions,paymentMethodIds:[id,id]}; const duplicateShipping=validRuleDocument(); duplicateShipping.conditions={...duplicateShipping.conditions,shippingMethodIds:[id,id]}; const duplicateChannels=validRuleDocument(); duplicateChannels.conditions={...duplicateChannels.conditions,salesChannels:["storefront","storefront"]}; const malformedChannel=validRuleDocument(); malformedChannel.conditions={...malformedChannel.conditions,salesChannels:["bad\nchannel"]}; const duplicateCombination=validRuleDocument(); duplicateCombination.combinationPolicy={kind:"benefit_classes",benefitClasses:["percentage","percentage"]}; const unorderedTiers=validRuleDocument(); unorderedTiers.benefit={kind:"quantity_tiers",tiers:[{minimumQuantity:3,percentageBps:1000},{minimumQuantity:2,percentageBps:2000}]}; for (const value of [duplicateTarget,duplicateAudience,duplicateCodes,duplicatePayment,duplicateShipping,duplicateChannels,malformedChannel,duplicateCombination,unorderedTiers]) assert.equal(validates(box,value),"f"); });
  scenario("legacy code collisions remain read-only while independent safe adoption continues", () => { const existing="60000000-0000-4000-8000-000000000126", legacyA="60000000-0000-4000-8000-000000000127", legacyB="60000000-0000-4000-8000-000000000128", legacyExisting="60000000-0000-4000-8000-000000000129", legacySafe="60000000-0000-4000-8000-000000000130"; psql(box, `INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES('${existing}','${STORE}','existing','draft',1,'${rule({kind:"percentage",percentageBps:1000})}'::jsonb,'2026-01-01','2026-01-01'); INSERT INTO saas.promotion_codes(id,store_id,promotion_id,code,status,created_at) VALUES('60000000-0000-4000-8000-000000000131','${STORE}','${existing}','EXISTING','active','2026-01-01');`); const record=(id,name,config)=>`INSERT INTO saas.merchant_admin_records(id,store_id,record_kind,name,config,status,version,created_at,updated_at) VALUES('${id}','${STORE}','discount','${name}','${JSON.stringify(config).replaceAll("'", "''")}'::jsonb,'draft',1,'2026-01-01','2026-01-01');`; psql(box, record(legacyA,"duplicate a",{discountType:"percent",value:"10",code:"DUPLICATE"})+record(legacyB,"duplicate b",{discountType:"percent",value:"10",code:"duplicate"})+record(legacyExisting,"existing code",{discountType:"fixed",value:"50",code:"EXISTING"})+record(legacySafe,"safe",{discountType:"fixed",value:"50"})); assert.equal(scalar(box,`SELECT saas.promotion_adopt_legacy_discounts_v1('${STORE}','2026-09-05T00:00:00Z')`),"1"); assert.equal(scalar(box,`SELECT count(*) FROM saas.promotions WHERE store_id='${STORE}' AND legacy_record_id IS NOT NULL`),"1"); assert.equal(scalar(box,`SELECT saas.promotion_adopt_legacy_discounts_v1('${STORE}','2026-09-05T00:00:00Z')`),"0"); assert.equal(scalar(box,`SELECT count(*) FROM saas.merchant_admin_records WHERE store_id='${STORE}' AND record_kind='discount'`),"4"); });
  scenario("canonical context rejects spoofed store authority and duplicate lines", () => { activate(box,PERCENT); assert.equal(evaluate(box,{storeId:"20000000-0000-4000-8000-000000000126"}).discountTotalMinor,0); assert.equal(evaluate(box,{cartLines:[context().cartLines[0],context().cartLines[0]]}).discountTotalMinor,0); });
  scenario("schedule starts inclusively and ends exclusively", () => { const id="70000000-0000-4000-8000-000000000126", document=validRuleDocument(); document.schedule={timezone:"Europe/Istanbul",startsAt:"2026-09-05T00:00:00.000Z",endsAt:"2026-09-05T00:00:01.000Z"}; psql(box,`INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES('${id}','${STORE}','scheduled edge','active',1,'${JSON.stringify(document)}','2026-01-01','2026-01-01');`); activate(box,id); assert.equal(evaluate(box).discountTotalMinor,30); assert.equal(JSON.parse(scalar(box,`SELECT saas.promotion_evaluate_v1('${STORE}','${JSON.stringify(context()).replaceAll("'", "''")}'::jsonb,'2026-09-05T00:00:01Z')`)).discountTotalMinor,0); });
  scenario("code candidates need an active normalized code owned by their promotion", () => { const id="70000000-0000-4000-8000-000000000127", document=validRuleDocument(); document.trigger={kind:"code",codes:["SAVE"]}; psql(box,`INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES('${id}','${STORE}','code','active',1,'${JSON.stringify(document)}','2026-01-01','2026-01-01'); INSERT INTO saas.promotion_codes(id,store_id,promotion_id,code,status,created_at) VALUES('70000000-0000-4000-8000-000000000128','${STORE}','${id}','SAVE','active','2026-01-01');`); activate(box,id); assert.equal(evaluate(box,{submittedCodes:["SAVE"]}).discountTotalMinor,30); psql(box,`UPDATE saas.promotion_codes SET status='paused' WHERE store_id='${STORE}' AND promotion_id='${id}'`); assert.equal(evaluate(box,{submittedCodes:["SAVE"]}).discountTotalMinor,0); });
  scenario("conditions and selected product targets gate eligibility", () => { const id="70000000-0000-4000-8000-000000000129", document=validRuleDocument(); document.targets={mode:"selected",include:[{kind:"product",id:LINE}],exclude:[]}; document.conditions={minimumBasketMinor:301,minimumQuantity:4,minimumProductQuantity:4,paymentMethodIds:[LINE],shippingMethodIds:[LINE],salesChannels:["quick_order"]}; psql(box,`INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES('${id}','${STORE}','conditions','active',1,'${JSON.stringify(document)}','2026-01-01','2026-01-01');`); activate(box,id); assert.equal(evaluate(box,{paymentMethodId:LINE,shippingMethodId:LINE,salesChannel:"quick_order"}).discountTotalMinor,0); assert.equal(evaluate(box,{cartLines:[{...context().cartLines[0],quantity:4}],paymentMethodId:LINE,shippingMethodId:LINE,salesChannel:"quick_order"}).discountTotalMinor,40); });
  scenario("audiences do not apply until their persisted customer facts match", () => { const id="70000000-0000-4000-8000-000000000130", document=validRuleDocument(); document.audience={mode:"customer_segments",referenceIds:[LINE]}; psql(box,`INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES('${id}','${STORE}','audience','active',1,'${JSON.stringify(document)}','2026-01-01','2026-01-01');`); activate(box,id); assert.equal(evaluate(box).discountTotalMinor,0); assert.equal(evaluate(box,{customerId:LINE,customerSegmentIds:[LINE]}).discountTotalMinor,30); });
  scenario("every audience mode is bounded to its persisted authority", () => { const cases=[["70000000-0000-4000-8000-000000000141",{mode:"first_paid_order"},{customerId:LINE,paidOrderCount:0}],["70000000-0000-4000-8000-000000000142",{mode:"customer_tags",referenceIds:[LINE]},{customerId:LINE,customerTagIds:[LINE]}],["70000000-0000-4000-8000-000000000143",{mode:"masked_customers",referenceIds:[LINE]},{customerId:LINE}]]; for (const [id,audience,facts] of cases) { const document=validRuleDocument(); document.audience=audience; psql(box,`INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES('${id}','${STORE}','audience','active',1,'${JSON.stringify(document)}','2026-01-01','2026-01-01');`); activate(box,id); assert.equal(evaluate(box,facts).discountTotalMinor,30); } });
  scenario("category brand collection and exclusion targets are evaluated from persisted catalog relations", () => { const refs=[["category",CATEGORY],["brand",BRAND],["collection",COLLECTION]]; for (const [kind,id] of refs) { const promotion=`70000000-0000-4000-8000-00000000015${refs.indexOf(refs.find((entry)=>entry[0]===kind))+1}`, document=validRuleDocument(); document.targets={mode:"selected",include:[{kind,id}],exclude:[]}; psql(box,`INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES('${promotion}','${STORE}','target','active',1,'${JSON.stringify(document)}','2026-01-01','2026-01-01');`); activate(box,promotion); assert.equal(evaluate(box).discountTotalMinor,30); } const excluded="70000000-0000-4000-8000-000000000155", excludedRule=validRuleDocument(); excludedRule.targets={mode:"all",include:[],exclude:[{kind:"product",id:LINE}]}; psql(box,`INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES('${excluded}','${STORE}','excluded','active',1,'${JSON.stringify(excludedRule)}','2026-01-01','2026-01-01');`); activate(box,excluded); assert.equal(evaluate(box).discountTotalMinor,0); });
  scenario("limits include committed and unexpired reserved use and budget", () => { const id="70000000-0000-4000-8000-000000000131", document=validRuleDocument(); document.limits={totalUsage:1,perCustomerUsage:null,budgetMinor:29,orderMaximumMinor:null}; psql(box,`INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES('${id}','${STORE}','limited','active',1,'${JSON.stringify(document)}','2026-01-01','2026-01-01'); INSERT INTO saas.promotion_usage_reservations(id,store_id,promotion_id,operation_id,source_reference,reserved_budget_minor,status,expires_at,created_at,updated_at) VALUES('70000000-0000-4000-8000-000000000132','${STORE}','${id}','70000000-0000-4000-8000-000000000132','test',29,'reserved','2026-09-06','2026-01-01','2026-01-01');`); activate(box,id); assert.equal(evaluate(box).discountTotalMinor,0); });
  scenario("competing non-combinable promotions use saving then priority then stable identifiers", () => { const first="70000000-0000-4000-8000-000000000133", second="70000000-0000-4000-8000-000000000134", one=validRuleDocument(), two=validRuleDocument(); one.priority=1; two.priority=2; psql(box,`INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES('${first}','${STORE}','first','active',1,'${JSON.stringify(one)}','2026-01-01','2026-01-01'),('${second}','${STORE}','second','active',1,'${JSON.stringify(two)}','2026-01-01','2026-01-01');`); activate(box,first); psql(box,`UPDATE saas.promotions SET status='active' WHERE store_id='${STORE}' AND id='${second}'`); const value=evaluate(box); assert.equal(value.appliedPromotions.length,1); assert.equal(value.appliedPromotions[0].promotionId,second); });
  scenario("non-combinable candidates choose larger customer saving before priority", () => { const smaller="70000000-0000-4000-8000-000000000171", larger="70000000-0000-4000-8000-000000000172", one=validRuleDocument(), two=validRuleDocument(); one.priority=100; two.priority=0; one.benefit={kind:"percentage",percentageBps:1000}; two.benefit={kind:"percentage",percentageBps:2000}; psql(box,`INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES('${smaller}','${STORE}','smaller','active',1,'${JSON.stringify(one)}','2026-01-01','2026-01-01'),('${larger}','${STORE}','larger','active',1,'${JSON.stringify(two)}','2026-01-01','2026-01-01');`); activate(box,smaller); psql(box,`UPDATE saas.promotions SET status='active' WHERE store_id='${STORE}' AND id='${larger}'`); assert.equal(evaluate(box).appliedPromotions[0].promotionId,larger); });
  scenario("shipping-only and explicit benefit-class policies combine deterministically", () => { const percent="70000000-0000-4000-8000-000000000156", shipping="70000000-0000-4000-8000-000000000157", explicit="70000000-0000-4000-8000-000000000158", first=validRuleDocument(), second=JSON.parse(rule({kind:"free_shipping"})), third=validRuleDocument(); first.combinationPolicy={kind:"shipping_only"}; second.combinationPolicy={kind:"shipping_only"}; third.combinationPolicy={kind:"benefit_classes",benefitClasses:["percentage"]}; psql(box,`INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES('${percent}','${STORE}','percent','active',1,'${JSON.stringify(first)}','2026-01-01','2026-01-01'),('${shipping}','${STORE}','shipping','active',1,'${JSON.stringify(second)}','2026-01-01','2026-01-01'),('${explicit}','${STORE}','explicit','active',1,'${JSON.stringify(third)}','2026-01-01','2026-01-01');`); activate(box,percent); psql(box,`UPDATE saas.promotions SET status='active' WHERE store_id='${STORE}' AND id IN ('${shipping}','${explicit}')`); const value=evaluate(box); assert.equal(value.shippingDiscountTotalMinor,40); assert.equal(value.appliedPromotions.length,3); });
  scenario("all three X/Y reward strategies use the matching deterministic reward unit", () => { const cases=[["same_product_cheapest",{}],["selected_products_cheapest",{productIds:[LINE]}],["specific_variant",{variantId:LINE}]]; for (const [strategy,details] of cases) { const id=`70000000-0000-4000-8000-00000000016${cases.indexOf(cases.find((entry)=>entry[0]===strategy))+1}`, document=JSON.parse(rule({kind:"buy_x_get_y",buyQuantity:2,receiveQuantity:1,discountPercentageBps:10000,reward:{strategy,...details}})); psql(box,`INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES('${id}','${STORE}','xy','active',1,'${JSON.stringify(document)}','2026-01-01','2026-01-01');`); activate(box,id); assert.equal(evaluate(box).discountTotalMinor,100); } });
  scenario("result keeps exact allocation and reconciliation when cart input is reordered", () => { activate(box,PERCENT); const another="50000000-0000-4000-8000-000000000127", lines=[{...context().cartLines[0],position:1},{lineId:another,position:0,productId:another,variantId:another,quantity:1,unitPriceMinor:101,unitCostMinor:20,currency:"TRY",categoryIds:[],brandId:null,collectionIds:[]}]; const left=evaluate(box,{cartLines:lines}); const right=evaluate(box,{cartLines:[...lines].reverse()}); assert.equal(JSON.stringify(left),JSON.stringify(right)); assert.equal(left.grandTotalMinor,left.subtotalBeforeDiscountMinor-left.lineDiscountTotalMinor+left.shippingBeforeDiscountMinor-left.shippingDiscountTotalMinor); });
  scenario("cross-store catalog references cannot make a target match", () => { const id="70000000-0000-4000-8000-000000000170", document=validRuleDocument(); document.targets={mode:"selected",include:[{kind:"product",id:OTHER_PRODUCT}],exclude:[]}; psql(box,`INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES('${id}','${STORE}','foreign target','active',1,'${JSON.stringify(document)}','2026-01-01','2026-01-01');`); activate(box,id); assert.equal(evaluate(box,{cartLines:[{...context().cartLines[0],productId:OTHER_PRODUCT,variantId:OTHER_PRODUCT}]}).discountTotalMinor,0); });
  scenario("a 1,600-product catalog keeps evaluator invocation at one EXPLAIN result node", () => { psql(box,`INSERT INTO saas.products(id,store_id,slug,title,status,currency,created_at,updated_at) SELECT ('30000000-0000-4000-8000-'||lpad(series::text,12,'0'))::uuid,'${STORE}','promotion-fixture-'||series,'Promotion fixture '||series,'active','TRY','2026-01-01','2026-01-01' FROM pg_catalog.generate_series(1,1600) series; INSERT INTO saas.promotions(id,store_id,name,status,version,rule_document,created_at,updated_at) VALUES('${PERCENT}','${STORE}','fixture percent','active',1,'${rule({kind:"percentage",percentageBps:1000})}'::jsonb,'2026-01-01','2026-01-01');`); activate(box,PERCENT); const plan=JSON.parse(psql(box,`EXPLAIN (FORMAT JSON) SELECT saas.promotion_evaluate_v1('${STORE}','${JSON.stringify(context()).replaceAll("'", "''")}'::jsonb,'2026-09-05T00:00:00Z')`).stdout), value=evaluate(box); assert.equal(scalar(box,`SELECT count(*) FROM saas.products WHERE store_id='${STORE}'`),"1601"); assert.equal(plan[0].Plan["Node Type"],"Result"); assert.equal(value.discountTotalMinor,30,JSON.stringify(value)); });
  scenario("the PostgreSQL payload is accepted by the Task 1 evaluator contract", () => { activate(box,PERCENT); parseContract(evaluate(box)); });
  scenario("harness used no external connection", () => assert.equal(process.env.DATABASE_URL, undefined));
  assert.equal(completed, TOTAL);
  process.stdout.write([`PROMOTIONS_STUDIO_POSTGRESQL16_COMPLETE ${completed}/${TOTAL}`, ""].join(String.fromCharCode(10)));
} finally { stop(box); }
