import {parseMerchantAdminEvent,parseMerchantAdminMutationResult,parseMerchantAdminProviderJob,parseMerchantAdminProviderJobMutationResult,parseMerchantAdminRecord,type MerchantAdminEvent,type MerchantAdminMutationResult,type MerchantAdminProviderJob,type MerchantAdminProviderJobMutationResult,type MerchantAdminRecord,type TenantContext} from "@celebix/saas-contracts";
import {acquirePostgresClient,type PostgresClientLike} from "../postgres/pool.ts";
import type {ValidatedCatalogAuthority} from "../catalog/validation.ts";
import {merchantAdminFingerprint} from "./canonical.ts";
import {MERCHANT_ADMIN_ERROR_CODES,MerchantAdminRepositoryError,type MerchantAdminErrorCode} from "./errors.ts";
import type {ArchiveMerchantAdminInput,CancelMerchantAdminProviderJobInput,ListMerchantAdminInput,ListMerchantAdminProviderJobsInput,MerchantAdminRepository,PostgresMerchantAdminRepositoryOptions,PrepareMerchantAdminProviderJobInput,SaveMerchantAdminInput} from "./types.ts";
import {catalogAuthority,exactMerchantAdminInput,merchantAdminConfig,merchantAdminKind,merchantAdminProviderKind,merchantAdminStatus,merchantAdminText,merchantAdminUuid,merchantAdminVersion} from "./validation.ts";
type Spec=Readonly<{text:string;values:unknown[]}>;type RecoverParser<T>=(value:unknown,replayed:boolean)=>T;const CODES=new Set<string>(MERCHANT_ADMIN_ERROR_CODES);
function unavailable(){return new MerchantAdminRepositoryError("unavailable")}function timeout(value:number){if(!Number.isSafeInteger(value)||value<1||value>60_000)throw unavailable();return`${value}ms`}function release(client:PostgresClientLike,destroy=false){try{client.release(destroy||undefined)}catch{}}
function payload(value:unknown,keys:readonly string[]){if(typeof value!=="object"||value===null||Array.isArray(value))throw unavailable();const result=value as Record<string,unknown>;if(Object.keys(result).sort().join(",")!==[...keys].sort().join(","))throw unavailable();return result}
function row(value:Readonly<{rows:unknown[];rowCount?:number|null}>){if(value.rowCount!==1||value.rows.length!==1)throw unavailable();const parsed=payload(value.rows[0],["outcome","result_payload"]);if(typeof parsed.outcome!=="string")throw unavailable();return{outcome:parsed.outcome,result:parsed.result_payload}}
function authorityValues(authority:ValidatedCatalogAuthority){return[authority.storeId,authority.principalId,authority.membershipId,authority.planId,authority.planCode,authority.planVersion,authority.now]}
export class PostgresMerchantAdminRepository implements MerchantAdminRepository{
 private readonly options:PostgresMerchantAdminRepositoryOptions;
 constructor(options:PostgresMerchantAdminRepositoryOptions){try{if(!options||typeof options!=="object"||Array.isArray(options)||Object.keys(options).sort().join(",")!=="audit,pool,role,timeouts,uuid"||options.role!=="celebix_saas_app"||typeof options.audit!=="function"||typeof options.uuid!=="function"||!options.timeouts||Object.keys(options.timeouts).sort().join(",")!=="idleTransactionMs,lockMs,poolCheckoutMs,statementMs")throw unavailable();for(const value of Object.values(options.timeouts))timeout(value);this.options=Object.freeze({...options,timeouts:Object.freeze({...options.timeouts})})}catch(error){if(error instanceof MerchantAdminRepositoryError)throw error;throw unavailable()}}
 private async acquire(){try{return await acquirePostgresClient(this.options.pool,this.options.timeouts.poolCheckoutMs)}catch{throw unavailable()}}
 private async configure(client:PostgresClientLike){await client.query("SELECT pg_catalog.set_config('statement_timeout', $1, true)",[timeout(this.options.timeouts.statementMs)]);await client.query("SELECT pg_catalog.set_config('lock_timeout', $1, true)",[timeout(this.options.timeouts.lockMs)]);await client.query("SELECT pg_catalog.set_config('idle_in_transaction_session_timeout', $1, true)",[timeout(this.options.timeouts.idleTransactionMs)]);await client.query("SET LOCAL ROLE celebix_saas_app")}
 private expected(outcome:string){return CODES.has(outcome)?new MerchantAdminRepositoryError(outcome as MerchantAdminErrorCode):undefined}
 private async rollback(client:PostgresClientLike){try{await client.query("ROLLBACK");release(client)}catch{release(client,true)}}
 private async read<T>(spec:Spec,expected:string,parser:(value:unknown)=>T){const client=await this.acquire();let began=false,terminal=false;try{await client.query("BEGIN READ ONLY");began=true;await this.configure(client);const result=row(await client.query(spec.text,spec.values)),error=this.expected(result.outcome);if(error)throw error;if(result.outcome!==expected)throw unavailable();const parsed=parser(result.result);try{await client.query("COMMIT");terminal=true;release(client)}catch{terminal=true;release(client,true);throw unavailable()}return parsed}catch(error){if(began&&!terminal)await this.rollback(client);else if(!began&&!terminal)release(client,true);if(error instanceof MerchantAdminRepositoryError)throw error;throw unavailable()}}
 private audit(){try{const pending=this.options.audit({type:"merchant_admin_commit_unknown"});if(pending)void pending.catch(()=>undefined)}catch{}}
 private recover<T>(authority:ValidatedCatalogAuthority,operationId:string,fingerprint:string,parser:RecoverParser<T>,functionName="merchant_admin_recover_operation"){return this.read({text:`SELECT outcome,result_payload FROM saas.${functionName}($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text)`,values:[...authorityValues(authority),operationId,fingerprint]},"operation_replayed",(value)=>parser(value,true))}
 private async mutate<T>(authority:ValidatedCatalogAuthority,operationId:string,fingerprint:string,expected:string,spec:Spec,parser:RecoverParser<T>,recoveryFunction="merchant_admin_recover_operation"){const client=await this.acquire();let began=false,terminal=false;try{await client.query("BEGIN ISOLATION LEVEL READ COMMITTED");began=true;await this.configure(client);const result=row(await client.query(spec.text,spec.values)),error=this.expected(result.outcome);if(error)throw error;if(result.outcome!==expected&&result.outcome!=="operation_replayed")throw unavailable();const parsed=parser(result.result,result.outcome==="operation_replayed");try{await client.query("COMMIT");terminal=true;release(client);return parsed}catch{terminal=true;release(client,true);this.audit();return await this.recover(authority,operationId,fingerprint,parser,recoveryFunction)}}catch(error){if(began&&!terminal)await this.rollback(client);else if(!began&&!terminal)release(client,true);if(error instanceof MerchantAdminRepositoryError)throw error;throw unavailable()}}
 private authority(input:unknown,required:readonly string[],optional:readonly string[]=[]){const parsed=exactMerchantAdminInput(input,required,optional);return{parsed,authority:catalogAuthority(parsed.tenantContext as TenantContext,parsed.now as Date)}}
 private uuid(){try{return merchantAdminUuid(this.options.uuid())}catch{throw unavailable()}}
 private mutation(value:unknown,replayed:boolean){try{return parseMerchantAdminMutationResult({...payload(value,["id","kind","status","version","updatedAt"]),replayed})}catch{throw unavailable()}}
 private providerMutation(value:unknown,replayed:boolean){try{return parseMerchantAdminProviderJobMutationResult({...payload(value,["id","recordId","recordKind","action","status","version","updatedAt"]),replayed})}catch{throw unavailable()}}
 async list(input:ListMerchantAdminInput):Promise<readonly MerchantAdminRecord[]>{const{parsed,authority}=this.authority(input,["tenantContext","now","kind"]),kind=merchantAdminKind(parsed.kind);return this.read({text:"SELECT outcome,result_payload FROM saas.merchant_admin_list($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::text)",values:[...authorityValues(authority),kind]},"listed",(value)=>{const result=payload(value,["items"]);if(!Array.isArray(result.items)||result.items.length>200)throw unavailable();try{return Object.freeze(result.items.map(parseMerchantAdminRecord))}catch{throw unavailable()}})}
 async listEvents(input:ListMerchantAdminInput):Promise<readonly MerchantAdminEvent[]>{const{parsed,authority}=this.authority(input,["tenantContext","now","kind"]),kind=merchantAdminKind(parsed.kind);return this.read({text:"SELECT outcome,result_payload FROM saas.merchant_admin_list_events($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::text)",values:[...authorityValues(authority),kind]},"listed",(value)=>{const result=payload(value,["items"]);if(!Array.isArray(result.items)||result.items.length>200)throw unavailable();try{return Object.freeze(result.items.map(parseMerchantAdminEvent))}catch{throw unavailable()}})}
 async listProviderJobs(input:ListMerchantAdminProviderJobsInput):Promise<readonly MerchantAdminProviderJob[]>{const{parsed,authority}=this.authority(input,["tenantContext","now","kind"]),kind=merchantAdminProviderKind(parsed.kind);return this.read({text:"SELECT outcome,result_payload FROM saas.merchant_provider_list($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::text)",values:[...authorityValues(authority),kind]},"listed",(value)=>{const result=payload(value,["items"]);if(!Array.isArray(result.items)||result.items.length>100)throw unavailable();try{return Object.freeze(result.items.map(parseMerchantAdminProviderJob))}catch{throw unavailable()}})}
 async save(input:SaveMerchantAdminInput):Promise<MerchantAdminMutationResult>{const{parsed,authority}=this.authority(input,["tenantContext","now","operationId","kind","name","config","status"],["recordId","expectedVersion"]),operationId=merchantAdminUuid(parsed.operationId),existingId=parsed.recordId===undefined?undefined:merchantAdminUuid(parsed.recordId),expectedVersion=parsed.expectedVersion===undefined?undefined:merchantAdminVersion(parsed.expectedVersion);if((existingId===undefined)!==(expectedVersion===undefined))throw new MerchantAdminRepositoryError("invalid_input");const recordId=existingId??this.uuid(),kind=merchantAdminKind(parsed.kind),name=merchantAdminText(parsed.name),config=merchantAdminConfig(kind,parsed.config),status=merchantAdminStatus(parsed.status),fingerprint=merchantAdminFingerprint("save",authority.storeId,{recordId:existingId??null,expectedVersion:expectedVersion??null,kind,name,config,status});return this.mutate(authority,operationId,fingerprint,"saved",{text:"SELECT outcome,result_payload FROM saas.merchant_admin_save($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text,$10::uuid,$11::bigint,$12::text,$13::text,$14::jsonb,$15::text)",values:[...authorityValues(authority),operationId,fingerprint,recordId,expectedVersion??null,kind,name,JSON.stringify(config),status]},(value,replayed)=>{const result=this.mutation(value,replayed);if(!replayed&&result.id!==recordId)throw unavailable();return result})}
 async archive(input:ArchiveMerchantAdminInput):Promise<MerchantAdminMutationResult>{const{parsed,authority}=this.authority(input,["tenantContext","now","operationId","recordId","expectedVersion"]),operationId=merchantAdminUuid(parsed.operationId),recordId=merchantAdminUuid(parsed.recordId),expectedVersion=merchantAdminVersion(parsed.expectedVersion),fingerprint=merchantAdminFingerprint("archive",authority.storeId,{recordId,expectedVersion});return this.mutate(authority,operationId,fingerprint,"archived",{text:"SELECT outcome,result_payload FROM saas.merchant_admin_archive($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text,$10::uuid,$11::bigint)",values:[...authorityValues(authority),operationId,fingerprint,recordId,expectedVersion]},(value,replayed)=>{const result=this.mutation(value,replayed);if(result.id!==recordId||result.status!=="archived")throw unavailable();return result})}
 async prepareProviderJob(input:PrepareMerchantAdminProviderJobInput):Promise<MerchantAdminProviderJobMutationResult>{const{parsed,authority}=this.authority(input,["tenantContext","now","operationId","recordId","expectedRecordVersion","kind"]),operationId=merchantAdminUuid(parsed.operationId),recordId=merchantAdminUuid(parsed.recordId),expectedRecordVersion=merchantAdminVersion(parsed.expectedRecordVersion),kind=merchantAdminProviderKind(parsed.kind),jobId=this.uuid(),fingerprint=merchantAdminFingerprint("prepare_provider_job",authority.storeId,{recordId,expectedRecordVersion,kind});return this.mutate(authority,operationId,fingerprint,"prepared",{text:"SELECT outcome,result_payload FROM saas.merchant_provider_prepare($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text,$10::uuid,$11::uuid,$12::bigint,$13::text)",values:[...authorityValues(authority),operationId,fingerprint,jobId,recordId,expectedRecordVersion,kind]},(value,replayed)=>{const result=this.providerMutation(value,replayed);if(result.recordId!==recordId||result.recordKind!==kind||(!replayed&&result.id!==jobId)||result.status!=="awaiting_provider_activation")throw unavailable();return result},"merchant_provider_recover_operation")}
 async cancelProviderJob(input:CancelMerchantAdminProviderJobInput):Promise<MerchantAdminProviderJobMutationResult>{const{parsed,authority}=this.authority(input,["tenantContext","now","operationId","jobId","expectedVersion","kind"]),operationId=merchantAdminUuid(parsed.operationId),jobId=merchantAdminUuid(parsed.jobId),expectedVersion=merchantAdminVersion(parsed.expectedVersion),kind=merchantAdminProviderKind(parsed.kind),fingerprint=merchantAdminFingerprint("cancel_provider_job",authority.storeId,{jobId,expectedVersion,kind});return this.mutate(authority,operationId,fingerprint,"cancelled",{text:"SELECT outcome,result_payload FROM saas.merchant_provider_cancel($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text,$10::uuid,$11::bigint,$12::text)",values:[...authorityValues(authority),operationId,fingerprint,jobId,expectedVersion,kind]},(value,replayed)=>{const result=this.providerMutation(value,replayed);if(result.id!==jobId||result.recordKind!==kind||result.status!=="cancelled")throw unavailable();return result},"merchant_provider_recover_operation")}
}
