import type { MerchantAdminEvent,MerchantAdminJson,MerchantAdminMutationResult,MerchantAdminProviderJob,MerchantAdminProviderJobMutationResult,MerchantAdminProviderRecordKind,MerchantAdminRecord,MerchantAdminRecordKind,MerchantAdminRecordStatus,TenantContext } from "@celebix/saas-contracts";
import type { PostgresPoolLike,PostgresTimeoutOptions } from "../postgres/pool.ts";
export interface MerchantAdminAuthorityInput {readonly tenantContext:TenantContext;readonly now:Date}
export interface ListMerchantAdminInput extends MerchantAdminAuthorityInput {readonly kind:MerchantAdminRecordKind}
export interface ListMerchantAdminProviderJobsInput extends MerchantAdminAuthorityInput {readonly kind:MerchantAdminProviderRecordKind}
export interface SaveMerchantAdminInput extends ListMerchantAdminInput {readonly operationId:string;readonly recordId?:string;readonly expectedVersion?:number;readonly name:string;readonly config:Readonly<Record<string,MerchantAdminJson>>;readonly status:Exclude<MerchantAdminRecordStatus,"archived">}
export interface ArchiveMerchantAdminInput extends MerchantAdminAuthorityInput {readonly operationId:string;readonly recordId:string;readonly expectedVersion:number}
export interface PrepareMerchantAdminProviderJobInput extends ListMerchantAdminProviderJobsInput {readonly operationId:string;readonly recordId:string;readonly expectedRecordVersion:number}
export interface CancelMerchantAdminProviderJobInput extends ListMerchantAdminProviderJobsInput {readonly operationId:string;readonly jobId:string;readonly expectedVersion:number}
export interface MerchantAdminRepository {list(input:ListMerchantAdminInput):Promise<readonly MerchantAdminRecord[]>;listEvents(input:ListMerchantAdminInput):Promise<readonly MerchantAdminEvent[]>;listProviderJobs(input:ListMerchantAdminProviderJobsInput):Promise<readonly MerchantAdminProviderJob[]>;save(input:SaveMerchantAdminInput):Promise<MerchantAdminMutationResult>;archive(input:ArchiveMerchantAdminInput):Promise<MerchantAdminMutationResult>;prepareProviderJob(input:PrepareMerchantAdminProviderJobInput):Promise<MerchantAdminProviderJobMutationResult>;cancelProviderJob(input:CancelMerchantAdminProviderJobInput):Promise<MerchantAdminProviderJobMutationResult>}
export interface PostgresMerchantAdminRepositoryOptions {readonly pool:PostgresPoolLike;readonly role:"celebix_saas_app";readonly timeouts:PostgresTimeoutOptions;readonly uuid:()=>string;readonly audit:(event:Readonly<{type:"merchant_admin_commit_unknown"}>)=>void|Promise<void>}
