import {MERCHANT_ADMIN_PROVIDER_RECORD_KINDS,MERCHANT_ADMIN_RECORD_KINDS,parseMerchantAdminConfig,type MerchantAdminJson,type MerchantAdminProviderRecordKind,type MerchantAdminRecordKind} from "@celebix/saas-contracts";
import {catalogAuthority} from "../catalog/validation.ts";
import {MerchantAdminRepositoryError} from "./errors.ts";
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,CONTROL=/[\u0000-\u001f\u007f]/,SURROGATE=/(?:[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF])/,PERCENT=/%(?![0-9A-F]{2})/,MEDIA=/^https:\/\/[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)+\/[A-Za-z0-9._~!$&'()*+,;=:@%/-]*$/,DESTINATION=/^\/(?!\/)[A-Za-z0-9._~!$&'()*+,;=:@%/-]*(?:\?[A-Za-z0-9._~!$&'()*+,;=:@%&/-]+)?$/,LOCAL=/^[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+)*$/;
const ENCODER=new TextEncoder();
const CONFIG_KEYS:Readonly<Record<MerchantAdminRecordKind,readonly string[]>>=Object.freeze({discount:["code","discountType","value","minimumOrderCents","usageLimit"],lucky_wheel:["campaignMessage","terms","dailySpinLimit","prizeLabels"],email_campaign:["subject","audience","content","scheduledAt"],phone_campaign:["audience","script","scheduledAt"],whatsapp_campaign:["audience","message","scheduledAt"],blog_post:["slug","locale","excerpt","body","published"],page:["slug","locale","body","published"],policy:["policyType","locale","body","effectiveAt"],marketplace_connection:["provider","merchantReference","syncEnabled"],general_setting:["storeDisplayName","supportEmail","timezone"],language_setting:["defaultLocale","enabledLocales"],payment_setting:["enabledMethods","cashOnDelivery"],shipping_setting:["regions","freeShippingThresholdCents","estimatedDays"],administrator_invite:["email","role","expiresAt"],accounting_profile:["legalName","taxOffice","taxNumber","invoiceEmail"],invoice_integration:["provider","accountReference","enabled"],seo_control:["metaTitle","metaDescription","allowIndex"],sitemap:["includeProducts","includeContent","changeFrequency"],social_preview:["title","description","imageUrl"],code_integration:["provider","publicIdentifier","enabled"],indexing_request:["urls","reason"],notification_setting:["emailEnabled","smsEnabled","pushEnabled","senderLabel","replyToEmail"],hero_banner:["headline","body","imageUrl","destination","enabled"],promotion_banner:["headline","body","destination","startsAt","endsAt","enabled"],marquee_setting:["items","icon","speed","direction","animation","enabled"]});
const HTML=/<[^>]*>/;
function fail():never{throw new MerchantAdminRepositoryError("invalid_input")}
function byteLength(value:string){return ENCODER.encode(value).byteLength}
function canonicalText(value:unknown,min:number,max:number){if(typeof value!=="string"||byteLength(value)<min||byteLength(value)>max||value.startsWith(" ")||value.endsWith(" ")||CONTROL.test(value)||SURROGATE.test(value))fail();return value}
function object(value:unknown){if(typeof value!=="object"||value===null||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)fail();const keys=Reflect.ownKeys(value);if(keys.some((key)=>typeof key!=="string"))fail();const descriptors=Object.getOwnPropertyDescriptors(value);if(keys.some((key)=>{const descriptor=descriptors[key as string];return !descriptor||!descriptor.enumerable||!("value" in descriptor)}))fail();return Object.fromEntries((keys as string[]).map((key)=>[key,descriptors[key]!.value])) as Record<string,unknown>}
export function exactMerchantAdminInput(value:unknown,required:readonly string[],optional:readonly string[]=[]){const result=object(value),allowed=new Set([...required,...optional]);if(required.some((key)=>!Object.hasOwn(result,key))||Object.keys(result).some((key)=>!allowed.has(key)))fail();return result}
export function merchantAdminUuid(value:unknown){if(typeof value!=="string"||!UUID.test(value))fail();return value}
export function merchantAdminVersion(value:unknown){if(!Number.isSafeInteger(value)||(value as number)<1)fail();return value as number}
export function merchantAdminKind(value:unknown):MerchantAdminRecordKind{if(!MERCHANT_ADMIN_RECORD_KINDS.includes(value as never))fail();return value as MerchantAdminRecordKind}
export function merchantAdminProviderKind(value:unknown):MerchantAdminProviderRecordKind{const kind=merchantAdminKind(value);if(!MERCHANT_ADMIN_PROVIDER_RECORD_KINDS.includes(kind as never))fail();return kind as MerchantAdminProviderRecordKind}
export function merchantAdminText(value:unknown){return canonicalText(value,1,160)}
function settingText(value:unknown,max:number){const result=canonicalText(value,1,max);if(HTML.test(result))fail();return result}
function optionalBoolean(config:Readonly<Record<string,MerchantAdminJson>>,key:string){if(Object.hasOwn(config,key)&&typeof config[key]!=="boolean")fail()}
function optionalSettingText(config:Readonly<Record<string,MerchantAdminJson>>,key:string,max:number){if(Object.hasOwn(config,key))settingText(config[key],max)}
function pathIsCanonical(path:string){const question=path.indexOf("?"),primary=question<0?path:path.slice(0,question);if(PERCENT.test(path)||/%(?:2[eE]|2[fF])/.test(path)||primary.split("/").some((segment)=>segment==="."||segment===".."))fail()}
function optionalMediaUrl(config:Readonly<Record<string,MerchantAdminJson>>,key:string){if(!Object.hasOwn(config,key))return;const value=canonicalText(config[key],1,2048);if(!MEDIA.test(value))fail();try{const url=new URL(value);if(url.toString()!==value||url.protocol!=="https:"||url.username||url.password||url.port||url.hash||url.search||url.hostname.split(".").some((label)=>!label||!/^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/.test(label)))fail();pathIsCanonical(url.pathname)}catch{fail()}}
function optionalDestination(config:Readonly<Record<string,MerchantAdminJson>>,key:string){if(!Object.hasOwn(config,key))return;const value=canonicalText(config[key],1,2048);if(!DESTINATION.test(value))fail();try{const url=new URL(value,"https://destination.invalid");if(url.pathname+url.search!==value||url.hash||url.origin!=="https://destination.invalid")fail();pathIsCanonical(value)}catch{fail()}}
function optionalEmail(config:Readonly<Record<string,MerchantAdminJson>>,key:string){if(!Object.hasOwn(config,key))return;const value=canonicalText(config[key],3,254),parts=value.split("@"),local=parts[0],domain=parts[1];if(parts.length!==2||local===undefined||domain===undefined||!LOCAL.test(local)||local.startsWith(".")||local.endsWith("."))fail();const labels=domain.split(".");if(labels.length<2||labels.some((label)=>!label||!/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(label)))fail()}
function optionalTimestamp(config:Readonly<Record<string,MerchantAdminJson>>,key:string){if(!Object.hasOwn(config,key))return undefined;const value=config[key];if(typeof value!=="string"||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value))fail();try{if(new Date(value).toISOString()!==value)fail()}catch{fail()}return value}
function optionalEnum(config:Readonly<Record<string,MerchantAdminJson>>,key:string,values:readonly string[]){if(Object.hasOwn(config,key)&&(!values.includes(config[key] as string)))fail()}
function typedSettingsConfig(kind:MerchantAdminRecordKind,config:Readonly<Record<string,MerchantAdminJson>>){if(kind==="notification_setting"){for(const key of ["emailEnabled","smsEnabled","pushEnabled"])optionalBoolean(config,key);optionalSettingText(config,"senderLabel",160);optionalEmail(config,"replyToEmail");return}if(kind==="hero_banner"){optionalSettingText(config,"headline",160);optionalSettingText(config,"body",4000);optionalMediaUrl(config,"imageUrl");optionalDestination(config,"destination");optionalBoolean(config,"enabled");return}if(kind==="promotion_banner"){optionalSettingText(config,"headline",160);optionalSettingText(config,"body",4000);optionalDestination(config,"destination");const startsAt=optionalTimestamp(config,"startsAt"),endsAt=optionalTimestamp(config,"endsAt");if(startsAt!==undefined&&endsAt!==undefined&&startsAt>=endsAt)fail();optionalBoolean(config,"enabled");return}if(kind==="marquee_setting"){if(Object.hasOwn(config,"items")){const items=config.items;if(!Array.isArray(items)||items.length<1||items.length>12)fail();for(const item of items)settingText(item,160)}optionalEnum(config,"icon",["none","sparkle","truck","shield"]);optionalEnum(config,"speed",["slow","normal","fast"]);optionalEnum(config,"direction",["left","right"]);optionalEnum(config,"animation",["continuous","step"]);optionalBoolean(config,"enabled")}}
export function merchantAdminConfig(kind:MerchantAdminRecordKind,value:unknown):Readonly<Record<string,MerchantAdminJson>>{try{const parsed=parseMerchantAdminConfig(value),allowed=new Set(CONFIG_KEYS[kind]);if(Object.keys(parsed).some((key)=>!allowed.has(key)))fail();typedSettingsConfig(kind,parsed);return parsed}catch(error){if(error instanceof MerchantAdminRepositoryError)throw error;fail()}}
export function merchantAdminStatus(value:unknown):"draft"|"active"{if(value!=="draft"&&value!=="active")fail();return value}
export{catalogAuthority};
