"use client";
import {useCallback,useEffect,useMemo,useState,type FormEvent} from "react";
import type {CatalogWeightDeclaration,CatalogWeightEditorProjection,ProductVariant} from "@celebix/saas-contracts";
import {catalogWeightClient,CatalogWeightApiError} from "@/lib/catalog-weight-ui/client";
import styles from "./CatalogWeightEditor.module.css";

type Target=Readonly<{key:string;label:string;variant:ProductVariant|null;declaration:CatalogWeightDeclaration|null}>;
function grams(value:number){return (value/1000).toLocaleString("tr-TR",{maximumFractionDigits:3});}
function gramsMilli(value:FormDataEntryValue|null):number|null{if(typeof value!=="string"||!/^\d{1,6}(?:[.,]\d{1,3})?$/u.test(value.trim()))return null;const parsed=Number(value.replace(",","."));const result=Math.round(parsed*1000);return Number.isSafeInteger(result)&&result>0?result:null;}
function message(error:unknown){if(error instanceof CatalogWeightApiError&&error.code==="conflict")return"Ürün başka bir oturumda değişti. Güncel veriyi yükleyip yeniden deneyin.";return"Gramaj bilgisi tamamlanamadı. Lütfen yeniden deneyin.";}
function scopeLabel(value:CatalogWeightDeclaration["scope"]){return value==="net_metal"?"Net metal":value==="total_product"?"Toplam ürün":"Kapsam belirtilmemiş";}
function unitLabel(value:CatalogWeightDeclaration["salesUnit"]){return value==="single"?"Tek ürün":value==="pair"?"Çift":value==="set"?"Set":"Birim belirtilmemiş";}

export function CatalogWeightEditor({productId,variants,canManage,archived}:Readonly<{productId:string;variants:readonly ProductVariant[];canManage:boolean;archived:boolean}>){
  const[projection,setProjection]=useState<CatalogWeightEditorProjection>();const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[editing,setEditing]=useState<string>();const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
  const load=useCallback(async()=>{setError("");try{setProjection(await catalogWeightClient.get(productId));}catch(failure){setError(message(failure));}finally{setLoading(false);}},[productId]);
  useEffect(()=>{void load();},[load]);
  const targets=useMemo<readonly Target[]>(()=>{if(!projection)return[];const product=projection.declarations.find(item=>item.variantId===null)??null;return Object.freeze([{key:"product",label:"Ürün geneli",variant:null,declaration:product},...variants.map(variant=>({key:variant.id,label:variant.title,variant,declaration:projection.declarations.find(item=>item.variantId===variant.id)??null}))]);},[projection,variants]);
  if(loading)return <section className={`product-detail-section ${styles.section}`} aria-label="Ağırlık yükleniyor"><div className={styles.feedback} role="status">Ağırlık bilgisi yükleniyor…</div></section>;
  if(!projection){return <section className={`product-detail-section ${styles.section}`} aria-labelledby="catalog-weight-title"><div className={styles.header}><div><span className="eyebrow">TEKNİK BİLGİ</span><h2 id="catalog-weight-title">Ağırlık / Gramaj</h2></div></div><div className={`${styles.feedback} ${styles.error}`} role="alert">{error}</div></section>;}
  if(projection.profileMode===null)return null;
  async function save(event:FormEvent<HTMLFormElement>,target:Target){event.preventDefault();if(!canManage||archived||busy)return;const data=new FormData(event.currentTarget);const amount=gramsMilli(data.get("grams"));if(amount===null){setError("Geçerli bir gram değeri girin.");return;}const approximate=data.get("approximate")==="on";const toleranceText=String(data.get("tolerance")??"").trim();const tolerance=toleranceText===""?null:Number(toleranceText);if((tolerance!==null&&(!Number.isInteger(tolerance)||tolerance<1||tolerance>100))||(!approximate&&tolerance!==null)){setError("Tolerans yaklaşık değerlerde %1–100 arasında olmalıdır.");return;}setBusy(true);setError("");setNotice("");try{const declarationId=target.declaration?.id??crypto.randomUUID();const result=await catalogWeightClient.save(productId,{declarationId,expectedVariantVersion:target.variant?.version??null,intent:{operationId:crypto.randomUUID(),expectedProductVersion:projection!.productVersion,expectedDeclarationVersion:target.declaration?.version??0,target:{level:target.variant?"variant":"product",variantId:target.variant?.id??null},declaration:{gramsMilli:amount,scope:String(data.get("scope")) as CatalogWeightDeclaration["scope"],salesUnit:String(data.get("salesUnit")) as CatalogWeightDeclaration["salesUnit"],approximate,toleranceBasisPoints:tolerance===null?null:tolerance*100}}});setProjection(result);setEditing(undefined);setNotice("Gramaj kaydedildi. Fiyatlandırma yöntemi değiştirilmedi.");}catch(failure){setError(message(failure));}finally{setBusy(false);}}
  return <section className={`product-detail-section ${styles.section}`} aria-labelledby="catalog-weight-title">
    <div className={styles.header}><div><span className="eyebrow">TEKNİK BİLGİ</span><h2 id="catalog-weight-title">Ağırlık / Gramaj</h2><p>Üründe beyan edilen ağırlığı fiyat yönteminden bağımsız yönetin.</p></div><span className={styles.mode}>{projection.profileMode==="jewelry"?"Kuyumculuk profili":"Genel ürün profili"}</span></div>
    {error?<div className={`${styles.feedback} ${styles.error}`} role="alert">{error}</div>:null}{notice?<div className={styles.feedback} role="status">{notice}</div>:null}
    <div className={styles.grid}>{targets.map(target=>{const current=target.declaration;const open=editing===target.key;return <article className={styles.card} key={target.key}>
      <div className={styles.cardHead}><div><strong>{target.label}</strong><small>{target.variant?"Varyant düzeyi":"Ürün düzeyi"}</small></div><div className={styles.badges}>{current?<><span className={styles.badge}>{current.source==="description"?"Açıklamadan aktarıldı":"Manuel girildi"}</span>{!current.pricingVerified?<span className={`${styles.badge} ${styles.warning}`}>Fiyatlandırma için doğrulanmadı</span>:null}</>:<span className={styles.badge}>Gramaj girilmedi</span>}</div></div>
      {!open?<>{current?<><dl className={styles.facts}><div><dt>Gram</dt><dd>{grams(current.gramsMilli)} g</dd></div><div><dt>Tür</dt><dd>{scopeLabel(current.scope)}</dd></div><div><dt>Satış birimi</dt><dd>{unitLabel(current.salesUnit)}</dd></div><div><dt>Kesinlik</dt><dd>{current.approximate?current.toleranceBasisPoints?`Yaklaşık ±%${current.toleranceBasisPoints/100}`:"Yaklaşık":"Kesin beyan"}</dd></div></dl>{current.sourceExcerpt?<p className={styles.source}>{current.sourceExcerpt}</p>:null}</>:<p className={styles.empty}>Bu düzey için kayıtlı ağırlık yok.</p>}{canManage&&!archived?<div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} type="button" onClick={()=>setEditing(target.key)}>{current?"Düzenle":"Gramaj ekle"}</button></div>:null}</>:<form className={styles.form} onSubmit={event=>void save(event,target)} onKeyDown={event=>{if(event.key==="Escape"){event.preventDefault();setEditing(undefined);}}}>
        <div className={styles.fields}><label className={styles.field}>Gram<input name="grams" required inputMode="decimal" autoFocus defaultValue={current?String(current.gramsMilli/1000).replace(".",","):""}/></label><label className={styles.field}>Beyan türü<select name="scope" defaultValue={current?.scope??"unspecified"}><option value="unspecified">Belirtilmemiş</option><option value="total_product">Toplam ürün</option><option value="net_metal">Net metal</option></select></label><label className={styles.field}>Satış birimi<select name="salesUnit" defaultValue={current?.salesUnit??"unspecified"}><option value="unspecified">Belirtilmemiş</option><option value="single">Tek ürün</option><option value="pair">Çift</option><option value="set">Set</option></select></label><label className={styles.field}>Tolerans (%)<input name="tolerance" inputMode="numeric" min="1" max="100" type="number" defaultValue={current?.toleranceBasisPoints?current.toleranceBasisPoints/100:""}/></label></div>
        <label className={styles.check}><input name="approximate" type="checkbox" defaultChecked={current?.approximate??false}/> Yaklaşık değer</label><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} type="button" onClick={()=>setEditing(undefined)} disabled={busy}>Vazgeç</button><button className={styles.button} type="submit" disabled={busy}>{busy?"Kaydediliyor…":"Gramajı kaydet"}</button></div>
      </form>}</article>;})}</div>
  </section>;
}
