import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { accessSync, constants, existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync } from "node:fs";
import path from "node:path";
import { spawn, spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../../");
const SQL = path.join(ROOT, "apps/owner/scripts/sql/saas");
const PG16 = "/Users/Celebix/.codex/tmp/postgresql-16.14-install/bin";
const DB = "typed_storefront_settings";
const STORE = "10000000-0000-4000-8000-000000000001";
const STORE_B = "10000000-0000-4000-8000-000000000002";
const PLAN = "00000000-0000-4000-8000-000000000001";
const OWNER = "20000000-0000-4000-8000-000000000001";
const EDITOR = "20000000-0000-4000-8000-000000000003";
const ANALYST = "20000000-0000-4000-8000-000000000004";
const MO = "30000000-0000-4000-8000-000000000001";
const ME = "30000000-0000-4000-8000-000000000003";
const ML = "30000000-0000-4000-8000-000000000004";
const RECORD = "71000000-0000-4000-8000-000000000010";
const NOW = "2026-07-22T19:00:00.000Z";
const PRIOR = [
  "202607110001_roles.up.sql", "202607110002_foundation.up.sql", "202607110003_free_starter.seed.sql", "202607110003_plan_versions.freeze.sql", "202607110004_grants.sql", "202607110005_catalog_assertions.sql",
  "202607110007_identity_roles.up.sql", "202607110008_identity_persistence.up.sql", "202607110009_identity_grants.sql", "202607110010_identity_catalog_assertions.sql",
  "202607120012_verified_identity_snapshot.up.sql", "202607120013_verified_identity_grants.sql", "202607120014_verified_identity_catalog_assertions.sql", "202607140015_panel_sessions.up.sql", "202607140016_panel_session_handoffs.up.sql", "202607140017_panel_browser_bindings.up.sql",
  "202607160018_product_catalog.up.sql", "202607160018_product_catalog_assertions.sql", "202607160019_product_catalog_api.up.sql", "202607160019_product_catalog_api_assertions.sql", "202607160020_pilot_storefront_media_domains.up.sql", "202607160020_pilot_storefront_media_domains_assertions.sql",
  "202607200021_catalog_dashboard_summary.up.sql", "202607200021_catalog_dashboard_summary_assertions.sql", "202607210022_order_management.up.sql", "202607210022_order_management_assertions.sql", "202607210023_order_management_api.up.sql", "202607210023_order_management_api_assertions.sql", "202607220024_quick_order_links.up.sql", "202607220024_quick_order_links_assertions.sql", "202607220025_quick_order_links_api.up.sql", "202607220025_quick_order_links_api_assertions.sql", "202607220026_quick_order_checkout_runtime.up.sql", "202607220026_quick_order_checkout_runtime_assertions.sql", "202607220027_quick_order_checkout_api.up.sql", "202607220027_quick_order_checkout_api_assertions.sql", "202607220028_quick_order_redemption_expiry_authority.up.sql", "202607220028_quick_order_redemption_expiry_authority_assertions.sql", "202607220029_quick_order_settlement_authority.up.sql", "202607220029_quick_order_settlement_authority_assertions.sql", "202607220030_abandoned_carts.up.sql", "202607220030_abandoned_carts_assertions.sql", "202607220031_abandoned_cart_api.up.sql", "202607220031_abandoned_cart_api_assertions.sql", "202607220032_abandoned_cart_capture.up.sql", "202607220032_abandoned_cart_capture_assertions.sql", "202607220033_customer_management.up.sql", "202607220033_customer_management_assertions.sql", "202607220034_customer_management_api.up.sql", "202607220034_customer_management_api_assertions.sql", "202607220035_catalog_administration.up.sql", "202607220035_catalog_administration_assertions.sql", "202607220036_merchant_admin_modules.up.sql", "202607220036_merchant_admin_modules_assertions.sql", "202607220037_merchant_provider_preparation.up.sql", "202607220037_merchant_provider_preparation_assertions.sql", "202607220038_merchant_analytics.up.sql", "202607220038_merchant_analytics_assertions.sql"
];

function executable(name) { for (const directory of [PG16, ...(process.env.PATH ?? "").split(path.delimiter)]) { if (!directory) continue; const candidate = path.join(directory, name); try { accessSync(candidate, constants.X_OK); return candidate; } catch {} } throw new Error("DISPOSABLE_DB_EXECUTION_BLOCKED"); }
function command(program, args, options = {}) { const result = spawnSync(program, args, { cwd: ROOT, encoding: "utf8", input: options.input, env: { ...process.env, LC_ALL: "C", LANG: "C" }, maxBuffer: 64 * 1024 * 1024 }); if (result.error) throw result.error; if (!options.allowFailure && result.status !== 0) throw new Error(`${path.basename(program)} failed\n${result.stderr}`); return result; }
function start() { const executables = Object.fromEntries(["initdb", "pg_ctl", "psql"].map((name) => [name, executable(name)])); const root = mkdtempSync(path.join("/tmp", "ts-")); const data = path.join(root, "data"), socket = path.join(root, "socket"), port = 20000 + Math.floor(Math.random() * 15000); mkdirSync(socket, { mode: 0o700 }); command(executables.initdb, ["-D", data, "--auth=trust", "--username=postgres", "--no-locale"]); command(executables.pg_ctl, ["-D", data, "-o", `-k ${socket} -p ${port} -h ''`, "-l", path.join(root, "postgres.log"), "start"]); return { executables, root, data, socket, port, postmasterPid: Number.parseInt(readFileSync(path.join(data, "postmaster.pid"), "utf8"), 10) }; }
function stop(box) { if (!box) return; command(box.executables.pg_ctl, ["-D", box.data, "-m", "fast", "stop"], { allowFailure: true }); rmSync(box.root, { recursive: true, force: true }); }
function processIsAbsent(pid) { try { process.kill(pid, 0); return false; } catch (error) { return error?.code === "ESRCH"; } }
function psql(box, source, database = DB, options = {}) { return command(box.executables.psql, ["-h", box.socket, "-p", String(box.port), "-X", "-qAt", "-v", "ON_ERROR_STOP=1", "-U", "postgres", "-d", database], { input: source, allowFailure: options.allowFailure }); }
function psqlAsync(box, source) { return new Promise((resolve, reject) => { const child = spawn(box.executables.psql, ["-h", box.socket, "-p", String(box.port), "-X", "-qAt", "-v", "ON_ERROR_STOP=1", "-U", "postgres", "-d", DB], { cwd: ROOT, env: { ...process.env, LC_ALL: "C", LANG: "C" } }); let stdout = "", stderr = ""; child.stdout.on("data", (chunk) => { stdout += chunk; }); child.stderr.on("data", (chunk) => { stderr += chunk; }); child.on("error", reject); child.on("close", (status) => status === 0 ? resolve({ stdout, stderr }) : reject(new Error(stderr))); child.stdin.end(source); }); }
function apply(box, file) { psql(box, readFileSync(path.join(SQL, file), "utf8")); }
function authority({ store = STORE, principal = OWNER, membership = MO, plan = PLAN, code = "free_starter", version = 1, now = NOW } = {}) { return `'${store}'::uuid,'${principal}'::uuid,'${membership}'::uuid,'${plan}'::uuid,'${code}'::text,${version}::bigint,'${now}'::timestamptz`; }
function callSave(box, { operationId, recordId = RECORD, expected = "NULL", kind = "hero_banner", config = "{\"headline\":\"Yeni sezon\",\"body\":\"Göz atın\",\"imageUrl\":\"https://cdn.example.test/hero.webp\",\"destination\":\"/collections/new\",\"enabled\":true}", status = "active", actor = {} } = {}) { const out = psql(box, `SET ROLE celebix_saas_app; SELECT jsonb_build_object('outcome',outcome,'result_payload',result_payload) FROM saas.merchant_admin_save(${authority(actor)},'${operationId}'::uuid,'${"a".repeat(64)}'::text,'${recordId}'::uuid,${expected}::bigint,'${kind}'::text,'Ayar'::text,'${config}'::jsonb,'${status}'::text);`).stdout.trim(); return JSON.parse(out); }
function callArchive(box, operationId, expected = 1) { const out = psql(box, `SET ROLE celebix_saas_app; SELECT jsonb_build_object('outcome',outcome,'result_payload',result_payload) FROM saas.merchant_admin_archive(${authority()},'${operationId}'::uuid,'${"b".repeat(64)}'::text,'${RECORD}'::uuid,${expected}::bigint);`).stdout.trim(); return JSON.parse(out); }
function callList(box, kind, actor = {}) { const out = psql(box, `SET ROLE celebix_saas_app; SELECT jsonb_build_object('outcome',outcome,'result_payload',result_payload) FROM saas.merchant_admin_list(${authority(actor)},'${kind}'::text);`).stdout.trim(); return JSON.parse(out); }
function seed(box) { psql(box, `BEGIN; SET LOCAL ROLE celebix_saas_owner;
INSERT INTO saas.principals(id,issuer,subject,email,email_verified,created_at,updated_at) VALUES ('${OWNER}','https://id.test/oidc','owner','owner@test.invalid',true,'2026-01-01','2026-01-01'),('${EDITOR}','https://id.test/oidc','editor','editor@test.invalid',true,'2026-01-01','2026-01-01'),('${ANALYST}','https://id.test/oidc','analyst','analyst@test.invalid',true,'2026-01-01','2026-01-01');
INSERT INTO saas.stores(id,name,slug,status,locale,currency,theme_key,created_at,updated_at) VALUES('${STORE}','Settings A','settings-a','active','tr','TRY','default','2026-01-01','2026-01-01'),('${STORE_B}','Settings B','settings-b','active','tr','TRY','default','2026-01-01','2026-01-01');
INSERT INTO saas.memberships(id,principal_id,store_id,role,status,created_at,updated_at) VALUES('${MO}','${OWNER}','${STORE}','store_owner','active','2026-01-01','2026-01-01'),('${ME}','${EDITOR}','${STORE}','editor','active','2026-01-01','2026-01-01'),('${ML}','${ANALYST}','${STORE}','analyst','active','2026-01-01','2026-01-01');
INSERT INTO saas.subscriptions(id,store_id,plan_id,plan_code,plan_version,status,valid_from,created_at,updated_at) VALUES('70000000-0000-4000-8000-000000000001','${STORE}','${PLAN}','free_starter',1,'active','2026-01-01','2026-01-01','2026-01-01'); COMMIT;`); }

const TOTAL = 17; let count = 0;
async function scenario(name, run) { await run(); count += 1; console.log(`PASS ${count}/${TOTAL} ${name}`); }
async function main() { let box; let readyForCleanup = false; try {
  box = start(); psql(box, `CREATE DATABASE ${DB};`, "postgres"); for (const file of PRIOR) apply(box, file); seed(box); apply(box, "202607220039_typed_storefront_settings.up.sql"); apply(box, "202607220039_typed_storefront_settings_assertions.sql");
  await scenario("manifest pins every migration artifact", () => { const manifest = JSON.parse(readFileSync(path.join(SQL, "phase3h-merchant-completion-manifest.json"), "utf8")); assert.equal(manifest.artifacts.length, 6); for (const artifact of manifest.artifacts) assert.equal(createHash("sha256").update(readFileSync(path.join(SQL, artifact.file))).digest("hex"), artifact.sha256); });
  await scenario("PostgreSQL 16 applies typed storefront settings", () => { assert.match(psql(box, "SHOW server_version;").stdout, /^16\./); assert.equal(psql(box, "SELECT saas.merchant_admin_required_action('hero_banner',true);").stdout.trim(), "configuration.manage"); });
  await scenario("all four settings kinds create with finite configuration", () => { const configs = { notification_setting: '{"emailEnabled":true,"smsEnabled":false,"pushEnabled":true,"senderLabel":"Celebix","replyToEmail":"support@example.test"}', hero_banner: '{"headline":"Hero","body":"Göz atın","imageUrl":"https://cdn.example.test/hero.webp","destination":"/hero","enabled":true}', promotion_banner: '{"headline":"Promosyon","body":"Sınırlı süre","destination":"/sale","startsAt":"2026-07-22T19:00:00.000Z","endsAt":"2026-08-22T19:00:00.000Z","enabled":true}', marquee_setting: '{"items":["Free shipping"],"icon":"truck","speed":"normal","direction":"left","animation":"continuous","enabled":true}' }; for (const [index, [kind, config]] of Object.entries(configs).entries()) assert.equal(callSave(box, { operationId: `72000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`, recordId: `71000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`, kind, config }).outcome, "saved", kind); });
  await scenario("update is versioned and archive has no recovery path", () => { const saved = callSave(box, { operationId: "72000000-0000-4000-8000-000000000010", recordId: RECORD }); assert.equal(saved.outcome, "saved"); assert.equal(callSave(box, { operationId: "72000000-0000-4000-8000-000000000011", expected: 1, config: '{"headline":"Yeni","body":"Göz atın","imageUrl":"https://cdn.example.test/hero.webp","destination":"/collections/new","enabled":true}' }).result_payload.version, 2); assert.equal(callArchive(box, "72000000-0000-4000-8000-000000000012", 2).outcome, "archived"); assert.equal(callSave(box, { operationId: "72000000-0000-4000-8000-000000000013", expected: 3 }).outcome, "invalid_transition"); });
  await scenario("same operation replays and fingerprint mismatch denies", () => { const operationId = "72000000-0000-4000-8000-000000000020", recordId = "71000000-0000-4000-8000-000000000020"; assert.equal(callSave(box, { operationId, recordId, kind: "notification_setting", config: '{"emailEnabled":true}' }).outcome, "saved"); assert.equal(callSave(box, { operationId, recordId, kind: "notification_setting", config: '{"emailEnabled":true}' }).outcome, "operation_replayed"); const result = psql(box, `SET ROLE celebix_saas_app; SELECT outcome FROM saas.merchant_admin_save(${authority()},'${operationId}'::uuid,'${"c".repeat(64)}'::text,'${recordId}'::uuid,NULL::bigint,'notification_setting'::text,'Ayar'::text,'{"emailEnabled":true}'::jsonb,'active'::text);`).stdout.trim(); assert.equal(result, "operation_mismatch"); });
  await scenario("concurrent same operation has one durable record and one replay", async () => { const operationId = "72000000-0000-4000-8000-000000000030", recordId = "71000000-0000-4000-8000-000000000030"; const sql = `SET ROLE celebix_saas_app; SELECT outcome FROM saas.merchant_admin_save(${authority()},'${operationId}'::uuid,'${"d".repeat(64)}'::text,'${recordId}'::uuid,NULL::bigint,'marquee_setting'::text,'Ayar'::text,'{"items":["Duyuru"]}'::jsonb,'active'::text);`; const outputs = await Promise.all([psqlAsync(box, sql), psqlAsync(box, sql)]); const outcomes = outputs.map((output) => output.stdout.trim()).sort(); assert.deepEqual(outcomes, ["operation_replayed", "saved"]); assert.equal(psql(box, `SELECT count(*) FROM saas.merchant_admin_records WHERE id='${recordId}'::uuid;`).stdout.trim(), "1"); });
  await scenario("editor reads but cannot manage and analyst only reads", () => { assert.equal(callList(box, "hero_banner", { principal: EDITOR, membership: ME }).outcome, "listed"); assert.equal(callList(box, "hero_banner", { principal: ANALYST, membership: ML }).outcome, "listed"); assert.equal(callSave(box, { operationId: "72000000-0000-4000-8000-000000000040", recordId: "71000000-0000-4000-8000-000000000040", actor: { principal: EDITOR, membership: ME } }).outcome, "membership_denied"); assert.equal(callSave(box, { operationId: "72000000-0000-4000-8000-000000000041", recordId: "71000000-0000-4000-8000-000000000041", actor: { principal: ANALYST, membership: ML } }).outcome, "membership_denied"); });
  await scenario("disabled catalog feature fails closed", () => { psql(box, `ALTER TABLE saas.plan_features DISABLE TRIGGER plan_features_immutable; UPDATE saas.plan_features SET enabled=false WHERE plan_id='${PLAN}' AND feature_key='catalog'; ALTER TABLE saas.plan_features ENABLE TRIGGER plan_features_immutable;`); assert.equal(callList(box, "hero_banner").outcome, "feature_not_enabled"); psql(box, `ALTER TABLE saas.plan_features DISABLE TRIGGER plan_features_immutable; UPDATE saas.plan_features SET enabled=true WHERE plan_id='${PLAN}' AND feature_key='catalog'; ALTER TABLE saas.plan_features ENABLE TRIGGER plan_features_immutable;`); });
  await scenario("cross-store authority is denied without data disclosure", () => { assert.equal(callList(box, "hero_banner", { store: STORE_B }).outcome, "membership_denied"); });
  await scenario("application direct DML remains denied", () => { for (const statement of ["INSERT INTO saas.merchant_admin_records(id,store_id,record_kind,name,config,status,created_at,updated_at) VALUES('79999999-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001','hero_banner','x','{}','draft',now(),now())", "UPDATE saas.merchant_admin_records SET name='x' WHERE false", "DELETE FROM saas.merchant_admin_operations WHERE false"]) assert.notEqual(psql(box, `SET ROLE celebix_saas_app; ${statement};`, DB, { allowFailure: true }).status, 0); });
  await scenario("hostile configuration fails before mutation", () => { const hostile = ['{"smtpPassword":"x"}', '{"apiKey":"x"}', '{"pushToken":"x"}', '{"html":"<script>x</script>"}', '{"imageUrl":"http://cdn.example.test/hero.webp"}', '{"destination":"https://evil.test"}', '{"items":[]}', '{"startsAt":"2026-08-22T19:00:00.000Z","endsAt":"2026-07-22T19:00:00.000Z"}']; for (const [index, config] of hostile.entries()) assert.equal(callSave(box, { operationId: `72000000-0000-4000-8000-${String(50 + index).padStart(12, "0")}`, recordId: `71000000-0000-4000-8000-${String(50 + index).padStart(12, "0")}`, config }).outcome, "invalid_input"); });
  await scenario("existing merchant kinds retain their prior finite behavior", () => { assert.equal(callSave(box, { operationId: "72000000-0000-4000-8000-000000000070", recordId: "71000000-0000-4000-8000-000000000070", kind: "discount", config: '{"discountType":"percent","value":15}' }).outcome, "saved"); assert.equal(callList(box, "discount").outcome, "listed"); });
  await scenario("list and recovery allowlists include settings with exact configured action", () => { for (const kind of ["notification_setting", "hero_banner", "promotion_banner", "marquee_setting"]) { assert.equal(callList(box, kind).outcome, "listed"); assert.equal(psql(box, `SELECT saas.merchant_admin_required_action('${kind}',false);`).stdout.trim(), "configuration.read"); } });
  await scenario("function ACL is exact for settings authority", () => { const signature = "saas.merchant_admin_save(uuid,uuid,uuid,uuid,text,bigint,timestamp with time zone,uuid,text,uuid,bigint,text,text,jsonb,text)"; assert.equal(psql(box, `SELECT has_function_privilege('celebix_saas_app','${signature}','EXECUTE');`).stdout.trim(), "t"); for (const role of ["celebix_saas_identity", "celebix_saas_workflow", "celebix_saas_host_resolver", "celebix_saas_bootstrap", "celebix_saas_observability", "celebix_saas_migrator"]) assert.equal(psql(box, `SELECT has_function_privilege('${role}','${signature}','EXECUTE');`).stdout.trim(), "f"); });
  await scenario("rollback restores 038-era kind and helper definitions", () => { psql(box, "SET ROLE celebix_saas_owner; ALTER TABLE saas.merchant_admin_events DISABLE TRIGGER merchant_admin_events_immutable; ALTER TABLE saas.merchant_admin_operations DISABLE TRIGGER merchant_admin_operations_immutable; DELETE FROM saas.merchant_admin_operations; DELETE FROM saas.merchant_admin_events WHERE record_kind IN('notification_setting','hero_banner','promotion_banner','marquee_setting'); DELETE FROM saas.merchant_admin_records WHERE record_kind IN('notification_setting','hero_banner','promotion_banner','marquee_setting'); ALTER TABLE saas.merchant_admin_events ENABLE TRIGGER merchant_admin_events_immutable; ALTER TABLE saas.merchant_admin_operations ENABLE TRIGGER merchant_admin_operations_immutable;"); apply(box, "202607220039_typed_storefront_settings.down.sql"); assert.equal(psql(box, "SELECT saas.merchant_admin_required_action('hero_banner',true);").stdout.trim(), "integrations.manage"); assert.equal(psql(box, "SELECT saas.merchant_admin_config_valid('hero_banner','{}'::jsonb);").stdout.trim(), "t"); assert.equal(psql(box, "SELECT saas.merchant_admin_required_action('discount',true);").stdout.trim(), "promotions.manage"); });
  await scenario("reapply restores typed storefront authority", () => { apply(box, "202607220039_typed_storefront_settings.up.sql"); apply(box, "202607220039_typed_storefront_settings_assertions.sql"); assert.equal(callList(box, "hero_banner").outcome, "listed"); });
  assert.equal(count, TOTAL - 1); readyForCleanup = true;
} finally { const root = box?.root, data = box?.data, socket = box?.socket, postmasterPid = box?.postmasterPid; stop(box); if (readyForCleanup) { await scenario("cleanup removes the disposable cluster", () => { assert.equal(existsSync(root), false); assert.equal(existsSync(data), false); assert.equal(existsSync(socket), false); assert.equal(processIsAbsent(postmasterPid), true); }); assert.equal(count, TOTAL); console.log(`${TOTAL}/${TOTAL} PASS`); } }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
