export type SeoResourceKind = 'product' | 'category' | 'page' | 'blog';
export type SeoIndexing = 'inherit' | 'index' | 'noindex';
export interface SeoResource { id: string; kind: SeoResourceKind; name: string; path: string; locale: string; status: string; version: number; seoVersion: number; title: string | null; description: string | null; canonicalPath: string | null; indexing: SeoIndexing; effectiveTitle: string; effectiveDescription: string; effectiveCanonicalPath: string; allowIndex: boolean; imageUrl: string | null; updatedAt: string }
export interface SeoIssue { code: string; severity: 'error' | 'warning'; message: string; path: string | null; kind: SeoResourceKind | null; resourceId: string | null; fixHref: string }
export interface SeoSettings { version: number; metaTitle: string | null; metaDescription: string | null; allowIndex: boolean; socialTitle: string | null; socialDescription: string | null; socialAssetId: string | null; socialImageUrl: string | null; googleVerification: string | null; bingVerification: string | null; indexNowEnabled: boolean; hostname: string | null; eligible: boolean }
export interface SeoLink { id: string; version: number; sourceKind: SeoResourceKind; sourceId: string; targetKind: SeoResourceKind; targetId: string; sourcePath: string; targetPath: string; anchorText: string; enabled: boolean }
export type SeoNotificationStatus = 'queued' | 'received' | 'verification_pending' | 'retrying' | 'failed';
export interface SeoNotification { id: string; path: string; status: SeoNotificationStatus; httpStatus: number | null; attempts: number; requestedAt: string; nextAttemptAt: string | null; error: string | null }
export interface SeoOverview { totalResources: number; publishedResources: number; issues: SeoIssue[]; sitemap: { url: string | null; robotsUrl: string | null; entryCount: number }; check: { checked: number; total: number; status: 'idle' | 'running' | 'completed' | 'failed'; lastCheckedAt: string | null }; notifications: SeoNotification[]; settings: SeoSettings }
export interface SaveSeoResourceRequest { kind: SeoResourceKind; id: string; expectedVersion: number; expectedSeoVersion: number; title: string | null; description: string | null; canonicalPath: string | null; indexing: SeoIndexing }
export interface SaveSeoSettingsRequest { expectedVersion: number; metaTitle: string | null; metaDescription: string | null; allowIndex: boolean; socialTitle: string | null; socialDescription: string | null; socialAssetId: string | null; googleVerification: string | null; bingVerification: string | null; indexNowEnabled: boolean }
export interface SaveSeoLinkRequest { id: string | null; expectedVersion: number | null; sourceKind: SeoResourceKind; sourceId: string; targetKind: SeoResourceKind; targetId: string; anchorText: string; enabled: boolean; remove?: boolean }
export interface NotifySeoRequest { resources: { kind: SeoResourceKind; id: string }[] }
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
function fail(): never { throw new TypeError('Invalid SEO input'); }
export function seoExact(value: unknown, keys: string[], optional: string[] = []): Record<string, unknown> { if (!value || typeof value !== 'object' || Object.getPrototypeOf(value) !== Object.prototype) fail(); const ds = Object.getOwnPropertyDescriptors(value); if (Reflect.ownKeys(ds).some(k => typeof k !== 'string' || ![...keys, ...optional].includes(k) || !ds[k]!.enumerable || !('value' in ds[k]!)) || keys.some(k => !Object.hasOwn(ds, k))) fail(); return Object.fromEntries(Object.entries(ds).map(([k,d]) => [k,d.value])); }
export function seoUuid(value: unknown): string { if (typeof value !== 'string' || !UUID.test(value)) fail(); return value; }
export function seoKind(value: unknown): SeoResourceKind { if (!['product','category','page','blog'].includes(value as string)) fail(); return value as SeoResourceKind; }
export function seoVersion(value: unknown): number { if (!Number.isSafeInteger(value) || (value as number) < 0) fail(); return value as number; }
function text(value: unknown, max: number, bytes = false): string | null { if (value === null) return null; if (typeof value !== 'string' || value !== value.trim() || !value.length || (bytes ? new TextEncoder().encode(value).length : value.length) > max || /[\u0000-\u001f\u007f]/.test(value)) fail(); return value; }
function bool(value: unknown): boolean { if (typeof value !== 'boolean') fail(); return value; }
export function seoCanonicalPath(value: unknown): string | null { if (value === null) return null; if (typeof value !== 'string' || value.length > 2048 || !/^\/(?:urunler|products|blog|(?:urun|products|kategori|categories|pages|blog)\/[a-z0-9]+(?:-[a-z0-9]+)*)?(?:\?lang=[a-z]{2,3}(?:-[A-Z]{2})?)?$/.test(value) || /(?:^|\/)\.\.?(?:\/|$)|%2f|%5c|%2e/i.test(value)) fail(); return value; }
export function parseSaveSeoResourceRequest(value: unknown): SaveSeoResourceRequest { const r=seoExact(value,['kind','id','expectedVersion','expectedSeoVersion','title','description','canonicalPath','indexing']); if (!['inherit','index','noindex'].includes(r.indexing as string)) fail(); return {kind:seoKind(r.kind),id:seoUuid(r.id),expectedVersion:seoVersion(r.expectedVersion),expectedSeoVersion:seoVersion(r.expectedSeoVersion),title:text(r.title,r.kind==='product'?200:160,r.kind!=='product'),description:text(r.description,r.kind==='product'?500:4000,r.kind!=='product'),canonicalPath:seoCanonicalPath(r.canonicalPath),indexing:r.indexing as SeoIndexing}; }
export function parseSaveSeoSettingsRequest(value: unknown): SaveSeoSettingsRequest { const r=seoExact(value,['expectedVersion','metaTitle','metaDescription','allowIndex','socialTitle','socialDescription','socialAssetId','googleVerification','bingVerification','indexNowEnabled']); const token=(v:unknown)=>{const s=text(v,256);if(s!==null&&!/^[a-zA-Z0-9_-]+$/.test(s))fail();return s;};return {expectedVersion:seoVersion(r.expectedVersion),metaTitle:text(r.metaTitle,160,true),metaDescription:text(r.metaDescription,500,true),allowIndex:bool(r.allowIndex),socialTitle:text(r.socialTitle,160,true),socialDescription:text(r.socialDescription,500,true),socialAssetId:r.socialAssetId===null?null:seoUuid(r.socialAssetId),googleVerification:token(r.googleVerification),bingVerification:token(r.bingVerification),indexNowEnabled:bool(r.indexNowEnabled)}; }
export function parseSaveSeoLinkRequest(value: unknown): SaveSeoLinkRequest { const r=seoExact(value,['id','expectedVersion','sourceKind','sourceId','targetKind','targetId','anchorText','enabled'],['remove']);const result={id:r.id===null?null:seoUuid(r.id),expectedVersion:r.expectedVersion===null?null:seoVersion(r.expectedVersion),sourceKind:seoKind(r.sourceKind),sourceId:seoUuid(r.sourceId),targetKind:seoKind(r.targetKind),targetId:seoUuid(r.targetId),anchorText:text(r.anchorText,160)!,enabled:bool(r.enabled),...(r.remove===undefined?{}:{remove:bool(r.remove)})};if(!result.anchorText || (result.id===null)!==(result.expectedVersion===null)|| result.sourceKind===result.targetKind&&result.sourceId===result.targetId) fail();return result; }
export function parseNotifySeoRequest(value: unknown): NotifySeoRequest { const r=seoExact(value,['resources']);if(!Array.isArray(r.resources)||r.resources.length<1||r.resources.length>100)fail();const resources=r.resources.map(v=>{const t=seoExact(v,['kind','id']);return{kind:seoKind(t.kind),id:seoUuid(t.id)};});if(new Set(resources.map(v=>v.kind+v.id)).size!==resources.length)fail();return{resources}; }
