import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import pg from 'pg';
import { startAccountingFixture } from '../accounting-ledger/fixture.mjs';

const migration = '202610030203_catalog_category_size_guides';
const fixture = startAccountingFixture(201);
const pool = new pg.Pool({ ...fixture.connection, max: 6 });
const now = '2026-10-03T12:00:00.000Z';
const store = randomUUID(), otherStore = randomUUID(), principal = randomUUID(), analyst = randomUUID(), member = randomUUID(), analystMember = randomUUID(), otherMember = randomUUID();
const ring = randomUUID(), child = randomUUID(), grandchild = randomUUID(), necklace = randomUUID(), otherCategory = randomUUID(), archivedCategory = randomUUID();
const product = randomUUID(), childProduct = randomUUID(), unrelated = randomUUID(), multiple = randomUUID();
const guide = randomUUID(), childGuide = randomUUID(), necklaceGuide = randomUUID(), necklaceOperation = randomUUID();
const body = '<h2>İşletmenin ölçü açıklaması</h2>\n<table><tbody><tr><th>Ölçü</th><th>Açıklama</th></tr><tr><td>A</td><td>Örnek</td></tr></tbody></table>';
let count = 0;
const check = async (label, run) => { await run(); console.log(`PASS ${++count} ${label}`); };
const literal = value => `'${String(value).replaceAll("'", "''")}'`;
const guideConfig = (categoryIds = [ring], patch = {}) => ({ schemaVersion: 1, type: 'size_guide', heading: 'Ölçü rehberi', body, categoryIds, includeDescendants: true, enabled: true, ...patch });
let plan;
const authority = (actor = {}) => [actor.store ?? store, actor.principal ?? principal, actor.member ?? member, plan, 'free_starter', 1, now];
async function call(name, args, actor = {}) {
  const client = await pool.connect();
  try { await client.query('BEGIN;SET LOCAL ROLE celebix_saas_app'); const auth = authority(actor); const values = [...(actor.onboarding ? [...auth.slice(0, 6), 100, auth[6]] : auth), ...args]; const placeholders = values.map((_, i) => `$${i + 1}`).join(','); const result = await client.query(`SELECT outcome,result_payload FROM saas.${name}(${placeholders})`, values); await client.query('COMMIT'); return result.rows[0]; }
  catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
}
function save(id, config, expected = null, patch = {}) {
  const input = { id, config, expected, kind: patch.kind ?? 'extra', name: patch.name ?? `Guide ${id}`, slug: patch.slug ?? `guide-${id}`, description: null, productIds: patch.productIds ?? [] };
  const fingerprint = patch.fingerprint ?? createHash('sha256').update(JSON.stringify(input)).digest('hex');
  return call('catalog_admin_save_resource', [patch.operation ?? randomUUID(), fingerprint, input.id, input.expected, input.kind, input.name, input.slug, input.description, JSON.stringify(config), input.productIds], patch.actor);
}
async function merchandising(id = product, selectedStore = store) { return (await pool.query('SELECT saas.public_starter_product_merchandising($1,$2) value', [selectedStore, id])).rows[0].value; }
const expectedGuide = config => ({ heading: config.heading, body: config.body });
const inventory = async () => (await pool.query("SELECT oid::regprocedure::text identity,pg_get_functiondef(oid) definition,proowner owner,proacl::text acl,proconfig settings,prosecdef security FROM pg_proc WHERE pronamespace='saas'::regnamespace AND proname IN ('catalog_admin_save_resource','public_starter_product_merchandising','catalog_get_onboarding_options','catalog_get_onboarding_choices','catalog_get_product_choices','catalog_onboard_product','catalog_update_merchandising') ORDER BY oid::regprocedure::text")).rows;
try {
  plan = (await pool.query("SELECT id FROM saas.plans WHERE plan_code='free_starter' AND version=1")).rows[0].id;
  await pool.query("INSERT INTO saas.principals(id,issuer,subject,email,email_verified,created_at,updated_at) VALUES($1,'https://guides.invalid/oidc',$1::uuid::text,'owner@guides.invalid',true,'2026-01-01','2026-01-01'),($2,'https://guides.invalid/oidc',$2::uuid::text,'analyst@guides.invalid',true,'2026-01-01','2026-01-01')", [principal, analyst]);
  for (const [id, membership] of [[store, member], [otherStore, otherMember]]) {
    await pool.query("INSERT INTO saas.stores(id,name,slug,status,locale,currency,theme_key,created_at,updated_at) VALUES($1,'Synthetic guides',$2,'active','tr','TRY','hemenaku','2026-01-01','2026-01-01')", [id, `guides-${id}`]);
    await pool.query("INSERT INTO saas.memberships(id,principal_id,store_id,role,status,created_at,updated_at) VALUES($1,$2,$3,'store_owner','active','2026-01-01','2026-01-01')", [membership, principal, id]);
    await pool.query("INSERT INTO saas.subscriptions(id,store_id,plan_id,plan_code,plan_version,status,valid_from,created_at,updated_at) VALUES($1,$2,$3,'free_starter',1,'active','2026-01-01','2026-01-01','2026-01-01')", [randomUUID(), id, plan]);
  }
  await pool.query("INSERT INTO saas.memberships(id,principal_id,store_id,role,status,created_at,updated_at) VALUES($1,$2,$3,'analyst','active','2026-01-01','2026-01-01')", [analystMember, analyst, store]);
  for (const [id, tenant, parent, position, status] of [[ring, store, null, 0, 'active'], [child, store, ring, 0, 'active'], [grandchild, store, child, 0, 'active'], [necklace, store, null, 1, 'active'], [otherCategory, otherStore, null, 0, 'active'], [archivedCategory, store, null, 2, 'archived']]) await pool.query("INSERT INTO saas.catalog_categories(id,store_id,parent_id,name,slug,position,status,version,created_at,updated_at,archived_at) VALUES($1,$2,$3,$4,$4,$5,$6,1,'2026-01-01','2026-01-01',CASE WHEN $6='archived' THEN '2026-01-01'::timestamptz END)", [id, tenant, parent, `category-${id}`, position, status]);
  for (const [id, categories] of [[product, [ring]], [childProduct, [grandchild]], [unrelated, [necklace]], [multiple, [ring, necklace]]]) { await pool.query("INSERT INTO saas.products(id,store_id,slug,title,status,currency,version,created_at,updated_at) VALUES($1,$2,$3,'Synthetic guide product','active','TRY',1,'2026-01-01','2026-01-01')", [id, store, `product-${id}`]); for (let position = 0; position < categories.length; position++) await pool.query('INSERT INTO saas.catalog_product_categories(store_id,product_id,category_id,position) VALUES($1,$2,$3,$4)', [store, id, categories[position], position]); }
  const before = await inventory();
  if (!process.argv.includes('--baseline')) {
    await check('203 applies, exactly rolls back before writes, reapplies and preserves authority', async () => { fixture.apply(`${migration}.up.sql`); const after = await inventory(); assert.deepEqual(after.map(({ definition, ...row }) => row), before.map(({ definition, ...row }) => row)); fixture.apply(`${migration}_assertions.sql`); fixture.apply(`${migration}.down.sql`); assert.deepEqual(await inventory(), before); fixture.apply(`${migration}.up.sql`); fixture.apply(`${migration}_assertions.sql`); });
  }
  await check('merchant guide reaches existing category products using the unchanged public shape', async () => { assert.equal((await save(guide, guideConfig())).outcome, 'saved'); assert.deepEqual((await merchandising())?.sizeGuide, expectedGuide(guideConfig())); assert.equal((await merchandising(unrelated))?.sizeGuide, undefined); });
  await check('product creation choices exclude category guides for old and current callers', async () => { for (const name of ['catalog_get_onboarding_options', 'catalog_get_onboarding_options_v2']) { const options = await call(name, [], { onboarding: true }); assert.equal(options.outcome, 'found'); assert.equal(options.result_payload.resources.some(resource => resource.id === guide), false); } });
  await check('direct product assignment cannot turn an automatic guide into a product option', async () => { await assert.rejects(() => pool.query('INSERT INTO saas.catalog_admin_resource_products VALUES($1,$2,$3,0)', [store, guide, product]), /CATEGORY_SIZE_GUIDE_DIRECT_PRODUCT_ASSIGNMENT_INVALID/); });
  await check('new products inherit at read time with no direct resource assignments', async () => { const id = randomUUID(); await pool.query("INSERT INTO saas.products(id,store_id,slug,title,status,currency,version,created_at,updated_at) VALUES($1,$2,$3,'Later product','active','TRY',1,'2026-01-01','2026-01-01')", [id, store, `product-${id}`]); await pool.query('INSERT INTO saas.catalog_product_categories VALUES($1,$2,$3,0)', [store, id, ring]); assert.deepEqual((await merchandising(id)).sizeGuide, expectedGuide(guideConfig())); assert.equal((await pool.query('SELECT count(*)::int total FROM saas.catalog_admin_resource_products WHERE resource_id=$1', [guide])).rows[0].total, 0); });
  await check('descendants inherit, disabling inheritance removes the descendant match', async () => { assert.deepEqual((await merchandising(childProduct)).sizeGuide, expectedGuide(guideConfig())); assert.equal((await save(guide, guideConfig([ring], { includeDescendants: false }), 1)).outcome, 'saved'); assert.equal((await merchandising(childProduct))?.sizeGuide, undefined); assert.equal((await save(guide, guideConfig(), 2)).outcome, 'saved'); });
  await check('nearest child guide wins over an ancestor and ordered direct categories resolve ties', async () => { const specific = guideConfig([child], { heading: 'Child guide' }); assert.equal((await save(childGuide, specific)).outcome, 'saved'); assert.deepEqual((await merchandising(childProduct)).sizeGuide, expectedGuide(specific)); const next = guideConfig([necklace], { heading: 'Necklace guide' }); assert.equal((await save(necklaceGuide, next, null, { operation: necklaceOperation })).outcome, 'saved'); assert.deepEqual((await merchandising(multiple)).sizeGuide, expectedGuide(guideConfig())); await pool.query('UPDATE saas.catalog_product_categories SET position=CASE WHEN category_id=$3 THEN 0 ELSE 1 END WHERE store_id=$1 AND product_id=$2', [store, multiple, necklace]); assert.deepEqual((await merchandising(multiple)).sizeGuide, expectedGuide(next)); });
  await check('strict config, reserved type, categories, and empty direct product relations are enforced by SQL', async () => { const bad = [guideConfig([]), guideConfig([ring, ring]), guideConfig([otherCategory]), guideConfig([archivedCategory]), guideConfig([ring], { schemaVersion: 2 }), guideConfig([ring], { extra: true }), guideConfig([ring], { enabled: 'true' }), guideConfig([ring], { body: '\t\r\n ' }), guideConfig([ring], { body: '\u00a0\u2003', enabled: false }), guideConfig([ring], { heading: '\u00a0leading', enabled: false }), guideConfig([ring], { body: 'x'.repeat(10001) }), guideConfig([ring], { body: '🙂'.repeat(5001) }), guideConfig([ring], { heading: ' leading' }), guideConfig([ring], { body: 'text\u001f' })]; for (const config of bad) assert.equal((await save(randomUUID(), config)).outcome, 'invalid_input'); assert.equal((await save(randomUUID(), guideConfig(), null, { productIds: [product] })).outcome, 'invalid_input'); assert.equal((await save(randomUUID(), guideConfig(), null, { kind: 'definition' })).outcome, 'invalid_input'); });
  await check('existing merchandising writes reject direct guide assignment with invalid_input', async () => { const payload = { profile: { minimumPurchaseQuantity: 1 }, categoryIds: [ring], resourceIds: { collections: [], tags: [], attributes: [], extras: [guide], definitions: [] }, channelIds: [] }; assert.equal((await call('catalog_update_merchandising', [randomUUID(), 'a'.repeat(64), product, 1, JSON.stringify(payload)], { onboarding: true })).outcome, 'invalid_input'); });
  await check('10k formatted Turkish body passes only the typed guide boundary', async () => { const long = '<p>' + 'ö'.repeat(9993) + '</p>'; assert.equal(long.length, 10000); assert.equal((await save(guide, guideConfig([ring], { body: long }), 3)).outcome, 'saved'); assert.equal((await merchandising()).sizeGuide.body, long); assert.equal((await save(randomUUID(), { options: ['x'.repeat(10000)], priceAdjustmentCents: 0 })).outcome, 'invalid_input'); });
  await check('existing guide cannot become an ordinary option and CAS prevents overwrites', async () => { assert.equal((await save(guide, { options: ['A'], priceAdjustmentCents: 0 }, 4)).outcome, 'invalid_transition'); assert.equal((await save(guide, guideConfig(), 3)).outcome, 'version_conflict'); assert.equal((await save(guide, guideConfig(), 4)).outcome, 'saved'); });
  await check('same operation replays once while changed fingerprint is rejected', async () => { const operation = randomUUID(); const config = guideConfig([ring], { enabled: false }); const first = await save(guide, config, 5, { operation }); assert.equal(first.outcome, 'saved'); assert.equal((await save(guide, config, 5, { operation })).outcome, 'operation_replayed'); assert.equal((await save(guide, guideConfig(), 5, { operation })).outcome, 'operation_mismatch'); assert.equal((await merchandising())?.sizeGuide, undefined); });
  await check('ordinary extra options keep their existing config and product assignments', async () => { const id = randomUUID(), config = { options: ['Hediye paketi'], priceAdjustmentCents: 25 }; assert.equal((await save(id, config, null, { productIds: [product] })).outcome, 'saved'); const resource = await call('catalog_admin_get_resource', ['extra', id]); assert.deepEqual(resource.result_payload.config, config); assert.deepEqual(resource.result_payload.productIds, [product]); });
  await check('simultaneous direct assignment commits one guide and reports a useful conflict', async () => { const blocker = await pool.connect(); await blocker.query('BEGIN'); await blocker.query("SELECT pg_advisory_xact_lock(hashtextextended('saas.catalog.store:'||$1::text,0))", [store]); const attempts = [randomUUID(), randomUUID()].map(id => save(id, guideConfig())); let waiting = false; for (let attempt = 0; attempt < 150 && !waiting; attempt++) { const result = await pool.query("SELECT count(*)::int total FROM pg_locks WHERE locktype='advisory' AND NOT granted AND objid=(hashtextextended('saas.catalog.store:'||$1::text,0)&4294967295)::oid", [store]); waiting = result.rows[0].total === 2; if (!waiting) await new Promise(resolve => setTimeout(resolve, 10)); } await blocker.query('COMMIT'); blocker.release(); const outcomes = (await Promise.all(attempts)).map(result => result.outcome).sort(); assert.equal(waiting, true, 'both saves must wait behind actual store serialization'); assert.deepEqual(outcomes, ['category_guide_conflict', 'saved']); });
  await check('simultaneous retries with one operation key commit once and replay the frozen result', async () => { const id = randomUUID(), operation = randomUUID(), config = guideConfig([ring], { enabled: false }); const outcomes = (await Promise.all([save(id, config, null, { operation }), save(id, config, null, { operation })])).map(result => result.outcome).sort(); assert.deepEqual(outcomes, ['operation_replayed', 'saved']); assert.equal((await pool.query('SELECT count(*)::int total FROM saas.catalog_admin_operations WHERE operation_id=$1', [operation])).rows[0].total, 1); });
  await check('disabled and archived guides free their category and preserve the old product fallback', async () => { const fallback = randomUUID(); await pool.query("INSERT INTO saas.catalog_admin_resources(id,store_id,resource_kind,name,slug,config,status,version,created_at,updated_at) VALUES($1,$2,'definition','Legacy guide',$3,$4,'active',1,'2026-01-01','2026-01-01')", [fallback, store, `legacy-${fallback}`, JSON.stringify({ role: 'size_guide', heading: 'Old direct guide', body: 'Legacy body' })]); await pool.query('INSERT INTO saas.catalog_admin_resource_products VALUES($1,$2,$3,0)', [store, fallback, product]); const active = (await pool.query("SELECT id,version FROM saas.catalog_admin_resources WHERE store_id=$1 AND resource_kind='extra' AND status='active' AND config->>'type'='size_guide' AND config->'categoryIds' ? $2 AND config->'enabled'='true'::jsonb", [store, ring])).rows[0]; assert.equal((await call('catalog_admin_archive_resource', [randomUUID(), 'a'.repeat(64), active.id, active.version])).outcome, 'archived'); assert.deepEqual((await merchandising()).sizeGuide, { heading: 'Old direct guide', body: 'Legacy body' }); assert.equal((await save(guide, guideConfig(), 6)).outcome, 'saved'); assert.deepEqual((await merchandising()).sizeGuide, expectedGuide(guideConfig())); });
  await check('category changes and category archives immediately remove obsolete inherited guides', async () => { await pool.query('UPDATE saas.catalog_product_categories SET category_id=$3 WHERE store_id=$1 AND product_id=$2', [store, childProduct, necklace]); assert.equal((await merchandising(childProduct)).sizeGuide.heading, 'Necklace guide'); await pool.query("UPDATE saas.catalog_categories SET status='archived',archived_at=$2,version=version+1,updated_at=$2 WHERE id=$1", [necklace, now]); assert.equal((await merchandising(childProduct))?.sizeGuide, undefined); assert.equal((await save(necklaceGuide, guideConfig([necklace], { enabled: false }), 1)).outcome, 'invalid_input'); assert.equal((await save(necklaceGuide, guideConfig([necklace], { heading: 'Necklace guide' }), null, { operation: necklaceOperation })).outcome, 'operation_replayed'); });
  await check('archived products cease inheriting a category guide', async () => { const id = randomUUID(); await pool.query("INSERT INTO saas.products(id,store_id,slug,title,status,currency,version,created_at,updated_at) VALUES($1,$2,$3,'Archived guide fixture','active','TRY',1,'2026-01-01','2026-01-01')", [id, store, `product-${id}`]); await pool.query('INSERT INTO saas.catalog_product_categories VALUES($1,$2,$3,0)', [store, id, ring]); assert.deepEqual((await merchandising(id)).sizeGuide, expectedGuide(guideConfig())); await pool.query("UPDATE saas.products SET status='archived',archived_at=$2,version=version+1,updated_at=$2 WHERE id=$1", [id, now]); assert.equal((await merchandising(id))?.sizeGuide, undefined); });
  await check('foreign-store resource reads and analyst writes are denied', async () => { assert.equal((await call('catalog_admin_get_resource', ['extra', guide], { store: otherStore, member: otherMember })).outcome, 'resource_not_found'); assert.equal((await save(randomUUID(), guideConfig(), null, { actor: { principal: analyst, member: analystMember } })).outcome, 'membership_denied'); assert.equal((await merchandising(product, otherStore))?.sizeGuide, undefined); });
  await check('function-only privileges, forced RLS and rollback retain all merchant guide data', async () => { assert.equal(fixture.value("SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid='saas.catalog_size_guides_203_backup'::regclass"), 't'); assert.equal(fixture.value("SELECT has_table_privilege('celebix_saas_app','saas.catalog_admin_resources','INSERT,UPDATE,DELETE')"), 'f'); const denied = fixture.sql(readFileSync(new URL(`../../../apps/owner/scripts/sql/saas/${migration}.down.sql`, import.meta.url), 'utf8'), true); assert.notEqual(denied.status, 0); assert.match(denied.stderr, /CATEGORY_SIZE_GUIDE_ROLLBACK_REQUIRES_DATA_RECOVERY/); assert.deepEqual((await merchandising()).sizeGuide, expectedGuide(guideConfig())); fixture.apply(`${migration}_assertions.sql`); });
  console.log(`CATEGORY_SIZE_GUIDES_POSTGRESQL16_COMPLETE ${count}/${count}`);
} finally { await pool.end(); fixture.stop(); }
