import { parseCustomerDetail,parseCustomerListItem,parseCustomerMutationResult,parseCustomerSegment,parseCustomerSummary,parseCustomerTag,parseCustomerWorkspace,type CustomerListItem,type CustomerMutationResult,type CustomerSegment,type CustomerTag,type TenantContext } from "@celebix/saas-contracts";
import { acquirePostgresClient,type PostgresClientLike } from "../postgres/pool.ts";import type { ValidatedOrderAuthority } from "../orders/validation.ts";import { customerFingerprint } from "./canonical.ts";import { decodeCustomerCursor,encodeCustomerCursor,parseDatabaseCustomerCursor } from "./cursor.ts";import { CUSTOMER_ERROR_CODES,CustomerRepositoryError,type CustomerErrorCode } from "./errors.ts";import type { AddCustomerNoteInput,ArchiveCustomerInput,CustomerAuthorityInput,CustomerExport,CustomerRepository,GetCustomerInput,ListCustomersInput,ListCustomersResult,PostgresCustomerRepositoryOptions,SaveCustomerInput,SetCustomerTaxonomyInput,UpsertCustomerSegmentInput,UpsertCustomerTagInput } from "./types.ts";import { customerAddress,customerAuthority,customerColor,customerConsent,customerEmail,customerPageSize,customerPhone,customerSearch,customerStatus,customerText,customerUuid,customerVersion,exactCustomerInput,uniqueIds } from "./validation.ts";
type Spec=Readonly<{text:string;values:unknown[]}>;const CODES=new Set<string>(CUSTOMER_ERROR_CODES);
function unavailable():CustomerRepositoryError{return new CustomerRepositoryError("unavailable")}
function timeout(v:number){if(!Number.isSafeInteger(v)||v<1||v>60000)throw unavailable();return `${v}ms`}
function release(c:PostgresClientLike,destroy?:boolean){try{c.release(destroy)}catch{}}
function payload(v:unknown,keys:readonly string[]){if(typeof v!=="object"||v===null||Array.isArray(v))throw unavailable();const r=v as Record<string,unknown>;if(Object.keys(r).sort().join(",")!==[...keys].sort().join(","))throw unavailable();return r}
function row(v:Readonly<{rows:unknown[];rowCount?:number|null}>){if(v.rowCount!==1||v.rows.length!==1)throw unavailable();const r=payload(v.rows[0],["outcome","result_payload"]);if(typeof r.outcome!=="string")throw unavailable();return{outcome:r.outcome,result:r.result_payload}}
function authorityValues(a:ValidatedOrderAuthority){return[a.storeId,a.principalId,a.membershipId,a.planId,a.planCode,a.planVersion,a.now]}
type RecoverParser<T>=(v:unknown,replayed:boolean)=>T;

export class PostgresCustomerRepository implements CustomerRepository{
 private readonly options:PostgresCustomerRepositoryOptions;
 constructor(options:PostgresCustomerRepositoryOptions){try{if(!options||typeof options!=="object"||Array.isArray(options)||Object.keys(options).sort().join(",")!=="audit,pool,role,timeouts,uuid"||options.role!=="celebix_saas_app"||typeof options.audit!=="function"||typeof options.uuid!=="function"||!options.timeouts||Object.keys(options.timeouts).sort().join(",")!=="idleTransactionMs,lockMs,poolCheckoutMs,statementMs")throw unavailable();for(const v of Object.values(options.timeouts))timeout(v);this.options=Object.freeze({...options,timeouts:Object.freeze({...options.timeouts})})}catch(e){if(e instanceof CustomerRepositoryError)throw e;throw unavailable()}}
 private async acquire(){try{return await acquirePostgresClient(this.options.pool,this.options.timeouts.poolCheckoutMs)}catch{throw unavailable()}}
 private async configure(c:PostgresClientLike){await c.query("SELECT pg_catalog.set_config('statement_timeout', $1, true)",[timeout(this.options.timeouts.statementMs)]);await c.query("SELECT pg_catalog.set_config('lock_timeout', $1, true)",[timeout(this.options.timeouts.lockMs)]);await c.query("SELECT pg_catalog.set_config('idle_in_transaction_session_timeout', $1, true)",[timeout(this.options.timeouts.idleTransactionMs)]);await c.query("SET LOCAL ROLE celebix_saas_app")}
 private expected(outcome:string){return CODES.has(outcome)?new CustomerRepositoryError(outcome as CustomerErrorCode):undefined}
 private async rollback(c:PostgresClientLike){try{await c.query("ROLLBACK");release(c)}catch{release(c,true)}}
 private async read<T>(spec:Spec,expected:string,parser:(v:unknown)=>T){const c=await this.acquire();let began=false,terminal=false;try{await c.query("BEGIN READ ONLY");began=true;await this.configure(c);const r=row(await c.query(spec.text,spec.values));const e=this.expected(r.outcome);if(e)throw e;if(r.outcome!==expected)throw unavailable();const parsed=parser(r.result);try{await c.query("COMMIT");terminal=true;release(c)}catch{terminal=true;release(c,true);throw unavailable()}return parsed}catch(e){if(began&&!terminal)await this.rollback(c);else if(!began&&!terminal)release(c,true);if(e instanceof CustomerRepositoryError)throw e;throw unavailable()}}
 private audit(){try{const p=this.options.audit({type:"customer_commit_unknown"});if(p)void p.catch(()=>undefined)}catch{}}
 private async recover<T>(a:ValidatedOrderAuthority,operationId:string,fingerprint:string,parser:RecoverParser<T>){return this.read({text:`SELECT outcome,result_payload FROM saas.customers_recover_operation($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text)`,values:[...authorityValues(a),operationId,fingerprint]},"operation_replayed",v=>parser(v,true))}
 private async mutate<T>(a:ValidatedOrderAuthority,operationId:string,fingerprint:string,spec:Spec,parser:RecoverParser<T>){const c=await this.acquire();let began=false,terminal=false;try{await c.query("BEGIN ISOLATION LEVEL READ COMMITTED");began=true;await this.configure(c);const r=row(await c.query(spec.text,spec.values));const e=this.expected(r.outcome);if(e)throw e;if(r.outcome!=="committed"&&r.outcome!=="operation_replayed")throw unavailable();const parsed=parser(r.result,r.outcome==="operation_replayed");try{await c.query("COMMIT");terminal=true;release(c);return parsed}catch{terminal=true;release(c,true);this.audit();return await this.recover(a,operationId,fingerprint,parser)}}catch(e){if(began&&!terminal)await this.rollback(c);else if(!began&&!terminal)release(c,true);if(e instanceof CustomerRepositoryError)throw e;throw unavailable()}}
 private authority(input:unknown,required:readonly string[],optional:readonly string[]=[]){const x=exactCustomerInput(input,required,optional);return{x,a:customerAuthority(x.tenantContext as TenantContext,x.now as Date)}}
 private uuid(){try{return customerUuid(this.options.uuid())}catch{throw unavailable()}}
 async getSummary(input:CustomerAuthorityInput){const{a}=this.authority(input,["tenantContext","now"]);return this.read({text:`SELECT outcome,result_payload FROM saas.customers_summary($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz)`,values:authorityValues(a)},"summarized",v=>{try{return parseCustomerSummary(v)}catch{throw unavailable()}})}
 async list(input:ListCustomersInput):Promise<ListCustomersResult>{const{x,a}=this.authority(input,["tenantContext","now","pageSize"],["cursor","status","search"]);const pageSize=customerPageSize(x.pageSize),status=customerStatus(x.status),search=customerSearch(x.search),cursor=decodeCustomerCursor(x.cursor as string|undefined,a.storeId,status,search);return this.read({text:`SELECT outcome,result_payload FROM saas.customers_list($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::text,$9::text,$10::bigint,$11::timestamptz,$12::uuid)`,values:[...authorityValues(a),status??null,search??null,pageSize,cursor?.updatedAt??null,cursor?.id??null]},"listed",v=>{const r=payload(v,Object.hasOwn(v as object,"nextCursor")?["items","nextCursor"]:["items"]);if(!Array.isArray(r.items)||r.items.length>pageSize)throw unavailable();let items:readonly CustomerListItem[];try{items=Object.freeze(r.items.map(parseCustomerListItem))}catch{throw unavailable()}for(let i=1;i<items.length;i++)if(items[i-1]!.updatedAt<items[i]!.updatedAt||(items[i-1]!.updatedAt===items[i]!.updatedAt&&items[i-1]!.id<=items[i]!.id))throw unavailable();if(!Object.hasOwn(r,"nextCursor"))return Object.freeze({items});if(items.length!==pageSize||items.length===0)throw unavailable();const c=parseDatabaseCustomerCursor(r.nextCursor,items.at(-1)!);return Object.freeze({items,nextCursor:encodeCustomerCursor(a.storeId,status,search,c)})})}
 async get(input:GetCustomerInput){const{x,a}=this.authority(input,["tenantContext","now","customerId"]),id=customerUuid(x.customerId);return this.read({text:`SELECT outcome,result_payload FROM saas.customers_get($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid)`,values:[...authorityValues(a),id]},"found",v=>{try{const d=parseCustomerDetail(v);if(d.id!==id)throw unavailable();return d}catch(e){if(e instanceof CustomerRepositoryError)throw e;throw unavailable()}})}
 async getWorkspace(input:GetCustomerInput){const{x,a}=this.authority(input,["tenantContext","now","customerId"]),id=customerUuid(x.customerId);return this.read({text:`SELECT outcome,result_payload FROM saas.customers_get_workspace($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid)`,values:[...authorityValues(a),id]},"found",v=>{try{const workspace=parseCustomerWorkspace(v),previous=workspace.neighbors.previous,next=workspace.neighbors.next;if(previous?.id===id||next?.id===id||(previous&&next&&previous.id===next.id))throw unavailable();return workspace}catch(e){if(e instanceof CustomerRepositoryError)throw e;throw unavailable()}})}
 async save(input:SaveCustomerInput){const{x,a}=this.authority(input,["tenantContext","now","operationId","firstName","lastName","addresses","consents"],["customerId","expectedVersion","email","phone"]),operationId=customerUuid(x.operationId),existingId=x.customerId===undefined?undefined:customerUuid(x.customerId),expected=x.expectedVersion===undefined?undefined:customerVersion(x.expectedVersion),firstName=customerText(x.firstName,1,100),lastName=customerText(x.lastName,1,100),email=customerEmail(x.email),phone=customerPhone(x.phone);if((existingId===undefined)!==(expected===undefined))throw new CustomerRepositoryError("invalid_input");if(!Array.isArray(x.addresses)||x.addresses.length>20||!Array.isArray(x.consents)||x.consents.length>3)throw new CustomerRepositoryError("invalid_input");const addresses=Object.freeze(x.addresses.map(customerAddress)),consents=Object.freeze(x.consents.map(customerConsent));if(new Set(consents.map(c=>c.channel)).size!==consents.length||addresses.filter(v=>v.isDefault).length>1)throw new CustomerRepositoryError("invalid_input");const customerId=existingId??this.uuid(),sqlAddresses=addresses.map(v=>({id:v.id??this.uuid(),label:v.label,recipient_name:v.recipientName,line1:v.line1,...(v.line2?{line2:v.line2}:{}),city:v.city,...(v.district?{district:v.district}:{}),...(v.postalCode?{postal_code:v.postalCode}:{}),country:v.country,is_default:v.isDefault}));const fingerprint=customerFingerprint(existingId?"update":"create",a.storeId,{customerId:existingId??null,expectedVersion:expected??null,firstName,lastName,email:email??null,phone:phone??null,addresses,consents});const parser:RecoverParser<CustomerMutationResult>=(v,replayed)=>{try{const m=parseCustomerMutationResult({...payload(v,["id","version","status","updatedAt"]),replayed});if(m.status!=="active"||(!replayed&&m.id!==customerId)||(!replayed&&m.version!==(expected??0)+1))throw unavailable();return m}catch(e){if(e instanceof CustomerRepositoryError)throw e;throw unavailable()}};return this.mutate(a,operationId,fingerprint,{text:`SELECT outcome,result_payload FROM saas.customers_save($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text,$10::uuid,$11::bigint,$12::text,$13::text,$14::text,$15::text,$16::jsonb,$17::jsonb)`,values:[...authorityValues(a),operationId,fingerprint,customerId,expected??null,firstName,lastName,email??null,phone??null,JSON.stringify(sqlAddresses),JSON.stringify(consents)]},parser)}
 private customerMutation(input:ArchiveCustomerInput|AddCustomerNoteInput,kind:"archive"|"add_note"){const optional=kind==="archive"?[]:[];const required=kind==="archive"?["tenantContext","now","customerId","operationId","expectedVersion"]:["tenantContext","now","customerId","operationId","text"];const{x,a}=this.authority(input,required,optional),customerId=customerUuid(x.customerId),operationId=customerUuid(x.operationId),payloadData=kind==="archive"?{customerId,expectedVersion:customerVersion(x.expectedVersion)}:{customerId,text:customerText(x.text,1,2000)},fingerprint=customerFingerprint(kind,a.storeId,payloadData),noteId=kind==="add_note"?this.uuid():undefined;const parser:RecoverParser<CustomerMutationResult>=(v,replayed)=>{try{const m=parseCustomerMutationResult({...payload(v,["id","version","status","updatedAt"]),replayed});if(m.id!==customerId||(kind==="archive"&&m.status!=="archived"))throw unavailable();return m}catch(e){if(e instanceof CustomerRepositoryError)throw e;throw unavailable()}};return this.mutate(a,operationId,fingerprint,{text:kind==="archive"?`SELECT outcome,result_payload FROM saas.customers_archive($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text,$10::uuid,$11::bigint)`:`SELECT outcome,result_payload FROM saas.customers_add_note($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text,$10::uuid,$11::uuid,$12::text)`,values:kind==="archive"?[...authorityValues(a),operationId,fingerprint,customerId,payloadData.expectedVersion]:[...authorityValues(a),operationId,fingerprint,customerId,noteId,payloadData.text]},parser)}
 archive(input:ArchiveCustomerInput){return this.customerMutation(input,"archive")}addNote(input:AddCustomerNoteInput){return this.customerMutation(input,"add_note")}
 private listTaxonomy<T>(input:CustomerAuthorityInput,kind:"tag"|"segment",parser:(v:unknown)=>T){const{a}=this.authority(input,["tenantContext","now"]);return this.read({text:`SELECT outcome,result_payload FROM saas.customer_${kind}s_list($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz)`,values:authorityValues(a)},"listed",v=>{const r=payload(v,["items"]);if(!Array.isArray(r.items)||r.items.length>1000)throw unavailable();try{return Object.freeze(r.items.map(parser))}catch{throw unavailable()}})}
 listTags(input:CustomerAuthorityInput){return this.listTaxonomy<CustomerTag>(input,"tag",parseCustomerTag)}listSegments(input:CustomerAuthorityInput){return this.listTaxonomy<CustomerSegment>(input,"segment",parseCustomerSegment)}
 private upsertTaxonomy(input:UpsertCustomerTagInput|UpsertCustomerSegmentInput,kind:"tag"|"segment"){const idKey=kind==="tag"?"tagId":"segmentId",secondaryKey=kind==="tag"?"color":"description",{x,a}=this.authority(input,["tenantContext","now","operationId","name",...(kind==="tag"?["color"]:[])],[idKey,"expectedVersion",...(kind==="segment"?["description"]:[])]),operationId=customerUuid(x.operationId),existing=x[idKey]===undefined?undefined:customerUuid(x[idKey]),expected=x.expectedVersion===undefined?undefined:customerVersion(x.expectedVersion);if((existing===undefined)!==(expected===undefined))throw new CustomerRepositoryError("invalid_input");const id=existing??this.uuid(),name=customerText(x.name,1,kind==="tag"?64:100),secondary=kind==="tag"?customerColor(x.color):x.description===undefined?undefined:customerText(x.description,1,500),fingerprint=customerFingerprint(`upsert_${kind}`,a.storeId,{id:existing??null,expectedVersion:expected??null,name,[secondaryKey]:secondary??null}),parse=kind==="tag"?parseCustomerTag:parseCustomerSegment;return this.mutate(a,operationId,fingerprint,{text:`SELECT outcome,result_payload FROM saas.customer_taxonomy_upsert($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text,$10::text,$11::uuid,$12::text,$13::text,$14::bigint)`,values:[...authorityValues(a),operationId,fingerprint,kind,id,name,secondary??null,expected??null]},v=>{try{return parse(v)}catch{throw unavailable()}}) as Promise<CustomerTag&CustomerSegment>}
 upsertTag(input:UpsertCustomerTagInput){return this.upsertTaxonomy(input,"tag") as Promise<CustomerTag>}upsertSegment(input:UpsertCustomerSegmentInput){return this.upsertTaxonomy(input,"segment") as Promise<CustomerSegment>}
 private setTaxonomy(input:SetCustomerTaxonomyInput,kind:"tag"|"segment"){const{x,a}=this.authority(input,["tenantContext","now","customerId","operationId","ids"]),customerId=customerUuid(x.customerId),operationId=customerUuid(x.operationId),ids=uniqueIds(x.ids),fingerprint=customerFingerprint(`set_${kind}s`,a.storeId,{customerId,ids}),parser:RecoverParser<CustomerMutationResult>=(v,replayed)=>{try{const m=parseCustomerMutationResult({...payload(v,["id","version","status","updatedAt"]),replayed});if(m.id!==customerId)throw unavailable();return m}catch(e){if(e instanceof CustomerRepositoryError)throw e;throw unavailable()}};return this.mutate(a,operationId,fingerprint,{text:`SELECT outcome,result_payload FROM saas.customer_set_taxonomy($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text,$10::uuid,$11::text,$12::uuid[])`,values:[...authorityValues(a),operationId,fingerprint,customerId,kind,ids]},parser)}setTags(i:SetCustomerTaxonomyInput){return this.setTaxonomy(i,"tag")}setSegments(i:SetCustomerTaxonomyInput){return this.setTaxonomy(i,"segment")}
 async export(input:CustomerAuthorityInput):Promise<CustomerExport>{const{a}=this.authority(input,["tenantContext","now"]);return this.read({text:`SELECT outcome,result_payload FROM saas.customers_export($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz)`,values:authorityValues(a)},"exported",v=>{const r=payload(v,["items","exportedAt"]);if(!Array.isArray(r.items)||r.items.length>1000||typeof r.exportedAt!=="string")throw unavailable();try{return Object.freeze({items:Object.freeze(r.items.map(parseCustomerListItem)),exportedAt:r.exportedAt})}catch{throw unavailable()}})}
}
