import type { CustomerConsentChannel, CustomerConsentStatus, CustomerStatus, TenantContext } from "@celebix/saas-contracts";
import { OrderRepositoryError } from "../orders/errors.ts";import { merchantAuthority,type ValidatedOrderAuthority } from "../orders/validation.ts";import { CustomerRepositoryError,type CustomerErrorCode } from "./errors.ts";
export const CUSTOMER_UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;const CONTROL=/[\u0000-\u001f\u007f]/,EMAIL=/^[^\s@]+@[^\s@]+\.[^\s@]+$/,PHONE=/^\+[1-9][0-9]{7,14}$/,COLOR=/^#[0-9a-f]{6}$/,COUNTRY=/^[A-Z]{2}$/;
function fail(code:CustomerErrorCode="invalid_input"):never{throw new CustomerRepositoryError(code)}
export function exactCustomerInput(v:unknown,required:readonly string[],optional:readonly string[]=[]){if(typeof v!=="object"||v===null||Array.isArray(v))fail();const p=Object.getPrototypeOf(v);if(p!==Object.prototype&&p!==null)fail();const r=v as Record<string,unknown>,a=new Set([...required,...optional]);if(required.some(k=>!Object.hasOwn(r,k))||Object.keys(r).some(k=>!a.has(k)))fail();return Object.freeze({...r})}
export function customerAuthority(c:TenantContext,n:Date):ValidatedOrderAuthority{try{return merchantAuthority(c,n,"customers")}catch(e){if(e instanceof OrderRepositoryError&&["invalid_input","unauthenticated","membership_denied","store_inactive","feature_not_enabled","durable_authority_invalid"].includes(e.code))fail(e.code as CustomerErrorCode);fail("durable_authority_invalid")}}
export function customerUuid(v:unknown){if(typeof v!=="string"||!CUSTOMER_UUID.test(v))fail();return v}
export function customerVersion(v:unknown){if(!Number.isSafeInteger(v)||(v as number)<1)fail();return v as number}
export function customerText(v:unknown,min:number,max:number,pattern?:RegExp){if(typeof v!=="string"||v.length<min||v.length>max||v!==v.trim()||CONTROL.test(v)||(pattern&&!pattern.test(v)))fail();return v}
export function optionalCustomerText(v:unknown,min:number,max:number,pattern?:RegExp){return v===undefined?undefined:customerText(v,min,max,pattern)}
export function customerEmail(v:unknown){return optionalCustomerText(v,3,320,EMAIL)}export function customerPhone(v:unknown){return optionalCustomerText(v,9,16,PHONE)}
export function customerPageSize(v:unknown){if(!Number.isSafeInteger(v)||(v as number)<1||(v as number)>100)fail();return v as number}export function customerSearch(v:unknown){return v===undefined?undefined:customerText(v,1,200)}
export function customerStatus(v:unknown):CustomerStatus|undefined{if(v===undefined)return undefined;if(v!=="active"&&v!=="archived")fail();return v}
export function customerAddress(v:unknown){const r=exactCustomerInput(v,["label","recipientName","line1","city","country","isDefault"],["id","line2","district","postalCode"]);if(typeof r.isDefault!=="boolean")fail();return Object.freeze({...(r.id===undefined?{}:{id:customerUuid(r.id)}),label:customerText(r.label,1,50),recipientName:customerText(r.recipientName,1,200),line1:customerText(r.line1,1,300),...(r.line2===undefined?{}:{line2:customerText(r.line2,1,300)}),city:customerText(r.city,1,100),...(r.district===undefined?{}:{district:customerText(r.district,1,100)}),...(r.postalCode===undefined?{}:{postalCode:customerText(r.postalCode,1,20)}),country:customerText(r.country,2,2,COUNTRY),isDefault:r.isDefault})}
export function customerConsent(v:unknown){const r=exactCustomerInput(v,["channel","status"]);if(!["email","phone","whatsapp"].includes(r.channel as string)||!["granted","denied"].includes(r.status as string))fail();return Object.freeze({channel:r.channel as CustomerConsentChannel,status:r.status as CustomerConsentStatus})}
export function customerColor(v:unknown){return customerText(v,7,7,COLOR)}
export function uniqueIds(v:unknown){if(!Array.isArray(v)||v.length>50)fail();const ids=Object.freeze(v.map(customerUuid));if(new Set(ids).size!==ids.length)fail();return ids}
