import assert from 'node:assert/strict';
import test from 'node:test';
import { EmailMarketingError } from '@celebix/saas-data';
const api = await import('./handler.ts').catch(() => ({})) as typeof import('./handler.ts');
const ORIGIN = 'https://panel.saas-staging.celebix.net', ID = '22700000-0000-4000-8000-000000000001', OP = '22700000-0000-4000-8000-000000000002', COOKIE = `v1.panel.current.${Buffer.alloc(32, 1).toString('base64url')}`;
function request(area: string, body?: unknown, headers: Record<string, string> = {}) { return new Request('http://internal:3400/api/marketing/email-connections' + area, { method: body === undefined ? 'GET' : 'POST', headers: { host: new URL(ORIGIN).hostname, cookie: `__Host-celebix_panel=${COOKIE}`, ...(body === undefined ? {} : { origin: ORIGIN, 'content-type': 'application/json', 'idempotency-key': OP }), ...headers }, body: body === undefined ? undefined : JSON.stringify(body) }); }
function fixture(email: any, role = 'store_owner') { let now = new Date('2026-10-09T12:00:00Z'); let expires = Infinity; const h = () => api.createEmailMarketingHttpHandlers({ resolveRuntime: async () => ({ email, access: { readiness: { mode: 'approved_staging' }, panelOrigin: ORIGIN, resolveCredential: async (i: any) => i.hostname !== new URL(ORIGIN).hostname || i.now.getTime() >= expires ? { kind: 'unauthorized' } : { kind: 'authenticated', tenantContext: { schemaVersion: 1, requestId: ID, principal: { id: ID }, store: { id: ID, slug: 'fixture', status: 'active' }, membership: { id: ID, role, status: 'active' }, entitlements: { status: 'active', features: ['integrations'] } } } } } as never), now: () => now, requestId: () => ID }); return { h, advance: () => now = new Date(now.getTime() + 31 * 60 * 1000), expire: () => expires = now.getTime() + 30 * 60 * 1000 }; }
test('overview reads saved state only; mutation binds actual store/session and never accepts caller authority', async () => { assert.equal(typeof api.createEmailMarketingHttpHandlers, 'function'); const inputs: any[] = []; let reads = 0; const h = fixture({ overview: async () => { reads++; return { configured: true }; }, validate: async (i: any) => { inputs.push(i); return { candidateId: ID }; } }).h(); assert.equal((await h.get(request(''), 'overview')).status, 200); assert.equal(reads, 1); assert.equal((await h.post(request('/validate', { provider: 'brevo', apiKey: 'private-fixture-key' }), 'validate')).status, 200); assert.equal(inputs[0].tenantContext.store.id, ID); assert.equal(inputs[0].operationId, OP); assert.match(inputs[0].sessionBinding, /^[a-f0-9]{64}$/); assert.notEqual(inputs[0].sessionBinding, COOKIE); assert.equal((await h.post(request('/validate', { provider: 'brevo', apiKey: 'key', storeId: ID }), 'validate')).status, 400); assert.equal((await h.get(request('', undefined, { 'x-store-id': ID }), 'overview')).status, 400); assert.equal(inputs.length, 1); });
test('support expired after validation cannot apply', async () => { let activated = 0; const f = fixture({ validate: async () => ({ candidateId: ID }), apply: async () => { activated++; } }); f.expire(); assert.equal((await f.h().post(request('/validate', { provider: 'klaviyo', apiKey: 'private-fixture-key' }), 'validate')).status, 200); f.advance(); assert.equal((await f.h().post(request('/apply', { candidateId: ID, expectedVersion: 0, selection: { kind: 'existing', listId: 'managed' } }), 'apply')).status, 403); assert.equal(activated, 0); });
test('foreign origin/host, absent session, read-only role and oversized/malformed mutation are rejected', async () => { let calls = 0; const h = fixture({ disconnect: async () => { calls++; } }).h(), body = { expectedVersion: 1 }; for (const headers of [{ origin: 'https://attacker.test' }, { host: 'attacker.test' }, { cookie: '' }] as Record<string,string>[])
    assert.ok([401, 403].includes((await h.post(request('/disconnect', body, headers), 'disconnect')).status)); assert.equal((await fixture({ disconnect: async () => { calls++; } }, 'analyst').h().post(request('/disconnect', body), 'disconnect')).status, 403); for (const headers of [{ 'idempotency-key': 'bad' }, { 'x-tenant-id': ID }] as Record<string,string>[])
    assert.equal((await h.post(request('/disconnect', body, headers), 'disconnect')).status, 400); assert.equal((await h.post(request('/disconnect', { ...body, extra: 'x'.repeat(17000) }), 'disconnect')).status, 400); assert.equal(calls, 0); });
test('candidate lists bind session; duplicate/unknown queries and API keys in query are refused', async () => { const inputs: any[] = []; const h = fixture({ lists: async (i: any) => { inputs.push(i); return { items: [] }; } }).h(); assert.equal((await h.get(request('/lists?candidateId=' + ID + '&cursor=next'), 'lists')).status, 200); assert.equal(inputs[0].candidateId, ID); assert.equal(inputs[0].cursor, 'next'); assert.ok(inputs[0].sessionBinding); for (const q of ['candidateId=' + ID + '&candidateId=' + ID, 'candidateId=' + ID + '&apiKey=secret', 'candidateId=' + ID + '&storeId=' + ID])
    assert.equal((await h.get(request('/lists?' + q), 'lists')).status, 400); assert.equal(inputs.length, 1); });
test('safe stale/candidate errors expose no provider body or unknown code', async () => { for (const [code, status] of [['version_conflict', 409], ['candidate_expired', 409], ['private-fixture-key', 503]] as const) {
    const h = fixture({ apply: async () => { throw new EmailMarketingError(code as never); } }).h();
    const r = await h.post(request('/apply', { candidateId: ID, expectedVersion: 0, selection: { kind: 'existing', listId: 'managed' } }), 'apply');
    assert.equal(r.status, status);
    assert.equal((await r.text()).includes('private-fixture-key'), false);
} });
