import assert from 'node:assert/strict';
import test from 'node:test';
import{createHash}from'node:crypto';
import {sealMerchantProviderCredential} from '@celebix/saas-data';
import type{ContentResourceAuthoringRequest,ContentResourceGeneration}from'@celebix/saas-contracts';
import{buildContentResourceSnapshot}from'./snapshot.ts';
import{createContentResourceAuthoringService}from'./service.ts';

const id='11111111-1111-4111-8111-111111111111',operationId='22222222-2222-4222-8222-222222222222',outlineId='33333333-3333-4333-8333-333333333333';
const now=()=>new Date('2026-09-29T00:00:00.000Z');
const values={name:'Bakım',slug:'bakim',locale:'tr',body:'<p>Mevcut metin.</p>',excerpt:null,seoTitle:null,seoDescription:null,published:false,status:'draft' as const};
const outline={title:'Bakım',sections:[{heading:'Temizlik',points:[]}]};
const outlineRequest:ContentResourceAuthoringRequest={target:{kind:'blog_post',draftId:id,recordId:null,recordVersion:null},currentDraft:values,locale:'tr',tone:'neutral',length:'medium',note:'',researchOperationId:null,stage:'outline',topic:'Bakım',purpose:'Bilgilendirme'};
const articleRequest:ContentResourceAuthoringRequest={target:outlineRequest.target,currentDraft:values,locale:'tr',tone:'neutral',length:'medium',note:'',researchOperationId:null,stage:'draft',action:'article',fields:['body'],reviewedOutline:outline,outlineGenerationId:outlineId,selection:null};
const tenantContext={store:{id,status:'active'},membership:{status:'active',role:'store_owner'}} as any;
const authority={configId:id,provider:'deepseek',selectedModel:'deepseek-flash',credentialVersion:1,version:1,sealedCredentials:sealMerchantProviderCredential({plaintext:new TextEncoder().encode('fixture-secret'),profileId:id,storeId:id,providerCode:'deepseek',capability:'ai_assistant',credentialVersion:1,keyring:{activeKeyId:'fixture',keys:[{keyId:'fixture',key:new Uint8Array(32).fill(7)}]}})};
function fixture(options:{request?:ContentResourceAuthoringRequest;invalidOutput?:boolean;emptyOutput?:boolean;toolOutput?:boolean;replay?:boolean;revoked?:boolean;deny?:boolean;missingOutline?:boolean;usage?:unknown;throwProvider?:boolean}={}){
 const request=options.request??outlineRequest,snapshot=buildContentResourceSnapshot(request,null,[]);
 let row:ContentResourceGeneration={id:operationId,target:request.target,stage:request.stage,status:'pending',outline:null,draft:null,sourceFingerprint:snapshot.sourceFingerprint,usage:null,safeCode:null,createdAt:now().toISOString(),updatedAt:now().toISOString(),finishedAt:null,requestFingerprint:createHash('sha256').update(JSON.stringify(request)).digest('hex'),configId:id,provider:'deepseek',model:'deepseek-flash',credentialVersion:1,promptVersion:'content-resource-v1',version:1,dispatchState:'not_dispatched',claimToken:null,leaseExpiresAt:now().toISOString()};
 let calls=0,claims=0,begins=0,authorityCalls=0,failed:any,complete:any;
 const deps:any={now,deadlineMs:1000,authorizePreferences:async()=>{if(options.deny)throw Object.assign(Error(),{code:'feature_not_enabled'});},contentRepository:{get:async()=>{throw Error('unexpected-document-read');}},researchRepository:{get:async()=>{throw Error('unexpected-research-read');}},providers:{getAuthority:async()=>({...authority,credentialVersion:options.revoked&&++authorityCalls>1?2:1})},keyring:()=>({activeKeyId:'fixture',keys:[{keyId:'fixture',key:new Uint8Array(32).fill(7)}]}),generations:{get:()=>({generate:async(input:any)=>{calls++;assert.equal(input.authoringProfile,'content_resource');assert.equal(input.maxOutputTokens,8192);assert.deepEqual(input.tools,[]);if(options.throwProvider)throw Object.assign(Error(),{code:'provider_unavailable'});const output=options.emptyOutput?'':options.invalidOutput?'{':request.stage==='outline'?JSON.stringify({sourceFingerprint:snapshot.sourceFingerprint,outline}):JSON.stringify({sourceFingerprint:snapshot.sourceFingerprint,values:{body:[{type:'paragraph',children:[{type:'text',text:'Bakım metni.'}]}]},citations:[],suggestions:[]});return{text:output,toolCalls:options.toolOutput?[{callId:id,name:'search',arguments:{}}]:[],usage:options.usage===undefined?{inputTokens:17,outputTokens:11}:options.usage};}})},repository:{getGeneration:async({operationId:asked}:any)=>{if(asked===outlineId){if(options.missingOutline)throw Object.assign(Error(),{code:'operation_not_found'});return{...row,id:outlineId,stage:'outline',status:'completed',target:request.target,outline,draft:null,finishedAt:now().toISOString()};}if(begins===0&&!options.replay)throw Object.assign(Error(),{code:'operation_not_found'});return row;},beginGeneration:async(input:any)=>{begins++;row={...row,requestFingerprint:input.requestFingerprint,sourceFingerprint:input.sourceFingerprint};return{kind:options.replay?'existing-status':'pending',generation:options.replay?{...row,dispatchState:'dispatched'}:row};},claimGenerationDispatch:async()=>{claims++;row={...row,version:2,dispatchState:'dispatched',claimToken:id};return{claimToken:id,version:2,leaseExpiresAt:now().toISOString()};},completeGeneration:async(input:any)=>{complete=input;row={...row,status:'completed',outline:input.outline,draft:input.draft,usage:input.usage,finishedAt:now().toISOString()};return row;},failGeneration:async(input:any)=>{failed=input;row={...row,status:input.dispatchState==='unknown'?'unknown':'failed',safeCode:input.safeCode,usage:input.usage??null,finishedAt:now().toISOString()};return row;}}};
 const service=createContentResourceAuthoringService(deps);
 return{service,request,deps,counts:()=>({calls,claims,begins}),failure:()=>failed,completion:()=>complete};
}
const call=(f:ReturnType<typeof fixture>)=>f.service.generateContent({tenantContext,operationId,request:f.request,signal:new AbortController().signal});
test('outline is one explicit bounded operation; article is not automatically called',async()=>{const f=fixture();const result=await call(f);assert.equal(result.status,'completed');assert.deepEqual(result.outline,outline);assert.equal(result.draft,null);assert.deepEqual(f.counts(),{calls:1,claims:1,begins:1});assert.deepEqual(result.usage,{inputTokens:17,outputTokens:11,totalTokens:28});});
test('article requires a completed same-actor outline before any paid dispatch',async()=>{const denied=fixture({request:articleRequest,missingOutline:true});await assert.rejects(call(denied));assert.deepEqual(denied.counts(),{calls:0,claims:0,begins:0});const okay=fixture({request:articleRequest});const result=await call(okay);assert.equal(result.status,'completed');assert.match(result.draft?.values.body??'',/Bakım metni/);assert.equal(okay.counts().calls,1);});
test('feature denial and dispatched replay make no paid call',async()=>{const denied=fixture({deny:true});await assert.rejects(call(denied),{code:'feature_not_enabled'});assert.deepEqual(denied.counts(),{calls:0,claims:0,begins:0});const replay=fixture({replay:true});await call(replay);assert.equal(replay.counts().calls,0);});
test('malformed output persists only validated adapter measurement as invalid_output',async()=>{const f=fixture({invalidOutput:true});const result=await call(f);assert.equal(result.safeCode,'invalid_output');assert.deepEqual(result.usage,{inputTokens:17,outputTokens:11,totalTokens:28});assert.deepEqual(f.failure()?.usage,result.usage);assert.equal(f.failure()?.claimToken,id);assert.equal(f.completion(),undefined);});
test('getter/coercion/invalid usage and adapter throw never manufacture token usage',async()=>{let invoked=0;const getter=Object.defineProperty({outputTokens:1},'inputTokens',{enumerable:true,get(){invoked++;return 1;}}),coercion={inputTokens:{valueOf(){invoked++;return 1;}},outputTokens:1};for(const usage of [getter,coercion,{inputTokens:-1,outputTokens:1},null]){const f=fixture({invalidOutput:true,usage});const result=await call(f);assert.equal(result.usage,null);}assert.equal(invoked,0);const thrown=fixture({throwProvider:true});const result=await call(thrown);assert.equal(result.status,'unknown');assert.equal(result.usage,null);});
test('revoked pinned connection fails before provider dispatch',async()=>{const f=fixture({revoked:true});const result=await call(f);assert.equal(result.safeCode,'connection_revoked');assert.equal(f.counts().calls,0);});
test('empty or tool-bearing successful adapters fail once while keeping only measured usage',async()=>{for(const options of [{emptyOutput:true},{toolOutput:true}]){const f=fixture(options);const result=await call(f);assert.equal(result.status,'failed');assert.equal(result.safeCode,'invalid_output');assert.deepEqual(result.usage,{inputTokens:17,outputTokens:11,totalTokens:28});assert.equal(f.counts().calls,1);}});
