'use client';
import { useMemo } from 'react';
import type { SeoResource, SeoSettings, SeoOverview as Overview, SeoLink, SeoNotification, StorefrontAsset } from '@celebix/saas-contracts';
import { SeoOverview, type SeoTab } from '@/components/seo/SeoOverview';
import { SeoContent } from '@/components/seo/SeoContent';
import { SeoSettings as SettingsScreen } from '@/components/seo/SeoSettings';
import { PanelLayoutClient } from '@/components/panel/PanelLayoutClient';
import { seoClient, SeoApiError, type SeoClient } from '@/lib/seo-ui/client';
import { MODEL } from '../mira-catalog/catalog-fixture';

const NOW='2026-09-30T11:42:00.000Z';
const uuid=(i:number)=>'78000000-0000-4000-8000-'+String(i).padStart(12,'0');
const titles=['Dantel Detaylı Bluz','Antrasit Straight Jean','Ekru Basic Triko','Mavi Wide Leg Jean','Haki Kargo Pantolon','Siyah Palazzo Pantolon'];
const images=['dantel-bluz','antrasit-jean','ekru-triko','mavi-jean','kargo-pantolon','siyah-pantolon'];

/** In-memory disposable clients mount the real components without auth or live writes. */
function fixtureClient(scenario:string):SeoClient{
 let rows:SeoResource[]=Array.from({length:128},(_,i)=>{const kind=i<82?'product':i<106?'category':i<118?'page':'blog';const name=kind==='product'?titles[i%6]+(i>=6?' · '+(i+1):''):kind==='category'?['Yeni Gelenler','Üst Giyim','Pantolon','Triko'][i%4]+' '+(i-81):kind==='page'?['Hakkımızda','İletişim','Teslimat','İade ve Değişim'][i%4]+' '+(i-105):'Sonbahar Gardırobu '+(i-117);const path='/'+(kind==='product'?'urun':kind==='category'?'kategori':kind==='page'?'pages':'blog')+'/icerik-'+(i+1);return {id:uuid(i+1),kind,name,path,locale:'tr-TR',status:i<112?'active':'draft',version:3,seoVersion:2,title:i<12?null:name+' | Mira Butik',description:i>=2&&i<9?null:name+' ile stilinizi tamamlayın. Özenle seçilen parçaları keşfedin.',canonicalPath:null,indexing:'inherit',effectiveTitle:name+' | Mira Butik',effectiveDescription:name+' ve yeni sezon seçkileri.',effectiveCanonicalPath:path,allowIndex:i<112&&i!==5,imageUrl:kind==='product'?'/seo-assets/product-'+images[i%6]+'.webp':null,updatedAt:NOW};});
 let settings:SeoSettings={version:4,metaTitle:'Mira Butik · Kendine yakışanı keşfet',metaDescription:'Özenle seçilmiş parçalar, her gününe eşlik eden stil. Yeni sezon koleksiyonunu keşfet.',allowIndex:true,socialTitle:'Yeni sezon, senin stilin.',socialDescription:'Doğal dokular, sade parçalar. Yeni koleksiyonla tanış.',socialAssetId:uuid(900),socialImageUrl:'/seo-assets/product-dantel-bluz.webp',googleVerification:null,bingVerification:null,indexNowEnabled:true,hostname:'mira-butik.example',eligible:scenario!=='domain'};
 let links:SeoLink[]=[{id:uuid(301),version:3,sourceKind:'category',sourceId:uuid(83),targetKind:'product',targetId:uuid(1),sourcePath:rows[82].path,targetPath:rows[0].path,anchorText:'Dantel bluzları keşfet',enabled:true},{id:uuid(302),version:2,sourceKind:'category',sourceId:uuid(84),targetKind:'product',targetId:uuid(3),sourcePath:rows[83].path,targetPath:rows[2].path,anchorText:'Ekru basic triko',enabled:true},{id:uuid(303),version:1,sourceKind:'blog',sourceId:uuid(119),targetKind:'product',targetId:uuid(2),sourcePath:rows[118].path,targetPath:rows[1].path,anchorText:'Antrasit jean',enabled:true},{id:uuid(304),version:1,sourceKind:'category',sourceId:uuid(85),targetKind:'product',targetId:uuid(6),sourcePath:rows[84].path,targetPath:rows[5].path,anchorText:'Palazzo pantolon',enabled:false}];
 let notifications:SeoNotification[]=Array.from({length:13},(_,i)=>({id:uuid(400+i),path:rows[i].path,status:i<8?'received':i<10?'queued':i===10?'retrying':i===11?'verification_pending':'failed',httpStatus:i<8?200:i===12?503:null,attempts:i<10?1:2,requestedAt:NOW,nextAttemptAt:i===10?'2026-09-30T11:50:00.000Z':null,error:null}));
 let check:Overview['check']={checked:112,total:112,status:'completed',lastCheckedAt:NOW};
 let ticks=0;const replay=new Map<string,unknown>();
 const clone=<T,>(value:T):T=>structuredClone(value);
 const wait=()=>new Promise<void>(resolve=>setTimeout(resolve,scenario==='loading'?60000:120));
 async function reading(){await wait();if(scenario==='error')throw new SeoApiError('unavailable',503);}
 const mutate=(key:string,work:()=>unknown)=>{if(replay.has(key))return clone(replay.get(key));if(scenario==='save-error')throw new SeoApiError('unavailable',503);if(scenario==='conflict')throw new SeoApiError('version_conflict',409);const result=work();replay.set(key,clone(result));if(scenario==='commit-unknown')throw new SeoApiError('commit_unknown',503);return clone(result);};
 const asset:StorefrontAsset={id:uuid(900),storeId:uuid(950),kind:'social',objectKey:'fixture/social.webp',publicUrl:'/seo-assets/product-dantel-bluz.webp',mediaType:'image/webp',altText:'Yeni sezon · QA görseli',width:800,height:420,byteSize:12000,status:'active',createdAt:NOW,updatedAt:NOW,version:1};
 return Object.freeze({...seoClient,
  async overview(){await reading();if(check.status==='running'){ticks++;check={...check,checked:Math.min(112,ticks*56),status:ticks>=2?'completed':'running'};}const topics:Overview['issues']=[...rows.filter(r=>!r.title).map(r=>({code:'missing_title',severity:'warning' as const,message:'Özel meta başlık eklenmemiş',path:r.path,kind:r.kind,resourceId:r.id,fixHref:'/seo/content?kind='+r.kind+'&resourceId='+r.id})),...rows.filter(r=>!r.description).map(r=>({code:'missing_description',severity:'warning' as const,message:'Özel meta açıklama eklenmemiş',path:r.path,kind:r.kind,resourceId:r.id,fixHref:'/seo/content?kind='+r.kind+'&resourceId='+r.id})),...rows.slice(3,6).map(r=>({code:'http_unavailable',severity:'error' as const,message:'Sayfa erişimi kontrol edilmeli',path:r.path,kind:r.kind,resourceId:r.id,fixHref:'/seo/content?kind='+r.kind+'&resourceId='+r.id}))];return clone({totalResources:scenario==='empty'?0:128,publishedResources:scenario==='empty'?0:112,issues:scenario==='empty'?[]:topics,sitemap:{url:'https://mira-butik.example/sitemap.xml',robotsUrl:'https://mira-butik.example/robots.txt',entryCount:scenario==='empty'?0:96},check:scenario==='empty'?{checked:0,total:0,status:'idle',lastCheckedAt:null}:check,notifications:scenario==='empty'?[]:notifications,settings}as Overview);},
  async settings(){await reading();return clone(settings);},
  async resources(input={}){await reading();const matches=scenario==='empty'?[]:rows.filter(r=>(!input.kind||r.kind===input.kind)&&(!input.query||(r.name+' '+r.path).toLocaleLowerCase('tr-TR').includes(input.query.toLocaleLowerCase('tr-TR')))&&(!input.missing||!r.title||!r.description));const offset=Number(input.cursor||0),limit=input.limit??50;return clone({items:matches.slice(offset,offset+limit),nextCursor:offset+limit<matches.length?String(offset+limit):null,total:matches.length});},
  async saveResource(kind,id,input,key){await wait();return mutate(key,()=>{const r=rows.find(r=>r.id===id&&r.kind===kind);if(!r)throw new SeoApiError('record_not_found',404);if(r.version!==input.expectedVersion||r.seoVersion!==input.expectedSeoVersion)throw new SeoApiError('version_conflict',409);Object.assign(r,input,{version:r.version+1,seoVersion:r.seoVersion+1,allowIndex:r.status==='active'&&input.indexing!=='noindex'});return {resource:r,replayed:false};})as Awaited<ReturnType<SeoClient['saveResource']>>;},
  async saveSettings(input,key){await wait();return mutate(key,()=>{if(input.expectedVersion!==settings.version)throw new SeoApiError('version_conflict',409);settings={...settings,...input,version:settings.version+1,socialImageUrl:input.socialAssetId?asset.publicUrl:null};return {settings,replayed:false};})as Awaited<ReturnType<SeoClient['saveSettings']>>;},
  async links(){await reading();return clone({items:scenario==='empty'?[]:links});},
  async saveLink(input,key){await wait();return mutate(key,()=>{if(input.remove){links=links.filter(l=>l.id!==input.id);return {link:null,replayed:false};}const source=rows.find(r=>r.id===input.sourceId),target=rows.find(r=>r.id===input.targetId);if(!source||!target)throw new SeoApiError('record_not_found',404);const record:SeoLink={id:input.id??uuid(305+links.length),version:(input.expectedVersion??0)+1,sourceKind:input.sourceKind,sourceId:input.sourceId,targetKind:input.targetKind,targetId:input.targetId,sourcePath:source.path,targetPath:target.path,anchorText:input.anchorText,enabled:input.enabled};links=[...links.filter(l=>l.id!==record.id),record];return {link:record,replayed:false};})as Awaited<ReturnType<SeoClient['saveLink']>>;},
  async notifications(){await reading();return clone({items:notifications});},
  async notify(input,key){await wait();return mutate(key,()=>{notifications=[...input.resources.map((r,i)=>({id:uuid(700+notifications.length+i),path:rows.find(x=>x.id===r.id)!.path,status:'queued' as const,httpStatus:null,attempts:0,requestedAt:NOW,nextAttemptAt:null,error:null})),...notifications].slice(0,100);return {queued:input.resources.length,replayed:false};})as Awaited<ReturnType<SeoClient['notify']>>;},
  async startCheck(){await wait();check={...check,checked:0,status:'running'};ticks=0;return {...check,replayed:false};},
  async assets(){await reading();return [clone(asset)];},
 });
}

export function SeoFixtureScreen({view,tab='checks',scenario='normal',kind='product',resourceId}:Readonly<{view:'overview'|'content'|'settings';tab?:SeoTab;scenario?:string;kind?:SeoResource['kind'];resourceId?:string}>){
 const client=useMemo(()=>fixtureClient(scenario),[scenario]);
 return <PanelLayoutClient model={{...MODEL,storeSlug:'mira-seo-fixture',storefrontHostname:'mira-butik.example',membershipLabel:'QA fixture · canlı değil'}}>{view==='overview'?<SeoOverview canManage={scenario!=='readonly'} initialTab={tab} client={client}/>:view==='content'?<SeoContent canManage={scenario!=='readonly'} initialKind={kind} resourceId={resourceId} client={client}/>:<SettingsScreen canManage={scenario!=='readonly'} client={client}/>}</PanelLayoutClient>;
}
