import assert from 'node:assert/strict';
import test from 'node:test';
import { createCollectionsApi, collectionConfig, collectionFromDetail, CollectionApiError } from './client.ts';
import { collectionDraft } from './model.ts';
const ID='73000000-0000-4000-8000-000000000001',OP='74000000-0000-4000-8000-000000000001',NOW='2026-09-30T12:00:00.000Z';
const config=collectionConfig({...collectionDraft(),name:'Şehir'});
const summary={id:ID,name:'Şehir',slug:'sehir',config,status:'active',productCount:0,publicProductCount:0,version:2,createdAt:NOW,updatedAt:NOW};
test('list query is paged/server-filtered and does not send tenant authority',async()=>{let observed='';const api=createCollectionsApi(async input=>{observed=String(input);return Response.json({items:[summary],page:2,pageSize:20,totalCount:21,counts:{all:21,published:0,draft:21,archived:0}});});const result=await api.list({page:2,pageSize:20,search:'Altın & inci',state:'draft',sort:'products'});assert.equal(result.items[0].name,'Şehir');const url=new URL(observed,'https://panel.example');assert.equal(url.pathname,'/api/catalog/collections');assert.equal(url.searchParams.get('search'),'Altın & inci');assert.equal(url.searchParams.get('page'),'2');assert.equal(url.searchParams.has('storeId'),false);});
test('members preview is read-only and preserves complete ordered IDs independent of rows',async()=>{let init:RequestInit|undefined;const api=createCollectionsApi(async(_input,options)=>{init=options;return Response.json({items:[{id:ID,title:'Ürün',status:'active'}],page:1,pageSize:20,totalCount:1,orderedIds:[ID,OP]});});const result=await api.members({config,query:{page:1,pageSize:20,mode:'members',productIds:[ID,OP]}});assert.deepEqual(result.orderedIds,[ID,OP]);assert.equal(new Headers(init?.headers).has('idempotency-key'),false);assert.deepEqual(JSON.parse(String(init?.body)).query.productIds,[ID,OP]);});
test('save binds expected version and a stable caller operation ID; never sends an editable slug',async()=>{let init:RequestInit|undefined;const api=createCollectionsApi(async(_input,options)=>{init=options;return Response.json({id:ID,version:3,status:'active',updatedAt:NOW,replayed:false});});await api.save({resourceId:ID,expectedVersion:2,name:'Yeni isim',description:'İlk satır\nİkinci satır',config,productIds:[OP]},OP);assert.equal(new Headers(init?.headers).get('idempotency-key'),OP);const body=JSON.parse(String(init?.body));assert.equal(body.expectedVersion,2);assert.equal(Object.hasOwn(body,'slug'),false);assert.equal(Object.hasOwn(body,'storeId'),false);assert.equal(body.description,'İlk satır\nİkinci satır');});
test('malformed or private response fields and foreign detail IDs are rejected',async()=>{const api=createCollectionsApi(async()=>Response.json({...summary,productIds:[],storeId:OP}));await assert.rejects(()=>api.detail(ID),CollectionApiError);const other=createCollectionsApi(async()=>Response.json({...summary,id:OP,productIds:[]}));await assert.rejects(()=>other.detail(ID),CollectionApiError);});
test('server error codes produce finite safe copy without exposing error payloads',async()=>{const api=createCollectionsApi(async()=>Response.json({code:'private_sql_failure',message:'secret'},{status:500}));await assert.rejects(()=>api.detail(ID),error=>error instanceof CollectionApiError&&!error.message.includes('secret')&&error.message.includes('şu anda'));});
test('legacy parsed detail maps to manual and draft and preserves old product IDs',()=>{const draft=collectionFromDetail({...summary,config:{...config,featured:true},productIds:[ID,OP]} as any);assert.equal(draft.mode,'manual');assert.equal(draft.publicationStatus,'draft');assert.equal(draft.featured,true);assert.deepEqual(draft.productIds,[ID,OP]);});

test('capacity errors explain the collection limit and retain the safe error code',async()=>{for(const [code,message] of [['capacity_exceeded','sıralama sınırını'],['product_limit_reached','10.000 ürün']] as const){const api=createCollectionsApi(async()=>Response.json({code},{status:409}));await assert.rejects(()=>api.detail(ID),error=>error instanceof CollectionApiError&&error.code===code&&error.message.includes(message));}});
