/**
 * Frozen shared SaaS contracts.
 *
 * After Atlas approval, breaking changes require a schemaVersion increment and
 * explicit integration review. Implementation agents consume these contracts
 * and must not redefine them locally.
 */
export {
  ADMIN_DOMAIN_KINDS,
  ADMIN_DOMAIN_STATUSES,
  PLAN_ENTITLEMENT_STATUSES,
  PLAN_FEATURE_KEYS,
  PLAN_LIMIT_KEYS,
  PROVISIONING_STATUSES,
  SAAS_CONTRACT_SCHEMA_VERSION,
  STORE_DOMAIN_TYPES,
  STORE_HOST_STATUSES,
  STORE_MEMBERSHIP_ROLES,
  STORE_MEMBERSHIP_STATUSES,
  STORE_STATUSES,
  getPlanLimit,
  isPlanFeatureEnabled,
  isPlanFeatureKey,
  isPlanLimitKey,
} from "./types.ts";

export type {
  AdminDomainKind,
  AdminDomainStatus,
  CreateStarterTenantInput,
  CreateStarterTenantResult,
  DomainId,
  MembershipId,
  OperationId,
  PlanEntitlementLimits,
  PlanEntitlementStatus,
  PlanEntitlements,
  PlanFeatureKey,
  PlanId,
  PlanLimitKey,
  PrincipalId,
  PublicAdminBrand,
  ProvisioningStatus,
  ResolvedStoreHost,
  SaaSContractSchemaVersion,
  StoreDomainType,
  StoreHostStatus,
  StoreId,
  StoreMembership,
  StoreMembershipRole,
  StoreMembershipStatus,
  StoreMediaReadiness,
  StoreStatus,
  TenantContext,
} from "./types.ts";

export { SAAS_ERROR_CODES } from "./errors.ts";
export type { SaaSContractError, SaaSErrorCode } from "./errors.ts";
export {
  PRODUCT_STATUSES,
  VARIANT_STATUSES,
  parseProduct,
  parseProductVariant,
} from "./catalog/index.ts";
export {
  CATALOG_ONBOARDING_CHANNEL_KINDS,
  CATALOG_ONBOARDING_PRODUCT_TYPES,
  CATALOG_ONBOARDING_RESOURCE_KINDS,
  CATALOG_ONBOARDING_UNITS,
  parseCatalogOnboardingIntent,
  parseCatalogCategory,
  parseCatalogCategoryFields,
  parseCatalogCategoryList,
  parseCatalogCategoryMutationResult,
  parseCatalogOnboardingOptions,
  parseCatalogOnboardingResult,
  parseCatalogProductEditorProjection,
} from "./catalog-onboarding/index.ts";
export type {
  CatalogAdvancedCreateIntent,
  CatalogCategory,
  CatalogCategoryFields,
  CatalogCategoryMutationResult,
  CatalogOnboardingCategoryOption,
  CatalogOnboardingChannelKind,
  CatalogOnboardingChannelOption,
  CatalogOnboardingIntent,
  CatalogOnboardingInventoryAllocation,
  CatalogOnboardingLocationOption,
  CatalogOnboardingOptions,
  CatalogOnboardingProductType,
  CatalogOnboardingResourceIds,
  CatalogOnboardingResourceKind,
  CatalogOnboardingResourceOption,
  CatalogOnboardingResult,
  CatalogOnboardingUnit,
  CatalogOnboardingUnitPricing,
  CatalogOnboardingVariantIntent,
  CatalogProductEditorProjection,
  CatalogProductEditorVariant,
  CatalogProductMerchandisingFields,
  CatalogProductMerchandisingProfile,
  CatalogQuickCreateIntent,
} from "./catalog-onboarding/index.ts";
export type {
  Product,
  ProductId,
  ProductStatus,
  ProductVariant,
  ProductVariantId,
  VariantStatus,
} from "./catalog/index.ts";
export {
  MERCHANT_ACTIONS,
  isMerchantActionAllowed,
} from "./authorization/actions.ts";
export type { MerchantAction } from "./authorization/actions.ts";
export {
  INVENTORY_COUNT_STATUSES,
  INVENTORY_LOCATION_ARCHIVE_BLOCK_REASONS,
  INVENTORY_MOVEMENT_KINDS,
  INVENTORY_TRANSFER_STATUSES,
  PURCHASE_ORDER_STATUSES,
  parseInventoryBalance,
  parseInventoryCount,
  parseInventoryCountLine,
  parseInventoryLocation,
  parseInventoryLocationArchiveInput,
  parseInventoryLocationMutationResult,
  parseInventoryLocationSaveInput,
  parseInventoryMovement,
  parseInventoryMutationResult,
  parseInventoryTransfer,
  parseInventoryTransferLine,
  parsePurchaseOrder,
  parsePurchaseOrderLine,
} from "./inventory/index.ts";
export type {
  InventoryBalance,
  InventoryCount,
  InventoryCountLine,
  InventoryCountStatus,
  InventoryLocation,
  InventoryLocationArchiveBlockReason,
  InventoryLocationArchiveEligibility,
  InventoryLocationArchiveInput,
  InventoryLocationMutationResult,
  InventoryLocationSaveInput,
  InventoryMovement,
  InventoryMovementKind,
  InventoryMutationResult,
  InventoryTransfer,
  InventoryTransferLine,
  InventoryTransferStatus,
  PurchaseOrder,
  PurchaseOrderLine,
  PurchaseOrderStatus,
} from "./inventory/index.ts";
export {
  PRICE_CHANNELS,
  PRICE_LIST_STATUSES,
  PRICE_SOURCE_KINDS,
  parseEffectivePrice,
  parsePriceList,
  parsePriceListItem,
  parsePriceListRule,
  parsePricingPreviewEntry,
  parsePricingPreviewRequest,
  parsePricingPreviewResult,
} from "./pricing/index.ts";
export type {
  EffectivePrice,
  PriceChannel,
  PriceList,
  PriceListItem,
  PriceListRule,
  PriceListStatus,
  PriceSourceKind,
  PricingPreviewEntry,
  PricingPreviewRequest,
  PricingPreviewResult,
} from "./pricing/index.ts";
export {
  ANALYTICS_CONNECTION_STATUSES,
  ANALYTICS_METRIC_TYPES,
  ANALYTICS_RANGES,
  ANALYTICS_PERIODS,
  parseAnalyticsConnectionMutationResult,
  parseAnalyticsConnectionView,
  parseAnalyticsDashboard,
  parseAnalyticsMetricResult,
  parseAnalyticsSummary,
} from "./analytics/index.ts";
export type {
  AnalyticsConnectionMutationResult,
  AnalyticsConnectionStatus,
  AnalyticsConnectionView,
  AnalyticsDashboard,
  AnalyticsMetricResult,
  AnalyticsMetricRow,
  AnalyticsMetricType,
  AnalyticsPeriod,
  AnalyticsPoint,
  AnalyticsRange,
  AnalyticsSeriesPoint,
  AnalyticsSummary,
  AnalyticsTopProduct,
} from "./analytics/index.ts";
export {
  QUICK_ORDER_EXPIRY_HOURS,
  QUICK_ORDER_LINK_STATUSES,
  QUICK_ORDER_MAX_COMPONENT_CENTS,
  QUICK_ORDER_MAX_TOTAL_CENTS,
  QUICK_ORDER_MAX_UNIT_PRICE_CENTS,
  parseQuickOrderLinkDetail,
  parseQuickOrderLinkListItem,
  parseQuickOrderLinkMutationResult,
} from "./quick-orders/index.ts";
export type {
  QuickOrderAddress,
  QuickOrderLinkDetail,
  QuickOrderLinkItem,
  QuickOrderLinkListItem,
  QuickOrderLinkMutationResult,
  QuickOrderLinkStatus,
} from "./quick-orders/index.ts";
export {
  ORDER_PAYMENT_STATUSES,
  ORDER_SOURCES,
  ORDER_STATUSES,
  ORDER_SORTS,
  parseOrderDashboardSummary,
  parseOrderDetail,
  parseOrderListItem,
  parseOrderNeighbors,
} from "./orders/index.ts";
export {
  CATALOG_ADMIN_RESOURCE_KINDS,
  CATALOG_IMPORT_STATUSES,
  PRODUCT_REVIEW_STATUSES,
  parseBarcodeLabelRows,
  parseCatalogAdminImportJob,
  parseCatalogAdminMutationResult,
  parseCatalogImportPreview,
  parseCatalogAdminResource,
  parseProductReview,
} from "./catalog-admin/index.ts";
export {
  MERCHANT_ADMIN_RECORD_KINDS,
  MERCHANT_ADMIN_EVENT_KINDS,
  MERCHANT_ADMIN_PROVIDER_ACTIONS,
  MERCHANT_ADMIN_PROVIDER_JOB_STATUSES,
  MERCHANT_ADMIN_PROVIDER_RECORD_KINDS,
  MERCHANT_PROVIDER_CAPABILITIES,
  MERCHANT_PROVIDER_PROFILE_STATUSES,
  parseMerchantAdminConfig,
  parseMerchantAdminEvent,
  parseMerchantAdminMutationResult,
  parseMerchantAdminProviderJob,
  parseMerchantAdminProviderJobMutationResult,
  parseMerchantAdminRecord,
  parseMerchantProviderDescriptor,
  parseMerchantProviderProfile,
} from "./merchant-admin/index.ts";
export type {
  MerchantAdminJson,
  MerchantAdminEvent,
  MerchantAdminEventKind,
  MerchantAdminMutationResult,
  MerchantAdminProviderAction,
  MerchantAdminProviderJob,
  MerchantAdminProviderJobMutationResult,
  MerchantAdminProviderJobStatus,
  MerchantAdminProviderRecordKind,
  MerchantAdminRecord,
  MerchantAdminRecordKind,
  MerchantAdminRecordStatus,
  MerchantProviderCapability,
  MerchantProviderCredentialFieldDescriptor,
  MerchantProviderDescriptor,
  MerchantProviderFieldDescriptor,
  MerchantProviderProfile,
  MerchantProviderProfileStatus,
} from "./merchant-admin/index.ts";
export type {
  BarcodeLabelRow,
  CatalogAdminImportJob,
  CatalogAdminImportRow,
  CatalogAdminJson,
  CatalogAdminMutationResult,
  CatalogAdminResource,
  CatalogAdminResourceKind,
  CatalogAdminResourceStatus,
  CatalogImportStatus,
  CatalogImportFormat,
  CatalogImportPreview,
  ProductReview,
  ProductReviewStatus,
} from "./catalog-admin/index.ts";
export {
  ABANDONED_CART_SORTS,
  ABANDONED_CART_STATUSES,
  parseAbandonedCartDetail,
  parseAbandonedCartListItem,
  parseAbandonedCartMutationResult,
  parseAbandonedCartSummary,
} from "./abandoned-carts/index.ts";
export {
  CUSTOMER_CONSENT_CHANNELS,
  CUSTOMER_STATUSES,
  parseCustomerDetail,
  parseCustomerListItem,
  parseCustomerMutationResult,
  parseCustomerSegment,
  parseCustomerSummary,
  parseCustomerTag,
} from "./customers/index.ts";
export type {
  CustomerAddress,
  CustomerConsent,
  CustomerConsentChannel,
  CustomerConsentStatus,
  CustomerDetail,
  CustomerListItem,
  CustomerMutationResult,
  CustomerSegment,
  CustomerSegmentRef,
  CustomerStatus,
  CustomerSummary,
  CustomerTag,
  CustomerTagRef,
} from "./customers/index.ts";
export type {
  AbandonedCartDetail,
  AbandonedCartItem,
  AbandonedCartListItem,
  AbandonedCartMutationResult,
  AbandonedCartSort,
  AbandonedCartStatus,
  AbandonedCartSummary,
} from "./abandoned-carts/index.ts";
export type {
  OrderAddress,
  OrderDashboardSummary,
  OrderDetail,
  OrderEvent,
  OrderItem,
  OrderListItem,
  OrderNote,
  OrderNeighbor,
  OrderNeighbors,
  OrderPaymentStatus,
  OrderSource,
  OrderSort,
  OrderStatus,
  OrderTracking,
} from "./orders/index.ts";
export {
  BUILT_IN_PAYMENT_METHODS,
  PAYMENT_METHOD_KINDS,
  PAYMENT_METHOD_STATES,
  PAYMENT_PROVIDER_INTERACTION_MODES,
  PAYMENT_PROVIDER_READINESS,
  isBuiltInPaymentMethodKind,
  normalizeTurkishIbanInput,
  parseBuiltInPaymentMethodConfig,
  parseMerchantPaymentMethod,
  parsePaymentMethodMutationResult,
  parsePaymentMethodReorderResult,
  parsePaymentProviderCatalog,
  parsePaymentProviderCatalogEntry,
} from "./payment-providers/index.ts";
export type {
  BuiltInPaymentMethodKind,
  MerchantPaymentMethod,
  PaymentMethodKind,
  PaymentMethodMutationResult,
  PaymentMethodReorderResult,
  PaymentMethodState,
  PaymentProviderCatalogEntry,
  PaymentProviderCategory,
  PaymentProviderEnvironment,
  PaymentProviderExecutionAuthority,
  PaymentProviderInteractionMode,
  PaymentProviderReadiness,
  PaymentProviderSupport,
} from "./payment-providers/index.ts";
