import { ORDER_PAYMENT_STATUSES, ORDER_STATUSES, type OrderPaymentStatus, type OrderStatus } from "../orders/types.ts";
import { CUSTOMER_CONSENT_CHANNELS, CUSTOMER_STATUSES, type CustomerAddress, type CustomerConsent, type CustomerConsentChannel, type CustomerDetail, type CustomerListItem, type CustomerMutationResult, type CustomerNeighbor, type CustomerOrderSummary, type CustomerSegment, type CustomerSegmentRef, type CustomerStatus, type CustomerSummary, type CustomerTag, type CustomerTagRef, type CustomerWorkspace } from "./types.ts";

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const ISO=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;
const CONTROL=/[\u0000-\u001f\u007f]/; const EMAIL=/^[^\s@]+@[^\s@]+\.[^\s@]+$/; const PHONE=/^\+[1-9][0-9]{7,14}$/; const COLOR=/^#[0-9a-f]{6}$/; const CURRENCY=/^[A-Z]{3}$/; const COUNTRY=/^[A-Z]{2}$/;
function invalid():never{throw new TypeError("customer_contract_invalid")}
function object(v:unknown):Record<string,unknown>{if(typeof v!=="object"||v===null||Array.isArray(v))invalid();const p=Object.getPrototypeOf(v);if(p!==Object.prototype&&p!==null)invalid();return v as Record<string,unknown>}
function exact(v:unknown,required:readonly string[],optional:readonly string[]=[]){const r=object(v);const a=new Set([...required,...optional]);if(required.some(k=>!Object.hasOwn(r,k))||Object.keys(r).some(k=>!a.has(k)))invalid();return r}
function text(v:unknown,min:number,max:number,pattern?:RegExp){if(typeof v!=="string"||v.length<min||v.length>max||v!==v.trim()||CONTROL.test(v)||(pattern&&!pattern.test(v)))invalid();return v}
function uuid(v:unknown){return text(v,36,36,UUID)}
function integer(v:unknown,min=0,max=Number.MAX_SAFE_INTEGER){if(!Number.isSafeInteger(v)||(v as number)<min||(v as number)>max)invalid();return v as number}
function timestamp(v:unknown){const s=text(v,24,24,ISO);if(new Date(s).toISOString()!==s)invalid();return s}
function bool(v:unknown){if(typeof v!=="boolean")invalid();return v}
function freeze<T>(v:T):Readonly<T>{if(typeof v==="object"&&v!==null&&!Object.isFrozen(v)){for(const n of Object.values(v))freeze(n);Object.freeze(v)}return v}
function optionalText(r:Record<string,unknown>,key:string,min:number,max:number,pattern?:RegExp){return Object.hasOwn(r,key)?text(r[key],min,max,pattern):undefined}
function status(v:unknown):CustomerStatus{if(typeof v!=="string"||!CUSTOMER_STATUSES.includes(v as CustomerStatus))invalid();return v as CustomerStatus}
function tagRef(v:unknown):Readonly<CustomerTagRef>{const r=exact(v,["id","name","color"]);return freeze({id:uuid(r.id),name:text(r.name,1,64),color:text(r.color,7,7,COLOR)})}
function segmentRef(v:unknown):Readonly<CustomerSegmentRef>{const r=exact(v,["id","name","kind"]);if(r.kind!=="manual")invalid();return freeze({id:uuid(r.id),name:text(r.name,1,100),kind:"manual"})}

export function parseCustomerListItem(v:unknown):Readonly<CustomerListItem>{const r=exact(v,["id","status","displayName","firstName","lastName","orderCount","totalSpentCents","currency","tags","version","createdAt","updatedAt"],["email","phone","lastOrderAt"]);if(!Array.isArray(r.tags)||r.tags.length>50)invalid();const tags=r.tags.map(tagRef);for(let i=1;i<tags.length;i++)if(tags[i-1]!.name.localeCompare(tags[i]!.name)>=0)invalid();const createdAt=timestamp(r.createdAt),updatedAt=timestamp(r.updatedAt),lastOrderAt=Object.hasOwn(r,"lastOrderAt")?timestamp(r.lastOrderAt):undefined;if(updatedAt<createdAt||(lastOrderAt&&lastOrderAt<createdAt))invalid();const result:CustomerListItem={id:uuid(r.id),status:status(r.status),displayName:text(r.displayName,1,201),firstName:text(r.firstName,1,100),lastName:text(r.lastName,1,100),...(Object.hasOwn(r,"email")?{email:optionalText(r,"email",3,320,EMAIL)!}:{}),...(Object.hasOwn(r,"phone")?{phone:optionalText(r,"phone",9,16,PHONE)!}:{}),orderCount:integer(r.orderCount),totalSpentCents:integer(r.totalSpentCents),currency:text(r.currency,3,3,CURRENCY),...(lastOrderAt?{lastOrderAt}:{}),tags:Object.freeze(tags),version:integer(r.version,1),createdAt,updatedAt};return freeze(result)}
function address(v:unknown):Readonly<CustomerAddress>{const r=exact(v,["id","label","recipientName","line1","city","country","isDefault","version"],["line2","district","postalCode"]);return freeze({id:uuid(r.id),label:text(r.label,1,50),recipientName:text(r.recipientName,1,200),line1:text(r.line1,1,300),...(Object.hasOwn(r,"line2")?{line2:optionalText(r,"line2",1,300)!}:{}),city:text(r.city,1,100),...(Object.hasOwn(r,"district")?{district:optionalText(r,"district",1,100)!}:{}),...(Object.hasOwn(r,"postalCode")?{postalCode:optionalText(r,"postalCode",1,20)!}:{}),country:text(r.country,2,2,COUNTRY),isDefault:bool(r.isDefault),version:integer(r.version,1)})}
function consent(v:unknown):Readonly<CustomerConsent>{const r=exact(v,["channel","status","recordedAt"]);if(typeof r.channel!=="string"||!CUSTOMER_CONSENT_CHANNELS.includes(r.channel as CustomerConsentChannel)||(r.status!=="granted"&&r.status!=="denied"))invalid();return freeze({channel:r.channel as CustomerConsentChannel,status:r.status,recordedAt:timestamp(r.recordedAt)})}
function note(v:unknown){const r=exact(v,["id","text","createdAt"]);return freeze({id:uuid(r.id),text:text(r.text,1,2000),createdAt:timestamp(r.createdAt)})}
export function parseCustomerDetail(v:unknown):Readonly<CustomerDetail>{const r=object(v);const {addresses,consents,notes,segments,...base}=r;if(![addresses,consents,notes,segments].every(Array.isArray)||Object.keys(r).length!==Object.keys(base).length+4)invalid();const list=parseCustomerListItem(base);if((addresses as unknown[]).length>20||(consents as unknown[]).length>3||(notes as unknown[]).length>100||(segments as unknown[]).length>50)invalid();const parsedConsents=(consents as unknown[]).map(consent);if(new Set(parsedConsents.map(v=>v.channel)).size!==parsedConsents.length)invalid();return freeze({...list,addresses:Object.freeze((addresses as unknown[]).map(address)),consents:Object.freeze(parsedConsents),notes:Object.freeze((notes as unknown[]).map(note)),segments:Object.freeze((segments as unknown[]).map(segmentRef))})}
export function parseCustomerSummary(v:unknown):Readonly<CustomerSummary>{const r=exact(v,["active","archived","consentedEmail","totalSpentCents","currency","asOf"]);return freeze({active:integer(r.active),archived:integer(r.archived),consentedEmail:integer(r.consentedEmail),totalSpentCents:integer(r.totalSpentCents),currency:text(r.currency,3,3,CURRENCY),asOf:timestamp(r.asOf)})}
export function parseCustomerTag(v:unknown):Readonly<CustomerTag>{const r=exact(v,["id","name","color","customerCount","version"]);return freeze({...tagRef({id:r.id,name:r.name,color:r.color}),customerCount:integer(r.customerCount),version:integer(r.version,1)})}
export function parseCustomerSegment(v:unknown):Readonly<CustomerSegment>{const r=exact(v,["id","name","kind","customerCount","version"],["description"]);return freeze({...segmentRef({id:r.id,name:r.name,kind:r.kind}),...(Object.hasOwn(r,"description")?{description:optionalText(r,"description",1,500)!}:{}),customerCount:integer(r.customerCount),version:integer(r.version,1)})}
export function parseCustomerMutationResult(v:unknown):Readonly<CustomerMutationResult>{const r=exact(v,["id","version","status","updatedAt","replayed"]);return freeze({id:uuid(r.id),version:integer(r.version,1),status:status(r.status),updatedAt:timestamp(r.updatedAt),replayed:bool(r.replayed)})}

function customerNeighbor(v:unknown):Readonly<CustomerNeighbor>{const r=exact(v,["id","displayName"]);return freeze({id:uuid(r.id),displayName:text(r.displayName,1,201)})}
function customerOrder(v:unknown):Readonly<CustomerOrderSummary>{const r=exact(v,["id","orderNumber","status","paymentStatus","totalCents","currency","createdAt"]);if(typeof r.status!=="string"||!ORDER_STATUSES.includes(r.status as OrderStatus)||typeof r.paymentStatus!=="string"||!ORDER_PAYMENT_STATUSES.includes(r.paymentStatus as OrderPaymentStatus))invalid();return freeze({id:uuid(r.id),orderNumber:text(r.orderNumber,1,64),status:r.status as OrderStatus,paymentStatus:r.paymentStatus as OrderPaymentStatus,totalCents:integer(r.totalCents),currency:text(r.currency,3,3,CURRENCY),createdAt:timestamp(r.createdAt)})}
export function parseCustomerWorkspace(v:unknown):Readonly<CustomerWorkspace>{const r=exact(v,["neighbors","orders"]),neighbors=exact(r.neighbors,[],["previous","next"]);if(!Array.isArray(r.orders)||r.orders.length>50)invalid();const previous=Object.hasOwn(neighbors,"previous")?customerNeighbor(neighbors.previous):undefined,next=Object.hasOwn(neighbors,"next")?customerNeighbor(neighbors.next):undefined;if(previous&&next&&previous.id===next.id)invalid();const orders=r.orders.map(customerOrder);if(new Set(orders.map(order=>order.id)).size!==orders.length)invalid();return freeze({neighbors:freeze({...(previous?{previous}:{}),...(next?{next}:{})}),orders:Object.freeze(orders)})}
