export type OrderBumpRule = Readonly<{id:string;name:string;enabled:boolean;productIds:readonly string[];categoryIds:readonly string[];minSubtotalCents:number|null;maxSubtotalCents:number|null;variantIds:readonly string[]}>;
export type OrderBumpSettings = Readonly<{schemaVersion:1;enabled:boolean;heading:string;placements:Readonly<{sideCart:boolean;checkout:boolean}>;maxOffers:1|2|3;rules:readonly OrderBumpRule[]}>;
export type OrderBumpWorkspace = Readonly<{version:number;updatedAt:string|null;config:OrderBumpSettings}>;
export type OrderBumpOption = Readonly<{id:string;label:string;productId:string|null;priceCents:number|null;available:boolean}>;
export type OrderBumpOptionsPage = Readonly<{items:readonly OrderBumpOption[];page:number;totalCount:number}>;
export type OrderBumpPublicOffer = Readonly<{ruleId:string;productId:string;variantId:string;slug:string;title:string;variantTitle:string;priceCents:number;currency:'TRY';media:Readonly<{url:string;altText:string;width?:number;height?:number}>|null}>;
export type OrderBumpPublicOffers = Readonly<{cartVersion:number|null;heading:string|null;offers:readonly OrderBumpPublicOffer[]}>;
export class OrderBumpContractError extends Error{constructor(){super('order_bump_contract_invalid');this.name='OrderBumpContractError';}}
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u;
function invalid():never{throw new OrderBumpContractError();}
function exact(value:unknown,required:readonly string[],optional:readonly string[]=[]):Record<string,unknown>{if(typeof value!=='object'||value===null||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)invalid();const row=value as Record<string,unknown>,allowed=new Set([...required,...optional]);if(required.some(key=>!Object.hasOwn(row,key))||Object.keys(row).some(key=>!allowed.has(key)))invalid();return row;}
function integer(value:unknown,min:number,max=Number.MAX_SAFE_INTEGER):number{if(!Number.isSafeInteger(value)||(value as number)<min||(value as number)>max)invalid();return value as number;}
function text(value:unknown,min:number,max:number):string{if(typeof value!=='string'||value!==value.trim()||value.length<min||value.length>max||/[\u0000-\u001f\u007f-\u009f]/u.test(value))invalid();return value;}
function bool(value:unknown):boolean{if(typeof value!=='boolean')invalid();return value;}
function uuid(value:unknown):string{if(typeof value!=='string'||!UUID.test(value))invalid();return value;}
function ids(value:unknown,min:number,max:number):readonly string[]{if(!Array.isArray(value)||value.length<min||value.length>max)invalid();const parsed=value.map(uuid);if(new Set(parsed).size!==parsed.length)invalid();return Object.freeze(parsed);}
function cents(value:unknown):number{return integer(value,0,8_000_000_000);}
function timestamp(value:unknown):string{const parsed=text(value,24,24);try{if(new Date(parsed).toISOString()!==parsed)invalid();}catch{invalid();}return parsed;}
export function parseOrderBumpSettings(value:unknown):OrderBumpSettings{
 const row=exact(value,['schemaVersion','enabled','heading','placements','maxOffers','rules']);if(row.schemaVersion!==1)invalid();const p=exact(row.placements,['sideCart','checkout']),sideCart=bool(p.sideCart),checkout=bool(p.checkout);if(!sideCart&&!checkout)invalid();
 if(!Array.isArray(row.rules)||row.rules.length>20)invalid();const rules=row.rules.map(value=>{const r=exact(value,['id','name','enabled','productIds','categoryIds','minSubtotalCents','maxSubtotalCents','variantIds']),min=r.minSubtotalCents===null?null:cents(r.minSubtotalCents),max=r.maxSubtotalCents===null?null:cents(r.maxSubtotalCents);if(min!==null&&max!==null&&min>max)invalid();return Object.freeze({id:uuid(r.id),name:text(r.name,1,160),enabled:bool(r.enabled),productIds:ids(r.productIds,0,20),categoryIds:ids(r.categoryIds,0,20),minSubtotalCents:min,maxSubtotalCents:max,variantIds:ids(r.variantIds,1,6)});});if(new Set(rules.map(r=>r.id)).size!==rules.length)invalid();
 return Object.freeze({schemaVersion:1,enabled:bool(row.enabled),heading:text(row.heading,1,120),placements:Object.freeze({sideCart,checkout}),maxOffers:integer(row.maxOffers,1,3) as 1|2|3,rules:Object.freeze(rules)});
}
export function createDefaultOrderBumpSettings():OrderBumpSettings{return parseOrderBumpSettings({schemaVersion:1,enabled:false,heading:'Bunları da beğenebilirsiniz',placements:{sideCart:true,checkout:true},maxOffers:3,rules:[]});}
export function parseOrderBumpWorkspace(value:unknown):OrderBumpWorkspace{const r=exact(value,['version','updatedAt','config']),version=integer(r.version,0),updatedAt=r.updatedAt===null?null:timestamp(r.updatedAt),config=parseOrderBumpSettings(r.config);if((version===0)!==(updatedAt===null)||version===0&&JSON.stringify(config)!==JSON.stringify(createDefaultOrderBumpSettings()))invalid();return Object.freeze({version,updatedAt,config});}
export function parseOrderBumpOptionsPage(value:unknown):OrderBumpOptionsPage{const r=exact(value,['items','page','totalCount']);if(!Array.isArray(r.items)||r.items.length>400)invalid();const items=r.items.map(value=>{const o=exact(value,['id','label','productId','priceCents','available']);return Object.freeze({id:uuid(o.id),label:text(o.label,1,400),productId:o.productId===null?null:uuid(o.productId),priceCents:o.priceCents===null?null:cents(o.priceCents),available:bool(o.available)});});if(new Set(items.map(o=>o.id)).size!==items.length)invalid();const totalCount=integer(r.totalCount,0);if(totalCount<items.length)invalid();return Object.freeze({page:integer(r.page,1),totalCount,items:Object.freeze(items)});}
export function parseOrderBumpPublicOffers(value:unknown):OrderBumpPublicOffers{const r=exact(value,['cartVersion','heading','offers']),cartVersion=r.cartVersion===null?null:integer(r.cartVersion,1),heading=r.heading===null?null:text(r.heading,1,120);if(!Array.isArray(r.offers)||r.offers.length>3)invalid();const offers=r.offers.map(value=>{const o=exact(value,['ruleId','productId','variantId','slug','title','variantTitle','priceCents','currency','media']);if(o.currency!=='TRY')invalid();const slug=text(o.slug,1,100);if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/u.test(slug))invalid();let media:OrderBumpPublicOffer['media']=null;if(o.media!==null){const m=exact(o.media,['url','altText'],['width','height']),url=text(m.url,1,2048);try{const parsed=new URL(url);if(parsed.protocol!=='https:'||parsed.username||parsed.password||parsed.port||parsed.hash)invalid();}catch{invalid();}media=Object.freeze({url,altText:text(m.altText,0,400),...(Object.hasOwn(m,'width')?{width:integer(m.width,1,100_000)}:{}),...(Object.hasOwn(m,'height')?{height:integer(m.height,1,100_000)}:{})});}return Object.freeze({ruleId:uuid(o.ruleId),productId:uuid(o.productId),variantId:uuid(o.variantId),slug,title:text(o.title,1,400),variantTitle:text(o.variantTitle,1,400),priceCents:cents(o.priceCents),currency:'TRY' as const,media});});if(offers.length>0&&(cartVersion===null||heading===null)||new Set(offers.map(o=>o.productId)).size!==offers.length)invalid();return Object.freeze({cartVersion,heading,offers:Object.freeze(offers)});}
