import {createCipheriv,createDecipheriv,randomBytes} from 'node:crypto';
import {googleError} from './errors.ts';
export type GoogleMarketingCredentialKeyring=Readonly<{activeKeyId:string;keys:readonly Readonly<{keyId:string;key:Uint8Array}>[]}>;
export type GoogleCredential=Readonly<{accessToken:string;refreshToken:string;expiresAt:string;scopes:readonly string[];subject:string;email:string}>;
export type SealedGoogleCredential=Readonly<{algorithm:'A256GCM';version:1;keyId:string;iv:string;tag:string;ciphertext:string}>;
export function validateGoogleCredentialKeyring(keyring:GoogleMarketingCredentialKeyring|undefined):GoogleMarketingCredentialKeyring{
 if(!keyring||!/^[A-Za-z0-9._-]{1,128}$/.test(keyring.activeKeyId)||!Array.isArray(keyring.keys)||keyring.keys.length<1||keyring.keys.length>16)googleError('crypto_unavailable');const ids=new Set<string>();const keys=keyring.keys.map(entry=>{if(!entry||!/^[A-Za-z0-9._-]{1,128}$/.test(entry.keyId)||ids.has(entry.keyId)||!(entry.key instanceof Uint8Array)||entry.key.length!==32)googleError('crypto_unavailable');ids.add(entry.keyId);return Object.freeze({keyId:entry.keyId,key:new Uint8Array(entry.key)});});if(!ids.has(keyring.activeKeyId))googleError('crypto_unavailable');return Object.freeze({activeKeyId:keyring.activeKeyId,keys:Object.freeze(keys)});
}
function authority(storeId:string,service:string):Buffer{return Buffer.from(JSON.stringify(['celebix-google-oauth',1,storeId,service]));}
export function sealGoogleCredential(credential:GoogleCredential,storeId:string,service:string,keyring:GoogleMarketingCredentialKeyring):SealedGoogleCredential{
 const selected=validateGoogleCredentialKeyring(keyring);const key=selected.keys.find(k=>k.keyId===selected.activeKeyId)!.key;const iv=randomBytes(12);const plaintext=Buffer.from(JSON.stringify(credential));try{const cipher=createCipheriv('aes-256-gcm',key,iv);cipher.setAAD(authority(storeId,service));const bytes=Buffer.concat([cipher.update(plaintext),cipher.final()]);return {algorithm:'A256GCM',version:1,keyId:selected.activeKeyId,iv:iv.toString('base64url'),tag:cipher.getAuthTag().toString('base64url'),ciphertext:bytes.toString('base64url')};}finally{plaintext.fill(0);for(const k of selected.keys)k.key.fill(0);}}
export function openGoogleCredential(envelope:SealedGoogleCredential,storeId:string,service:string,keyring:GoogleMarketingCredentialKeyring):GoogleCredential{
 const selected=validateGoogleCredentialKeyring(keyring);let plaintext:Buffer|undefined;try{const key=selected.keys.find(k=>k.keyId===envelope.keyId)?.key;if(!key||envelope.algorithm!=='A256GCM'||envelope.version!==1||typeof envelope.ciphertext!=='string'||envelope.ciphertext.length>32768)googleError('crypto_unavailable');const iv=Buffer.from(envelope.iv,'base64url'),tag=Buffer.from(envelope.tag,'base64url');if(iv.length!==12||tag.length!==16)googleError('crypto_unavailable');const cipher=createDecipheriv('aes-256-gcm',key,iv);cipher.setAAD(authority(storeId,service));cipher.setAuthTag(tag);plaintext=Buffer.concat([cipher.update(Buffer.from(envelope.ciphertext,'base64url')),cipher.final()]);const v=JSON.parse(plaintext.toString('utf8')) as GoogleCredential;if(typeof v.accessToken!=='string'||!v.accessToken||v.accessToken.length>8192||typeof v.refreshToken!=='string'||v.refreshToken.length>8192||!Array.isArray(v.scopes)||!v.scopes.every(s=>typeof s==='string')||!Number.isFinite(Date.parse(v.expiresAt))||!v.subject||!v.email)googleError('crypto_unavailable');return Object.freeze(v);}catch{return googleError('crypto_unavailable');}finally{plaintext?.fill(0);for(const k of selected.keys)k.key.fill(0);}}
