import {createHash,randomBytes} from 'node:crypto';
import {GOOGLE_MARKETING_SERVICES,parseGoogleMarketingService,parseGoogleMarketingSelection,parseGoogleMarketingConnection,parsePublicGoogleMarketingProjection,type TenantContext,type GoogleMarketingService,type GoogleMarketingConnection,type GoogleMarketingSelection} from '@celebix/saas-contracts';
import {acquirePostgresClient} from '../postgres/pool.ts';
import {GoogleMarketingProvider,GOOGLE_SCOPES,GTM_INSTALL_SCOPES} from './provider.ts';
import {sealGoogleCredential,openGoogleCredential,validateGoogleCredentialKeyring,type GoogleCredential,type SealedGoogleCredential} from './credential-crypto.ts';
import {googleError,googleMarketingErrorCode,GOOGLE_MARKETING_ERROR_CODES,GoogleMarketingRepositoryError} from './errors.ts';
import type {GoogleMarketingRepository,GoogleMarketingAuthorityInput,PostgresGoogleMarketingRepositoryOptions} from './types.ts';
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const defaults={poolCheckoutMs:3000,statementMs:10000,lockMs:3000,idleTransactionMs:10000};
function uuid(value:unknown):string{if(typeof value!=='string'||!UUID.test(value))googleError('invalid_input');return value;}
function hash(value:string):string{return createHash('sha256').update(value).digest('hex');}
function date(value:Date):string{if(!(value instanceof Date)||!Number.isFinite(value.getTime()))googleError('invalid_input');return value.toISOString();}
function opaque(value:unknown,min=16,max=8192):string{if(typeof value!=='string'||value.length<min||value.length>max||/[\x00-\x20\x7f]/.test(value))googleError('invalid_input');return value;}
function expected(value:number):number{if(!Number.isSafeInteger(value)||value<0)googleError('invalid_input');return value;}
function origin(value:string):string{try{const u=new URL(value);if(u.protocol!=='https:'||u.origin!==value||u.username||u.password||u.port)googleError('invalid_input');return u.origin;}catch{googleError('invalid_input');}}
function stable(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(stable).join(',')}]`;return `{${Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stable(v)}`).join(',')}}`;}
function authority(input:GoogleMarketingAuthorityInput):unknown[]{const t=input.tenantContext;if(!t||t.schemaVersion!==1||t.store?.status!=='active'||t.membership?.status!=='active'||t.entitlements?.status!=='active'||!t.entitlements.features.includes('integrations'))googleError('membership_denied');return [uuid(t.store.id),uuid(t.principal.id),uuid(t.membership.id),uuid(t.entitlements.planId),t.entitlements.planCode,t.entitlements.version,date(input.now)];}
type Private={domain:string;connection:GoogleMarketingConnection;credential:SealedGoogleCredential|null;requiredScopes:readonly string[]};
export function createPostgresGoogleMarketingRepository(options:PostgresGoogleMarketingRepositoryOptions):GoogleMarketingRepository{
 const configuration=options.configuration;const provider=new GoogleMarketingProvider(configuration,options.fetch);const timeouts={...defaults,...options.timeouts};for(const timeout of Object.values(timeouts)){if(!Number.isSafeInteger(timeout)||timeout<1||timeout>60000)googleError('unavailable');}
 const configured=()=>Boolean(configuration.clientId&&configuration.clientSecret&&configuration.panelOrigin);
 const keyring=()=>validateGoogleCredentialKeyring(configuration.credentialKeyring);
 async function query(text:string,values:unknown[],publicRead=false):Promise<Record<string,any>>{
  const client=await acquirePostgresClient(options.pool,timeouts.poolCheckoutMs);let terminal=false;
  try{await client.query('BEGIN');await client.query("SELECT pg_catalog.set_config('statement_timeout',$1,true)",[`${timeouts.statementMs}ms`]);await client.query("SELECT pg_catalog.set_config('lock_timeout',$1,true)",[`${timeouts.lockMs}ms`]);await client.query("SELECT pg_catalog.set_config('idle_in_transaction_session_timeout',$1,true)",[`${timeouts.idleTransactionMs}ms`]);await client.query(publicRead?'SET LOCAL ROLE celebix_saas_host_resolver':'SET LOCAL ROLE celebix_saas_app');const r=await client.query(text,values);if(r.rows.length!==1||r.rowCount!==1)googleError('unavailable');try{await client.query('COMMIT');terminal=true;client.release();}catch{terminal=true;client.release(true);googleError('commit_unknown');}return r.rows[0]!;}catch(error){if(!terminal){try{await client.query('ROLLBACK');client.release();}catch{client.release(true);}}if(error instanceof GoogleMarketingRepositoryError)throw error;googleError('unavailable');}
 }
 async function command(input:GoogleMarketingAuthorityInput,action:string,payload:Record<string,unknown>,success:readonly string[]):Promise<{outcome:string;result:any}>{const r=await query('SELECT outcome,result_payload FROM saas.google_marketing_command($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::text,$9::jsonb)',[...authority(input),action,JSON.stringify(payload)]);if(success.includes(r.outcome))return {outcome:r.outcome,result:r.result_payload};if(GOOGLE_MARKETING_ERROR_CODES.includes(r.outcome))googleError(r.outcome);googleError('unavailable');}
 async function privateConnection(input:GoogleMarketingAuthorityInput,service:GoogleMarketingService):Promise<Private>{const r=await command(input,'private',{service},['private']);if(!r.result||typeof r.result.domain!=='string')googleError('unavailable');return {...r.result,connection:parseGoogleMarketingConnection(r.result.connection)};}
 async function access(input:GoogleMarketingAuthorityInput,service:GoogleMarketingService,selected:Private):Promise<GoogleCredential>{if(!selected.credential)googleError('needs_reconnect');const keys=keyring();let credential=openGoogleCredential(selected.credential,input.tenantContext.store.id,service,keys);if(Date.parse(credential.expiresAt)<=input.now.getTime()+60000){try{credential=await provider.refresh(credential,input.now);await command(input,'refresh',{service,credential:sealGoogleCredential(credential,input.tenantContext.store.id,service,keys),subject:credential.subject},['saved']);}catch(error){if(googleMarketingErrorCode(error)==='needs_reconnect')await command(input,'error',{service,code:'needs_reconnect'},['saved']);throw error;}}return credential;}
 async function installCredential(input:GoogleMarketingAuthorityInput,selected:Private):Promise<GoogleCredential>{const credential=await access(input,'gtm',selected);if(!GTM_INSTALL_SCOPES.every(scope=>credential.scopes.includes(scope))){await command(input,'scopes',{service:'gtm',scopes:GTM_INSTALL_SCOPES},['saved']);googleError('incremental_authorization_required');}return credential;}
 const repository:GoogleMarketingRepository={
  async overview(input){const r=await command(input,'overview',{},['found']);return {storeDomain:r.result.domain,oauthConfigured:configured(),connections:r.result.connections.map(parseGoogleMarketingConnection)};},
  async begin(input){if(!configured())googleError('oauth_unconfigured');keyring();const service=parseGoogleMarketingService(input.service),returnOrigin=origin(input.returnOrigin),panelOrigin=origin(configuration.panelOrigin!);if(!configuration.allowedReturnOrigins?.includes(returnOrigin)&&!configuration.allowReturnOrigin?.(returnOrigin,input.tenantContext))googleError('invalid_input');const state=randomBytes(32).toString('base64url');const r=await command(input,'start_oauth',{service,operationId:uuid(input.operationId),stateHash:hash(state),sessionHash:hash(opaque(input.sessionBinding)),returnOrigin},['started']);const scopes=['openid','email',...GOOGLE_SCOPES[service],...(service==='gtm'?r.result.scopes??[]:[])];const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');for(const [key,value]of Object.entries({client_id:configuration.clientId!,redirect_uri:`${panelOrigin}/api/marketing/google/callback`,response_type:'code',state,scope:[...new Set(scopes)].join(' '),access_type:'offline',prompt:'consent',include_granted_scopes:'true'}))url.searchParams.set(key,value);return {authorizationUrl:url.toString()};},
  async resolveOAuthReturn(input){opaque(input.state,43,43);const r=await query('SELECT saas.google_marketing_oauth_return($1::text,$2::timestamptz) AS result_payload',[hash(input.state),date(input.now)]);return r.result_payload;},
  async complete(input){if(!configured())googleError('oauth_unconfigured');const keys=keyring();opaque(input.code,1,8192);const stateHash=hash(opaque(input.state,43,43));const r=await command(input,'consume_state',{stateHash,sessionHash:hash(opaque(input.sessionBinding))},['consumed']);const service=parseGoogleMarketingService(r.result.service);const previous=await privateConnection(input,service);const priorCredential=previous.credential?openGoogleCredential(previous.credential,input.tenantContext.store.id,service,keys):undefined;const credential=await provider.exchange(input.code,input.now,priorCredential);if(!GOOGLE_SCOPES[service].every(scope=>credential.scopes.includes(scope)))googleError('oauth_denied');await command(input,'credential',{service,stateHash,subject:credential.subject,email:credential.email,credential:sealGoogleCredential(credential,input.tenantContext.store.id,service,keys)},['saved']);return {returnOrigin:r.result.returnOrigin};},
  async resources(input){const service=parseGoogleMarketingService(input.service);if(input.accountId!==undefined)opaque(input.accountId,1,160);const selected=await privateConnection(input,service);const credential=await access(input,service,selected);try{return await provider.resources(service,credential.accessToken,input.accountId);}catch(error){if(googleMarketingErrorCode(error)==='needs_reconnect')await command(input,'error',{service,code:'needs_reconnect'},['saved']);throw error;}},
  async apply(input){const service=parseGoogleMarketingService(input.service),selection=parseGoogleMarketingSelection(input.selection),operationId=uuid(input.operationId),expectedVersion=expected(input.expectedVersion);const fingerprint=hash(stable({kind:'apply',service,selection,expectedVersion}));const claimed=await command(input,'claim',{service,operationId,expectedVersion,fingerprint,selection,kind:'apply'},['claimed','operation_replayed']);if(claimed.outcome==='operation_replayed')return parseGoogleMarketingConnection(claimed.result);
   let progress:Record<string,unknown>=claimed.result.progress??{};const leaseToken=claimed.result.leaseToken;const checkpoint=async(next:Record<string,unknown>)=>{await command(input,'checkpoint',{service,operationId,leaseToken,progress:next},['saved']);progress=next;};
   try{const selected=await privateConnection(input,service);let validated:GoogleMarketingSelection,verificationToken:string|undefined;
    if(service==='gtm'){const credential=await installCredential(input,selected);const ads=await privateConnection(input,'ads');validated=await provider.applyGtm(credential.accessToken,selection,selected.domain,operationId,progress,checkpoint,ads.connection.status==='connected'?ads.connection.selection??undefined:undefined);}
    else{const credential=await access(input,service,selected);if(service==='ads'){validated=await provider.validateSelection(service,credential.accessToken,selection,selected.domain);const gtm=await privateConnection(input,'gtm');if(gtm.connection.status==='connected'&&gtm.connection.selection){const gtmCredential=await installCredential(input,gtm);await provider.applyGtm(gtmCredential.accessToken,gtm.connection.selection,gtm.domain,operationId,progress,checkpoint,validated);}}
     else{const result=await provider.applySearchConsole(credential.accessToken,selection,selected.domain,progress,checkpoint);validated=result.selection;verificationToken=result.verificationToken;}}
    const result=await command(input,'finalize',{service,operationId,leaseToken,selection:validated,...(verificationToken?{verificationToken}:{})},['saved','operation_replayed']);return parseGoogleMarketingConnection(result.result);
   }catch(error){const code=googleMarketingErrorCode(error);try{await command(input,'fail',{service,operationId,leaseToken,code},['saved']);}catch{}throw error instanceof GoogleMarketingRepositoryError?error:new GoogleMarketingRepositoryError('unavailable');}
  },
  async disconnect(input){const service=parseGoogleMarketingService(input.service),expectedVersion=expected(input.expectedVersion),operationId=uuid(input.operationId);const fingerprint=hash(stable({kind:'disconnect',service,expectedVersion}));const r=await command(input,'disconnect',{service,expectedVersion,operationId,fingerprint},['saved','operation_replayed']);return parseGoogleMarketingConnection(r.result);},
  async publicProjection(storeId){const r=await query('SELECT saas.public_google_marketing_projection($1::uuid) AS result_payload',[uuid(storeId)],true);return parsePublicGoogleMarketingProjection(r.result_payload);}
 };return repository;
}
