import {
  PROMOTION_AUDIENCE_MODES, PROMOTION_BENEFIT_KINDS, PROMOTION_ERROR_CODES, PROMOTION_STATUSES, PROMOTION_TARGET_KINDS,
  type PromotionAnalytics, type PromotionAudience, type PromotionBenefit, type PromotionCodeBatch, type PromotionCombinationPolicy,
  type PromotionConditions, type PromotionCsvRow, type PromotionDetail, type PromotionEffectiveStatus, type PromotionEvaluatorCartLine,
  type PromotionEvaluatorContext, type PromotionEvaluatorResult, type PromotionLegacyProjection, type PromotionLifecycleInput,
  type PromotionLimits, type PromotionListQuery, type PromotionMarginPolicy, type PromotionRuleDocument, type PromotionSafeError,
  type PromotionSchedule, type PromotionSimulatorResponse, type PromotionTargetReference, type PromotionTargets, type PromotionTrigger,
} from "./types.ts";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const ISO = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}(?:\d{3})?Z$/;
const CONTROL_OR_SPACE = /[\s\u0000-\u001f\u007f]/u;
const TEXT_CONTROL = /[\u0000-\u001f\u007f]/u;
const MAX_MINOR = 8_000_000_000;
type Input = Readonly<Record<string, unknown>>;

function invalid(): never { throw new TypeError("promotion_contract_invalid"); }
function guarded<T>(parse: () => T): T { try { return parse(); } catch { return invalid(); } }
function record(value: unknown): object { if (typeof value !== "object" || value === null || Array.isArray(value)) invalid(); const prototype = Object.getPrototypeOf(value); if (prototype !== Object.prototype && prototype !== null) invalid(); return value; }
function exact(value: unknown, required: readonly string[], optional: readonly string[] = []): Input { const descriptors = Object.getOwnPropertyDescriptors(record(value)); const allowed = new Set([...required, ...optional]); const keys = Reflect.ownKeys(descriptors); if (keys.some((key) => typeof key !== "string" || !allowed.has(key)) || required.some((key) => !Object.hasOwn(descriptors, key))) invalid(); const output = Object.create(null) as Record<string, unknown>; for (const key of keys) { if (typeof key !== "string") invalid(); const descriptor = descriptors[key]; if (!descriptor || !("value" in descriptor) || !descriptor.enumerable) invalid(); output[key] = descriptor.value; } return output; }
function integer(value: unknown, min: number, max: number): number { if (!Number.isSafeInteger(value) || (value as number) < min || (value as number) > max) invalid(); return value as number; }
function text(value: unknown, min: number, max: number): string { if (typeof value !== "string" || value.length < min || value.length > max || value !== value.trim() || TEXT_CONTROL.test(value)) invalid(); return value; }
function uuid(value: unknown): string { const parsed = text(value, 36, 36); if (!UUID.test(parsed)) invalid(); return parsed; }
function currency(value: unknown): string { const parsed = text(value, 3, 3); if (!/^[A-Z]{3}$/.test(parsed)) invalid(); return parsed; }
function timestamp(value: unknown): string { if (typeof value !== "string" || !ISO.test(value)) invalid(); const date = new Date(value); if (!Number.isFinite(date.getTime())) invalid(); return value; }
function timezone(value: unknown): string { const parsed = text(value, 1, 64); try { new Intl.DateTimeFormat("en-US", { timeZone: parsed }); } catch { invalid(); } return parsed; }
function freeze<T>(value: T): T { if (typeof value === "object" && value !== null && !Object.isFrozen(value)) { for (const entry of Object.values(value)) freeze(entry); Object.freeze(value); } return value; }
function array<T>(value: unknown, min: number, max: number, parse: (entry: unknown) => T): readonly T[] { if (!Array.isArray(value) || Object.getPrototypeOf(value) !== Array.prototype) invalid(); const descriptors = Object.getOwnPropertyDescriptors(value); if (value.length < min || value.length > max || Reflect.ownKeys(descriptors).length !== value.length + 1) invalid(); const output: T[] = []; for (let i = 0; i < value.length; i += 1) { const descriptor = descriptors[String(i)]; if (!descriptor || !("value" in descriptor) || !descriptor.enumerable) invalid(); output.push(parse(descriptor.value)); } return Object.freeze(output); }
function unique<T>(values: readonly T[], selector: (value: T) => string): readonly T[] { if (new Set(values.map(selector)).size !== values.length) invalid(); return values; }

export function normalizePromotionCode(value: unknown): string { if (typeof value !== "string" || value.length < 1 || value.length > 64 || CONTROL_OR_SPACE.test(value)) invalid(); const normalized = value.replace(/ı/g, "i").replace(/İ/g, "I").replace(/ş/gi, "s").replace(/ç/gi, "c").replace(/ğ/gi, "g").replace(/ö/gi, "o").replace(/ü/gi, "u").toUpperCase(); if (!/^[A-Z0-9_-]+$/.test(normalized)) invalid(); return normalized; }
function target(value: unknown): PromotionTargetReference { const parsed = exact(value, ["kind", "id"]); if (typeof parsed.kind !== "string" || !PROMOTION_TARGET_KINDS.includes(parsed.kind as never)) invalid(); return freeze({ kind: parsed.kind as PromotionTargetReference["kind"], id: uuid(parsed.id) }); }
function targets(value: unknown): PromotionTargets { const parsed = exact(value, ["mode", "include", "exclude"]); if (parsed.mode !== "all" && parsed.mode !== "selected") invalid(); const include = unique(array(parsed.include, 0, 500, target), (row) => `${row.kind}:${row.id}`); const exclude = unique(array(parsed.exclude, 0, 500, target), (row) => `${row.kind}:${row.id}`); const overlaps = new Set(include.map((row) => `${row.kind}:${row.id}`)); if (exclude.some((row) => overlaps.has(`${row.kind}:${row.id}`)) || (parsed.mode === "selected" && include.length === 0)) invalid(); return freeze({ mode: parsed.mode, include, exclude }); }
function audience(value: unknown): PromotionAudience { const parsed = exact(value, ["mode"], ["referenceIds"]); if (typeof parsed.mode !== "string" || !PROMOTION_AUDIENCE_MODES.includes(parsed.mode as never)) invalid(); const needsReferences = ["customer_segments", "customer_tags", "masked_customers"].includes(parsed.mode); const hasReferences = Object.hasOwn(parsed, "referenceIds"); if (needsReferences !== hasReferences) invalid(); const referenceIds = hasReferences ? unique(array(parsed.referenceIds, 1, 500, uuid), (id) => id) : undefined; return freeze({ mode: parsed.mode as PromotionAudience["mode"], ...(referenceIds ? { referenceIds } : {}) }); }
function trigger(value: unknown): PromotionTrigger { const parsed = exact(value, ["kind"], ["codes"]); if (parsed.kind === "automatic") { if (Object.hasOwn(parsed, "codes")) invalid(); return freeze({ kind: "automatic" }); } if (parsed.kind !== "code" || !Object.hasOwn(parsed, "codes")) invalid(); const codes = unique(array(parsed.codes, 1, 10_000, normalizePromotionCode), (code) => code); return freeze({ kind: "code", codes }); }
function schedule(value: unknown): PromotionSchedule { const parsed = exact(value, ["timezone"], ["startsAt", "endsAt"]); const startsAt = Object.hasOwn(parsed, "startsAt") ? timestamp(parsed.startsAt) : undefined; const endsAt = Object.hasOwn(parsed, "endsAt") ? timestamp(parsed.endsAt) : undefined; if (endsAt !== undefined && (startsAt === undefined || endsAt <= startsAt)) invalid(); return freeze({ timezone: timezone(parsed.timezone), ...(startsAt ? { startsAt } : {}), ...(endsAt ? { endsAt } : {}) }); }
function limits(value: unknown): PromotionLimits { const parsed = exact(value, ["totalUsage", "perCustomerUsage", "budgetMinor", "orderMaximumMinor"]); const nullable = (entry: unknown, maximum: number) => entry === null ? null : integer(entry, 0, maximum); return freeze({ totalUsage: nullable(parsed.totalUsage, 1_000_000_000), perCustomerUsage: nullable(parsed.perCustomerUsage, 1_000_000_000), budgetMinor: nullable(parsed.budgetMinor, MAX_MINOR), orderMaximumMinor: nullable(parsed.orderMaximumMinor, MAX_MINOR) }); }
function conditions(value: unknown): PromotionConditions { const parsed = exact(value, ["minimumBasketMinor", "minimumQuantity", "minimumProductQuantity"]); return freeze({ minimumBasketMinor: integer(parsed.minimumBasketMinor, 0, MAX_MINOR), minimumQuantity: integer(parsed.minimumQuantity, 0, 1_000_000), minimumProductQuantity: integer(parsed.minimumProductQuantity, 0, 1_000_000) }); }
function benefit(value: unknown): PromotionBenefit { const root = exact(value, ["kind"], ["percentageBps", "amountMinor", "currency", "buyQuantity", "receiveQuantity", "discountPercentageBps", "tiers", "bundleQuantity", "bundlePriceMinor", "giftVariantId"]); switch (root.kind) { case "percentage": { const parsed = exact(value, ["kind", "percentageBps"]); return freeze({ kind: "percentage", percentageBps: integer(parsed.percentageBps, 1, 10_000) }); } case "fixed_amount": { const parsed = exact(value, ["kind", "amountMinor", "currency"]); return freeze({ kind: "fixed_amount", amountMinor: integer(parsed.amountMinor, 1, MAX_MINOR), currency: currency(parsed.currency) }); } case "free_shipping": exact(value, ["kind"]); return freeze({ kind: "free_shipping" }); case "buy_x_get_y": { const parsed = exact(value, ["kind", "buyQuantity", "receiveQuantity", "discountPercentageBps"]); return freeze({ kind: "buy_x_get_y", buyQuantity: integer(parsed.buyQuantity, 1, 1_000_000), receiveQuantity: integer(parsed.receiveQuantity, 1, 1_000_000), discountPercentageBps: integer(parsed.discountPercentageBps, 1, 10_000) }); } case "quantity_tiers": { const parsed = exact(value, ["kind", "tiers"]); const tiers = array(parsed.tiers, 1, 20, (tier) => { const row = exact(tier, ["minimumQuantity", "percentageBps"]); return freeze({ minimumQuantity: integer(row.minimumQuantity, 1, 1_000_000), percentageBps: integer(row.percentageBps, 1, 10_000) }); }); for (let i = 1; i < tiers.length; i += 1) if (tiers[i - 1]!.minimumQuantity >= tiers[i]!.minimumQuantity) invalid(); return freeze({ kind: "quantity_tiers", tiers }); } case "bundle_price": { const parsed = exact(value, ["kind", "bundleQuantity", "bundlePriceMinor", "currency"]); return freeze({ kind: "bundle_price", bundleQuantity: integer(parsed.bundleQuantity, 2, 1_000_000), bundlePriceMinor: integer(parsed.bundlePriceMinor, 0, MAX_MINOR), currency: currency(parsed.currency) }); } case "gift": { const parsed = exact(value, ["kind", "giftVariantId"]); return freeze({ kind: "gift", giftVariantId: uuid(parsed.giftVariantId) }); } default: invalid(); } }
function combinationPolicy(value: unknown): PromotionCombinationPolicy { const root = exact(value, ["kind"], ["benefitClasses"]); if (root.kind === "none" || root.kind === "shipping_only") { exact(value, ["kind"]); return freeze({ kind: root.kind }); } if (root.kind !== "benefit_classes") invalid(); const parsed = exact(value, ["kind", "benefitClasses"]); const benefitClasses = unique(array(parsed.benefitClasses, 1, 7, (entry) => { if (typeof entry !== "string" || !PROMOTION_BENEFIT_KINDS.includes(entry as never)) invalid(); return entry as PromotionBenefit["kind"]; }), (entry) => entry); return freeze({ kind: "benefit_classes", benefitClasses }); }
function marginPolicy(value: unknown): PromotionMarginPolicy { const root = exact(value, ["kind"], ["maximumPercentageBps"]); if (root.kind === "warn" || root.kind === "floor_at_cost") { exact(value, ["kind"]); return freeze({ kind: root.kind }); } if (root.kind !== "maximum_percentage") invalid(); const parsed = exact(value, ["kind", "maximumPercentageBps"]); return freeze({ kind: "maximum_percentage", maximumPercentageBps: integer(parsed.maximumPercentageBps, 0, 10_000) }); }

export function parsePromotionRuleDocument(value: unknown): PromotionRuleDocument { return guarded(() => { const parsed = exact(value, ["schemaVersion", "benefit", "targets", "audience", "trigger", "schedule", "limits", "conditions", "combinationPolicy", "priority", "marginPolicy", "progressMessagePolicy"]); const progress = exact(parsed.progressMessagePolicy, ["enabled"]); if (progress.enabled !== true && progress.enabled !== false) invalid(); return freeze({ schemaVersion: integer(parsed.schemaVersion, 1, 1) as 1, benefit: benefit(parsed.benefit), targets: targets(parsed.targets), audience: audience(parsed.audience), trigger: trigger(parsed.trigger), schedule: schedule(parsed.schedule), limits: limits(parsed.limits), conditions: conditions(parsed.conditions), combinationPolicy: combinationPolicy(parsed.combinationPolicy), priority: integer(parsed.priority, 0, 1_000), marginPolicy: marginPolicy(parsed.marginPolicy), progressMessagePolicy: freeze({ enabled: progress.enabled }) }); }); }
export function derivePromotionLifecycle(input: PromotionLifecycleInput): PromotionEffectiveStatus { return guarded(() => { const now = timestamp(input.now); const scheduleInput = exact(input.schedule, ["timezone"], ["startsAt", "endsAt"]); const startsAt = Object.hasOwn(scheduleInput, "startsAt") ? timestamp(scheduleInput.startsAt) : undefined; const endsAt = Object.hasOwn(scheduleInput, "endsAt") ? timestamp(scheduleInput.endsAt) : undefined; if (startsAt && endsAt && endsAt <= startsAt) invalid(); timezone(scheduleInput.timezone); const currentLimits = exact(input.limits, ["totalUsage", "budgetMinor"]); const totalUsage = currentLimits.totalUsage === null ? null : integer(currentLimits.totalUsage, 0, 1_000_000_000); const budgetMinor = currentLimits.budgetMinor === null ? null : integer(currentLimits.budgetMinor, 0, MAX_MINOR); const usage = exact(input.usage, ["total", "budgetSpentMinor"]); const total = integer(usage.total, 0, 1_000_000_000); const spent = integer(usage.budgetSpentMinor, 0, MAX_MINOR); if (typeof input.status !== "string" || !PROMOTION_STATUSES.includes(input.status as never)) invalid(); if (input.status !== "active") return input.status; if ((endsAt && now >= endsAt)) return "ended"; if ((totalUsage !== null && total >= totalUsage) || (budgetMinor !== null && spent >= budgetMinor)) return "exhausted"; return "active"; }); }
function cartLine(value: unknown): PromotionEvaluatorCartLine { const parsed = exact(value, ["lineId", "position", "productId", "variantId", "quantity", "unitPriceMinor", "costMinor", "currency", "categoryIds", "brandId", "collectionIds"]); const costMinor = parsed.costMinor === null ? null : integer(parsed.costMinor, 0, MAX_MINOR); const brandId = parsed.brandId === null ? null : uuid(parsed.brandId); return freeze({ lineId: uuid(parsed.lineId), position: integer(parsed.position, 0, 100), productId: uuid(parsed.productId), variantId: uuid(parsed.variantId), quantity: integer(parsed.quantity, 1, 1_000_000), unitPriceMinor: integer(parsed.unitPriceMinor, 0, MAX_MINOR), costMinor, currency: currency(parsed.currency), categoryIds: unique(array(parsed.categoryIds, 0, 100, uuid), (id) => id), brandId, collectionIds: unique(array(parsed.collectionIds, 0, 100, uuid), (id) => id) }); }
export function parsePromotionEvaluatorContext(value: unknown): PromotionEvaluatorContext { return guarded(() => { const parsed = exact(value, ["storeId", "customerId", "paidOrderCount", "customerSegmentIds", "customerTagIds", "cartLines", "shippingMethodId", "paymentMethodId", "currency", "storeLocalTime", "salesChannel", "submittedCodes", "abandonedCart"]); const customerId = parsed.customerId === null ? null : uuid(parsed.customerId); const shippingMethodId = parsed.shippingMethodId === null ? null : uuid(parsed.shippingMethodId); const paymentMethodId = parsed.paymentMethodId === null ? null : uuid(parsed.paymentMethodId); const abandonedCart = parsed.abandonedCart === null ? null : freeze({ id: uuid(exact(parsed.abandonedCart, ["id"]).id) }); const cartLines = unique(array(parsed.cartLines, 0, 20, cartLine), (line) => line.lineId); return freeze({ storeId: uuid(parsed.storeId), customerId, paidOrderCount: integer(parsed.paidOrderCount, 0, 1_000_000_000), customerSegmentIds: unique(array(parsed.customerSegmentIds, 0, 100, uuid), (id) => id), customerTagIds: unique(array(parsed.customerTagIds, 0, 100, uuid), (id) => id), cartLines, shippingMethodId, paymentMethodId, currency: currency(parsed.currency), storeLocalTime: timestamp(parsed.storeLocalTime), salesChannel: text(parsed.salesChannel, 1, 64), submittedCodes: unique(array(parsed.submittedCodes, 0, 5, normalizePromotionCode), (code) => code), abandonedCart }); }); }
export function parsePromotionEvaluatorResult(value: unknown): PromotionEvaluatorResult { return guarded(() => { const parsed = exact(value, ["eligiblePromotionIds", "appliedPromotions", "rejectedPromotions", "lineEffects", "shippingDiscountMinor", "gifts", "preDiscountTotalMinor", "postDiscountTotalMinor", "currency", "progressMessages", "merchantExplanation"]); const appliedPromotions = array(parsed.appliedPromotions, 0, 100, (entry) => { const row = exact(entry, ["promotionId", "version", "name", "benefitKind", "discountMinor"], ["normalizedCode"]); if (typeof row.benefitKind !== "string" || !PROMOTION_BENEFIT_KINDS.includes(row.benefitKind as never)) invalid(); const normalizedCode = Object.hasOwn(row, "normalizedCode") ? normalizePromotionCode(row.normalizedCode) : undefined; return freeze({ promotionId: uuid(row.promotionId), version: integer(row.version, 1, 1_000_000_000), name: text(row.name, 1, 200), benefitKind: row.benefitKind as PromotionBenefit["kind"], ...(normalizedCode ? { normalizedCode } : {}), discountMinor: integer(row.discountMinor, 0, MAX_MINOR) }); }); const lineEffects = array(parsed.lineEffects, 0, 20, (entry) => { const row = exact(entry, ["lineId", "discountMinor", "giftQuantity"]); return freeze({ lineId: uuid(row.lineId), discountMinor: integer(row.discountMinor, 0, MAX_MINOR), giftQuantity: integer(row.giftQuantity, 0, 1_000_000) }); }); const gifts = array(parsed.gifts, 0, 100, (entry) => { const row = exact(entry, ["variantId", "quantity"]); return freeze({ variantId: uuid(row.variantId), quantity: integer(row.quantity, 1, 1_000_000) }); }); const pre = integer(parsed.preDiscountTotalMinor, 0, MAX_MINOR); const post = integer(parsed.postDiscountTotalMinor, 0, MAX_MINOR); const shipping = integer(parsed.shippingDiscountMinor, 0, MAX_MINOR); if (post > pre || appliedPromotions.reduce((sum, item) => sum + item.discountMinor, 0) + shipping < pre - post) invalid(); return freeze({ eligiblePromotionIds: unique(array(parsed.eligiblePromotionIds, 0, 100, uuid), (id) => id), appliedPromotions: unique(appliedPromotions, (item) => item.promotionId), rejectedPromotions: unique(array(parsed.rejectedPromotions, 0, 100, (entry) => { const row = exact(entry, ["promotionId", "reason"]); return freeze({ promotionId: uuid(row.promotionId), reason: text(row.reason, 1, 100) }); }), (item) => item.promotionId), lineEffects: unique(lineEffects, (item) => item.lineId), shippingDiscountMinor: shipping, gifts, preDiscountTotalMinor: pre, postDiscountTotalMinor: post, currency: currency(parsed.currency), progressMessages: array(parsed.progressMessages, 0, 2, (entry) => text(entry, 1, 200)), merchantExplanation: text(parsed.merchantExplanation, 1, 500) }); }); }
export function parsePromotionListQuery(value: unknown): PromotionListQuery { return guarded(() => { const parsed = exact(value, ["cursor", "limit", "statuses"], ["search"]); const cursor = parsed.cursor === null ? null : text(parsed.cursor, 1, 512); const search = Object.hasOwn(parsed, "search") ? text(parsed.search, 1, 100) : undefined; const statuses = unique(array(parsed.statuses, 0, 5, (entry) => { if (typeof entry !== "string" || !PROMOTION_STATUSES.includes(entry as never)) invalid(); return entry as PromotionListQuery["statuses"][number]; }), (entry) => entry); return freeze({ cursor, limit: integer(parsed.limit, 1, 100), ...(search ? { search } : {}), statuses }); }); }
export function parsePromotionDetail(value: unknown): PromotionDetail { return guarded(() => { const parsed = exact(value, ["id", "version", "name", "status", "ruleDocument", "createdAt", "updatedAt"]); if (typeof parsed.status !== "string" || !PROMOTION_STATUSES.includes(parsed.status as never)) invalid(); const createdAt = timestamp(parsed.createdAt); const updatedAt = timestamp(parsed.updatedAt); if (updatedAt < createdAt) invalid(); return freeze({ id: uuid(parsed.id), version: integer(parsed.version, 1, 1_000_000_000), name: text(parsed.name, 1, 200), status: parsed.status as PromotionDetail["status"], ruleDocument: parsePromotionRuleDocument(parsed.ruleDocument), createdAt, updatedAt }); }); }
export function parsePromotionSimulatorResponse(value: unknown): PromotionSimulatorResponse { return guarded(() => { const parsed = exact(value, ["evaluation", "mutated"]); if (parsed.mutated !== false) invalid(); return freeze({ evaluation: parsePromotionEvaluatorResult(parsed.evaluation), mutated: false }); }); }
export function parsePromotionCodeBatch(value: unknown): PromotionCodeBatch { return guarded(() => { const parsed = exact(value, ["id", "promotionId", "status", "count", "createdAt"]); if (parsed.status !== "active" && parsed.status !== "paused" && parsed.status !== "revoked") invalid(); return freeze({ id: uuid(parsed.id), promotionId: uuid(parsed.promotionId), status: parsed.status, count: integer(parsed.count, 1, 10_000), createdAt: timestamp(parsed.createdAt) }); }); }
export function parsePromotionCsvRow(value: unknown): PromotionCsvRow { return guarded(() => { const parsed = exact(value, ["code", "status"]); if (parsed.status !== "active" && parsed.status !== "paused" && parsed.status !== "revoked") invalid(); const code = normalizePromotionCode(parsed.code); if (/^[=+\-@]/.test(code)) invalid(); return freeze({ code, status: parsed.status }); }); }
export function parsePromotionAnalytics(value: unknown): PromotionAnalytics { return guarded(() => { const parsed = exact(value, ["currency", "redemptions", "discountMinor", "revenueMinor", "conversionBps"]); return freeze({ currency: currency(parsed.currency), redemptions: integer(parsed.redemptions, 0, 1_000_000_000), discountMinor: integer(parsed.discountMinor, 0, MAX_MINOR), revenueMinor: integer(parsed.revenueMinor, 0, MAX_MINOR), conversionBps: integer(parsed.conversionBps, 0, 10_000) }); }); }
export function parsePromotionLegacyProjection(value: unknown): PromotionLegacyProjection { return guarded(() => { const parsed = exact(value, ["legacyRecordId", "promotionId", "reason"]); return freeze({ legacyRecordId: uuid(parsed.legacyRecordId), promotionId: parsed.promotionId === null ? null : uuid(parsed.promotionId), reason: text(parsed.reason, 1, 100) }); }); }
export function safePromotionError(value: unknown): PromotionSafeError { return freeze({ code: typeof value === "string" && PROMOTION_ERROR_CODES.includes(value as never) ? value as PromotionSafeError["code"] : "promotion_unavailable" }); }
