import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const read = (name: string) => readFile(new URL(name, import.meta.url), "utf8");

test("home exhaustively renders the finite public section union", async () => { const source = await read("CampaignHome.tsx"); for (const kind of ["hero", "category_grid", "product_row", "split_campaign", "brand_story"]) assert.match(source, new RegExp(`case [\"']${kind}[\"']`)); assert.match(source, /assertNever/); });
test("empty optional sections do not create blank storefront bands", async () => { const module = await import("./campaign-home-sections.ts"); const presentation = { sections: [{ kind: "hero", slides: [{ heading: "Hero", destination: "/products" }] }, { kind: "category_grid", heading: "Kategoriler", items: [] }, { kind: "product_row", key: "empty", heading: "Boş", source: "latest", limit: 4 }, { kind: "split_campaign", panels: [] }] }; assert.deepEqual(module.visibleCampaignSectionKinds({ presentation, productRows: [{ key: "empty", items: [] }] } as never), ["hero"]); });
test("hero uses stable desktop mobile media and canonical hotspot", async () => { const source = await read("CampaignHero.tsx"); for (const token of ["<picture", "mobileImage", "desktopImage", "width=", "height=", "hotspot.productSlug", "hotspot.priceCents"]) assert.match(source, new RegExp(token)); });
test("hero rotation is explicit scroll snap without autoplay", async () => { const [client, css] = await Promise.all([read("CampaignHeroClient.tsx"), read("campaign-home.module.css")]); assert.match(client, /scrollBy/); assert.match(client, /Önceki slayt/); assert.match(client, /Sonraki slayt/); assert.doesNotMatch(client, /setInterval|autoplay/); assert.match(css, /scroll-snap-type/); });
test("category and campaign panels use only safe public relative destinations", async () => { const source = await read("CampaignPanels.tsx"); assert.match(source, /`\/categories\/\$\{item[.]slug\}`/); assert.match(source, /panel[.]destination/); assert.doesNotMatch(source, /assetId|categoryId|storeId|tenantId/); });
test("product rows bind exact projection keys to canonical product cards", async () => { const source = await read("CampaignProductRow.tsx"); assert.match(source, /section[.]key/); assert.match(source, /ProductGrid/); assert.match(source, /products/); assert.doesNotMatch(source, /Math[.]random|fake|mock/); });
test("home page resolves campaign projection only through server page context", async () => { const [page, context] = await Promise.all([read("../app/page.tsx"), read("../lib/page-context.ts")]); assert.match(page, /context[.]campaign/); assert.match(context, /resolveCampaignHome/); assert.doesNotMatch(`${page}\n${context}`, /localStorage|sessionStorage|x-store-id|tenantId/); });
test("campaign home remains responsive stable and reduced-motion safe", async () => { const css = await read("campaign-home.module.css"); assert.match(css, /aspect-ratio/); assert.match(css, /@media\(max-width:700px\)/); assert.match(css, /prefers-reduced-motion/); assert.match(css, /min-height:48px/); });
