import assert from "node:assert/strict";
import test from "node:test";
import React from "react";
import { componentLoader, withProductBrowser } from "./product-variant-media-test-utils.ts";
import { wheelAward, wheelCampaign } from "../lib/lucky-wheel/test-utils.ts";
async function fixture(run: (value: { container: HTMLElement; click(selector: string): Promise<void>; bridge: { acquireEngagementModal(owner: symbol): boolean; releaseEngagementModal(owner: symbol): void; registerEngagementCart(value: unknown): () => void }; route(path: string): Promise<void>; loaded(): number }) => Promise<void>, disabled = false) {
  let loaded = 0;
  const load = componentLoader({ "next/navigation": { usePathname: () => window.location.pathname }, "next/dynamic": { __esModule: true, default: () => (props: { onClose(): void }) => { loaded++; return React.createElement("section", { role: "dialog", "aria-modal": true }, React.createElement("button", { "data-close-wheel": true, onClick: props.onClose }, "Kapat")); } }, "../lib/lucky-wheel/client.ts": { createLuckyWheelClient: () => ({ settings: async () => ({ campaign: disabled ? null : wheelCampaign() }), recoverResult: async () => null }) } });
  const { LuckyWheelLauncher } = load<{ LuckyWheelLauncher: React.ComponentType<Record<string, unknown>> }>(new URL("./LuckyWheelLauncher.tsx", import.meta.url)), bridge = load<any>(new URL("../lib/engagement/integration.ts", import.meta.url));
  await withProductBrowser(async ({ container, render, click }) => { const previous = globalThis.HTMLElement; Object.assign(globalThis, { HTMLElement: window.HTMLElement }); const element = React.createElement(LuckyWheelLauncher, { storefrontId: "store", storefrontName: "Mağaza", applyCoupon: async () => "" }); try { await render(element); await React.act(async () => { await new Promise(resolve => window.setTimeout(resolve, 25)); }); await run({ container, click, bridge, loaded: () => loaded, route: async path => { window.history.replaceState({}, "", path); await render(React.cloneElement(element)); } }); } finally { Object.assign(globalThis, { HTMLElement: previous }); } });
}
test("enabled wheel starts as small launcher and loads modal only after visitor opens it", async () => { await fixture(async ({ container, click, loaded }) => { assert.ok(container.querySelector("[data-wheel-launcher]")); assert.equal(container.querySelector('[role="dialog"]'), null); assert.equal(loaded(), 0); assert.equal(Boolean(document.activeElement === container.querySelector('[data-wheel-launcher]')), false, "first load does not move focus"); await click("[data-wheel-launcher]"); assert.equal(loaded(), 1); assert.equal(container.querySelectorAll('[role="dialog"]').length, 1); }); await fixture(async ({ container, loaded }) => { assert.equal(container.querySelector("[data-wheel-launcher]"), null); assert.equal(loaded(), 0); }, true); });
test("wheel waits drawer closure and holds lease until close; active engagement wins concurrent launch", async () => { await fixture(async ({ container, click, bridge, loaded }) => { const owner = Symbol("popup"); bridge.acquireEngagementModal(owner); await click("[data-wheel-launcher]"); assert.equal(loaded(), 0); bridge.releaseEngagementModal(owner); let closed = false; const retire = bridge.registerEngagementCart({ storefrontId: "store", getCart: () => null, closeDrawerAndWait: async () => { closed = true; return true; } }); try { await click("[data-wheel-launcher]"); assert.equal(closed, true); assert.equal(bridge.acquireEngagementModal(owner), false); await click("[data-close-wheel]"); assert.equal(bridge.acquireEngagementModal(owner), true); bridge.releaseEngagementModal(owner); } finally { retire(); } }); });
test("checkout account payment routes and another visible dialog prevent opening", async () => { await fixture(async ({ container, route, click, loaded }) => { for (const path of ["/checkout", "/checkout/payment/result", "/account/login", "/payments/result"]) { await route(path); assert.equal(container.querySelector("[data-wheel-launcher]"), null); } await route("/products/one"); const other = document.createElement("dialog"); other.open = true; document.body.append(other); await click("[data-wheel-launcher]"); assert.equal(loaded(), 0); other.remove(); }); });
test("last quota award remains accessible after reload with no public campaign and no second spin", async () => {
  let saved: typeof wheelAward | null = null, spins = 0, settingsReads = 0, recoveries = 0;
  const realClient = await import("../lib/lucky-wheel/client.ts");
  const client = { spin: async (input: { operationId: string }) => { spins++; saved = { ...wheelAward, operationId: input.operationId }; return saved; }, result: async () => saved, settings: async () => { settingsReads++; return { campaign: saved ? null : wheelCampaign() }; }, recoverResult: async () => { recoveries++; return saved; } };
  const load = componentLoader({ "next/navigation": { usePathname: () => window.location.pathname }, "next/dynamic": { __esModule: true, default: (loader: () => Promise<{ default: React.ComponentType<any> }>) => { const Lazy = React.lazy(async () => ({ default: await loader() as unknown as React.ComponentType<any> })); return (props: any) => React.createElement(React.Suspense, { fallback: "Yükleniyor" }, React.createElement(Lazy, props)); } }, "../lib/lucky-wheel/client.ts": { ...realClient, createLuckyWheelClient: () => client } });
  const { LuckyWheel } = load<{ LuckyWheel: React.ComponentType<any> }>(new URL("./LuckyWheel.tsx", import.meta.url)), { LuckyWheelLauncher } = load<{ LuckyWheelLauncher: React.ComponentType<any> }>(new URL("./LuckyWheelLauncher.tsx", import.meta.url));
  await withProductBrowser(async ({ container, render, click }) => {
    const previous = globalThis.HTMLElement; Object.assign(globalThis, { HTMLElement: window.HTMLElement }); window.matchMedia = () => ({ matches: true }) as MediaQueryList;
    const props = { storefrontId: "store", storefrontName: "Mağaza", onClose() {}, applyCoupon: async () => "Kod hazır" };
    try {
      await render(React.createElement(LuckyWheel, { ...props, campaign: wheelCampaign() }));
      const input = container.querySelector<HTMLInputElement>('input[type="email"]')!; await React.act(async () => { Object.getOwnPropertyDescriptor(Object.getPrototypeOf(input), "value")!.set!.call(input, "ada@example.test"); input.dispatchEvent(new window.Event("input", { bubbles: true })); });
      await click('button[type="submit"]'); assert.equal(spins, 1); assert.ok(container.textContent?.includes(wheelAward.couponCode));
      await render(null); await render(React.createElement(LuckyWheelLauncher, props)); await React.act(async () => { await new Promise(resolve => window.setTimeout(resolve, 30)); });
      assert.equal(settingsReads, 1); assert.equal(recoveries, 1); assert.ok(container.querySelector('[data-wheel-launcher]')); assert.equal(container.querySelector('[role="dialog"]'), null);
      await click('[data-wheel-launcher]'); await React.act(async () => { await new Promise(resolve => window.setTimeout(resolve, 50)); });
      assert.ok(container.textContent?.includes(wheelAward.couponCode)); assert.equal(spins, 1); assert.equal(Boolean(container.querySelector('input, form, [data-wheel-new-participation]')), false); assert.equal(container.querySelectorAll('[role="dialog"]').length, 1);
      await React.act(async () => { document.dispatchEvent(new window.KeyboardEvent("keydown", { key: "Escape", bubbles: true })); }); await React.act(async () => { await new Promise(resolve => window.setTimeout(resolve, 35)); });
      assert.equal(Boolean(document.activeElement === container.querySelector('[data-wheel-launcher]')), true, "Escape restores focus to the recreated launcher");
    } finally { Object.assign(globalThis, { HTMLElement: previous }); }
  });
});
for (const recoveryCase of ["first", "renewed", "not_committed"]) test(recoveryCase === "first" ? "lost first spin response recovers the same last-quota award without an operation cookie after reload" : recoveryCase === "renewed" ? "older operation cookie cannot mask a newer lost-response last-quota award after reload" : "missing newer operation preserves the previous verified award after checking the latest reference", async () => {
  const olderCookie = recoveryCase !== "first";
  let saved: typeof wheelAward | null = null, attemptedOperation = "", spins = 0, beforeSpin: { campaignId: string; operationId: string } | null = null; const lookups: string[][] = [];
  const oldAward = { ...wheelAward, repeatEligibleAt: "2026-10-09T12:00:00.000Z" }, latestCode = "W-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
  const realClient = await import("../lib/lucky-wheel/client.ts");
  const client = { spin: async (input: { campaignId: string; operationId: string }) => { beforeSpin = bridge.readLatestWheelParticipationOperation("store"); attemptedOperation = input.operationId; spins++; if (recoveryCase !== "not_committed") saved = { ...wheelAward, operationId: input.operationId, couponCode: latestCode, ruleDocument: { ...wheelAward.ruleDocument, trigger: { kind: "code", codes: [latestCode] } } }; throw Error("initial response and Set-Cookie lost"); }, result: async (campaignId: string, operationId?: string) => { lookups.push([campaignId, operationId ?? ""]); return saved?.campaignId === campaignId && saved.operationId === operationId ? saved : olderCookie && campaignId === oldAward.campaignId && (!operationId || operationId === oldAward.operationId) ? oldAward : null; }, settings: async () => ({ campaign: null }), recoverResult: async () => olderCookie ? oldAward : null };
  const load = componentLoader({ "next/navigation": { usePathname: () => window.location.pathname }, "next/dynamic": { __esModule: true, default: (loader: () => Promise<unknown>) => { const Lazy = React.lazy(async () => ({ default: await loader() as React.ComponentType<any> })); return (props: any) => React.createElement(React.Suspense, { fallback: "Yükleniyor" }, React.createElement(Lazy, props)); } }, "../lib/lucky-wheel/client.ts": { ...realClient, createLuckyWheelClient: () => client } });
  const { LuckyWheel } = load<{ LuckyWheel: React.ComponentType<any> }>(new URL("./LuckyWheel.tsx", import.meta.url)), { LuckyWheelLauncher } = load<{ LuckyWheelLauncher: React.ComponentType<any> }>(new URL("./LuckyWheelLauncher.tsx", import.meta.url)), bridge = load<{ readLatestWheelParticipationOperation(storefrontId: string): { campaignId: string; operationId: string } | null }>(new URL("../lib/engagement/integration.ts", import.meta.url));
  await withProductBrowser(async ({ container, render, click }) => {
    const previous = globalThis.HTMLElement; Object.assign(globalThis, { HTMLElement: window.HTMLElement }); window.matchMedia = () => ({ matches: true }) as MediaQueryList;
    const props = { storefrontId: "store", storefrontName: "Mağaza", onClose() {}, applyCoupon: async () => "Kod hazır" };
    try {
      await render(React.createElement(LuckyWheel, { ...props, campaign: wheelCampaign() })); await React.act(async () => { await new Promise(resolve => window.setTimeout(resolve, 25)); });
      if (olderCookie) await click('[data-wheel-new-participation]');
      const input = container.querySelector<HTMLInputElement>('input[type="email"]')!; await React.act(async () => { Object.getOwnPropertyDescriptor(Object.getPrototypeOf(input), "value")!.set!.call(input, "ada@example.test"); input.dispatchEvent(new window.Event("input", { bubbles: true })); });
      await click('button[type="submit"]'); assert.equal(spins, 1); assert.equal(Boolean(container.textContent?.includes(latestCode)), false); assert.deepEqual(beforeSpin, { campaignId: wheelAward.campaignId, operationId: attemptedOperation });
      const stored = Array.from({ length: window.sessionStorage.length }, (_, index) => window.sessionStorage.getItem(window.sessionStorage.key(index)!)); assert.doesNotMatch(JSON.stringify(stored), /ada@example|phone|marketingConsent/);
      await render(null); await render(React.createElement(LuckyWheelLauncher, props)); await React.act(async () => { await new Promise(resolve => window.setTimeout(resolve, 40)); });
      assert.equal(Boolean(container.querySelector('[data-wheel-launcher]')), true);
      await click('[data-wheel-launcher]'); await React.act(async () => { await new Promise(resolve => window.setTimeout(resolve, 50)); });
      assert.ok(container.textContent?.includes(recoveryCase === "not_committed" ? oldAward.couponCode : latestCode)); assert.equal(spins, 1); assert.deepEqual(lookups.at(-1), [wheelAward.campaignId, attemptedOperation]); assert.equal(Boolean(container.querySelector('input, form, [data-wheel-new-participation]')), false);
    } finally { Object.assign(globalThis, { HTMLElement: previous }); }
  });
});
