import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const read = (name: string) => readFile(new URL(name, import.meta.url), "utf8");
const product = (patch: Record<string, unknown> = {}) => ({ id: "10000000-0000-4000-8000-000000000001", slug: "urun", title: "Ürün", currency: "TRY", status: "active", priceCents: 1500, available: true, variants: [{ id: "20000000-0000-4000-8000-000000000001", title: "Standart", priceCents: 1500, stockTracking: true, stockQuantity: 2, available: true, attributes: {} }], media: [], ...patch });

test("product badge is derived only from canonical price and availability", async () => { const { productBadge } = await import("./product-card-model.ts"); assert.equal(productBadge(product({ compareAtCents: 2000 }) as never), "sale"); assert.equal(productBadge(product({ available: false }) as never), "unavailable"); assert.equal(productBadge(product() as never), null); });
test("variant products require selection instead of an invented default", async () => { const { cardAction } = await import("./product-card-model.ts"); assert.equal(cardAction(product() as never), "quick_add"); assert.equal(cardAction(product({ variants: [...product().variants, { ...product().variants[0], id: "20000000-0000-4000-8000-000000000002", title: "Büyük" }] }) as never), "choose_options"); assert.equal(cardAction(product({ available: false }) as never), "unavailable"); });
test("quick view is modal focus-safe and reuses canonical purchase logic", async () => { const source = await read("ProductQuickView.tsx"); for (const token of ["aria-modal=\"true\"", "event.key === \"Escape\"", "event.key === \"Tab\"", "triggerRef.current?.focus", "event.target === event.currentTarget", "ProductPurchasePanel", "product.media"]) assert.match(source, new RegExp(token.replace("?", "\\?"))); assert.match(source, /formatTry\(product[.]priceCents\)/); assert.doesNotMatch(source, /storeId|tenantId|localStorage|sessionStorage|computedTotal/); });
test("cards keep stable first media second hover media and finite canonical actions", async () => { const [card, css] = await Promise.all([read("ProductCard.tsx"), read("../app/globals.css")]); assert.match(card, /product[.]media\[0\]/); assert.match(card, /product[.]media\[1\]/); assert.match(card, /productBadge/); assert.match(card, /cardAction/); assert.match(card, /Hızlı ekle/); assert.match(card, /ProductQuickView/); assert.match(css, /product-image-secondary/); assert.match(css, /product-card-badge/); });
