"use client";
import {createContext,useContext,useEffect,useId,useRef,useState,type FormEvent,type ReactNode} from 'react';
import type {PublicProduct,RestockAlertsConfig} from '@celebix/saas-contracts';
import styles from './restock-alerts.module.css';
const Context=createContext<RestockAlertsConfig|null>(null);
export const useRestockAlertsConfig=()=>useContext(Context);
export function RestockAlertsProvider({config,children}:Readonly<{config:RestockAlertsConfig|null;children:ReactNode}>){return <Context.Provider value={config?.enabled?config:null}>{children}</Context.Provider>;}
export function RestockSubscriptionForm({product,variant}:Readonly<{product:PublicProduct;variant:PublicProduct['variants'][number]|undefined}>){const config=useRestockAlertsConfig();if(!config||!variant||variant.available||!variant.stockTracking)return null;return <Subscription key={variant.id} config={config} productTitle={product.title} variant={variant}/>;}
function Subscription({config,productTitle,variant}:Readonly<{config:RestockAlertsConfig;productTitle:string;variant:PublicProduct['variants'][number]}>){
 const [open,setOpen]=useState(false),[email,setEmail]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState('');const id=useId(),field=useRef<HTMLInputElement>(null),pending=useRef(false),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);useEffect(()=>{if(open)field.current?.focus();},[open]);
 async function submit(event:FormEvent){event.preventDefault();if(pending.current||!consent)return;pending.current=true;setBusy(true);setError('');try{const response=await fetch('/api/restock/subscribe',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({variantId:variant.id,email,consent:true})});if(!response.ok)throw Error('request_failed');if(mounted.current)setDone(true);}catch{if(mounted.current)setError('Bildirim isteği alınamadı. Bilgileriniz korunuyor; yeniden deneyin.');}finally{pending.current=false;if(mounted.current)setBusy(false);}}
 return <section className={styles.alert} data-restock-alert aria-labelledby={id}>
 <button className={styles.launcher} type="button" data-restock-open aria-expanded={open} aria-controls={`${id}-form`} onClick={()=>setOpen(value=>!value)}><svg width="18" height="18" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9Z"/><path d="M9 21h6"/></svg><span id={id}>{config.title}</span></button>
 {open?<div id={`${id}-form`} className={styles.content}>{done?<p role="status">İstek uygunsa e-posta adresinize bir onay bağlantısı gönderilecek. Gelen kutunuzu ve spam klasörünü kontrol edin.</p>:<form onSubmit={event=>void submit(event)} noValidate><p><strong>{productTitle}</strong><span>{variant.title}</span></p><label htmlFor={`${id}-email`}>E-posta<input ref={field} id={`${id}-email`} name="restock-email" type="email" autoComplete="email" inputMode="email" required maxLength={254} value={email} disabled={busy} onChange={event=>setEmail(event.target.value)}/></label><label className={styles.consent}><input name="restock-consent" type="checkbox" checked={consent} disabled={busy} onChange={event=>setConsent(event.target.checked)}/><span>Yalnız bu seçenek tekrar stokta olduğunda bir kez e-posta almak istiyorum. Bu bir pazarlama aboneliği değildir.</span></label>{error?<p role="alert">{error}</p>:null}<button type="submit" className="store-button" disabled={busy||!consent||!email.trim()}>{busy?'Gönderiliyor…':config.buttonLabel}</button><small>E-postadaki bağlantıyla isteğinizi onaylayabilir veya iptal edebilirsiniz. Bildirim stok ayırmaz.</small></form>}</div>:null}
 </section>;
}
export function RestockManageAction({token,action}:Readonly<{token:string;action:'confirm'|'cancel'}>){const[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState('');const pending=useRef(false);async function submit(){if(pending.current)return;pending.current=true;setBusy(true);setError('');try{const response=await fetch('/api/restock/manage',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({token,action})});if(!response.ok)throw Error();setDone(true);}catch{setError('İşlem tamamlanamadı. Yeniden deneyin.');}finally{pending.current=false;setBusy(false);}}return done?<p role="status">{action==='confirm'?'Bağlantı geçerliyse stok bildiriminiz onaylandı.':'Bildirim isteğiniz iptal edildi.'}</p>:<>{error?<p role="alert">{error}</p>:null}<button type="button" className="store-button" disabled={busy} onClick={()=>void submit()}>{busy?'İşleniyor…':action==='confirm'?'Stok bildirimini onayla':'Bildirimi iptal et'}</button></>;}

/** Capability stays in the fragment: never sent to page requests or referrers. */
export function RestockManagePage(){const[value,setValue]=useState<{token:string;action:'confirm'|'cancel'}|null>(null),[ready,setReady]=useState(false);useEffect(()=>{const query=new URLSearchParams(window.location.hash.slice(1)),token=query.get('token')??'',action=query.get('action');window.history.replaceState(window.history.state,'',window.location.pathname+window.location.search);if(/^[A-Za-z0-9_-]{43}$/u.test(token)&&(action==='confirm'||action==='cancel'))setValue({token,action});setReady(true);},[]);return <><h1>{value?.action==='cancel'?'Bildirimi iptal edin':'Stok bildirimini onaylayın'}</h1><p>Bu istek yalnız seçtiğiniz ürün seçeneği içindir. Pazarlama aboneliği oluşturmaz.</p>{!ready?<p role="status">Bağlantı kontrol ediliyor…</p>:value?<RestockManageAction {...value}/>:<p>Bağlantı geçersiz. E-postanızdaki bağlantıyı yeniden açın.</p>}</>;}
