export const TOSHI_PANEL_HELP = Object.freeze([
  { title: "Ürün ekleme ve düzenleme", keywords: "ürün ekle yükle düzenle açıklama fotoğraf fiyat varyant", href: "/products/new", text: "Ürünler ekranındaki yeni ürün akışından başlık, görseller, fiyat ve varyantları girin. Taslak olarak kaydedebilir veya yayınlayabilirsiniz. Var olan ürünü Ürünler listesinden açıp düzenleyin. Toshi açıklama taslağı önerebilir; kaydetme işlemini ürün ekranında siz tamamlarsınız." },
  { title: "Gram, ağırlık ve fiziksel ölçüler", keywords: "gram ağırlık kilo kuyumcu 14,89 hacim uzunluk en boy yükseklik alan paket", href: "/products/new", text: "Ürün yükleme/düzenleme akışındaki isteğe bağlı fiziksel bilgiler alanlarını kullanın. Ağırlıkta g veya kg seçin; örneğin 14,89 g girebilirsiniz. Hacim, uzunluk, en/derinlik/yükseklik, alan ve paket adedi de isteğe bağlıdır. Ölçü değeri stok adedi veya fiyat değildir; satmadığınız ürün niteliğini boş bırakın." },
  { title: "Barkod ve etiket", keywords: "barkod barkot atama etiket okuyucu okut yazdır", href: "/products/barcode-labels", text: "Ürün veya varyant barkod alanındaki atama kontrolü 98 veya 99 ile başlayan 13 haneli dahili EAN-13 barkod üretir. Barkod etiketleri ekranında ürün/varyantları seçerek etiket yazdırabilirsiniz. Okuyucu ve etiket aynı barkod standardını desteklemelidir." },
  { title: "Mağazada satış ve manuel POS", keywords: "pos mağazada mağaza satış kasa okut ödeme manuel indirim", href: "/orders/quick-links", text: "Mağazada satış ekranında barkod okuyucu veya ürün aramayla sepete ürün ekleyin, gerekiyorsa indirim uygulayın. Fiziksel POS cihazında tahsilatı manuel olarak alın; Toshi veya panel POS cihazından ödeme çekmez. Panelde ödeme ve satış tamamlama adımını doğrulayın. Stok ve sipariş kaydı tamamlanan satış akışı tarafından yönetilir." },
  { title: "Siparişler ve numaralar", keywords: "sipariş web pos numara ödeme kargo durum", href: "/orders", text: "Siparişler ekranında numarayla arayın, siparişi açıp ödeme/kargo/durum bilgilerini kontrol edin. Yeni internet siparişleri WEB-, mağaza satışları POS- serisini kullanır; eski sipariş numaraları korunur. Ödeme veya sipariş durumunu değiştirmek için yetkili ekranı kullanın; Toshi burada yalnız kayıtları okur." },
  { title: "İndirim ve kampanya", keywords: "indirim kampanya kupon kod yüzde otomatik yayınla", href: "/discounts", text: "İndirimler ekranında yeni kampanya oluşturun. Fayda, geçerli ürünler, müşteri kitlesi, tarih ve kullanım sınırlarını belirleyip önizlemeyi kontrol edin; uygun yetkiyle yayınlayın. Toshi kampanya fikri/metni önerebilir ve mevcut kampanyaları okuyabilir; kampanyayı kendiliğinden yayınlamaz." },
  { title: "Stok ve depo", keywords: "stok düşük tükenen bitti depo sayım satın transfer", href: "/products", text: "Ürünler listesindeki stok özetini ve varyant detaylarını kontrol edin. Stok sayımı, satın alma ve transfer alt ekranları depo hareketlerini yönetir. Stok takibi kapalı ürün, sıfır stok ve eşik altı düşük stok farklı durumlardır. Depo stok sonucu yalnız seçilen depoyu kapsar." },
  { title: "Satış ve analiz", keywords: "analiz satış ciro gelir rapor bugün dün hafta ay iade", href: "/analytics", text: "Analizler ekranında tarih aralığını ve para birimini seçin. Brüt satış, iadeler ve net tutarları ayrı okuyun. Farklı para birimlerini birbirine toplamayın; seçilen mağaza saat dilimi gün sınırını belirler." },
  { title: "Müşteri kayıtları", keywords: "müşteri bul ara sipariş geçmiş not segment etiket", href: "/customers", text: "Müşteriler ekranında isimle arayıp müşteriyi açın. Sipariş geçmişi, segmentler ve etiketler yetkinize göre kullanılabilir. Toshi arama ve toplu alışveriş bilgilerini okuyabilir; adres, telefon ve e-posta gibi gereksiz kişisel bilgileri model bağlamına taşımaz." },
  { title: "Yapay zekâ bağlantısı", keywords: "yapay zeka deepseek openai gemini claude anahtar api bakiye varsayılan model", href: "/settings/artificial-intelligence", text: "Yapay Zeka ayarlarında kendi sağlayıcı anahtarınızı bağlayın, doğrulanan modelden seçim yapın ve varsayılan sağlayıcıyı belirleyin. Yeni Toshi konuşmaları bu sağlayıcı/modeli kullanır; eski konuşma aynı sağlayıcı/modelde kalır. Bakiye veya anahtar hatasını sağlayıcı hesabınızda giderin. Anahtarınızı sohbete yapıştırmayın." },
]);

export function findPanelHelp(query: string) {
  const terms = query.toLocaleLowerCase("tr-TR").split(/\s+/u).filter(term => term.length > 1);
  return TOSHI_PANEL_HELP.map(article => ({ article, score: terms.reduce((count, term) => count + Number(`${article.title} ${article.keywords}`.toLocaleLowerCase("tr-TR").includes(term)), 0) }))
    .filter(item => item.score > 0).sort((a, b) => b.score - a.score).slice(0, 5).map(({ article }) => article);
}
