import assert from "node:assert/strict";
import test from "node:test";
import { PostgresProductMediaRepository } from "./index.ts";
const STORE_ID="10000000-0000-4000-8000-000000000001", PRODUCT_ID="20000000-0000-4000-8000-000000000001", OPERATION_ID="50000000-0000-4000-8000-000000000001", VARIANT_ID="80000000-0000-4000-8000-000000000001", MEDIA_ID="40000000-0000-4000-8000-000000000001";
const now=new Date("2026-10-01T09:00:00.000Z");
const tenantContext = { schemaVersion: 1, requestId: OPERATION_ID, principal: { id: "60000000-0000-4000-8000-000000000001", issuer: "https://identity.example.test/oidc", subject: "pilot" }, store: { id: STORE_ID, slug: "pilot-store", status: "active" }, membership: { id: "70000000-0000-4000-8000-000000000001", role: "store_owner", status: "active" }, entitlements: { schemaVersion: 1, planId: "00000000-0000-4000-8000-000000000001", planCode: "free_starter", version: 1, status: "active", features: ["catalog", "media"], limits: { products: 100, staff: 1, storageBytes: 1_000_000_000 }, validFrom: "2026-01-01T00:00:00.000Z" }, locale: "tr-TR" } as const;
function fixture(outcome="committed", failCommit=false, payload:any={gallery:{productId:PRODUCT_ID,version:2,assignments:[{variantId:VARIANT_ID,mediaIds:[MEDIA_ID]}]}}){
 const calls:{text:string;values:unknown[]}[]=[];
 const repo=new PostgresProductMediaRepository({pool:{async connect(){return {async query(text:string,values:unknown[]=[]){calls.push({text,values});if(text==="COMMIT"&&failCommit)throw Error("lost");return {rows:text.startsWith("SELECT outcome")?[{outcome,result_payload:payload}]:[],rowCount:text.startsWith("SELECT outcome")?1:0,command:"SELECT",oid:0,fields:[]};},release(){}};}},role:"celebix_saas_app",mediaOrigin:"https://media.saas-staging.celebix.site",timeouts:{poolCheckoutMs:100,statementMs:100,lockMs:100,idleTransactionMs:100},audit(){}});
 return {repo,calls};
}
const input={tenantContext,now,productId:PRODUCT_ID,operationId:OPERATION_ID,expectedVersion:1,assignments:[{variantId:VARIANT_ID,mediaIds:[MEDIA_ID]}]};
test("gallery saves ordered reusable IDs using guarded role and caller operation",async()=>{const {repo,calls}=fixture();const result=await repo.saveVariantGallery(input);assert.equal(result.gallery.version,2);assert.equal(result.replayed,false);const rpc=calls.find(c=>c.text.includes("media_save_variant_gallery"))!;assert.equal(rpc.values[0],STORE_ID);assert.equal(rpc.values[8],OPERATION_ID);assert.equal(rpc.values[11],1);assert.deepEqual(JSON.parse(rpc.values[12] as string),input.assignments);assert.ok(calls.some(c=>c.text==="SET LOCAL ROLE celebix_saas_app"));});
test("replay is visible and conflict preserves caller version",async()=>{assert.equal((await fixture("operation_replayed").repo.saveVariantGallery(input)).replayed,true);await assert.rejects(fixture("version_conflict").repo.saveVariantGallery(input),{message:"version_conflict"});});
test("invalid targets and unauthorized prices fail before SQL",async()=>{const f=fixture();await assert.rejects(f.repo.saveVariantGallery({...input,assignments:[{variantId:VARIANT_ID,mediaIds:[MEDIA_ID,MEDIA_ID]}]}),{message:"invalid_input"});await assert.rejects(f.repo.saveVariantGallery({...input,tenantContext:{...tenantContext,membership:{...tenantContext.membership,role:"analyst"}}}),{message:"membership_denied"});assert.equal(f.calls.length,0);});
test("unknown commit does not resubmit assignment, and malformed cross-product projection rejected",async()=>{const f=fixture("committed",true);await assert.rejects(f.repo.saveVariantGallery(input),{message:"unavailable"});assert.equal(f.calls.filter(c=>c.text.includes("media_save_variant_gallery")).length,1);assert.ok(!f.calls.some(c=>c.text==="ROLLBACK"));await assert.rejects(fixture("committed",false,{gallery:{productId:STORE_ID,version:2,assignments:[]}}).repo.saveVariantGallery(input),{message:"unavailable"});});
