import assert from 'node:assert/strict';
import test from 'node:test';
import type { PostgresClientLike } from '@celebix/saas-data';
import { initializeEmailMarketingProductionRuntime } from './production.ts';
import type { EmailMarketingWorkerConfig } from './config.ts';
function configuration(): EmailMarketingWorkerConfig { return { database: { url: 'postgresql://workflow:fixture@postgres:5432/email_fixture?sslmode=verify-full', name: 'email_fixture' }, workerId: 'owner-fixture', mode: 'full', keyring: { activeKeyId: 'fixture', keys: [{ keyId: 'fixture', key: new Uint8Array(32).fill(4) }] } }; }
function fixture(healthy = true) { const calls: string[] = []; let ended = 0; const client = { async query(sql: string, args?: readonly unknown[]) { calls.push(sql); if (sql.includes('server_version_num'))
        return { rows: [{ version: 160014, database_name: 'email_fixture', role: 'celebix_saas_workflow', superuser: false, member: true, lifecycle: healthy }] }; if (sql.includes('email_marketing_work'))
        return { rows: [{ result: args?.[0] === 'claim' ? [] : 0 }] }; return { rows: [] }; }, release() { calls.push('release'); } }; return { calls, get ended() { return ended; }, deps: { createPool: () => ({ connect: async () => client as unknown as PostgresClientLike, end: async () => { ended++; } }), fetch: async () => { throw Error('unexpected provider call'); }, now: () => new Date('2026-10-09T12:00:00Z'), uuid: () => '22600000-0000-4000-8000-000000000099' } }; }
test('production preflight is bounded and an empty tick never contacts a provider', async () => { const f = fixture(), config = configuration(); const runtime = await initializeEmailMarketingProductionRuntime(config, f.deps); assert.equal((await runtime.runOnce()).claimed, 0); assert.ok(f.calls.some(s => s.includes('statement_timeout'))); assert.ok(f.calls.includes('SET LOCAL ROLE celebix_saas_workflow')); await runtime.close(); assert.equal(f.ended, 1); assert.ok(config.keyring.keys.every(k => k.key.every(b => b === 0))); });
test('failed preflight closes its independent pool and clears decrypted key material', async () => { const f = fixture(false), config = configuration(); await assert.rejects(initializeEmailMarketingProductionRuntime(config, f.deps), /email_marketing_preflight_failed/); assert.equal(f.ended, 1); assert.ok(f.calls.includes('ROLLBACK')); assert.ok(config.keyring.keys.every(k => k.key.every(b => b === 0))); });
