// Isolated HTTP fixture for actual production components; never connects to a catalog/database.
import { parseCatalogCollectionConfig, type CatalogCollectionConfig } from '@celebix/saas-contracts';
export const NOW='2026-09-30T12:00:00.000Z';
export const COLLECTION_ID='73000000-0000-4000-8000-000000000001';
export const CATEGORY_ID='91000000-0000-4000-8000-000000000004';
const image={url:'https://media.saas-staging.celebix.site/stores/a828862c-4cc1-475a-89cc-5fbee31eb43f/storefront/category/a4d45e40-064f-488f-b7c4-0dcbe3287f75.jpg',width:896,height:1195,mediaType:'image/jpeg',altText:'QA koleksiyon kapağı'};
const productImage={url:'https://media.saas-staging.celebix.site/stores/a828862c-4cc1-475a-89cc-5fbee31eb43f/products/6117374e-e794-4a3f-9032-b631c55d5e9d/c8afc1b9-1321-8971-8877-274f486d4444.jpg',width:548,height:547,mediaType:'image/jpeg',altText:'QA ürün görseli'};
export const PRODUCTS=Array.from({length:125},(_,index)=>({id:`72000000-0000-4000-8000-${String(index+1).padStart(12,'0')}`,title:['Keten ceket','Ekru triko','Şehir pantolonu','Dantel bluz','Mavi jean'][index%5]+` ${index+1}`,sku:`SKU-${String(index+1).padStart(3,'0')}`,status:index===124?'archived':index>118?'draft':'active',priceCents:129900+index*1000,image:productImage}));
export const CONFIG={schemaVersion:1 as const,mode:'manual' as const,published:true,featured:true,match:'all' as const,rules:[],sort:'custom' as const};
type Row={id:string;name:string;slug:string;description?:string;status:'active'|'archived';config:CatalogCollectionConfig;cover?:typeof image;productIds:string[];version:number;createdAt:string;updatedAt:string};
let rows:Row[]=Array.from({length:6},(_,index)=>({id:`73000000-0000-4000-8000-${String(index+1).padStart(12,'0')}`,name:['Şehir koleksiyonu','Yeni sezon','Günlük seçkiler','Hafta sonu','Son parçalar','Yaz arşivi'][index],slug:['sehir-koleksiyonu','yeni-sezon','gunluk-seckiler','hafta-sonu','son-parcalar','yaz-arsivi'][index],description:['Rahat kesimler, doğal dokular.','Sezonun yeni gelenleri.','Her gün için sade parçalar.','','',''][index],status:index===5?'archived':'active',config:{...CONFIG,published:index<3,featured:index===0,mode:index===1?'automatic':'manual',rules:index===1?[{kind:'category',resourceId:CATEGORY_ID}]:[]},cover:index<4?image:undefined,productIds:index===0?PRODUCTS.map(product=>product.id):PRODUCTS.slice(index*4,index*4+16).map(product=>product.id),version:7,createdAt:NOW,updatedAt:NOW}));
function matches(row:Row){return row.config.mode==='automatic'?PRODUCTS.filter(product=>product.status!=='archived'):row.productIds.map(id=>PRODUCTS.find(product=>product.id===id)).filter(Boolean);}
export function summary(row:Row){const members=matches(row);const {productIds,description,...item}=row;return {...item,...(description?{description}:{}),productCount:members.length,publicProductCount:members.filter(product=>product?.status==='active').length};}
export function listCollections(url:URL){const search=url.searchParams.get('search')?.toLocaleLowerCase('tr-TR')||'',state=url.searchParams.get('state')||'all',page=Number(url.searchParams.get('page')||1),pageSize=Number(url.searchParams.get('pageSize')||20);const counts={all:rows.filter(row=>row.status!=='archived').length,published:rows.filter(row=>row.status==='active'&&row.config.published).length,draft:rows.filter(row=>row.status==='active'&&!row.config.published).length,archived:rows.filter(row=>row.status==='archived').length};let found=rows.filter(row=>(state==='all'?row.status!=='archived':state==='archived'?row.status==='archived':row.status==='active'&&row.config.published===(state==='published'))&&row.name.toLocaleLowerCase('tr-TR').includes(search));if(url.searchParams.get('sort')==='title')found.sort((a,b)=>a.name.localeCompare(b.name,'tr'));if(url.searchParams.get('sort')==='products')found.sort((a,b)=>matches(b).length-matches(a).length);return {items:found.slice((page-1)*pageSize,page*pageSize).map(summary),page,pageSize,totalCount:found.length,counts};}
export function collectionDetail(id:string){const row=rows.find(row=>row.id===id);return row?{...summary(row),productIds:row.productIds}:undefined;}
export function collectionMembers(input:any){const config:CatalogCollectionConfig=input.config??rows.find(row=>row.id===input.collectionId)?.config??CONFIG;const pins:string[]=input.query.productIds??rows.find(row=>row.id===input.collectionId)?.productIds??[];let ordered=input.query.mode==='catalog'?PRODUCTS.filter(product=>product.status!=='archived'||pins.includes(product.id)):config.mode==='automatic'?PRODUCTS.filter(product=>product.status!=='archived'):pins.map(id=>PRODUCTS.find(product=>product.id===id)).filter(Boolean);if(config.mode==='automatic'&&input.query.mode!=='catalog'){const positions=new Map(pins.map((id,index)=>[id,index]));ordered.sort((a,b)=>(positions.get(a.id)??100000)-(positions.get(b.id)??100000));}if(config.sort==='title')ordered.sort((a,b)=>a.title.localeCompare(b.title,'tr'));if(config.sort==='price-asc'||config.sort==='price-desc')ordered.sort((a,b)=>(a.priceCents-b.priceCents)*(config.sort==='price-asc'?1:-1));const orderedIds=ordered.map(product=>product.id);const found=input.query.search?ordered.filter(product=>`${product.title} ${product.sku}`.toLocaleLowerCase('tr-TR').includes(input.query.search.toLocaleLowerCase('tr-TR'))):ordered;const {page=1,pageSize=20}=input.query;return {items:found.slice((page-1)*pageSize,page*pageSize),page,pageSize,totalCount:found.length,orderedIds};}
export function saveCollection(input:any){const config=parseCatalogCollectionConfig(input.config);if(input.name==='Hata testi')return {code:'unavailable',http:503};if(input.resourceId){const row=rows.find(row=>row.id===input.resourceId);if(!row)return {code:'resource_not_found',http:404};if(row.version!==input.expectedVersion)return {code:'version_conflict',http:409};Object.assign(row,{name:input.name,description:input.description,config,productIds:input.productIds,version:row.version+1});return {id:row.id,version:row.version,status:row.status,updatedAt:NOW,replayed:false};}const id=crypto.randomUUID(),slug=input.name.toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'koleksiyon';rows.push({id,name:input.name,slug,status:'active',config,productIds:input.productIds,version:1,createdAt:NOW,updatedAt:NOW});return {id,version:1,status:'active',updatedAt:NOW,replayed:false};}
export function transitionCollection(id:string,action:string,version:number){const row=rows.find(row=>row.id===id);if(!row)return {code:'resource_not_found',http:404};if(row.version!==version)return {code:'version_conflict',http:409};row.status=action==='archive'?'archived':'active';row.config={...row.config,published:false};row.version++;return {id,version:row.version,status:row.status,updatedAt:NOW,replayed:false};}
