import assert from 'node:assert/strict';
import test from 'node:test';
import {createContentResearchHttpHandlers} from './handler.ts';
const id='11111111-1111-4111-8111-111111111111',cookie=`v1.panel.current.${Buffer.alloc(32,1).toString('base64url')}`;
const body={target:{kind:'page',draftId:id,recordId:null,recordVersion:null},urls:['https://source.example.test/']};
const result={operationId:id,status:'completed',sources:[{id,originalUrl:body.urls[0],finalUrl:body.urls[0],title:'Source',fetchedAt:'2026-09-29T12:00:00.000Z',contentSha256:'a'.repeat(64),byteCount:13}],usage:{sourcesAttempted:1,fetchedBytes:13,extractedBytes:13,elapsedMs:100},safeCode:null};
function request(value:unknown=body,headers:HeadersInit={},get=false){return new Request(`http://customer-panel:3400/api/content-research${get?'/'+id:''}`,{method:get?'GET':'POST',headers:{cookie:`__Host-celebix_panel=${cookie}`,origin:'https://fixture.admin.saas-staging.celebix.site','content-type':'application/json','idempotency-key':id,...Object.fromEntries(new Headers(headers))},...(get?{}:{body:JSON.stringify(value)})});}
function fixture(enabled=true){let calls=0;const handler=createContentResearchHttpHandlers({resolveRuntime:async()=>({access:{panelOrigin:'https://panel.saas-staging.celebix.site',resolveCredential:async()=>({kind:'authenticated',tenantContext:{store:{id,slug:'fixture',status:'active'},membership:{status:'active',role:'editor'}}})},enabled:()=>enabled,service:{research:async()=>{calls++;return result;},get:async()=>{calls++;return result;}}}as any),now:()=>new Date('2026-09-29T12:00:00.000Z'),requestId:()=>id});return{handler,count:()=>calls};}
test('research POST and GET expose only strict safe source metadata and no-store',async()=>{const f=fixture();for(const response of [await f.handler.post(request()),await f.handler.get(request(undefined,{},true),{params:Promise.resolve({operationId:id})})]){assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'no-store');const json=await response.json();assert.equal(json.sources[0].extractedText,undefined);assert.equal(json.sources[0].id,id);}assert.equal(f.count(),2);});
test('feature, origin, tenant header, malformed URL and extra body key reject before dispatch',async()=>{for(const[enabled,value,headers,status]of[[false,body,{},503],[true,body,{origin:'https://evil.test'},403],[true,body,{'x-store-id':id},400],[true,{...body,urls:['http://source.example.test/']},{},400],[true,{...body,storeId:id},{},400]]as const){const f=fixture(enabled);const response=await f.handler.post(request(value,headers));assert.equal(response.status,status);assert.equal(f.count(),0);}});
test('feature off and missing session block retrieval',async()=>{const f=fixture(false);assert.equal((await f.handler.get(request(undefined,{},true),{params:Promise.resolve({operationId:id})})).status,503);const g=fixture();const unauthenticated=new Request(`http://customer-panel:3400/api/content-research/${id}`);assert.equal((await g.handler.get(unauthenticated,{params:Promise.resolve({operationId:id})})).status,401);assert.equal(g.count(),0);});
