import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PublicStorefrontRepositoryError } from "@celebix/saas-data";
import { ProductGallery } from "@/components/ProductGallery";
import { StorefrontFrame } from "@/components/StorefrontFrame";
import { formatTry } from "@/lib/format.ts";
import { resolveStorefrontPage } from "@/lib/page-context.ts";
import { requireStorefrontPage } from "@/lib/page-resolution.ts";

async function product(slug: string) { const { runtime, storefront } = requireStorefrontPage(await resolveStorefrontPage()); try { return { storefront, product: await runtime.repository.getPublicProductBySlug({ storefront, now: new Date(), slug }) }; } catch (error) { if (error instanceof PublicStorefrontRepositoryError && error.code === "not_found") notFound(); throw error; } }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const selected = await product((await params).slug); return { title: `${selected.product.title} | ${selected.storefront.name}`, description: selected.product.description ?? `${selected.product.title} ürün ayrıntıları`, alternates: { canonical: new URL(`/products/${selected.product.slug}`, selected.storefront.canonicalUrl).toString() }, openGraph: { title: selected.product.title, type: "website", images: selected.product.media[0]?.url ? [selected.product.media[0].url] : [] } }; }
export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) { const selected = await product((await params).slug); const { storefront, product: item } = selected; return <StorefrontFrame storefront={storefront}><section className="product-detail store-container"><ProductGallery product={item} /><div className="product-copy"><span>ÜRÜN DETAYI</span><h1>{item.title}</h1><div className="detail-price">{item.compareAtCents ? <del>{formatTry(item.compareAtCents)}</del> : null}<strong>{formatTry(item.priceCents)}</strong></div><p>{item.description ?? "Bu ürün için ayrıntılı açıklama yakında eklenecek."}</p><div className={`stock-callout ${item.available ? "is-available" : ""}`}><b>{item.available ? "Stokta" : "Tükendi"}</b><span>{item.available ? "Siparişe hazır aktif seçenekler mevcut." : "Aktif seçenekler şu anda stokta değil."}</span></div><section className="variant-panel" aria-labelledby="variants-title"><h2 id="variants-title">Varyantlar</h2>{item.variants.map((variant) => <article key={variant.id}><div><strong>{variant.title}</strong>{variant.sku ? <small>SKU {variant.sku}</small> : null}</div><div><span>{formatTry(variant.priceCents)}</span><em>{variant.available ? (variant.stockTracking ? `${variant.stockQuantity} adet` : "Stokta") : "Tükendi"}</em></div></article>)}</section></div></section></StorefrontFrame>; }
