import type { AdminDomainView, StoreDomainDnsInstruction, StoreDomainUiStatus } from "@celebix/saas-contracts";
import { StoreDomainApiError } from "../store-domain-ui/client.ts";

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u;
const HOST=/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/u;
const UI=["dns_pending","hostname_pending","ssl_pending","origin_pending","active","action_required","disabled"] as const;
function record(value:unknown,keys:readonly string[]){if(!value||typeof value!=="object"||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)throw new StoreDomainApiError();const selected=value as Record<string,unknown>;if(Object.keys(selected).sort().join(",")!==[...keys].sort().join(","))throw new StoreDomainApiError();return selected;}
function timestamp(value:unknown):string{if(typeof value!=="string"||new Date(value).toISOString()!==value)throw new StoreDomainApiError();return value;}
function instruction(value:unknown):StoreDomainDnsInstruction{const selected=record(value,["type","name","value"]);if((selected.type!=="CNAME"&&selected.type!=="TXT")||typeof selected.name!=="string"||typeof selected.value!=="string")throw new StoreDomainApiError();return Object.freeze({type:selected.type,name:selected.name,value:selected.value});}
function parse(value:unknown):AdminDomainView{const s=record(value,["schemaVersion","id","hostname","kind","status","primary","fallback","hostnameStatus","sslStatus","dnsStatus","originStatus","uiStatus","dnsInstructions","verifiedAt","lastCheckedAt","version","createdAt","updatedAt"]);if(s.schemaVersion!==1||typeof s.id!=="string"||!UUID.test(s.id)||typeof s.hostname!=="string"||!HOST.test(s.hostname)||!["platform_subdomain","custom_alias"].includes(String(s.kind))||!["pending_verification","active","disabled"].includes(String(s.status))||typeof s.primary!=="boolean"||typeof s.fallback!=="boolean"||!["pending","active","failed","deleted"].includes(String(s.hostnameStatus))||!["pending","active","failed","deleted"].includes(String(s.sslStatus))||!["pending","ready","mismatch"].includes(String(s.dnsStatus))||!["pending","ready","failed"].includes(String(s.originStatus))||!UI.includes(s.uiStatus as never)||!Array.isArray(s.dnsInstructions)||s.dnsInstructions.length>4||!Number.isSafeInteger(s.version)||(s.version as number)<1)throw new StoreDomainApiError();const createdAt=timestamp(s.createdAt),updatedAt=timestamp(s.updatedAt),verifiedAt=s.verifiedAt===null?null:timestamp(s.verifiedAt),lastCheckedAt=s.lastCheckedAt===null?null:timestamp(s.lastCheckedAt);if(updatedAt<createdAt||(s.status==="active"&&verifiedAt===null)||(s.primary&&s.status!=="active")||(s.fallback!==(s.kind==="platform_subdomain")))throw new StoreDomainApiError();return Object.freeze({schemaVersion:1,id:s.id,hostname:s.hostname,kind:s.kind as AdminDomainView["kind"],status:s.status as AdminDomainView["status"],primary:s.primary,fallback:s.fallback,hostnameStatus:s.hostnameStatus as AdminDomainView["hostnameStatus"],sslStatus:s.sslStatus as AdminDomainView["sslStatus"],dnsStatus:s.dnsStatus as AdminDomainView["dnsStatus"],originStatus:s.originStatus as AdminDomainView["originStatus"],uiStatus:s.uiStatus as StoreDomainUiStatus,dnsInstructions:Object.freeze(s.dnsInstructions.map(instruction)),verifiedAt,lastCheckedAt,version:s.version as number,createdAt,updatedAt});}
async function json(response:Response){const value=await response.json().catch(()=>{throw new StoreDomainApiError();});if(!response.ok){const code=(value as {code?:unknown})?.code;throw new StoreDomainApiError(typeof code==="string"?code as never:"unavailable",response.status);}return value;}
export function createAdminDomainApiClient(fetcher:typeof fetch=fetch,uuid:()=>string=crypto.randomUUID.bind(crypto)){async function request(path:string,init?:RequestInit){return json(await fetcher(path,{credentials:"same-origin",cache:"no-store",...init}));}async function mutation(path:string,method:"POST"|"DELETE",body:unknown){const operation=uuid();if(!UUID.test(operation))throw new StoreDomainApiError("invalid_input",400);const result=record(await request(path,{method,headers:{"content-type":"application/json","idempotency-key":operation},body:JSON.stringify(body)}),["domain"]);return parse(result.domain);}return Object.freeze({async list(){const result=record(await request("/api/admin-domains"),["items"]);if(!Array.isArray(result.items)||result.items.length>16)throw new StoreDomainApiError();return Object.freeze(result.items.map(parse));},create(hostname:string){const selected=hostname.trim().toLowerCase();if(!selected.startsWith("admin.")||!HOST.test(selected))throw new StoreDomainApiError("invalid_input",400);return mutation("/api/admin-domains","POST",{hostname:selected});},recheck(id:string,v:number){return mutation(`/api/admin-domains/${id}/recheck`,"POST",{expectedVersion:v});},makePrimary(id:string,v:number){return mutation(`/api/admin-domains/${id}/primary`,"POST",{expectedVersion:v});},remove(id:string,v:number){return mutation(`/api/admin-domains/${id}`,"DELETE",{expectedVersion:v});}});}
export const adminDomainApi=createAdminDomainApiClient();
