"use client";
import Link from"next/link";
import {useEffect,useRef,useState,type FormEvent}from"react";
import{ArrowDownToLine,Plus,RefreshCw,Search}from"lucide-react";
import type{AccountingAccount,AccountingCollectionPreview,AccountingCustomerAccount,AccountingEvent,AccountingFilters,AccountingIntentMap,AccountingMutation,AccountingMutationResult,AccountingOverview,AccountingReceivable,InStorePosCustomer}from"@celebix/saas-contracts";
import{PanelPageHeader,PanelPageShell,PanelStatusBadge}from"@/components/panel/PanelPageShell";
import{accountingUi,AccountingUiError}from"@/lib/accounting-ui/client";
import{accountingMoney as money,accountingDate as date,ACCOUNT_TYPE_LABELS,EVENT_LABELS,accountingEventContext,accountingFilterQuery,previewCollection,toExpenseCsv}from"@/lib/accounting-ui/model";
import{parseMinorUnits}from"@/lib/in-store-sales-ui/model";
import{inStoreSalesUi}from"@/lib/in-store-sales-ui/client";
import{FinanceModal}from"./FinanceModal";
import styles from"./accounting.module.css";
type Mode="overview"|"receivables"|"accounts"|"expenses";
type Command={kind:AccountingMutation;intent:AccountingIntentMap[AccountingMutation];key:string};
const LABELS:Record<AccountingMutation,string>={collect:"Tahsilat al",openingDebt:"Açılış borcu",saveAccount:"Hesap ekle",openBalance:"Açılış bakiyesi",expense:"Gider ekle",transfer:"Hesaplar arası transfer",settleCard:"Kart tutarını bankaya aktar",reverse:"Ters kayıt",returnCredit:"İade kaydı",refund:"Para iadesi"};
const TITLES:Record<Mode,string>={overview:"Muhasebe",receivables:"Müşteri hesapları",accounts:"Kasa ve banka",expenses:"Giderler"};
const today=()=>new Date().toLocaleDateString("sv-SE",{timeZone:"Europe/Istanbul"});
const errorText=(e:unknown)=>e instanceof AccountingUiError?e.message:"İşlem tamamlanamadı. Bilgilerin korunuyor; yeniden dene.";
export function AccountingConsole({mode,canManage,scopeKey}:{mode:Mode;canManage:boolean;scopeKey:string}){
 const[filters,setFilters]=useState<AccountingFilters>({}),[draftFilters,setDraftFilters]=useState({query:"",dateFrom:"",dateTo:"",channel:"",currency:""}),[filterError,setFilterError]=useState<string|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[revision,setRevision]=useState(0);
 const[overview,setOverview]=useState<AccountingOverview|null>(null),[accounts,setAccounts]=useState<readonly AccountingAccount[]>([]),[receivables,setReceivables]=useState<readonly AccountingReceivable[]>([]),[events,setEvents]=useState<readonly AccountingEvent[]>([]);
 const[viewCustomer,setViewCustomer]=useState(false);
 const[dialog,setDialog]=useState<AccountingMutation|null>(null),[form,setForm]=useState<Record<string,string>>({}),[formError,setFormError]=useState<string|null>(null),[saving,setSaving]=useState(false),[pending,setPending]=useState<Command|null>(null),pendingRef=useRef<Command|null>(null);
 const[selectedDebt,setSelectedDebt]=useState<AccountingReceivable|null>(null),[customerAccount,setCustomerAccount]=useState<AccountingCustomerAccount|null>(null),[customerBusy,setCustomerBusy]=useState(false),[customerResults,setCustomerResults]=useState<readonly InStorePosCustomer[]>([]);
 const[serverPreview,setServerPreview]=useState<{amount:number;orderId:string|null;value:AccountingCollectionPreview}|null>(null),[previewBusy,setPreviewBusy]=useState(false),[previewError,setPreviewError]=useState<string|null>(null);
 const[reversalOrderVersion,setReversalOrderVersion]=useState<number|null>(null),customerLookup=useRef<{generation:number;abort:AbortController|null}>({generation:0,abort:null});
 useEffect(()=>()=>{customerLookup.current.generation++;customerLookup.current.abort?.abort();},[]);
 const[selectedEvent,setSelectedEvent]=useState<AccountingEvent|null>(null),storageKey=`celebix-accounting-operation:${scopeKey}`;
 useEffect(()=>{try{const raw=window.sessionStorage.getItem(storageKey);if(raw){const command=JSON.parse(raw) as Command;if(command.key&&command.kind&&command.intent){pendingRef.current=command;setPending(command);setDialog(command.kind);setForm({...Object.fromEntries(Object.entries(command.intent).map(([key,value])=>[key,value===null?"":String(value)])),amount:"amountCents"in command.intent?String(command.intent.amountCents/100):"",commission:"commissionCents"in command.intent?String(command.intent.commissionCents/100):""});setFormError("Önceki işlemin sonucu doğrulanmalı. Aynı işlemi kontrol et.");}}}catch{}},[storageKey]);
 useEffect(()=>{const abort=new AbortController();setBusy(true);setError(null);async function load(){try{if(mode==="overview"){const value=await accountingUi.overview(filters,abort.signal);if(!abort.signal.aborted){setOverview(value);setAccounts(value.accounts);setEvents(value.recentEvents);}}else if(mode==="receivables"){const values=await Promise.all([accountingUi.receivables(filters,abort.signal),accountingUi.accounts({},abort.signal)]);if(!abort.signal.aborted){setReceivables(values[0].receivables);setAccounts(values[1].accounts);}}else if(mode==="accounts"){const value=await accountingUi.accounts(filters,abort.signal);if(!abort.signal.aborted){setAccounts(value.accounts);setEvents(value.events);}}else{const values=await Promise.all([accountingUi.expenses(filters,abort.signal),accountingUi.accounts({},abort.signal)]);if(!abort.signal.aborted){setEvents(values[0].expenses);setAccounts(values[1].accounts);}}}catch(e){if(!abort.signal.aborted)setError(errorText(e));}finally{if(!abort.signal.aborted)setBusy(false);}}void load();return()=>abort.abort();},[mode,filters,revision]);
 useEffect(()=>{if(dialog!=="openingDebt"||!form.customerQuery?.trim())return;const abort=new AbortController(),timer=setTimeout(()=>{void inStoreSalesUi.searchCustomers(form.customerQuery.trim(),abort.signal).then(setCustomerResults).catch(()=>setFormError("Müşteri araması yapılamadı. Yeniden dene."));},200);return()=>{abort.abort();clearTimeout(timer);};},[dialog,form.customerQuery]);
 function update(name:string,value:string){if(pendingRef.current)return;const normalized=name==="currency"?value.toUpperCase():value;setForm(old=>({...old,[name]:normalized,...(name==="currency"&&dialog==="expense"?{accountId:accounts.find(account=>account.currency===normalized)?.id??""}:{})}));if(name==="currency"&&dialog==="openingDebt"&&form.customerId&&/^[A-Z]{3}$/.test(normalized))void loadCustomer(form.customerId,normalized);setFormError(null);}
 function invalidateCustomerLookup(){customerLookup.current.generation++;customerLookup.current.abort?.abort();customerLookup.current.abort=null;setCustomerBusy(false);}
 async function loadCustomer(customerId:string,currency:string){invalidateCustomerLookup();const generation=customerLookup.current.generation,abort=new AbortController();customerLookup.current.abort=abort;setCustomerAccount(null);setCustomerBusy(true);try{const value=await accountingUi.customerAccount(customerId,currency,abort.signal);if(abort.signal.aborted||generation!==customerLookup.current.generation)return;if(value.customerId!==customerId||value.currency!==currency)throw new AccountingUiError("invalid_response");setCustomerAccount(value);}catch(e){if(!abort.signal.aborted&&generation===customerLookup.current.generation)setFormError(errorText(e));}finally{if(!abort.signal.aborted&&generation===customerLookup.current.generation)setCustomerBusy(false);}}
 async function loadOrderVersion(orderId:string){invalidateCustomerLookup();const generation=customerLookup.current.generation,abort=new AbortController();customerLookup.current.abort=abort;setCustomerBusy(true);try{const finance=await accountingUi.orderFinance(orderId,abort.signal);if(abort.signal.aborted||generation!==customerLookup.current.generation)return;if(!finance)throw new Error();setReversalOrderVersion(finance.version);}catch{if(!abort.signal.aborted&&generation===customerLookup.current.generation)setFormError("Sipariş tahsilatı yüklenemedi. Yeniden dene.");}finally{if(!abort.signal.aborted&&generation===customerLookup.current.generation)setCustomerBusy(false);}}
 function open(kind:AccountingMutation,row?:AccountingReceivable,account?:AccountingAccount,event?:AccountingEvent){if(pendingRef.current){setDialog(pendingRef.current.kind);return;}invalidateCustomerLookup();setViewCustomer(false);setDialog(kind);setFormError(null);setNotice(null);setSelectedDebt(row??null);setSelectedEvent(event??null);setReversalOrderVersion(null);setCustomerAccount(null);setCustomerResults([]);setForm({amount:"",commission:"0",currency:row?.currency??account?.currency??accounts[0]?.currency??"TRY",accountId:kind==="collect"?"":account?.id??accounts[0]?.id??"",fromAccountId:account?.id??accounts[0]?.id??"",toAccountId:accounts.find(a=>a.id!==(account?.id??accounts[0]?.id)&&a.currency===(account?.currency??accounts[0]?.currency??"TRY")&&(kind!=="settleCard"||a.type==="bank"))?.id??"",type:"cash",paymentMethod:"cash",occurredOn:today(),note:"",category:"",documentNumber:"",name:"",reason:"",customerId:row?.customerId??"",customerQuery:"",orderId:kind==="collect"?"":""});if(row?.customerId)void loadCustomer(row.customerId,row.currency);else if(event?.customerId)void loadCustomer(event.customerId,event.currency);else if(event?.orderId)void loadOrderVersion(event.orderId);}
 function openCustomer(row:AccountingReceivable){if(!row.customerId||pendingRef.current)return;invalidateCustomerLookup();setSelectedDebt(row);setDialog(null);setViewCustomer(true);setCustomerAccount(null);setFormError(null);void loadCustomer(row.customerId,row.currency);}
 function clearCommand(){pendingRef.current=null;setPending(null);try{window.sessionStorage.removeItem(storageKey);}catch{}}
 function close(){if(saving||pendingRef.current)return;invalidateCustomerLookup();setCustomerAccount(null);setDialog(null);setViewCustomer(false);setFormError(null);}
 async function execute(command:Command,recover=false){if(saving)return;setSaving(true);setFormError(null);let lookupCompleted=!recover;try{let result:AccountingMutationResult|null=null;if(recover){result=await accountingUi.getOperation(command.key);lookupCompleted=true;}if(!result)result=await accountingUi.mutate(command.kind,command.intent as never,command.key);clearCommand();setDialog(null);setNotice(result.replayed?"Önceki kayıt doğrulandı.":"Kayıt eklendi.");setRevision(value=>value+1);}catch(e){setFormError(errorText(e));if(lookupCompleted&&(!(e instanceof AccountingUiError)||!e.unknownResult)){clearCommand();if(e instanceof AccountingUiError&&e.code==="version_conflict"){setRevision(value=>value+1);if(form.customerId)void loadCustomer(form.customerId,form.currency);}}}finally{setSaving(false);}}
 function amount(name="amount",allowZero=false){const value=parseMinorUnits(form[name]??"");if(value===null||(!allowZero&&value<1))throw new Error("Geçerli bir tutar gir; en fazla iki ondalık basamak kullan.");return value;}
 function selectedAccount(id:string){const account=accounts.find(value=>value.id===id);if(!account)throw new Error("Bir hesap seç.");return account;}
 function note(name="note"){const value=form[name]?.trim();if(!value)throw new Error(name==="reason"?"İşlemin nedenini yaz.":"Kayıt açıklamasını yaz.");return value;}
 function build(kind:AccountingMutation):AccountingIntentMap[AccountingMutation]{const cents=kind==="saveAccount"||kind==="reverse"?0:amount("amount",kind==="openBalance");const customer=customerAccount;
  switch(kind){
   case"collect":{if(!customer||customer.customerId!==form.customerId||customer.currency!==form.currency)throw new Error("Müşteri bakiyesini yeniden yükle.");previewCollection(customer.receivables,cents,form.orderId||null);if(!serverPreview||serverPreview.amount!==cents||serverPreview.orderId!==(form.orderId||null)||serverPreview.value.version!==customer.version)throw new Error("Tahsilat dağılımının doğrulanmasını bekle.");return{customerId:customer.customerId,orderId:form.orderId||null,amountCents:cents,currency:customer.currency,paymentMethod:form.paymentMethod as "cash",accountId:form.accountId||null,expectedVersion:customer.version,note:form.note.trim()||null};}
   case"openingDebt":{if(!form.customerId||!customer||customer.customerId!==form.customerId||customer.currency!==form.currency)throw new Error("Bir müşteri seç ve güncel hesabını yükle.");return{customerId:form.customerId,amountCents:cents,currency:form.currency,occurredOn:form.occurredOn,note:note(),expectedVersion:customer.version};}
   case"saveAccount":return{name:note("name"),type:form.type as "cash",currency:form.currency};
   case"openBalance":{const account=selectedAccount(form.accountId);return{accountId:account.id,amountCents:cents,occurredOn:form.occurredOn,note:note(),expectedVersion:account.version};}
   case"expense":{const account=selectedAccount(form.accountId);return{accountId:account.id,amountCents:cents,currency:account.currency,category:note("category"),note:note(),documentNumber:form.documentNumber.trim()||null,occurredOn:form.occurredOn,expectedVersion:account.version};}
   case"transfer":case"settleCard":{const from=selectedAccount(form.fromAccountId),to=selectedAccount(form.toAccountId);if(from.id===to.id||from.currency!==to.currency)throw new Error("Aynı para biriminde iki farklı hesap seç.");if(kind==="settleCard"&&(from.type!=="card"||to.type!=="bank"))throw new Error("Kart hesabından bir banka hesabına aktarım seç.");const input={fromAccountId:from.id,toAccountId:to.id,amountCents:cents,expectedVersion:from.version,toExpectedVersion:to.version,note:note()};if(kind==="transfer")return input;const commission=amount("commission",true);if(commission>cents)throw new Error("Komisyon brüt tutarı aşamaz.");return{...input,commissionCents:commission};}
   case"reverse":{if(!selectedEvent)throw new Error("Bir hareket seç.");if(selectedEvent.customerId){if(!customerAccount||customerAccount.customerId!==selectedEvent.customerId||customerAccount.currency!==selectedEvent.currency)throw new Error("Müşteri hesabının yüklenmesini bekle.");return{eventId:selectedEvent.id,reason:note("reason"),expectedVersion:customerAccount.version};}if(selectedEvent.orderId){if(reversalOrderVersion===null)throw new Error("Sipariş tahsilatının yüklenmesini bekle.");return{eventId:selectedEvent.id,reason:note("reason"),expectedVersion:reversalOrderVersion};}const account=accounts.find(a=>a.id===selectedEvent.accountId);if(!account)throw new Error("Hareketin hesap bakiyesi yüklenemedi. Hesaplar sayfasından yeniden dene.");return{eventId:selectedEvent.id,reason:note("reason"),expectedVersion:account.version};}
   case"returnCredit":{if(!selectedDebt?.orderId)throw new Error("Bir sipariş seç.");if(cents>selectedDebt.saleCents-selectedDebt.returnCents)throw new Error("İade tutarı kalan satış tutarını aşamaz.");return{orderId:selectedDebt.orderId,amountCents:cents,reason:note("reason"),expectedVersion:selectedDebt.version};}
   case"refund":{if(!selectedDebt?.orderId)throw new Error("Bir sipariş seç.");if(cents>selectedDebt.refundDueCents)throw new Error("Para iadesi ödenecek iade tutarını aşamaz.");return{orderId:selectedDebt.orderId,accountId:selectedAccount(form.accountId).id,amountCents:cents,paymentMethod:form.paymentMethod as "cash",reason:note("reason"),expectedVersion:selectedDebt.version};}
  }
 }
 function submit(event:FormEvent){event.preventDefault();if(!dialog||!canManage||saving||pendingRef.current)return;try{const command:Command={kind:dialog,intent:build(dialog),key:accountingUi.newId()};pendingRef.current=command;setPending(command);try{window.sessionStorage.setItem(storageKey,JSON.stringify(command));}catch{}void execute(command);}catch(e){setFormError(e instanceof Error?e.message:"Bilgileri kontrol et.");}}
 function applyFilters(event:FormEvent){event.preventDefault();if(draftFilters.dateFrom&&draftFilters.dateTo&&draftFilters.dateFrom>draftFilters.dateTo){setFilterError("Başlangıç tarihi bitiş tarihinden sonra olamaz.");return;}setFilterError(null);setFilters(accountingFilterQuery(draftFilters));}
 function exportExpenses(){const blob=new Blob([toExpenseCsv(events)],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`giderler-${today()}.csv`;link.click();URL.revokeObjectURL(url);}
 const amountCents=parseMinorUnits(form.amount??""),commission=parseMinorUnits(form.commission??"");let allocations:ReturnType<typeof previewCollection>=[],allocationError:string|null=null;if(dialog==="collect"&&customerAccount&&amountCents!==null&&amountCents>0){try{allocations=previewCollection(customerAccount.receivables,amountCents,form.orderId||null);}catch(e){allocationError=(e as Error).message;}}
 useEffect(()=>{setServerPreview(null);setPreviewError(null);if(dialog!=="collect"||!customerAccount||amountCents===null||amountCents<1||allocationError||pending)return;const abort=new AbortController();setPreviewBusy(true);const timer=setTimeout(()=>{void accountingUi.collectionPreview({customerId:customerAccount.customerId,orderId:form.orderId||null,currency:customerAccount.currency,amountCents},abort.signal).then(value=>{if(!abort.signal.aborted){if(value.version!==customerAccount.version){setPreviewError("Hesap değişti. Güncel borcu kontrol et.");void loadCustomer(customerAccount.customerId,customerAccount.currency);}else setServerPreview({amount:amountCents,orderId:form.orderId||null,value});}}).catch(e=>{if(!abort.signal.aborted)setPreviewError(errorText(e));}).finally(()=>{if(!abort.signal.aborted)setPreviewBusy(false);});},180);return()=>{clearTimeout(timer);abort.abort();};},[dialog,customerAccount,amountCents,allocationError,form.orderId,pending]);
 const field=(name:string,label:string,type="text",required=true)=><label className={styles.field}><span>{label}</span><input name={name} value={form[name]??""} onChange={event=>update(name,event.target.value)} type={type} required={required} disabled={saving||Boolean(pending)} inputMode={["amount","commission"].includes(name)?"decimal":undefined} maxLength={name==="note"||name==="reason"?2000:200}/></label>;
 const accountSelect=(name:string,label:string,type?:AccountingAccount["type"])=><label className={styles.field}><span>{label}</span><select name={name} value={form[name]??""} onChange={event=>update(name,event.target.value)} disabled={saving||Boolean(pending)} required={dialog!=="collect"}><option value="">{dialog==="collect"?"Yönteme göre otomatik hesap":"Hesap seç"}</option>{accounts.filter(a=>(!type||a.type===type)&&(!form.currency||a.currency===form.currency)).map(a=><option key={a.id} value={a.id}>{a.name} · {a.currency}</option>)}</select></label>;
 const methodSelect=<label className={styles.field}><span>Tahsilat yöntemi</span><select name="paymentMethod" value={form.paymentMethod??"cash"} onChange={event=>{update("paymentMethod",event.target.value);if(dialog==="collect")update("accountId","");}} disabled={saving||Boolean(pending)}><option value="cash">Nakit</option><option value="card">Kart · Harici POS</option><option value="bank_transfer">Banka havalesi</option></select></label>;
 const eventTable=(rows:readonly AccountingEvent[])=><div className={styles.tableScroll} tabIndex={0} aria-label="Hareket tablosu"><table><thead><tr><th>Tarih / işlem</th><th>Açıklama</th><th>Tutar</th><th>Durum</th><th><span className="sr-only">İşlemler</span></th></tr></thead><tbody>{rows.map(event=>{
  const context=accountingEventContext(event);
  const method=event.paymentMethod==="cash"?"Nakit":event.paymentMethod==="card"?"Kart":event.paymentMethod==="bank_transfer"?"Havale":null;
  return <tr key={event.id}><td><strong>{EVENT_LABELS[event.kind]??"Hesap hareketi"}</strong><small>{date(event.occurredAt)}</small>{method?<small>{method}</small>:null}</td><td>{event.category??event.note??"—"}{event.category&&event.note?<small>{event.note}</small>:null}{event.documentNumber?<small>Belge {event.documentNumber}</small>:null}{context.label?<small>{context.label}</small>:null}{context.orderId?<small><Link href={`/orders/${context.orderId}`}>Siparişe git</Link></small>:null}</td><td className={styles.numeric}>{money(event.amountCents,event.currency)}</td><td>{event.reversed?"Ters kaydedildi":"Kaydedildi"}</td><td>{canManage&&context.canReverse&&event.kind!=="reversal"&&event.kind!=="sale"&&(event.accountId||event.customerId||context.orderId)?<button className={styles.quiet} onClick={()=>open("reverse",undefined,undefined,{...event,orderId:context.orderId})}>Ters kayıt</button>:null}</td></tr>;
 })}</tbody></table></div>;
 if(!canManage)return<PanelPageShell><PanelPageHeader title={TITLES[mode]}/><h1 className="sr-only">{TITLES[mode]}</h1><p className={styles.empty}>Muhasebe kayıtları için mağaza yöneticisi yetkisi gerekiyor.</p></PanelPageShell>;
 return<PanelPageShell><PanelPageHeader title={TITLES[mode]}/><h1 className="sr-only">{TITLES[mode]}</h1><div className={styles.console}><nav className={styles.tabs} aria-label="Muhasebe bölümleri">{(["overview","receivables","accounts","expenses"]as const).map(value=><Link key={value} href={value==="overview"?"/accounting":`/accounting/${value}`} aria-current={mode===value?"page":undefined}>{TITLES[value]}</Link>)}<Link href="/accounting/settings">Yasal bilgiler</Link></nav>
  <div className={styles.toolbar}><form className={styles.filters} onSubmit={applyFilters}><label className={styles.search}><Search size={16} aria-hidden="true"/><span className="sr-only">Kayıt ara</span><input value={draftFilters.query} onChange={event=>setDraftFilters(old=>({...old,query:event.target.value}))} placeholder={mode==="receivables"?"Müşteri veya sipariş ara":"Kayıt ara"}/></label><label className={styles.filterField}><span>Başlangıç</span><input type="date" value={draftFilters.dateFrom} onChange={event=>setDraftFilters(old=>({...old,dateFrom:event.target.value}))}/></label><label className={styles.filterField}><span>Bitiş</span><input type="date" value={draftFilters.dateTo} onChange={event=>setDraftFilters(old=>({...old,dateTo:event.target.value}))}/></label><label className={styles.filterField}><span>Kanal</span><select value={draftFilters.channel} onChange={event=>setDraftFilters(old=>({...old,channel:event.target.value}))}><option value="">Tüm kanallar</option><option value="POS">Tüm manuel satışlar</option><option value="manual">Manuel satış</option><option value="social">Sosyal Medya</option><option value="WEB">Web</option></select></label><label className={styles.filterField}><span>Para birimi</span><input value={draftFilters.currency} onChange={event=>setDraftFilters(old=>({...old,currency:event.target.value.toUpperCase()}))} placeholder="Tümü" pattern="[A-Z]{3}|" maxLength={3}/></label><button className={styles.secondary} disabled={busy}>Uygula{Object.keys(filters).length?` · ${Object.keys(filters).length}`:""}</button></form><div className={styles.actions}>{mode==="receivables"?<button className={styles.primary} onClick={()=>open("openingDebt")}><Plus size={16} aria-hidden="true"/>Açılış borcu ekle</button>:mode==="accounts"?<button className={styles.primary} onClick={()=>open("saveAccount")}><Plus size={16} aria-hidden="true"/>Hesap ekle</button>:mode==="expenses"?<><button className={styles.secondary} onClick={exportExpenses} disabled={!events.length}><ArrowDownToLine size={16} aria-hidden="true"/>CSV</button><button className={styles.primary} onClick={()=>open("expense")}><Plus size={16} aria-hidden="true"/>Gider ekle</button></>:null}</div></div>
 {filterError?<p role="alert" className={styles.error}>{filterError}</p>:null}{error?<div role="alert" className={styles.error}><span>{error}</span><button className={styles.secondary} onClick={()=>setRevision(v=>v+1)}><RefreshCw size={16} aria-hidden="true"/>Yeniden dene</button></div>:null}{notice?<p className={styles.notice} role="status">{notice}</p>:null}
 {busy?<div role="status" className={styles.loading}><span className="sr-only">Muhasebe kayıtları yükleniyor…</span><div/><div/><div/></div>:null}
 {!busy&&mode==="overview"&&overview?<><div className={styles.overview}>{overview.currencies.map(summary=><section key={summary.currency} className={styles.currencyGroup} aria-label={`${summary.currency} özeti`}><span className={styles.currencyLabel}>{summary.currency}</span><dl className={styles.metrics}><div><dt>Satış</dt><dd>{money(summary.salesCents,summary.currency)}</dd><small>Tamamlanma tarihine göre</small></div><div><dt>Tahsilat</dt><dd>{money(summary.collectionsCents,summary.currency)}</dd><small>Tahsilat tarihine göre</small></div><div><dt>Açık alacak</dt><dd>{money(summary.dueCents,summary.currency)}</dd></div><div><dt>Ödenmiş gider</dt><dd>{money(summary.expensesCents,summary.currency)}</dd></div></dl><dl className={styles.inlineTotals}><div><dt>İade kaydı</dt><dd>{money(summary.returnCents,summary.currency)}</dd></div><div><dt>Ödenen para iadesi</dt><dd>{money(summary.refundsCents,summary.currency)}</dd></div><div><dt>Vadesi geçen alacak</dt><dd>{money(summary.overdueCents,summary.currency)}</dd></div><div><dt>Bekleyen para iadesi</dt><dd>{money(summary.refundDueCents,summary.currency)}</dd></div><div><dt>Kart komisyonu</dt><dd>{money(summary.commissionCents,summary.currency)}</dd></div><div><dt>Kayıtlı web ödemeleri</dt><dd>{money(summary.recordedWebPaymentsCents,summary.currency)}</dd></div></dl></section>)}</div>{!overview.currencies.length?<p className={styles.empty}>Bu dönemde muhasebe hareketi yok. Tarih veya kanal filtresini değiştir.</p>:null}<section className={styles.section}><h2>Son hareketler</h2>{events.length?eventTable(events):<p className={styles.muted}>Henüz hareket kaydedilmedi.</p>}</section></>:null}
 {!busy&&mode==="receivables"?<section className={styles.section}>{receivables.length?<div className={styles.tableScroll} tabIndex={0} aria-label="Müşteri hesapları"><table><thead><tr><th>Müşteri / sipariş</th><th>Tarih / vade</th><th>Satış</th><th>Tahsilat</th><th>Açık borç</th><th>İade ödenecek</th><th><span className="sr-only">İşlemler</span></th></tr></thead><tbody>{receivables.map(row=><tr key={row.id}><td><strong>{row.customerName}</strong><small>{row.customerPhone??"Telefon kaydı yok"} · {row.orderNumber??"Açılış borcu"}</small>{row.customerArchived?<small>Arşivlenmiş müşteri</small>:null}</td><td>{date(row.occurredAt)}<small>{row.dueDate?`Vade ${date(row.dueDate)}`:"Vade belirtilmedi"}</small></td><td className={styles.numeric}>{money(row.saleCents,row.currency)}</td><td className={styles.numeric}>{money(row.collectedCents,row.currency)}</td><td className={styles.numeric}><strong>{money(row.dueCents,row.currency)}</strong></td><td className={styles.numeric}>{money(row.refundDueCents,row.currency)}</td><td><div className={styles.rowActions}>{row.customerId?<><button className={styles.secondary} disabled={!row.dueCents} onClick={()=>open("collect",row)}>Tahsilat al</button><button className={styles.quiet} onClick={()=>openCustomer(row)}>Hesap hareketleri</button><button className={styles.quiet} onClick={()=>open("openingDebt",row)}>Açılış borcu</button></>:null}{row.orderId?<><button className={styles.quiet} onClick={()=>open("returnCredit",row)}>İade kaydı</button><button className={styles.quiet} onClick={()=>open("refund",row)}>Para iadesi</button></>:null}</div></td></tr>)}</tbody></table></div>:<p className={styles.empty}>Bu filtrelerde açık müşteri hesabı yok. Müşteri borcu ekleyebilir veya filtreleri değiştirebilirsin.</p>}</section>:null}
 {!busy&&mode==="accounts"?<><div className={styles.accountCards}>{accounts.map(account=><article key={account.id} className={styles.accountCard}><div><strong>{account.name}</strong><small>{ACCOUNT_TYPE_LABELS[account.type]} · {account.currency}</small></div><b>{money(account.balanceCents,account.currency)}</b><div className={styles.rowActions}><button className={styles.secondary} onClick={()=>open("transfer",undefined,account)}>Transfer</button>{account.type==="card"?<button className={styles.secondary} onClick={()=>open("settleCard",undefined,account)}>Bankaya aktar</button>:null}<button className={styles.quiet} onClick={()=>open("openBalance",undefined,account)}>Açılış bakiyesi</button></div></article>)}</div>{!accounts.length?<p className={styles.empty}>Henüz kasa veya banka hesabı yok. İlk hesabı ekle.</p>:null}<section className={styles.section}><h2>Hesap hareketleri</h2>{events.length?eventTable(events):<p className={styles.muted}>Henüz hesap hareketi yok.</p>}</section></>:null}
 {!busy&&mode==="expenses"?<section className={styles.section}>{events.length?eventTable(events):<p className={styles.empty}>Bu dönemde ödenmiş gider yok. İlk gideri ekle veya tarihleri değiştir.</p>}</section>:null}
 <FinanceModal title={viewCustomer?"Müşteri hesabı":dialog?LABELS[dialog]:"Muhasebe işlemi"} open={Boolean(dialog)||viewCustomer} locked={saving||Boolean(pending)} onClose={close}>{viewCustomer?<div className={styles.dialogBody}>{customerBusy?<p role="status">Müşteri hesabı yükleniyor…</p>:customerAccount?<><div className={styles.customerSummary}><strong>{customerAccount.customerName}</strong><span>{customerAccount.customerPhone}</span>{customerAccount.customerArchived?<span>Arşivlenmiş müşteri</span>:null}</div><dl className={styles.financeSummary}><div><dt>Açık borç</dt><dd>{money(customerAccount.dueCents,customerAccount.currency)}</dd></div><div><dt>İade ödenecek</dt><dd>{money(customerAccount.refundDueCents,customerAccount.currency)}</dd></div></dl><section className={styles.section}><h3>Hesap hareketleri</h3>{customerAccount.events.length?eventTable(customerAccount.events):<p className={styles.muted}>Hesap hareketi yok.</p>}</section></>:null}{formError?<p className={styles.error} role="alert">{formError}</p>:null}</div>:<form onSubmit={submit}><div className={styles.dialogBody}>{pending?<div className={styles.notice} role="status"><strong>İşlem bilgileri korunuyor</strong><p>{LABELS[pending.kind]} · {"amountCents"in pending.intent?money(pending.intent.amountCents,"currency"in pending.intent?pending.intent.currency:"TRY"):"Kayıt"}</p></div>:null}
 {dialog==="openingDebt"&&!selectedDebt?<><label className={styles.field}><span>Müşteri ara</span><input name="customerQuery" value={form.customerQuery??""} onChange={event=>update("customerQuery",event.target.value)} placeholder="Ad, telefon veya e-posta" disabled={saving||Boolean(pending)}/></label><div className={styles.customerResults}>{customerResults.map(customer=><button key={customer.id} type="button" className={styles.secondary} onClick={()=>{update("customerId",customer.id);setForm(old=>({...old,customerQuery:customer.name}));setCustomerResults([]);void loadCustomer(customer.id,form.currency);}}><strong>{customer.name}</strong><small>{customer.phone??customer.email}{customer.archived?" · Arşivlenmiş":""}</small></button>)}</div></>:null}
 {dialog==="collect"||dialog==="openingDebt"?<div className={styles.customerSummary}>{customerBusy?<p role="status">Müşteri hesabı yükleniyor…</p>:customerAccount?<><strong>{customerAccount.customerName}</strong><span>{customerAccount.customerPhone??""}</span><span>Açık borç {money(customerAccount.dueCents,customerAccount.currency)}</span></>:<p>Müşteri seç.</p>}</div>:null}
 <div className={styles.formGrid}>{dialog==="saveAccount"?<>{field("name","Hesap adı")}<label className={styles.field}><span>Hesap türü</span><select name="type" value={form.type??"cash"} onChange={event=>update("type",event.target.value)} disabled={saving||Boolean(pending)}><option value="cash">Kasa</option><option value="bank">Banka</option><option value="card">Kart hesabı</option></select></label>{field("currency","Para birimi")}</>:null}
 {dialog&&!["saveAccount","reverse"].includes(dialog)?field("amount",dialog==="settleCard"?"Brüt tutar":"Tutar"):null}
 {dialog==="collect"?<><label className={styles.field}><span>Tahsilat kapsamı</span><select name="orderId" value={form.orderId??""} onChange={event=>update("orderId",event.target.value)} disabled={saving||Boolean(pending)}><option value="">Müşteri · en eski borçtan başla</option>{customerAccount?.receivables.filter(row=>row.orderId&&row.dueCents>0).map(row=><option key={row.id} value={row.orderId!}>{row.orderNumber??row.orderId}</option>)}</select></label>{methodSelect}{accountSelect("accountId","Tahsilat hesabı",form.paymentMethod==="bank_transfer"?"bank":form.paymentMethod==="card"?"card":"cash")}</>:null}
 {dialog==="expense"?<><label className={styles.field}><span>Para birimi</span><select name="currency" value={form.currency??"TRY"} onChange={event=>update("currency",event.target.value)} disabled={saving||Boolean(pending)}>{Array.from(new Set(accounts.map(account=>account.currency))).map(currency=><option key={currency} value={currency}>{currency}</option>)}</select></label>{accountSelect("accountId","Ödeme hesabı")}{field("category","Kategori")}{field("documentNumber","Belge numarası · isteğe bağlı","text",false)}</>:null}
 {dialog==="openBalance"?accountSelect("accountId","Hesap"):null}
 {dialog==="refund"?<>{accountSelect("accountId","Para iadesi hesabı")}{methodSelect}</>:null}
 {dialog==="transfer"||dialog==="settleCard"?<>{accountSelect("fromAccountId","Çıkış hesabı",dialog==="settleCard"?"card":undefined)}{accountSelect("toAccountId","Giriş hesabı",dialog==="settleCard"?"bank":undefined)}{dialog==="settleCard"?field("commission","Komisyon"):null}</>:null}
 {dialog==="openingDebt"&&!selectedDebt?field("currency","Para birimi"):null}{dialog&&["openingDebt","openBalance","expense"].includes(dialog)?field("occurredOn","Kayıt tarihi","date"):null}
 {dialog&&["returnCredit","refund","reverse"].includes(dialog)?field("reason","İşlem nedeni"):dialog&&dialog!=="saveAccount"?field("note",dialog==="collect"?"Açıklama · isteğe bağlı":"Açıklama","text",dialog!=="collect"):null}</div>
 {dialog==="collect"?<><p className={styles.muted}>Tahsilat en eski açık borçlara dağıtılır. Sipariş seçilirse yalnız o siparişe uygulanır.</p>{previewBusy&&!pending?<p className={styles.muted} role="status">Tahsilat dağılımı doğrulanıyor…</p>:null}{previewError?<p className={styles.error} role="alert">{previewError}</p>:null}{allocationError?<p className={styles.error} role="alert">{allocationError}</p>:null}{allocations.length?<dl className={styles.allocations} aria-label="Tahsilat dağılımı">{allocations.map(allocation=><div key={allocation.receivableId}><dt>{customerAccount?.receivables.find(row=>row.id===allocation.receivableId)?.orderNumber??"Açılış borcu"}</dt><dd>{money(allocation.amountCents,customerAccount!.currency)}</dd></div>)}</dl>:null}</>:null}
 {dialog==="settleCard"?<dl className={styles.allocations}><div><dt>Brüt aktarım</dt><dd>{amountCents!==null?money(amountCents,form.currency):"—"}</dd></div><div><dt>Komisyon</dt><dd>{commission!==null?money(commission,form.currency):"—"}</dd></div><div><dt>Bankaya geçecek net</dt><dd>{amountCents!==null&&commission!==null&&commission<=amountCents?money(amountCents-commission,form.currency):"—"}</dd></div></dl>:null}
 {dialog==="openingDebt"?<p className={styles.muted}>Açılış borcu gelir veya stok hareketi oluşturmaz.</p>:dialog==="openBalance"?<p className={styles.muted}>Bu kayıt hesabın mevcut başlangıç tutarını ekler.</p>:dialog==="returnCredit"?<p className={styles.muted}>İade kaydı açık borcu azaltır. Para çıkışı ayrı kaydedilir; stok iadesi ürün ve adet doğrulamasıyla ayrı yapılır.</p>:dialog==="refund"?<p className={styles.muted}>Bu işlem müşteriye yapılan gerçek para iadesini kaydeder. Bekleyen iade: {money(selectedDebt?.refundDueCents??0,selectedDebt?.currency??"TRY")}</p>:dialog==="reverse"?<p className={styles.muted}>Hareket silinmez. Nedeniyle birlikte eşit ve ters bir hareket oluşturulur.</p>:null}
 {formError?<p className={styles.error} role="alert">{formError}</p>:null}</div><footer className={styles.dialogActions}>{pending&&!saving?<button type="button" className={styles.primary} onClick={()=>void execute(pending,true)}>Aynı işlemi kontrol et</button>:<><button type="button" className={styles.secondary} disabled={saving} onClick={close}>Vazgeç</button><button className={styles.primary} disabled={saving||customerBusy||Boolean(allocationError)||dialog==="collect"&&(!serverPreview||serverPreview.amount!==amountCents||serverPreview.orderId!==(form.orderId||null)||previewBusy)}>{saving?"Kaydediliyor…":"Kaydet"}</button></>}</footer></form>}</FinanceModal>
 </div></PanelPageShell>;
}
