"use client";
import{useEffect,useRef,useState,type FormEvent}from"react";
import type{AccountingCollectionPreview,AccountingCollectionIntent,AccountingCustomerAccount}from"@celebix/saas-contracts";
import{accountingUi,AccountingUiError}from"@/lib/accounting-ui/client";
import{accountingMoney as money,previewCollection}from"@/lib/accounting-ui/model";
import{parseMinorUnits}from"@/lib/in-store-sales-ui/model";
import styles from"./accounting.module.css";
export function CustomerCollectionForm({customerId,orderId=null,currency="TRY",scopeKey,onCollected,onLockedChange}:{customerId:string;orderId?:string|null;currency?:string;scopeKey:string;onCollected:()=>void;onLockedChange?:(locked:boolean)=>void}){
 const[account,setAccount]=useState<AccountingCustomerAccount|null>(null),[amount,setAmount]=useState(""),[method,setMethod]=useState<AccountingCollectionIntent["paymentMethod"]>("cash"),[note,setNote]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[pending,setPending]=useState<{key:string;intent:AccountingCollectionIntent}|null>(null),[revision,setRevision]=useState(0),command=useRef<typeof pending>(null);
 const[serverPreview,setServerPreview]=useState<{amount:number;value:AccountingCollectionPreview}|null>(null),[previewBusy,setPreviewBusy]=useState(false),[previewError,setPreviewError]=useState<string|null>(null);
 const storageKey=`celebix-accounting-collection:${scopeKey}:${customerId}:${orderId??"customer"}:${currency}`;
 useEffect(()=>{try{const raw=window.sessionStorage.getItem(storageKey);if(raw){const value=JSON.parse(raw);if(value.intent?.customerId===customerId&&value.intent.orderId===orderId&&value.intent.currency===currency&&value.key){command.current=value;setPending(value);setAmount(String(value.intent.amountCents/100));setMethod(value.intent.paymentMethod);setNote(value.intent.note??"");setError("Önceki tahsilatın sonucu kontrol edilmeli. Yeniden para alma.");}}}catch{}},[storageKey,customerId,orderId,currency]);
 useEffect(()=>{onLockedChange?.(busy||Boolean(pending));},[busy,pending,onLockedChange]);
 useEffect(()=>{const abort=new AbortController();setLoading(true);void accountingUi.customerAccount(customerId,currency,abort.signal).then(value=>{if(!abort.signal.aborted)setAccount(value);}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof AccountingUiError?e.message:"Müşteri hesabı yüklenemedi. Yeniden dene.");}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[customerId,currency,revision]);
 const cents=parseMinorUnits(amount);let allocations:ReturnType<typeof previewCollection>=[],amountError:string|null=null;if(account&&cents!==null&&cents>0)try{allocations=previewCollection(account.receivables,cents,orderId);}catch(e){amountError=(e as Error).message;}
 useEffect(()=>{setServerPreview(null);setPreviewError(null);if(!account||cents===null||cents<1||amountError||pending)return;const abort=new AbortController();setPreviewBusy(true);const timer=setTimeout(()=>{void accountingUi.collectionPreview({customerId,orderId,currency,amountCents:cents},abort.signal).then(value=>{if(!abort.signal.aborted){if(value.version!==account.version){setPreviewError("Müşteri hesabı değişti. Güncel bakiye yükleniyor; tutarı kontrol et.");setRevision(v=>v+1);}else setServerPreview({amount:cents,value});}}).catch(e=>{if(!abort.signal.aborted)setPreviewError(e instanceof AccountingUiError?e.message:"Tahsilat dağılımı doğrulanamadı. Tutarı yeniden kontrol et.");}).finally(()=>{if(!abort.signal.aborted)setPreviewBusy(false);});},180);return()=>{abort.abort();clearTimeout(timer);};},[account,cents,amountError,pending,customerId,orderId,currency]);
 function clear(){command.current=null;setPending(null);try{window.sessionStorage.removeItem(storageKey);}catch{}}
 async function save(recover=false){if(busy)return;setError(null);let lookupCompleted=!recover;try{let current=command.current;if(!current){if(!account||cents===null||cents<1)throw new Error("Sıfırdan büyük bir tahsilat tutarı gir.");previewCollection(account.receivables,cents,orderId);if(!serverPreview||serverPreview.amount!==cents||serverPreview.value.version!==account.version)throw new Error("Tahsilat dağılımının doğrulanmasını bekle.");current={key:accountingUi.newId(),intent:{customerId,orderId,amountCents:cents,currency,paymentMethod:method,accountId:null,expectedVersion:account.version,note:note.trim()||null}};command.current=current;setPending(current);try{window.sessionStorage.setItem(storageKey,JSON.stringify(current));}catch{}}setBusy(true);const operation=recover?await accountingUi.getOperation(current.key):null;lookupCompleted=true;if(!operation)await accountingUi.mutate("collect",current.intent,current.key);clear();onCollected();}catch(e){setError(e instanceof AccountingUiError?e.message:e instanceof Error?e.message:"Tahsilat kaydedilemedi.");if(lookupCompleted&&(!(e instanceof AccountingUiError)||!e.unknownResult)){clear();if(e instanceof AccountingUiError&&e.code==="version_conflict")setRevision(v=>v+1);}}finally{setBusy(false);}}
 function submit(event:FormEvent){event.preventDefault();void save(Boolean(command.current));}
 if(loading)return<div className={styles.dialogBody} role="status">Müşteri hesabı yükleniyor…</div>;
 if(!account)return<div className={styles.dialogBody}><p className={styles.error} role="alert">{error??"Müşteri hesabı yüklenemedi."}</p><button className={styles.secondary} onClick={()=>setRevision(v=>v+1)}>Yeniden dene</button></div>;
 const due=account.receivables.filter(row=>!orderId||row.orderId===orderId).reduce((sum,row)=>sum+row.dueCents,0);
 return<form onSubmit={submit}><div className={styles.dialogBody}><div className={styles.customerSummary}><strong>{account.customerName}</strong><span>{account.customerPhone}</span><span>Açık borç {money(due,currency)}</span>{account.customerArchived?<span>Arşivlenmiş müşteri · borç görünür</span>:null}</div><div className={styles.formGrid}><label className={styles.field}><span>Tahsil edilen tutar</span><input name="amount" value={amount} onChange={event=>{if(!pending)setAmount(event.target.value);}} inputMode="decimal" required disabled={busy||Boolean(pending)}/></label><label className={styles.field}><span>Tahsilat yöntemi</span><select value={method} onChange={event=>setMethod(event.target.value as typeof method)} disabled={busy||Boolean(pending)}><option value="cash">Nakit</option><option value="card">Kart · Harici POS</option><option value="bank_transfer">Banka havalesi</option></select></label></div><label className={styles.field}><span>Açıklama · isteğe bağlı</span><input value={note} onChange={event=>setNote(event.target.value)} maxLength={2000} disabled={busy||Boolean(pending)}/></label><p className={styles.muted}>{orderId?"Tahsilat yalnız bu siparişe uygulanır.":"Tahsilat en eski açık borçtan başlayarak uygulanır."} Gerçekte alınan parayı kaydet.</p>{previewBusy&&!pending?<p role="status" className={styles.muted}>Tahsilat dağılımı doğrulanıyor…</p>:null}{previewError?<p role="alert" className={styles.error}>{previewError}</p>:null}{allocations.length?<dl className={styles.allocations} aria-label="Tahsilat dağılımı">{allocations.map(allocation=><div key={allocation.receivableId}><dt>{account.receivables.find(row=>row.id===allocation.receivableId)?.orderNumber??"Açılış borcu"}</dt><dd>{money(allocation.amountCents,currency)}</dd></div>)}</dl>:null}{amountError?<p role="alert" className={styles.error}>{amountError}</p>:null}{error?<p role="alert" className={styles.error}>{error}</p>:null}</div><footer className={styles.dialogActions}><button className={styles.primary} disabled={busy||!pending&&(cents===null||cents<1||Boolean(amountError)||!serverPreview||serverPreview.amount!==cents||previewBusy)}>{busy?"Kaydediliyor…":pending?"Aynı tahsilatı kontrol et":"Tahsilatı kaydet"}</button></footer></form>;
}
