"use client";

import { ChevronDown, ChevronUp, Plus, Trash2 } from "lucide-react";
import { useId, useState } from "react";
import type { DesignDestination, DesignMediaReference, StorefrontDesignDestinationOption, StorefrontDesignDocument, StorefrontDesignMediaOption } from "@celebix/saas-contracts";

import styles from "../design-settings.module.css";

export type DesignSection = "brand" | "colors" | "typography" | "hero" | "promotion" | "announcement";
const COLOR_DEFAULTS = Object.freeze({ primaryColor: "#FF5A00", accentColor: "#171717", backgroundColor: "#FFFFFF", textColor: "#171717" } as const);

function Toggle({ checked, onChange, disabled, label }: Readonly<{ checked: boolean; onChange(value: boolean): void; disabled: boolean; label: string }>) {
  return <label className={styles.toggle}><input type="checkbox" checked={checked} onChange={(event) => onChange(event.currentTarget.checked)} disabled={disabled} /><span aria-hidden="true" /><strong>{label}</strong></label>;
}

function MediaField({ label, value, media, storeName, disabled, showUpload = true, onChange, onUpload }: Readonly<{ label: string; value: DesignMediaReference; media: readonly StorefrontDesignMediaOption[]; storeName: string; disabled: boolean; showUpload?: boolean; onChange(value: DesignMediaReference): void; onUpload(file: File, altText: string): Promise<StorefrontDesignMediaOption> }>) {
  const id = useId();
  const [uploading, setUploading] = useState(false);
  const [error, setError] = useState("");
  const selected = value?.kind === "media" ? media.find(({ id: mediaId }) => mediaId === value.mediaId) : undefined;
  return <div className={styles.field}><label htmlFor={id}>{label}</label>{selected ? <img className={styles.mediaThumbnail} src={selected.url} alt={selected.altText} /> : null}<select id={id} value={value?.kind === "media" ? value.mediaId : ""} onChange={(event) => { setError(""); onChange(event.currentTarget.value ? { kind: "media", mediaId: event.currentTarget.value } : null); }} disabled={disabled || uploading}><option value="">Görsel yok</option>{media.map((item) => <option value={item.id} key={item.id}>{item.altText || "Adsız görsel"} · {item.width}×{item.height}</option>)}</select>{showUpload ? <label className={styles.uploadButton}>{uploading ? "Yükleniyor…" : "Yeni görsel yükle"}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={disabled || uploading} onChange={async (event) => { const file = event.currentTarget.files?.[0]; if (!file) return; setUploading(true); setError(""); try { const created = await onUpload(file, `${storeName} ${label}`); onChange({ kind: "media", mediaId: created.id }); } catch (caught) { setError(caught instanceof Error ? caught.message : "Görsel yüklenemedi."); } finally { setUploading(false); event.currentTarget.value = ""; } }} /></label> : null}{error ? <span className={styles.fieldError} role="alert">{error}</span> : null}</div>;
}

function DestinationField({ value, destinations, disabled, onChange }: Readonly<{ value: DesignDestination; destinations: readonly StorefrontDesignDestinationOption[]; disabled: boolean; onChange(value: DesignDestination): void }>) {
  const id = useId();
  const selected = value.kind === "none" ? "" : `${value.kind}:${value.resourceId}`;
  return <div className={styles.field}><label htmlFor={id}>Bağlantı</label><select id={id} value={selected} disabled={disabled} onChange={(event) => { const option = destinations.find((item) => `${item.kind}:${item.resourceId}` === event.currentTarget.value); onChange(option ? { kind: option.kind, resourceId: option.resourceId } : { kind: "none" }); }}><option value="">Bağlantı yok</option>{destinations.map((item) => <option key={`${item.kind}:${item.resourceId}`} value={`${item.kind}:${item.resourceId}`}>{item.label}</option>)}</select></div>;
}

function TextField({ label, value, maxLength, disabled, multiline, onChange }: Readonly<{ label: string; value: string; maxLength: number; disabled: boolean; multiline?: boolean; onChange(value: string): void }>) {
  const id = useId();
  return <div className={styles.field}><label htmlFor={id}>{label}</label>{multiline ? <textarea id={id} value={value} maxLength={maxLength} disabled={disabled} onChange={(event) => onChange(event.currentTarget.value)} /> : <input id={id} value={value} maxLength={maxLength} disabled={disabled} onChange={(event) => onChange(event.currentTarget.value)} />}</div>;
}

function toLocal(value: string | null): string { return value?.slice(0, 16) ?? ""; }
function fromLocal(value: string): string | null { if (!value) return null; const date = new Date(value); return Number.isFinite(date.valueOf()) ? date.toISOString() : null; }

export function DesignInspector({ section, design, storeName, timezone, media, destinations, canManage, onChange, onUpload }: Readonly<{ section: DesignSection; design: StorefrontDesignDocument; storeName: string; timezone: string; media: readonly StorefrontDesignMediaOption[]; destinations: readonly StorefrontDesignDestinationOption[]; canManage: boolean; onChange(design: StorefrontDesignDocument): void; onUpload(file: File, altText: string): Promise<StorefrontDesignMediaOption> }>) {
  const disabled = !canManage;
  const brand = (patch: Partial<StorefrontDesignDocument["brand"]>) => onChange({ ...design, brand: { ...design.brand, ...patch } });
  const hero = (patch: Partial<StorefrontDesignDocument["hero"]>) => onChange({ ...design, hero: { ...design.hero, ...patch } });
  const heroSlide = (index: number, patch: Partial<StorefrontDesignDocument["hero"]["slides"][number]>) => hero({ slides: design.hero.slides.map((slide, selected) => selected === index ? { ...slide, ...patch } : slide) });
  const moveHeroSlide = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= design.hero.slides.length) return; const slides = [...design.hero.slides]; [slides[index], slides[target]] = [slides[target]!, slides[index]!]; hero({ slides }); };
  const addHeroSlide = () => { if (design.hero.slides.length >= 3) return; hero({ slides: [...design.hero.slides, { headline: "Yeni banner", body: "", desktopImage: null, mobileImage: null, destination: { kind: "none" }, enabled: true }] }); };
  const removeHeroSlide = (index: number) => { if (design.hero.slides.length <= 1) return; hero({ slides: design.hero.slides.filter((_, selected) => selected !== index) }); };
  const promotion = (patch: Partial<StorefrontDesignDocument["promotion"]>) => onChange({ ...design, promotion: { ...design.promotion, ...patch } });
  const announcement = (patch: Partial<StorefrontDesignDocument["announcement"]>) => onChange({ ...design, announcement: { ...design.announcement, ...patch } });

  if (section === "brand") return <div className={styles.inspectorFields}><MediaField label="Logo" value={design.brand.logo} media={media} storeName={storeName} disabled={disabled} onChange={(logo) => brand({ logo })} onUpload={onUpload} /><MediaField label="Tarayıcı simgesi" value={design.brand.favicon} media={media} storeName={storeName} disabled={disabled} onChange={(favicon) => brand({ favicon })} onUpload={onUpload} /></div>;
  if (section === "colors") return <div className={styles.inspectorFields}>{(["primaryColor", "accentColor", "backgroundColor", "textColor"] as const).map((key, index) => <div className={styles.colorField} key={key}><label htmlFor={`design-${key}`}>{["Ana renk", "Vurgu", "Arka plan", "Metin"][index]}</label><div><input id={`design-${key}`} type="color" value={design.brand[key]} disabled={disabled} onChange={(event) => brand({ [key]: event.currentTarget.value.toUpperCase() })} /><output>{design.brand[key]}</output><button type="button" disabled={disabled || design.brand[key] === COLOR_DEFAULTS[key]} onClick={() => brand({ [key]: COLOR_DEFAULTS[key] })}>Varsayılana dön</button></div></div>)}</div>;
  if (section === "typography") return <div className={styles.inspectorFields}><div className={styles.field}><label htmlFor="design-font">Yazı tipi</label><select id="design-font" value={design.brand.fontFamily} disabled={disabled} onChange={(event) => brand({ fontFamily: event.currentTarget.value as StorefrontDesignDocument["brand"]["fontFamily"] })}><option value="inter">Inter</option><option value="manrope">Manrope</option><option value="playfair">Playfair</option><option value="montserrat">Montserrat</option></select><strong className={styles.fontSample} data-font={design.brand.fontFamily}>{storeName}</strong></div></div>;
  if (section === "hero") return <div className={styles.inspectorFields}><Toggle checked={design.hero.enabled} onChange={(enabled) => hero({ enabled })} disabled={disabled} label={design.hero.enabled ? "Bannerları göster" : "Bannerları gizle"} />{design.hero.slides.map((slide, index) => <section className={styles.bannerCard} key={index}><header><strong>Banner {index + 1}</strong><div><button type="button" aria-label="Yukarı taşı" disabled={disabled || index === 0} onClick={() => moveHeroSlide(index, -1)}><ChevronUp size={16} /></button><button type="button" aria-label="Aşağı taşı" disabled={disabled || index === design.hero.slides.length - 1} onClick={() => moveHeroSlide(index, 1)}><ChevronDown size={16} /></button><button type="button" aria-label="Bannerı sil" disabled={disabled || design.hero.slides.length === 1} onClick={() => removeHeroSlide(index)}><Trash2 size={16} /></button></div></header><Toggle checked={slide.enabled} onChange={(enabled) => heroSlide(index, { enabled })} disabled={disabled} label={slide.enabled ? "Yayında" : "Gizli"} /><TextField label="Başlık" value={slide.headline} maxLength={120} disabled={disabled} onChange={(headline) => heroSlide(index, { headline })} /><TextField label="Alt metin" value={slide.body} maxLength={500} disabled={disabled} multiline onChange={(body) => heroSlide(index, { body })} /><MediaField label="Masaüstü görseli" value={slide.desktopImage} media={media} storeName={storeName} disabled={disabled} onChange={(desktopImage) => heroSlide(index, { desktopImage })} onUpload={onUpload} /><MediaField label="Mobil görseli (isteğe bağlı)" value={slide.mobileImage} media={media} storeName={storeName} disabled={disabled} onChange={(mobileImage) => heroSlide(index, { mobileImage })} onUpload={onUpload} /><DestinationField value={slide.destination} destinations={destinations} disabled={disabled} onChange={(destination) => heroSlide(index, { destination })} /></section>)}<button type="button" className={styles.addBannerButton} disabled={disabled || design.hero.slides.length >= 3} onClick={addHeroSlide}><Plus size={17} />Banner ekle <span>{design.hero.slides.length}/3</span></button></div>;
  if (section === "promotion") return <div className={styles.inspectorFields}><Toggle checked={design.promotion.enabled} onChange={(enabled) => promotion({ enabled })} disabled={disabled} label={design.promotion.enabled ? "Göster" : "Gizle"} /><TextField label="Başlık" value={design.promotion.headline} maxLength={120} disabled={disabled} onChange={(headline) => promotion({ headline })} /><TextField label="Alt metin" value={design.promotion.body} maxLength={500} disabled={disabled} multiline onChange={(body) => promotion({ body })} /><DestinationField value={design.promotion.destination} destinations={destinations} disabled={disabled} onChange={(destination) => promotion({ destination })} /><div className={styles.schedule}><span>Saat dilimi: {timezone}</span><label>Başlangıç<input type="datetime-local" value={toLocal(design.promotion.startsAt)} disabled={disabled} onChange={(event) => promotion({ startsAt: fromLocal(event.currentTarget.value), endsAt: design.promotion.endsAt ?? fromLocal(event.currentTarget.value) })} /></label><label>Bitiş<input type="datetime-local" value={toLocal(design.promotion.endsAt)} disabled={disabled} onChange={(event) => promotion({ endsAt: fromLocal(event.currentTarget.value), startsAt: design.promotion.startsAt ?? fromLocal(event.currentTarget.value) })} /></label><button type="button" disabled={disabled} onClick={() => promotion({ startsAt: null, endsAt: null })}>Zamanı kaldır</button></div></div>;

  const selectFields = [["Simge", "icon", ["none", "sparkle", "truck", "shield"]], ["Hız", "speed", ["slow", "normal", "fast"]], ["Yön", "direction", ["left", "right"]], ["Hareket", "animation", ["continuous", "step"]]] as const;
  const labels: Record<string, string> = { none: "Yok", sparkle: "Parıltı", truck: "Kargo", shield: "Kalkan", slow: "Yavaş", normal: "Normal", fast: "Hızlı", left: "Sola", right: "Sağa", continuous: "Sürekli", step: "Adımlı" };
  return <div className={styles.inspectorFields}><Toggle checked={design.announcement.enabled} onChange={(enabled) => announcement({ enabled })} disabled={disabled} label={design.announcement.enabled ? "Göster" : "Gizle"} /><div className={styles.field}><label htmlFor="design-announcement-items">Mesajlar</label><textarea id="design-announcement-items" value={design.announcement.items.join("\n")} disabled={disabled} maxLength={1452} onChange={(event) => { const items = event.currentTarget.value.split("\n").map((item) => item.trim()).filter(Boolean).slice(0, 12); if (items.length) announcement({ items }); }} /></div>{selectFields.map(([label, key, values]) => <div className={styles.field} key={key}><label htmlFor={`design-${key}`}>{label}</label><select id={`design-${key}`} value={design.announcement[key]} disabled={disabled} onChange={(event) => announcement({ [key]: event.currentTarget.value })}>{values.map((value) => <option key={value} value={value}>{labels[value]}</option>)}</select></div>)}</div>;
}
