import assert from "node:assert/strict";
import test from "node:test";
import React,{type ReactNode} from "react";
import { normalizeStorefrontDesignDocumentV5,type StorefrontDesignDocument,type StorefrontDesignEditorWorkspace } from "@celebix/saas-contracts";
import { StorefrontDesignApiError } from "../../../lib/storefront-design-ui/client.ts";
import { compile,DESIGN,withEditor } from "./design-editor-test-utils.ts";
const NOW="2026-09-30T10:00:00.000Z";
function button(container:HTMLElement,label:string){const found=Array.from(container.querySelectorAll<HTMLButtonElement>("button")).find(item=>item.textContent?.trim()===label||item.getAttribute("aria-label")===label||item.querySelector("strong")?.textContent===label);assert.ok(found,`Missing ${label}: ${container.textContent}`);return found;}
const baseline=()=>normalizeStorefrontDesignDocumentV5({...DESIGN,promotion:{...DESIGN.promotion,headline:"Published"}});
const media={id:"40000000-0000-4000-8000-000000000001",url:"https://fixture.invalid/banner.webp",altText:"Banner image",mediaType:"image/webp" as const,width:1600,height:900,reference:{kind:"asset" as const,assetId:"40000000-0000-4000-8000-000000000001"},assetKind:"hero" as const};
function fixture(canManage=true){
 let live:StorefrontDesignEditorWorkspace={schemaVersion:1,publishedVersion:4,publishedAt:NOW,design:baseline(),store:{name:"Fixture",timezone:"UTC"},media:[media],destinations:[]};
 let failure:string|undefined;let hold:Promise<void>|undefined;let release:(()=>void)|undefined;
 const requests:{input:{expectedPublishedVersion:number;design:StorefrontDesignDocument};operationId:string}[]=[];
 const api={editor:async()=>structuredClone(live),uploadMedia:async()=>{throw new Error("Unused");},apply:async(input:typeof requests[number]["input"],options:{operationId:string})=>{requests.push({input:structuredClone(input),operationId:options.operationId});await hold;if(failure){const code=failure;failure=undefined;throw new StorefrontDesignApiError(code as never,code==="version_conflict"?409:503);}if(input.expectedPublishedVersion!==live.publishedVersion)throw new StorefrontDesignApiError("version_conflict",409);live={...live,publishedVersion:live.publishedVersion+1,design:normalizeStorefrontDesignDocumentV5(input.design)};return{publishedVersion:live.publishedVersion,publishedAt:NOW,design:live.design,published:{} as never};}};
 const {DesignWorkspace}=compile<{DesignWorkspace:(props:Record<string,unknown>)=>ReactNode}>(new URL("./DesignWorkspace.tsx",import.meta.url),{
  "@/components/panel/PanelTopbarChrome":{PanelTopbarBridge:()=>null},
  "@/lib/storefront-design-ui/client":{StorefrontDesignApiError,storefrontDesignApi:api},
  "@/lib/storefront-design-preview-ui/use-preview-resources":{useStorefrontDesignPreviewResources:()=>({})},
  "./DesignStepEditor":{DesignStepEditor:({design,onChange,canManage:allowed}:{design:StorefrontDesignDocument;onChange:(value:StorefrontDesignDocument)=>void;canManage:boolean})=>React.createElement("input",{"aria-label":"Fixture heading",value:design.promotion.headline,disabled:!allowed,onInput:(event:React.FormEvent<HTMLInputElement>)=>onChange({...design,promotion:{...design.promotion,headline:event.currentTarget.value}})})},
  "./DesignPreview":{DesignPreview:({design,onSelectSurface,onInsertSection,onSelectSection}:{design:StorefrontDesignDocument;onSelectSurface:(surface:string,trigger:HTMLElement)=>void;onInsertSection:(index:number,trigger:HTMLElement)=>void;onSelectSection:(id:string,trigger:HTMLElement)=>void})=>React.createElement(React.Fragment,null,React.createElement("output",{"data-preview":true},JSON.stringify(design)),React.createElement("button",{onClick:(event:React.MouseEvent<HTMLButtonElement>)=>onSelectSurface("brand",event.currentTarget)},"Edit brand"),React.createElement("button",{onClick:(event:React.MouseEvent<HTMLButtonElement>)=>onInsertSection(0,event.currentTarget)},"Insert start"),...design.composition.sections.map((section,index)=>React.createElement("button",{key:index,onClick:(event:React.MouseEvent<HTMLButtonElement>)=>onSelectSection("sectionId" in section?section.sectionId:"",event.currentTarget)},`Edit section ${index+1}`)))},
 });
 return {DesignWorkspace,canManage,requests,get live(){return live;},fail(code="unavailable"){failure=code;},remote(){live={...live,publishedVersion:5,design:{...live.design,promotion:{...live.design.promotion,headline:"Remote"}}};},hold(){hold=new Promise<void>(resolve=>{release=resolve;});},release(){release?.();hold=undefined;}};
}
test("global popup uses published baseline, performs no implicit save, and Cancel restores preview and focus",async()=>withEditor(async({container,window,render,click,change})=>{
 const app=fixture();await render(React.createElement(app.DesignWorkspace,{workspace:app.live,initialPreviewResources:{},canManage:true}));assert.equal(container.querySelector('[role="dialog"]'),null);
 const trigger=button(container,"Edit brand");await click(trigger);const input=container.querySelector<HTMLInputElement>('input[aria-label="Fixture heading"]')!;await change(input,"Local");assert.equal(app.requests.length,0);assert.match(container.querySelector("output")?.textContent??"",/Local/);
 await click(button(container,"Vazgeç"));assert.equal(container.querySelector('[role="dialog"]'),null);assert.match(container.querySelector("output")?.textContent??"",/Published/);assert.equal(app.requests.length,0);assert.equal(window.document.activeElement,trigger);assert.doesNotMatch(container.textContent??"",/Taslak|Yayınla|otomatik/);
}));
test("Apply commits once to live and a failed Apply preserves inputs and retries the same operation",async()=>withEditor(async({container,render,click,change})=>{
 const app=fixture();await render(React.createElement(app.DesignWorkspace,{workspace:app.live,initialPreviewResources:{},canManage:true}));await click(button(container,"Edit brand"));await change(container.querySelector<HTMLInputElement>("input")!,"Local");app.fail();await click(button(container,"Uygula"));
 assert.equal(app.requests.length,1);assert.equal(app.live.design.promotion.headline,"Published");assert.equal(container.querySelector<HTMLInputElement>("input")?.value,"Local");assert.ok(container.querySelector('[role="dialog"]'));
 await click(button(container,"Uygula"));assert.equal(app.requests.length,2);assert.equal(app.requests[0]?.operationId,app.requests[1]?.operationId);assert.deepEqual(app.requests[0]?.input,app.requests[1]?.input);assert.equal(app.live.design.promotion.headline,"Local");assert.equal(app.live.publishedVersion,5);assert.equal(container.querySelector('[role="dialog"]'),null);
}));
test("conflict compares latest while preserving inputs and requires explicit latest-version Apply",async()=>withEditor(async({container,render,click,change})=>{
 const app=fixture();await render(React.createElement(app.DesignWorkspace,{workspace:app.live,initialPreviewResources:{},canManage:true}));await click(button(container,"Edit brand"));await change(container.querySelector<HTMLInputElement>("input")!,"Local");app.remote();await click(button(container,"Uygula"));assert.equal(app.requests.length,1);assert.equal(app.live.design.promotion.headline,"Remote");assert.equal(button(container,"Uygula").disabled,true);
 await click(button(container,"Güncel sürümle karşılaştır"));assert.match(container.querySelector("table")?.textContent??"",/Remote/);assert.match(container.querySelector("table")?.textContent??"",/Local/);assert.equal(app.requests.length,1);
 await click(button(container,"Bu değişiklikleri güncel sürüme uygula"));assert.equal(app.requests.length,2);assert.equal(app.requests[1]?.input.expectedPublishedVersion,5);assert.notEqual(app.requests[1]?.operationId,app.requests[0]?.operationId);assert.equal(app.live.design.promotion.headline,"Local");
}));
test("insertion uses the same modal, preserves asset reference, and publishes only on Apply",async()=>withEditor(async({container,render,click,change})=>{
 const app=fixture();await render(React.createElement(app.DesignWorkspace,{workspace:app.live,initialPreviewResources:{},canManage:true}));await click(button(container,"Insert start"));await click(button(container,"Banner"));assert.equal(container.querySelectorAll('[role="dialog"]').length,1);assert.ok(button(container,"İçerik"));assert.ok(button(container,"Görünüm"));
 const desktop=Array.from(container.querySelectorAll("label")).find(label=>label.textContent?.startsWith("Masaüstü görseli"))?.querySelector("select");assert.ok(desktop);await change(desktop,`asset:${media.id}`);assert.equal(app.requests.length,0);
 await click(button(container,"Görünüm"));const background=Array.from(container.querySelectorAll("label")).find(label=>label.textContent?.startsWith("Arka plan"))?.querySelector("select");assert.ok(background);await change(background,"dark");await click(button(container,"Uygula"));assert.equal(app.requests.length,1);
 const banner=app.live.design.composition.sections[0];assert.equal(banner?.kind,"banner");if(banner?.kind==="banner"){assert.deepEqual(banner.slides[0]?.desktopImage,{kind:"asset",assetId:media.id});assert.equal(banner.style?.background,"dark");}
}));
test("ordering and section visibility remain local until Apply; Cancel discards ordering",async()=>withEditor(async({container,render,click})=>{
 const app=fixture();const second={kind:"brand_story" as const,sectionId:"home_story_fixture",enabled:true,heading:"Story",body:"Story body"};const workspace={...app.live,design:{...app.live.design,composition:{...app.live.design.composition,sections:[...app.live.design.composition.sections,second]}}};await render(React.createElement(app.DesignWorkspace,{workspace,initialPreviewResources:{},canManage:true}));
 await click(button(container,"Sıralama"));await click(button(container,"Marka hikâyesi 2 yukarı taşı"));assert.match(container.querySelector("output")?.textContent??"",/Story/);assert.equal(app.requests.length,0);await click(button(container,"Vazgeç"));const preview=JSON.parse(container.querySelector("output")!.textContent!) as StorefrontDesignDocument;assert.equal(preview.composition.sections[0]?.kind,"product_row");
 await click(button(container,"Edit section 1"));await click(button(container,"Gizle"));assert.equal(app.requests.length,0);await click(button(container,"Uygula"));assert.equal(app.live.design.composition.sections[0]?.enabled,false);
}));
test("permission denial preserves input; read-only callbacks cannot create an Apply",async()=>withEditor(async({container,render,click,change})=>{
 const app=fixture();await render(React.createElement(app.DesignWorkspace,{workspace:app.live,initialPreviewResources:{},canManage:true}));await click(button(container,"Edit brand"));await change(container.querySelector<HTMLInputElement>("input")!,"Preserved");app.fail("membership_denied");await click(button(container,"Uygula"));assert.equal(container.querySelector<HTMLInputElement>("input")?.value,"Preserved");assert.match(container.textContent??"",/yetkiniz yok/);
 const readonly=fixture(false);await render(React.createElement(readonly.DesignWorkspace,{workspace:readonly.live,initialPreviewResources:{},canManage:false}));await click(button(container,"Edit brand"));assert.equal(container.querySelector<HTMLInputElement>("input")?.disabled,true);assert.equal(button(container,"Uygula").disabled,true);assert.equal(readonly.requests.length,0);
}));
