"use client";

import { ChevronDown, ChevronUp, Plus, Trash2 } from "lucide-react";
import { useEffect, useId, useRef, useState } from "react";
import type { DesignDestination, StorefrontDesignDestinationOption, StorefrontDesignDocument, StorefrontDesignMediaOption } from "@celebix/saas-contracts";

import styles from "../design-settings.module.css";
import { toStoreLocalTime, fromStoreLocalTime, updateDesignAnnouncement, effectiveHeroEnabled, updateHeroVisibility } from "./design-editor-model";
import { TypographyEditor } from "./TypographyEditor";
import { DesignMediaField } from "./DesignMediaField";

export type DesignSection = "brand" | "colors" | "typography" | "hero" | "promotion" | "announcement";
const COLOR_DEFAULTS = Object.freeze({ primaryColor: "#FF5A00", accentColor: "#171717", backgroundColor: "#FFFFFF", textColor: "#171717" } as const);

function Toggle({ checked, onChange, disabled, label }: Readonly<{ checked: boolean; onChange(value: boolean): void; disabled: boolean; label: string }>) {
  return <label className={styles.toggle}><input type="checkbox" checked={checked} onChange={(event) => onChange(event.currentTarget.checked)} disabled={disabled} /><span aria-hidden="true" /><strong>{label}</strong></label>;
}


function DestinationField({ value, destinations, disabled, onChange }: Readonly<{ value: DesignDestination; destinations: readonly StorefrontDesignDestinationOption[]; disabled: boolean; onChange(value: DesignDestination): void }>) {
  const id = useId();
  const selected = value.kind === "none" ? "" : `${value.kind}:${value.resourceId}`;
  return <div className={styles.field}><label htmlFor={id}>Bağlantı</label><select id={id} value={selected} disabled={disabled} onChange={(event) => { const option = destinations.find((item) => `${item.kind}:${item.resourceId}` === event.currentTarget.value); onChange(option ? { kind: option.kind, resourceId: option.resourceId } : { kind: "none" }); }}><option value="">Bağlantı yok</option>{destinations.map((item) => <option key={`${item.kind}:${item.resourceId}`} value={`${item.kind}:${item.resourceId}`}>{item.label}</option>)}</select></div>;
}

function TextField({ label, value, maxLength, disabled, multiline, onChange }: Readonly<{ label: string; value: string; maxLength: number; disabled: boolean; multiline?: boolean; onChange(value: string): void }>) {
  const id = useId();
  return <div className={styles.field}><label htmlFor={id}>{label}</label>{multiline ? <textarea id={id} value={value} maxLength={maxLength} disabled={disabled} onChange={(event) => onChange(event.currentTarget.value)} /> : <input id={id} value={value} maxLength={maxLength} disabled={disabled} onChange={(event) => onChange(event.currentTarget.value)} />}</div>;
}

export function DesignInspector({ section, design, storeName, timezone, media, destinations, canManage, onChange, onUpload, onMediaBusyChange }: Readonly<{ section: DesignSection; design: StorefrontDesignDocument; storeName: string; timezone: string; media: readonly StorefrontDesignMediaOption[]; destinations: readonly StorefrontDesignDestinationOption[]; canManage: boolean; onChange(design: StorefrontDesignDocument): void; onUpload(file: File, altText: string): Promise<StorefrontDesignMediaOption>; onMediaBusyChange?(id: string, busy: boolean): void }>) {
  const disabled = !canManage;
  const latest = useRef(design); latest.current = design;
  const [scheduleError,setScheduleError] = useState("");
  const [announcementText,setAnnouncementText] = useState<string|null>(null);
  const [announcementError,setAnnouncementError] = useState("");
  const lastAnnouncementWrite=useRef<string|null>(null);
  const announcementIdentity=JSON.stringify(design.composition.announcement.items);
  useEffect(()=>{if(lastAnnouncementWrite.current!==announcementIdentity){setAnnouncementText(null);setAnnouncementError("");}},[announcementIdentity]);
  const currentAnnouncement = {...design.announcement,enabled:design.composition.announcement.enabled,items:design.composition.announcement.items};
  const brand = (patch: Partial<StorefrontDesignDocument["brand"]>) => onChange({ ...latest.current, brand: { ...latest.current.brand, ...patch } });
  const hero = (patch: Partial<StorefrontDesignDocument["hero"]>) => { const current=latest.current;const next={...current,hero:{...current.hero,...patch}};onChange(typeof patch.enabled === "boolean" ? updateHeroVisibility(next,patch.enabled) : next); };
  const heroSlide = (index: number, patch: Partial<StorefrontDesignDocument["hero"]["slides"][number]>) => hero({ slides: latest.current.hero.slides.map((slide, selected) => selected === index ? { ...slide, ...patch } : slide) });
  const moveHeroSlide = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= design.hero.slides.length) return; const slides = [...design.hero.slides]; [slides[index], slides[target]] = [slides[target]!, slides[index]!]; hero({ slides }); };
  const addHeroSlide = () => { if (design.hero.slides.length >= 3) return; hero({ slides: [...design.hero.slides, { headline: "Yeni banner", body: "", desktopImage: null, mobileImage: null, destination: { kind: "none" }, enabled: true }] }); };
  const removeHeroSlide = (index: number) => { if (design.hero.slides.length <= 1) return; hero({ slides: design.hero.slides.filter((_, selected) => selected !== index) }); };
  const promotion = (patch: Partial<StorefrontDesignDocument["promotion"]>) => onChange({ ...design, promotion: { ...design.promotion, ...patch } });
  const announcement = (patch: Partial<StorefrontDesignDocument["announcement"]>) => onChange(updateDesignAnnouncement(latest.current,patch));
  const schedule = (key:"startsAt"|"endsAt",value:string) => {
    const instant = fromStoreLocalTime(value,timezone);
    if(value&&!instant){setScheduleError("Bu saat mağaza saat diliminde geçerli değil. Başka bir saat seçin.");return;}
    const next = {...design.promotion,[key]:instant};
    if(instant && !next[key === "startsAt" ? "endsAt" : "startsAt"]) next[key === "startsAt" ? "endsAt" : "startsAt"] = instant;
    if(next.startsAt&&next.endsAt&&next.startsAt>next.endsAt){setScheduleError("Bitiş başlangıçtan önce olamaz. Son geçerli zaman korunuyor.");return;}
    setScheduleError("");promotion(next);
  };

  if (section === "brand") return <div className={styles.inspectorFields}><DesignMediaField label="Logo" frame="logo" onBusyChange={onMediaBusyChange} value={design.brand.logo} media={media} storeName={storeName} disabled={disabled} onChange={(logo) => brand({ logo })} onUpload={onUpload} /><DesignMediaField label="Tarayıcı simgesi" frame="square" onBusyChange={onMediaBusyChange} value={design.brand.favicon} media={media} storeName={storeName} disabled={disabled} onChange={(favicon) => brand({ favicon })} onUpload={onUpload} /></div>;
  if (section === "colors") return <div className={styles.inspectorFields}>{(["primaryColor", "accentColor", "backgroundColor", "textColor"] as const).map((key, index) => <div className={styles.colorField} key={key}><label htmlFor={`design-${key}`}>{["Ana renk", "Vurgu", "Arka plan", "Metin"][index]}</label><div><input id={`design-${key}`} type="color" value={design.brand[key]} disabled={disabled} onChange={(event) => brand({ [key]: event.currentTarget.value.toUpperCase() })} /><output>{design.brand[key]}</output><button type="button" disabled={disabled || design.brand[key] === COLOR_DEFAULTS[key]} onClick={() => brand({ [key]: COLOR_DEFAULTS[key] })}>Varsayılana dön</button></div></div>)}</div>;
  if (section === "typography") return <TypographyEditor value={design.typography} disabled={disabled} onChange={(typography) => onChange({ ...design, typography })} />;
  if (section === "hero") return <div className={styles.inspectorFields}><Toggle checked={effectiveHeroEnabled(design)} onChange={(enabled) => hero({ enabled })} disabled={disabled} label="Bannerları göster" />{design.hero.slides.map((slide, index) => <section className={styles.bannerCard} key={index}><header><strong>Banner {index + 1}</strong><div><button type="button" aria-label="Yukarı taşı" disabled={disabled || index === 0} onClick={() => moveHeroSlide(index, -1)}><ChevronUp size={16} /></button><button type="button" aria-label="Aşağı taşı" disabled={disabled || index === design.hero.slides.length - 1} onClick={() => moveHeroSlide(index, 1)}><ChevronDown size={16} /></button><button type="button" aria-label="Bannerı sil" disabled={disabled || design.hero.slides.length === 1} onClick={() => removeHeroSlide(index)}><Trash2 size={16} /></button></div></header><Toggle checked={slide.enabled} onChange={(enabled) => heroSlide(index, { enabled })} disabled={disabled} label="Slaytı göster" /><TextField label="Başlık" value={slide.headline} maxLength={120} disabled={disabled} onChange={(headline) => heroSlide(index, { headline })} /><TextField label="Alt metin" value={slide.body} maxLength={500} disabled={disabled} multiline onChange={(body) => heroSlide(index, { body })} /><DesignMediaField label="Masaüstü görseli" onBusyChange={onMediaBusyChange} value={slide.desktopImage} media={media} storeName={storeName} disabled={disabled} onChange={(desktopImage) => heroSlide(index, { desktopImage })} onUpload={onUpload} /><DesignMediaField label="Mobil görseli (isteğe bağlı)" frame="portrait" emptyLabel="Masaüstü görselini kullan" onBusyChange={onMediaBusyChange} value={slide.mobileImage} media={media} storeName={storeName} disabled={disabled} onChange={(mobileImage) => heroSlide(index, { mobileImage })} onUpload={onUpload} /><DestinationField value={slide.destination} destinations={destinations} disabled={disabled} onChange={(destination) => heroSlide(index, { destination })} /></section>)}<button type="button" className={styles.addBannerButton} disabled={disabled || design.hero.slides.length >= 3} onClick={addHeroSlide}><Plus size={17} />Banner ekle <span>{design.hero.slides.length}/3</span></button></div>;
  if (section === "promotion") return <div className={styles.inspectorFields}><Toggle checked={design.promotion.enabled} onChange={(enabled) => promotion({ enabled })} disabled={disabled} label={design.promotion.enabled ? "Göster" : "Gizle"} /><TextField label="Başlık" value={design.promotion.headline} maxLength={120} disabled={disabled} onChange={(headline) => promotion({ headline })} /><TextField label="Alt metin" value={design.promotion.body} maxLength={500} disabled={disabled} multiline onChange={(body) => promotion({ body })} /><DestinationField value={design.promotion.destination} destinations={destinations} disabled={disabled} onChange={(destination) => promotion({ destination })} /><div className={styles.schedule}><span>Saat dilimi: {timezone}</span><label>Başlangıç<input type="datetime-local" value={toStoreLocalTime(design.promotion.startsAt,timezone)} disabled={disabled} onChange={(event) => schedule("startsAt",event.currentTarget.value)} /></label><label>Bitiş<input type="datetime-local" value={toStoreLocalTime(design.promotion.endsAt,timezone)} disabled={disabled} onChange={(event) => schedule("endsAt",event.currentTarget.value)} /></label><button type="button" disabled={disabled} onClick={() => { setScheduleError("");promotion({ startsAt: null, endsAt: null }); }}>Zamanı kaldır</button>{scheduleError?<p role="alert" className={styles.fieldError}>{scheduleError}</p>:null}</div></div>;

  const selectFields = [["Simge", "icon", ["none", "sparkle", "truck", "shield"]], ["Hız", "speed", ["slow", "normal", "fast"]], ["Yön", "direction", ["left", "right"]], ["Hareket", "animation", ["continuous", "step"]]] as const;
  const labels: Record<string, string> = { none: "Yok", sparkle: "Parıltı", truck: "Kargo", shield: "Kalkan", slow: "Yavaş", normal: "Normal", fast: "Hızlı", left: "Sola", right: "Sağa", continuous: "Sürekli", step: "Adımlı" };
  return <div className={styles.inspectorFields}><Toggle checked={currentAnnouncement.enabled} onChange={(enabled) => announcement({ enabled })} disabled={disabled} label="Duyuru şeridini göster" /><div className={styles.field}><label htmlFor="design-announcement-items">Duyuru metni</label><textarea id="design-announcement-items" aria-invalid={Boolean(announcementError)} aria-describedby={announcementError?"design-announcement-error":undefined} value={announcementText ?? currentAnnouncement.items.join("\n")} disabled={disabled} maxLength={1452} onChange={(event) => { setAnnouncementText(event.currentTarget.value); const items = event.currentTarget.value.split(/\n|·/).map((item) => item.trim()).filter(Boolean);
      if(!items.length || items.length>12 || items.some(item=>item.length>120)){setAnnouncementError("1–12 mesaj yazın; her mesaj en fazla 120 karakter olmalı. Girişleriniz korunuyor.");return;}
      lastAnnouncementWrite.current=JSON.stringify(items);setAnnouncementError("");announcement({ items }); }} />{announcementError?<small id="design-announcement-error" className={styles.fieldError} role="alert">{announcementError}</small>:null}</div><div className={styles.field}><label htmlFor="design-announcement-link">Bağlantı</label><select id="design-announcement-link" disabled={disabled} value={!design.composition.announcement.destination?"":destinations.some(item=>item.path===design.composition.announcement.destination)?design.composition.announcement.destination:"custom"} onChange={event=>{const current=latest.current,content={...current.composition.announcement};if(event.currentTarget.value==="custom")content.destination="/products";else if(event.currentTarget.value)content.destination=event.currentTarget.value;else delete content.destination;onChange({...current,composition:{...current.composition,announcement:content}});}}><option value="">Bağlantı yok</option>{destinations.map(item=><option key={`${item.kind}:${item.resourceId}`} value={item.path}>{item.label}</option>)}<option value="custom">Özel bağlantı</option></select></div>{design.composition.announcement.destination&&!destinations.some(item=>item.path===design.composition.announcement.destination)?<TextField label="Özel bağlantı" value={design.composition.announcement.destination} maxLength={500} disabled={disabled} onChange={destination=>{const current=latest.current,content={...current.composition.announcement};if(destination)content.destination=destination;else delete content.destination;onChange({...current,composition:{...current.composition,announcement:content}});}}/>:null}<details className={styles.advancedDisclosure}><summary>Hareket ve simge</summary><div className={styles.formGrid}>{selectFields.map(([label, key, values]) => <div className={styles.field} key={key}><label htmlFor={`design-${key}`}>{label}</label><select id={`design-${key}`} value={design.announcement[key]} disabled={disabled} onChange={(event) => announcement({ [key]: event.currentTarget.value })}>{values.map((value) => <option key={value} value={value}>{labels[value]}</option> )}</select></div>)}</div></details></div>;
}
