"use client";
import { ArrowDownUp,Layers3,Monitor,Smartphone } from "lucide-react";
import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import { getStorefrontDesignPublishIssue,normalizeStorefrontDesignDocumentV5,normalizeStarterThemeCompositionV4,type HomepageSectionId,type StorefrontDesignDocument,type StorefrontDesignEditorWorkspace,type StorefrontDesignMediaOption,type StorefrontAsset } from "@celebix/saas-contracts";
import { PanelTopbarBridge } from "@/components/panel/PanelTopbarChrome";
import { createDirtyNavigationGuard } from "../../../lib/catalog-ui/dirty-navigation.ts";
import { StorefrontDesignApiError,storefrontDesignApi } from "@/lib/storefront-design-ui/client";
import type { StorefrontDesignPreviewResources } from "@/lib/storefront-design-preview-model";
import { useStorefrontDesignPreviewResources } from "@/lib/storefront-design-preview-ui/use-preview-resources";
import { DesignPreview } from "./DesignPreview";
import type { StorefrontPreviewIdentity } from "./VisualStorefrontCanvas";
import { DesignSettingsModal } from "./DesignSettingsDrawer";
import { DesignStepEditor } from "./DesignStepEditor";
import type { DesignWorkspaceLocation } from "./workspace-navigation-model";
import { DESIGN_CANVAS_SURFACES,designCanvasSurface,designCanvasSurfaceForLocation,type DesignCanvasSurface,type DesignCanvasTrigger } from "./design-surface-model";
import { HomepageBuilder,HomepageSectionEditor,HomepageSectionLibrary,SECTION_LABEL,nextSectionId } from "./HomepageBuilder";
import { addHomepageSection } from "./homepage-command-model";
import { applyDesignEdit,beginDesignApply,cancelDesignEdit,compareDesignDrafts,completeDesignApply,createDesignEditorState,editorAssetOptions,failDesignApply,type DesignEditorState } from "./workspace-model";
import styles from "../design-settings.module.css";
type Popup={kind:"surface";surface:DesignCanvasSurface}|{kind:"insert";index:number}|{kind:"section";sectionId:HomepageSectionId}|{kind:"order"};
export function DesignWorkspaceToolbar({selectedSurface,previewMode,onSelectSurface,onPreviewModeChange,onOrder}:Readonly<{selectedSurface?:DesignCanvasSurface;previewMode:"desktop"|"mobile";onSelectSurface:(surface:DesignCanvasSurface,trigger?:DesignCanvasTrigger)=>void;onPreviewModeChange:(mode:"desktop"|"mobile")=>void;onOrder:(trigger:DesignCanvasTrigger)=>void}>){
 return <div className={styles.topbarActions} role="toolbar" aria-label="Tasarım önizleme araçları" data-design-toolbar="true"><details className={styles.surfaceMenu}><summary aria-label="Tasarım alanlarını aç"><Layers3 size={17} aria-hidden="true"/>Alanlar</summary><div>{DESIGN_CANVAS_SURFACES.map(surface=><button type="button" key={surface.key} aria-current={surface.key===selectedSurface?"true":undefined} onClick={event=>{const menu=event.currentTarget.closest("details");onSelectSurface(surface.key,menu?.querySelector<HTMLElement>("summary")??event.currentTarget);menu?.removeAttribute("open");}}><strong>{surface.label}</strong><span>{surface.hint}</span></button>)}</div></details><button type="button" className={styles.orderButton} onClick={event=>onOrder(event.currentTarget)}><ArrowDownUp size={17}/>Sıralama</button><div className={styles.previewSwitch} role="group" aria-label="Önizleme boyutu"><button type="button" aria-pressed={previewMode==="desktop"} className={previewMode==="desktop"?styles.active:""} onClick={()=>onPreviewModeChange("desktop")}><Monitor size={17}/>Masaüstü</button><button type="button" aria-pressed={previewMode==="mobile"} className={previewMode==="mobile"?styles.active:""} onClick={()=>onPreviewModeChange("mobile")}><Smartphone size={17}/>Mobil</button></div></div>;
}
export function DesignWorkspace({workspace,storefront,initialPreviewResources,canManage,initialLocation,recoveryScope:_recoveryScope}:Readonly<{workspace:StorefrontDesignEditorWorkspace;storefront?:StorefrontPreviewIdentity;initialPreviewResources:StorefrontDesignPreviewResources;canManage:boolean;initialLocation?:DesignWorkspaceLocation;recoveryScope?:string}>){
 const [editor,setEditor]=useState(()=>createDesignEditorState(workspace)),editorRef=useRef(editor);
 const [popup,setPopup]=useState<Popup|null>(null),[previewMode,setPreviewMode]=useState<"desktop"|"mobile">("desktop"),[previewSurface,setPreviewSurface]=useState<DesignCanvasSurface>();
 const [media,setMedia]=useState(workspace.media),[destinations,setDestinations]=useState(workspace.destinations),[publishedAt,setPublishedAt]=useState(workspace.publishedAt);
 const [previewProductId,setPreviewProductId]=useState<string>(),[message,setMessage]=useState(""),[recovery,setRecovery]=useState<StorefrontDesignEditorWorkspace|null>(null),[readingLatest,setReadingLatest]=useState(false),[uploadsInProgress,setUploadsInProgress]=useState(0);
 const mediaAttempts=useRef(new WeakMap<File,{operationId:string;altText:string}>());
 const pendingMedia=useRef(new Set<string>()),[pendingMediaCount,setPendingMediaCount]=useState(0);
 const mediaBusy=useCallback((id:string,busy:boolean)=>{if(busy)pendingMedia.current.add(id);else pendingMedia.current.delete(id);if(mountedRef.current)setPendingMediaCount(pendingMedia.current.size);},[]);
 const returnFocusRef=useRef<DesignCanvasTrigger|null>(null),requestRef=useRef<AbortController|null>(null),mountedRef=useRef(true),nowRef=useRef(new Date()),canManageRef=useRef(canManage);canManageRef.current=canManage;
 const update=useCallback((transform:(state:DesignEditorState)=>DesignEditorState)=>{editorRef.current=transform(editorRef.current);if(mountedRef.current)setEditor(editorRef.current);},[]);
 const close=useCallback(()=>{if(requestRef.current)return;update(cancelDesignEdit);setPopup(null);setMessage("");setRecovery(null);},[update]);
 const open=useCallback((next:Popup,trigger?:DesignCanvasTrigger)=>{if(requestRef.current)return;returnFocusRef.current=trigger??null;update(cancelDesignEdit);setPopup(next);setPreviewSurface(next.kind==="surface"?next.surface:"homepage");setMessage("");setRecovery(null);},[update]);
 useEffect(()=>{mountedRef.current=true;const guard=createDirtyNavigationGuard({isDirty:()=>editorRef.current.status!=="applied"||pendingMedia.current.size>0,confirm:()=>{if(requestRef.current){setMessage("İşlem sürüyor. Tamamlanmasını bekleyin.");return false;}return window.confirm("Uygulanmamış tasarım değişikliklerini bırakıp ayrılmak istiyor musunuz?");}});const unload=guard.bindBeforeUnload(window),navigation=guard.bindApplicationNavigation(document,()=>window.location.href);return()=>{mountedRef.current=false;requestRef.current?.abort();unload();navigation();};},[]);
 // Deep links select a focused popup once, without using a saved draft baseline.
 const openedInitial=useRef(false);useEffect(()=>{if(initialLocation&&!openedInitial.current){openedInitial.current=true;const surface=designCanvasSurfaceForLocation(initialLocation).key;if(surface!=="brand")open(surface==="homepage"?{kind:"order"}:{kind:"surface",surface});}},[initialLocation,open]);
 const change=useCallback((design:StorefrontDesignDocument)=>{if(!canManageRef.current||requestRef.current)return;update(current=>applyDesignEdit(current,design));setMessage("");setRecovery(null);},[update]);
 const apply=useCallback(async()=>{
  if(!canManageRef.current||requestRef.current||pendingMedia.current.size>0||editorRef.current.status==="conflict")return;
  let design:ReturnType<typeof normalizeStorefrontDesignDocumentV5>;
  try{design=normalizeStorefrontDesignDocumentV5(editorRef.current.design);const issue=getStorefrontDesignPublishIssue(design);if(issue){setMessage(issue.code==="product_row_selection_missing"?"Elle seçilen ürün bölümüne ürün ekleyin.":issue.code==="category_grid_image_missing"?"Kategori kartları için görsel seçin.":"Görselleri, başlıkları ve bağlantıları kontrol edin.");return;}}
  catch{setMessage("Eksik veya geçersiz alanları kontrol edin. Girişleriniz korunuyor.");return;}
  update(current=>applyDesignEdit(current,design));const started=beginDesignApply(editorRef.current,globalThis.crypto.randomUUID());update(()=>started.state);
  const controller=new AbortController();requestRef.current=controller;
  try{const result=await storefrontDesignApi.apply({expectedPublishedVersion:started.token.expectedPublishedVersion,design:normalizeStorefrontDesignDocumentV5(started.token.design)},{operationId:started.token.operationId,signal:controller.signal});if(!mountedRef.current)return;update(current=>completeDesignApply(current,started.token,result));setPublishedAt(result.publishedAt);setPopup(null);setMessage("");setRecovery(null);}
  catch(error){if(!mountedRef.current)return;const status=error instanceof StorefrontDesignApiError&&error.code==="version_conflict"?"conflict":"error";update(current=>failDesignApply(current,status));setMessage(error instanceof StorefrontDesignApiError?error.message:"Değişiklikler uygulanamadı. Girişleriniz korunuyor; yeniden deneyin.");}
  finally{requestRef.current=null;}
 },[update]);
 const upload=useCallback(async(file:File,altText:string):Promise<StorefrontDesignMediaOption>=>{if(!canManageRef.current||requestRef.current)throw new StorefrontDesignApiError("membership_denied",403);let attempt=mediaAttempts.current.get(file);if(!attempt){attempt={operationId:globalThis.crypto.randomUUID(),altText};mediaAttempts.current.set(file,attempt);}setUploadsInProgress(current=>current+1);try{const created=await storefrontDesignApi.uploadMedia({file,...attempt});mediaAttempts.current.delete(file);if(mountedRef.current)setMedia(current=>[...current.filter(item=>!(item.reference.kind==="media"&&item.reference.mediaId===created.id)),{...created,reference:{kind:"media",mediaId:created.id}}]);return created;}finally{if(mountedRef.current)setUploadsInProgress(current=>Math.max(0,current-1));}},[]);
 const assetUploaded=useCallback((asset:StorefrontAsset)=>{if(mountedRef.current)setMedia(current=>[...current.filter(item=>!(item.reference.kind==="asset"&&item.reference.assetId===asset.id)),{id:asset.id,url:asset.publicUrl,altText:asset.altText,mediaType:asset.mediaType,width:asset.width,height:asset.height,reference:{kind:"asset",assetId:asset.id},assetKind:asset.kind}]);},[]);
 const refreshMedia=useCallback(async()=>{try{const latest=await storefrontDesignApi.editor();if(mountedRef.current){setMedia(latest.media);setDestinations(latest.destinations);}}catch{if(mountedRef.current)setMessage("Görsel listesi yenilenemedi. Seçimleriniz korunuyor.");}},[]);
 const compareLatest=useCallback(async()=>{setReadingLatest(true);try{const latest=await storefrontDesignApi.editor();if(mountedRef.current)setRecovery(latest);}catch{if(mountedRef.current)setMessage("Güncel tasarım yüklenemedi. Girişleriniz korunuyor.");}finally{if(mountedRef.current)setReadingLatest(false);}},[]);
 const differences=useMemo(()=>recovery?compareDesignDrafts(editor.design,recovery.design):[],[editor.design,recovery]);
 const selectedSurface=popup?.kind==="surface"?popup.surface:popup?"homepage":previewSurface;
 const previewResources=useStorefrontDesignPreviewResources(editor.design.composition,initialPreviewResources,undefined,previewProductId);
 const assets=useMemo(()=>editorAssetOptions(media),[media]);
 const section=popup?.kind==="section"?editor.design.composition.sections.find(item=>"sectionId" in item&&item.sectionId===popup.sectionId):undefined;
 const surface=popup?.kind==="surface"?designCanvasSurface(popup.surface):{label:popup?.kind==="insert"?"Bölüm ekle":popup?.kind==="section"?SECTION_LABEL[section?.kind as keyof typeof SECTION_LABEL]??"Bölüm":"Bölüm sıralaması",hint:popup?.kind==="insert"?"Seçtiğiniz konuma bir bölüm ekleyin.":popup?.kind==="section"?"Değişiklikleri önizleyin, sonra uygulayın.":"Ana sayfa bölümlerinin sırasını düzenleyin."};
 const busy=editor.status==="applying";
 return <section className={styles.workspace} data-panel-layout="visual-storefront-canvas"><PanelTopbarBridge title="Tasarım" hideHeading/><div className={styles.workspaceToolbar}><p className={styles.workspaceStatus} role="status" data-status={!canManage?"readonly":editor.status}><span aria-hidden="true"/>{!canManage?"Salt okunur":editor.status==="applied"?"Yayındaki tasarım":editor.status==="applying"?"Uygulanıyor":editor.status==="conflict"?"Başka bir oturumda değişti":editor.status==="error"?"Uygulanamadı":"Uygulanmamış değişiklik"}</p><DesignWorkspaceToolbar selectedSurface={selectedSurface} previewMode={previewMode} onSelectSurface={(surface,trigger)=>open(surface==="homepage"?{kind:"order"}:{kind:"surface",surface},trigger)} onPreviewModeChange={setPreviewMode} onOrder={trigger=>open({kind:"order"},trigger)}/></div>
  <main className={styles.canvasStage} aria-label="Mağaza önizlemesi"><DesignPreview design={editor.design} storeName={workspace.store.name} storefront={storefront} publishedVersion={editor.publishedVersion} publishedAt={publishedAt} media={media} destinations={destinations} previewResources={previewResources} previewProductId={previewProductId} onSelectPreviewProduct={setPreviewProductId} mode={previewMode} now={nowRef.current} selectedSurface={selectedSurface} selectedSectionId={popup?.kind==="section"?popup.sectionId:undefined} onSelectSurface={(surface,trigger)=>open(surface==="homepage"?{kind:"order"}:{kind:"surface",surface},trigger)} onInsertSection={(index,trigger)=>open({kind:"insert",index},trigger)} onSelectSection={(sectionId,trigger)=>open({kind:"section",sectionId},trigger)}/></main>
  <DesignSettingsModal open={popup!==null} surface={surface} returnFocusRef={returnFocusRef} onClose={close} onApply={()=>void apply()} applying={busy} applyDisabled={!canManage||uploadsInProgress>0||pendingMediaCount>0||editor.status==="applied"||editor.status==="conflict"||popup?.kind==="insert"}>
   {message?<p className={styles.fieldError} role="alert">{message}</p>:null}
   {editor.status==="conflict"?<section className={styles.conflictRecovery} aria-label="Tasarım çakışması"><p>Girişleriniz korunuyor. Güncel sürümü karşılaştırıp nasıl devam edeceğinizi seçin.</p><button type="button" disabled={readingLatest} onClick={()=>void compareLatest()}>Güncel sürümle karşılaştır</button>{recovery?<><div className={styles.conflictComparison}><table aria-label="Tasarım farkları"><thead><tr><th>Alan</th><th>Bu değişiklik</th><th>Güncel sürüm</th></tr></thead><tbody>{differences.map(row=><tr key={row.field}><th scope="row">{row.field}</th><td>{row.local}</td><td>{row.remote}</td></tr>)}</tbody></table></div><p>Bu değişiklikleri uygulamak güncel tasarımın tamamını değiştirir.</p><button type="button" disabled={!canManage} onClick={()=>{update(current=>({...createDesignEditorState(recovery),design:current.design,revision:current.revision+1,status:"dirty"}));setRecovery(null);setMessage("");void apply();}}>Bu değişiklikleri güncel sürüme uygula</button><button type="button" onClick={()=>{update(()=>createDesignEditorState(recovery));setPublishedAt(recovery.publishedAt);setMedia(recovery.media);setDestinations(recovery.destinations);setPopup(null);setRecovery(null);setMessage("");}}>Girişleri bırak, güncel sürümü kullan</button></>:null}</section>:null}
   {popup?.kind==="insert"?<HomepageSectionLibrary disabled={!canManage||busy} onSelect={kind=>{const sectionId=nextSectionId(kind);change({...editorRef.current.design,composition:addHomepageSection(normalizeStarterThemeCompositionV4(editorRef.current.design.composition),kind,sectionId,popup.index)});setPopup({kind:"section",sectionId});}}/>:popup?.kind==="section"?<HomepageSectionEditor key={popup.sectionId} design={editor.design} sectionId={popup.sectionId} media={media} assets={assets} destinations={destinations} disabled={!canManage||busy} onChange={change} onSelectSection={sectionId=>setPopup({kind:"section",sectionId})} onUpload={upload} onMediaBusyChange={mediaBusy} onAssetUploaded={assetUploaded}/>:popup?.kind==="order"?<><HomepageBuilder design={editor.design} media={media} assets={assets} destinations={destinations} canManage={canManage&&!busy} onChange={change}/><DesignStepEditor step="homepage" design={editor.design} storeName={workspace.store.name} timezone={workspace.store.timezone} media={media.filter(item=>item.reference.kind==="media")} assets={assets} onAssetsChange={()=>void refreshMedia()} destinations={destinations} canManage={canManage&&!busy} previewMode={previewMode} onChange={change} onUpload={upload} onMediaBusyChange={mediaBusy} onAssetUploaded={assetUploaded}/></>:popup?.kind==="surface"?<DesignStepEditor surface={popup.surface} step={designCanvasSurface(popup.surface).location.step} design={editor.design} storeName={workspace.store.name} timezone={workspace.store.timezone} media={media.filter(item=>item.reference.kind==="media")} assets={assets} onAssetsChange={()=>void refreshMedia()} destinations={destinations} canManage={canManage&&!busy} previewMode={previewMode} onChange={change} onUpload={upload} onMediaBusyChange={mediaBusy} onAssetUploaded={assetUploaded}/>:null}
  </DesignSettingsModal>
 </section>;
}
