import assert from "node:assert/strict";
import test from "node:test";
import React,{type ReactNode} from "react";
import {normalizeStorefrontDesignDocumentV5,type StarterThemeSectionConfigV4,type StorefrontDesignDocument} from "@celebix/saas-contracts";
import {compile,DESIGN,withEditor} from "./design-editor-test-utils.ts";
const {HomepageSectionEditor,HomepageBuilder}=compile<{HomepageSectionEditor:(props:Record<string,unknown>)=>ReactNode;HomepageBuilder:(props:Record<string,unknown>)=>ReactNode}>(new URL("./HomepageBuilder.tsx",import.meta.url));
const id=(number:number)=>`40000000-0000-4000-8000-${String(number).padStart(12,"0")}`;
const asset={id:id(1),kind:"hero",url:"https://fixture.invalid/one.webp",altText:"One",mediaType:"image/webp",width:1200,height:800};
const categories=[1,2].map(number=>({kind:"collection",resourceId:id(number+10),label:`Kategori ${number}`,path:`/collections/${number}`}));
function button(container:HTMLElement,label:string){const element=Array.from(container.querySelectorAll<HTMLButtonElement>("button")).find(item=>item.textContent?.trim()===label||item.getAttribute("aria-label")===label||item.textContent?.includes(label));assert.ok(element,`Missing ${label}`);return element;}
function field(container:HTMLElement,label:string){const element=Array.from(container.querySelectorAll("label")).find(item=>item.textContent?.startsWith(label))?.querySelector<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>("input,select,textarea");assert.ok(element,`Missing field ${label}`);return element;}
async function chooseImage(container:HTMLElement,label:string,key:string,click:(element:Element)=>Promise<void>){
 const imageField=Array.from(container.querySelectorAll<HTMLElement>('section[aria-labelledby]')).find(item=>item.querySelector('strong')?.textContent===label);assert.ok(imageField,`Missing image ${label}`);
 if(!key){await click(button(imageField,"Kaldır"));return;}
 const library=imageField.querySelector('button[aria-controls]');assert.ok(library);await click(library);
 const option=Array.from(imageField.querySelectorAll<HTMLButtonElement>('button[value]')).find(item=>item.value===key);assert.ok(option,`Missing image choice ${key}`);await click(option);
}
function design(section:StarterThemeSectionConfigV4):StorefrontDesignDocument{const baseline=normalizeStorefrontDesignDocumentV5(DESIGN);return {...baseline,composition:{...baseline.composition,sections:[section]}};}
const row:StarterThemeSectionConfigV4={kind:"product_row",sectionId:"home_products",enabled:true,heading:"Products",source:"latest",limit:8};
test("banner text edits preserve its existing hidden address and named selection saves the resource reference",async()=>withEditor(async({container,render,change})=>{
 let current=design({kind:"banner",sectionId:"home_named_links",enabled:true,layout:"single",autoplay:false,presentation:"overlay",slides:[{slideId:"slide_named_links",enabled:true,headline:"Banner",body:"",desktopImage:null,mobileImage:null,destination:{kind:"path",path:"/pages/legacy-offer"}}]});
 const draw=()=>render(React.createElement(HomepageSectionEditor,{design:current,sectionId:"home_named_links",media:[],destinations:categories,disabled:false,onChange:(next:StorefrontDesignDocument)=>{current=next;},onSelectSection:()=>{}}));
 await draw();assert.doesNotMatch(container.textContent??"",/\/pages\/legacy-offer|Mağaza içi adres/);
 await change(field(container,"Başlık"),"Yeni başlık");await draw();
 const section=current.composition.sections[0];assert.equal(section?.kind,"banner");if(section?.kind==="banner")assert.deepEqual(section.slides[0]?.destination,{kind:"path",path:"/pages/legacy-offer"});
 await change(field(container,"Bağlantı"),`collection:${categories[0]!.resourceId}`);await draw();
 const updated=current.composition.sections[0];if(updated?.kind==="banner"){assert.deepEqual(updated.slides[0]?.destination,{kind:"collection",resourceId:categories[0]!.resourceId});assert.equal(updated.slides[0]?.headline,"Yeni başlık");}
}));
test("section fields keep incomplete local text editable and preserve unrelated fields",async()=>withEditor(async({container,render,change})=>{
 let current=design(row);const draw=()=>render(React.createElement(HomepageSectionEditor,{design:current,sectionId:"home_products",media:[],destinations:[],disabled:false,onChange:(next:StorefrontDesignDocument)=>{current=next;},onSelectSection:()=>{}}));await draw();await change(field(container,"Başlık"),"");await draw();assert.equal(field(container,"Başlık").value,"");assert.match(container.textContent??"",/Başlık yazın/);
 await change(field(container,"Ürün sayısı"),"12");await draw();assert.equal(field(container,"Başlık").value,"");await change(field(container,"Başlık"),"Complete");await draw();const section=current.composition.sections[0];assert.equal(section?.kind,"product_row");if(section?.kind==="product_row"){assert.equal(section.limit,12);assert.equal(section.heading,"Complete");}
}));
test("campaign image changes keep eyebrow and body; second card can be completed first",async()=>withEditor(async({container,render,change,click})=>{
 let current=design({kind:"split_campaign",sectionId:"home_campaign",enabled:true,panels:[{heading:"First",eyebrow:"Eyebrow",body:"Body",assetId:asset.id,destination:"/products"}]});const draw=()=>render(React.createElement(HomepageSectionEditor,{design:current,sectionId:"home_campaign",media:[],assets:[asset,{...asset,id:id(2)}],destinations:categories,disabled:false,onChange:(next:StorefrontDesignDocument)=>{current=next;},onSelectSection:()=>{}}));await draw();await chooseImage(container,"Görsel",id(2),click);await draw();const first=current.composition.sections[0];assert.equal(first?.kind,"split_campaign");if(first?.kind==="split_campaign"){assert.equal(first.panels[0]?.body,"Body");assert.equal(first.panels[0]?.eyebrow,"Eyebrow");}
 const second=container.querySelectorAll("fieldset")[1]!;await change(field(second,"Başlık"),"Second");await draw();await chooseImage(container.querySelectorAll("fieldset")[1]!,"Görsel",asset.id,click);await draw();await change(field(container.querySelectorAll("fieldset")[1]!,"Bağlantı"),categories[0]!.path);await draw();const section=current.composition.sections[0];if(section?.kind==="split_campaign")assert.deepEqual(section.panels.map(panel=>panel.heading),["First","Second"]);
}));
test("manual product picker searches SKU and barcode, filters category and preserves merchant order",async()=>withEditor(async({container,render,change,click})=>{
 const products=[1,2,3].map(number=>({kind:"product",resourceId:id(number+20),label:`Ürün ${number}`,path:`/products/${number}`,searchTerms:[`SKU-${number}`,`86900${number}`],categoryIds:[categories[number===3?1:0]!.resourceId]}));let current=design({...row,source:"manual",productIds:[],limit:12});const draw=()=>render(React.createElement(HomepageSectionEditor,{design:current,sectionId:row.sectionId,media:[],destinations:[...categories,...products],disabled:false,onChange:(next:StorefrontDesignDocument)=>{current=next;},onSelectSection:()=>{}}));await draw();
 await change(container.querySelector<HTMLInputElement>('input[type="search"]')!,"SKU-1");await click(button(container,"Seç"));await draw();await change(container.querySelector<HTMLInputElement>('input[type="search"]')!,"869002");await click(button(container,"Seç"));await draw();await click(button(container,"Ürün 2 yukarı taşı"));await draw();const selected=current.composition.sections[0];if(selected?.kind==="product_row")assert.deepEqual(selected.productIds,[products[1]!.resourceId,products[0]!.resourceId]);
 await change(container.querySelector<HTMLInputElement>('input[type="search"]')!,"");await change(field(container,"Kategori filtresi"),categories[1]!.resourceId);assert.match(container.querySelector("ul.productPickerList")?.textContent??"",/Ürün 3/);assert.doesNotMatch(container.querySelector("ul.productPickerList")?.textContent??"",/Ürün 1/);
}));
test("category sections keep their selected categories, image overrides and ordering",async()=>withEditor(async({container,render,change,click})=>{
 let current=design({kind:"category_grid",sectionId:"home_categories",enabled:true,heading:"Categories",layout:"grid",categoryIds:categories.map(item=>item.resourceId)});const draw=()=>render(React.createElement(HomepageSectionEditor,{design:current,sectionId:"home_categories",media:[],assets:[{...asset,kind:"category"}],destinations:categories,disabled:false,onChange:(next:StorefrontDesignDocument)=>{current=next;},onSelectSection:()=>{}}));await draw();await chooseImage(container,"Kart görseli",asset.id,click);await draw();await click(button(container,"Kategori 2 yukarı taşı"));await draw();const section=current.composition.sections[0];if(section?.kind==="category_grid"){assert.deepEqual(section.categoryIds,[categories[1]!.resourceId,categories[0]!.resourceId]);assert.deepEqual(section.categoryImages,[{categoryId:categories[0]!.resourceId,assetId:asset.id}]);}
}));
test("banner supports all layouts, stable slides, encoded origins and desktop fallback",async()=>withEditor(async({container,render,change,click})=>{
 let current=design({kind:"banner",sectionId:"home_banner",enabled:true,layout:"single",autoplay:false,presentation:"image_only",slides:[{slideId:"slide_one",enabled:true,headline:"",body:"",desktopImage:{kind:"legacy_https",url:"https://fixture.invalid/retained.webp"},mobileImage:null,destination:{kind:"none"}}]});const choices=[{...asset,reference:{kind:"asset",assetId:asset.id},assetKind:"hero"},{...asset,reference:{kind:"media",mediaId:asset.id}},{...asset,id:id(8),reference:{kind:"asset",assetId:id(8)},assetKind:"category"}];const draw=()=>render(React.createElement(HomepageSectionEditor,{design:current,sectionId:"home_banner",media:choices,destinations:[],disabled:false,onChange:(next:StorefrontDesignDocument)=>{current=next;},onSelectSection:()=>{}}));await draw();assert.equal(container.querySelector("img")?.getAttribute("src"),"https://fixture.invalid/retained.webp");const firstLibrary=container.querySelector("button[aria-controls]");assert.ok(firstLibrary);await click(firstLibrary);assert.ok(!Array.from(container.querySelectorAll<HTMLButtonElement>("button[value]")).some(option=>option.value===`asset:${id(8)}`));await click(firstLibrary);
 for(const layout of ["slider","stacked","single"]){await change(field(container,"Yerleşim"),layout);await draw();const section=current.composition.sections[0];if(section?.kind==="banner"){assert.equal(section.layout,layout);assert.equal(section.slides[0]?.desktopImage?.kind,"legacy_https");}}
 await chooseImage(container,"Masaüstü görseli",`asset:${asset.id}`,click);await draw();await chooseImage(container,"Mobil görseli",`media:${asset.id}`,click);await draw();await chooseImage(container,"Mobil görseli","",click);await draw();await click(button(container,"Görsel ekle"));await draw();const section=current.composition.sections[0];if(section?.kind==="banner"){assert.equal(section.slides.length,2);assert.notEqual(section.slides[0]?.slideId,section.slides[1]?.slideId);assert.deepEqual(section.slides[0]?.desktopImage,{kind:"asset",assetId:asset.id});assert.equal(section.slides[0]?.mobileImage,null);}
}));
test("every section can duplicate, hide and remove in local editor state",async()=>withEditor(async({container,render,click})=>{
 let current=design({kind:"brand_story",sectionId:"home_story",enabled:true,heading:"Story",body:"Body"}),selected="home_story";const draw=()=>render(React.createElement(HomepageSectionEditor,{design:current,sectionId:selected,media:[],destinations:[],disabled:false,onChange:(next:StorefrontDesignDocument)=>{current=next;},onSelectSection:(id:string)=>{selected=id;}}));await draw();await click(button(container,"Çoğalt"));await draw();assert.equal(current.composition.sections.length,2);assert.notEqual(selected,"home_story");await click(button(container,"Gizle"));await draw();assert.equal(current.composition.sections[1]?.enabled,false);await click(button(container,"Kaldır"));await draw();assert.equal(current.composition.sections.length,1);assert.match(container.textContent??"",/Bölüm kaldırıldı/);
}));
test("order popup supports drag, arrows, remove and undo without changing boundary surfaces",async()=>withEditor(async({container,window,render,click})=>{
 const base=normalizeStorefrontDesignDocumentV5(DESIGN);let current={...base,composition:{...base.composition,sections:[row,{...row,sectionId:"home_second"}]}} as StorefrontDesignDocument;const draw=()=>render(React.createElement(HomepageBuilder,{design:current,canManage:true,onChange:(next:StorefrontDesignDocument)=>{current=next;}}));await draw();const rows=container.querySelectorAll(".homepageSectionList li");await React.act(async()=>{rows[1]!.dispatchEvent(new window.Event("dragstart",{bubbles:true}) as unknown as Event);rows[0]!.dispatchEvent(new window.Event("drop",{bubbles:true,cancelable:true}) as unknown as Event);});await draw();assert.equal((current.composition.sections[0] as {sectionId:string}).sectionId,"home_second");await click(button(container,"Ürün bölümü 1 aşağı taşı"));await draw();assert.equal((current.composition.sections[0] as {sectionId:string}).sectionId,row.sectionId);await click(button(container,"Ürün bölümü 1 kaldır"));await draw();await click(button(container,"Kaldırılan bölümü geri getir"));await draw();assert.equal(current.composition.sections.length,2);assert.deepEqual(current.composition.footer,base.composition.footer);assert.deepEqual(current.composition.navigation,base.composition.navigation);
}));

test("closing the banner editor while upload is pending ignores its late configuration completion",async()=>withEditor(async({container,window,render})=>{
 const current=design({kind:"banner",sectionId:"home_upload",enabled:true,layout:"single",autoplay:false,presentation:"overlay",slides:[{slideId:"slide_upload",enabled:true,headline:"Banner",body:"",desktopImage:null,mobileImage:null,destination:{kind:"none"}}]});let release:((value:unknown)=>void)|undefined;let updates=0;const pending=new Promise(resolve=>{release=resolve;});
 await render(React.createElement(HomepageSectionEditor,{design:current,sectionId:"home_upload",media:[],destinations:[],disabled:false,onChange:()=>updates++,onSelectSection:()=>{},onUpload:()=>pending}));
 const upload=container.querySelector<HTMLInputElement>('input[type="file"]');assert.ok(upload);Object.defineProperty(upload,"files",{configurable:true,value:[new window.File(["fixture"],"banner.webp",{type:"image/webp"})]});await React.act(async()=>upload.dispatchEvent(new window.Event("change",{bubbles:true}) as unknown as Event));await render(null);await React.act(async()=>release?.({...asset,kind:undefined}));assert.equal(updates,0);
}));
