import assert from 'node:assert/strict';
import test from 'node:test';
import type {QueryResult} from 'pg';
import type {TenantContext} from '@celebix/saas-contracts';
import type {PostgresClientLike,PostgresPoolLike} from '../postgres/pool.ts';
import {PostgresAccountingRepository,accountingRepositoryErrorCode} from './index.ts';
const STORE='10000000-0000-4000-8000-000000000001',PRINCIPAL='10000000-0000-4000-8000-000000000002',MEMBER='10000000-0000-4000-8000-000000000003',PLAN='10000000-0000-4000-8000-000000000004',OP='20000000-0000-4000-8000-000000000001',ACCOUNT='20000000-0000-4000-8000-000000000002';
const NOW=new Date('2026-10-02T10:00:00.000Z');
const authority=(role='store_owner')=>({tenantContext:{schemaVersion:1,requestId:'private',principal:{id:PRINCIPAL,issuer:'https://identity.test/oidc',subject:'private'},store:{id:STORE,slug:'test',status:'active'},membership:{id:MEMBER,role,status:'active'},entitlements:{schemaVersion:1,planId:PLAN,planCode:'growth',version:2,status:'active',features:['orders'],limits:{products:100,staff:5,storageBytes:1024},validFrom:'2026-01-01T00:00:00.000Z'},locale:'tr-TR'} as TenantContext,now:new Date(NOW)});
class Client implements PostgresClientLike{queries:{text:string;values?:unknown[]}[]=[];released:(boolean|Error|undefined)[]=[];constructor(private response:unknown,private commitLost=false){}async query(text:string,values?:unknown[]):Promise<QueryResult<Record<string,unknown>>>{this.queries.push({text,values});if(text==='COMMIT'&&this.commitLost)throw new Error('private transport');const rows=text.includes('FROM saas.accounting_')?[this.response]:[];return{rows,rowCount:rows.length}as QueryResult<Record<string,unknown>>;}release(destroy?:boolean|Error){this.released.push(destroy);}}
class Pool implements PostgresPoolLike{calls=0;constructor(readonly clients:Client[]){}async connect(){const c=this.clients[this.calls++];if(!c)throw new Error('private pool');return c;}}
const repo=(...clients:Client[])=>new PostgresAccountingRepository({pool:new Pool(clients),role:'celebix_saas_app',timeouts:{poolCheckoutMs:100,statementMs:200,lockMs:100,idleTransactionMs:200}});
const account={id:ACCOUNT,name:'Bank',type:'bank',currency:'TRY',balanceCents:0,version:1,createdAt:NOW.toISOString()};
const result={operationId:OP,replayed:false,event:null,account,customerAccount:null,finance:null};
test('account reads use trusted tenant authority in a read-only restricted transaction',async()=>{const c=new Client({outcome:'found',result_payload:{accounts:[account],events:[]}});assert.equal((await repo(c).accounts(authority())).accounts[0]?.id,ACCOUNT);const call=c.queries.find(q=>q.text.includes('FROM saas.accounting_read'))!;assert.deepEqual(call.values?.slice(0,7),[STORE,PRINCIPAL,MEMBER,PLAN,'growth',2,NOW]);assert.equal(c.queries[0]?.text,'BEGIN READ ONLY');assert.ok(c.queries.some(q=>q.text==='SET LOCAL ROLE celebix_saas_app'));});
test('nested malformed money and versions roll back before any commit',async()=>{for(const bad of [{...account,balanceCents:'5000'},{...account,version:0},{...account,id:'not-uuid'},{...account,currency:'try'}]){const c=new Client({outcome:'committed',result_payload:{...result,account:bad}});await assert.rejects(()=>repo(c).saveAccount({...authority(),operationId:OP,intent:{name:'Bank',type:'bank',currency:'TRY'}}),e=>accountingRepositoryErrorCode(e)==='unavailable');assert.equal(c.queries.at(-1)?.text,'ROLLBACK');assert.ok(!c.queries.some(q=>q.text==='COMMIT'));}});
test('unknown commit recovers exact immutable account operation on a new connection',async()=>{const c=new Client({outcome:'committed',result_payload:result},true),recovery=new Client({outcome:'found',result_payload:{...result,replayed:true}});const value=await repo(c,recovery).saveAccount({...authority(),operationId:OP,intent:{name:'Bank',type:'bank',currency:'TRY'}});assert.equal(value.account?.id,ACCOUNT);assert.equal(value.replayed,true);assert.deepEqual(c.released,[true]);assert.ok(recovery.queries.some(q=>q.text.includes('FROM saas.accounting_get_operation')));});
test('operation mismatch in a valid SQL shape cannot commit a different returned operation',async()=>{const c=new Client({outcome:'committed',result_payload:{...result,operationId:ACCOUNT}});await assert.rejects(()=>repo(c).saveAccount({...authority(),operationId:OP,intent:{name:'Bank',type:'bank',currency:'TRY'}}),e=>accountingRepositoryErrorCode(e)==='unavailable');assert.equal(c.queries.at(-1)?.text,'ROLLBACK');});
test('extra caller tenant authority and intent accessors never reach the connection',async()=>{const pool=new Pool([]),r=new PostgresAccountingRepository({pool,role:'celebix_saas_app',timeouts:{poolCheckoutMs:100,statementMs:200,lockMs:100,idleTransactionMs:200}});let reads=0;await assert.rejects(()=>r.saveAccount({...authority(),operationId:OP,intent:{name:'Bank',type:'bank',currency:'TRY'},storeId:STORE} as never),e=>accountingRepositoryErrorCode(e)==='invalid_input');await assert.rejects(()=>r.saveAccount({...authority(),operationId:OP,intent:{get name(){reads++;return'Bank';},type:'bank',currency:'TRY'}}),e=>accountingRepositoryErrorCode(e)==='invalid_input');assert.equal(reads,0);assert.equal(pool.calls,0);});
test('editor finance authority is rejected before connecting and SQL cashier denial is controlled',async()=>{const pool=new Pool([]),r=new PostgresAccountingRepository({pool,role:'celebix_saas_app',timeouts:{poolCheckoutMs:100,statementMs:200,lockMs:100,idleTransactionMs:200}});await assert.rejects(()=>r.accounts(authority('editor')),e=>accountingRepositoryErrorCode(e)==='membership_denied');assert.equal(pool.calls,0);const c=new Client({outcome:'membership_denied',result_payload:null});await assert.rejects(()=>repo(c).accounts(authority('cashier')),e=>accountingRepositoryErrorCode(e)==='membership_denied');assert.equal(c.queries.at(-1)?.text,'ROLLBACK');});
