import assert from "node:assert/strict";
import test from "node:test";
import { PostgresContentAuthoringRepository, toContentGenerationView } from "./repository.ts";
const id = "33333333-3333-4333-8333-333333333333", now = new Date("2026-09-29T12:00:00.000Z");
const tenantContext: any = { schemaVersion: 1, requestId: "request", principal: { id, issuer: "https://id.example", subject: "owner" }, store: { id, slug: "store", status: "active" }, membership: { id, role: "store_owner", status: "active" }, entitlements: { schemaVersion: 1, planId: id, planCode: "starter", version: 1, status: "active", features: ["catalog"], limits: { products: 100, staff: 5, storageBytes: 1024 }, validFrom: "2026-01-01T00:00:00.000Z" }, locale: "tr-TR" };
const generation: any = { id, draftId: id, productId: null, status: "pending", requestFingerprint: "a".repeat(64), sourceFingerprint: "b".repeat(64), provider: "deepseek", model: "model", configId: id, credentialVersion: 1, promptVersion: "v1", version: 1, dispatchState: "not_dispatched", claimToken: null, leaseExpiresAt: now.toISOString(), usage: null, draft: null, safeCode: null, createdAt: now.toISOString(), updatedAt: now.toISOString(), finishedAt: null };
function setup(commitError = false, outcome = "pending") { const calls: string[] = []; const client = { async query(text: string) { calls.push(text); if (text === "COMMIT" && commitError)
        throw Error("lost"); return text.includes("saas.content_authoring_") ? { rows: [{ outcome, result_payload: generation }], rowCount: 1, command: "", oid: 0, fields: [] } : { rows: [], rowCount: 0, command: "", oid: 0, fields: [] }; }, release() { } }; return { calls, repo: new PostgresContentAuthoringRepository({ pool: { async connect() { return client; } }, role: "celebix_saas_app", timeouts: { poolCheckoutMs: 100, statementMs: 500, lockMs: 500, idleTransactionMs: 500 }, audit() { } }) }; }
const begin = () => ({ tenantContext, now, operationId: id, requestFingerprint: "a".repeat(64), providerBinding: { configId: id, provider: "deepseek", model: "model", credentialVersion: 1, promptVersion: "v1" }, envelope: { draftId: id, productId: null, sourceFingerprint: "b".repeat(64) } });
test("begin persists exactly once and preserves unknown usage", async () => { const { repo, calls } = setup(); assert.equal((await repo.beginGeneration(begin())).generation.usage, null); assert.equal(calls.filter(t => t.includes("content_authoring_begin")).length, 1); assert.equal(calls.at(-1), "COMMIT"); });
test("claim commit uncertainty never grants dispatch or retries mutation", async () => { const { repo, calls } = setup(true, "claimed"); await assert.rejects(() => repo.claimGenerationDispatch({ tenantContext, now, operationId: id, expectedVersion: 1 }), /commit_unknown/); assert.equal(calls.filter(t => t.includes("content_authoring_claim")).length, 1); });
test("cashier denied before pool checkout", async () => { const { repo, calls } = setup(); await assert.rejects(() => repo.beginGeneration({ ...begin(), tenantContext: { ...tenantContext, membership: { id, role: "cashier", status: "active" } } }), /membership_denied/); assert.equal(calls.length, 0); });
test("public view removes credentials and lease authority", () => { const view = toContentGenerationView(generation); assert.equal(view.usage, null); for (const key of ["claimToken", "leaseExpiresAt", "configId", "credentialVersion", "requestFingerprint", "version", "dispatchState"])
    assert.equal(Object.hasOwn(view, key), false); });
test("malformed nested provider payload cannot be persisted as a validated draft", async () => { const { repo, calls } = setup(); await assert.rejects(() => repo.completeGeneration({ tenantContext, now, operationId: id, claimToken: id, expectedVersion: 2, validatedDraft: { sourceFingerprint: 'b'.repeat(64), seoTitle: 'Title', suggestions: [], claims: [], sealedCredentials: 'secret' } as never, usage: null })); assert.equal(calls.length, 0); });
