import assert from"node:assert/strict";import test from"node:test";import{parseUmamiPublicCollectorConfig}from"./config.ts";const ENV={CELEBIX_DEPLOYMENT_TIER:"staging",CELEBIX_UMAMI_PUBLIC_MODE:"approved_staging",CELEBIX_UMAMI_TRACKER_SCRIPT_URL:"https://analytics.example.test/script.js",CELEBIX_UMAMI_COLLECTOR_ORIGIN:"https://analytics.example.test"},resolve=async()=>[{address:"1.1.1.1",family:4 as const}];
test("public collector is disabled by default",async()=>assert.equal(await parseUmamiPublicCollectorConfig({},resolve),null));
test("exact staging public config is frozen",async()=>{const value=await parseUmamiPublicCollectorConfig(ENV,resolve);assert.deepEqual(value,{mode:"approved_staging",trackerScriptUrl:"https://analytics.example.test/script.js",collectorOrigin:"https://analytics.example.test"});assert.equal(Object.isFrozen(value),true)});
test("production-like profiles are denied",async()=>assert.rejects(()=>parseUmamiPublicCollectorConfig({...ENV,CELEBIX_DEPLOYMENT_TIER:"production"},resolve),/umami_public_config_invalid/));
test("credentials query fragment and port are denied",async()=>{for(const url of ["https://u:p@analytics.example.test/script.js","https://analytics.example.test/script.js?q=1","https://analytics.example.test/script.js#x","https://analytics.example.test:8443/script.js"])await assert.rejects(()=>parseUmamiPublicCollectorConfig({...ENV,CELEBIX_UMAMI_TRACKER_SCRIPT_URL:url},resolve),/umami_public_config_invalid/)});
test("HTTP and non-script paths are denied",async()=>{for(const url of ["http://analytics.example.test/script.js","https://analytics.example.test/","https://analytics.example.test/a.js"])await assert.rejects(()=>parseUmamiPublicCollectorConfig({...ENV,CELEBIX_UMAMI_TRACKER_SCRIPT_URL:url},resolve),/umami_public_config_invalid/)});
test("localhost local and internal names are denied",async()=>{for(const host of ["localhost","umami.local","umami.internal"])await assert.rejects(()=>parseUmamiPublicCollectorConfig({...ENV,CELEBIX_UMAMI_TRACKER_SCRIPT_URL:`https://${host}/script.js`,CELEBIX_UMAMI_COLLECTOR_ORIGIN:`https://${host}`},resolve),/umami_public_config_invalid/)});
test("private and documentation DNS are denied",async()=>{for(const address of ["127.0.0.1","10.0.0.1","192.168.1.1","203.0.113.1","::1","fc00::1"])await assert.rejects(()=>parseUmamiPublicCollectorConfig(ENV,async()=>[{address,family:address.includes(":")?6:4}]as never),/umami_public_config_invalid/)});
test("collector must be an exact HTTPS origin on the script host",async()=>{for(const origin of ["https://collector.example.test","https://analytics.example.test/api","https://analytics.example.test/"])await assert.rejects(()=>parseUmamiPublicCollectorConfig({...ENV,CELEBIX_UMAMI_COLLECTOR_ORIGIN:origin},resolve),/umami_public_config_invalid/)});
