import assert from"node:assert/strict";import test from"node:test";import{createSafeUmamiTracker,trackPageview}from"./tracker-client.ts";const WEBSITE="50000000-0000-4000-8000-000000000001";
function fixture(url="https://shop.example.test/products/sku?coupon=secret#reviews",referrer="https://search.example/path?q=private"){const sent:unknown[]=[];let cookies=0,storage=0;const browser={location:new URL(url),document:{title:"Product",referrer,get cookie(){cookies++;return"private"}},localStorage:{getItem(){storage++;return"private"}},sessionStorage:{getItem(){storage++;return"private"}},umami:{track(value:unknown){sent.push(value)}}};return{browser,sent,get reads(){return{cookies,storage}}}}
test("emits one sanitized pageview without browser authority",()=>{const f=fixture(),tracker=createSafeUmamiTracker({websiteId:WEBSITE,hostname:"shop.example.test",browser:f.browser as never});trackPageview(tracker);assert.deepEqual(f.sent[0],{website:WEBSITE,hostname:"shop.example.test",url:"/products/sku?utm_source=referral&utm_medium=referral",title:"Product",referrer:"https://search.example"})});
test("query hash and referrer path are stripped",()=>{const f=fixture("https://shop.example.test/a?token=x#secret","https://ref.example/private?q=x#y"),tracker=createSafeUmamiTracker({websiteId:WEBSITE,hostname:"shop.example.test",browser:f.browser as never});trackPageview(tracker);assert.deepEqual(f.sent[0],{website:WEBSITE,hostname:"shop.example.test",url:"/a?utm_source=referral&utm_medium=referral",title:"Product",referrer:"https://ref.example"})});
test("only validated UTM dimensions survive the page URL",()=>{const f=fixture("https://shop.example.test/a?utm_source=google&utm_medium=cpc&utm_campaign=summer&email=private%40example.test&token=x",""),tracker=createSafeUmamiTracker({websiteId:WEBSITE,hostname:"shop.example.test",browser:f.browser as never});trackPageview(tracker);assert.deepEqual(f.sent[0],{website:WEBSITE,hostname:"shop.example.test",url:"/a?utm_source=google&utm_medium=cpc&utm_campaign=summer",title:"Product",referrer:"direct"});assert.doesNotMatch(JSON.stringify(f.sent),/private|token/) });
test("cookies and storage are never read",()=>{const f=fixture(),tracker=createSafeUmamiTracker({websiteId:WEBSITE,hostname:"shop.example.test",browser:f.browser as never});trackPageview(tracker);assert.deepEqual(f.reads,{cookies:0,storage:0})});
test("cross-host browser location is a no-op",()=>{const f=fixture("https://evil.example/a"),tracker=createSafeUmamiTracker({websiteId:WEBSITE,hostname:"shop.example.test",browser:f.browser as never});trackPageview(tracker);assert.equal(f.sent.length,0)});
test("title is bounded and control-free",()=>{const f=fixture();f.browser.document.title=` A\n${"x".repeat(300)} `;const tracker=createSafeUmamiTracker({websiteId:WEBSITE,hostname:"shop.example.test",browser:f.browser as never});trackPageview(tracker);assert.ok(String((f.sent[0]as{title:string}).title).length<=200);assert.doesNotMatch((f.sent[0]as{title:string}).title,/\n/)});
test("missing Umami global safely does nothing",()=>{const f=fixture();delete(f.browser as{umami?:unknown}).umami;const tracker=createSafeUmamiTracker({websiteId:WEBSITE,hostname:"shop.example.test",browser:f.browser as never});assert.doesNotThrow(()=>trackPageview(tracker));assert.equal(f.sent.length,0)});
