import test from 'node:test';
import assert from 'node:assert/strict';
import {createInvitationBrowserHandlers} from './handlers.ts';
import {createInvitationTransport,INVITATION_BINDING_COOKIE} from '../../../../packages/saas-data/src/platform-invitations/transport.ts';
import {createInvitationService} from '../../../owner/lib/platform-invitations/service.ts';
import {createInvitationInternalHandler} from '../../../owner/lib/platform-invitations/http.ts';
import {createAes256GcmPayloadCipher} from '../../../owner/lib/saas-persistence/identity-crypto.ts';
import type {OidcProviderCallbackInput} from '../../../owner/lib/self-serve-oidc.ts';
const fixed=()=>new Date('2026-10-04T00:00:00Z');
const token='a'.repeat(72),host='shop.admin.example.test';
const config={ownerOrigin:'https://owner.example.test',panelOrigin:'https://panel.example.test',panelCallbackUrl:'https://panel.example.test/auth/callback',authorizationOrigin:'https://identity.example.test',clientId:'common-admin',key:Buffer.alloc(32,8),keyId:'fixture'};
function post(url:string,payload:string,origin:string){return new Request(url,{method:'POST',headers:{host:new URL(url).host,origin,'content-type':'application/x-www-form-urlencoded'},body:payload});}
function fixture(){
 const transport=createInvitationTransport({key:config.key,keyId:config.keyId,clock:fixed});let saved:unknown[]=[];let completed=false;let verifyCount=0;const actions:string[]=[];
 const service=createInvitationService({issuer:'https://identity.example.test',audience:config.clientId,callbackUrl:config.panelCallbackUrl,clock:fixed,seal:transport.seal,cipher:createAes256GcmPayloadCipher({currentKeyId:'fixture',resolveKey:()=>Buffer.alloc(32,9)}),provider:{buildAuthorizationUrl(input){const u=new URL(`${config.authorizationOrigin}/oidc/auth`);for(const [name,value] of Object.entries({state:input.state,redirect_uri:input.redirectUri,code_challenge:input.codeChallenge,code_challenge_method:input.codeChallengeMethod,client_id:config.clientId,response_type:'code'}))u.searchParams.set(name,value);return u;},async verifyCallback(input:OidcProviderCallbackInput){verifyCount++;return {issuer:input.expectedIssuer,subject:'new-subject',email:'invited@example.test',emailVerified:true,nonce:input.expectedNonce,audience:[config.clientId]};}},repository:{async execute(name,values){actions.push(name);if(name==='start'){assert.equal(values[2],host);saved=values;return {id:values[0]};}if(name==='claim'){if(completed)return {outcome:'replayed',result:{redirectUrl:`https://${host}/invitations/accepted`}};return {id:saved[0],encryptedPayload:JSON.parse(String(saved[5]))};}assert.deepEqual(values.slice(1),['https://identity.example.test','new-subject','invited@example.test',true]);completed=true;return {outcome:'committed',result:{redirectUrl:`https://${host}/invitations/accepted`}};}}});
 const internal=createInvitationInternalHandler(async()=>({service,transport,ownerOrigin:config.ownerOrigin}));
 const handlers=createInvitationBrowserHandlers({configuration:()=>config,clock:fixed,fetch:internal});
 return {handlers,transport,verifyCount:()=>verifyCount,actions};
}
async function begin(f:ReturnType<typeof fixture>){const started=await f.handlers.start(post(`https://${host}/api/platform-invitations/start`,`token=${token}`,`https://${host}`));assert.equal(started.status,200);assert.equal(started.headers.get('set-cookie'),null);const html=await started.text();assert.equal(html.includes('nonce='),true);const ticket=html.match(/name="ticket" value="([^"]+)"/)![1];const bootstrapped=await f.handlers.bootstrap(post(`${config.panelOrigin}/api/platform-invitations/bootstrap`,`ticket=${encodeURIComponent(ticket)}`,`https://${host}`));assert.equal(bootstrapped.status,303);const authorization=new URL(bootstrapped.headers.get('location')!);assert.equal(authorization.origin,config.authorizationOrigin);const setCookie=bootstrapped.headers.get('set-cookie')!;assert.match(setCookie,/Secure; HttpOnly; SameSite=Lax/);return {ticket,state:authorization.searchParams.get('state')!,cookie:setCookie.split(';')[0]};}
test('tenant invitation uses central callback and separate browser cookie, creates only native membership and recovers completed response',async()=>{const f=fixture(),b=await begin(f);const callback=new Request(`${config.panelCallbackUrl}?state=${b.state}&code=verified`,{headers:{host:'panel.example.test',cookie:`celebix_panel_session=normal-session; ${b.cookie}`}});const completed=await f.handlers.callback(callback);assert.equal(completed.status,303);assert.equal(completed.headers.get('location'),`https://${host}/invitations/accepted`);assert.equal(completed.headers.get('set-cookie'),`${INVITATION_BINDING_COOKIE}=; Path=/; Max-Age=0; Secure; HttpOnly; SameSite=Lax`);assert.equal(f.verifyCount(),1);assert.equal((await f.handlers.callback(callback)).status,303);assert.equal(f.verifyCount(),1);assert.deepEqual([...new Set(f.actions)],['start','claim','complete']);});
test('wrong tenant start origin, tampered bootstrap, cross origin, duplicate or absent browser binding fail closed',async()=>{const f=fixture();assert.equal((await f.handlers.start(post(`https://${host}/api/platform-invitations/start`,`token=${token}`,'https://evil.example.test'))).status,403);assert.equal(f.actions.length,0);const b=await begin(f);assert.equal((await f.handlers.bootstrap(post(`${config.panelOrigin}/api/platform-invitations/bootstrap`,`ticket=${b.ticket}`,'https://other.admin.example.test'))).status,403);assert.equal((await f.handlers.bootstrap(post(`${config.panelOrigin}/api/platform-invitations/bootstrap`,'ticket=iv1.tampered',`https://${host}`))).status,403);const callback=`${config.panelCallbackUrl}?state=${b.state}&code=verified`;assert.equal((await f.handlers.callback(new Request(callback,{headers:{host:'panel.example.test'}}))).status,403);assert.equal((await f.handlers.callback(new Request(callback,{headers:{host:'panel.example.test',cookie:`${b.cookie}; ${b.cookie}`}}))).status,403);assert.equal((await f.handlers.callback(new Request(callback,{headers:{host:'other.admin.example.test',cookie:b.cookie}}))).status,403);assert.equal(f.verifyCount(),0);});
