import assert from 'node:assert/strict';
import test from 'node:test';
import type {TenantContext} from '@celebix/saas-contracts';
const id='22300000-0000-4000-8000-000000000001',now=new Date('2026-10-09T12:00:00.000Z');
const config={schemaVersion:1,enabled:false,heading:'Bunları da beğenebilirsiniz',placements:{sideCart:true,checkout:true},maxOffers:3,rules:[]};
const context={schemaVersion:1,requestId:'qa',principal:{id,issuer:'https://test.invalid',subject:'qa'},store:{id,slug:'qa',status:'active'},membership:{id,role:'store_owner',status:'active'},entitlements:{schemaVersion:1,planId:id,planCode:'starter',version:1,status:'active',features:['catalog'],limits:{products:10,staff:1,storageBytes:100},validFrom:'2026-01-01T00:00:00.000Z'},locale:'tr-TR'} as TenantContext;
async function api(){const m:any=await import('./index.ts').catch(()=>({}));assert.equal(typeof m.PostgresOrderBumpAdminRepository,'function','order-bump repository must exist');return m;}
const options=(pool:any,role='celebix_saas_app')=>({pool,role,timeouts:{poolCheckoutMs:1000,statementMs:1000,lockMs:1000,idleTransactionMs:1000}});
function setup(payload:unknown,outcome='ok',uncertain=false,recoveryOutcome='replayed'){const calls:{text:string;values?:readonly unknown[]}[]=[],released:boolean[]=[];let count=0;const pool={connect:async()=>{const connection=count++;return{query:async(text:string,values?:readonly unknown[])=>{calls.push({text,values});if(text==='COMMIT'&&uncertain&&connection===0)throw Error('connection lost');return{rowCount:1,rows:text.includes('FROM saas.order_bump_')?[{outcome:text.includes('operation_get')?recoveryOutcome:outcome,result_payload:payload}]:[]};},release(destroy=false){released.push(destroy);}};}};return{pool,calls,released};}
test('settings read is read-only and binds server tenant authority',async()=>{const a=await api(),workspace={version:0,updatedAt:null,config},s=setup(workspace),r=new a.PostgresOrderBumpAdminRepository(options(s.pool));assert.deepEqual(await r.get({tenantContext:context,now}),workspace);assert.ok(s.calls.some(x=>x.text==='BEGIN READ ONLY'));assert.deepEqual(s.calls.find(x=>x.text.includes('settings_get('))?.values?.slice(0,3),[id,id,id]);});
test('uncertain save commit recovers exact journal result without another save',async()=>{const a=await api(),workspace={version:1,updatedAt:now.toISOString(),config},s=setup(workspace,'saved',true),r=new a.PostgresOrderBumpAdminRepository(options(s.pool));assert.deepEqual(await r.save({tenantContext:context,now,operationId:id,expectedVersion:0,config}),workspace);const write=s.calls.filter(x=>x.text.includes('settings_save('));assert.equal(write.length,1);const recovery=s.calls.find(x=>x.text.includes('operation_get('));assert.equal(recovery?.values?.[8],write[0]?.values?.[8]);assert.deepEqual(s.released,[true,false]);});
test('failed recovery stays uncertain and conflicts never issue a second write',async()=>{const a=await api(),s=setup(null,'saved',true,'operation_not_found'),r=new a.PostgresOrderBumpAdminRepository(options(s.pool));await assert.rejects(r.save({tenantContext:context,now,operationId:id,expectedVersion:0,config}),(e:any)=>e.code==='commit_uncertain');assert.equal(s.calls.filter(x=>x.text.includes('settings_save(')).length,1);const failure=setup(null,'version_conflict'),other=new a.PostgresOrderBumpAdminRepository(options(failure.pool));await assert.rejects(other.save({tenantContext:context,now,operationId:id,expectedVersion:0,config}),(e:any)=>e.code==='version_conflict');assert.ok(failure.calls.some(x=>x.text==='ROLLBACK'));assert.ok(!failure.calls.some(x=>x.text.includes('operation_get(')));});
test('forged scope and unsafe options are rejected before connection',async()=>{const a=await api(),s=setup(null),r=new a.PostgresOrderBumpAdminRepository(options(s.pool));for(const input of[{tenantContext:context,now,operationId:id,expectedVersion:-1,config},{tenantContext:context,now,operationId:id,expectedVersion:0,config,storeId:id}])await assert.rejects(r.save(input));for(const input of[{tenantContext:context,now,kind:'variant',page:0},{tenantContext:context,now,kind:'variant',page:1,ids:Array(401).fill(id)},{tenantContext:context,now,kind:'other',page:1}])await assert.rejects(r.options(input));assert.equal(s.calls.length,0);});
test('public offers bind trusted host credentials and reject forged cart totals',async()=>{const a=await api(),value={cartVersion:null,heading:null,offers:[]},s=setup(value),r=new a.PostgresPublicOrderBumpRepository(options(s.pool,'celebix_saas_host_resolver')),input={hostname:'store.example.com',now,credentialCandidates:[{keyId:'key1',digest:'a'.repeat(64)}],placement:'side_cart'};assert.deepEqual(await r.offers(input),value);assert.ok(s.calls.some(x=>x.text==='BEGIN READ ONLY'));assert.equal(s.calls.find(x=>x.text.includes('public_offers('))?.values?.[0],input.hostname);s.calls.length=0;for(const spoofed of[{...input,cartId:id},{...input,subtotalCents:1000},{...input,credentialCandidates:[{keyId:'key1',digest:'bad'}]},{...input,placement:'payment'}])await assert.rejects(r.offers(spoofed));assert.equal(s.calls.length,0);});
test('selected references read is bounded and response cannot inject a price authority',async()=>{const a=await api(),value={page:1,totalCount:1,items:[{id,label:'Ürün',productId:null,priceCents:null,available:true}]},s=setup(value),r=new a.PostgresOrderBumpAdminRepository(options(s.pool));assert.deepEqual(await r.options({tenantContext:context,now,kind:'product',page:1,ids:[id]}),value);const invalid=setup({...value,items:[{...value.items[0],salePriceCents:1}]}),other=new a.PostgresOrderBumpAdminRepository(options(invalid.pool));await assert.rejects(other.options({tenantContext:context,now,kind:'product',page:1}),(e:any)=>e.code==='unavailable');});

test('options share HTTP query bounds and reject ambiguous selected-mode selectors',async()=>{const a=await api(),value={items:[],page:1,totalCount:0},s=setup(value),r=new a.PostgresOrderBumpAdminRepository(options(s.pool));assert.deepEqual(await r.options({tenantContext:context,now,kind:'product',page:1,search:'s'.repeat(120)}),value);s.calls.length=0;for(const bad of[{search:''},{search:'s'.repeat(121)},{page:10001},{ids:[id],search:'x'},{ids:[id],productId:id}])await assert.rejects(r.options({tenantContext:context,now,kind:'variant',page:1,...bad}),(e:any)=>e.code==='invalid_input');assert.equal(s.calls.length,0);});
test('misspelled timeout configuration and pool failures remain typed safe errors',async()=>{const a=await api(),s=setup(null);assert.throws(()=>new a.PostgresOrderBumpAdminRepository({...options(s.pool),timeouts:{poolCheckoutMs:1000,statementMs:1000,lockMs:1000,idleTransactionTypo:1000}}),(e:any)=>e.code==='unavailable');const r=new a.PostgresOrderBumpAdminRepository(options({connect:async()=>{throw Error('socket secret');}}));await assert.rejects(r.get({tenantContext:context,now}),(e:any)=>e.code==='unavailable'&&!e.message.includes('socket'));});
