import {createHash} from 'node:crypto';
import type {TenantContext} from '@celebix/saas-contracts';
import {parseOrderBumpSettings,parseOrderBumpWorkspace,parseOrderBumpOptionsPage,parseOrderBumpPublicOffers,type OrderBumpSettings,type OrderBumpWorkspace,type OrderBumpOptionsPage,type OrderBumpPublicOffers} from '../../../saas-contracts/src/order-bumps/index.ts';
import {catalogAuthority} from '../catalog/validation.ts';
import {acquirePostgresClient,type PostgresPoolLike,type PostgresTimeoutOptions} from '../postgres/pool.ts';
import {commerceCandidates} from '../storefront-commerce/validation.ts';
import type {StorefrontCredentialCandidate} from '../storefront-commerce/types.ts';
export type OrderBumpRepositoryOptions=Readonly<{pool:PostgresPoolLike;role:'celebix_saas_app'|'celebix_saas_host_resolver';timeouts:PostgresTimeoutOptions}>;
export type OrderBumpGetInput=Readonly<{tenantContext:TenantContext;now:Date}>;
export type OrderBumpSaveInput=OrderBumpGetInput&Readonly<{operationId:string;expectedVersion:number;config:OrderBumpSettings}>;
export type OrderBumpOptionsInput=OrderBumpGetInput&Readonly<{kind:'product'|'category'|'variant';page:number;search?:string;productId?:string;ids?:readonly string[]}>;
export type OrderBumpPublicInput=Readonly<{hostname:string;now:Date;credentialCandidates:readonly StorefrontCredentialCandidate[];placement:'side_cart'|'checkout'}>;
export const ORDER_BUMP_ERROR_CODES=['invalid_input','unauthenticated','store_inactive','membership_denied','feature_not_enabled','durable_authority_invalid','role_denied','not_found','invalid_reference','version_conflict','operation_mismatch','operation_not_found','unavailable','commit_uncertain'] as const;
export type OrderBumpErrorCode=typeof ORDER_BUMP_ERROR_CODES[number];
export class OrderBumpRepositoryError extends Error{constructor(readonly code:OrderBumpErrorCode){super(`order_bump_${code}`);this.name='OrderBumpRepositoryError';}}
function fail(code:OrderBumpErrorCode='invalid_input'):never{throw new OrderBumpRepositoryError(code);}
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u;
function uuid(value:unknown):string{if(typeof value!=='string'||!UUID.test(value))fail();return value;}
function exact(value:unknown,required:readonly string[],optional:readonly string[]=[]):Record<string,unknown>{if(typeof value!=='object'||value===null||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)fail();const row=value as Record<string,unknown>,allowed=new Set([...required,...optional]);if(required.some(key=>!Object.hasOwn(row,key))||Object.keys(row).some(key=>!allowed.has(key)))fail();return row;}
function date(value:unknown):Date{if(!(value instanceof Date)||!Number.isFinite(value.getTime()))fail();return new Date(value.getTime());}
function fingerprint(value:unknown):string{function canonical(x:unknown):unknown{if(Array.isArray(x))return x.map(canonical);if(x&&typeof x==='object')return Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b,'en')).map(([key,v])=>[key,canonical(v)]));return x;}return createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex');}
type Call=Readonly<{name:string;values:readonly unknown[];casts:readonly string[]}>;
const authorityCasts=['uuid','uuid','uuid','uuid','text','bigint','timestamptz'] as const;
function authority(input:OrderBumpGetInput){try{const a=catalogAuthority(input.tenantContext,input.now);return[a.storeId,a.principalId,a.membershipId,a.planId,a.planCode,a.planVersion,a.now] as const;}catch(error){const code=(error as {code?:OrderBumpErrorCode}).code;fail(code&&ORDER_BUMP_ERROR_CODES.includes(code)?code:'invalid_input');}}
class Repository{
 constructor(protected readonly configuration:OrderBumpRepositoryOptions,role:OrderBumpRepositoryOptions['role']){if(configuration.role!==role||typeof configuration.pool?.connect!=='function'||Object.keys(configuration.timeouts??{}).length!==4||['poolCheckoutMs','statementMs','lockMs','idleTransactionMs'].some(k=>!Object.hasOwn(configuration.timeouts??{},k))||Object.values(configuration.timeouts).some(x=>!Number.isSafeInteger(x)||x<1||x>60_000))fail('unavailable');}
 protected async transact(call:Call,readOnly=true):Promise<unknown>{let client;try{client=await acquirePostgresClient(this.configuration.pool,this.configuration.timeouts.poolCheckoutMs);}catch{fail('unavailable');}let began=false,committing=false,destroy=false;try{await client.query(readOnly?'BEGIN READ ONLY':'BEGIN');began=true;for(const[key,value]of[['statement_timeout',this.configuration.timeouts.statementMs],['lock_timeout',this.configuration.timeouts.lockMs],['idle_in_transaction_session_timeout',this.configuration.timeouts.idleTransactionMs]] as const)await client.query('SELECT pg_catalog.set_config($1,$2,true)',[key,`${value}ms`]);await client.query(`SET LOCAL ROLE ${this.configuration.role}`);const result=await client.query(`SELECT outcome,result_payload FROM saas.${call.name}(${call.casts.map((cast,i)=>`$${i+1}::${cast}`).join(',')})`,[...call.values]);if(result.rowCount!==1||result.rows.length!==1)fail('unavailable');const row=result.rows[0] as {outcome:unknown;result_payload:unknown};if(!['ok','saved','replayed'].includes(row.outcome as string))fail(ORDER_BUMP_ERROR_CODES.includes(row.outcome as OrderBumpErrorCode)?row.outcome as OrderBumpErrorCode:'unavailable');committing=true;await client.query('COMMIT');committing=false;began=false;return row.result_payload;}catch(error){if(committing){destroy=true;fail(readOnly?'unavailable':'commit_uncertain');}if(began)try{await client.query('ROLLBACK');}catch{destroy=true;}if(error instanceof OrderBumpRepositoryError)throw error;fail('unavailable');}finally{client.release(destroy||undefined);}}
}
export class PostgresOrderBumpAdminRepository extends Repository{
 constructor(options:OrderBumpRepositoryOptions){super(options,'celebix_saas_app');}
 async get(input:OrderBumpGetInput):Promise<OrderBumpWorkspace>{exact(input,['tenantContext','now']);const value=await this.transact({name:'order_bump_settings_get',values:authority(input),casts:authorityCasts});try{return parseOrderBumpWorkspace(value);}catch{fail('unavailable');}}
 async save(input:OrderBumpSaveInput):Promise<OrderBumpWorkspace>{exact(input,['tenantContext','now','operationId','expectedVersion','config']);const a=authority(input),operationId=uuid(input.operationId);if(!Number.isSafeInteger(input.expectedVersion)||input.expectedVersion<0||input.expectedVersion>=Number.MAX_SAFE_INTEGER)fail();let config:OrderBumpSettings;try{config=parseOrderBumpSettings(input.config);}catch{fail();}const f=fingerprint({principalId:a[1],action:'save_order_bumps',expectedVersion:input.expectedVersion,config}),call={name:'order_bump_settings_save',values:[...a,operationId,f,input.expectedVersion,JSON.stringify(config)],casts:[...authorityCasts,'uuid','text','bigint','jsonb']};let value:unknown;try{value=await this.transact(call,false);}catch(error){if(!(error instanceof OrderBumpRepositoryError)||error.code!=='commit_uncertain')throw error;try{value=await this.transact({name:'order_bump_operation_get',values:[...a,operationId,f],casts:[...authorityCasts,'uuid','text']});}catch{fail('commit_uncertain');}}try{const result=parseOrderBumpWorkspace(value);if(result.version!==input.expectedVersion+1||JSON.stringify(result.config)!==JSON.stringify(config))fail('unavailable');return result;}catch{fail('unavailable');}}
 async options(input:OrderBumpOptionsInput):Promise<OrderBumpOptionsPage>{exact(input,['tenantContext','now','kind','page'],['search','productId','ids']);const a=authority(input);if(!['product','category','variant'].includes(input.kind)||!Number.isSafeInteger(input.page)||input.page<1||input.page>10_000)fail();if(input.search!==undefined&&(typeof input.search!=='string'||input.search!==input.search.trim()||input.search.length<1||input.search.length>120||/[\u0000-\u001f\u007f-\u009f]/u.test(input.search)))fail();const productId=input.productId===undefined?null:uuid(input.productId);if(productId!==null&&input.kind!=='variant')fail();let ids:readonly string[]|null=null;if(input.ids!==undefined){if(!Array.isArray(input.ids)||input.ids.length<1||input.ids.length>400)fail();ids=input.ids.map(uuid);if(new Set(ids).size!==ids.length||input.page!==1||input.search!==undefined||input.productId!==undefined)fail();}const value=await this.transact({name:'order_bump_options',values:[...a,input.kind,input.page,input.search??null,productId,ids],casts:[...authorityCasts,'text','integer','text','uuid','uuid[]']});try{const result=parseOrderBumpOptionsPage(value);if(result.page!==input.page||result.items.length>(ids?ids.length:20)||ids&&result.items.some(x=>!ids!.includes(x.id)))fail('unavailable');return result;}catch{fail('unavailable');}}
}
export class PostgresPublicOrderBumpRepository extends Repository{
 constructor(options:OrderBumpRepositoryOptions){super(options,'celebix_saas_host_resolver');}
 async offers(input:OrderBumpPublicInput):Promise<OrderBumpPublicOffers>{exact(input,['hostname','now','credentialCandidates','placement']);if(typeof input.hostname!=='string'||input.hostname!==input.hostname.toLowerCase()||input.hostname.length>253||!/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/u.test(input.hostname)||!['side_cart','checkout'].includes(input.placement))fail();let candidates;try{candidates=commerceCandidates(input.credentialCandidates,true);}catch{fail();}const value=await this.transact({name:'order_bump_public_offers',values:[input.hostname,date(input.now),JSON.stringify(candidates),input.placement],casts:['text','timestamptz','jsonb','text']});try{return parseOrderBumpPublicOffers(value);}catch{fail('unavailable');}}
}
