import { CATALOG_ADMIN_RESOURCE_KINDS, PRODUCT_REVIEW_STATUSES, parseCatalogAdminImportJob, parseCatalogAdminMutationResult, parseCatalogAdminResource, parseCatalogImportPreview, parseProductReview, type CatalogAdminResourceKind, type CatalogImportFormat, type ProductReviewStatus, type TenantContext } from "@celebix/saas-contracts";
import { CATALOG_ADMIN_ERROR_CODES, CatalogAdminRepositoryError, type CatalogAdminErrorCode } from "@celebix/saas-data";
import type { ServerPanelAccessResult } from "../server-panel-access/access.ts";
import type { ServerCatalogAdminRuntime } from "../server-catalog-admin/runtime.ts";
import { readOrderPanelSessionCookie } from "../order-http/request-input.ts";
import { approvedPanelMutationOriginForStore, hasApprovedPanelMutationOriginShape } from "../panel-origin-authority.ts";
import { CATALOG_IMPORT_PROVIDERS, parseCatalogImportSource, type CatalogImportProvider } from "../catalog-import/providers.ts";
import { CatalogFeedError, type CatalogFeedMediaType } from "../catalog-import/feed-fetcher.ts";
import { parseCatalogCsv } from "../catalog-import/csv.ts";
import { digestCatalogImport } from "../catalog-import/digest.ts";

const BASE = "/api/catalog/admin";
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const REQUEST_ID = UUID;
const CONTROL = /[\u0000-\u001f\u007f]/;
const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const SKU = /^[A-Z0-9][A-Z0-9._-]{0,63}$/;
const ATTRIBUTE_KEY = /^[A-Za-z0-9][A-Za-z0-9_.:-]{0,63}$/;
const STATUS: Readonly<Record<CatalogAdminErrorCode, number>> = Object.freeze({ invalid_input: 400, unauthenticated: 401, membership_denied: 403, store_inactive: 403, feature_not_enabled: 403, resource_not_found: 404, review_not_found: 404, slug_conflict: 409, product_limit_reached: 409, import_conflict: 409, invalid_transition: 409, version_conflict: 409, operation_mismatch: 409, durable_authority_invalid: 409, unavailable: 503 });
type FeedResult = Readonly<{ mediaType: CatalogFeedMediaType; body: string }>;
type Deps = Readonly<{ resolveRuntime(): Promise<ServerCatalogAdminRuntime | null>; now(): Date; requestId(): string; fetchFeed?: (url: string) => Promise<FeedResult> }>;
type Authorized = Readonly<{ runtime: ServerCatalogAdminRuntime; tenantContext: TenantContext; now: Date }>;
function json(value: unknown, status = 200, extra?: HeadersInit) { const headers = new Headers(extra); headers.set("cache-control", "no-store"); headers.set("x-content-type-options", "nosniff"); return Response.json(value, { status, headers }); }
function error(code: string, status: number, extra?: HeadersInit) { return json({ code }, status, extra); }
function privateHeaders(request: Request) { for (const [name] of request.headers) if (name === "authorization" || name.startsWith("x-celebix") || ["x-store-id", "x-tenant-id", "x-principal-id", "x-membership-id", "x-plan-id", "x-database-url"].includes(name)) return true; return false; }
function record(value: unknown) { if (typeof value !== "object" || value === null || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype) return null; return value as Record<string, unknown>; }
function exact(value: unknown, required: readonly string[], optional: readonly string[] = []) { const parsed = record(value); if (!parsed) return null; const allowed = new Set([...required, ...optional]); return required.some((key) => !Object.hasOwn(parsed, key)) || Object.keys(parsed).some((key) => !allowed.has(key)) ? null : parsed; }
function text(value: unknown, min: number, max: number, pattern?: RegExp) { return typeof value === "string" && value.length >= min && value.length <= max && value === value.trim() && !CONTROL.test(value) && (!pattern || pattern.test(value)) ? value : null; }
function positive(value: unknown) { return Number.isSafeInteger(value) && (value as number) > 0 ? value as number : null; }
function nonNegative(value: unknown) { return Number.isSafeInteger(value) && (value as number) >= 0 ? value as number : null; }
function operation(request: Request) { const value = request.headers.get("idempotency-key"); return value && UUID.test(value) && !value.includes(",") ? value : null; }
async function body(request: Request) { if (request.headers.get("content-type") !== "application/json" || request.headers.get("transfer-encoding") !== null || request.body === null) return null; const length = request.headers.get("content-length"); if (length !== null && (!/^(?:0|[1-9]\d*)$/.test(length) || Number(length) > 524_288)) return null; const reader = request.body.getReader(); const chunks: Uint8Array[] = []; let total = 0; try { for (;;) { const next = await reader.read(); if (next.done) break; total += next.value.byteLength; if (total > 524_288) { await reader.cancel().catch(() => undefined); return null; } chunks.push(new Uint8Array(next.value)); } } catch { return null; } if (!total) return null; const bytes = new Uint8Array(total); let offset = 0; for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.length; } try { return JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(bytes)); } catch { return null; } }
function repositoryError(value: unknown) { return value instanceof CatalogAdminRepositoryError && CATALOG_ADMIN_ERROR_CODES.includes(value.code) ? error(value.code, STATUS[value.code]) : error("unavailable", 503); }
async function authorize(deps: Deps, request: Request, method: "GET" | "POST", pathname: string, query: "allowed" | "forbidden"): Promise<Response | Authorized> { let runtime; try { runtime = await deps.resolveRuntime(); } catch { return error("unavailable", 503); } if (!runtime) return error("unavailable", 503); if (request.method !== method) return error("method_not_allowed", 405, { allow: method }); if (method === "POST" && !hasApprovedPanelMutationOriginShape(request, runtime.access.panelOrigin)) return error("origin_denied", 403); let url: URL; try { url = new URL(request.url); } catch { return error("invalid_input", 400); } if (!["http:", "https:"].includes(url.protocol) || url.username || url.password || url.pathname !== pathname || url.hash || (query === "forbidden" && url.search) || privateHeaders(request)) return error("invalid_input", 400); const cookie = readOrderPanelSessionCookie(request); if (cookie.kind !== "present") return error("unauthenticated", 401); let now: Date; let requestId: string; try { now = deps.now(); requestId = deps.requestId(); } catch { return error("unavailable", 503); } if (!(now instanceof Date) || !Number.isFinite(now.getTime()) || !REQUEST_ID.test(requestId)) return error("unavailable", 503); let access: ServerPanelAccessResult; try { access = await runtime.access.resolveCredential({ credential: cookie.credential, requestId, now: new Date(now) }); } catch { return error("unavailable", 503); } if (access.kind === "unauthenticated") return error("unauthenticated", 401); if (access.kind === "unauthorized") return error("membership_denied", 403); if (access.kind !== "authenticated") return error("unavailable", 503); if (method === "POST" && !approvedPanelMutationOriginForStore(request, runtime.access.panelOrigin, access.tenantContext.store.slug)) return error("origin_denied", 403); return Object.freeze({ runtime, tenantContext: access.tenantContext, now: new Date(now) }); }
function isResponse(value: unknown): value is Response { return value instanceof Response; }
async function execute(run: () => Promise<unknown>, parser: (value: unknown) => unknown) { try { return json(parser(await run())); } catch (caught) { return repositoryError(caught); } }
function items(value: unknown, parser: (entry: unknown) => unknown, limit: number) { if (!Array.isArray(value) || value.length > limit) throw new TypeError(); return Object.freeze({ items: Object.freeze(value.map(parser)) }); }
function kind(value: unknown): CatalogAdminResourceKind | null { return CATALOG_ADMIN_RESOURCE_KINDS.includes(value as never) ? value as CatalogAdminResourceKind : null; }
function id(value: unknown) { return typeof value === "string" && UUID.test(value) ? value : null; }
function resourceInput(raw: unknown) { const parsed = exact(raw, ["name", "slug", "config", "productIds"], ["resourceId", "expectedVersion", "description"]); if (!parsed || (parsed.resourceId !== undefined && (!id(parsed.resourceId) || !positive(parsed.expectedVersion))) || (parsed.resourceId === undefined && parsed.expectedVersion !== undefined) || !Array.isArray(parsed.productIds) || parsed.productIds.length > 10_000 || new TextEncoder().encode(JSON.stringify(parsed.productIds)).byteLength > 400_000 || parsed.productIds.some((entry) => !id(entry)) || new Set(parsed.productIds).size !== parsed.productIds.length || !record(parsed.config)) return null; const name = text(parsed.name, 1, 120); const slug = text(parsed.slug, 1, 120, SLUG); const description = parsed.description === undefined ? undefined : text(parsed.description, 1, 2000); if (!name || !slug || (parsed.description !== undefined && !description) || JSON.stringify(parsed.config).length > 8192) return null; return Object.freeze({ ...(parsed.resourceId ? { resourceId: parsed.resourceId as string, expectedVersion: parsed.expectedVersion as number } : {}), name, slug, ...(description ? { description } : {}), config: parsed.config as Record<string, never>, productIds: Object.freeze([...parsed.productIds] as string[]) }); }
function importInput(raw: unknown) { const parsed = exact(raw, ["fileName", "rows"]); const fileName = parsed ? text(parsed.fileName, 1, 200) : null; if (!parsed || !fileName || !Array.isArray(parsed.rows) || parsed.rows.length < 1 || parsed.rows.length > 100) return null; const rows = parsed.rows.map((entry) => { const row = exact(entry, ["title", "slug", "priceCents", "stockQuantity"], ["sku"]); const title = row ? text(row.title, 1, 200) : null; const slug = row ? text(row.slug, 3, 100, SLUG) : null; const sku = row?.sku === undefined ? undefined : text(row.sku, 1, 64, SKU); return row && title && slug && Number.isSafeInteger(row.priceCents) && (row.priceCents as number) >= 0 && Number.isSafeInteger(row.stockQuantity) && (row.stockQuantity as number) >= 0 && (row.sku === undefined || sku) ? Object.freeze({ title, slug, priceCents: row.priceCents as number, ...(sku ? { sku } : {}), stockQuantity: row.stockQuantity as number }) : null; }); return rows.some((entry) => !entry) ? null : Object.freeze({ fileName, rows: Object.freeze(rows as NonNullable<(typeof rows)[number]>[]) }); }
function importAttributes(raw: unknown) { const parsed = record(raw); if (!parsed || Object.keys(parsed).length > 32 || Object.keys(parsed).some((key) => !ATTRIBUTE_KEY.test(key))) return null; const entries = Object.entries(parsed).map(([key, value]) => { const selected = text(value, 0, 256); return selected === null ? null : [key, selected] as const; }); return entries.some((entry) => entry === null) ? null : Object.freeze(Object.fromEntries(entries as readonly (readonly [string, string])[])); }
function importVariant(raw: unknown) { const parsed = exact(raw, ["title", "priceCents", "stockQuantity", "attributes"], ["sku", "barcode", "compareAtCents", "costCents"]); if (!parsed) return null; const title = text(parsed.title, 1, 200), sku = parsed.sku === undefined ? undefined : text(parsed.sku, 1, 64, SKU), barcode = parsed.barcode === undefined ? undefined : text(parsed.barcode, 1, 128), priceCents = nonNegative(parsed.priceCents), compareAtCents = parsed.compareAtCents === undefined ? undefined : nonNegative(parsed.compareAtCents), costCents = parsed.costCents === undefined ? undefined : nonNegative(parsed.costCents), stockQuantity = nonNegative(parsed.stockQuantity), attributes = importAttributes(parsed.attributes); if (!title || priceCents === null || stockQuantity === null || !attributes || (parsed.sku !== undefined && !sku) || (parsed.barcode !== undefined && !barcode) || (parsed.compareAtCents !== undefined && (compareAtCents === null || compareAtCents === undefined || compareAtCents < priceCents)) || (parsed.costCents !== undefined && costCents === null)) return null; return Object.freeze({ title, ...(sku ? { sku } : {}), ...(barcode ? { barcode } : {}), priceCents, ...(typeof compareAtCents === "number" ? { compareAtCents } : {}), ...(typeof costCents === "number" ? { costCents } : {}), stockQuantity, attributes }); }
function importInputV2(raw: unknown) { const parsed = exact(raw, ["fileName", "products"]), fileName = parsed ? text(parsed.fileName, 1, 200) : null; if (!parsed || !fileName || !Array.isArray(parsed.products) || parsed.products.length < 1 || parsed.products.length > 100) return null; const slugs = new Set<string>(), skus = new Set<string>(); let variantCount = 0; const products = parsed.products.map((entry) => { const product = exact(entry, ["title", "slug", "status", "variants"], ["description"]), title = product ? text(product.title, 1, 200) : null, slug = product ? text(product.slug, 3, 100, SLUG) : null, description = product?.description === undefined ? undefined : text(product.description, 1, 10_000); if (!product || !title || !slug || !["draft", "active"].includes(String(product.status)) || (product.description !== undefined && !description) || !Array.isArray(product.variants) || product.variants.length < 1 || product.variants.length > 50 || slugs.has(slug)) return null; slugs.add(slug); const variants = product.variants.map((value) => { const variant = importVariant(value); if (!variant || (variant.sku && skus.has(variant.sku))) return null; if (variant.sku) skus.add(variant.sku); variantCount += 1; return variant; }); if (variantCount > 500 || variants.some((variant) => !variant)) return null; return Object.freeze({ title, slug, ...(description ? { description } : {}), status: product.status as "draft" | "active", variants: Object.freeze(variants as NonNullable<(typeof variants)[number]>[]) }); }); return products.some((product) => !product) || JSON.stringify(products).length > 120_000 ? null : Object.freeze({ fileName, products: Object.freeze(products as NonNullable<(typeof products)[number]>[]) }); }
function feedInput(raw: unknown) { const parsed = exact(raw, ["provider", "url"]), url = parsed ? text(parsed.url, 1, 2048) : null; const provider = parsed && CATALOG_IMPORT_PROVIDERS.some((entry) => entry.id === parsed.provider) ? parsed.provider as CatalogImportProvider : null; return url && provider ? Object.freeze({ url, provider }) : null; }
function previewInput(raw: unknown) { const parsed = exact(raw, ["format", "fileName", "content"]); const format = parsed && ["native_csv", "shopify_csv"].includes(String(parsed.format)) ? parsed.format as CatalogImportFormat : null; const fileName = parsed ? text(parsed.fileName, 1, 200) : null; return parsed && format && fileName && typeof parsed.content === "string" ? { format, fileName, content: parsed.content } : null; }

export function createCatalogAdminHttpHandlers(deps: Deps) {
  if (!deps || typeof deps.resolveRuntime !== "function" || typeof deps.now !== "function" || typeof deps.requestId !== "function" || (deps.fetchFeed !== undefined && typeof deps.fetchFeed !== "function")) throw new Error("catalog_admin_http_handler_invalid");
  return Object.freeze({
    async resources(request: Request, rawKind: unknown) { const resourceKind = kind(rawKind); if (!resourceKind) return error("invalid_input", 400); const path = `${BASE}/resources/${resourceKind}`; const authorized = await authorize(deps, request, "GET", path, "forbidden"); return isResponse(authorized) ? authorized : execute(() => authorized.runtime.catalogAdmin.listResources({ tenantContext: authorized.tenantContext, now: authorized.now, kind: resourceKind }), (value) => items(value, parseCatalogAdminResource, 200)); },
    async resource(request: Request, rawKind: unknown, rawId: unknown) { const resourceKind = kind(rawKind); const resourceId = id(rawId); if (!resourceKind || !resourceId) return error("invalid_input", 400); const path = `${BASE}/resources/${resourceKind}/${resourceId}`; const authorized = await authorize(deps, request, "GET", path, "forbidden"); return isResponse(authorized) ? authorized : execute(() => authorized.runtime.catalogAdmin.getResource({ tenantContext: authorized.tenantContext, now: authorized.now, kind: resourceKind, resourceId }), parseCatalogAdminResource); },
    async saveResource(request: Request, rawKind: unknown) { const resourceKind = kind(rawKind); if (!resourceKind) return error("invalid_input", 400); const path = `${BASE}/resources/${resourceKind}`; const authorized = await authorize(deps, request, "POST", path, "forbidden"); if (isResponse(authorized)) return authorized; const operationId = operation(request); const input = resourceInput(await body(request)); return operationId && input ? execute(() => authorized.runtime.catalogAdmin.saveResource({ tenantContext: authorized.tenantContext, now: authorized.now, operationId, kind: resourceKind, ...input }), parseCatalogAdminMutationResult) : error("invalid_input", 400); },
    async archiveResource(request: Request, rawKind: unknown, rawId: unknown) { const resourceKind = kind(rawKind); const resourceId = id(rawId); if (!resourceKind || !resourceId) return error("invalid_input", 400); const path = `${BASE}/resources/${resourceKind}/${resourceId}/archive`; const authorized = await authorize(deps, request, "POST", path, "forbidden"); if (isResponse(authorized)) return authorized; const operationId = operation(request); const parsed = exact(await body(request), ["expectedVersion"]); const expectedVersion = parsed ? positive(parsed.expectedVersion) : null; return operationId && expectedVersion ? execute(() => authorized.runtime.catalogAdmin.archiveResource({ tenantContext: authorized.tenantContext, now: authorized.now, operationId, resourceId, expectedVersion }), parseCatalogAdminMutationResult) : error("invalid_input", 400); },
    async reviews(request: Request) { const authorized = await authorize(deps, request, "GET", `${BASE}/reviews`, "allowed"); if (isResponse(authorized)) return authorized; const url = new URL(request.url); const entries = [...url.searchParams.entries()]; if (entries.some(([key]) => key !== "status") || new Set(entries.map(([key]) => key)).size !== entries.length) return error("invalid_input", 400); const rawStatus = url.searchParams.get("status"); const status = rawStatus === null ? undefined : PRODUCT_REVIEW_STATUSES.includes(rawStatus as never) ? rawStatus as ProductReviewStatus : null; return status === null ? error("invalid_input", 400) : execute(() => authorized.runtime.catalogAdmin.listReviews({ tenantContext: authorized.tenantContext, now: authorized.now, ...(status ? { status } : {}) }), (value) => items(value, parseProductReview, 200)); },
    async moderateReview(request: Request, rawId: unknown) { const reviewId = id(rawId); if (!reviewId) return error("invalid_input", 400); const path = `${BASE}/reviews/${reviewId}/moderate`; const authorized = await authorize(deps, request, "POST", path, "forbidden"); if (isResponse(authorized)) return authorized; const operationId = operation(request); const parsed = exact(await body(request), ["expectedVersion", "status"], ["reply"]); const expectedVersion = parsed ? positive(parsed.expectedVersion) : null; const status = parsed && ["approved", "rejected", "archived"].includes(String(parsed.status)) ? parsed.status as "approved" | "rejected" | "archived" : null; const reply = parsed?.reply === undefined ? undefined : text(parsed.reply, 1, 2000); return operationId && expectedVersion && status && (parsed?.reply === undefined || reply) ? execute(() => authorized.runtime.catalogAdmin.moderateReview({ tenantContext: authorized.tenantContext, now: authorized.now, operationId, reviewId, expectedVersion, status, ...(reply ? { reply } : {}) }), parseCatalogAdminMutationResult) : error("invalid_input", 400); },
    async imports(request: Request) { const authorized = await authorize(deps, request, "GET", `${BASE}/imports`, "forbidden"); return isResponse(authorized) ? authorized : execute(() => authorized.runtime.catalogAdmin.listImports({ tenantContext: authorized.tenantContext, now: authorized.now }), (value) => items(value, parseCatalogAdminImportJob, 100)); },
    async importProducts(request: Request) { const authorized = await authorize(deps, request, "POST", `${BASE}/imports`, "forbidden"); if (isResponse(authorized)) return authorized; const operationId = operation(request); const raw = await body(request); const legacy = importInput(raw); const rich = legacy ? null : importInputV2(raw); if (!operationId || (!legacy && !rich)) return error("invalid_input", 400); return legacy ? execute(() => authorized.runtime.catalogAdmin.importProducts({ tenantContext: authorized.tenantContext, now: authorized.now, operationId, ...legacy }), parseCatalogAdminMutationResult) : execute(() => authorized.runtime.catalogAdmin.importProductsV2({ tenantContext: authorized.tenantContext, now: authorized.now, operationId, ...rich! }), parseCatalogAdminMutationResult); },
    async previewFeed(request: Request) { const authorized = await authorize(deps, request, "POST", `${BASE}/imports/feed/preview`, "forbidden"); if (isResponse(authorized)) return authorized; const selected = feedInput(await body(request)); if (!selected || !deps.fetchFeed) return error("invalid_input", 400); try { await authorized.runtime.catalogAdmin.authorizeFeedPreview({ tenantContext: authorized.tenantContext, now: authorized.now }); } catch (caught) { return repositoryError(caught); } let fetched: FeedResult; try { fetched = await deps.fetchFeed(selected.url); } catch (caught) { return caught instanceof CatalogFeedError && ["catalog_feed_url_invalid", "catalog_feed_address_denied", "catalog_feed_redirect_invalid", "catalog_feed_response_invalid", "catalog_feed_response_too_large"].includes(caught.code) ? error("invalid_input", 400) : error("unavailable", 503); } try { const parsed = parseCatalogImportSource(fetched.body, { provider: selected.provider, format: fetched.mediaType }); return json({ products: parsed.products, warnings: parsed.warnings, skippedRows: parsed.skippedRows, totalRows: parsed.totalRows, format: fetched.mediaType }); } catch { return error("invalid_input", 400); } },
    async prepareImportPreview(request: Request) { const authorized = await authorize(deps, request, "POST", `${BASE}/import-previews`, "forbidden"); if (isResponse(authorized)) return authorized; const operationId = operation(request); let input = previewInput(await body(request)); if (!operationId || !input) return error("invalid_input", 400); let previewId: string; try { previewId = deps.requestId(); } catch { return error("unavailable", 503); } if (!REQUEST_ID.test(previewId)) return error("unavailable", 503); let rows; let digest; let content = input.content; try { rows = parseCatalogCsv({ format: input.format, content }); digest = digestCatalogImport(input.format, content); } catch { return error("invalid_input", 400); } const repositoryInput = Object.freeze({ tenantContext: authorized.tenantContext, now: authorized.now, operationId, previewId, format: input.format, fileName: input.fileName, digest, rows }); content = ""; input = null; return execute(() => authorized.runtime.catalogAdmin.prepareImport(repositoryInput), parseCatalogImportPreview); },
    async getImportPreview(request: Request, rawId: unknown) { const previewId = id(rawId); if (!previewId) return error("invalid_input", 400); const authorized = await authorize(deps, request, "GET", `${BASE}/import-previews/${previewId}`, "forbidden"); return isResponse(authorized) ? authorized : execute(() => authorized.runtime.catalogAdmin.getImportPreview({ tenantContext: authorized.tenantContext, now: authorized.now, previewId }), parseCatalogImportPreview); },
    async commitImportPreview(request: Request, rawId: unknown) { const previewId = id(rawId); if (!previewId) return error("invalid_input", 400); const authorized = await authorize(deps, request, "POST", `${BASE}/import-previews/${previewId}/commit`, "forbidden"); if (isResponse(authorized)) return authorized; const operationId = operation(request); const parsed = exact(await body(request), ["expectedVersion"]); const expectedVersion = parsed ? positive(parsed.expectedVersion) : null; return operationId && expectedVersion ? execute(() => authorized.runtime.catalogAdmin.commitImportPreview({ tenantContext: authorized.tenantContext, now: authorized.now, operationId, previewId, expectedVersion }), parseCatalogAdminMutationResult) : error("invalid_input", 400); },
  });
}
