import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import * as React from 'react';
import { act, createElement } from 'react';
import * as jsxRuntime from 'react/jsx-runtime';
import { Window } from 'happy-dom';
import ts from 'typescript';
import { parseStorefrontAsset } from '@celebix/saas-contracts';
import { categoryImageFileError, categoryImageFrame } from '../../lib/catalog-onboarding-ui/category-image.ts';
import { safePublicUrl } from '../../lib/catalog-collections-ui/model.ts';
const STORE='76000000-0000-4000-8000-000000000001',NOW='2026-09-30T12:00:00.000Z';
function asset(id:string){const objectKey=`stores/${STORE}/storefront/collection/${id}.webp`;return {id,storeId:STORE,kind:'collection',objectKey,publicUrl:`https://media.example.test/${objectKey}`,mediaType:'image/webp',altText:'Şehir',width:1200,height:1600,byteSize:32,status:'active',createdAt:NOW,updatedAt:NOW,version:1};}
test('3:4 crop uploads a collection asset, failure retains its retry identity and success clears pending',async()=>{
 const browser=new Window({url:'https://panel.example.test/products/collections/new'});const old=new Map<string,PropertyDescriptor|undefined>();const changes:any[]=[],pending:boolean[]=[],calls:{id:string;kind:unknown;file:File}[]=[],releases:string[]=[];let attempt=0,draw:any[]=[];const urls={createObjectURL:()=>`blob:fixture-${++attempt}`,revokeObjectURL:(url:string)=>releases.push(url)};class DecodedImage{naturalWidth=1200;naturalHeight=1600;onload:()=>void=()=>{};set src(_value:string){queueMicrotask(()=>this.onload());}}
 class MockURL extends URL {static createObjectURL=urls.createObjectURL;static revokeObjectURL=urls.revokeObjectURL;}
 Object.defineProperty(browser,'Image',{value:DecodedImage,configurable:true});browser.HTMLCanvasElement.prototype.getContext=(()=>({drawImage:(...args:any[])=>draw=args}))as any;browser.HTMLCanvasElement.prototype.toBlob=function(callback:(blob:InstanceType<typeof browser.Blob>)=>void,type?:string){callback(new browser.Blob(['valid-binary-image'],{type:type??'image/webp'}));};
 const fetchStub=async(_input:unknown,init?:RequestInit)=>{const body=init?.body as unknown as FormData;const id=new Headers(init?.headers).get('idempotency-key')!;calls.push({id,kind:body.get('kind'),file:body.get('file')as File});return calls.length===1?Response.json({code:'unavailable'},{status:503}):Response.json({asset:asset(id)});};
 for(const[key,value]of Object.entries({window:browser,document:browser.document,navigator:browser.navigator,HTMLElement:browser.HTMLElement,Element:browser.Element,Event:browser.Event,MouseEvent:browser.MouseEvent,MutationObserver:browser.MutationObserver,File:browser.File,Blob:browser.Blob,FormData:browser.FormData,URL:MockURL,fetch:fetchStub,IS_REACT_ACT_ENVIRONMENT:true})){old.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{configurable:true,writable:true,value});}
 const styles=new Proxy({},{get:(_t,key)=>key==='__esModule'?true:key==='default'?styles:String(key)});const modules=new Map<string,Record<string,unknown>>();const sources=new Map(await Promise.all(['CollectionMediaField','CollectionDialog'].map(async file=>[file,await readFile(new URL(`./${file}.tsx`,import.meta.url),'utf8')]as const)));function load(file:string):Record<string,unknown>{if(modules.has(file))return modules.get(file)!;const compiled={exports:{} as Record<string,unknown>};modules.set(file,compiled.exports);const output=ts.transpileModule(sources.get(file)!,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;Function('require','module','exports',output)((name:string)=>{if(name==='react')return React;if(name==='react/jsx-runtime')return jsxRuntime;if(name==='lucide-react')return new Proxy({},{get:()=>()=>null});if(name==='@celebix/saas-contracts')return {parseStorefrontAsset};if(name==='@/lib/catalog-onboarding-ui/category-image')return {categoryImageFileError,categoryImageFrame};if(name==='@/lib/catalog-collections-ui/model')return {safePublicUrl};if(name==='./CollectionDialog')return load('CollectionDialog');if(name.endsWith('.module.css'))return styles;throw new Error(name);},compiled,compiled.exports);return compiled.exports;}
 const Field=load('CollectionMediaField').CollectionMediaField as React.ComponentType<any>;function Parent(){const[value,setValue]=React.useState<string>();const[url,setUrl]=React.useState<string>();return createElement(Field,{value,imageUrl:url,name:'Şehir',disabled:false,onChange:(id?:string,image?:string)=>{changes.push(id);setValue(id);setUrl(image);},onBusyChange:()=>{},onPendingChange:(value:boolean)=>pending.push(value)});}
 const {createRoot}=await import('react-dom/client');const container=browser.document.createElement('div');browser.document.body.append(container);const root=createRoot(container as unknown as HTMLElement);const settle=async()=>act(async()=>{await new Promise(resolve=>setTimeout(resolve,0));});try{await act(async()=>root.render(createElement(Parent)));const input=container.querySelector('input[type=file]')!;Object.defineProperty(input,'files',{value:[new browser.File(['source-image'],'photo.png',{type:'image/png'})],configurable:true});await act(async()=>input.dispatchEvent(new browser.Event('change',{bubbles:true})));await settle();assert.ok(container.querySelector('dialog[open]'));const apply=[...container.querySelectorAll('button')].find(button=>button.textContent==='Kapağı kullan')!;await act(async()=>apply.click());await settle();assert.match(container.textContent??'',/Seçiminiz korundu/);assert.equal(pending.at(-1),true);assert.equal(calls[0].kind,'collection');assert.equal(calls[0].file.type,'image/webp');assert.equal(draw[7]/draw[8],3/4);const retry=[...container.querySelectorAll('button')].find(button=>button.textContent==='Tekrar dene')!;await act(async()=>retry.click());await settle();assert.equal(calls.length,2);assert.equal(calls[0].id,calls[1].id);assert.deepEqual(changes,[calls[0].id]);assert.equal(pending.at(-1),false);assert.ok(container.querySelector('img[src^="https://media.example.test/"]'));assert.equal(releases.length,2);}finally{await act(async()=>root.unmount());for(const[key,descriptor]of old)descriptor?Object.defineProperty(globalThis,key,descriptor):Reflect.deleteProperty(globalThis,key);await browser.happyDOM.close();}
});
