'use client';
import { parseStorefrontAsset, type StorefrontAsset } from '@celebix/saas-contracts';
import { Image as ImageIcon, ImagePlus, LoaderCircle, Trash2, Upload } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { categoryImageFileError, categoryImageFrame } from '@/lib/catalog-onboarding-ui/category-image';
import { safePublicUrl } from '@/lib/catalog-collections-ui/model';
import { CollectionDialog } from './CollectionDialog';
import styles from './collections.module.css';
type Crop={file:File;url:string;width:number;height:number;zoom:number;x:number;y:number};
type Attempt={id:string;file:File;url:string;altText:string};
export function CollectionMediaField({value,imageUrl,name,disabled,onChange,onBusyChange,onPendingChange}:{value?:string;imageUrl?:string;name:string;disabled:boolean;onChange(assetId?:string,url?:string):void;onBusyChange(busy:boolean):void;onPendingChange(pending:boolean):void}){
 const [assets,setAssets]=useState<readonly StorefrontAsset[]>([]);const [library,setLibrary]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [crop,setCrop]=useState<Crop>();const [attempt,setAttempt]=useState<Attempt>();const fileRef=useRef<HTMLInputElement>(null);const chooseRef=useRef<HTMLButtonElement>(null);const mounted=useRef(true);const urls=useRef(new Set<string>());const controller=useRef<AbortController | undefined>(undefined);const callbacks=useRef({onChange,onBusyChange,onPendingChange});callbacks.current={onChange,onBusyChange,onPendingChange};
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;controller.current?.abort();urls.current.forEach(url=>URL.revokeObjectURL(url));callbacks.current.onBusyChange(false);callbacks.current.onPendingChange(false);};},[]);
 function objectUrl(file:File){const url=URL.createObjectURL(file);urls.current.add(url);return url;}
 function revoke(url:string){URL.revokeObjectURL(url);urls.current.delete(url);}
 function working(value:boolean){setBusy(value);callbacks.current.onBusyChange(value);}
 function clearAttempt(){if(attempt)revoke(attempt.url);setAttempt(undefined);callbacks.current.onPendingChange(false);}
 async function select(file?:File){if(!file||disabled||busy)return;const failure=categoryImageFileError(file);if(failure){setError(failure);return;}clearAttempt();setError('');working(true);callbacks.current.onPendingChange(true);const url=objectUrl(file);try{const image=new window.Image();await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error('decode'));image.src=url;});categoryImageFrame(image.naturalWidth,image.naturalHeight);if(mounted.current)setCrop({file,url,width:image.naturalWidth,height:image.naturalHeight,zoom:1,x:50,y:50});}catch{revoke(url);callbacks.current.onPendingChange(false);setError('Görsel açılamadı. En fazla 8192 × 8192 boyutunda bir görsel seçin.');}finally{if(mounted.current)working(false);if(fileRef.current)fileRef.current.value='';}}
 function closeCrop(){if(crop)revoke(crop.url);setCrop(undefined);callbacks.current.onPendingChange(false);chooseRef.current?.focus();}
 async function upload(next:Attempt){working(true);setError('');const request=new AbortController();controller.current=request;try{const body=new FormData();body.set('file',next.file);body.set('kind','collection');body.set('altText',next.altText);const response=await fetch('/api/storefront-assets',{method:'POST',credentials:'same-origin',headers:{'idempotency-key':next.id},body,signal:request.signal});if(!response.ok)throw new Error();const result=await response.json() as {asset:unknown};const asset=parseStorefrontAsset(result.asset);if(asset.id!==next.id||asset.kind!=='collection'||asset.status!=='active')throw new Error();if(!mounted.current)return;setAssets(current=>[asset,...current.filter(item=>item.id!==asset.id)]);callbacks.current.onChange(asset.id,asset.publicUrl);revoke(next.url);setAttempt(undefined);callbacks.current.onPendingChange(false);setLibrary(false);}catch{if(mounted.current)setError('Kapak yüklenemedi. Seçiminiz korundu; tekrar deneyin.');}finally{controller.current=undefined;if(mounted.current)working(false);}}
 async function applyCrop(){if(!crop||busy)return;working(true);setError('');try{const frame=categoryImageFrame(crop.width,crop.height);const width=frame.sourceWidth/crop.zoom,height=frame.sourceHeight/crop.zoom;const x=(crop.width-width)*crop.x/100,y=(crop.height-height)*crop.y/100;const image=new window.Image();await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error());image.src=crop.url;});const canvas=document.createElement('canvas');canvas.width=frame.width;canvas.height=frame.height;const context=canvas.getContext('2d');if(!context)throw new Error();context.drawImage(image,x,y,width,height,0,0,frame.width,frame.height);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error()),'image/webp',.9));const file=new File([blob],`collection.${blob.type==='image/webp'?'webp':'png'}`,{type:blob.type});if(categoryImageFileError(file))throw new Error();const next={id:crypto.randomUUID(),file,url:objectUrl(file),altText:name.trim()||'Koleksiyon kapağı'};revoke(crop.url);setCrop(undefined);setAttempt(next);await upload(next);}catch{setError('Kapak hazırlanamadı. Başka bir görsel deneyin.');callbacks.current.onPendingChange(false);working(false);}}
 async function openLibrary(){setLibrary(current=>!current);if(library)return;setLoading(true);setError('');try{const response=await fetch('/api/storefront-assets?kind=collection',{credentials:'same-origin',cache:'no-store'});if(!response.ok)throw new Error();const body=await response.json() as {assets:unknown[]};if(!Array.isArray(body.assets))throw new Error();setAssets(body.assets.map(parseStorefrontAsset).filter(asset=>asset.kind==='collection'&&asset.status==='active'));}catch{setError('Kapak kütüphanesi yüklenemedi. Tekrar deneyin.');}finally{setLoading(false);}}
 const selected=assets.find(asset=>asset.id===value);const preview=attempt?.url||safePublicUrl(selected?.publicUrl||imageUrl);const blocked=disabled||busy;const cropFrame=crop?categoryImageFrame(crop.width,crop.height):undefined;const cropW=crop&&cropFrame?crop.width/cropFrame.sourceWidth*crop.zoom*100:100;const cropH=crop&&cropFrame?crop.height/cropFrame.sourceHeight*crop.zoom*100:100;
 return <section className={styles.coverSection} aria-label="Koleksiyon kapağı" aria-busy={busy}><div className={styles.sectionLine}><h2>Kapak</h2><span className={styles.helper}>3:4</span></div><button ref={chooseRef} type="button" className={styles.coverPreview} disabled={blocked} aria-label={preview?'Koleksiyon kapağını değiştir':'Kapak görseli yükle'} onClick={()=>fileRef.current?.click()} onDragOver={event=>{if(!blocked&&event.dataTransfer.types.includes('Files'))event.preventDefault();}} onDrop={event=>{event.preventDefault();if(!blocked)void select(event.dataTransfer.files[0]);}}>{preview?<img src={preview} alt={name||'Koleksiyon kapağı'}/>:<span className={styles.coverPlaceholder}><ImagePlus aria-hidden="true"/><span>Kapak görseli ekle</span></span>}{busy?<span className={styles.busyOverlay} role="status"><LoaderCircle aria-hidden="true"/><span className={styles.srOnly}>Kapak yükleniyor</span></span>:null}</button><div className={styles.coverActions}><button type="button" className={styles.button} disabled={blocked} onClick={()=>fileRef.current?.click()}><Upload aria-hidden="true"/>{preview?'Değiştir':'Yükle'}</button><button type="button" className={styles.iconButton} disabled={blocked} aria-label="Kapak kütüphanesini aç" aria-expanded={library} aria-controls="collection-cover-library" onClick={()=>void openLibrary()}><ImageIcon aria-hidden="true"/></button>{value||attempt?<button type="button" className={styles.iconButton} aria-label="Kapağı kaldır" disabled={blocked} onClick={()=>{clearAttempt();setError('');callbacks.current.onChange(undefined);}}><Trash2 aria-hidden="true"/></button>:null}</div><span className={styles.helper}>JPG, PNG, WebP · 5 MB</span><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" className={styles.srOnly} tabIndex={-1} aria-label="Kapak görseli dosyası" disabled={blocked} onChange={event=>void select(event.currentTarget.files?.[0])}/>{error?<div className={styles.error} role="alert">{error}{attempt?<button type="button" className={styles.textButton} disabled={busy} onClick={()=>void upload(attempt)}>Tekrar dene</button>:null}</div>:null}{library?<div id="collection-cover-library" className={styles.coverLibrary} onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();setLibrary(false);chooseRef.current?.focus();}}}>{loading?<span className={styles.helper} role="status">Yükleniyor…</span>:assets.length?assets.map(asset=><button key={asset.id} className={styles.coverOption} type="button" aria-label={`${asset.altText||'Koleksiyon'} kapağını seç`} aria-pressed={value===asset.id} disabled={blocked} onClick={()=>{clearAttempt();setError('');callbacks.current.onChange(asset.id,asset.publicUrl);setLibrary(false);chooseRef.current?.focus();}}><img src={asset.publicUrl} alt={asset.altText} loading="lazy"/></button>):<span className={styles.helper}>Kayıtlı kapak yok.</span>}</div>:null}
 {crop?<CollectionDialog title="Kapağı kadrajla" blocked={busy} onClose={closeCrop} footer={<><button className={styles.button} type="button" disabled={busy} onClick={closeCrop}>Vazgeç</button><button type="button" className={styles.primary} disabled={busy} onClick={()=>void applyCrop()}>{busy?'Hazırlanıyor…':'Kapağı kullan'}</button></>}><div className={styles.cropWorkspace}><div className={styles.cropFrame}><img src={crop.url} alt="Kapak kadrajı" style={{width:`${cropW}%`,height:`${cropH}%`,left:`${(100-cropW)*crop.x/100}%`,top:`${(100-cropH)*crop.y/100}%`}}/></div><div className={styles.cropControls}><label>Yakınlaştır<input type="range" min="1" max="3" step="0.05" value={crop.zoom} disabled={busy} onChange={event=>setCrop({...crop,zoom:Number(event.currentTarget.value)})}/></label><label>Yatay<input type="range" min="0" max="100" value={crop.x} disabled={busy} onChange={event=>setCrop({...crop,x:Number(event.currentTarget.value)})}/></label><label>Dikey<input type="range" min="0" max="100" value={crop.y} disabled={busy} onChange={event=>setCrop({...crop,y:Number(event.currentTarget.value)})}/></label></div></div></CollectionDialog>:null}</section>;
}
