'use client';
import { Search } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { collectionsApi, collectionError, collectionConfig, type CollectionMembers, type CollectionOptions } from '@/lib/catalog-collections-ui/client';
import { applySelection, money, type CollectionDraft } from '@/lib/catalog-collections-ui/model';
import { CollectionDialog } from './CollectionDialog';
import { CollectionImage, CollectionPagination, CollectionSkeleton } from './CollectionPrimitives';
import styles from './collections.module.css';
const SIZE=20;
export function CollectionProductPicker({draft,collectionId,options,onClose,onApply}:{draft:CollectionDraft;collectionId?:string;options:CollectionOptions;onClose():void;onApply(ids:readonly string[]):void}){
 const [selected,setSelected]=useState(()=>new Set(draft.productIds));const [search,setSearch]=useState('');const [filters,setFilters]=useState({search:'',categoryId:'',brandId:'',tagId:'',selectedOnly:false,page:1});const [data,setData]=useState<CollectionMembers>();const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [revision,setRevision]=useState(0);const request=useRef(0);const original=useRef(new Set(draft.productIds));const selectedRef=useRef(selected);selectedRef.current=selected;
 useEffect(()=>{const timer=setTimeout(()=>setFilters(current=>({...current,page:1,search:search.trim()})),250);return()=>clearTimeout(timer);},[search]);
 useEffect(()=>{const seq=++request.current;const controller=new AbortController();setLoading(true);setError('');void collectionsApi.members({...(collectionId?{collectionId}:{}),config:collectionConfig({...draft,mode:'manual'}),query:{page:filters.page,pageSize:SIZE,mode:filters.selectedOnly?'members':'catalog',productIds:[...selectedRef.current],...(filters.search?{search:filters.search}:{}),...(filters.categoryId?{categoryId:filters.categoryId}:{}),...(filters.brandId?{brandId:filters.brandId}:{}),...(filters.tagId?{tagId:filters.tagId}:{})}},controller.signal).then(result=>{if(request.current===seq)setData(result);}).catch(caught=>{if(request.current===seq&&!controller.signal.aborted)setError(collectionError(caught));}).finally(()=>{if(request.current===seq)setLoading(false);});return()=>controller.abort();},[filters,revision,collectionId,draft]);
 function toggle(id:string,checked:boolean){setSelected(current=>{const next=new Set(current);if(checked){if(next.size>=10_000){setError('En fazla 10.000 ürün seçebilirsiniz.');return current;}next.add(id);}else next.delete(id);return next;});}
 function selectPage(){const valid=(data?.items??[]).filter(item=>item.status!=='archived'||original.current.has(item.id));const remove=valid.length>0&&valid.every(item=>selected.has(item.id));setSelected(current=>{const next=new Set(current);for(const item of valid){if(remove)next.delete(item.id);else next.add(item.id);}if(next.size>10_000){setError('En fazla 10.000 ürün seçebilirsiniz.');return current;}return next;});}
 const filterOptions=(kind:'categories'|'brands'|'tags',label:string,key:'categoryId'|'brandId'|'tagId')=><label><span className={styles.srOnly}>{label}</span><select className={styles.select} value={filters[key]} onChange={event=>setFilters(current=>({...current,page:1,[key]:event.currentTarget.value}))}><option value="">{label}</option>{options[kind].map(option=><option value={option.id} key={option.id}>{option.name}</option>)}</select></label>;
 return <CollectionDialog title="Ürün ekle" wide onClose={onClose} footer={<><span className={styles.helper} aria-live="polite">{selected.size.toLocaleString('tr-TR')} ürün seçili</span><div><button className={styles.button} type="button" onClick={onClose}>Vazgeç</button><button className={styles.primary} type="button" onClick={()=>onApply(applySelection(draft.productIds,selected))}>Seçimi uygula</button></div></>}><div className={styles.pickerToolbar}><label className={styles.search}><Search aria-hidden="true"/><span className={styles.srOnly}>Katalogda ürün adı veya SKU ara</span><input autoComplete="off" type="search" placeholder="Ürün adı veya SKU" value={search} onChange={event=>setSearch(event.currentTarget.value)}/></label><div className={styles.pickerFilters}>{filterOptions('categories','Tüm kategoriler','categoryId')}{filterOptions('brands','Tüm markalar','brandId')}{filterOptions('tags','Tüm etiketler','tagId')}</div></div><div className={styles.pickerTabs}><div className={styles.tabs} role="group" aria-label="Ürün görünümü"><button type="button" aria-pressed={!filters.selectedOnly} onClick={()=>setFilters(current=>({...current,page:1,selectedOnly:false}))}>Tüm ürünler</button><button type="button" aria-pressed={filters.selectedOnly} onClick={()=>setFilters(current=>({...current,page:1,selectedOnly:true}))}>Seçilenler <span className={styles.count}>{selected.size}</span></button></div><button type="button" className={styles.textButton} disabled={loading||!data?.items.length} onClick={selectPage}>{data?.items.length&&data.items.every(item=>selected.has(item.id))?'Bu sayfanın seçimini kaldır':'Bu sayfayı seç'}</button></div>
 {error?<div className={styles.error} role="alert">{error}<button type="button" className={styles.textButton} onClick={()=>setRevision(value=>value+1)}>Tekrar dene</button></div>:null}{loading?<CollectionSkeleton rows={3}/>:data?.items.length?data.items.map(item=><label key={item.id} className={styles.pickerRow}><input type="checkbox" checked={selected.has(item.id)} disabled={item.status==='archived'&&!original.current.has(item.id)} onChange={event=>toggle(item.id,event.currentTarget.checked)} aria-label={`${item.title} ürününü seç`}/><CollectionImage product url={item.image?.url} alt={item.image?.altText||item.title}/><span className={styles.productCopy}><strong>{item.title}</strong><small>{item.sku||'—'}{item.status==='archived'?' · Arşiv':item.status==='draft'?' · Taslak':''}</small></span><span className={styles.price}>{money(item.priceCents??undefined)}</span></label>):!error?<div className={`${styles.empty} ${styles.compactEmpty}`}><strong>Eşleşen ürün yok</strong><button className={styles.button} type="button" onClick={()=>{setSearch('');setFilters({search:'',categoryId:'',brandId:'',tagId:'',selectedOnly:false,page:1});}}>Filtreleri temizle</button></div>:null}
 {data?<div className={styles.memberFooter}><span>{data.totalCount.toLocaleString('tr-TR')} ürün</span><CollectionPagination page={data.page} pageSize={data.pageSize} total={data.totalCount} busy={loading} onPage={page=>setFilters(current=>({...current,page}))}/></div>:null}</CollectionDialog>;
}
