'use client';
import { ChevronLeft, ChevronRight, Image as ImageIcon } from 'lucide-react';
import { safePublicUrl, statusLabel } from '@/lib/catalog-collections-ui/model';
import styles from './collections.module.css';
export function CollectionStatus({status}:{status:string}){return <span className={styles.status} data-status={status}><i aria-hidden="true"/>{statusLabel(status)}</span>;}
export function CollectionImage({url,alt='',product=false}:{url?:string;alt?:string;product?:boolean}){const safe=safePublicUrl(url);return safe?<img src={safe} alt={alt} className={product?styles.productThumb:styles.coverThumb} loading="lazy" decoding="async"/>:<span className={`${product?styles.productThumb:styles.coverThumb} ${styles.placeholder}`} aria-label="Görsel yok"><ImageIcon aria-hidden="true"/></span>;}
export function CollectionPagination({page,total,pageSize,onPage,busy=false}:{page:number;total:number;pageSize:number;onPage(page:number):void;busy?:boolean}){const pages=Math.max(1,Math.ceil(total/pageSize));return <div className={styles.pagination} aria-label="Sayfalama"><button type="button" className={styles.iconButton} aria-label="Önceki sayfa" disabled={busy||page<=1} onClick={()=>onPage(page-1)}><ChevronLeft aria-hidden="true"/></button><span>{page} / {pages}</span><button type="button" className={styles.iconButton} aria-label="Sonraki sayfa" disabled={busy||page>=pages} onClick={()=>onPage(page+1)}><ChevronRight aria-hidden="true"/></button></div>;}
export function CollectionSkeleton({rows=4}:{rows?:number}){return <div role="status" aria-label="Koleksiyonlar yükleniyor">{Array.from({length:rows},(_,index)=><div key={index} className={styles.skeletonRow}><span className={styles.skeleton}/><span className={styles.skeleton}/></div>)}</div>;}
export function CollectionIllustration(){return <svg viewBox="0 0 160 140" fill="none" aria-hidden="true"><ellipse cx="80" cy="124" rx="55" ry="6" fill="var(--cp-soft)"/><rect x="34" y="30" width="54" height="80" rx="8" fill="var(--cp-surface)" stroke="var(--cp-border)" transform="rotate(-10 34 30)"/><rect x="66" y="20" width="56" height="88" rx="8" fill="var(--cp-surface)" stroke="var(--cp-border)" transform="rotate(10 66 20)"/><rect x="50" y="40" width="60" height="80" rx="8" fill="var(--cp-soft)" stroke="var(--cp-border)"/><path d="M64 65h32M64 77h24M64 100h32" stroke="var(--cp-text-secondary)" strokeWidth="2" strokeLinecap="round"/><path d="M113 39v14m-7-7h14" stroke="var(--cp-brand)" strokeWidth="2" strokeLinecap="round"/></svg>;}
