import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import * as React from 'react';
import { act, createElement } from 'react';
import * as jsxRuntime from 'react/jsx-runtime';
import { Window } from 'happy-dom';
import ts from 'typescript';
import * as model from '../../lib/catalog-collections-ui/model.ts';
import { collectionConfig, collectionFromDetail, CollectionApiError } from '../../lib/catalog-collections-ui/client.ts';
const ID='71000000-0000-4000-8000-000000000001',NOW='2026-09-30T12:00:00.000Z';
const ids=Array.from({length:125},(_,index)=>`72000000-0000-4000-8000-${String(index+1).padStart(12,'0')}`);
const config={schemaVersion:1 as const,mode:'manual' as const,published:false,featured:false,match:'all' as const,rules:[],sort:'custom' as const};
const detail={id:ID,name:'Şehir koleksiyonu',slug:'sehir-koleksiyonu',status:'active' as const,config,productIds:ids,productCount:125,publicProductCount:120,version:7,createdAt:NOW,updatedAt:NOW};
type Api=Record<string,(...args:any[])=>Promise<any>>;
async function mount(verify:(ctx:{container:HTMLElement;browser:Window;settle(ms?:number):Promise<void>;click(text:string):Promise<void>;input(label:string,value:string):Promise<void>;saved:any[];pushes:string[];members:any[]})=>Promise<void>,settings:{api?:Partial<Api>;resourceId?:string|null;canManage?:boolean}={}){
 const browser=new Window({url:'https://panel.example.test/products/collections/'+ID+'/edit'});const navigation=new browser.EventTarget();Object.defineProperty(browser,'navigation',{value:navigation,configurable:true});const old=new Map<string,PropertyDescriptor|undefined>();const saved:any[]=[],pushes:string[]=[],memberCalls:any[]=[];const api={detail:async()=>detail,options:async()=>({categories:[{id:ID,name:'Giyim'}],brands:[{id:ID,name:'Atelier'}],tags:[{id:ID,name:'Yeni sezon'}]}),members:async(input:any)=>{memberCalls.push(input);const order=input.query.mode==='catalog'?ids:input.query.productIds??ids;const visible=order.slice((input.query.page-1)*20,input.query.page*20);return {items:visible.map((id:string,index:number)=>({id,title:`Ürün ${ids.indexOf(id)+1}`,sku:`SKU-${index+1}`,status:'active',priceCents:10000})),page:input.query.page,pageSize:20,totalCount:order.length,orderedIds:order};},save:async(input:any)=>{saved.push(input);throw new CollectionApiError('unavailable',503);},...settings.api};
 for(const [key,value] of Object.entries({window:browser,document:browser.document,navigator:browser.navigator,Element:browser.Element,HTMLElement:browser.HTMLElement,HTMLInputElement:browser.HTMLInputElement,HTMLDialogElement:browser.HTMLDialogElement,Event:browser.Event,MouseEvent:browser.MouseEvent,KeyboardEvent:browser.KeyboardEvent,MutationObserver:browser.MutationObserver,requestAnimationFrame:(callback:FrameRequestCallback)=>setTimeout(()=>callback(0),0),IS_REACT_ACT_ENVIRONMENT:true})){old.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{configurable:true,writable:true,value});}
 const cache=new Map<string,unknown>();const style=new Proxy({},{get:(_target,key)=>key==='__esModule'?true:key==='default'?style:String(key)});const files=['CollectionEditor','CollectionPrimitives','CollectionDialog','CollectionProductPicker'];const sources=new Map(await Promise.all(files.map(async file=>[file,await readFile(new URL(`./${file}.tsx`,import.meta.url),'utf8')] as const)));
 function load(file:string):unknown{if(cache.has(file))return cache.get(file);const compiled={exports:{} as Record<string,unknown>};cache.set(file,compiled.exports);const source=sources.get(file);if(!source)throw new Error(file);const output=ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;Function('require','module','exports',output)((name:string)=>{if(name==='react')return React;if(name==='react/jsx-runtime')return jsxRuntime;if(name==='next/navigation')return {useRouter:()=>({push:(path:string)=>pushes.push(path),refresh:()=>{}})};if(name==='next/link')return ({href,children,...props}:any)=>createElement('a',{href,...props},children);if(name==='lucide-react')return new Proxy({},{get:()=>()=>null});if(name.endsWith('.module.css'))return style;if(name==='@/components/panel/PanelPageShell')return {PanelPageShell:({children}:any)=>children,PanelPageHeader:()=>null};if(name==='@/lib/catalog-collections-ui/model')return model;if(name==='@/lib/catalog-collections-ui/client')return {collectionsApi:api,collectionConfig,collectionFromDetail,collectionError:(error:any)=>error?.message??'İşlem tamamlanamadı',CollectionApiError};if(name==='./CollectionMediaField')return {CollectionMediaField:()=>null};if(name.startsWith('./'))return load(name.slice(2));throw new Error(`unexpected:${name}`);},compiled,compiled.exports);cache.set(file,compiled.exports);return compiled.exports;}
 const Editor=(load('CollectionEditor') as any).CollectionEditor;const {createRoot}=await import('react-dom/client');const container=browser.document.createElement('div');browser.document.body.append(container);const root=createRoot(container as unknown as HTMLElement);const settle=async(ms=250)=>{await act(async()=>{await new Promise(resolve=>setTimeout(resolve,ms));});};const click=async(text:string)=>{const button=[...container.querySelectorAll('button')].find(button=>button.textContent?.trim()===text||button.getAttribute('aria-label')===text);assert.ok(button,`button:${text}`);await act(async()=>button.click());await settle();};const input=async(label:string,value:string)=>{const field=[...container.querySelectorAll('label')].find(item=>item.textContent?.trim().startsWith(label))?.querySelector('input,textarea,select') as unknown as HTMLInputElement;assert.ok(field,`field:${label}`);await act(async()=>{const constructor=field.tagName==='TEXTAREA'?browser.HTMLTextAreaElement:field.tagName==='SELECT'?browser.HTMLSelectElement:browser.HTMLInputElement;Object.getOwnPropertyDescriptor(constructor.prototype,'value')?.set?.call(field,value);field.dispatchEvent(new browser.Event(field.tagName==='SELECT'?'change':'input',{bubbles:true}) as unknown as Event);});await settle();};
 try{await act(async()=>{root.render(createElement(Editor,{resourceId:settings.resourceId===null?undefined:settings.resourceId??ID,canManage:settings.canManage??true}));});await settle();await settle();await verify({container:container as unknown as HTMLElement,browser,settle,click,input,saved,pushes,members:memberCalls});}finally{await act(async()=>root.unmount());for(const [key,value]of old)value?Object.defineProperty(globalThis,key,value):Reflect.deleteProperty(globalThis,key);await browser.happyDOM.close();}
}

test('save retains all 125 IDs while only the first 20 rows are loaded and errors preserve name/version',async()=>mount(async({container,input,click,saved,pushes})=>{assert.equal(container.querySelectorAll('[data-product-id]').length,20);await input('Koleksiyon adı','Yeni isim');await click('Kaydet');assert.equal(saved.length,1);assert.equal(saved[0].name,'Yeni isim');assert.equal(saved[0].config.published,true);assert.equal(saved[0].expectedVersion,7);assert.deepEqual(saved[0].productIds,ids);assert.equal((container.querySelector('input[required]')as HTMLInputElement).value,'Yeni isim');assert.deepEqual(pushes,[]);assert.match(container.textContent??'',/Koleksiyon hizmeti şu anda/);}));
test('move to first from page 2 preserves full canonical order and unseen product links',async()=>mount(async({container,click,settle,saved,input})=>{await click('Sonraki sayfa');await click('Ürün 21 başa taşı');await settle();await input('Koleksiyon adı','Sıralanan koleksiyon');await click('Kaydet');assert.deepEqual(saved[0].productIds,[ids[20],...ids.slice(0,20),...ids.slice(21)]);assert.match(container.textContent??'',/1\. sıraya taşındı/);}));
test('dirty navigation offers discard, Escape restores focus, and unload protection remains',async()=>mount(async({container,browser,input,click,pushes})=>{await input('Koleksiyon adı','Kirli');const event=new browser.Event('beforeunload',{cancelable:true});browser.dispatchEvent(event);assert.equal(event.defaultPrevented,true);await click('Koleksiyonlara dön');assert.ok(container.querySelector('dialog[open]'));await click('Düzenlemeye devam et');assert.equal(container.querySelector('dialog[open]'),null);assert.deepEqual(pushes,[]);await click('Koleksiyonlara dön');await click('Kaydetmeden ayrıl');assert.deepEqual(pushes,['/products/collections']);}));
test('version conflicts retain input, stop repeated saves, and require explicit reload',async()=>{let calls=0;await mount(async({container,input,click})=>{await input('Koleksiyon adı','Korunacak isim');await click('Kaydet');assert.match(container.textContent??'',/başka bir kullanıcı/);assert.equal((container.querySelector('input[required]')as HTMLInputElement).value,'Korunacak isim');const save=[...container.querySelectorAll('button')].find(button=>button.textContent==='Kaydet');assert.equal(save?.disabled,true);assert.equal(calls,1);},{api:{save:async()=>{calls++;throw new CollectionApiError('version_conflict',409);}}});});
test('existing type is immutable and read-only access cannot save, select, remove or reorder',async()=>mount(async({container,saved})=>{assert.equal(container.querySelector('[aria-label="Koleksiyon türü"]'),null);assert.equal([...container.querySelectorAll('button')].some(button=>button.textContent==='Kaydet'),false);assert.equal([...container.querySelectorAll('button')].some(button=>button.textContent?.includes('Ürün ekle')),false);assert.ok([...container.querySelectorAll('[aria-label*="başa taşı"]')].every(button=>(button as HTMLButtonElement).disabled));assert.deepEqual(saved,[]);},{canManage:false}));
test('new automatic collections publish on save, reject incomplete rules, preview completed rules and enforce ten-rule limit',async()=>mount(async({container,click,input,members,saved})=>{await click('Otomatik');await input('Koleksiyon adı','Yeni otomatik');await click('Kaydet');assert.match(container.textContent??'',/tamamlanmış koşul/);assert.equal(saved.length,0);const select=container.querySelector('[data-rules] .ruleRow label:nth-child(2) select')as HTMLSelectElement;await act(async()=>{Object.getOwnPropertyDescriptor((globalThis.window as any).HTMLSelectElement.prototype,'value')?.set?.call(select,ID);select.dispatchEvent(new (globalThis.window as any).Event('change',{bubbles:true}));});await act(async()=>{await new Promise(resolve=>setTimeout(resolve,250));});await click('Kaydet');assert.equal(saved[0].config.mode,'automatic');assert.equal(saved[0].config.published,true);assert.deepEqual(saved[0].config.rules,[{kind:'category',resourceId:ID}]);assert.ok(members.some(input=>input.config.mode==='automatic'));for(let i=1;i<10;i++)await click('Koşul ekle');assert.equal([...container.querySelectorAll('button')].find(button=>button.textContent?.includes('Koşul ekle'))?.disabled,true);},{resourceId:null}));

test('same-document browser back is canceled before navigation and requires discard confirmation',async()=>mount(async({container,browser,input,click,pushes})=>{await input('Koleksiyon adı','Korunan değişiklik');const event=new browser.Event('navigate',{cancelable:true});Object.assign(event,{navigationType:'traverse',destination:{url:'https://panel.example.test/products/collections',sameDocument:true}});await act(async()=>{(browser as any).navigation.dispatchEvent(event);});assert.equal(event.defaultPrevented,true);assert.ok(container.querySelector('dialog[open]'));assert.equal((container.querySelector('input[required]')as HTMLInputElement).value,'Korunan değişiklik');await click('Düzenlemeye devam et');assert.deepEqual(pushes,[]);const safe=new browser.Event('navigate',{cancelable:true});Object.assign(safe,{navigationType:'traverse',destination:{url:browser.location.href,sameDocument:true}});(browser as any).navigation.dispatchEvent(safe);assert.equal(safe.defaultPrevented,false);}));

test('product picker preserves choices across server pages and applies only the explicit selection',async()=>mount(async({container,browser,click,settle,input,saved})=>{await click('Ürün ekle');const dialog=()=>container.querySelector('dialog[open]')!;const first=dialog().querySelector('[aria-label="Ürün 1 ürününü seç"]')as HTMLInputElement;assert.ok(first);await act(async()=>first.click());await settle();const next=dialog().querySelector('[aria-label="Sonraki sayfa"]')as HTMLButtonElement;await act(async()=>next.click());await settle();const other=dialog().querySelector('[aria-label="Ürün 21 ürününü seç"]')as HTMLInputElement;assert.ok(other);await act(async()=>other.click());await settle();assert.match(dialog().textContent??'',/2 ürün seçili/);const apply=[...dialog().querySelectorAll('button')].find(button=>button.textContent==='Seçimi uygula')!;await act(async()=>apply.click());await settle();assert.equal(container.querySelector('dialog[open]'),null);await input('Koleksiyon adı','İki seçim');await click('Kaydet');assert.deepEqual(saved[0].productIds,[ids[0],ids[20]]);},{resourceId:null}));

test('retrying an uncertain save reuses its operation identity while a changed draft gets a new one',async()=>{const operations:string[]=[];await mount(async({input,click})=>{await input('Koleksiyon adı','Tekrar');await click('Kaydet');await click('Kaydet');assert.equal(operations[0],operations[1]);await input('Koleksiyon adı','Değişti');await click('Kaydet');assert.notEqual(operations[1],operations[2]);},{api:{save:async(_input:any,operation:string)=>{operations.push(operation);throw new CollectionApiError('unavailable',503);}}});});

test('explicit collection hiding is saved without a second publication action',async()=>mount(async({container,input,click,saved,browser})=>{const visibility=[...container.querySelectorAll('label')].find(label=>label.textContent==='Mağazada göster')?.querySelector('input') as HTMLInputElement;assert.equal(visibility.checked,true);await act(async()=>visibility.click());await input('Koleksiyon adı','Gizli koleksiyon');await click('Kaydet');assert.equal(saved[0].config.published,false);}));
