import assert from'node:assert/strict';
import test from'node:test';
import{createContentResourceAuthoringHttpHandlers}from'./handler.ts';
const id='11111111-1111-4111-8111-111111111111',cookie=`v1.panel.current.${Buffer.alloc(32,1).toString('base64url')}`;
const requestBody={target:{kind:'page',draftId:id,recordId:null,recordVersion:null},currentDraft:{name:'Page',slug:'page',locale:'tr',body:'',excerpt:null,seoTitle:null,seoDescription:null,published:false,status:'draft'},locale:'tr',tone:'neutral',length:'short',note:'',researchOperationId:null,stage:'outline',topic:'Konu',purpose:'Özet'};
const generation={id,target:requestBody.target,stage:'outline',status:'completed',outline:{title:'Konu',sections:[{heading:'Giriş',points:[]}]},draft:null,sourceFingerprint:'a'.repeat(64),usage:null,safeCode:null,createdAt:'2026-09-29T00:00:00.000Z',updatedAt:'2026-09-29T00:00:00.000Z',finishedAt:'2026-09-29T00:00:01.000Z',provider:'secret-value'};
function request(body:unknown=requestBody,headers:HeadersInit={},get=false){return new Request(`http://customer-panel:3400/api/content-resource-authoring${get?'/'+id:''}`,{method:get?'GET':'POST',headers:{cookie:`__Host-celebix_panel=${cookie}`,origin:'https://fixture.admin.saas-staging.celebix.site','content-type':'application/json','idempotency-key':id,...Object.fromEntries(new Headers(headers))},...(get?{}:{body:JSON.stringify(body)})});}
function fixture(enabled=true){let calls=0;const handler=createContentResourceAuthoringHttpHandlers({resolveRuntime:async()=>({access:{panelOrigin:'https://panel.saas-staging.celebix.site',resolveCredential:async()=>({kind:'authenticated',tenantContext:{store:{id,slug:'fixture',status:'active'},membership:{status:'active',role:'editor'}}})},enabled:()=>enabled,service:{generateContent:async()=>{calls++;return generation;},getGeneration:async()=>{calls++;return generation;}}}as any),now:()=>new Date('2026-09-29T00:00:00.000Z'),requestId:()=>id});return{handler,count:()=>calls};}
test('resource HTTP uses current tenant authority and returns a strict no-store projection',async()=>{const f=fixture();const result=await f.handler.post(request());assert.equal(result.status,200);assert.equal(result.headers.get('cache-control'),'no-store');const body=await result.json();assert.equal(body.generation.provider,undefined);assert.equal(body.generation.id,id);assert.equal(f.count(),1);});
test('resource HTTP rejects feature-off, forged fields and cross-origin posts before generation',async()=>{for(const [enabled,body,headers,status]of[[false,requestBody,{},503],[true,{...requestBody,storeId:id},{},400],[true,requestBody,{origin:'https://evil.example'},403]]as const){const f=fixture(enabled);const response=await f.handler.post(request(body,headers));assert.equal(response.status,status);assert.equal(f.count(),0);}});
test('resource GET is bound to own session and feature flag',async()=>{const f=fixture();assert.equal((await f.handler.get(request(undefined,{},true),{params:Promise.resolve({operationId:id})})).status,200);const off=fixture(false);assert.equal((await off.handler.get(request(undefined,{},true),{params:Promise.resolve({operationId:id})})).status,503);});
