import assert from 'node:assert/strict';import test from 'node:test';import {readFile} from 'node:fs/promises';import {Window} from 'happy-dom';import React,{createElement} from 'react';import * as jsx from 'react/jsx-runtime';import ts from 'typescript';import * as model from '../../lib/seo-ui/model.ts';import {SeoApiError} from '../../lib/seo-ui/client.ts';
test('links select real kinds and names, prevent self links, and apply an explicit versioned request',async()=>{
 const browser=new Window({url:'https://panel.test/seo?tab=links'}),prior=new Map<string,PropertyDescriptor|undefined>();for(const[key,value]of Object.entries({window:browser,document:browser.document,navigator:browser.navigator,HTMLElement:browser.HTMLElement,HTMLInputElement:browser.HTMLInputElement,Event:browser.Event,IS_REACT_ACT_ENVIRONMENT:true})){prior.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{configurable:true,writable:true,value});}
 const sourceResource={id:'11111111-1111-4111-8111-111111111111',kind:'category',name:'Altın yüzükler',path:'/kategori/yuzukler'},targetResource={id:'22222222-2222-4222-8222-222222222222',kind:'blog',name:'Yüzük bakım rehberi',path:'/blog/bakim'};const writes:any[]=[];let self=true;
 const client={links:async()=>({items:[]}),resources:async()=>({items:[],nextCursor:null,total:0}),saveLink:async(payload:any,key:string)=>{writes.push({payload,key});return{link:payload,replayed:false};}};
 const source=await readFile(new URL('./SeoOverview.tsx',import.meta.url),'utf8'),code=ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,compiled={exports:{}as Record<string,unknown>};
 Function('require','module','exports',code)((name:string)=>{if(name==='react')return React;if(name==='react/jsx-runtime')return jsx;if(name==='next/link')return({children,href}:any)=>createElement('a',{href},children);if(name.includes('seo-ui/client'))return{seoClient:client,SeoApiError};if(name.includes('seo-ui/model'))return model;if(name.includes('SeoShared'))return{SeoFeedback:({error,message}:any)=>createElement('div',null,error,message),ResourcePicker:({label,value,onChange}:any)=>createElement('button',{type:'button',onClick:()=>onChange(label==='Kaynak'||self?sourceResource:targetResource)},`${label} seç${value?' · '+value.name:''}`)};if(name.includes('OrderActionDialog'))return{OrderActionDialog:({open,children,footer}:any)=>open?createElement('div',{role:'dialog'},children,footer):null};if(name.endsWith('.css'))return{};throw Error(name);},compiled,compiled.exports);
 const{createRoot}=await import('react-dom/client');const container=browser.document.createElement('div')as unknown as HTMLElement;browser.document.body.append(container as never);const root=createRoot(container);const click=async(label:string)=>{const button=[...container.querySelectorAll('button')].find(item=>item.textContent?.startsWith(label));assert.ok(button,label);await React.act(async()=>button.click());};
 try{await React.act(async()=>root.render(createElement(compiled.exports.SeoLinks as React.ComponentType<any>,{canManage:true,client})));await click('Bağlantı ekle');await click('Kaynak seç');await click('Hedef seç');const input=container.querySelector('input:not([type="checkbox"])')as HTMLInputElement;await React.act(async()=>{Object.getOwnPropertyDescriptor(browser.HTMLInputElement.prototype,'value')!.set!.call(input,'Bakım rehberi');input.dispatchEvent(new browser.Event('input',{bubbles:true})as unknown as Event);});assert.match(container.textContent??'',/Altın yüzükler/);await React.act(async()=>container.querySelector('form')!.dispatchEvent(new browser.SubmitEvent('submit',{bubbles:true,cancelable:true})as unknown as Event));assert.equal(writes.length,0,'self link form submission must not call the server');self=false;await click('Hedef seç');await click('Uygula');assert.equal(writes.length,1);assert.equal(writes[0].payload.sourceKind,'category');assert.equal(writes[0].payload.sourceId,sourceResource.id);assert.equal(writes[0].payload.targetKind,'blog');assert.equal(writes[0].payload.targetId,targetResource.id);assert.equal(writes[0].payload.expectedVersion,null);assert.equal(writes[0].payload.anchorText,'Bakım rehberi');assert.equal(writes[0].payload.sourcePath,undefined);}finally{await React.act(async()=>root.unmount());for(const[key,value]of prior)value?Object.defineProperty(globalThis,key,value):Reflect.deleteProperty(globalThis,key);await browser.happyDOM.close();}
});
