import assert from 'node:assert/strict';import test from 'node:test';import {readFile} from 'node:fs/promises';import {Window} from 'happy-dom';import React,{createElement} from 'react';import * as jsx from 'react/jsx-runtime';import * as lucide from 'lucide-react';import ts from 'typescript';import * as model from '../../lib/seo-ui/model.ts';import {SeoApiError} from '../../lib/seo-ui/client.ts';
test("overview displays checked URL count and actionable issues; scans begin only on explicit click",async()=>{
 const browser=new Window({url:'https://panel.test/seo'}),prior=new Map<string,PropertyDescriptor|undefined>();for(const[key,value]of Object.entries({window:browser,document:browser.document,navigator:browser.navigator,HTMLElement:browser.HTMLElement,Event:browser.Event,IS_REACT_ACT_ENVIRONMENT:true})){prior.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{configurable:true,writable:true,value});}
 let starts=0;const overview={totalResources:12,publishedResources:10,issues:[{code:'missing_title',severity:'warning',message:'Başlık eksik',path:'/products/ring',kind:'product',resourceId:'11111111-1111-4111-8111-111111111111',fixHref:'/seo/content?kind=product'}],sitemap:{url:'https://store.test/sitemap.xml',robotsUrl:'https://store.test/robots.txt',entryCount:10},check:{checked:3,total:10,status:'completed',lastCheckedAt:null},notifications:[],settings:{eligible:true,indexNowEnabled:false,hostname:'store.test' as string|null}};
 const client={overview:async()=>({...overview,issues:[...overview.issues],settings:{...overview.settings}}),startCheck:async()=>{starts++;return{checked:0,total:10,status:'running',replayed:false};}};
 const source=await readFile(new URL('./SeoOverview.tsx',import.meta.url),'utf8'),code=ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,compiled={exports:{}as Record<string,unknown>};
 Function('require','module','exports',code)((name:string)=>{if(name==='react')return React;if(name==='react/jsx-runtime')return jsx;if(name==='lucide-react')return lucide;if(name==='next/link')return({children,href}:any)=>createElement('a',{href},children);if(name.includes('seo-ui/client'))return{seoClient:client,SeoApiError};if(name.includes('seo-ui/model'))return model;if(name.includes('SeoShared'))return{SeoFrame:({children}:any)=>createElement('section',null,children),SeoFeedback:({error,message}:any)=>createElement('div',null,error,message),ResourcePicker:()=>null,SeoArtwork:()=>null,SeoResourceThumb:()=>null,SeoLoading:({label}:any)=>createElement('p',{role:'status'},label)};if(name.includes('OrderActionDialog'))return{OrderActionDialog:()=>null};if(name.endsWith('.css'))return{};throw Error(name);},compiled,compiled.exports);
 const{createRoot}=await import('react-dom/client');const container=browser.document.createElement('div')as unknown as HTMLElement;browser.document.body.append(container as never);const root=createRoot(container);
 try{await React.act(async()=>root.render(createElement(compiled.exports.SeoOverview as React.ComponentType<any>,{canManage:true,client,initialTab:'checks'})));assert.equal(starts,0);assert.match(container.textContent??'',/3\s*\/\s*10/);assert.match(container.textContent??'',/Başlık eksik/);assert.ok(container.querySelector('a[href="/seo/content?kind=product"]'));const pageLink=container.querySelector('a[href="https://store.test/products/ring"]');assert.equal(pageLink?.textContent,'Sayfayı aç');assert.equal(pageLink?.getAttribute('target'),'_blank');assert.equal(pageLink?.getAttribute('rel'),'noreferrer');const refresh=[...container.querySelectorAll('button')].find(item=>item.textContent==='Yenile');assert.ok(refresh);for(const path of ['//evil.test/ring','https://evil.test/ring','/\\evil.test/ring','relative-path','/products\n/ring']){overview.issues[0]!.path=path;await React.act(async()=>refresh.click());assert.equal([...container.querySelectorAll('a')].some(link=>link.textContent==='Sayfayı aç'),false,`unsafe path ${path} has no storefront link`);}overview.issues[0]!.path='/products/ring';overview.settings.hostname=null;await React.act(async()=>refresh.click());assert.equal([...container.querySelectorAll('a')].some(link=>link.textContent==='Sayfayı aç'),false,'unknown storefront hostname has no link');overview.settings.hostname='store.test';overview.issues=Array.from({length:200},()=>({...overview.issues[0]!}));await React.act(async()=>refresh.click());assert.match(container.textContent??'',/Gösterilen konu/);assert.match(container.textContent??'',/Öncelikli 200 konu gösteriliyor/);assert.ok(container.querySelector('a[href="/seo/content?missing=1"]'));const button=[...container.querySelectorAll('button')].find(item=>item.textContent==='Kontrolü başlat');assert.ok(button);await React.act(async()=>button.click());assert.equal(starts,1);assert.doesNotMatch(container.textContent??'',/sağlık puanı|Google.*indekslendi/i);}finally{await React.act(async()=>root.unmount());for(const[key,value]of prior)value?Object.defineProperty(globalThis,key,value):Reflect.deleteProperty(globalThis,key);await browser.happyDOM.close();}
});

async function overviewHarness(client:any,initialTab='checks',canManage=true){
 const browser=new Window({url:'https://panel.test/seo'}),prior=new Map<string,PropertyDescriptor|undefined>();
 for(const[key,value]of Object.entries({window:browser,document:browser.document,navigator:browser.navigator,HTMLElement:browser.HTMLElement,HTMLInputElement:browser.HTMLInputElement,HTMLSelectElement:browser.HTMLSelectElement,Event:browser.Event,IS_REACT_ACT_ENVIRONMENT:true})){prior.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{configurable:true,writable:true,value});}
 const source=await readFile(new URL('./SeoOverview.tsx',import.meta.url),'utf8'),code=ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,compiled={exports:{}as Record<string,unknown>};
 Function('require','module','exports',code)((name:string)=>{if(name==='react')return React;if(name==='react/jsx-runtime')return jsx;if(name==='lucide-react')return lucide;if(name==='next/link')return({children,...props}:any)=>createElement('a',props,children);if(name.includes('seo-ui/client'))return{seoClient:client,SeoApiError};if(name.includes('seo-ui/model'))return model;if(name.includes('SeoShared'))return{SeoFrame:({children}:any)=>createElement('section',null,children),SeoFeedback:({error,message}:any)=>createElement('div',null,error,message),SeoArtwork:()=>null,SeoResourceThumb:()=>null,SeoLoading:({label}:any)=>createElement('p',{role:'status'},label),ResourcePicker:()=>null};if(name.includes('OrderActionDialog'))return{OrderActionDialog:()=>null};if(name.endsWith('.css'))return{};throw Error(name);},compiled,compiled.exports);
 const{createRoot}=await import('react-dom/client');const container=browser.document.createElement('div')as unknown as HTMLElement;browser.document.body.append(container as never);const root=createRoot(container);
 await React.act(async()=>root.render(createElement(compiled.exports.SeoOverview as React.ComponentType<any>,{client,initialTab,canManage})));
 return{browser,container,async click(label:string){const button=[...container.querySelectorAll('button')].find(item=>item.textContent===label||item.getAttribute('aria-label')===label);assert.ok(button,label);await React.act(async()=>button.click());},async wait(){await React.act(async()=>{await new Promise(resolve=>setTimeout(resolve,240));});},async cleanup(){await React.act(async()=>root.unmount());for(const[key,value]of prior)value?Object.defineProperty(globalThis,key,value):Reflect.deleteProperty(globalThis,key);await browser.happyDOM.close();}};
}
function visualOverview(issues:any[]=[]){return{totalResources:12,publishedResources:8,issues,sitemap:{url:null,robotsUrl:null,entryCount:0},check:{checked:3,total:10,status:'completed',lastCheckedAt:null},notifications:[],settings:{eligible:true,indexNowEnabled:true,allowIndex:true,hostname:'store.test'}};}
function notificationResource(id:string,kind='product',allowIndex=true){return{id,kind,name:`İçerik ${id.slice(-2)}`,path:`/products/item-${id.slice(-2)}`,allowIndex,imageUrl:null};}
test('issue charts filter displayed findings without claiming a health score or unique affected resources',async()=>{
 const issues=[{code:'missing_title',severity:'warning',message:'Başlık eksik',path:'/products/ring',kind:'product',resourceId:'a',fixHref:'/seo/content?kind=product'},{code:'broken_link',severity:'error',message:'Bağlantı erişilemiyor',path:'/products/ring',kind:'product',resourceId:'a',fixHref:'/seo?tab=links'}];
 const h=await overviewHarness({overview:async()=>visualOverview(issues)});
 try{assert.ok(h.container.querySelector('[role="img"][aria-label="Yayın kapsamı: 8 yayında, 4 taslak veya kapalı, 12 toplam içerik"]'));await h.click('Hata');assert.match(h.container.textContent??'',/Bağlantı erişilemiyor/);assert.doesNotMatch(h.container.textContent??'',/Başlık eksik/);await h.click('Tümü');assert.match(h.container.textContent??'',/Başlık eksik/);assert.doesNotMatch(h.container.textContent??'',/sağlık puanı|Google.*indekslendi/i);}finally{await h.cleanup();}
});
test('notification resource pages preserve selections across kinds and retry with the same idempotency identity',async()=>{
 const first=notificationResource('11111111-1111-4111-8111-111111111111'),second=notificationResource('22222222-2222-4222-8222-222222222222'),category=notificationResource('33333333-3333-4333-8333-333333333333','category'),blocked=notificationResource('44444444-4444-4444-8444-444444444444','category',false),requests:any[]=[],writes:any[]=[];
 const client={overview:async()=>visualOverview(),resources:async(input:any)=>{requests.push(input);return input.kind==='category'?{items:[category,blocked],nextCursor:null,total:2}:input.cursor?{items:[second],nextCursor:null,total:2}:{items:[first],nextCursor:'page-2',total:2};},notify:async(payload:any,key:string)=>{writes.push({payload,key});if(writes.length===1)throw new SeoApiError('commit_unknown',503);return{queued:3,replayed:true};}};
 const h=await overviewHarness(client,'notifications');
 const pick=async(id:string)=>{const input=h.container.querySelector(`input[data-resource-id="${id}"]`)as HTMLInputElement;assert.ok(input,id);await React.act(async()=>input.click());};
 try{await h.wait();await pick(first.id);await h.click('Sonraki içerikler');await h.wait();await pick(second.id);const select=h.container.querySelector('select[aria-label="Bildirilecek içerik türü"]')as HTMLSelectElement;assert.ok(select);await React.act(async()=>{select.value='category';select.dispatchEvent(new h.browser.Event('change',{bubbles:true})as unknown as Event);});await h.wait();await pick(category.id);assert.equal((h.container.querySelector(`input[data-resource-id="${blocked.id}"]`)as HTMLInputElement).disabled,true);await h.click('3 URL bildir');assert.match(h.container.textContent??'',/İşlem sonucu doğrulanamadı/);await h.click('3 URL bildir');assert.equal(writes.length,2);assert.deepEqual(writes[0].payload,writes[1].payload);assert.equal(writes[0].key,writes[1].key);assert.deepEqual(writes[0].payload.resources,[{kind:'product',id:first.id},{kind:'product',id:second.id},{kind:'category',id:category.id}]);assert.ok(requests.some(r=>r.cursor==='page-2'));assert.match(h.container.textContent??'',/0 seçili/);}finally{await h.cleanup();}
});
test('notification history can reach later events and domain eligibility blocks sending',async()=>{
 const data={...visualOverview(),settings:{...visualOverview().settings,eligible:false},notifications:Array.from({length:13},(_,i)=>({id:String(i),path:`/products/event-${i}`,status:i===12?'failed':'received',httpStatus:i===12?503:200,attempts:1,requestedAt:'2026-09-30T12:00:00Z',nextAttemptAt:null,error:null}))};
 const h=await overviewHarness({overview:async()=>data,resources:async()=>({items:[],nextCursor:null,total:0})},'notifications');
 try{await h.wait();assert.match(h.container.textContent??'',/birincil özel alan adı/);await h.click('Sonraki bildirimler');assert.match(h.container.textContent??'',/event-12/);assert.match(h.container.textContent??'',/HTTP 503/);const submit=[...h.container.querySelectorAll('button')].find(b=>/URL bildir/.test(b.textContent??''));assert.ok(submit?.disabled);}finally{await h.cleanup();}
});

test('running checks recover after failed polling with bounded delays and stop after completion',async()=>{
 const browser=new Window({url:'https://panel.test/seo'}),prior=new Map<string,PropertyDescriptor|undefined>();
 for(const[key,value]of Object.entries({window:browser,document:browser.document,navigator:browser.navigator,HTMLElement:browser.HTMLElement,Event:browser.Event,IS_REACT_ACT_ENVIRONMENT:true})){prior.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{configurable:true,writable:true,value});}
 const originalTimeout=globalThis.setTimeout,originalClear=globalThis.clearTimeout,timers=new Map<number,{callback:()=>Promise<void>|void;delay:number}>();let nextTimer=1000,calls=0;
 globalThis.setTimeout=((callback:()=>Promise<void>|void,delay:number,...args:unknown[])=>{if(delay>=5000){const id=nextTimer++;timers.set(id,{callback,delay});return id;}return originalTimeout(callback,delay,...args);})as typeof setTimeout;
 globalThis.clearTimeout=((id:any)=>{if(timers.delete(id))return;originalClear(id);})as typeof clearTimeout;
 const overview={totalResources:10,publishedResources:10,issues:[],sitemap:{url:null,robotsUrl:null,entryCount:10},check:{checked:3,total:10,status:'running',lastCheckedAt:null},notifications:[],settings:{eligible:true,indexNowEnabled:false}};
 const client={overview:async()=>{calls++;if(calls>=2&&calls<=5)throw new SeoApiError('unavailable',503);return calls===6?{...overview,check:{...overview.check,checked:10,status:'completed'}}:overview;}};
 const source=await readFile(new URL('./SeoOverview.tsx',import.meta.url),'utf8'),code=ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,compiled={exports:{}as Record<string,unknown>};
 Function('require','module','exports',code)((name:string)=>{if(name==='react')return React;if(name==='react/jsx-runtime')return jsx;if(name==='lucide-react')return lucide;if(name==='next/link')return({children,href}:any)=>createElement('a',{href},children);if(name.includes('seo-ui/client'))return{seoClient:client,SeoApiError};if(name.includes('seo-ui/model'))return model;if(name.includes('SeoShared'))return{SeoFrame:({children}:any)=>createElement('section',null,children),SeoFeedback:({error,message}:any)=>createElement('div',null,error,message),ResourcePicker:()=>null,SeoArtwork:()=>null,SeoResourceThumb:()=>null,SeoLoading:({label}:any)=>createElement('p',{role:'status'},label)};if(name.includes('OrderActionDialog'))return{OrderActionDialog:()=>null};if(name.endsWith('.css'))return{};throw Error(name);},compiled,compiled.exports);
 const{createRoot}=await import('react-dom/client');const container=browser.document.createElement('div')as unknown as HTMLElement;browser.document.body.append(container as never);const root=createRoot(container);
 const tick=async(expectedDelay:number)=>{assert.equal(timers.size,1,'exactly one pending poll');const[id,timer]=[...timers][0]!;assert.equal(timer.delay,expectedDelay);timers.delete(id);await React.act(async()=>{await timer.callback();});};
 try{
  await React.act(async()=>root.render(createElement(compiled.exports.SeoOverview as React.ComponentType<any>,{canManage:true,client,initialTab:'checks'})));
  await tick(5000);assert.equal(calls,2);assert.match(container.textContent??'',/3\s*\/\s*10/);assert.match(container.textContent??'',/yeniden deneyin/i);
  await tick(10000);await tick(20000);await tick(30000);await tick(30000);
  assert.equal(calls,6);assert.match(container.textContent??'',/10\s*\/\s*10/);assert.match(container.textContent??'',/Kontrol tamamlandı/);assert.doesNotMatch(container.textContent??'',/şu anda yüklenemiyor/);assert.equal(timers.size,0,'completed checks cancel the polling timer');
 }finally{await React.act(async()=>root.unmount());globalThis.setTimeout=originalTimeout;globalThis.clearTimeout=originalClear;for(const[key,value]of prior)value?Object.defineProperty(globalThis,key,value):Reflect.deleteProperty(globalThis,key);await browser.happyDOM.close();}
});
