import assert from 'node:assert/strict';import test from 'node:test';import {readFile} from 'node:fs/promises';import {Window} from 'happy-dom';import React,{createElement} from 'react';import * as jsx from 'react/jsx-runtime';import ts from 'typescript';import * as model from '../../lib/seo-ui/model.ts';import {SeoApiError} from '../../lib/seo-ui/client.ts';
test("overview displays checked URL count and actionable issues; scans begin only on explicit click",async()=>{
 const browser=new Window({url:'https://panel.test/seo'}),prior=new Map<string,PropertyDescriptor|undefined>();for(const[key,value]of Object.entries({window:browser,document:browser.document,navigator:browser.navigator,HTMLElement:browser.HTMLElement,Event:browser.Event,IS_REACT_ACT_ENVIRONMENT:true})){prior.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{configurable:true,writable:true,value});}
 let starts=0;const overview={totalResources:12,publishedResources:10,issues:[{code:'missing_title',severity:'warning',message:'Başlık eksik',path:'/products/ring',kind:'product',resourceId:'11111111-1111-4111-8111-111111111111',fixHref:'/seo/content?kind=product'}],sitemap:{url:'https://store.test/sitemap.xml',robotsUrl:'https://store.test/robots.txt',entryCount:10},check:{checked:3,total:10,status:'completed',lastCheckedAt:null},notifications:[],settings:{eligible:true,indexNowEnabled:false}};
 const client={overview:async()=>overview,startCheck:async()=>{starts++;return{checked:0,total:10,status:'running',replayed:false};}};
 const source=await readFile(new URL('./SeoOverview.tsx',import.meta.url),'utf8'),code=ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,compiled={exports:{}as Record<string,unknown>};
 Function('require','module','exports',code)((name:string)=>{if(name==='react')return React;if(name==='react/jsx-runtime')return jsx;if(name==='next/link')return({children,href}:any)=>createElement('a',{href},children);if(name.includes('seo-ui/client'))return{seoClient:client,SeoApiError};if(name.includes('seo-ui/model'))return model;if(name.includes('SeoShared'))return{SeoFrame:({children}:any)=>createElement('section',null,children),SeoFeedback:({error,message}:any)=>createElement('div',null,error,message),ResourcePicker:()=>null};if(name.includes('OrderActionDialog'))return{OrderActionDialog:()=>null};if(name.endsWith('.css'))return{};throw Error(name);},compiled,compiled.exports);
 const{createRoot}=await import('react-dom/client');const container=browser.document.createElement('div')as unknown as HTMLElement;browser.document.body.append(container as never);const root=createRoot(container);
 try{await React.act(async()=>root.render(createElement(compiled.exports.SeoOverview as React.ComponentType<any>,{canManage:true,client,initialTab:'checks'})));assert.equal(starts,0);assert.match(container.textContent??'',/3\s*\/\s*10/);assert.match(container.textContent??'',/Başlık eksik/);assert.ok(container.querySelector('a[href="/seo/content?kind=product"]'));const button=[...container.querySelectorAll('button')].find(item=>item.textContent==='Kontrolü başlat');assert.ok(button);await React.act(async()=>button.click());assert.equal(starts,1);assert.doesNotMatch(container.textContent??'',/sağlık puanı|Google.*indekslendi/i);}finally{await React.act(async()=>root.unmount());for(const[key,value]of prior)value?Object.defineProperty(globalThis,key,value):Reflect.deleteProperty(globalThis,key);await browser.happyDOM.close();}
});

test('running checks recover after failed polling with bounded delays and stop after completion',async()=>{
 const browser=new Window({url:'https://panel.test/seo'}),prior=new Map<string,PropertyDescriptor|undefined>();
 for(const[key,value]of Object.entries({window:browser,document:browser.document,navigator:browser.navigator,HTMLElement:browser.HTMLElement,Event:browser.Event,IS_REACT_ACT_ENVIRONMENT:true})){prior.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{configurable:true,writable:true,value});}
 const originalTimeout=globalThis.setTimeout,originalClear=globalThis.clearTimeout,timers=new Map<number,{callback:()=>Promise<void>|void;delay:number}>();let nextTimer=1000,calls=0;
 globalThis.setTimeout=((callback:()=>Promise<void>|void,delay:number,...args:unknown[])=>{if(delay>=5000){const id=nextTimer++;timers.set(id,{callback,delay});return id;}return originalTimeout(callback,delay,...args);})as typeof setTimeout;
 globalThis.clearTimeout=((id:any)=>{if(timers.delete(id))return;originalClear(id);})as typeof clearTimeout;
 const overview={totalResources:10,publishedResources:10,issues:[],sitemap:{url:null,robotsUrl:null,entryCount:10},check:{checked:3,total:10,status:'running',lastCheckedAt:null},notifications:[],settings:{eligible:true,indexNowEnabled:false}};
 const client={overview:async()=>{calls++;if(calls>=2&&calls<=5)throw new SeoApiError('unavailable',503);return calls===6?{...overview,check:{...overview.check,checked:10,status:'completed'}}:overview;}};
 const source=await readFile(new URL('./SeoOverview.tsx',import.meta.url),'utf8'),code=ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,compiled={exports:{}as Record<string,unknown>};
 Function('require','module','exports',code)((name:string)=>{if(name==='react')return React;if(name==='react/jsx-runtime')return jsx;if(name==='next/link')return({children,href}:any)=>createElement('a',{href},children);if(name.includes('seo-ui/client'))return{seoClient:client,SeoApiError};if(name.includes('seo-ui/model'))return model;if(name.includes('SeoShared'))return{SeoFrame:({children}:any)=>createElement('section',null,children),SeoFeedback:({error,message}:any)=>createElement('div',null,error,message),ResourcePicker:()=>null};if(name.includes('OrderActionDialog'))return{OrderActionDialog:()=>null};if(name.endsWith('.css'))return{};throw Error(name);},compiled,compiled.exports);
 const{createRoot}=await import('react-dom/client');const container=browser.document.createElement('div')as unknown as HTMLElement;browser.document.body.append(container as never);const root=createRoot(container);
 const tick=async(expectedDelay:number)=>{assert.equal(timers.size,1,'exactly one pending poll');const[id,timer]=[...timers][0]!;assert.equal(timer.delay,expectedDelay);timers.delete(id);await React.act(async()=>{await timer.callback();});};
 try{
  await React.act(async()=>root.render(createElement(compiled.exports.SeoOverview as React.ComponentType<any>,{canManage:true,client,initialTab:'checks'})));
  await tick(5000);assert.equal(calls,2);assert.match(container.textContent??'',/3\s*\/\s*10/);assert.match(container.textContent??'',/yeniden deneyin/i);
  await tick(10000);await tick(20000);await tick(30000);await tick(30000);
  assert.equal(calls,6);assert.match(container.textContent??'',/10\s*\/\s*10/);assert.match(container.textContent??'',/Kontrol tamamlandı/);assert.doesNotMatch(container.textContent??'',/şu anda yüklenemiyor/);assert.equal(timers.size,0,'completed checks cancel the polling timer');
 }finally{await React.act(async()=>root.unmount());globalThis.setTimeout=originalTimeout;globalThis.clearTimeout=originalClear;for(const[key,value]of prior)value?Object.defineProperty(globalThis,key,value):Reflect.deleteProperty(globalThis,key);await browser.happyDOM.close();}
});
