import assert from 'node:assert/strict';import test from 'node:test';import {readFile} from 'node:fs/promises';import {Window} from 'happy-dom';import React,{createElement} from 'react';import * as jsx from 'react/jsx-runtime';import ts from 'typescript';import * as model from '../../lib/seo-ui/model.ts';import {SeoApiError} from '../../lib/seo-ui/client.ts';
test("overview displays checked URL count and actionable issues; scans begin only on explicit click",async()=>{
 const browser=new Window({url:'https://panel.test/seo'}),prior=new Map<string,PropertyDescriptor|undefined>();for(const[key,value]of Object.entries({window:browser,document:browser.document,navigator:browser.navigator,HTMLElement:browser.HTMLElement,Event:browser.Event,IS_REACT_ACT_ENVIRONMENT:true})){prior.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{configurable:true,writable:true,value});}
 let starts=0;const overview={totalResources:12,publishedResources:10,issues:[{code:'missing_title',severity:'warning',message:'Başlık eksik',path:'/products/ring',kind:'product',resourceId:'11111111-1111-4111-8111-111111111111',fixHref:'/seo/content?kind=product'}],sitemap:{url:'https://store.test/sitemap.xml',robotsUrl:'https://store.test/robots.txt',entryCount:10},check:{checked:3,total:10,status:'completed',lastCheckedAt:null},notifications:[],settings:{eligible:true,indexNowEnabled:false}};
 const client={overview:async()=>overview,startCheck:async()=>{starts++;return{checked:0,total:10,status:'running',replayed:false};}};
 const source=await readFile(new URL('./SeoOverview.tsx',import.meta.url),'utf8'),code=ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,compiled={exports:{}as Record<string,unknown>};
 Function('require','module','exports',code)((name:string)=>{if(name==='react')return React;if(name==='react/jsx-runtime')return jsx;if(name==='next/link')return({children,href}:any)=>createElement('a',{href},children);if(name.includes('seo-ui/client'))return{seoClient:client,SeoApiError};if(name.includes('seo-ui/model'))return model;if(name.includes('SeoShared'))return{SeoFrame:({children}:any)=>createElement('section',null,children),SeoFeedback:({error,message}:any)=>createElement('div',null,error,message),ResourcePicker:()=>null};if(name.includes('OrderActionDialog'))return{OrderActionDialog:()=>null};if(name.endsWith('.css'))return{};throw Error(name);},compiled,compiled.exports);
 const{createRoot}=await import('react-dom/client');const container=browser.document.createElement('div')as unknown as HTMLElement;browser.document.body.append(container as never);const root=createRoot(container);
 try{await React.act(async()=>root.render(createElement(compiled.exports.SeoOverview as React.ComponentType<any>,{canManage:true,client,initialTab:'checks'})));assert.equal(starts,0);assert.match(container.textContent??'',/3\s*\/\s*10/);assert.match(container.textContent??'',/Başlık eksik/);assert.ok(container.querySelector('a[href="/seo/content?kind=product"]'));const button=[...container.querySelectorAll('button')].find(item=>item.textContent==='Kontrolü başlat');assert.ok(button);await React.act(async()=>button.click());assert.equal(starts,1);assert.doesNotMatch(container.textContent??'',/sağlık puanı|Google.*indekslendi/i);}finally{await React.act(async()=>root.unmount());for(const[key,value]of prior)value?Object.defineProperty(globalThis,key,value):Reflect.deleteProperty(globalThis,key);await browser.happyDOM.close();}
});
