'use client';
import Link from 'next/link';
import {useEffect,useState,type ReactNode} from 'react';
import type {SeoResource,SeoResourceKind} from '@celebix/saas-contracts';
import {PanelPageShell} from '@/components/panel/PanelPageShell';
import {seoClient,type SeoClient} from '@/lib/seo-ui/client';
import {RESOURCE_KINDS,RESOURCE_LABELS} from '@/lib/seo-ui/model';
import styles from './seo.module.css';
export function SeoFrame({active,title,canManage,children}:Readonly<{active:'overview'|'content'|'settings';title:string;canManage:boolean;children:ReactNode}>){return <PanelPageShell><div className={styles.workspace}><h1 className="sr-only">{title}</h1><nav className={styles.nav} aria-label="SEO ekranları">{[['overview','/seo','SEO Kontrol'],['content','/seo/content','İçerik SEO'],['settings','/seo/settings','SEO Ayarları']].map(([key,href,label])=><Link key={key} href={href!} aria-current={active===key?'page':undefined}>{label}</Link>)}</nav>{!canManage?<p className={styles.status}>Bu ekranı görüntüleyebilirsiniz. Değişiklik yapmak için yönetim yetkisi gerekir.</p>:null}{children}</div></PanelPageShell>;}
export function SeoFeedback({error,message}:Readonly<{error?:string;message?:string}>){return <>{error?<p className={styles.error} role="alert">{error}</p>:null}{message?<p className={styles.status} role="status">{message}</p>:null}</>;}
export function ResourcePicker({label,value,onChange,disabled=false,client=seoClient}:Readonly<{label:string;value:Pick<SeoResource,'id'|'kind'|'name'|'path'>|null;onChange:(value:SeoResource|null)=>void;disabled?:boolean;client?:SeoClient}>){
 const[kind,setKind]=useState<SeoResourceKind>(value?.kind??'product'),[query,setQuery]=useState(''),[items,setItems]=useState<SeoResource[]>([]),[cursor,setCursor]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(value&&value.kind!==kind)setKind(value.kind);},[value?.kind]);
 useEffect(()=>{let alive=true;setBusy(true);const timer=setTimeout(()=>{void client.resources({kind,query}).then(result=>{if(alive){setItems(result.items);setCursor(result.nextCursor);setError('');}}).catch(()=>{if(alive)setError('İçerikler yüklenemedi. Aramayı yeniden deneyin.');}).finally(()=>{if(alive)setBusy(false);});},200);return()=>{alive=false;clearTimeout(timer);};},[client,kind,query]);
 async function more(){if(!cursor)return;setBusy(true);try{const result=await client.resources({kind,query,cursor});setItems(current=>[...current,...result.items]);setCursor(result.nextCursor);setError('');}catch{setError('Diğer içerikler yüklenemedi. Yeniden deneyin.');}finally{setBusy(false);}}
 return <div className={styles.picker}><div className={styles.pickerFilters}><label>{label} türü<select value={kind} disabled={disabled} onChange={e=>{setKind(e.target.value as SeoResourceKind);onChange(null);setItems([]);}}>{RESOURCE_KINDS.map(kind=><option key={kind} value={kind}>{RESOURCE_LABELS[kind]}</option>)}</select></label><label>{label} ara<input type="search" maxLength={100} value={query} disabled={disabled} onChange={e=>setQuery(e.target.value)} placeholder="Ad veya URL"/></label></div><label>{label}<select disabled={disabled||busy} value={value?.kind===kind?value.id:''} onChange={e=>onChange(items.find(item=>item.id===e.target.value)??null)}><option value="">{busy?'Yükleniyor…':'İçerik seçin'}</option>{value?.kind===kind&&!items.some(item=>item.id===value.id)?<option value={value.id}>{value.name} · {value.path}</option>:null}{items.map(item=><option key={item.id} value={item.id}>{item.name} · {item.path}</option>)}</select></label>{cursor?<button type="button" disabled={disabled||busy} onClick={()=>void more()}>Daha fazla içerik</button>:null}{error?<p role="alert">{error}</p>:null}</div>;
}
