import test from 'node:test';
import assert from 'node:assert/strict';
const api = await import('./hooks.ts').catch(() => ({})) as typeof import('./hooks.ts');
import { sealEmailMarketingCredential } from './credential-crypto.ts';
const keyring = { activeKeyId: 'fixture', keys: [{ keyId: 'fixture', key: new Uint8Array(32).fill(1) }] };
const connectionId = '22600000-0000-4000-8000-000000000003', storeId = '22600000-0000-4000-8000-000000000001';
test('hook creation records a sealed secret before provider IO; unknown recovery never recreates', async () => { assert.equal(typeof api.synchronizeEmailMarketingWebhook, 'function'); const calls: string[] = []; let saved: any; const job: any = { id: '22600000-0000-4000-8000-000000000010', connectionId, storeId, provider: 'brevo', leaseToken: '22600000-0000-4000-8000-000000000099', webhook: { credential: null, version: 1, state: null } }; const repository: any = { hookCheckpoint: async (_j: any, p: any) => { calls.push(p.state); saved = p; return true; } }; const adapter: any = { createWebhook: async () => { calls.push('create'); return { kind: 'unknown' }; }, findWebhook: async () => ({ kind: 'missing' }), deleteWebhook: async () => ({ kind: 'verified', value: null }) }; await api.synchronizeEmailMarketingWebhook(job, { repository, keyring, adapter, apiKey: 'fixture-key', removing: false }); assert.deepEqual(calls, ['dispatched', 'create', 'unknown']); assert.equal(saved.state, 'unknown'); calls.length = 0; job.webhook = { credential: sealEmailMarketingCredential('s'.repeat(43), { storeId, credentialOwnerId: connectionId, provider: 'brevo', purpose: 'webhook', credentialVersion: 1 }, keyring), version: 1, state: 'unknown', id: null }; assert.equal(await api.synchronizeEmailMarketingWebhook(job, { repository, keyring, adapter, apiKey: 'fixture-key', removing: false }), true); assert.equal(calls.includes('create'), false); assert.equal(await api.synchronizeEmailMarketingWebhook(job, { repository, keyring, adapter, apiKey: 'fixture-key', removing: true }), false); });

test('an explicitly rejected hook create releases only its unsent secret for retry',async()=>{const {EmailMarketingError}=await import('./errors.ts');const marks:string[]=[];const job:any={id:connectionId,connectionId,storeId,provider:'brevo',leaseToken:connectionId,webhook:{credential:null,version:1,state:null}};const failure=new EmailMarketingError('provider_rate_limited',30);Object.defineProperty(failure,'effectNotApplied',{value:true});const repository:any={hookCheckpoint:async(_:any,p:any)=>{marks.push(p.state);return true;}};const adapter:any={createWebhook:async()=>{throw failure;},findWebhook:async()=>({kind:'missing'}),deleteWebhook:async()=>({kind:'verified'})};await assert.rejects(api.synchronizeEmailMarketingWebhook(job,{repository,keyring,adapter,apiKey:'fixture',removing:false}));assert.deepEqual(marks,['dispatched','not_sent']);});
