import test from 'node:test';
import assert from 'node:assert/strict';
const api = await import('./sync.ts').catch(() => ({})) as typeof import('./sync.ts');
import { sealEmailMarketingCredential } from './credential-crypto.ts';
const now = () => new Date('2026-10-09T12:00:00Z'), keyring = { activeKeyId: 'email-key', keys: [{ keyId: 'email-key', key: new Uint8Array(32).fill(1) }] };
const storeId = '22600000-0000-4000-8000-000000000001', connectionId = '22600000-0000-4000-8000-000000000002';
function fixture(phase = 'queued', denied = false) { const calls: string[] = []; const job: any = { id: '22600000-0000-4000-8000-000000000003', storeId, connectionId, generation: 1, credentialVersion: 1, email: 'ada@example.test', consentVersion: 1, kind: 'profile', leaseToken: '22600000-0000-4000-8000-000000000004', leaseUntil: '2026-10-09T12:01:30Z', phase, providerReference: null, provider: 'klaviyo', listId: 'managed', credential: sealEmailMarketingCredential('fixture-key', { storeId, credentialOwnerId: connectionId, provider: 'klaviyo', purpose: 'connection', credentialVersion: 1 }, keyring), progress: { action: 'subscribe', dispatchedAt: '2026-10-09T11:59:00Z' }, audience: { kind: denied ? 'deny' : 'grant', sequence: denied ? 2 : 1, consentedAt: '2026-10-01T10:00:00Z', source: 'newsletter', evidenceVersion: 'v1' }, profileId: null }; const repository: any = { checkpoint: async (i: any) => { calls.push(i.result.phase); return true; }, finish: async (i: any) => { calls.push(i.outcome.status); return true; }, bootstrap: async () => { }, poll: async () => { }, cleanup: async () => { } }; const adapter: any = { contact: async () => ({ kind: phase === 'queued' ? 'absent' : 'known', profileId: phase === 'queued' ? null : 'p1', marketingStatus: denied ? 'unsubscribed' : 'unknown', listIds: [], suppressionReasons: [], unsubscribedListIds: [], consentUpdatedAt: null }), subscribeNew: async () => { calls.push('subscribe'); return { kind: 'accepted' }; } }; return { calls, job, dependencies: { repository, providers: { klaviyo: adapter, brevo: adapter }, keyring, now } }; }
test('checkpoint precedes a Subscribe and 202 remains pending', async () => { assert.equal(typeof api.runEmailMarketingSyncJob, 'function'); const f = fixture(); await api.runEmailMarketingSyncJob(f.job, f.dependencies); assert.deepEqual(f.calls, ['dispatched', 'subscribe', 'accepted', 'pending']); });
test('ret after accepted subscribe keeps the effect pending with no repeat grant', async () => { const f = fixture('accepted', true); await api.runEmailMarketingSyncJob(f.job, f.dependencies); assert.equal(f.calls.includes('subscribe'), false); assert.equal(f.calls.at(-1), 'attention'); });
test('lost lease before dispatch causes zero external mutations', async () => { const f = fixture(); f.dependencies.repository.checkpoint = async () => false; await api.runEmailMarketingSyncJob(f.job, f.dependencies); assert.equal(f.calls.includes('subscribe'), false); });
test('a validated rotated key may read back without changing the original dispatch evidence', async () => { const f = fixture('accepted'); f.job.reconciliationCredentialVersion = 2; f.job.reconciliationCredential = sealEmailMarketingCredential('rotated-fixture', { storeId, credentialOwnerId: connectionId, provider: 'klaviyo', purpose: 'connection', credentialVersion: 2 }, keyring); f.dependencies.providers.klaviyo.contact = async (key: string) => { assert.equal(key, 'rotated-fixture'); return { kind: 'known', profileId: 'p1', marketingStatus: 'subscribed', listIds: ['managed'], suppressionReasons: [], unsubscribedListIds: [], consentUpdatedAt: '2026-10-01T10:00:00Z' }; }; await api.runEmailMarketingSyncJob(f.job, f.dependencies); assert.equal(f.calls.includes('subscribe'), false); assert.equal(f.calls.at(-1), 'verified'); assert.equal(f.job.credentialVersion, 1); });
test('dispatch fences the credential version selected before provider IO', async () => { const f = fixture(); let selected: number | undefined; f.dependencies.repository.checkpoint = async (input: any) => { selected = input.result.credentialVersion; return false; }; await api.runEmailMarketingSyncJob(f.job, f.dependencies); assert.equal(selected, 1); assert.equal(f.calls.includes('subscribe'), false); });
test('lost final lease reports pending instead of a verified result', async () => { const f = fixture('accepted'); f.dependencies.providers.klaviyo.contact = async () => ({ kind: 'known', profileId: 'p1', marketingStatus: 'subscribed', listIds: ['managed'], suppressionReasons: [], unsubscribedListIds: [], consentUpdatedAt: '2026-10-01T10:00:00Z' }); f.dependencies.repository.finish = async () => false; assert.equal(await api.runEmailMarketingSyncJob(f.job, f.dependencies), 'pending'); });
