import { CATALOG_ADMIN_RESOURCE_KINDS, parseCatalogAdminImportJob, parseCatalogAdminMutationResult, parseCatalogAdminResource, parseCatalogImportPreview, parseProductReview, type CatalogAdminJson, type CatalogAdminResourceKind, type CatalogImportFormat as CatalogImportPreviewFormat, type ProductReviewStatus } from "@celebix/saas-contracts";
import type { CatalogAdminImportProduct, CatalogAdminImportRow } from "@celebix/saas-data";
import type { CatalogImportFormat, CatalogImportProvider } from "../catalog-import/providers.ts";
const CODES = ["invalid_input", "unauthenticated", "membership_denied", "store_inactive", "feature_not_enabled", "resource_not_found", "review_not_found", "slug_conflict", "product_limit_reached", "import_conflict", "invalid_transition", "version_conflict", "operation_mismatch", "durable_authority_invalid", "unavailable"] as const;
type Code = (typeof CODES)[number];
const MESSAGES: Record<Code, string> = { invalid_input: "Gönderilen katalog bilgileri geçersiz.", unauthenticated: "Oturumunuz sona erdi.", membership_denied: "Bu katalog işlemi için yetkiniz yok.", store_inactive: "Mağaza katalog işlemlerine kapalı.", feature_not_enabled: "Katalog yönetimi planınızda etkin değil.", resource_not_found: "Katalog kaydı bulunamadı.", review_not_found: "Ürün yorumu bulunamadı.", slug_conflict: "Bu URL anahtarı başka bir kayıtta kullanılıyor.", product_limit_reached: "Planınızdaki ürün sınırına ulaştınız.", import_conflict: "Yükleme satırlarından biri mevcut katalogla çakışıyor.", invalid_transition: "Bu işlem artık uygulanamaz.", version_conflict: "Kayıt sizden önce güncellendi.", operation_mismatch: "İşlem güvenle tekrar edilemedi.", durable_authority_invalid: "Katalog yetkisi yeniden doğrulanamadı.", unavailable: "Katalog yönetimi şu anda kullanılamıyor." };
export class CatalogAdminApiError extends Error {
  readonly code: Code;
  readonly status: number;
  constructor(code: Code, status: number) {
    super(MESSAGES[code]);
    this.name = "CatalogAdminApiError";
    this.code = code;
    this.status = status;
  }
}
type Fetch = typeof fetch;
function record(value: unknown) { return typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : null; }
async function json(response: Response) { if (response.headers.get("content-type")?.split(";", 1)[0] !== "application/json") throw new CatalogAdminApiError("unavailable", response.status || 503); try { return await response.json(); } catch (caught) { if (caught instanceof DOMException && caught.name === "AbortError") throw caught; throw new CatalogAdminApiError("unavailable", 503); } }
function kind(value: CatalogAdminResourceKind) { if (!CATALOG_ADMIN_RESOURCE_KINDS.includes(value)) throw new TypeError("catalog_admin_client_invalid"); return value; }
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const SKU = /^[A-Z0-9][A-Z0-9._-]{0,63}$/;
const ATTRIBUTE_KEY = /^[A-Za-z0-9][A-Za-z0-9_.:-]{0,63}$/;
const PROVIDERS = new Set(["woocommerce", "shopify", "ideasoft", "ticimax", "tsoft", "ikas", "opencart", "prestashop", "magento", "bigcommerce", "wix", "generic"]);
function unavailable(): never { throw new CatalogAdminApiError("unavailable", 503); }
function exactRecord(value: unknown, required: readonly string[], optional: readonly string[] = []) { const selected = record(value); if (!selected) unavailable(); const allowed = new Set([...required, ...optional]); if (required.some((key) => !Object.hasOwn(selected, key)) || Object.keys(selected).some((key) => !allowed.has(key))) unavailable(); return selected; }
function safeText(value: unknown, minimum: number, maximum: number, pattern?: RegExp) { if (typeof value !== "string" || value.length < minimum || value.length > maximum || value !== value.trim() || /[\u0000-\u001f\u007f]/.test(value) || (pattern && !pattern.test(value))) unavailable(); return value; }
function safeInteger(value: unknown) { if (!Number.isSafeInteger(value) || (value as number) < 0) unavailable(); return value as number; }
function parseImportAttributes(value: unknown) { const selected = record(value); if (!selected || Object.keys(selected).length > 32) unavailable(); const entries = Object.entries(selected).map(([key, item]) => [safeText(key, 1, 64, ATTRIBUTE_KEY), safeText(item, 0, 256)] as const); return Object.freeze(Object.fromEntries(entries)); }
function parseImportVariant(value: unknown) { const selected = exactRecord(value, ["title", "priceCents", "stockQuantity", "attributes"], ["sku", "barcode", "compareAtCents", "costCents"]); const priceCents = safeInteger(selected.priceCents); const compareAtCents = selected.compareAtCents === undefined ? undefined : safeInteger(selected.compareAtCents); if (compareAtCents !== undefined && compareAtCents < priceCents) unavailable(); return Object.freeze({ title: safeText(selected.title, 1, 200), ...(selected.sku === undefined ? {} : { sku: safeText(selected.sku, 1, 64, SKU) }), ...(selected.barcode === undefined ? {} : { barcode: safeText(selected.barcode, 1, 128) }), priceCents, ...(compareAtCents === undefined ? {} : { compareAtCents }), ...(selected.costCents === undefined ? {} : { costCents: safeInteger(selected.costCents) }), stockQuantity: safeInteger(selected.stockQuantity), attributes: parseImportAttributes(selected.attributes) }); }
function parseImportProduct(value: unknown) { const selected = exactRecord(value, ["title", "slug", "status", "variants"], ["description"]); if (!Array.isArray(selected.variants) || selected.variants.length < 1 || selected.variants.length > 50 || !["draft", "active"].includes(String(selected.status))) unavailable(); return Object.freeze({ title: safeText(selected.title, 1, 200), slug: safeText(selected.slug, 3, 100, SLUG), ...(selected.description === undefined ? {} : { description: safeText(selected.description, 1, 10_000) }), status: selected.status as "draft" | "active", variants: Object.freeze(selected.variants.map(parseImportVariant)) }); }
function parseFeedPreview(value: unknown) { const selected = exactRecord(value, ["products", "warnings", "skippedRows", "totalRows", "format"]); if (!Array.isArray(selected.products) || selected.products.length < 1 || selected.products.length > 100 || !Array.isArray(selected.warnings) || selected.warnings.length > 8 || selected.warnings.some((warning) => warning !== "unsupported_fields_ignored") || !["csv", "json", "xml"].includes(String(selected.format))) unavailable(); const skippedRows = safeInteger(selected.skippedRows), totalRows = safeInteger(selected.totalRows); if (totalRows < selected.products.length || skippedRows > totalRows) unavailable(); return Object.freeze({ products: Object.freeze(selected.products.map(parseImportProduct)), warnings: Object.freeze([...selected.warnings] as string[]), skippedRows, totalRows, format: selected.format as CatalogImportFormat }); }
function opaqueId(value: string) { if (!UUID.test(value)) throw new TypeError("catalog_admin_client_invalid"); return value; }
function preview(value: unknown) { try { return parseCatalogImportPreview(value); } catch { throw new CatalogAdminApiError("unavailable", 503); } }
export function createCatalogAdminApi(fetcher: Fetch = fetch, uuid: () => string = crypto.randomUUID.bind(crypto)) {
  async function request(path: string, init?: RequestInit) { const response = await fetcher(path, { credentials: "same-origin", cache: "no-store", ...init }); const value = await json(response); if (!response.ok) { const parsed = record(value); const code = parsed && typeof parsed.code === "string" && CODES.includes(parsed.code as Code) ? parsed.code as Code : "unavailable"; throw new CatalogAdminApiError(code, response.status); } return value; }
  function post(path: string, value: unknown, operationId = uuid()) { if (!UUID.test(operationId)) throw new TypeError("catalog_admin_client_invalid"); return request(path, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": operationId }, body: JSON.stringify(value) }); }
  function postRead(path: string, value: unknown) { return request(path, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(value) }); }
  function items<T>(value: unknown, parser: (entry: unknown) => T): readonly T[] { const parsed = record(value); if (!parsed || Object.keys(parsed).join(",") !== "items" || !Array.isArray(parsed.items)) throw new CatalogAdminApiError("unavailable", 503); return Object.freeze(parsed.items.map(parser)); }
  return Object.freeze({
    async resources(resourceKind: CatalogAdminResourceKind) { return items(await request(`/api/catalog/admin/resources/${kind(resourceKind)}`), parseCatalogAdminResource); },
    async resource(resourceKind: CatalogAdminResourceKind, resourceId: string) { const expectedKind = kind(resourceKind); const expectedId = opaqueId(resourceId); let result; try { result = parseCatalogAdminResource(await request(`/api/catalog/admin/resources/${expectedKind}/${expectedId}`)); } catch (error) { if (error instanceof CatalogAdminApiError) throw error; throw new CatalogAdminApiError("unavailable", 503); } if (result.kind !== expectedKind || result.id !== expectedId) throw new CatalogAdminApiError("unavailable", 503); return result; },
    async saveResource(resourceKind: CatalogAdminResourceKind, value: Readonly<{ resourceId?: string; expectedVersion?: number; name: string; slug: string; description?: string; config: Readonly<Record<string, CatalogAdminJson>>; productIds: readonly string[] }>) { return parseCatalogAdminMutationResult(await post(`/api/catalog/admin/resources/${kind(resourceKind)}`, value)); },
    async archiveResource(resourceKind: CatalogAdminResourceKind, resourceId: string, expectedVersion: number) { return parseCatalogAdminMutationResult(await post(`/api/catalog/admin/resources/${kind(resourceKind)}/${encodeURIComponent(resourceId)}/archive`, { expectedVersion })); },
    async reviews(status?: ProductReviewStatus) { const query = status ? `?status=${encodeURIComponent(status)}` : ""; return items(await request(`/api/catalog/admin/reviews${query}`), parseProductReview); },
    async moderateReview(reviewId: string, value: Readonly<{ expectedVersion: number; status: "approved" | "rejected" | "archived"; reply?: string }>) { return parseCatalogAdminMutationResult(await post(`/api/catalog/admin/reviews/${encodeURIComponent(reviewId)}/moderate`, value)); },
    async imports() { return items(await request("/api/catalog/admin/imports"), parseCatalogAdminImportJob); },
    async previewFeed(value: Readonly<{ provider: CatalogImportProvider; url: string }>) { if (!PROVIDERS.has(value.provider) || typeof value.url !== "string") throw new TypeError("catalog_admin_client_invalid"); return parseFeedPreview(await postRead("/api/catalog/admin/imports/feed/preview", value)); },
    async importProducts(value: Readonly<{ fileName: string; products: readonly CatalogAdminImportProduct[] }> | Readonly<{ fileName: string; rows: readonly CatalogAdminImportRow[] }>, operationId?: string) { return parseCatalogAdminMutationResult(await post("/api/catalog/admin/imports", value, operationId)); },
    async prepareImportPreview(value: Readonly<{ format: CatalogImportPreviewFormat; fileName: string; content: string }>, signal?: AbortSignal) { return preview(await request("/api/catalog/admin/import-previews", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": uuid() }, body: JSON.stringify(value), signal })); },
    async getImportPreview(previewId: string, signal?: AbortSignal) { return preview(await request(`/api/catalog/admin/import-previews/${opaqueId(previewId)}`, { signal })); },
    async commitImportPreview(previewId: string, expectedVersion: number, signal?: AbortSignal) { if (!Number.isSafeInteger(expectedVersion) || expectedVersion < 1) throw new TypeError("catalog_admin_client_invalid"); const value = await request(`/api/catalog/admin/import-previews/${opaqueId(previewId)}/commit`, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": uuid() }, body: JSON.stringify({ expectedVersion }), signal }); try { return parseCatalogAdminMutationResult(value); } catch { throw new CatalogAdminApiError("unavailable", 503); } },
  });
}
export const catalogAdminApi = createCatalogAdminApi();
