import assert from 'node:assert/strict';
import test from 'node:test';
import type {CatalogAdminRepository} from '@celebix/saas-data';
import type {ServerPanelAccessRuntime} from '../server-panel-access/runtime.ts';
import {registerServerCatalogAdminRepository} from '../server-catalog-admin/runtime.ts';
import {registerServerLuckyWheelRepository,resolveServerLuckyWheelRuntime,type LuckyWheelAdminRepository} from './runtime.ts';
function access(){return{readiness:{mode:'approved_staging'},panelOrigin:'https://fixture.invalid'} as ServerPanelAccessRuntime}
function catalog(){return Object.fromEntries(['listResources','getResource','saveResource','archiveResource','listReviews','moderateReview','listImports','importProducts','importProductsV2','authorizeFeedPreview','prepareImport','getImportPreview','commitImportPreview'].map(name=>[name,async()=>null])) as unknown as CatalogAdminRepository}
test('runtime facade exposes and binds every required method including real deletion',async()=>{const a=access();registerServerCatalogAdminRepository(a,catalog());const methods=['list','save','deleteCampaign','history','revokeCoupons','managedPromotions'],repo={marker:'required',...Object.fromEntries(methods.map(name=>[name,async function(this:{marker:string},input:unknown){return{name,marker:this.marker,input}}]))} as unknown as LuckyWheelAdminRepository;registerServerLuckyWheelRepository(a,repo);const runtime=resolveServerLuckyWheelRuntime(a)!;assert.deepEqual(Object.keys(runtime.luckyWheel),methods);assert.equal(Object.isFrozen(runtime.luckyWheel),true);for(const method of methods){const result=await(runtime.luckyWheel as any)[method]('fixture');assert.deepEqual(result,{name:method,marker:'required',input:'fixture'})}});
test('missing any required method and duplicate or unapproved registration rejects',()=>{const methods=['list','save','deleteCampaign','history','revokeCoupons','managedPromotions'];for(const absent of methods){const repo=Object.fromEntries(methods.filter(m=>m!==absent).map(m=>[m,async()=>null]));assert.throws(()=>registerServerLuckyWheelRepository(access(),repo as unknown as LuckyWheelAdminRepository))}const a=access(),repo=Object.fromEntries(methods.map(m=>[m,async()=>null])) as unknown as LuckyWheelAdminRepository;registerServerLuckyWheelRepository(a,repo);assert.throws(()=>registerServerLuckyWheelRepository(a,repo));assert.throws(()=>registerServerLuckyWheelRepository({...a,panelOrigin:null},repo));assert.equal(resolveServerLuckyWheelRuntime(access()),null)});
