"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import type { AbandonedCartDetail, AbandonedCartListItem, AbandonedCartSort, AbandonedCartStatus, AbandonedCartSummary } from "@celebix/saas-contracts";
import { Archive, CheckCircle2, Clock3, Mail, Package2, Phone, RefreshCcw, Search, ShoppingCart, UserRound, Wallet } from "lucide-react";

import { PanelEmptyState, PanelPageHeader, PanelPageShell, PanelStatusBadge } from "@/components/panel/PanelPageShell";
import { AbandonedCartApiError, abandonedCartApi } from "@/lib/abandoned-cart-ui/client";
import styles from "./abandoned-cart-console.module.css";

type State = "loading" | "loaded" | "error";
const STATUS: Readonly<Record<AbandonedCartStatus, string>> = Object.freeze({ active: "Aktif", abandoned: "Terk edildi", recovered: "Kurtarıldı", archived: "Arşivlendi" });

function money(cents: number, currency: string) { return new Intl.NumberFormat("tr-TR", { style: "currency", currency }).format(cents / 100); }
function date(value: string) { return new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function tone(status: AbandonedCartStatus): "neutral" | "success" | "warning" | "danger" { return status === "recovered" ? "success" : status === "abandoned" ? "danger" : status === "active" ? "warning" : "neutral"; }
function customer(cart: AbandonedCartListItem) { return cart.customerName ?? cart.customerEmail ?? cart.customerPhone ?? "Anonim sepet"; }
function message(error: unknown) { return error instanceof AbandonedCartApiError ? error.message : "Sepetler yüklenemedi. Lütfen yeniden deneyin."; }

function Metric({ label, value, detail, icon: Icon }: { label: string; value: string; detail: string; icon: typeof ShoppingCart }) {
  return <article className={styles.metric}><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div><i aria-hidden="true"><Icon /></i></article>;
}

function CartCard({ cart }: { cart: AbandonedCartListItem }) {
  return <article className={styles.cartCard}><div className={styles.cardHeading}><strong>{customer(cart)}</strong><PanelStatusBadge tone={tone(cart.status)}>{STATUS[cart.status]}</PanelStatusBadge></div><dl><div><dt>Toplam</dt><dd>{money(cart.totalCents, cart.currency)}</dd></div><div><dt>Ürün</dt><dd>{cart.itemCount}</dd></div><div><dt>Son etkinlik</dt><dd>{date(cart.lastActivityAt)}</dd></div></dl><Link className={styles.detailLink} href={`/orders/abandoned-carts/${cart.id}`}>Sepet ayrıntısını aç</Link></article>;
}

export function AbandonedCartListPresentation(props: Readonly<{ state: State; items: readonly AbandonedCartListItem[]; summary?: AbandonedCartSummary; error: string; search: string; status: AbandonedCartStatus | "all"; sort: AbandonedCartSort; nextCursor?: string; loadingMore: boolean; onRetry(): void; onSearch(value: string): void; onSubmit(): void; onStatus(value: AbandonedCartStatus | "all"): void; onSort(value: AbandonedCartSort): void; onLoadMore(): void }>) {
  return <PanelPageShell><PanelPageHeader title="Terk Edilen Sepetler" description="Yarım kalan alışverişleri gerçek mağaza ve ürün verileriyle takip edin." />
    {props.summary ? <section className={styles.metrics} aria-label="Sepet özeti"><Metric label="Terk edilen" value={props.summary.abandoned.toLocaleString("tr-TR")} detail="Takip bekleyen sepet" icon={ShoppingCart} /><Metric label="Kurtarılan" value={props.summary.recovered.toLocaleString("tr-TR")} detail="Kalıcı kurtarma kaydı" icon={CheckCircle2} /><Metric label="Kayıp değer" value={money(props.summary.lostValueCents, props.summary.currency)} detail="Terk edilmiş sepet toplamı" icon={Wallet} /><Metric label="Kurtarılan değer" value={money(props.summary.recoveredValueCents, props.summary.currency)} detail={`Son hesaplama ${date(props.summary.asOf)}`} icon={RefreshCcw} /></section> : null}
    <section className={styles.surface} aria-labelledby="abandoned-list-title"><header><div><h2 id="abandoned-list-title">Sepet akışı</h2><p>Durum, müşteri ve tutara göre güvenli mağaza görünümü.</p></div></header>
      <form className={styles.toolbar} role="search" onSubmit={(event) => { event.preventDefault(); props.onSubmit(); }}><label className={styles.search}><span className="sr-only">Sepet ara</span><Search aria-hidden="true" /><input value={props.search} onChange={(event) => props.onSearch(event.target.value)} placeholder="Müşteri adı, e-posta veya telefon" maxLength={200} /><button type="submit">Ara</button></label><label><span className="sr-only">Sepet durumu</span><select value={props.status} onChange={(event) => props.onStatus(event.target.value as AbandonedCartStatus | "all")}><option value="all">Tüm durumlar</option>{Object.entries(STATUS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span className="sr-only">Sıralama</span><select value={props.sort} onChange={(event) => props.onSort(event.target.value as AbandonedCartSort)}><option value="newest">En yeni</option><option value="oldest">En eski</option><option value="highest">Tutar: yüksekten düşüğe</option><option value="lowest">Tutar: düşükten yükseğe</option></select></label></form>
      {props.state === "loading" ? <div className={styles.loading} role="status">Sepetler yükleniyor…</div> : props.state === "error" ? <div className={styles.error} role="alert"><div><h2>Sepetler yüklenemedi</h2><p>{props.error}</p></div><button type="button" onClick={props.onRetry}>Tekrar dene</button></div> : props.items.length === 0 ? <PanelEmptyState title="Henüz terk edilmiş sepet yok" description="Gerçek bir alışveriş yarım kaldığında burada görünecek." /> : <><div className={styles.desktopTable}><table aria-label="Terk edilen sepet listesi"><thead><tr><th>Müşteri</th><th>Durum</th><th>Son etkinlik</th><th>Ürün</th><th>Toplam</th><th /></tr></thead><tbody>{props.items.map((cart) => <tr key={cart.id}><td><strong>{customer(cart)}</strong><small>{cart.customerEmail ?? cart.customerPhone ?? "İletişim bilgisi yok"}</small></td><td><PanelStatusBadge tone={tone(cart.status)}>{STATUS[cart.status]}</PanelStatusBadge></td><td>{date(cart.lastActivityAt)}</td><td>{cart.itemCount.toLocaleString("tr-TR")}</td><td><strong>{money(cart.totalCents, cart.currency)}</strong></td><td><Link className={styles.rowAction} href={`/orders/abandoned-carts/${cart.id}`}>İncele</Link></td></tr>)}</tbody></table></div><div className={styles.mobileCards}>{props.items.map((cart) => <CartCard key={cart.id} cart={cart} />)}</div>{props.nextCursor ? <button className={styles.loadMore} type="button" disabled={props.loadingMore} onClick={props.onLoadMore}>{props.loadingMore ? "Yükleniyor…" : "Daha fazla sepet yükle"}</button> : null}</>}
    </section></PanelPageShell>;
}

export function AbandonedCartConsole() {
  const [state, setState] = useState<State>("loading"); const [items, setItems] = useState<readonly AbandonedCartListItem[]>([]); const [summary, setSummary] = useState<AbandonedCartSummary>(); const [error, setError] = useState(""); const [searchInput, setSearchInput] = useState(""); const [search, setSearch] = useState(""); const [status, setStatus] = useState<AbandonedCartStatus | "all">("all"); const [sort, setSort] = useState<AbandonedCartSort>("newest"); const [nextCursor, setNextCursor] = useState<string>(); const [loadingMore, setLoadingMore] = useState(false); const sequence = useRef(0);
  const load = useCallback(async (cursor?: string) => { const current = ++sequence.current; cursor ? setLoadingMore(true) : setState("loading"); setError(""); try { const [list, latestSummary] = await Promise.all([abandonedCartApi.list({ pageSize: 20, ...(cursor ? { cursor } : {}), ...(status === "all" ? {} : { status }), ...(search ? { search } : {}), sort }), abandonedCartApi.getSummary()]); if (current !== sequence.current) return; setItems((existing) => cursor ? Object.freeze([...existing, ...list.items]) : list.items); setNextCursor(list.nextCursor); setSummary(latestSummary); setState("loaded"); } catch (failure) { if (current === sequence.current) { if (!cursor) { setItems([]); setSummary(undefined); setNextCursor(undefined); } setError(message(failure)); setState("error"); } } finally { if (current === sequence.current) setLoadingMore(false); } }, [search, sort, status]);
  useEffect(() => { void load(); return () => { sequence.current += 1; }; }, [load]);
  return <AbandonedCartListPresentation state={state} items={items} summary={summary} error={error} search={searchInput} status={status} sort={sort} nextCursor={nextCursor} loadingMore={loadingMore} onRetry={() => void load()} onSearch={setSearchInput} onSubmit={() => { const value = searchInput.trim(); if (value.length <= 200) setSearch(value); }} onStatus={setStatus} onSort={setSort} onLoadMore={() => { if (nextCursor) void load(nextCursor); }} />;
}

export function AbandonedCartDetailPresentation(props: Readonly<{ state: State; detail?: AbandonedCartDetail; error: string; notice: string; busy: boolean; canManage: boolean; onRetry(): void; onRecovered(): void; onArchive(): void }>) {
  if (props.state === "loading") return <div className={styles.loading} role="status">Sepet ayrıntısı yükleniyor…</div>;
  if (props.state === "error" || !props.detail) return <section className={styles.detailState}><div className={styles.error} role="alert"><div><h1>Sepet ayrıntısı açılamadı</h1><p>{props.error || "Sepet bulunamadı."}</p></div><button type="button" onClick={props.onRetry}>Tekrar dene</button></div></section>;
  const cart = props.detail;
  return <PanelPageShell><Link className={styles.back} href="/orders/abandoned-carts">Terk Edilen Sepetlere dön</Link><PanelPageHeader title="Sepet ayrıntısı" description={`${customer(cart)} · sürüm ${cart.version}`} actions={props.canManage && cart.status !== "archived" ? <div className={styles.actions}>{cart.status === "abandoned" ? <button type="button" disabled={props.busy} onClick={props.onRecovered}><CheckCircle2 aria-hidden="true" />Kurtarıldı olarak işaretle</button> : null}<button type="button" disabled={props.busy} onClick={props.onArchive}><Archive aria-hidden="true" />Arşivle</button></div> : null} />{props.error ? <div className={styles.inlineError} role="alert">{props.error}</div> : null}{props.notice ? <div className={styles.notice} role="status">{props.notice}</div> : null}
    <section className={styles.detailHero} aria-label="Sepet özeti"><div><ShoppingCart /><span>Durum</span><PanelStatusBadge tone={tone(cart.status)}>{STATUS[cart.status]}</PanelStatusBadge></div><div><Wallet /><span>Toplam</span><strong>{money(cart.totalCents, cart.currency)}</strong></div><div><Package2 /><span>Ürün</span><strong>{cart.itemCount}</strong></div><div><Clock3 /><span>Son etkinlik</span><strong>{date(cart.lastActivityAt)}</strong></div></section>
    <div className={styles.detailGrid}><section className={styles.panel}><header><div><h2>Sepet ürünleri</h2><p>Kalıcı katalog anlık görüntüsü</p></div></header><div className={styles.items}>{cart.items.map((item) => <article key={item.id}>{item.imageUrl ? <img src={item.imageUrl} alt="" /> : <i><Package2 /></i>}<div><strong>{item.productName}</strong><span>{item.variantName ?? "Standart"}{item.sku ? ` · ${item.sku}` : ""}</span></div><span>{item.quantity} × {money(item.unitPriceCents, cart.currency)}</span><b>{money(item.lineTotalCents, cart.currency)}</b></article>)}</div><dl className={styles.totals}><div><dt>Ara toplam</dt><dd>{money(cart.subtotalCents, cart.currency)}</dd></div><div><dt>İndirim</dt><dd>− {money(cart.discountCents, cart.currency)}</dd></div><div><dt>Toplam</dt><dd>{money(cart.totalCents, cart.currency)}</dd></div></dl></section>
      <section className={styles.panel}><header><div><h2>Müşteri ve zaman</h2><p>Sepette bırakılan gerçek iletişim bilgileri</p></div></header><dl className={styles.customer}><div><dt><UserRound />Müşteri</dt><dd>{cart.customerName ?? "Anonim sepet"}</dd></div><div><dt><Mail />E-posta</dt><dd>{cart.customerEmail ?? "Belirtilmedi"}</dd></div><div><dt><Phone />Telefon</dt><dd>{cart.customerPhone ?? "Belirtilmedi"}</dd></div><div><dt><Clock3 />Sepet başlangıcı</dt><dd>{date(cart.checkoutStartedAt)}</dd></div><div><dt><RefreshCcw />Son etkinlik</dt><dd>{date(cart.lastActivityAt)}</dd></div></dl></section></div>
  </PanelPageShell>;
}

export function AbandonedCartDetailConsole({ cartId, canManage }: { cartId: string; canManage: boolean }) {
  const [state, setState] = useState<State>("loading"); const [detail, setDetail] = useState<AbandonedCartDetail>(); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setError(""); try { setDetail(await abandonedCartApi.get(cartId)); setState("loaded"); } catch (failure) { setError(message(failure)); setState("error"); } }, [cartId]); useEffect(() => { void load(); }, [load]);
  async function mutate(kind: "recovered" | "archive") { if (!detail || !canManage || busy) return; setBusy(true); setError(""); setNotice(""); try { if (kind === "recovered") await abandonedCartApi.markRecovered(cartId, detail.version); else await abandonedCartApi.archive(cartId, detail.version); await load(); setNotice(kind === "recovered" ? "Sepet kurtarıldı olarak işaretlendi." : "Sepet arşivlendi."); } catch (failure) { setError(message(failure)); if (failure instanceof AbandonedCartApiError && failure.code === "version_conflict") await load(); } finally { setBusy(false); } }
  return <AbandonedCartDetailPresentation state={state} detail={detail} error={error} notice={notice} busy={busy} canManage={canManage} onRetry={() => { setState("loading"); void load(); }} onRecovered={() => void mutate("recovered")} onArchive={() => void mutate("archive")} />;
}
