"use client";

import { ArrowRight, Check, Clock3, Banknote, CreditCard, History, LockKeyhole, MapPin, Minus, Package, Pause, Percent, Plus, RefreshCw, ScanLine, ShieldCheck, Trash2, UserRound, X } from "lucide-react";
import { useEffect, useId, useMemo, useRef, useState, useSyncExternalStore, type FormEvent, type KeyboardEvent } from "react";
import type { InStoreDiscount, InStoreProduct, InStoreSale, InStoreStaffGrant } from "@celebix/saas-contracts";
import { PanelPageHeader, PanelPageShell, PanelStatusBadge } from "@/components/panel/PanelPageShell";
import { InStoreSalesUiError, inStoreSalesUi } from "@/lib/in-store-sales-ui/client";
import { InStoreRegisterController, message, parseMinorUnits, previewTotals } from "@/lib/in-store-sales-ui/model";
import styles from "./in-store-sales.module.css";

const money=(value:number)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(value/100);
const time=(value:string)=>new Intl.DateTimeFormat("tr-TR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value));
type DialogKind="price"|"discount"|"customer"|"held"|"pending"|"recent"|"unpaid"|"staff"|null;
const STAFF_ROLE_LABELS:Readonly<Record<string,string>>={store_owner:"Mağaza sahibi",admin:"Yönetici",cashier:"Kasiyer"};
const eligibleStaff=(grants:readonly InStoreStaffGrant[])=>grants.filter(grant=>Object.hasOwn(STAFF_ROLE_LABELS,grant.role));
const STATUS_LABELS={draft:"Taslak",held:"Bekletiliyor",payment_pending:"Tahsilat bekliyor",payment_received:"Ödeme beyanı alındı",completed:"Tamamlandı",cancelled:"İptal"} as const;
type PricePreviewLine=Readonly<{unitPriceCents:number|null;catalogUnitPriceCents?:number;quantity:number;discountEligible:boolean}>;
function previewWithPermission(lines:readonly PricePreviewLine[],discount:InStoreDiscount|null,limitBps:number){
  try{
    const totals=previewTotals(lines.map(row=>({unitPriceCents:row.unitPriceCents??0,quantity:row.quantity,discountEligible:row.discountEligible})),discount);
    let catalogEligible=0n,reductions=0n;
    for(const row of lines){const catalog=BigInt(row.catalogUnitPriceCents??row.unitPriceCents??0),applied=BigInt(row.unitPriceCents??0),quantity=BigInt(row.quantity),reduction=catalog>applied?(catalog-applied)*quantity:0n;
      if(!row.discountEligible&&reduction>0n)return {totals,error:"Bu ürüne indirim uygulanamaz; birim fiyatı katalog fiyatının altına düşüremezsin.",reductionsCents:Number(reductions),limitCents:0};
      if(row.discountEligible)catalogEligible+=catalog*quantity;reductions+=reduction;
    }
    const limit=catalogEligible*BigInt(limitBps)/10000n;
    return {totals,error:reductions+BigInt(totals.discountCents)>limit?"Fiyat düşüşü ve sepet indirimi satış yetkinin sınırını aşıyor.":null,reductionsCents:Number(reductions),limitCents:Number(limit)};
  }catch{return {totals:null,error:"İndirim sepetin güncel tutarına uygun değil. İndirimi düzenle.",reductionsCents:0,limitCents:0};}
}
const paymentLabel=(method:InStoreSale["paymentMethod"])=>method==="cash"?"Nakit":method==="card"?"Kart · Harici POS":"Eski kayıt · Harici POS";
function ProductImage({imageUrl,name}:{imageUrl:string|null;name:string}) { return <span className={styles.thumbnail}>{imageUrl?<img src={imageUrl} alt="" loading="lazy" />:<Package aria-hidden="true" />}<span className="sr-only">{name}</span></span>; }

export function InStoreSalesConsole(){
  const [controller]=useState(()=>new InStoreRegisterController(inStoreSalesUi,()=>window.localStorage));
  const state=useSyncExternalStore(controller.subscribe,controller.getSnapshot,controller.getSnapshot);
  const [query,setQuery]=useState(""),[results,setResults]=useState<readonly InStoreProduct[]>([]),[searchBusy,setSearchBusy]=useState(false),[searchError,setSearchError]=useState<string|null>(null),[selected,setSelected]=useState(-1);
  const [dialog,setDialog]=useState<DialogKind>(null),[discountKind,setDiscountKind]=useState<"percentage"|"fixed_amount">("percentage"),[discountText,setDiscountText]=useState(""),[customer,setCustomer]=useState(""),[note,setNote]=useState("");
  const [priceVariant,setPriceVariant]=useState<string|null>(null),[priceText,setPriceText]=useState("");
  const [list,setList]=useState<readonly InStoreSale[]>([]),[nextCursor,setNextCursor]=useState<string|null>(null),[listBusy,setListBusy]=useState(false),[listError,setListError]=useState<string|null>(null),[staff,setStaff]=useState<readonly InStoreStaffGrant[]>([]),[staffBusy,setStaffBusy]=useState<string|null>(null);
  const queryRef=useRef(""),resultsTerm=useRef(""),resultsLocation=useRef(""),lookupGeneration=useRef(0);
  const scanRef=useRef<HTMLInputElement>(null),dialogRef=useRef<HTMLDialogElement>(null),returnFocus=useRef<HTMLElement|null>(null),discountRef=useRef<HTMLInputElement>(null),priceRef=useRef<HTMLInputElement>(null),customerRef=useRef<HTMLInputElement>(null),closeRef=useRef<HTMLButtonElement>(null);
  function updateQuery(value:string){queryRef.current=value;setQuery(value);}
  const resultsId=useId(),dialogTitleId=useId();const editable=controller.isEditable();
  const payment=state.sale?.status==="payment_pending",received=state.sale?.status==="payment_received",completed=state.sale?.status==="completed";
  const unknown=Boolean(state.recovery&&!state.busy),blocked=Boolean(state.busy),permissions=state.bootstrap?.permissions;
  const totalPreview=useMemo(()=>previewWithPermission(state.cart,state.discount,permissions?.discountLimitBps??0),[state.cart,state.discount,permissions?.discountLimitBps]);
  const totals=state.sale&&["payment_pending","payment_received","completed"].includes(state.sale.status)?state.sale.totals:totalPreview.totals;
  const focusScan=()=>requestAnimationFrame(()=>{if(controller.isEditable())scanRef.current?.focus();});
  useEffect(()=>{void controller.initialize();return()=>controller.dispose();},[controller]);
  useEffect(()=>{if(state.phase==="ready"&&!state.sale)focusScan();},[state.phase,state.sale?.id]);
  useEffect(()=>{
    const term=query.trim();setSelected(-1);if(resultsTerm.current!==term)setResults([]);if(!term||!editable){setResults([]);setSearchBusy(false);return;}
    const abort=new AbortController();const timer=setTimeout(()=>{setSearchBusy(true);setSearchError(null);void inStoreSalesUi.searchProducts({locationId:state.locationId,...(/^\d+$/.test(term)?{barcode:term}:{query:term})},abort.signal).then(products=>{if(!abort.signal.aborted&&queryRef.current.trim()===term&&controller.getSnapshot().locationId===state.locationId){resultsTerm.current=term;resultsLocation.current=state.locationId;setResults(products);setSearchBusy(false);}}).catch(error=>{if(!abort.signal.aborted&&queryRef.current.trim()===term){setSearchError(message(error));setResults([]);setSearchBusy(false);}});},200);
    return()=>{clearTimeout(timer);abort.abort();};
  },[query,state.locationId,editable]);
  useEffect(()=>{
    const element=dialogRef.current;if(!element)return;
    if(dialog){if(!element.open)element.showModal();requestAnimationFrame(()=>{if(dialog==="price")priceRef.current?.focus();else if(dialog==="discount")discountRef.current?.focus();else if(dialog==="customer")customerRef.current?.focus();else closeRef.current?.focus();});}
    else if(element.open)element.close();
  },[dialog]);
  function openDialog(kind:DialogKind){returnFocus.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setListError(null);setDialog(kind);
    if(kind==="discount"){setDiscountKind(state.discount?.kind??"percentage");setDiscountText(state.discount?String((state.discount.kind==="percentage"?state.discount.percentageBps:state.discount.amountCents)/100):"");}
    if(kind==="customer"){setCustomer(state.customerName);setNote(state.note);}
    if(kind==="held"||kind==="pending"||kind==="recent"){setList(kind==="held"?state.bootstrap?.heldSales??[]:kind==="pending"?state.bootstrap?.pendingSales??[]:state.bootstrap?.recentSales??[]);setNextCursor(null);void loadList(kind);}
    if(kind==="staff"){setListBusy(true);void inStoreSalesUi.listStaff().then(grants=>setStaff(eligibleStaff(grants))).catch(error=>setListError(message(error))).finally(()=>setListBusy(false));}
  }
  function openPrice(variantId:string){const row=state.cart.find(line=>line.variantId===variantId);if(!row||!editable||!permissions?.canEditPrice)return;setPriceVariant(variantId);setPriceText(row.unitPriceCents===null?"":String(row.unitPriceCents/100).replace(".",","));openDialog("price");}
  function closeDialog(){if(staffBusy)return;setDialog(null);}
  function dialogClosed(){setDialog(null);const target=returnFocus.current;if(target?.isConnected&&!target.hasAttribute("disabled"))target.focus();else focusScan();}
  async function loadList(kind:"held"|"pending"|"recent",cursor?:string){setListBusy(true);setListError(null);try{const page=await inStoreSalesUi.listSales({status:kind==="recent"?"completed":kind,...(cursor?{cursor}:{}),pageSize:20});setList(old=>cursor?[...old,...page.sales]:page.sales);setNextCursor(page.nextCursor);}catch(error){setListError(message(error));}finally{setListBusy(false);}}
  async function add(product:InStoreProduct){if(resultsTerm.current!==queryRef.current.trim()||resultsLocation.current!==controller.getSnapshot().locationId){setSearchError("Arama sonucu güncel değil. Ürünü yeniden ara.");return;}updateQuery("");setResults([]);setSearchError(null);await controller.addProduct(product);focusScan();}
  function submitScan(event:FormEvent){event.preventDefault();const value=queryRef.current.trim();if(!editable||!value)return;
    if(selected>=0&&results[selected]&&resultsTerm.current===value){void add(results[selected]);return;}
    const generation=++lookupGeneration.current;updateQuery("");setResults([]);setSelected(-1);setSearchError(null);
    void controller.lookup(value).then(result=>{
      if(result.matched){focusScan();return;}
      if(generation!==lookupGeneration.current||queryRef.current!=="")return;
      updateQuery(value);resultsTerm.current=value;resultsLocation.current=controller.getSnapshot().locationId;setResults(result.products);setSearchError(result.products.length?"Doğru renk ve bedeni sonuçlardan seç.":"Ürün bulunamadı. Başka bir barkod, ad veya SKU dene.");focusScan();
    });
  }
  function searchKeys(event:KeyboardEvent<HTMLInputElement>){if(event.key==="Escape"){updateQuery("");setResults([]);setSearchError(null);return;}if(["ArrowDown","ArrowUp"].includes(event.key)&&results.length){event.preventDefault();setSelected(old=>old<0?(event.key==="ArrowDown"?0:results.length-1):(old+(event.key==="ArrowDown"?1:-1)+results.length)%results.length);}}
  const priceRow=state.cart.find(row=>row.variantId===priceVariant),priceValue=parseMinorUnits(priceText);
  const pricePreview=priceRow&&priceValue!==null&&priceValue>0?previewWithPermission(state.cart.map(row=>row.variantId===priceVariant?{...row,catalogUnitPriceCents:row.catalogUnitPriceCents??row.unitPriceCents??0,unitPriceCents:priceValue}:row),state.discount,permissions?.discountLimitBps??0):null;
  const priceError=dialog==="price"?(priceValue===null?(priceText.trim()?"En fazla iki ondalık basamakla geçerli tutar gir.":null):priceValue<1?"Birim fiyat sıfırdan büyük olmalı.":pricePreview?.error??null):null;
  function applyPrice(event:FormEvent){event.preventDefault();if(!editable||!permissions?.canEditPrice||!priceRow||priceError||priceValue===null||priceValue<1)return;controller.setUnitPrice(priceRow.variantId,priceValue===(priceRow.catalogUnitPriceCents??priceRow.unitPriceCents)?null:priceValue);closeDialog();}
  let discountDraft:InStoreDiscount|null=null,discountError:string|null=null,discountTotals=totals;
  if(dialog==="discount"){
    const value=parseMinorUnits(discountText);if(value===null)discountError=discountText.trim()?"En fazla iki ondalık basamakla geçerli değer gir.":null;
    else if(discountKind==="percentage"&&value>=10000)discountError="İndirim %100’den küçük olmalı.";
    else{discountDraft=value===0?null:discountKind==="percentage"?{kind:"percentage",percentageBps:value}:{kind:"fixed_amount",amountCents:value};const preview=previewWithPermission(state.cart,discountDraft,permissions?.discountLimitBps??0);discountTotals=preview.totals;discountError=preview.error;}
  }
  function applyDiscount(event:FormEvent){event.preventDefault();if(!editable||discountError||parseMinorUnits(discountText)===null)return;controller.setDiscount(discountDraft);closeDialog();}
  const paymentMethod=(payment||received||completed?state.sale?.paymentMethod??state.paymentMethod:state.paymentMethod)??null;
  const cash=paymentMethod==="cash",card=paymentMethod==="card";
  const canChoosePayment=(editable||payment&&state.sale?.paymentMethod==null)&&!blocked&&!unknown&&!state.conflict;
  const paymentInstructions=payment?cash?(state.paymentResumed?"Önce nakit tahsilatını kontrol et. Ödeme alındıysa tekrar tahsilat yapma; yalnız ödemeyi aldığını onayla. Alınmadığından eminsen bu tutarı nakit tahsil et.":"Bu tutarı nakit tahsil et. Tahsilat tamamlanınca ödemeyi aldığını onayla."):card?(state.paymentResumed?"Önce fiziksel POS slipini kontrol et. Ödeme alındıysa tekrar tahsilat yapma; yalnız ödemeyi aldığını onayla. Alınmadığından eminsen bu tutarla tahsil et.":"Bu tutarı fiziksel POS’a gir. Tahsilat tamamlanınca ödemeyi aldığını onayla."):"Önce tahsilatı kontrol et. Ödeme alındıysa tekrar tahsilat yapma. Alınan veya alınacak ödeme yöntemini seçip onayla.":"Sonuç doğrulanana kadar tutarı ve sepeti değiştirme.";
  const paymentAmountLabel=payment?(state.paymentResumed?"Kontrol edilecek tutar":cash?"Nakit tahsil edilecek tutar":card?"POS’a girilecek tutar":"Tahsil edilecek tutar"):received||completed?"Tahsil edilen tutar":"Ödenecek tutar";
  const checkoutNote=received||unknown?"Tekrar tahsilat yapma. Aynı satış kaydı korunuyor.":payment?(cash?(state.paymentResumed?"Önce nakit tahsilatını kontrol et; alınmış ödemeyi yeniden tahsil etme.":"Nakit tahsilatı tamamlandıktan sonra onayla."):card?(state.paymentResumed?"Önce POS slipini kontrol et; alınmış ödemeyi yeniden tahsil etme.":"Fiziksel POS ödemesi tamamlandıktan sonra onayla."):"Ödemeyi onaylamadan önce Kart veya Nakit seç."):state.dirty?"Sepet sunucuya kaydediliyor.":completed?"Yeni satış için boş bir sepet açılır.":cash?"Tutarı nakit tahsil edeceksin.":card?"Tutarı fiziksel POS cihazına gireceksin.":"Devam etmek için Kart veya Nakit seç.";
  async function primary(){if(unknown){await controller.recover(true);return;}if(completed){await controller.newSale();focusScan();return;}if(payment||received){await controller.finish();return;}await controller.prepare();}
  const primaryLabel=state.busy==="prepare"?"Tutar hazırlanıyor…":state.busy==="payment"?"Ödeme beyanı kaydediliyor…":state.busy==="complete"?"Satış kaydediliyor…":state.busy==="recover"?"Satış kontrol ediliyor…":unknown?"Aynı satışın durumunu kontrol et":completed?"Yeni satış":received?"Satışı kaydetmeyi yeniden dene":payment?(cash?"Nakit ödemeyi aldım — Satışı tamamla":card?"Kart ödemesini aldım — Satışı tamamla":"Ödemeyi aldım — Satışı tamamla"):"Ödemeye geç";
  const primaryDisabled=blocked||Boolean(state.conflict)||!permissions?.canSell||(!unknown&&!completed&&!received&&!paymentMethod)||(!unknown&&!completed&&!payment&&!received&&(!state.cart.length||!totals||totals.totalCents<1||!state.locationId||Boolean(totalPreview.error)));
  async function saveGrant(grant:InStoreStaffGrant,form:HTMLFormElement){if(!Object.hasOwn(STAFF_ROLE_LABELS,grant.role))return;const fields=new FormData(form);const cap=parseMinorUnits(String(fields.get("discount")??"0"));if(cap===null||cap>9999){setListError("İndirim sınırı %0 ile %99,99 arasında olmalı.");return;}setStaffBusy(grant.membershipId);setListError(null);try{const updated=await inStoreSalesUi.setStaffGrant(grant.membershipId,{expectedVersion:grant.version,enabled:fields.get("enabled")==="on",locationIds:fields.getAll("location").map(String),discountLimitBps:cap,canEditPrice:fields.get("canEditPrice")==="on"},inStoreSalesUi.newId());setStaff(old=>old.map(x=>x.membershipId===updated.membershipId?updated:x));await controller.refreshLists();}catch(error){
    setListError(message(error));
    if(error instanceof InStoreSalesUiError&&(error.unknownResult||error.code==="version_conflict")){
      try{setStaff(eligibleStaff(await inStoreSalesUi.listStaff()));setListError("Güncel yetkiler yüklendi. Yeniden kaydetmeden önce ayarları kontrol et.");}catch{setListError("Yetki değişikliğinin sonucu doğrulanamadı. Pencereyi yeniden açıp güncel ayarları kontrol et.");}
    }
  }finally{setStaffBusy(null);}}
  if(state.phase==="loading")return <PanelPageShell><PanelPageHeader title="Mağaza satışı" /><h1 className="sr-only">Mağaza satışı</h1><div className={styles.loading} role="status">Satış alanı hazırlanıyor…</div></PanelPageShell>;
  if(state.phase==="error")return <PanelPageShell><PanelPageHeader title="Mağaza satışı" /><h1 className="sr-only">Mağaza satışı</h1><div className={styles.error} role="alert"><p>{state.error}</p><button className={styles.secondary} onClick={()=>void controller.initialize()}>Yeniden dene</button></div></PanelPageShell>;
  return <PanelPageShell><PanelPageHeader title="Mağaza satışı" /><h1 className="sr-only">Mağaza satışı</h1>
    <div className={styles.console}>
      <div className={styles.commandbar}><label className={styles.location}><MapPin aria-hidden="true" /><span className="sr-only">Satış deposu</span><select value={state.locationId} onChange={event=>{lookupGeneration.current++;setResults([]);resultsTerm.current="";controller.setLocation(event.target.value);}} disabled={!editable}><option value="" disabled>Depo seç</option>{state.bootstrap?.locations.map(location=><option key={location.id} value={location.id}>{location.name}</option>)}</select></label>
        <div className={styles.secondaryActions}><button className={styles.secondary} onClick={()=>openDialog("held")}><Clock3 aria-hidden="true" /><span>Bekletilenler</span><b>{state.bootstrap?.heldSales.length??0}</b></button><button className={styles.secondary} onClick={()=>openDialog("pending")}><ShieldCheck aria-hidden="true" /><span>Bekleyen satışlar</span><b>{state.bootstrap?.pendingSales.length??0}</b></button><button className={styles.secondary} onClick={()=>openDialog("recent")}><History aria-hidden="true" /><span>Son satışlar</span></button>{permissions?.canManageStaff?<button className={styles.iconButton} aria-label="Satış yetkileri" title="Satış yetkileri" onClick={()=>openDialog("staff")}><UserRound aria-hidden="true" /></button>:null}</div>
      </div>
      {!permissions?.canSell?<div className={styles.banner} role="status"><LockKeyhole aria-hidden="true" /><p>Mağaza satışı için yetki gerekiyor. Satış yetkilerini mağaza yöneticisi düzenleyebilir.</p></div>:null}
      {state.error?<div className={styles.error} role="alert"><p>{state.error}</p>{state.canReenterDraft?<button className={styles.secondary} onClick={()=>void controller.reenterDraft()} disabled={blocked}>{state.sale?"Sunucudaki taslağı yükle":"Ürünleri yeniden okut"}</button>:null}{state.conflict?<button className={styles.secondary} onClick={()=>state.canAcceptRecovery?void controller.acceptRecoveryCurrentSale():controller.acceptCurrentSale()} disabled={blocked}>Güncel sepeti yükle</button>:!unknown&&editable?<button className={styles.secondary} onClick={()=>void controller.flush().catch(()=>undefined)}><RefreshCw aria-hidden="true" />Kaydı yeniden dene</button>:null}{permissions?.canResolve&&state.sale?<button className={styles.secondary} onClick={()=>void controller.takeover()} disabled={blocked||unknown||Boolean(state.conflict)}>Satışı devral</button>:null}</div>:null}
      {state.notice?<div className={styles.notice} role="status">{state.notice}</div>:null}
      <div className={styles.layout}><div className={styles.mainColumn}>
        {!completed?<>
          {(payment||received||["prepare","payment","complete","recover"].includes(state.busy??""))?<div className={styles.banner} role="status"><LockKeyhole aria-hidden="true" /><div><strong>{received||state.busy==="complete"?"Ödeme beyanı saklandı":payment?(state.paymentResumed?"Bekleyen ödeme yeniden açıldı":"Sepet ödeme için sabitlendi"):"Satış kontrol ediliyor"}</strong><p>{received||state.busy==="complete"?"Aynı satış kaydedilecek. Yeniden tahsilat yapma.":paymentInstructions}</p></div></div>:null}
          <section className={styles.card}><form className={styles.scanCard} onSubmit={submitScan}><label htmlFor="in-store-scan">Barkod okut veya ürün ara</label><div className={styles.scanField}><ScanLine aria-hidden="true" /><input id="in-store-scan" ref={scanRef} value={query} onChange={event=>{lookupGeneration.current++;updateQuery(event.target.value);resultsTerm.current="";setResults([]);setSelected(-1);setSearchError(null);}} onKeyDown={searchKeys} autoComplete="off" placeholder="Barkod, ürün adı veya SKU" maxLength={128} disabled={!editable||!state.locationId} role="combobox" aria-expanded={results.length>0} aria-controls={resultsId} aria-activedescendant={selected>=0?`${resultsId}-${selected}`:undefined} aria-autocomplete="list" aria-describedby="in-store-scan-help" /><span aria-hidden="true">Enter ↵</span></div><p id="in-store-scan-help" className={styles.helper}>Aynı ürünü tekrar okutunca adedi artar.</p>
            {searchBusy?<p className={styles.helper} role="status">Ürünler aranıyor…</p>:null}{searchError?<p className={styles.fieldError} role="alert">{searchError}</p>:null}
            {results.length>0?<ul id={resultsId} className={styles.results} role="listbox" aria-label="Ürün sonuçları">{results.map((product,index)=><li key={product.variantId}><button id={`${resultsId}-${index}`} type="button" role="option" aria-selected={index===selected} className={index===selected?styles.selectedResult:undefined} onClick={()=>void add(product)} disabled={product.pricingUnavailable||product.unitPriceCents===null||(product.stockTracking&&product.availableQuantity<1)}><ProductImage imageUrl={product.imageUrl} name={product.productName} /><span><strong>{product.productName}</strong><small>{product.variantName}{product.sku?` · ${product.sku}`:""}</small><small>{product.stockTracking?`${product.availableQuantity} adet satılabilir`:"Stok takibi kapalı"}</small></span><b>{product.unitPriceCents===null?"Fiyat alınamadı":money(product.unitPriceCents)}</b></button></li>)}</ul>:null}
          </form></section>
          <section className={styles.card} aria-labelledby="in-store-cart-title"><header className={styles.cardHeader}><h2 id="in-store-cart-title">Sepet <span>{state.cart.reduce((sum,row)=>sum+row.quantity,0)} adet</span></h2><button className={styles.quiet} onClick={()=>void controller.hold().then(focusScan)} disabled={!editable||blocked||!state.cart.length}><Pause aria-hidden="true" />Beklet</button></header>
            {state.cart.length?<><div className={`${styles.cartGrid} ${styles.cartLabels}`} aria-hidden="true"><span /><span>Ürün</span><span>Birim</span><span>Adet</span><span>Tutar</span><span /></div>{state.cart.map(row=><div className={`${styles.cartGrid} ${styles.cartRow}`} key={row.variantId}><ProductImage imageUrl={row.imageUrl} name={row.productName} /><div className={styles.identity}><strong>{row.productName}</strong><small>{row.variantName}</small><small className={styles.mobileUnit}>{row.unitPriceCents===null?"Fiyat alınamadı":money(row.unitPriceCents)}</small>{row.unitPriceOverrideCents!=null?<small className={styles.priceOverride}>Satışa özel fiyat</small>:null}{!row.discountEligible?<small>İndirim uygulanmaz</small>:null}{editable&&permissions?.canEditPrice?<button className={`${styles.quiet} ${styles.priceAction}`} aria-label={`${row.productName} birim fiyatını düzenle`} onClick={()=>openPrice(row.variantId)}>Fiyatı düzenle</button>:null}</div><span className={styles.unitPrice}>{row.unitPriceCents===null?"—":money(row.unitPriceCents)}</span><div className={styles.quantity} aria-label={`${row.productName} adedi`}><button className={styles.iconButton} aria-label={`${row.productName} adedini azalt`} onClick={()=>{controller.setQuantity(row.variantId,row.quantity-1);if(row.quantity===1)focusScan();}} disabled={!editable}><Minus aria-hidden="true" /></button><span aria-live="polite">{row.quantity}</span><button className={styles.iconButton} aria-label={`${row.productName} adedini artır`} onClick={()=>controller.setQuantity(row.variantId,row.quantity+1)} disabled={!editable||row.quantity>=9999||(row.stockTracking&&row.quantity>=row.availableQuantity)}><Plus aria-hidden="true" /></button></div><strong className={styles.lineTotal}>{money((row.unitPriceCents??0)*row.quantity)}</strong><button className={`${styles.iconButton} ${styles.remove}`} aria-label={`${row.productName} ürününü çıkar`} onClick={()=>{controller.setQuantity(row.variantId,0);focusScan();}} disabled={!editable}><Trash2 aria-hidden="true" /></button></div>)}</>:<div className={styles.empty}><ScanLine aria-hidden="true" /><strong>Sepet satışa hazır</strong><p>Bir barkod okut veya ürün adıyla ara.</p></div>}
            <footer className={styles.detailBar}><button className={styles.quiet} onClick={()=>openDialog("customer")} disabled={!editable}><UserRound aria-hidden="true" />Müşteri / not ekle</button><span>{state.customerName||state.note&&"Not eklendi"||"İsteğe bağlı"}</span></footer>
          </section>
        </>:<section className={`${styles.card} ${styles.receipt}`} aria-live="polite"><span className={styles.successIcon}><Check aria-hidden="true" /></span><h2>Satış tamamlandı</h2><p>{state.sale?.orderNumber??state.sale?.saleNumber}<br />{state.sale?.completedAt?time(state.sale.completedAt):""} · Mağazadan teslim</p><dl className={styles.receiptTotals}><div><dt>Ara toplam</dt><dd>{money(state.sale!.totals.subtotalCents)}</dd></div><div><dt>İndirim</dt><dd>− {money(state.sale!.totals.discountCents)}</dd></div><div><dt>Tahsil edilen</dt><dd>{money(state.sale!.totals.totalCents)}</dd></div></dl><p>{paymentLabel(state.sale?.paymentMethod)} · Kasiyer beyanı<br />{state.cart.reduce((sum,row)=>sum+row.quantity,0)} adet ürün</p><button className={styles.quiet} onClick={()=>openDialog("recent")}>Son satışlarda görüntüle</button></section>}
      </div>
      <aside className={`${styles.card} ${styles.summary}`} aria-label="Ödeme özeti"><header><h2>Satış özeti</h2><span>{state.cart.length} ürün</span></header><dl className={styles.totals}><div><dt>Ara toplam</dt><dd>{money(totals?.subtotalCents??state.cart.reduce((sum,row)=>sum+(row.unitPriceCents??0)*row.quantity,0))}</dd></div><div><dt>İndirim{state.discount?.kind==="percentage"?` · %${state.discount.percentageBps/100}`:""}</dt><dd>− {money(totals?.discountCents??0)}</dd></div></dl>
        <button className={`${styles.secondary} ${styles.discountButton} ${state.discount?styles.applied:""}`} onClick={()=>openDialog("discount")} disabled={!editable||!permissions?.canDiscount||!state.cart.length}><Percent aria-hidden="true" />{state.discount?"İndirimi düzenle":"İndirim uygula"}</button>
        {totals&&totals.eligibleSubtotalCents<totals.subtotalCents?<p className={styles.helper}>İndirime uygun {money(totals.eligibleSubtotalCents)}. Bazı ürünlere indirim uygulanmaz.</p>:null}{totalPreview.error&&!payment&&!received&&!completed?<p className={styles.fieldError} role="alert">{totalPreview.error}</p>:null}
        {!received&&!completed?<fieldset className={styles.paymentChoice} aria-describedby="in-store-payment-help"><legend>Ödeme yöntemi</legend><div className={styles.segmented}><button type="button" aria-pressed={card} onClick={()=>controller.setPaymentMethod(card?null:"card")} disabled={!canChoosePayment}><CreditCard aria-hidden="true" />Kart</button><button type="button" aria-pressed={cash} onClick={()=>controller.setPaymentMethod(cash?null:"cash")} disabled={!canChoosePayment}><Banknote aria-hidden="true" />Nakit</button></div><p id="in-store-payment-help" className={styles.helper}>{!paymentMethod?"Devam etmek için ödeme yöntemi seç.":payment?(state.sale?.paymentMethod==null?"Ödeme onaylandığında yöntem kaydedilir.":"Hazırlanan satışın tutarı ve ödeme yöntemi korunur."):cash?"Nakit tahsilat":"Fiziksel POS ile kart tahsilatı"}</p></fieldset>:null}
        <div className={styles.totalBlock}><span>{paymentAmountLabel}</span><strong>{totals?money(totals.totalCents):"—"}</strong><small>Vergiler dahildir</small></div><p className={styles.paymentMethod}>{cash?<Banknote aria-hidden="true" />:<CreditCard aria-hidden="true" />}{received||completed?paymentLabel(state.sale?.paymentMethod):cash?"Nakit · Manuel tahsilat":card?"Kart · Harici POS":"Ödeme yöntemi seçilmedi"}</p>
        <div className={styles.checkoutFooter}><div className={styles.mobileTotal}><span>{paymentAmountLabel.replace(" tutar","")}</span><strong>{totals?money(totals.totalCents):"—"}</strong></div><button className={styles.primary} onClick={()=>void primary()} disabled={primaryDisabled}>{payment?<Check aria-hidden="true" />:completed?<Plus aria-hidden="true" />:<ArrowRight aria-hidden="true" />}{primaryLabel}</button>{payment&&!unknown?<button className={styles.quiet} onClick={()=>openDialog("unpaid")} disabled={blocked}>Ödeme alınmadı — Sepete dön</button>:null}<p className={styles.checkoutNote}>{checkoutNote}</p>{state.sale?<small className={styles.saleId}>{completed?state.sale.orderNumber??state.sale.saleNumber:state.sale.saleNumber} · {state.sale.ownerLabel}</small>:null}</div>
      </aside></div>
      <p className={styles.daySummary}>Bugün {state.bootstrap?.summary.completedCount??0} satış · Net {money(state.bootstrap?.summary.netCents??0)} · İndirim {money(state.bootstrap?.summary.discountCents??0)}</p>
    </div>
    <dialog ref={dialogRef} className={`${styles.dialog} ${["held","pending","recent","staff"].includes(dialog??"")?styles.drawer:""}`} aria-labelledby={dialogTitleId} onClose={dialogClosed} onCancel={event=>{if(staffBusy)event.preventDefault();else setDialog(null);}}><header className={styles.dialogHeader}><h2 id={dialogTitleId}>{dialog==="price"?"Birim fiyat":dialog==="discount"?"Sepet indirimi":dialog==="customer"?"Müşteri ve satış notu":dialog==="held"?"Bekletilen sepetler":dialog==="pending"?"Bekleyen satışlar":dialog==="recent"?"Son satışlar":dialog==="staff"?"Satış yetkileri":"Ödeme alınmadı mı?"}</h2><button ref={closeRef} className={styles.iconButton} aria-label="Pencereyi kapat" onClick={closeDialog} disabled={Boolean(staffBusy)}><X aria-hidden="true" /></button></header>
      {dialog==="price"&&priceRow?<form onSubmit={applyPrice}><div className={styles.dialogBody}><p className={styles.priceProduct}><strong>{priceRow.productName}</strong><span>{priceRow.variantName} · {priceRow.quantity} adet</span></p><p className={styles.catalogPrice}>Katalog fiyatı <strong>{money(priceRow.catalogUnitPriceCents??priceRow.unitPriceCents??0)}</strong></p><label className={styles.field}><span>Satış birim fiyatı · TL</span><input ref={priceRef} value={priceText} onChange={event=>setPriceText(event.target.value)} inputMode="decimal" autoComplete="off" aria-invalid={Boolean(priceError)} aria-describedby="in-store-price-help in-store-price-error" /></label><p id="in-store-price-help" className={styles.helper}>Bu fiyat bu varyantın tüm adedine uygulanır.</p><p className={styles.fieldError} id="in-store-price-error" role={priceError?"alert":undefined}>{priceError}</p><div className={styles.preview}><div><span>Ürün tutarı</span><strong>{priceValue!==null&&priceValue>0?money(priceValue*priceRow.quantity):"—"}</strong></div><div><span>Sepet toplamı</span><strong>{pricePreview?.totals?money(pricePreview.totals.totalCents):"—"}</strong></div></div><p className={styles.helper}>Fiyat düşüşü ve sepet indirimi için ortak sınır: {money(totalPreview.limitCents)}. Kesin tutar ödemeye geçerken doğrulanır.</p></div><footer className={styles.dialogActions}><button type="button" className={styles.quiet} onClick={()=>{if(editable&&permissions?.canEditPrice){controller.setUnitPrice(priceRow.variantId,null);closeDialog();}}} disabled={!editable||!permissions?.canEditPrice||priceRow.unitPriceOverrideCents==null}>Katalog fiyatına dön</button><button type="button" className={styles.secondary} onClick={closeDialog}>Vazgeç</button><button className={styles.primary} disabled={!editable||!permissions?.canEditPrice||Boolean(priceError)||priceValue===null||priceValue<1}>Uygula</button></footer></form>:null}
      {dialog==="discount"?<form onSubmit={applyDiscount}><div className={styles.dialogBody}><div className={styles.segmented} aria-label="İndirim türü"><button type="button" aria-pressed={discountKind==="percentage"} onClick={()=>{setDiscountKind("percentage");setDiscountText("");discountRef.current?.focus();}}>% Yüzde</button><button type="button" aria-pressed={discountKind==="fixed_amount"} onClick={()=>{setDiscountKind("fixed_amount");setDiscountText("");discountRef.current?.focus();}}>TL Tutar</button></div><label className={styles.field}><span>{discountKind==="percentage"?"İndirim yüzdesi":"İndirim tutarı"}</span><input ref={discountRef} value={discountText} onChange={event=>setDiscountText(event.target.value)} inputMode="decimal" autoComplete="off" aria-invalid={Boolean(discountError)} aria-describedby="in-store-discount-error" /></label><p className={styles.fieldError} id="in-store-discount-error" role={discountError?"alert":undefined}>{discountError}</p><div className={styles.preview}><div><span>İndirim</span><strong>− {money(discountTotals?.discountCents??0)}</strong></div><div><span>Ödenecek</span><strong>{discountTotals?money(discountTotals.totalCents):"—"}</strong></div></div>{permissions&&permissions.discountLimitBps<9999?<p className={styles.helper}>Yetki sınırı: %{permissions.discountLimitBps/100}</p>:null}</div><footer className={styles.dialogActions}><button type="button" className={styles.quiet} onClick={()=>{controller.setDiscount(null);closeDialog();}} disabled={!state.discount}>Kaldır</button><button type="button" className={styles.secondary} onClick={closeDialog}>Vazgeç</button><button className={styles.primary} disabled={!editable||Boolean(discountError)||parseMinorUnits(discountText)===null}>Uygula</button></footer></form>:null}
      {dialog==="customer"?<form onSubmit={event=>{event.preventDefault();controller.setCustomer(customer,note);closeDialog();}}><div className={styles.dialogBody}><label className={styles.field}><span>Müşteri adı · isteğe bağlı</span><input ref={customerRef} value={customer} onChange={event=>setCustomer(event.target.value)} maxLength={200} /></label><label className={styles.field}><span>Satış notu · isteğe bağlı</span><textarea value={note} onChange={event=>setNote(event.target.value)} maxLength={2000} rows={3} /></label></div><footer className={styles.dialogActions}><button type="button" className={styles.secondary} onClick={closeDialog}>Vazgeç</button><button className={styles.primary} disabled={!editable}>Kaydet</button></footer></form>:null}
      {dialog==="unpaid"?<><div className={styles.dialogBody}><p>{cash?"Nakit tahsil edilmediyse sepete dönebilirsin. Emin değilsen önce nakit tahsilatını kontrol et.":card?"Fiziksel POS cihazından ödeme alınmadıysa sepete dönebilirsin. Emin değilsen önce cihazdaki slipi kontrol et.":"Ödeme alınmadığından eminsen sepete dönebilirsin. Emin değilsen önce tahsilatı kontrol et."} Ürün, fiyat veya indirim değişince yeni tutar hazırlanır.</p></div><footer className={styles.dialogActions}><button className={styles.secondary} onClick={closeDialog}>Ödeme ekranında kal</button><button className={styles.primary} onClick={()=>{closeDialog();void controller.cancelUnpaid().then(focusScan);}} disabled={blocked||unknown}>Ödeme alınmadı — Sepete dön</button></footer></>:null}
      {["held","pending","recent"].includes(dialog??"")?<div className={styles.dialogBody}>{listBusy?<p role="status" className={styles.helper}>Satışlar yükleniyor…</p>:null}{listError?<p className={styles.fieldError} role="alert">{listError}</p>:null}{!list.length&&!listBusy?<p className={styles.listEmpty}>Bu listede satış bulunmuyor.</p>:null}{list.map(sale=><article className={styles.listEntry} key={sale.id}><header><strong>{sale.status==="completed"?[sale.customerName,sale.orderNumber??sale.saleNumber].filter(Boolean).join(" · "):sale.customerName??sale.saleNumber}</strong><strong>{money(sale.totals.totalCents)}</strong></header><p>{time(sale.updatedAt)} · {sale.items.reduce((sum,row)=>sum+row.quantity,0)} adet<br />{sale.ownerLabel} · {sale.locationName}{["payment_pending","payment_received","completed"].includes(sale.status)?<><br />{paymentLabel(sale.paymentMethod)}</>:null}</p><PanelStatusBadge tone={sale.status==="completed"?"success":"neutral"}>{STATUS_LABELS[sale.status]}</PanelStatusBadge>{dialog!=="recent"?<button className={styles.secondary} disabled={blocked||unknown||Boolean(state.sale&&["payment_pending","payment_received"].includes(state.sale.status))} onClick={()=>{closeDialog();void controller.openSale(sale.id).then(focusScan);}}>Satışa dön</button>:null}</article>)}{nextCursor&&dialog!==null?<button className={styles.secondary} onClick={()=>void loadList(dialog as "held"|"pending"|"recent",nextCursor)} disabled={listBusy}>Daha fazla</button>:null}</div>:null}
      {dialog==="staff"?<div className={styles.dialogBody}><p className={styles.helper}>Mevcut mağaza çalışanlarının satış deposu, fiyat ve indirim yetkisini düzenle.</p>{listBusy?<p role="status">Yetkiler yükleniyor…</p>:null}{listError?<p className={styles.fieldError} role="alert">{listError}</p>:null}{staff.map(grant=><form key={`${grant.membershipId}-${grant.version}`} className={styles.staffEntry} onSubmit={event=>{event.preventDefault();void saveGrant(grant,event.currentTarget);}}><strong>{grant.label}</strong><small>{STAFF_ROLE_LABELS[grant.role]}</small><label className={styles.checkbox}><input name="enabled" type="checkbox" defaultChecked={grant.enabled} disabled={Boolean(staffBusy)} />Mağaza satışı etkin</label><label className={styles.checkbox}><input name="canEditPrice" type="checkbox" defaultChecked={grant.canEditPrice??false} disabled={Boolean(staffBusy)} />Fiyat düzenleyebilir</label><fieldset disabled={Boolean(staffBusy)}><legend>Satış depoları</legend>{state.bootstrap?.locations.map(location=><label key={location.id} className={styles.checkbox}><input name="location" type="checkbox" value={location.id} defaultChecked={grant.locationIds.includes(location.id)} />{location.name}</label>)}</fieldset><label className={styles.field}><span>En yüksek indirim %</span><input name="discount" defaultValue={String(grant.discountLimitBps/100)} inputMode="decimal" disabled={Boolean(staffBusy)} /></label><button className={styles.secondary} disabled={Boolean(staffBusy)}>{staffBusy===grant.membershipId?"Kaydediliyor…":"Yetkiyi kaydet"}</button></form>)}</div>:null}
    </dialog>
  </PanelPageShell>;
}
