-- Actual disposable PostgreSQL fixture; no live writes.
BEGIN;
SET LOCAL ROLE celebix_saas_owner;
DO $test$
DECLARE st uuid:='a2010000-0000-4000-8000-000000000001';pr uuid:='a2010000-0000-4000-8000-000000000002';mb uuid:='a2010000-0000-4000-8000-000000000003';pl uuid:='a2010000-0000-4000-8000-000000000004';loc uuid;pd uuid:='a2010000-0000-4000-8000-000000000007';v uuid:='a2010000-0000-4000-8000-000000000008';sale uuid:='a2010000-0000-4000-8000-000000000010';op uuid:='a2010000-0000-4000-8000-000000000012';now_at timestamptz:='2026-10-02T10:00:00Z';r record;intent jsonb;contact jsonb;customer_id uuid;oid uuid;paid_at timestamptz;before_payload jsonb;cp uuid:='a2010000-0000-4000-8000-000000000041';cm uuid:='a2010000-0000-4000-8000-000000000040';n integer;
BEGIN
 IF to_regprocedure('saas.in_store_sales_prepare_v3(uuid,uuid,uuid,uuid,text,bigint,timestamp with time zone,uuid,text,uuid,bigint,bigint)') IS NULL THEN RAISE EXCEPTION 'V3 frozen credit sale preparation absent';END IF;
 INSERT INTO saas.stores(id,name,slug,status,locale,currency,theme_key,created_at,updated_at) VALUES(st,'POS credit regression','pos-credit-regression-201','active','tr','TRY','hemenaku',now_at,now_at);
 INSERT INTO saas.principals VALUES(pr,'https://qa.celebix.invalid','pos201','pos201@qa.celebix.invalid',true,now_at,now_at),(cp,'https://qa.celebix.invalid','pos201_cashier','cashier201@qa.celebix.invalid',true,now_at,now_at);
 INSERT INTO saas.memberships VALUES(mb,pr,st,'store_owner','active',now_at,now_at),(cm,cp,st,'cashier','active',now_at,now_at);
 INSERT INTO saas.plans VALUES(pl,'pos201_qa',1,'active',now_at-interval '1 day',NULL,now_at,now_at);
 ALTER TABLE saas.plan_features DISABLE TRIGGER plan_features_immutable;
 INSERT INTO saas.plan_features VALUES(pl,'orders',2,true),(pl,'catalog',1,true);
 ALTER TABLE saas.plan_features ENABLE TRIGGER plan_features_immutable;
 INSERT INTO saas.subscriptions VALUES('a2010000-0000-4000-8000-000000000013',st,pl,'pos201_qa',1,'active',now_at-interval '1 day',NULL,now_at,now_at);
 SELECT id INTO loc FROM saas.inventory_locations WHERE store_id=st AND is_default;
 INSERT INTO saas.products(id,store_id,slug,title,status,currency,created_at,updated_at) VALUES(pd,st,'pos-credit-product','POS Ürün','active','TRY',now_at,now_at);
 PERFORM set_config('saas.inventory.source_marker','catalog_adjustment',true);PERFORM set_config('saas.inventory.source_id',op::text,true);PERFORM set_config('saas.inventory.source_time',now_at::text,true);
 INSERT INTO saas.product_variants(id,store_id,product_id,title,barcode,price_cents,stock_tracking,stock_quantity,status,created_at,updated_at) VALUES(v,st,pd,'M','2010012345678',1100000,true,10,'active',now_at,now_at);
 SELECT * INTO r FROM saas.in_store_sales_set_staff_v3(st,pr,mb,pl,'pos201_qa',1,now_at,'a2010000-0000-4000-8000-000000000042',repeat('1',64),cm,0,true,ARRAY[loc],0,false,false,false);
 IF r.outcome<>'committed' OR r.result_payload->>'canSellOnCredit'<>'false' THEN RAISE EXCEPTION 'credit cashier defaults false: %',r;END IF;
 contact:=jsonb_build_object('firstName','Ali','lastName','Veli','phone','+905552010001','email',NULL);
 SELECT * INTO r FROM saas.in_store_sales_create_customer(st,cp,cm,pl,'pos201_qa',1,now_at,op,repeat('2',64),contact);
 IF r.outcome<>'committed' THEN RAISE EXCEPTION 'narrow cashier CRM create failed: %',r;END IF;
 customer_id:=(r.result_payload#>>'{customer,id}')::uuid;
 SELECT * INTO r FROM saas.in_store_sales_create_customer(st,cp,cm,pl,'pos201_qa',1,now_at,op,repeat('2',64),contact);
 IF r.outcome<>'operation_replayed' THEN RAISE EXCEPTION 'customer lost commit replay failed';END IF;
 SELECT * INTO r FROM saas.in_store_sales_create_customer(st,cp,cm,pl,'pos201_qa',1,now_at,'a2010000-0000-4000-8000-000000000014',repeat('3',64),contact);
 IF r.outcome<>'customer_duplicate' THEN RAISE EXCEPTION 'duplicate contact bypassed: %',r;END IF;
 SELECT * INTO r FROM saas.in_store_sales_search_customers(st,cp,cm,pl,'pos201_qa',1,now_at,'Ali',20);
 IF r.outcome<>'found' OR r.result_payload#>>'{customers,0,id}'<>customer_id::text THEN RAISE EXCEPTION 'POS contact search failed: %',r;END IF;
 SELECT * INTO r FROM saas.in_store_sales_search_customers(st,cp,cm,pl,'pos201_qa',1,now_at,'%',20);
 IF r.result_payload->'customers'<>'[]'::jsonb THEN RAISE EXCEPTION 'POS wildcard escaped search broadened contact data';END IF;
 SELECT * INTO r FROM saas.in_store_sales_search_customers('10000000-0000-4000-8000-000000000148',cp,cm,pl,'pos201_qa',1,now_at,'Ali',20);
 IF r.outcome<>'membership_denied' THEN RAISE EXCEPTION 'foreign tenant customer search permitted: %',r;END IF;
 IF EXISTS(SELECT 1 FROM saas.storefront_accounts WHERE store_id=st) THEN RAISE EXCEPTION 'POS created authentication account';END IF;
 intent:=jsonb_build_object('locationId',loc,'items',jsonb_build_array(jsonb_build_object('variantId',v,'quantity',1,'unitPriceOverrideCents',NULL)),'discount',NULL,'customerName',NULL,'note',NULL,'paymentMethod','cash','customerId',customer_id,'initialCollectionCents',500000,'dueDate','2026-11-01');
 SELECT * INTO r FROM saas.in_store_quote_v3(st,cm,now_at,jsonb_set(intent,'{initialCollectionCents}','1100001'));
 IF r.outcome<>'invalid_input' THEN RAISE EXCEPTION 'initial overpay permitted: %',r;END IF;
 SELECT * INTO r FROM saas.in_store_sales_create_v3(st,cp,cm,pl,'pos201_qa',1,now_at,'a2010000-0000-4000-8000-000000000015',repeat('4',64),sale,intent);
 IF r.outcome<>'committed' THEN RAISE EXCEPTION 'partial draft missing: %',r;END IF;
 SELECT * INTO r FROM saas.in_store_sales_prepare_v3(st,cp,cm,pl,'pos201_qa',1,now_at,'a2010000-0000-4000-8000-000000000016',repeat('5',64),sale,1,1100000);
 IF r.outcome NOT IN('credit_denied','feature_not_enabled') THEN RAISE EXCEPTION 'cashier without credit grant prepared debt: %',r;END IF;
 UPDATE saas.in_store_staff_grants SET can_sell_on_credit=true WHERE membership_id=cm;
 UPDATE saas.accounting_release_state SET credit_sales_enabled=false;
 SELECT * INTO r FROM saas.in_store_sales_prepare_v3(st,cp,cm,pl,'pos201_qa',1,now_at,'a2010000-0000-4000-8000-000000000016',repeat('5',64),sale,1,1100000);
 IF r.outcome<>'feature_not_enabled' THEN RAISE EXCEPTION 'rollout gate bypassed: %',r;END IF;
 UPDATE saas.accounting_release_state SET credit_sales_enabled=true;
 SELECT * INTO r FROM saas.in_store_sales_prepare_v3(st,cp,cm,pl,'pos201_qa',1,now_at,'a2010000-0000-4000-8000-000000000016',repeat('5',64),sale,1,1100000);
 IF r.outcome<>'committed' OR r.result_payload#>>'{sale,status}'<>'payment_pending' THEN RAISE EXCEPTION 'partial prepare failed: %',r;END IF;
 UPDATE saas.customers SET first_name='Changed',phone='+905552019999' WHERE id=customer_id;
 UPDATE saas.product_variants SET price_cents=1200000 WHERE id=v;
 SELECT * INTO r FROM saas.in_store_sales_confirm_payment_v3(st,cp,cm,pl,'pos201_qa',1,now_at+interval '1 hour','a2010000-0000-4000-8000-000000000017',repeat('6',64),sale,2,'receipt-201',NULL);
 IF r.outcome<>'committed' OR (SELECT amount_cents FROM saas.in_store_payment_attestations WHERE sale_id=sale)<>500000 THEN RAISE EXCEPTION 'immutable partial attestation failed: %',r;END IF;
 before_payload:=r.result_payload;
 SELECT * INTO r FROM saas.in_store_sales_complete_v2(st,cp,cm,pl,'pos201_qa',1,now_at+interval '2 hours','a2010000-0000-4000-8000-000000000018',repeat('7',64),sale,3);
 IF r.outcome<>'client_upgrade_required' THEN RAISE EXCEPTION 'old mutator altered credit sale';END IF;
 SELECT * INTO r FROM saas.in_store_sales_complete_v3(st,pr,mb,pl,'pos201_qa',1,now_at+interval '2 hours','a2010000-0000-4000-8000-000000000018',repeat('7',64),sale,3);
 IF r.outcome<>'committed' OR r.result_payload#>>'{sale,finance,dueCents}'<>'600000' OR r.result_payload#>>'{sale,customer,firstName}'<>'Ali' THEN RAISE EXCEPTION 'frozen partial completion failed: %',r;END IF;
 oid:=(r.result_payload#>>'{sale,orderId}')::uuid;
 IF (SELECT payment_status FROM saas.orders WHERE id=oid)<>'pending' OR (SELECT status FROM saas.orders WHERE id=oid)<>'delivered' OR (SELECT total_cents FROM saas.orders WHERE id=oid)<>1100000 THEN RAISE EXCEPTION 'credit order delivery/debt drift';END IF;
 IF r.result_payload#>>'{sale,finance,receipts,0,receivedAt}'<>to_char((now_at+interval '1 hour') AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') OR r.result_payload#>>'{sale,finance,receipts,0,actorMembershipId}'<>cm::text THEN RAISE EXCEPTION 'receipt completion date/actor invented';END IF;
 SELECT * INTO r FROM saas.in_store_sales_get_operation_v3(st,cp,cm,pl,'pos201_qa',1,now_at+interval '2 hours','a2010000-0000-4000-8000-000000000017',repeat('6',64));
 IF r.result_payload#>>'{sale,initialCollectionCents}'<>'500000' OR r.result_payload#>>'{sale,status}'<>'payment_received' THEN RAISE EXCEPTION 'uncertain confirmation replay evidence changed';END IF;
 SELECT * INTO r FROM saas.in_store_sales_complete_v3(st,pr,mb,pl,'pos201_qa',1,now_at+interval '2 hours','a2010000-0000-4000-8000-000000000018',repeat('7',64),sale,3);
 IF r.outcome<>'operation_replayed' OR (SELECT count(*) FROM saas.inventory_movements WHERE store_id=st AND source_kind='in_store_sale')<>1 OR (SELECT stock_quantity FROM saas.product_variants WHERE id=v)<>9 THEN RAISE EXCEPTION 'credit duplicate stock';END IF;
 FOR n IN 0..1 LOOP
  sale:=saas.inventory_deterministic_uuid('credit-fixture',n::text);intent:=jsonb_set(intent,'{initialCollectionCents}',CASE WHEN n=0 THEN '0' ELSE '1200000' END::jsonb);intent:=jsonb_set(intent,'{paymentMethod}',CASE WHEN n=0 THEN 'null' ELSE '"bank_transfer"' END::jsonb);
  IF n=1 THEN intent:=jsonb_set(intent,'{customerId}','null');UPDATE saas.accounting_release_state SET credit_sales_enabled=false;END IF;
  SELECT * INTO r FROM saas.in_store_sales_create_v3(st,pr,mb,pl,'pos201_qa',1,now_at,saas.inventory_deterministic_uuid('credit-create',n::text),repeat('a',64),sale,intent);
  IF r.outcome<>'committed' THEN RAISE EXCEPTION 'zero/full draft failed %',r;END IF;
  SELECT * INTO r FROM saas.in_store_sales_prepare_v3(st,pr,mb,pl,'pos201_qa',1,now_at,saas.inventory_deterministic_uuid('credit-prepare',n::text),repeat('b',64),sale,1,1200000);
  IF r.outcome<>'committed' THEN RAISE EXCEPTION 'zero/full prepare failed %',r;END IF;
  IF n=1 THEN SELECT * INTO r FROM saas.in_store_sales_confirm_payment_v3(st,pr,mb,pl,'pos201_qa',1,now_at,saas.inventory_deterministic_uuid('credit-confirm',n::text),repeat('c',64),sale,2,NULL,NULL);END IF;
  SELECT * INTO r FROM saas.in_store_sales_complete_v3(st,pr,mb,pl,'pos201_qa',1,now_at,saas.inventory_deterministic_uuid('credit-complete',n::text),repeat('d',64),sale,CASE WHEN n=0 THEN 2 ELSE 3 END);
  IF r.outcome<>'committed' OR (n=0 AND (r.result_payload#>>'{sale,paymentReceivedAt}' IS NOT NULL OR EXISTS(SELECT 1 FROM saas.in_store_payment_attestations WHERE sale_id=sale))) OR (n=1 AND r.result_payload#>>'{sale,finance,status}'<>'paid') THEN RAISE EXCEPTION 'zero/full completion failed %',r;END IF;
  IF n=1 THEN oid:=(r.result_payload#>>'{sale,orderId}')::uuid;SELECT * INTO r FROM saas.orders_get_with_archive_v2(st,pr,mb,pl,'pos201_qa',1,now_at,oid);IF r.outcome<>'found' OR r.result_payload->>'inStorePaymentMethod'<>'bank_transfer' THEN RAISE EXCEPTION 'order detail dropped bank transfer method: %',r;END IF;END IF;
 END LOOP;
 IF EXISTS(SELECT 1 FROM saas.payment_attempts WHERE store_id=st) THEN RAISE EXCEPTION 'POS credit admitted provider payment attempt';END IF;
 UPDATE saas.customers SET status='archived',archived_at=now_at WHERE id=customer_id;
 SELECT * INTO r FROM saas.in_store_sales_create_customer(st,cp,cm,pl,'pos201_qa',1,now_at,'a2010000-0000-4000-8000-000000000050',repeat('e',64),jsonb_set(contact,'{phone}','"+905552019999"'));
 IF r.outcome<>'customer_archived' OR (SELECT status FROM saas.customers WHERE id=customer_id)<>'archived' THEN RAISE EXCEPTION 'archived duplicate reactivated';END IF;
 SELECT * INTO r FROM saas.in_store_sales_search_customers(st,cp,cm,pl,'pos201_qa',1,now_at,'Changed',20);
 IF r.result_payload#>>'{customers,0,archived}'<>'true' THEN RAISE EXCEPTION 'open account archived customer hidden';END IF;
 IF (SELECT count(*) FROM saas.inventory_movements WHERE store_id=st AND source_kind='in_store_sale')<>3 THEN RAISE EXCEPTION 'three completed sales should consume three stocks';END IF;
END $test$;
ROLLBACK;
