import { acquirePostgresClient, type PostgresPoolLike, type PostgresTimeoutOptions } from '../postgres/pool.ts';
export type PlatformErrorCode = 'invalid_input'|'operator_denied'|'record_not_found'|'version_conflict'|'operation_mismatch'|'overpayment'|'already_reversed'|'limit_below_usage'|'pending_pos_blocks_downgrade'|'open_debt_blocks_downgrade'|'verified_identity_required'|'last_owner'|'staff_limit_reached'|'charge_below_collected'|'ownership_acceptance_required'|'invitation_acceptance_required'|'invitation_denied'|'support_denied'|'admin_host_unverified'|'operator_principal_unverified'|'not_found'|'unavailable'|'commit_unknown';
export class PlatformRepositoryError extends Error { constructor(readonly code:PlatformErrorCode){super(code);this.name='PlatformRepositoryError';} }
const codes:readonly string[]=['invalid_input','operator_denied','record_not_found','version_conflict','operation_mismatch','overpayment','already_reversed','limit_below_usage','pending_pos_blocks_downgrade','open_debt_blocks_downgrade','verified_identity_required','last_owner','staff_limit_reached','charge_below_collected','ownership_acceptance_required','invitation_acceptance_required','invitation_denied','support_denied','admin_host_unverified','operator_principal_unverified','not_found'];
const resources=['overview','stores','memberships','invitations','store-detail','usage','plans','subscriptions','billing','audit','operations','support-sessions'];
const actions=['plan.publish','subscription.assign','billing.period.create','billing.receipt.record','billing.receipt.reverse','billing.period.adjust','ownership.invite','membership.update','support.issue','support.revoke','sales.pause','sales.resume'];
function fail(code:PlatformErrorCode='invalid_input'):never{throw new PlatformRepositoryError(code);}
function uuid(value:unknown):string {if(typeof value!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(value))fail();return value;}
function json(value:unknown,max:number):string{if(!value||typeof value!=='object'||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)fail();let text:string;try{text=JSON.stringify(value);const parsed=JSON.parse(text);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))fail();}catch{fail();}if(Buffer.byteLength(text!,'utf8')>max)fail();return text!;}
export interface PlatformRepositoryOptions{pool:PostgresPoolLike;role:'celebix_saas_platform_operator';timeouts:PostgresTimeoutOptions}
/** Dedicated server pool only; immutable verified operator UUID must come from the identity resolver. */
export class PostgresPlatformRepository{
 private readonly options:PlatformRepositoryOptions;
 constructor(options:PlatformRepositoryOptions){if(options.role!=='celebix_saas_platform_operator'||!options.pool||typeof options.pool.connect!=='function')fail();for(const n of Object.values(options.timeouts))if(!Number.isSafeInteger(n)||n<1||n>60000)fail();this.options={...options,timeouts:{...options.timeouts}};}
 async read(operatorId:string,resource:string,query:Record<string,unknown>={}):Promise<Record<string,unknown>>{uuid(operatorId);if(!resources.includes(resource))fail();return this.execute('SELECT saas.platform_read($1::uuid,$2::text,$3::jsonb) AS result',[operatorId,resource,json(query,8192)],false);}
 async command(operatorId:string,action:string,payload:Record<string,unknown>,expectedVersion:number,idempotencyKey:string):Promise<Record<string,unknown>>{uuid(operatorId);if(!actions.includes(action)||!Number.isSafeInteger(expectedVersion)||expectedVersion<0||expectedVersion>=Number.MAX_SAFE_INTEGER||typeof idempotencyKey!=='string'||idempotencyKey.length<1||idempotencyKey.length>128||idempotencyKey!==idempotencyKey.trim()||/[\x00-\x1f\x7f]/.test(idempotencyKey))fail();return this.execute('SELECT saas.platform_command($1::uuid,$2::text,$3::jsonb,$4::bigint,$5::text) AS result',[operatorId,action,json(payload,16384),expectedVersion,idempotencyKey],true);}
 async resolveOperator(issuer:string,subject:string):Promise<Record<string,unknown>>{if(typeof issuer!=='string'||!issuer||issuer.length>2048||typeof subject!=='string'||!subject||subject.length>512)fail();return this.execute('SELECT saas.platform_operator_resolve($1::text,$2::text) AS result',[issuer,subject],false);}
 private async execute(sql:string,values:unknown[],write:boolean):Promise<Record<string,unknown>>{
  let client;try{client=await acquirePostgresClient(this.options.pool,this.options.timeouts.poolCheckoutMs);}catch{fail('unavailable');}
  let began=false,terminal=false;
  try{await client!.query(write?'BEGIN ISOLATION LEVEL READ COMMITTED':'BEGIN READ ONLY');began=true;const t=this.options.timeouts;
   for(const [name,value] of [['statement_timeout',t.statementMs],['lock_timeout',t.lockMs],['idle_in_transaction_session_timeout',t.idleTransactionMs]] as const)await client!.query(`SELECT pg_catalog.set_config('${name}',$1,true)`,[`${value}ms`]);
   await client!.query('SET LOCAL ROLE celebix_saas_platform_operator');const output=await client!.query(sql,values);const result=output.rows[0]?.result;if(output.rows.length!==1||!result||typeof result!=='object'||Array.isArray(result))fail('unavailable');
   try{await client!.query('COMMIT');terminal=true;client!.release();}catch{terminal=true;client!.release(true);fail(write?'commit_unknown':'unavailable');}return result as Record<string,unknown>;
  }catch(error){if(began&&!terminal){try{await client!.query('ROLLBACK');client!.release();}catch{client!.release(true);}}else if(!terminal)client!.release(true);
   if(error instanceof PlatformRepositoryError)throw error;const message=(error as {message?:unknown})?.message;if(typeof message==='string'&&codes.includes(message))fail(message as PlatformErrorCode);fail('unavailable');}
 }
}
