import assert from 'node:assert/strict';import test from 'node:test';import {readFile} from 'node:fs/promises';import ts from 'typescript';import React from 'react';import * as jsx from 'react/jsx-runtime';
async function page(path:string,imports:Record<string,unknown>){const source=await readFile(new URL(path,import.meta.url),'utf8');const code=ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const compiled={exports:{}as any};Function('require','module','exports',code)((name:string)=>{if(name==='react/jsx-runtime')return jsx;if(name in imports)return imports[name];throw Error(name);},compiled,compiled.exports);return compiled.exports;}
test("three canonical SEO pages resolve server capability and pass only safe view state",async()=>{
 for(const[file,name]of [['../../app/seo/page.tsx','SeoOverview'],['../../app/seo/content/page.tsx','SeoContent'],['../../app/seo/settings/page.tsx','SeoSettings']]){let access=0;const imports={'@celebix/saas-contracts':{isMerchantActionAllowed:(role:string,action:string)=>{assert.equal(role,'viewer');assert.equal(action,'integrations.manage');return false;}},'@/lib/server-access':{requireServerPanelAccess:async()=>{access++;return{tenantContext:{membership:{role:'viewer'}}};}},[`@/components/seo/${name}`]:{[name]:()=>null}};const module=await page(file!,imports);const rendered=await module.default({searchParams:Promise.resolve({kind:'category',tab:'sitemap',resourceId:'11111111-1111-4111-8111-111111111111','x-store-id':'foreign'})})as React.ReactElement<any>;assert.equal(access,1);assert.equal(rendered.props.canManage,false);assert.equal(rendered.props['x-store-id'],undefined);if(name==='SeoContent')assert.equal(rendered.props.initialKind,'category');if(name==='SeoOverview')assert.equal(rendered.props.initialTab,'sitemap');}
});
test("legacy edit and nested new edit routes preserve their record identity for safe server resolution",async()=>{
 for(const route of ['products','categories','pages','content','internal-linking','fast-indexing','geo-optimization','code-integrations'])for(const suffix of ['[recordId]/edit','new/[recordId]/edit']){const calls:any[]=[];const module=await page(`../../app/seo/${route}/${suffix}/page.tsx`,{'@/lib/seo-ui/legacy-route':{redirectLegacySeo:async(input:unknown)=>calls.push(input)}});await module.default({params:Promise.resolve({recordId:'11111111-1111-4111-8111-111111111111'}),searchParams:Promise.resolve({query:'Altın'})});assert.equal(calls[0]?.recordId,'11111111-1111-4111-8111-111111111111');assert.equal(calls[0]?.route,route);}
});
test("legacy resolution reads only the authenticated tenant record and never writes",async()=>{
 const id='11111111-1111-4111-8111-111111111111',resourceId='22222222-2222-4222-8222-222222222222',tenantContext={store:{id:'active-store'}};let read:any;let archived=false;
 const source=await readFile(new URL('./legacy-route.ts',import.meta.url),'utf8'),code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,compiled={exports:{}as any};
 const {legacySeoDestination}=await import('./model.ts');
 Function('require','module','exports',code)((name:string)=>{if(name==='server-only')return{};if(name==='next/navigation')return{redirect:(href:string)=>{throw Object.assign(new Error('redirect'),{href});}};if(name==='@/lib/server-access')return{requireServerPanelAccess:async()=>({tenantContext})};if(name==='@/lib/server-panel-access/default')return{resolveDefaultServerPanelAccessRuntime:async()=>({})};if(name==='@/lib/server-merchant-admin/runtime')return{resolveServerMerchantAdminRuntime:()=>({merchantAdmin:{get:async(input:any)=>{read=input;return{status:archived?'archived':'active',config:{resourceId}};}}})};if(name==='./model')return{legacySeoDestination};throw Error(name);},compiled,compiled.exports);
 const call=()=>compiled.exports.redirectLegacySeo({route:'products',kind:'seo_product_entry',recordId:id,searchParams:{'x-store-id':'foreign',query:'Altın'}});
 await assert.rejects(call(),(error:any)=>error.href===`/seo/content?kind=product&resourceId=${resourceId}&query=Alt%C4%B1n`);assert.equal(read.tenantContext,tenantContext);assert.equal(read.recordId,id);assert.equal(read.kind,'seo_product_entry');assert.equal(read['x-store-id'],undefined);
 archived=true;await assert.rejects(call(),(error:any)=>error.href.startsWith('/seo/content?kind=product&query=')&&!error.href.includes('resourceId='));
});
