import {createHash} from 'node:crypto';import {isIP} from 'node:net';
import {normalizeRestockEmail} from '../../../../packages/saas-contracts/src/restock-alerts/index.ts';
import type {PostgresPublicRestockRepository} from '../../../../packages/saas-data/src/restock-alerts/repository.ts';
import type {TrustedStorefrontHostAuthority} from '../trusted-host-authority.ts';
type Dependencies<T>=Readonly<{selectAuthority(headers:Headers):TrustedStorefrontHostAuthority;resolveRepository():Promise<T|null>;now():Date}>;
const json=(value:unknown,status:number)=>Response.json(value,{status,headers:{'cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer'}});
async function body(request:Request,hostname:string,path:string){const url=new URL(request.url);if(request.method!=='POST'||url.pathname!==path||url.search||url.hash||request.headers.get('origin')!==`https://${hostname}`||request.headers.get('content-type')!=='application/json'||request.headers.has('authorization')||request.headers.has('transfer-encoding')||!request.body)throw Error('invalid_input');const declared=request.headers.get('content-length');if(declared!==null&&(!/^(0|[1-9][0-9]*)$/u.test(declared)||Number(declared)>2048))throw Error('invalid_input');const reader=request.body.getReader();const chunks:Uint8Array[]=[];let bytes=0;try{for(;;){const part=await reader.read();if(part.done)break;bytes+=part.value.length;if(bytes>2048){await reader.cancel();throw Error('invalid_input');}chunks.push(part.value);}const all=new Uint8Array(bytes);let offset=0;for(const part of chunks){all.set(part,offset);offset+=part.length;}return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(all));}finally{reader.releaseLock();}}
const exact=(row:unknown,keys:readonly string[])=>{if(!row||typeof row!=='object'||Array.isArray(row)||Object.keys(row).sort().join(',')!==[...keys].sort().join(','))throw Error('invalid_input');return row as Record<string,unknown>;};
export function createRestockSubscribeRoute(deps:Dependencies<Pick<PostgresPublicRestockRepository,'subscribe'>>){return async(request:Request)=>{let authority;try{authority=deps.selectAuthority(request.headers);}catch{return json({code:'unavailable'},503);}if(authority.kind!=='trusted')return json({code:'unavailable'},503);let input;try{const row=exact(await body(request,authority.hostname,'/api/restock/subscribe'),['variantId','email','consent']);if(typeof row.variantId!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u.test(row.variantId)||row.consent!==true)throw Error('invalid_input');input={variantId:row.variantId,email:normalizeRestockEmail(row.email as string),consent:true as const};}catch{return json({code:'invalid_input'},400);}try{const repository=await deps.resolveRepository();if(!repository)return json({code:'unavailable'},503);const candidate=request.headers.get('cf-connecting-ip'),ip=candidate&&isIP(candidate)&&candidate===candidate.trim()?candidate:'unknown_client';await repository.subscribe({...input,hostname:authority.hostname,clientHash:createHash('sha256').update(`restock-v1:${authority.hostname}:${ip}`).digest('hex'),now:deps.now()});return json({outcome:'accepted'},200);}catch{return json({code:'unavailable'},503);}};}
export function createRestockManageRoute(deps:Dependencies<Pick<PostgresPublicRestockRepository,'manage'>>){return async(request:Request)=>{let authority;try{authority=deps.selectAuthority(request.headers);}catch{return json({code:'unavailable'},503);}if(authority.kind!=='trusted')return json({code:'unavailable'},503);let input;try{const row=exact(await body(request,authority.hostname,'/api/restock/manage'),['token','action']);if(typeof row.token!=='string'||!/^[A-Za-z0-9_-]{43}$/u.test(row.token)||!['confirm','cancel'].includes(row.action as string))throw Error('invalid_input');input={token:row.token,action:row.action as 'confirm'|'cancel'};}catch{return json({code:'invalid_input'},400);}try{const repository=await deps.resolveRepository();if(!repository)return json({code:'unavailable'},503);await repository.manage({...input,hostname:authority.hostname,now:deps.now()});return json({outcome:'accepted'},200);}catch{return json({code:'unavailable'},503);}};}
