import type {RestockDelivery,RestockWorkerRepository} from '../../../../packages/saas-data/src/restock-alerts/repository.ts';
export type RestockEmail=Readonly<{to:string;storeName:string;subject:string;html:string;text:string;idempotencyKey:string}>;
const escape=(text:string)=>text.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
export function renderRestockNotification(delivery:RestockDelivery):RestockEmail{
 const confirmation=delivery.kind==='confirmation',heading=confirmation?'Stok bildiriminizi onaylayın':'Beklediğiniz ürün yeniden stokta',link=confirmation?delivery.confirmUrl:delivery.productUrl,label=confirmation?'Bildirimi onayla':'Ürünü incele';
 const copy=confirmation?'Yalnız seçtiğiniz ürün ve seçenek tekrar geldiğinde bir kez e-posta almak için onaylayın. Bu bir pazarlama aboneliği değildir. Bağlantı 24 saat geçerlidir.':'Seçtiğiniz seçenek şu anda satın alınabilir. Stoklar değişebilir; bu bildirim ürün ayırmaz.';
 return Object.freeze({to:delivery.to,storeName:delivery.storeName,subject:`${delivery.storeName}: ${heading}`,idempotencyKey:delivery.idempotencyKey,text:`${heading}\n${delivery.productTitle} · ${delivery.variantTitle}\n${copy}\n\n${label}: ${link}\n\nBildirimi iptal et: ${delivery.cancelUrl}\nBu isteği siz yapmadıysanız onaylamayın.`,html:`<div style="font-family:Arial,sans-serif;max-width:520px;margin:auto;padding:32px;color:#202020"><p style="font-weight:700">${escape(delivery.storeName)}</p><h1 style="font-size:24px">${heading}</h1><h2 style="font-size:18px">${escape(delivery.productTitle)}</h2><p>${escape(delivery.variantTitle)}</p><p style="line-height:1.6;color:#555">${copy}</p><p style="margin:28px 0"><a href="${escape(link)}" style="display:inline-block;background:#202020;color:#fff;border-radius:8px;padding:14px 24px;text-decoration:none">${label}</a></p><p style="font-size:13px"><a href="${escape(delivery.cancelUrl)}">Bildirimi iptal et</a></p><p style="font-size:12px;color:#777">Bu isteği siz yapmadıysanız onaylamayın.</p></div>`});
}
export async function runRestockNotificationBatch(repository:RestockWorkerRepository,deps:Readonly<{now():Date;workerId:string;send(email:RestockEmail):Promise<Readonly<{kind:'accepted'|'retryable'|'failed';code?:string}>>}>){
 const items=await repository.claim({now:deps.now(),workerId:deps.workerId,limit:25}),counts={claimed:items.length,accepted:0,retried:0,failed:0,skipped:0,recordingErrors:0};
 // Two sequential pipelines bound email provider load across the shared cluster.
 let next=0;await Promise.all(Array.from({length:Math.min(2,items.length)},async()=>{while(next<items.length){const item=items[next++]!;try{const delivery=await repository.authorize({...item,workerId:deps.workerId,now:deps.now()});if(!delivery){counts.skipped++;continue;}let result:Readonly<{kind:'accepted'|'retryable'|'failed';code?:string}>;try{result=await deps.send(renderRestockNotification(delivery));}catch{result={kind:'retryable',code:'provider_network_error'};}
 const state=result.kind==='accepted'?'accepted':result.kind==='retryable'?'retry':'failed',error=result.kind==='accepted'?null:/^[a-z0-9_]{1,64}$/u.test(result.code??'')?result.code!:'provider_failed';await repository.finish({...item,workerId:deps.workerId,now:deps.now(),result:state,error});if(state==='accepted')counts.accepted++;else if(state==='retry')counts.retried++;else counts.failed++;}catch{counts.recordingErrors++;}}}));return Object.freeze(counts);
}
