import { lookup as dnsLookup } from "node:dns/promises";
import { isIP } from "node:net";
import { isPublicCatalogFeedAddress } from "../catalog-import/feed-authority.ts";

export const UMAMI_PRIVATE_ENVIRONMENT_FIELDS=Object.freeze(["CELEBIX_UMAMI_MODE","CELEBIX_UMAMI_API_BASE_URL","CELEBIX_UMAMI_USERNAME","CELEBIX_UMAMI_PASSWORD"] as const);
export type UmamiPrivateApiConfig=Readonly<{mode:"approved_staging";apiBaseUrl:string;username:string;password:string;timeoutMs:number;maximumResponseBytes:number;maximumMetricRows:number}>;
export type UmamiAddress=Readonly<{address:string;family:4|6}>;
export type UmamiResolver=(hostname:string)=>Promise<readonly UmamiAddress[]>;
function invalid():never{throw new Error("umami_config_invalid")}
function secret(value:unknown){if(typeof value!=="string"||value.length<1||value.length>1024||value!==value.trim()||/[\u0000-\u001f\u007f]/.test(value))invalid();return value}
async function defaultResolver(hostname:string):Promise<readonly UmamiAddress[]>{const values=await dnsLookup(hostname,{all:true,verbatim:true});return values.filter((value):value is {address:string;family:4|6}=>value.family===4||value.family===6).map((value)=>Object.freeze({address:value.address,family:value.family}))}
function addresses(value:unknown):readonly string[]{if(!Array.isArray(value)||value.length<1||value.length>32)invalid();const selected=value.map((entry)=>{if(!entry||typeof entry!=="object"||Array.isArray(entry))invalid();const record=entry as Record<string,unknown>;if(Object.keys(record).sort().join(",")!=="address,family"||typeof record.address!=="string"||(record.family!==4&&record.family!==6)||!isPublicCatalogFeedAddress(record.address))invalid();return`${record.family}:${record.address.toLowerCase()}`}).sort();if(new Set(selected).size!==selected.length)invalid();return Object.freeze(selected)}
export async function parseUmamiPrivateApiConfig(environment:Readonly<Record<string,string|undefined>>,resolver:UmamiResolver=defaultResolver):Promise<UmamiPrivateApiConfig|null>{
  try{if(!environment||typeof environment!=="object"||Array.isArray(environment)||typeof resolver!=="function")invalid();const raw=UMAMI_PRIVATE_ENVIRONMENT_FIELDS.map((field)=>environment[field]);if(raw.every((value)=>value===undefined||value===""))return null;if(raw.some((value)=>value===undefined||value===""))invalid();if(raw[0]!=="approved_staging")invalid();const base=secret(raw[1]),username=secret(raw[2]),password=secret(raw[3]);let url:URL;try{url=new URL(base)}catch{return invalid()}const hostname=url.hostname.toLowerCase();if(url.protocol!=="https:"||url.username||url.password||url.port||url.pathname!=="/"||url.search||url.hash||url.origin!==base||url.href!==`${base}/`||!hostname.includes(".")||isIP(hostname)!==0||hostname==="localhost"||hostname.endsWith(".localhost")||hostname.endsWith(".local")||hostname.endsWith(".internal"))invalid();let first:readonly string[],second:readonly string[];try{first=addresses(await resolver(hostname));second=addresses(await resolver(hostname))}catch{return invalid()}if(first.join("\n")!==second.join("\n"))invalid();return Object.freeze({mode:"approved_staging",apiBaseUrl:url.origin,username,password,timeoutMs:3000,maximumResponseBytes:262144,maximumMetricRows:100})}catch(error){if(error instanceof Error&&error.message==="umami_config_invalid")throw error;return invalid()}
}
