import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import test from 'node:test';
import {createContentResearchService} from './service.ts';

const id='11111111-1111-4111-8111-111111111111',sourceId='22222222-2222-4222-8222-222222222222',target={kind:'page',draftId:id,recordId:null,recordVersion:null} as const;
const tenant={schemaVersion:1,requestId:id,principal:{id,issuer:'https://identity.test',subject:'owner'},store:{id,slug:'test',status:'active'},membership:{id,role:'store_owner',status:'active'},entitlements:{schemaVersion:1,planId:id,planCode:'free_starter',version:1,status:'active',features:['catalog'],limits:{products:100,staff:5,storageBytes:100},validFrom:'2026-01-01T00:00:00.000Z'},locale:'tr'} as never;
const zero={sourcesAttempted:0,fetchedBytes:0,extractedBytes:0,elapsedMs:0};
const source=(url='https://source.example.test/')=>({id:sourceId,originalUrl:url,finalUrl:url,title:'Source',fetchedAt:'2026-09-29T12:00:00.000Z',contentSha256:createHash('sha256').update('Evidence text').digest('hex'),extractedText:'Evidence text',byteCount:13});
function fixture(fetch:(input:{url:string})=>Promise<ReturnType<typeof source>>){let row:any=null,fetches=0,claims=0,failures=0;const repository={async get(){if(!row)throw Object.assign(Error(),{code:'operation_not_found'});return row;},async begin(input:any){row={operationId:id,status:'pending',sources:[],usage:zero,safeCode:null,target,requestFingerprint:input.requestFingerprint,version:1,dispatchState:'not_dispatched',claimToken:null,leaseExpiresAt:'2026-09-29T12:01:00.000Z'};return{kind:'pending',operation:row};},async claim(){claims++;row={...row,version:2,dispatchState:'dispatched',claimToken:sourceId};return{claimToken:sourceId,version:2,leaseExpiresAt:'2026-09-29T12:01:00.000Z'};},async complete(input:any){row={...row,status:'completed',version:3,leaseExpiresAt:null,sources:input.sources,usage:input.usage};return row;},async fail(input:any){failures++;row={...row,status:input.dispatchState==='unknown'?'unknown':'failed',version:input.expectedVersion+1,leaseExpiresAt:null,sources:[],usage:input.usage,safeCode:input.safeCode,dispatchState:input.dispatchState};return row;}};
const service=createContentResearchService({repository:repository as never,fetcher:{fetch:async input=>{fetches++;return fetch(input);}},now:()=>new Date('2026-09-29T12:00:00.000Z'),deadlineMs:1000});return{service,counts:()=>({fetches,claims,failures}),row:()=>row};}
test('successful explicit research retains exact private evidence while safe result and replay omit text',async()=>{const f=fixture(async()=>source());const input={tenantContext:tenant,operationId:id,request:{target,urls:['https://source.example.test/']},signal:new AbortController().signal};const result=await f.service.research(input);assert.equal(result.status,'completed');assert.equal(result.sources.length,1);assert.equal('extractedText' in result.sources[0]!,false);assert.equal(f.row().sources[0].extractedText,'Evidence text');assert.deepEqual(f.counts(),{fetches:1,claims:1,failures:0});assert.deepEqual(await f.service.research(input),result);assert.deepEqual(f.counts(),{fetches:1,claims:1,failures:0});});
test('second-source failure records measured first source but never exposes partial evidence',async()=>{const f=fixture(async input=>{if(input.url.includes('second'))throw Object.assign(Error(),{code:'content_research_response_invalid'});return source();});const result=await f.service.research({tenantContext:tenant,operationId:id,request:{target,urls:['https://source.example.test/','https://second.example.test/']},signal:new AbortController().signal});assert.equal(result.status,'failed');assert.equal(result.safeCode,'content_research_response_invalid');assert.deepEqual(result.sources,[]);assert.equal(result.usage?.sourcesAttempted,2);assert.equal(result.usage?.fetchedBytes,13);assert.equal(result.usage?.extractedBytes,13);assert.deepEqual(f.row().sources,[]);assert.deepEqual(f.counts(),{fetches:2,claims:1,failures:1});});
test('ambiguous transport outcome is fenced unknown and never retried',async()=>{const f=fixture(async()=>{throw Object.assign(Error(),{code:'content_research_unavailable'});});const input={tenantContext:tenant,operationId:id,request:{target,urls:['https://source.example.test/']},signal:new AbortController().signal};const result=await f.service.research(input);assert.equal(result.status,'unknown');assert.equal(result.safeCode,'content_research_unavailable');assert.equal((await f.service.research(input)).status,'unknown');assert.deepEqual(f.counts(),{fetches:1,claims:1,failures:1});});
test('invalid source digest and changed idempotency input never produce a second fetch',async()=>{const f=fixture(async()=>({...source(),contentSha256:'0'.repeat(64)}));const input={tenantContext:tenant,operationId:id,request:{target,urls:['https://source.example.test/']},signal:new AbortController().signal};const result=await f.service.research(input);assert.equal(result.safeCode,'content_research_extraction_invalid');assert.equal(result.status,'failed');await assert.rejects(()=>f.service.research({...input,request:{target,urls:['https://changed.example.test/']}}),{code:'operation_mismatch'});assert.equal(f.counts().fetches,1);});
