import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import pg from 'pg';
import { parseContactWidgetConfig, createDefaultContactWidgetConfig } from '@celebix/saas-contracts';
import { startAccountingFixture } from '../accounting-ledger/fixture.mjs';

const migration = '202610030204_storefront_contact_widget';
const fixture = startAccountingFixture(203), pool = new pg.Pool({ ...fixture.connection, max: 6 });
const now = '2026-10-03T12:00:00.000Z', store = randomUUID(), otherStore = randomUUID(), principal = randomUUID(), analyst = randomUUID(), member = randomUUID(), otherMember = randomUUID(), analystMember = randomUUID(), widget = randomUUID();
const host = `contact-${store}.example.test`, otherHost = `contact-${otherStore}.example.test`;
const defaults = () => ({ schemaVersion: 1, enabled: false, title: 'Bize ulaşın', greeting: '', buttonLabel: 'İletişim', position: 'bottom-right', icon: 'message', theme: 'brand', devices: { desktop: true, mobile: true }, pages: ['home', 'products', 'categories', 'content', 'cart', 'search'], whatsappMessage: '', includeProductLink: false, hours: { enabled: false, timeZone: 'Europe/Istanbul', days: [1, 2, 3, 4, 5], opensAt: '09:00', closesAt: '18:00', outsideBehavior: 'message', outsideMessage: '' }, channels: [{ type: 'whatsapp', enabled: true, label: 'WhatsApp', value: '+905551112233' }] });
let plan, count = 0;
const check = async (label, run) => { await run(); console.log(`PASS ${++count} ${label}`); };
async function call(name, args, actor = {}) {
  const client = await pool.connect();
  try { await client.query('BEGIN;SET LOCAL ROLE celebix_saas_app'); const values = [actor.store ?? store, actor.principal ?? principal, actor.member ?? member, plan, 'free_starter', 1, now, ...args]; const result = await client.query(`SELECT outcome,result_payload FROM saas.${name}(${values.map((_, i) => `$${i + 1}`).join(',')})`, values); await client.query('COMMIT'); return result.rows[0]; }
  catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
}
function save(id, config, expected = null, patch = {}) {
  const fingerprint = patch.fingerprint ?? createHash('sha256').update(JSON.stringify([id, config, expected, patch.status ?? 'active'])).digest('hex');
  return call('merchant_admin_save', [patch.operation ?? randomUUID(), fingerprint, id, expected, patch.kind ?? 'contact_widget', 'İletişim balonu', JSON.stringify(config), patch.status ?? 'active'], patch.actor);
}
async function publicRead(hostname = host, at = now) {
  const client = await pool.connect();
  try { await client.query('BEGIN READ ONLY;SET LOCAL ROLE celebix_saas_host_resolver'); const result = await client.query('SELECT outcome,result_payload FROM saas.public_contact_widget_get($1,$2)', [hostname, at]); await client.query('COMMIT'); return result.rows[0]; }
  catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
}
const inventory = async () => (await pool.query("SELECT oid,oid::regprocedure::text identity,pg_get_functiondef(oid) definition,proowner owner,proacl::text acl,proconfig settings,prosecdef security,provolatile volatility,proisstrict strict FROM pg_proc WHERE pronamespace='saas'::regnamespace AND proname IN ('merchant_admin_required_action','merchant_admin_config_valid','merchant_admin_list','merchant_admin_list_events','merchant_admin_get_record','merchant_admin_save','merchant_admin_archive','resolve_public_storefront','public_starter_retail_presentation') ORDER BY oid::regprocedure::text")).rows;
try {
  plan = (await pool.query("SELECT id FROM saas.plans WHERE plan_code='free_starter' AND version=1")).rows[0].id;
  await pool.query("INSERT INTO saas.principals(id,issuer,subject,email,email_verified,created_at,updated_at) VALUES($1,'https://contact.invalid/oidc',$1::uuid::text,'owner@contact.invalid',true,'2026-01-01','2026-01-01'),($2,'https://contact.invalid/oidc',$2::uuid::text,'analyst@contact.invalid',true,'2026-01-01','2026-01-01')", [principal, analyst]);
  for (const [id, membership, hostname] of [[store, member, host], [otherStore, otherMember, otherHost]]) {
    await pool.query("INSERT INTO saas.stores(id,name,slug,status,locale,currency,theme_key,created_at,updated_at) VALUES($1,'Contact fixture',$2,'active','tr','TRY','hemenaku','2026-01-01','2026-01-01')", [id, `contact-${id}`]);
    await pool.query("INSERT INTO saas.memberships(id,principal_id,store_id,role,status,created_at,updated_at) VALUES($1,$2,$3,'store_owner','active','2026-01-01','2026-01-01')", [membership, principal, id]);
    await pool.query("INSERT INTO saas.subscriptions(id,store_id,plan_id,plan_code,plan_version,status,valid_from,created_at,updated_at) VALUES($1,$2,$3,'free_starter',1,'active','2026-01-01','2026-01-01','2026-01-01')", [randomUUID(), id, plan]);
    await pool.query("INSERT INTO saas.store_domains(id,store_id,hostname,hostname_type,status,is_primary,verified_at,created_at,updated_at) VALUES($1,$2,$3,'platform_subdomain','active',true,'2026-01-01','2026-01-01','2026-01-01')", [randomUUID(), id, hostname]);
  }
  await pool.query("INSERT INTO saas.memberships(id,principal_id,store_id,role,status,created_at,updated_at) VALUES($1,$2,$3,'analyst','active','2026-01-01','2026-01-01')", [analystMember, analyst, store]);
  const before = await inventory();
  if (!process.argv.includes('--baseline')) await check('204 exact rollback/reapply preserves every existing function identity and authority', async () => { fixture.apply(`${migration}.up.sql`); fixture.apply(`${migration}_assertions.sql`); const after = await inventory(); assert.deepEqual(after.map(({ definition, ...row }) => row), before.map(({ definition, ...row }) => row)); fixture.apply(`${migration}.down.sql`); assert.deepEqual(await inventory(), before); fixture.apply(`${migration}.up.sql`); fixture.apply(`${migration}_assertions.sql`); });
  await check('singleton record saves and active enabled config reaches only its own hostname', async () => { const config = { ...defaults(), enabled: true }; assert.equal((await save(widget, config)).outcome, 'saved'); assert.deepEqual((await publicRead()).result_payload, { storeId: store, config }); assert.deepEqual((await publicRead(otherHost)).result_payload, { storeId: otherStore, config: null }); });
  await check('list/get/events use existing durable scoped merchant APIs', async () => { assert.equal((await call('merchant_admin_list', ['contact_widget'])).result_payload.items[0].id, widget); assert.equal((await call('merchant_admin_get_record', ['contact_widget', widget])).result_payload.id, widget); assert.equal((await call('merchant_admin_list_events', ['contact_widget'])).result_payload.items.length, 1); assert.equal((await call('merchant_admin_get_record', ['contact_widget', widget], { store: otherStore, member: otherMember })).outcome, 'record_not_found'); });
  await check('disabled config stays singleton and is omitted from public reads', async () => { assert.equal((await save(widget, defaults(), 1)).outcome, 'saved'); assert.equal((await publicRead()).result_payload.config, null); assert.equal((await save(randomUUID(), defaults())).outcome, 'version_conflict'); assert.equal((await save(widget, defaults(), 1)).outcome, 'version_conflict'); });
  await check('operation replay is frozen, changed payload cannot reuse a key', async () => { const operation = randomUUID(); assert.equal((await save(widget, { ...defaults(), enabled: true }, 2, { operation })).outcome, 'saved'); assert.equal((await save(widget, { ...defaults(), enabled: true }, 2, { operation })).outcome, 'operation_replayed'); assert.equal((await save(widget, defaults(), 2, { operation })).outcome, 'operation_mismatch'); });
  await check('SQL strict schema rejects malformed config and hostile channel values', async () => { const bad = [{ ...defaults(), extra: true }, { ...defaults(), schemaVersion: 2 }, { ...defaults(), enabled: 'true' }, { ...defaults(), title: ' lead' }, { ...defaults(), title: 'x'.repeat(81) }, { ...defaults(), title: '\u00a0bad' }, { ...defaults(), greeting: 'bad\u001f' }, { ...defaults(), enabled: true, channels: [] }, { ...defaults(), enabled: true, devices: { desktop: false, mobile: false } }, { ...defaults(), enabled: true, pages: [] }, { ...defaults(), pages: ['home', 'home'] }, { ...defaults(), hours: { ...defaults().hours, timeZone: 'Invalid/Zone' } }, { ...defaults(), hours: { ...defaults().hours, days: [1, 1] } }, { ...defaults(), hours: { ...defaults().hours, opensAt: '18:00', closesAt: '18:00' } }, { ...defaults(), channels: [{ type: 'whatsapp', enabled: true, label: 'WhatsApp', value: 'javascript:alert(1)' }] }, { ...defaults(), channels: [{ type: 'email', enabled: true, label: 'Email', value: 'a@b.test?subject=x' }] }, { ...defaults(), channels: [{ type: 'contact_page', enabled: true, label: 'Contact', value: '//evil.test' }] }]; for (const config of bad) assert.equal((await save(widget, config, 3)).outcome, 'invalid_input', JSON.stringify(config)); assert.equal((await save(widget, defaults(), 3, { status: 'draft' })).outcome, 'invalid_input'); });
  await check('shared parser and SQL agree on malformed nested keys, null enums and channel bounds', async () => {
    const base = defaults(), cases = [base, createDefaultContactWidgetConfig(), { ...base, title: '🙂'.repeat(80) }, { ...base, title: '🙂'.repeat(81) }, { ...base, hours: { ...base.hours, timeZone: 'utc' } }, { ...base, hours: { ...base.hours, opensAt: '22:00', closesAt: '02:00' } }, { ...base, hours: { ...base.hours, timeZone: 'Factory' } }];
    for (const key of Object.keys(base)) { cases.push({ ...base, [key]: null }, { ...base, [key]: {} }); const missing = { ...base }; delete missing[key]; cases.push(missing); }
    for (const key of Object.keys(base.hours)) { cases.push({ ...base, hours: { ...base.hours, [key]: null } }); const missing = { ...base.hours }; delete missing[key]; cases.push({ ...base, hours: missing }); }
    const values = { whatsapp: ['+1234567', '+123456', '+123456789012345', '+1234567890123456', '05345556677'], phone: ['+442071234567', 'tel:+442071234567'], sms: ['+905551112233', 'sms:+905551112233'], email: ['A@example.test', 'a@example.t', 'a@EXAMPLE.test', 'a?b@example.test', 'a@' + 'x'.repeat(63) + '.test', 'a@' + 'x'.repeat(64) + '.test'], instagram: ['store', 'store_name', 'store.name', '.store', 'store.', 'st..ore', 'a'.repeat(30), 'a'.repeat(31)], telegram: ['store', 'stor', 'store_name', '1store'], messenger: ['store.name', 'store_name', 'store-name', 'a'.repeat(50), 'a'.repeat(51)], maps: ['ab', 'abc', 'İstanbul Türkiye', 'https://evil.test', '//evil.test', '<b>Place</b>'], contact_page: ['/pages/contact', '/pages/a-' + 'b'.repeat(140), '/pages/a-' + 'b'.repeat(151), '/pages/UPPER', '//evil.test'] };
    for (const [type, candidates] of Object.entries(values)) for (const value of candidates) cases.push({ ...base, channels: [{ type, value, enabled: true, label: 'Contact' }] });
    for (const config of cases) { let expected = true; try { parseContactWidgetConfig(config); } catch { expected = false; } const actual = (await pool.query('SELECT saas.contact_widget_config_valid($1::jsonb) valid', [JSON.stringify(config)])).rows[0].valid; assert.equal(actual, expected, JSON.stringify(config)); }
  });
  await check('shared parser and SQL agree on every PostgreSQL named zone and reject ICU-only aliases and offsets', async () => {
    const base = defaults();
    const rows = (await pool.query("SELECT name,saas.contact_widget_config_valid(jsonb_set($1::jsonb,'{hours,timeZone}',to_jsonb(name))) valid FROM pg_timezone_names", [JSON.stringify(base)])).rows;
    for (const row of rows) { let expected = true; try { parseContactWidgetConfig({ ...base, hours: { ...base.hours, timeZone: row.name } }); } catch { expected = false; } assert.equal(row.valid, expected, row.name); }
    for (const timeZone of ['+01:00', '-05:30', 'utc', 'EST5EDT', 'GMT+0', 'Etc/GMT+1', 'SystemV/EST5EDT', 'systemv/est5edt', 'Factory', 'posix/Europe/Istanbul', 'right/Europe/Istanbul', 'localtime', 'posixrules', 'ACT', 'AET', 'AGT', 'ART', 'AST', 'BET', 'BST', 'CAT', 'CNT', 'CST', 'CTT', 'EAT', 'ECT', 'IET', 'IST', 'JST', 'MIT', 'NET', 'NST', 'PLT', 'PNT', 'PRT', 'PST', 'SST', 'VST']) {
      const config = { ...base, hours: { ...base.hours, timeZone } }; let expected = true; try { parseContactWidgetConfig(config); } catch { expected = false; }
      assert.equal((await pool.query('SELECT saas.contact_widget_config_valid($1::jsonb) valid', [JSON.stringify(config)])).rows[0].valid, expected, timeZone);
    }
  });
  await check('all nine channel types have canonical SQL validation', async () => { const values = { whatsapp: '+905551112233', phone: '+442071234567', sms: '+905551112233', email: 'support@example.test', instagram: 'merchant.store', telegram: 'merchant_store', messenger: 'merchant.store', maps: 'İstanbul, Türkiye', contact_page: '/pages/contact' }; const config = { ...defaults(), channels: Object.entries(values).map(([type, value]) => ({ type, value, enabled: true, label: type })) }; assert.equal(fixture.value(`SELECT saas.contact_widget_config_valid('${JSON.stringify(config).replaceAll("'", "''")}'::jsonb)`), 't'); });
  await check('contact_page must be published in same store; public read filters later archive', async () => { const cfg = { ...defaults(), enabled: true, channels: [{ type: 'contact_page', enabled: true, label: 'İletişim', value: '/pages/contact' }] }; assert.equal((await save(widget, cfg, 3)).outcome, 'invalid_input');
    const foreignPage = randomUUID();
    await pool.query("INSERT INTO saas.merchant_admin_records(id,store_id,record_kind,name,config,status,created_at,updated_at) VALUES($1,$2,'page','Foreign locale','{\"slug\":\"foreign-contact\",\"locale\":\"en\",\"body\":\"Contact\",\"published\":true}', 'active','2026-01-01','2026-01-01')", [foreignPage, store]);
    assert.equal((await save(widget, { ...cfg, channels: [{ ...cfg.channels[0], value: '/pages/foreign-contact' }] }, 3)).outcome, 'invalid_input', 'foreign-locale-only page is absent at the fixed default-language route');
    await pool.query("INSERT INTO saas.merchant_admin_records(id,store_id,record_kind,name,config,status,created_at,updated_at) VALUES($1,$2,'page','Contact','{\"slug\":\"contact\",\"locale\":\"tr\",\"body\":\"Contact\",\"published\":true}', 'active','2026-01-01','2026-01-01')", [randomUUID(), otherStore]); assert.equal((await save(widget, cfg, 3)).outcome, 'invalid_input'); const page = randomUUID(); await pool.query("INSERT INTO saas.merchant_admin_records(id,store_id,record_kind,name,config,status,created_at,updated_at) VALUES($1,$2,'page','Contact','{\"slug\":\"contact\",\"locale\":\"tr\",\"body\":\"Contact\",\"published\":true}', 'active','2026-01-01','2026-01-01')", [page, store]); assert.equal((await save(widget, cfg, 3)).outcome, 'saved'); assert.deepEqual((await publicRead()).result_payload.config, cfg);
    const language = randomUUID();
    await pool.query("INSERT INTO saas.merchant_admin_records(id,store_id,record_kind,name,config,status,created_at,updated_at) VALUES($1,$2,'language_setting','Languages','{\"defaultLocale\":\"en\",\"enabledLocales\":[\"tr\",\"en\"]}', 'active','2026-01-01','2026-01-01')", [language, store]);
    assert.equal((await publicRead()).result_payload.config, null, 'changing default locale makes the old default-language link unavailable');
    await pool.query("UPDATE saas.merchant_admin_records SET config='{\"defaultLocale\":\"tr\",\"enabledLocales\":[\"tr\",\"en\"]}',version=version+1,updated_at=$2 WHERE id=$1", [language, now]);
    assert.deepEqual((await publicRead()).result_payload.config, cfg);
    await pool.query("UPDATE saas.merchant_admin_records SET status='archived',archived_at=$2,version=version+1,updated_at=$2 WHERE id=$1", [page, now]); assert.equal((await publicRead()).result_payload.config, null); });
  await check('foreign, disabled, future-verified hosts and inactive stores expose no widget', async () => { assert.equal((await publicRead('unknown.example.test')).outcome, 'not_found'); assert.equal((await publicRead(host.toUpperCase())).outcome, 'invalid_input'); assert.equal((await publicRead(host, '2025-12-31T00:00:00Z')).outcome, 'not_found'); await pool.query("UPDATE saas.store_domains SET status='disabled',is_primary=false,version=version+1,updated_at=$2 WHERE hostname=$1", [host, now]); assert.equal((await publicRead()).outcome, 'not_found'); await pool.query("UPDATE saas.store_domains SET status='active',is_primary=true,version=version+1,updated_at=$2 WHERE hostname=$1", [host, now]); await pool.query("UPDATE saas.stores SET status='suspended',updated_at=$2 WHERE id=$1", [store, now]); assert.equal((await publicRead()).outcome, 'not_found'); await pool.query("UPDATE saas.stores SET status='active',updated_at=$2 WHERE id=$1", [store, now]); });
  await check('analyst cannot mutate widget and table writes stay denied', async () => { assert.equal((await save(widget, defaults(), 4, { actor: { principal: analyst, member: analystMember } })).outcome, 'membership_denied'); assert.equal(fixture.value("SELECT has_table_privilege('celebix_saas_app','saas.merchant_admin_records','INSERT,UPDATE,DELETE')"), 'f'); assert.equal(fixture.value("SELECT has_function_privilege('celebix_saas_app','saas.public_contact_widget_get(text,timestamptz)','EXECUTE')"), 'f'); assert.equal(fixture.value("SELECT has_function_privilege('celebix_saas_host_resolver','saas.public_contact_widget_get(text,timestamptz)','EXECUTE')"), 't'); });
  await check('concurrent first saves commit one disabled singleton; same-operation retry replays', async () => { const config = defaults(); const outcomes = (await Promise.all([save(randomUUID(), config, null, { actor: { store: otherStore, member: otherMember } }), save(randomUUID(), config, null, { actor: { store: otherStore, member: otherMember } })])).map(row => row.outcome).sort(); assert.deepEqual(outcomes, ['saved', 'version_conflict']); const record = (await pool.query("SELECT id,version FROM saas.merchant_admin_records WHERE store_id=$1 AND record_kind='contact_widget'", [otherStore])).rows[0]; const operation = randomUUID(); const replay = (await Promise.all([save(record.id, config, record.version, { operation, actor: { store: otherStore, member: otherMember } }), save(record.id, config, record.version, { operation, actor: { store: otherStore, member: otherMember } })])).map(row => row.outcome).sort(); assert.deepEqual(replay, ['operation_replayed', 'saved']); });
  await check('archive uses existing authority and rollback refuses merchant data loss', async () => { assert.equal((await call('merchant_admin_archive', [randomUUID(), 'a'.repeat(64), widget, 4])).outcome, 'archived'); assert.equal((await publicRead()).result_payload.config, null); const rollback = fixture.sql(await import('node:fs').then(fs => fs.readFileSync(new URL(`../../../apps/owner/scripts/sql/saas/${migration}.down.sql`, import.meta.url), 'utf8')), true); assert.notEqual(rollback.status, 0); assert.match(rollback.stderr, /CONTACT_WIDGET_ROLLBACK_REQUIRES_DATA_RECOVERY/); });
  fixture.apply(`${migration}_assertions.sql`);
  console.log(`CONTACT_WIDGET_POSTGRESQL16_COMPLETE ${count}/${count}`);
} finally { await pool.end(); fixture.stop(); }
