import assert from 'node:assert/strict';
import test from 'node:test';
import { auditSeoHtml, deliverSeoBatch, isPublicAddress } from './seo-worker.ts';

test('private and special address ranges are denied before storefront fetch',()=>{for(const address of ['127.0.0.1','10.0.0.2','192.168.1.5','172.16.0.1','169.254.169.254','100.64.0.1','0.0.0.0','::1','fc00::1','fe80::1','::ffff:127.0.0.1'])assert.equal(isPublicAddress(address),false,address);assert.equal(isPublicAddress('1.1.1.1'),true);assert.equal(isPublicAddress('2606:4700:4700::1111'),true);});
test('audit checks actual canonical robots metadata and product schema without claiming Google indexing',()=>{const input={hostname:'store.example.com',path:'/urun/yuzuk',kind:'product' as const,resourceId:'11111111-1111-4111-8111-111111111111',allowIndex:true,effectiveTitle:'Yüzük | Mağaza',effectiveDescription:'Altın yüzük',effectiveCanonicalPath:'/urun/yuzuk'};const html='<title>Yüzük | Mağaza</title><meta content="Altın yüzük" name="description"><link href="https://store.example.com/urun/yuzuk" rel="canonical"><meta name="robots" content="index,follow"><script type="application/ld+json">{"@type":"Product","offers":{"@type":"Offer","price":"10","priceCurrency":"TRY"}}</script>';assert.deepEqual(auditSeoHtml(input,{status:200,html}),[]);const problems=auditSeoHtml(input,{status:200,html:html.replace('index,follow','noindex,follow').replace('https://store.example.com/urun/yuzuk','https://other.test/x').replace('"@type":"Product"','"@type":"Thing"')});assert.ok(problems.some(item=>item.code==='unexpected_noindex'));assert.ok(problems.some(item=>item.code==='canonical_mismatch'));assert.ok(problems.some(item=>item.code==='product_schema_missing'));assert.ok(auditSeoHtml(input,{status:404,html:''}).some(item=>item.code==='http_404'));});
function notification(id:string){return{id,storeId:'store',hostname:'store.example.com',key:'a'.repeat(32),path:'/urun/yuzuk',attempts:1,leaseId:'lease'};}
test('IndexNow sends exact keyLocation and records accepted response, never indexed status',async()=>{const finished:any[]=[],sent:any[]=[];const repo={claim:async()=>({notifications:[notification('n1')],checks:[]}),finishNotification:async(value:any)=>{finished.push(value);},finishCheck:async()=>{throw Error('unexpected')}};const result=await deliverSeoBatch(repo as never,{now:()=>new Date('2026-09-30T12:00:00Z'),workerId:'test',storefront:async()=>({status:200,html:'a'.repeat(32)}),indexNow:async(value:any)=>{sent.push(value);return{status:200};}});assert.equal(result.received,1);assert.equal(finished[0].status,'received');assert.equal(sent[0].keyLocation,'https://store.example.com/'+('a'.repeat(32))+'.txt');assert.deepEqual(sent[0].urlList,['https://store.example.com/urun/yuzuk']);});
test('202 remains verification pending and transient failure schedules bounded retry',async()=>{for(const status of [202,429,503]){const finished:any[]=[];const repo={claim:async()=>({notifications:[notification('n1')],checks:[]}),finishNotification:async(value:any)=>{finished.push(value);},finishCheck:async()=>{}};await deliverSeoBatch(repo as never,{now:()=>new Date('2026-09-30T12:00:00Z'),workerId:'test',storefront:async()=>({status:200,html:'a'.repeat(32)}),indexNow:async()=>({status})});assert.equal(finished[0].status,status===202?'verification_pending':'retrying');assert.ok(finished[0].nextAttemptAt instanceof Date);}});
test('invalid key file never submits and audit failures retain leased result rather than marking success',async()=>{let submissions=0;const finished:any[]=[];const repo={claim:async()=>({notifications:[notification('n1')],checks:[]}),finishNotification:async(value:any)=>{finished.push(value);},finishCheck:async()=>{}};await deliverSeoBatch(repo as never,{now:()=>new Date('2026-09-30T12:00:00Z'),workerId:'test',storefront:async()=>({status:200,html:'wrong'}),indexNow:async()=>{submissions++;return{status:200}}});assert.equal(submissions,0);assert.equal(finished[0].status,'retrying');assert.equal(finished[0].error,'key_verification_failed');});


test('bounded parallel checks complete other leases when one result cannot be recorded',async()=>{
  let active=0,peak=0;const recorded:string[]=[];
  const repo={claim:async()=>({notifications:[],checks:Array.from({length:8},(_,index)=>({id:String(index),leaseId:'lease',hostname:'store.example.com',path:'/',kind:null,resourceId:null}))}),finishNotification:async()=>{},finishCheck:async(value:any)=>{if(value.id==='0')throw Error('version_conflict');recorded.push(value.id);}};
  const result=await deliverSeoBatch(repo as never,{now:()=>new Date(),workerId:'test',settings:async()=>({allowIndex:true,eligible:true,metaTitle:null,metaDescription:null} as never),storefront:async()=>{active++;peak=Math.max(peak,active);await new Promise(resolve=>setTimeout(resolve,5));active--;return{status:200,html:'<title>Store</title><meta name="description" content="Store"><link rel="canonical" href="https://store.example.com/">'};},indexNow:async()=>({status:200})});
  assert.equal(peak,3);assert.equal(recorded.length,7);assert.equal(result.checked,7);assert.equal(result.recordingErrors,1);
});
