import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import pg from 'pg';
import {startAccountingFixture} from '../accounting-ledger/fixture.mjs';

const fixture=startAccountingFixture(204),pool=new pg.Pool({...fixture.connection,max:6});
const now='2026-10-03T12:00:00.000Z',future='2026-10-11T12:00:00.000Z';
const store=randomUUID(),otherStore=randomUUID(),principal=randomUUID(),member=randomUUID(),otherMember=randomUUID(),analyst=randomUUID(),analystMember=randomUUID(),product=randomUUID(),otherProduct=randomUUID();
const host=`reviews-${store}.example.test`,otherHost=`reviews-${otherStore}.example.test`;
const hash=value=>createHash('sha256').update(value).digest('hex');
let plan,count=0;
const check=async(name,run)=>{await run();console.log(`PASS ${++count} ${name}`);};
async function rpc(role,name,args){const client=await pool.connect();try{await client.query('BEGIN');await client.query(`SET LOCAL ROLE ${role}`);const result=await client.query(`SELECT outcome,result_payload FROM saas.${name}(${args.map((_,i)=>`$${i+1}`).join(',')})`,args);await client.query('COMMIT');return result.rows[0];}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
const authority=(actor={})=>[actor.store??store,actor.principal??principal,actor.member??member,plan,'free_starter',1,now];
const overview=actor=>rpc('celebix_saas_app','review_collection_admin_overview',authority(actor));
const mutate=(action,input,operation=randomUUID(),actor={})=>rpc('celebix_saas_app','review_collection_admin_mutate',[...authority(actor),operation,hash(JSON.stringify([action,input])),action,JSON.stringify(input)]);
const claim=at=>rpc('celebix_saas_workflow','review_collection_work_claim',[at??now,randomUUID()]);
const seal=(item,token,at=now)=>rpc('celebix_saas_workflow','review_collection_work_seal',[item.id,item.leaseId,at,hash(token),JSON.stringify({fromLabel:'Review fixture',to:item.recipient,subject:'Yorumunuzu paylaşın',html:`<p>${token}</p>`,text:token})]);
const finish=(item,result='accepted',at=now,code='provider-accepted')=>rpc('celebix_saas_workflow','review_collection_work_finish',[item.id,item.leaseId,at,result,code]);
const publicRpc=(token,action='get',input={},operation=null,hostname=host,at=now)=>rpc('celebix_saas_host_resolver','review_collection_public',[hostname,at,hash(token),action,operation,operation?hash(JSON.stringify([action,input])):null,JSON.stringify(input)]);
async function order({status='delivered',payment='completed',targetStore=store,targetProduct=product,email='customer@reviews.example',source='storefront'}={}){
  const id=randomUUID(),item=randomUUID();
  await pool.query("INSERT INTO saas.orders(id,store_id,order_number,source,customer_name,customer_email,currency,subtotal_cents,shipping_cents,discount_cents,total_cents,status,payment_status,shipping_address,created_at,updated_at) VALUES($1,$2,$3,$4,'Synthetic review customer',$5,'TRY',1000,0,0,1000,$6,$7,$8,'2026-10-01',$9)",[id,targetStore,`REV-${id}`,source,email,status,payment,JSON.stringify({recipientName:'Synthetic customer',line1:'Fixture address',city:'Fixture',country:'TR'}),now]);
  await pool.query("INSERT INTO saas.order_items(id,store_id,order_id,product_id,position,product_name,unit_price_cents,quantity,discount_cents,line_total_cents,created_at) VALUES($1,$2,$3,$4,0,'Review fixture',1000,1,0,1000,$5)",[item,targetStore,id,targetProduct,now]);return id;
}
const functionInventory=async()=>(await pool.query("SELECT oid,oid::regprocedure::text identity,pg_get_functiondef(oid) definition,proowner owner,proacl::text acl,proconfig settings FROM pg_proc WHERE oid IN('saas.product_review_projection(uuid,uuid)'::regprocedure,'saas.public_starter_review_projection(uuid,uuid)'::regprocedure) ORDER BY oid")).rows;
try{
  const before=await functionInventory();fixture.apply('202610030206_verified_review_collection.up.sql');
  plan=(await pool.query("SELECT id FROM saas.plans WHERE plan_code='free_starter' AND version=1")).rows[0].id;
  for(const[id,email]of[[principal,'owner@reviews.example'],[analyst,'analyst@reviews.example']])await pool.query("INSERT INTO saas.principals(id,issuer,subject,email,email_verified,created_at,updated_at) VALUES($1,'https://reviews.invalid/oidc',$1::uuid::text,$2,true,'2026-01-01','2026-01-01')",[id,email]);
  for(const[id,membership,hostname,pid]of[[store,member,host,product],[otherStore,otherMember,otherHost,otherProduct]]){
    await pool.query("INSERT INTO saas.stores(id,name,slug,status,locale,currency,theme_key,created_at,updated_at) VALUES($1,'Review fixture',$2,'active','tr','TRY','hemenaku','2026-01-01','2026-01-01')",[id,`reviews-${id}`]);
    await pool.query("INSERT INTO saas.memberships(id,principal_id,store_id,role,status,created_at,updated_at) VALUES($1,$2,$3,'store_owner','active','2026-01-01','2026-01-01')",[membership,principal,id]);
    await pool.query("INSERT INTO saas.subscriptions(id,store_id,plan_id,plan_code,plan_version,status,valid_from,created_at,updated_at) VALUES($1,$2,$3,'free_starter',1,'active','2026-01-01','2026-01-01','2026-01-01')",[randomUUID(),id,plan]);
    await pool.query("INSERT INTO saas.store_domains(id,store_id,hostname,hostname_type,status,is_primary,verified_at,created_at,updated_at) VALUES($1,$2,$3,'platform_subdomain','active',true,'2026-01-01','2026-01-01','2026-01-01')",[randomUUID(),id,hostname]);
    await pool.query("INSERT INTO saas.products(id,store_id,slug,title,status,currency,created_at,updated_at) VALUES($1,$2,$3,'Review fixture','active','TRY','2026-01-01','2026-01-01')",[pid,id,`reviews-${pid}`]);
  }
  await pool.query("INSERT INTO saas.memberships(id,principal_id,store_id,role,status,created_at,updated_at) VALUES($1,$2,$3,'analyst','active','2026-01-01','2026-01-01')",[analystMember,analyst,store]);
  await check('projection replacement preserves existing function identity and privileges',async()=>{assert.deepEqual((await functionInventory()).map(({definition,...rest})=>rest),before.map(({definition,...rest})=>rest));});
  await check('automatic invitations start off and no historical order is enqueued on enabling',async()=>{assert.deepEqual((await overview()).result_payload.settings,{enabled:false,delayDays:7,version:0});await order();assert.equal((await mutate('settings',{enabled:true,delayDays:7,expectedVersion:0})).outcome,'saved');assert.equal((await overview()).result_payload.requests.length,0);});
  await check('settings CAS, exact replay, mismatched replay and analyst denial',async()=>{const op=randomUUID(),input={enabled:false,delayDays:7,expectedVersion:1};assert.equal((await mutate('settings',input,op)).outcome,'saved');assert.equal((await mutate('settings',input,op)).outcome,'operation_replayed');assert.equal((await mutate('settings',{...input,delayDays:2},op)).outcome,'operation_mismatch');assert.equal((await mutate('settings',{enabled:true,delayDays:7,expectedVersion:1})).outcome,'version_conflict');assert.equal((await mutate('settings',{enabled:true,delayDays:7,expectedVersion:2},randomUUID(),{principal:analyst,member:analystMember})).outcome,'membership_denied');});
  await check('unpaid, undelivered, imported, archived-product and foreign orders are ineligible',async()=>{for(const options of[{payment:'pending'},{status:'shipped'},{source:'manual_import'},{targetStore:otherStore,targetProduct:otherProduct}]){const id=await order(options);assert.equal((await mutate('request',{orderId:id,expectedVersion:1})).outcome,'ineligible_order');}const archived=await order();await pool.query("UPDATE saas.products SET status='archived',archived_at=$2,version=version+1,updated_at=$2 WHERE id=$1",[product,now]);assert.equal((await mutate('request',{orderId:archived,expectedVersion:1})).result_payload.queuedCount,0);await pool.query("UPDATE saas.products SET status='active',archived_at=NULL,version=version+1,updated_at=$2 WHERE id=$1",[product,now]);});
  const selectedOrder=await order();
  await check('manual requests deduplicate each paid delivered order product',async()=>{const result=await mutate('request',{orderId:selectedOrder,expectedVersion:1});assert.equal(result.outcome,'saved');assert.equal(result.result_payload.queuedCount,1);assert.equal((await mutate('request',{orderId:selectedOrder,expectedVersion:1})).result_payload.queuedCount,0);});
  let selected,token;
  await check('two workers cannot claim the same invitation concurrently',async()=>{const batches=await Promise.all([claim(),claim()]);const items=batches.flatMap(result=>result.result_payload.items);assert.equal(items.length,1);selected=items[0];assert.equal(new Set(items.map(item=>item.id)).size,items.length);});
  await check('seal stores immutable recipient/payload and repeat returns original content',async()=>{token=Buffer.alloc(32,1).toString('base64url');const first=await seal(selected,token);assert.equal(first.outcome,'sealed');const second=await seal(selected,Buffer.alloc(32,2).toString('base64url'));assert.deepEqual(second.result_payload,first.result_payload);assert.equal((await finish({...selected,leaseId:randomUUID()})).outcome,'lease_lost');assert.equal((await finish(selected)).outcome,'finished');});
  await check('invitation is bound to its verified store hostname and expires',async()=>{assert.equal((await publicRpc(token)).outcome,'found');assert.equal((await publicRpc(token,'get',{},null,otherHost)).outcome,'not_found');assert.equal((await publicRpc(token,'get',{},null,'unknown.example.test')).outcome,'not_found');assert.equal((await publicRpc(token,'get',{},null,host,'2026-11-04T12:00:00Z')).outcome,'invitation_expired');});
  let reviewId;
  await check('one-star purchase review is pending, replay-safe and verified',async()=>{const op=randomUUID(),input={reviewerName:'Real purchase fixture',rating:1,title:'İlk izlenim',body:'Satın aldığım ürün hakkında gerçek yorum.'};const result=await publicRpc(token,'submit',input,op);assert.equal(result.outcome,'submitted');assert.equal(result.result_payload.status,'pending');assert.equal((await publicRpc(token,'submit',input,op)).outcome,'operation_replayed');assert.equal((await publicRpc(token,'submit',{...input,rating:5},op)).outcome,'operation_mismatch');assert.equal((await publicRpc(token,'submit',input,randomUUID())).outcome,'already_submitted');reviewId=(await pool.query('SELECT review_id FROM saas.review_collection_requests WHERE id=$1',[selected.id])).rows[0].review_id;assert.equal((await pool.query('SELECT saas.public_starter_review_projection($1,$2) value',[store,reviewId])).rows[0].value,null);assert.equal((await pool.query('SELECT saas.product_review_projection($1,$2) value',[store,reviewId])).rows[0].value.verifiedPurchase,true);});
  await check('existing moderation publishes verified review and merchant response',async()=>{const result=await rpc('celebix_saas_app','catalog_admin_moderate_review',[...authority(),randomUUID(),'a'.repeat(64),reviewId,1,'approved','Geri bildiriminiz için teşekkür ederiz.']);assert.equal(result.outcome,'moderated');const projection=(await pool.query('SELECT saas.public_starter_review_projection($1,$2) value',[store,reviewId])).rows[0].value;assert.equal(projection.rating,1);assert.equal(projection.verifiedPurchase,true);assert.equal(projection.merchantReply,'Geri bildiriminiz için teşekkür ederiz.');});
  await check('legacy approved reviews never gain invented purchase verification',async()=>{const id=randomUUID();await pool.query("INSERT INTO saas.product_reviews(id,store_id,product_id,reviewer_name,rating,review_body,status,created_at,updated_at) VALUES($1,$2,$3,'Legacy',5,'Legacy review','approved',$4,$4)",[id,store,product,now]);assert.equal((await pool.query('SELECT saas.public_starter_review_projection($1,$2) value',[store,id])).rows[0].value.verifiedPurchase,false);});
  await check('recipient opt-out stops future invitations only in the selected store',async()=>{assert.equal((await publicRpc(token,'unsubscribe')).outcome,'unsubscribed');const denied=await order();assert.equal((await mutate('request',{orderId:denied,expectedVersion:1})).outcome,'ineligible_order');const sameEmail=await order({targetStore:otherStore,targetProduct:otherProduct});assert.equal((await mutate('request',{orderId:sameEmail,expectedVersion:1},randomUUID(),{store:otherStore,member:otherMember})).result_payload.queuedCount,1);});
  await check('automatic delivery event schedules once after configured delay',async()=>{assert.equal((await mutate('settings',{enabled:true,delayDays:7,expectedVersion:2})).outcome,'saved');const id=await order({email:'automatic@reviews.example'});for(let i=0;i<2;i++)await pool.query("INSERT INTO saas.order_events(id,store_id,order_id,event_type,from_value,to_value,message,created_at) VALUES($1,$2,$3,'status_transition','shipped','delivered','Delivered fixture',$4)",[randomUUID(),store,id,now]);const rows=(await pool.query('SELECT status,scheduled_at FROM saas.review_collection_requests WHERE order_id=$1',[id])).rows;assert.equal(rows.length,1);assert.equal(rows[0].scheduled_at.toISOString(),'2026-10-10T12:00:00.000Z');});
  await check('expired uncertain provider attempt is not sent again after 24 hours',async()=>{const batches=await claim(future);const item=batches.result_payload.items.find(item=>item.recipient==='automatic@reviews.example');assert.ok(item);await seal(item,Buffer.alloc(32,3).toString('base64url'),future);await finish(item,'retryable',future,'provider_unavailable');const later='2026-10-12T12:00:00.000Z';await claim(later);const row=(await pool.query('SELECT status,error_code FROM saas.review_collection_requests WHERE id=$1',[item.id])).rows[0];assert.deepEqual(row,{status:'requires_review',error_code:'idempotency_window_expired'});});
  await check('automatic disable after claim and sealing blocks every later provider retry',async()=>{const id=await order({email:'disable-after-claim@reviews.example'});await pool.query("INSERT INTO saas.order_events(id,store_id,order_id,event_type,from_value,to_value,message,created_at) VALUES($1,$2,$3,'status_transition','shipped','delivered','Delivered fixture',$4)",[randomUUID(),store,id,now]);const item=(await claim(future)).result_payload.items.find(item=>item.recipient==='disable-after-claim@reviews.example');assert.ok(item);const token=Buffer.alloc(32,4).toString('base64url');assert.equal((await seal(item,token,future)).outcome,'sealed');assert.equal((await mutate('settings',{enabled:false,delayDays:7,expectedVersion:3})).outcome,'saved');assert.equal((await seal(item,token,future)).outcome,'suppressed');assert.equal((await pool.query('SELECT status FROM saas.review_collection_requests WHERE id=$1',[item.id])).rows[0].status,'suppressed');});
  await check('recipient opt-out after claim blocks an already snapshotted delivery',async()=>{const id=await order({email:'optout-after-claim@reviews.example'});assert.equal((await mutate('request',{orderId:id,expectedVersion:1})).result_payload.queuedCount,1);const item=(await claim(future)).result_payload.items.find(item=>item.recipient==='optout-after-claim@reviews.example');assert.ok(item);const token=Buffer.alloc(32,5).toString('base64url');assert.equal((await seal(item,token,future)).outcome,'sealed');assert.equal((await publicRpc(token,'unsubscribe',{},null,host,future)).outcome,'unsubscribed');assert.equal((await seal(item,token,future)).outcome,'lease_lost');assert.equal((await pool.query('SELECT status FROM saas.review_collection_requests WHERE id=$1',[item.id])).rows[0].status,'suppressed');});
  await check('canceled or refunded order after claim cannot send an immutable retry',async()=>{const id=await order({email:'cancel-after-claim@reviews.example'});await mutate('request',{orderId:id,expectedVersion:1});const item=(await claim(future)).result_payload.items.find(item=>item.recipient==='cancel-after-claim@reviews.example');assert.ok(item);const token=Buffer.alloc(32,6).toString('base64url');assert.equal((await seal(item,token,future)).outcome,'sealed');await pool.query("UPDATE saas.orders SET status='cancelled',updated_at=$2,version=version+1 WHERE id=$1",[id,future]);assert.equal((await seal(item,token,future)).outcome,'suppressed');assert.equal((await publicRpc(token,'get',{},null,host,future)).outcome,'invitation_expired');});
  await check('an expired worker lease cannot seal or authorize a send',async()=>{const id=await order({email:'lease-after-claim@reviews.example'});await mutate('request',{orderId:id,expectedVersion:1});const item=(await claim(future)).result_payload.items.find(item=>item.recipient==='lease-after-claim@reviews.example');assert.ok(item);assert.equal((await seal(item,Buffer.alloc(32,7).toString('base64url'),'2026-10-11T12:02:00.000Z')).outcome,'lease_lost');const row=(await pool.query('SELECT email_payload,first_attempt_at FROM saas.review_collection_requests WHERE id=$1',[item.id])).rows[0];assert.equal(row.email_payload,null);assert.equal(row.first_attempt_at,null);});
  await check('table-level access is denied and no unmoderated public review escapes',async()=>{for(const role of['celebix_saas_app','celebix_saas_workflow','celebix_saas_host_resolver'])for(const table of['review_collection_requests','review_collection_settings','review_collection_optouts','review_collection_operations'])assert.equal((await pool.query('SELECT has_table_privilege($1,$2,$3) allowed',[role,`saas.${table}`,'SELECT,INSERT,UPDATE,DELETE'])).rows[0].allowed,false);assert.equal((await overview({store:otherStore,member:otherMember})).result_payload.requests.some(item=>item.id===selected.id),false);});
  console.log(`REVIEW_COLLECTION_POSTGRESQL16_COMPLETE ${count}/${count}`);
}finally{await pool.end();fixture.stop();}
