import assert from 'node:assert/strict';
import test from 'node:test';
import {readSupportCookie, supportCookie, supportAccess} from './policy.ts';
const token='a'.repeat(64),host='admin.example.test',now=new Date('2026-10-04T10:00:00Z');
const tenant={schemaVersion:1,requestId:'r',principal:{id:'p',issuer:'https://id.test',subject:'operator'},store:{id:'s',slug:'store',status:'active'},membership:{id:'m',role:'admin',status:'active'},entitlements:{schemaVersion:1,planId:'plan',planCode:'starter',version:1,status:'active',features:['catalog'],limits:{products:100,staff:1,storageBytes:1000},validFrom:'2026-01-01T00:00:00Z'},locale:'tr'};
const support={id:'x',operatorId:'o',principalId:'p',storeId:'s',adminHost:host,reason:'Support',operatorLabel:'operator@example.test',version:1,issuedAt:'2026-10-04T09:40:00Z',expiresAt:'2026-10-04T10:10:00Z',revokedAt:null};
test('support cookie is independent, bounded, rejects duplicate credentials',()=>{const read=readSupportCookie('__Host-celebix_panel=regular; __Host-celebix_support='+token);assert.equal(read.kind,'present');if(read.kind==='present')assert.equal(read.credential,'support:'+token);assert.equal(readSupportCookie('__Host-celebix_support='+token+'; __Host-celebix_support='+token).kind,'invalid');assert.equal(readSupportCookie('__Host-celebix_support=regular').kind,'invalid');assert.equal(readSupportCookie('__Host-celebix_panel='+token).kind,'missing');assert.match(supportCookie(token,600),/HttpOnly; Secure; SameSite=Strict/);assert.doesNotMatch(supportCookie(token,600),/Domain=/);});
test('support sidecar never widens strict TenantContext and keeps real operator identity',()=>{const value=supportAccess({support,tenantContext:tenant},host,now);assert.equal(value.kind,'authenticated');if(value.kind==='authenticated'){assert.deepEqual(value.tenantContext,tenant);assert.equal(value.support?.operatorId,'o');assert.equal('support' in value.tenantContext,false);assert.equal(value.session.principal.subject,'operator');}});
test('expiry, revocation, host and principal/store mismatch deny even before database cleanup',()=>{for(const change of [{expiresAt:now.toISOString()},{revokedAt:now.toISOString()},{adminHost:'foreign.example.test'},{principalId:'foreign'},{storeId:'foreign'},{expiresAt:'2026-10-04T11:00:00Z'}])assert.equal(supportAccess({support:{...support,...change},tenantContext:tenant},host,now).kind,'unauthorized');});

test('malformed support tenant envelopes cannot authorize a session',()=>{for(const change of [{schemaVersion:2},{support:{}},{entitlements:{...tenant.entitlements,schemaVersion:2}},{entitlements:{...tenant.entitlements,status:'expired'}},{entitlements:{...tenant.entitlements,version:0}}])assert.equal(supportAccess({support,tenantContext:{...tenant,...change}},host,now).kind,'unauthorized');});
