import assert from"node:assert/strict";import test from"node:test";import{createAnalyticsBrowserApi}from"./client.ts";
const OP="10000000-0000-4000-8000-000000000001",NOW="2026-07-26T12:00:00.000Z",MUT={status:"active",version:2,updatedAt:NOW,replayed:false},VIEW={schemaVersion:1,provider:"umami",status:"active",configured:true,hostname:"store.example.test",version:2,lastVerifiedAt:NOW};
function fixture(value:unknown=VIEW,status=200){let request:Request|undefined;return{api:createAnalyticsBrowserApi(async(input,init)=>{request=new Request(input,init);return Response.json(value,{status})}),get request(){return request}}}
test("connection uses a relative same-origin URL",async()=>{const f=fixture();await f.api.connection();assert.equal(f.request?.url,"http://localhost/api/analytics/connection");assert.equal(f.request?.credentials,"same-origin")});
test("enable posts only intent and idempotency",async()=>{const f=fixture(MUT);await f.api.enable({idempotencyKey:OP});assert.equal(await f.request?.text(),'{'+'"intent":"enable"}');assert.equal(f.request?.headers.get("idempotency-key"),OP)});
test("disable body contains only expectedVersion",async()=>{const f=fixture({...MUT,status:"disabled"});await f.api.disable({idempotencyKey:OP,expectedVersion:2});assert.deepEqual(JSON.parse(await f.request!.text()),{intent:"disable",expectedVersion:2})});
test("summary binds one exact range",async()=>{const f=fixture({schemaVersion:1,range:"7d",asOf:NOW,pageviews:0,visitors:0,visits:0,bounces:0,totalTimeSeconds:0,activeVisitors:0,bounceRateBasisPoints:0,averageVisitSeconds:0,comparison:null,pageviewsSeries:[],visitsSeries:[]});await f.api.summary("7d");assert.ok(f.request?.url.endsWith("/api/analytics/summary?range=7d"))});
test("metrics bind exact range and type",async()=>{const f=fixture({schemaVersion:1,range:"30d",type:"path",asOf:NOW,items:[]});await f.api.metrics("30d","path");assert.ok(f.request?.url.endsWith("/api/analytics/metrics?range=30d&type=path"))});
test("all calls are no-store and propagate abort",async()=>{const f=fixture(),controller=new AbortController();await f.api.connection(controller.signal);assert.equal(f.request?.cache,"no-store");assert.equal(f.request?.signal.aborted,false);controller.abort();assert.equal(f.request?.signal.aborted,true)});
test("strict response parsing rejects private fields",async()=>{const f=fixture({...VIEW,websiteId:"secret"});await assert.rejects(()=>f.api.connection(),/analytics_api_response_invalid/)});
test("server failures map to fixed secret-free errors",async()=>{const f=fixture({code:"unavailable",detail:"private"},503);await assert.rejects(()=>f.api.connection(),(error:unknown)=>String(error)==="Error: analytics_api_unavailable")});
