import { ANALYTICS_PERIODS, parseAnalyticsDashboard, type AnalyticsDashboard, type AnalyticsPeriod } from "@celebix/saas-contracts";
const CODES = ["invalid_input", "unauthenticated", "membership_denied", "store_inactive", "feature_not_enabled", "durable_authority_invalid", "unavailable"] as const;
type Code = (typeof CODES)[number]; type Fetch = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
export class AnalyticsApiError extends Error { constructor(readonly code: Code, readonly status: number) { super(code); this.name = "AnalyticsApiError"; } }
function period(value: AnalyticsPeriod): AnalyticsPeriod { if (!ANALYTICS_PERIODS.includes(value)) throw new TypeError("analytics_client_invalid"); return value; }
function code(value: unknown): Code { return typeof value === "object" && value !== null && !Array.isArray(value) && typeof (value as Record<string, unknown>).code === "string" && CODES.includes((value as Record<string, unknown>).code as Code) ? (value as Record<string, unknown>).code as Code : "unavailable"; }
async function readJson(response: Response): Promise<unknown> { if (response.headers.get("content-type")?.split(";", 1)[0] !== "application/json") throw new AnalyticsApiError("unavailable", response.status || 503); try { return await response.json(); } catch { throw new AnalyticsApiError("unavailable", 503); } }
export function createAnalyticsApi(fetcher: Fetch = fetch) {
  async function request(path: string): Promise<Readonly<AnalyticsDashboard>> { try { const response = await fetcher(path, { credentials: "same-origin", cache: "no-store" }); const value = await readJson(response); if (!response.ok) throw new AnalyticsApiError(code(value), response.status); try { return parseAnalyticsDashboard(value); } catch { throw new AnalyticsApiError("unavailable", 503); } } catch (error) { if (error instanceof AnalyticsApiError) throw error; throw new AnalyticsApiError("unavailable", 503); } }
  async function download(path: string): Promise<string> { try { const response = await fetcher(path, { credentials: "same-origin", cache: "no-store" }); if (!response.ok || response.headers.get("content-type") !== "text/csv; charset=utf-8" || response.headers.get("content-disposition") !== 'attachment; filename="merchant-analytics.csv"') throw new AnalyticsApiError("unavailable", response.status || 503); return await response.text(); } catch (error) { if (error instanceof AnalyticsApiError) throw error; throw new AnalyticsApiError("unavailable", 503); } }
  return Object.freeze({ dashboard(value: AnalyticsPeriod) { return request(`/api/analytics/dashboard?period=${encodeURIComponent(period(value))}`); }, export(value: AnalyticsPeriod, format: "csv" | "json") { if (format !== "csv" && format !== "json") throw new TypeError("analytics_client_invalid"); return format === "json" ? request(`/api/analytics/export?period=${encodeURIComponent(period(value))}&format=json`) : download(`/api/analytics/export?period=${encodeURIComponent(period(value))}&format=csv`); } });
}
export const analyticsApi = createAnalyticsApi();
