import assert from 'node:assert/strict';
import test from 'node:test';
import React from 'react';
import {compile,withEditor} from '../settings/design/design-editor-test-utils.ts';
import {wheelFixture,WHEEL_ID} from '../../lib/lucky-wheel-ui/fixtures.ts';
async function screen(run:(s:any)=>Promise<void>,options:any={}){
 const writes:any[]=[],deletions:any[]=[],revokes:any[]=[],coupons:any[]=[],campaign=wheelFixture();
 const api={list:async()=>options.records??[campaign],history:async()=>({items:[],hasMore:false}),hasUnresolved:()=>options.uncertain??false,pendingIntent:async()=>options.recovery??null,pendingMutation:async()=>null,save:async(input:any)=>{writes.push(input);return options.save?options.save(input):{...campaign,...input,version:input.expectedVersion?input.expectedVersion+1:1}},deleteCampaign:async(input:any)=>{deletions.push(input);return{campaignId:input.campaignId,deleted:true,issuedCouponsPreserved:true}},revokeCoupons:async(input:any)=>{revokes.push(input);return{campaignId:input.campaignId,revoked:2,held:1}}};
 const {LuckyWheelStudio}=compile<any>(new URL('./LuckyWheelStudio.tsx',import.meta.url),{'@/components/panel/PanelPageShell':{PanelPageShell:({children}:any)=>React.createElement('main',null,children),PanelPageHeader:()=>null},'@/components/panel/PanelLayoutClient':{usePanelChromeModel:()=>({storeSlug:'fixture'})},'@/lib/lucky-wheel-ui/client':{scopedLuckyWheelApi:()=>api},'@/lib/promotion-ui/client':{promotionApi:{list:async()=>({items:options.couponItems??[],nextCursor:null}),apply:async(draft:any)=>{coupons.push(draft);return {kind:"saved",promotion:{id:WHEEL_ID,name:draft.name,status:"active",version:2,createdAt:campaign.createdAt,updatedAt:campaign.updatedAt,ruleDocument:campaign.prizes[0].ruleDocument}}},detail:async()=>options.couponDetail??({id:WHEEL_ID,name:'Kaynak',status:'active',ruleDocument:campaign.prizes[0].ruleDocument})},promotionErrorMessage:()=>''}});
 await withEditor(async s=>{await s.render(React.createElement(LuckyWheelStudio,{canManage:true,canReadCoupons:true,canCreateCoupon:true,canDelete:true,canRevoke:true,...options.props}));const settle=()=>React.act(async()=>new Promise(r=>setTimeout(r,0)));await settle();const button=(label:string)=>{const b=Array.from((s.container.querySelector('[role="dialog"]')??s.container).querySelectorAll('button')).find((b:any)=>b.getAttribute('aria-label')===label||b.textContent?.trim()===label);assert.ok(b,label);return b};const click=async(label:string)=>{await s.click(button(label));await settle()};await run({...s,button,click,settle,writes,deletions,revokes,coupons})});
}
test('save applies selected enabled state and frozen rules label without editable prize labels',async()=>{await screen(async({click,writes,container})=>{await click('Karşılama düzenle');assert.equal(container.querySelector('[name="wheel-prize-label"]'),null);await click('Kaydet');assert.equal(writes.length,1);assert.equal(writes[0].enabled,true);assert.equal(writes[0].expectedVersion,1);assert.match(container.textContent,/Kaydedildi/);assert.equal(container.querySelector('[role="dialog"]'),null)})});
test('uncertain save preserves original form and only permits same retry',async()=>{let tries=0;await screen(async({click,writes,container})=>{await click('Karşılama düzenle');await click('Kaydet');assert.equal((container.querySelector('[name="wheel-name"]')!.closest('fieldset') as HTMLFieldSetElement).disabled,true);await click('Vazgeç');assert.ok(container.querySelector('[role="dialog"]'));await click('Kaydı doğrula');assert.deepEqual(writes[0],writes[1])},{save:async(input:any)=>{if(++tries===1)throw Error('network');return {...wheelFixture(2),...input,version:2}}})});
test('real delete explains issued coupon preservation and never invokes revoke',async()=>{await screen(async({click,deletions,revokes,container})=>{await click('Karşılama sil');assert.match(container.textContent,/Verilmiş kuponlar ve geçmiş korunur/);await click('Sil');assert.equal(deletions.length,1);assert.equal(revokes.length,0);assert.match(container.textContent,/Çark silindi/);assert.equal(container.querySelector('[role="dialog"]'),null)})});
test('coupon revocation is separate and held receipt remains visible',async()=>{await screen(async({click,revokes,deletions,container})=>{await click('Karşılama kuponlarını iptal et');await click('Kuponları iptal et');assert.equal(revokes.length,1);assert.equal(deletions.length,0);assert.match(container.textContent,/2 kupon iptal edildi.*1 kupon ödeme işlemi/s)})});
test('legacy text prizes remain visible and no save conversion is offered',async()=>{await screen(async({click,container,writes})=>{await click('Eski çark görüntüle');assert.match(container.textContent,/Hediye ürün/);assert.match(container.textContent,/Eski metin ödülleri/);assert.equal(Array.from(container.querySelectorAll('button')).some((b:any)=>b.textContent==='Kaydet'),false);assert.equal(writes.length,0)},{records:[{...wheelFixture(),name:'Eski çark',enabled:false,legacy:true,config:null,prizes:[],blockedReason:'legacy_configuration',legacyConfig:{prizes:'Hediye ürün, %20'}}]})});
test('identified or pooled source discount is explained and cannot be linked',async()=>{const campaign=wheelFixture();await screen(async({click,container})=>{await click('Karşılama düzenle');await click('Ödüller');await click('İndirimi değiştir');await click('Kişiye özel');assert.match(container.textContent,/kişi başı kullanım ve ortak kullanım\/bütçe/);const apply=Array.from(container.querySelectorAll('button') as NodeListOf<HTMLButtonElement>).find(b=>b.textContent==='İndirimi seç');assert.ok(apply?.disabled)},{couponItems:[{id:WHEEL_ID,name:'Kişiye özel'}],couponDetail:{id:WHEEL_ID,name:'Kişiye özel',status:'active',ruleDocument:{...campaign.prizes[0].ruleDocument,limits:{...campaign.prizes[0].ruleDocument.limits,perCustomerUsage:1}}}})});
test('inline create uses real promotion apply with public storefront rules and automatic reward label',async()=>{await screen(async({click,container,coupons})=>{await click('Karşılama düzenle');await click('Ödüller');await click('İndirimi değiştir');await click('Yeni indirim');await click('İndirim oluştur');assert.equal(coupons.length,1);assert.equal(coupons[0].audience,'everyone');assert.equal(coupons[0].perCustomerUsage,null);assert.equal(coupons[0].totalUsage,null);assert.equal(coupons[0].budgetMinor,null);assert.deepEqual(coupons[0].salesChannels,['storefront']);assert.equal(container.querySelectorAll('[role="dialog"]').length,1)})});
test('typing keeps focus and tab stays inside the editor',async()=>{await screen(async({click,container,window,change})=>{await click('Karşılama düzenle');const input=container.querySelector('[name="wheel-name"]') as HTMLInputElement;input.focus();await change(input,'Yeni isim');assert.equal(window.document.activeElement,input);const buttons=Array.from(container.querySelector('[role="dialog"]')!.querySelectorAll('button') as NodeListOf<HTMLButtonElement>),close=buttons.find(b=>b.getAttribute('aria-label')==='Vazgeç ve kapat')!;close.focus();await React.act(async()=>close.dispatchEvent(new window.KeyboardEvent('keydown',{key:'Tab',shiftKey:true,bubbles:true,cancelable:true})));assert.equal(window.document.activeElement,buttons.at(-1))})});
test('reload recovery keeps original expected version even when later list is newer',async()=>{const saved=wheelFixture(),recovery={campaignId:WHEEL_ID,expectedVersion:1,name:saved.name,enabled:true,config:saved.config};await screen(async({click,writes})=>{await click('Önceki kaydı doğrula');await click('Kaydı doğrula');assert.equal(writes.length,1);assert.equal(writes[0].expectedVersion,1)},{recovery,records:[wheelFixture(2)]})});
