'use client';
import {useCallback,useEffect,useMemo,useRef,useState,type RefObject} from 'react';
import {createDefaultLuckyWheelConfig,isLuckyWheelPromotionEligible,luckyWheelRewardLabel,luckyWheelRewardConditions,parseLuckyWheelConfig,type LuckyWheelCampaign,type LuckyWheelConfig,type LuckyWheelHistoryResult,type PromotionDetail} from '@celebix/saas-contracts';
import {PanelPageHeader,PanelPageShell} from '@/components/panel/PanelPageShell';
import {usePanelChromeModel} from '@/components/panel/PanelLayoutClient';
import {scopedLuckyWheelApi,type LuckyWheelSaveInput,type LuckyWheelPendingMutation,type createLuckyWheelApi} from '@/lib/lucky-wheel-ui/client';
import {promotionApi} from '@/lib/promotion-ui/client';
import {isoToZonedLocalInput,zonedLocalInputToIso,decimalToHundredths} from '../../lib/promotion-ui/model';
import {DesignSettingsModal} from '../settings/design/DesignSettingsDrawer';
import {LuckyWheelPreview} from './LuckyWheelPreview';
import {LuckyWheelPromotionPicker} from './LuckyWheelPromotionPicker';
import styles from './lucky-wheel-studio.module.css';
type Api=ReturnType<typeof createLuckyWheelApi>;
export type LuckyWheelPermissions=Readonly<{canManage:boolean;canReadCoupons:boolean;canCreateCoupon:boolean;canDelete:boolean;canRevoke:boolean;canEnable?:boolean;timezone?:string;currency?:string}>;
const BLOCKED:Readonly<Record<string,string>>={quota_exhausted:'Dağıtım sınırı doldu',promotion_unavailable:'İndirim koşulları uygun değil',scheduled:'Başlangıç bekleniyor',ended:'Tarihi bitti',legacy_configuration:'Eski yapılandırma'};
const ACTIONS:Readonly<Record<string,string>>={created:'Oluşturuldu',updated:'Güncellendi',deleted:'Silindi',coupons_revoked:'Kuponlar iptal edildi'};
function code(error:unknown){return error&&typeof error==='object'&&'code'in error?String(error.code):'unavailable'}
function message(error:unknown){return error instanceof Error?error.message:'İşlem tamamlanamadı. Tekrar deneyin.'}
function money(minor:number,currency:string){return new Intl.NumberFormat('tr-TR',{style:'currency',currency}).format(minor/100)}
const TABS=[['campaign','Kampanya'],['appearance','Görünüm'],['prizes','Ödüller'],['participation','Katılım'],['display','Gösterim']] as const;
type Tab=typeof TABS[number][0];
function defaultInput():LuckyWheelSaveInput{const config=createDefaultLuckyWheelConfig();return{name:'Yeni çark',enabled:true,config:{...config,prizes:config.prizes.map(p=>({...p,id:crypto.randomUUID()}))}}}
export function LuckyWheelEditor({campaign,recovery,api,onSaved,onClose,onReload,returnFocusRef,canManage,canReadCoupons,canCreateCoupon,canEnable=true,timezone='Europe/Istanbul',currency='TRY'}:LuckyWheelPermissions & {campaign:LuckyWheelCampaign|null;recovery?:LuckyWheelSaveInput;api:Api;onSaved:(campaign:LuckyWheelCampaign)=>void;onClose:()=>void;onReload:(id:string)=>Promise<LuckyWheelCampaign|null>;returnFocusRef:RefObject<HTMLElement|null>}){
 const initial=useRef(recovery??(campaign?.config?{campaignId:campaign.id,expectedVersion:campaign.version,name:campaign.name,enabled:campaign.enabled,config:campaign.config}:{...defaultInput(),enabled:canEnable}));
 const [draft,setDraft]=useState<LuckyWheelSaveInput>(initial.current),[tab,setTab]=useState<Tab>('campaign'),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(Boolean(recovery)),[conflict,setConflict]=useState(false),[error,setError]=useState(''),[discard,setDiscard]=useState(false),[picker,setPicker]=useState<string|null>(null);
 const [details,setDetails]=useState<Record<string,PromotionDetail>>(()=>Object.fromEntries((campaign?.prizes??[]).map(p=>[p.promotionId,{id:p.promotionId,name:p.label,status:'active',version:1,createdAt:campaign!.createdAt,updatedAt:campaign!.updatedAt,ruleDocument:p.ruleDocument}]))),[sourceLoading,setSourceLoading]=useState(false);
 const writing=useRef(false),pickerTrigger=useRef<HTMLElement|null>(null);
 const locked=!canManage||busy||uncertain||conflict;const dirty=JSON.stringify(initial.current)!==JSON.stringify(draft);
 useEffect(()=>{let active=true;const ids=[...new Set(draft.config.prizes.map(p=>p.promotionId))];if(!canReadCoupons||!ids.length)return;setSourceLoading(true);Promise.allSettled(ids.map(id=>promotionApi.detail(id))).then(results=>{if(!active)return;setDetails(previous=>{const next={...previous};for(const r of results)if(r.status==='fulfilled'&&isLuckyWheelPromotionEligible(r.value.ruleDocument))next[r.value.id]=r.value;return next});setSourceLoading(false)});return()=>{active=false}},[canReadCoupons,draft.config.prizes.map(p=>p.promotionId).join(',')]);
 useEffect(()=>{if(!dirty&&!uncertain&&!busy)return;const unload=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',unload);return()=>window.removeEventListener('beforeunload',unload)},[dirty,uncertain,busy]);
 const closeState=useRef({uncertain,dirty});closeState.current={uncertain,dirty};
 const close=useCallback(()=>{if(writing.current||closeState.current.uncertain)return;if(closeState.current.dirty){setDiscard(true);return}onClose()},[onClose]);
 function change(patch:Partial<LuckyWheelSaveInput>){if(locked)return;setDraft(v=>({...v,...patch}));setError('');setDiscard(false)}
 function config(patch:Partial<LuckyWheelConfig>){change({config:{...draft.config,...patch}})}
 function prize(id:string,patch:Partial<LuckyWheelConfig['prizes'][number]>){config({prizes:draft.config.prizes.map(p=>p.id===id?{...p,...patch}:p)})}
 function count(next:number){const prizes=Array.from({length:next},(_,i)=>draft.config.prizes[i]??{id:crypto.randomUUID(),promotionId:'',weightBps:1,issuanceLimit:null});const share=Math.floor(10000/next),extra=10000%next;config({prizes:prizes.map((p,i)=>({...p,weightBps:share+(i<extra?1:0)}))})}
 function schedule(key:'startsAt'|'endsAt',value:string){try{config({[key]:value?zonedLocalInputToIso(value,timezone):null})}catch{setError('Tarih ve saati kontrol edin.')}}
 async function save(){if(writing.current||!canManage||conflict||sourceLoading&&!uncertain)return;let payload:LuckyWheelSaveInput;try{payload={...draft,name:draft.name.trim(),config:parseLuckyWheelConfig({...draft.config,heading:draft.config.heading.trim(),body:draft.config.body.trim().replace(/[\r\n]+/g,' '),marketingOptInLabel:draft.config.marketingOptInLabel.trim()})};if(!payload.name||!uncertain&&payload.config.prizes.some(p=>!details[p.promotionId]||!isLuckyWheelPromotionEligible(details[p.promotionId].ruleDocument)))throw Error()}catch{setError('Adı, başlığı, indirimleri ve %100 toplam kazanma oranını kontrol edin.');setTab('prizes');return}writing.current=true;setBusy(true);setError('');try{const saved=await api.save(payload);setUncertain(false);onSaved(saved)}catch(reason){const unknown=['unavailable','operation_mismatch','unresolved','storage_unavailable'].includes(code(reason));setDraft(payload);setUncertain(unknown||api.hasUnresolved());setConflict(code(reason)==='version_conflict');setError(message(reason))}finally{writing.current=false;setBusy(false)}}
 async function reloadVersion(){if(!draft.campaignId||busy)return;setBusy(true);try{const current=await onReload(draft.campaignId);if(!current||current.legacy)throw Error('Güncel kayıt bulunamadı.');setDraft(value=>({...value,expectedVersion:current.version}));setConflict(false);setError('Güncel sürüm alındı. Formunuz korunuyor; değişikliklerinizi kontrol edip Kaydet’e basın.')}catch(reason){setError(message(reason))}finally{setBusy(false)}}
 const labels=draft.config.prizes.map(p=>details[p.promotionId]?luckyWheelRewardLabel(details[p.promotionId].ruleDocument):'İndirim seçin');
 return <>{picker?<LuckyWheelPromotionPicker canRead={canReadCoupons} canCreate={canCreateCoupon} timezone={timezone} currency={currency} returnFocusRef={pickerTrigger} onClose={()=>setPicker(null)} onSelected={detail=>{setDetails(v=>({...v,[detail.id]:detail}));prize(picker,{promotionId:detail.id});setPicker(null)}}/>:null}
 <DesignSettingsModal open={!picker} surface={{label:campaign?'Çarkı düzenle':'Çark oluştur',hint:'Gerçek indirim ödülleri ve katılım ayarları'}} returnFocusRef={returnFocusRef} onClose={close} onApply={()=>void save()} applying={busy} applyDisabled={!canManage||conflict||sourceLoading&&!uncertain} closeDisabled={uncertain} applyLabel={uncertain?'Kaydı doğrula':'Kaydet'} applyingLabel="Kaydediliyor…" className={styles.editor}>
  <div className={styles.editorGrid}><div className={styles.formColumn}><div className={styles.tabs} role="tablist" aria-label="Çark ayarları">{TABS.map(([id,label])=><button key={id} id={'wheel-tab-'+id} role="tab" aria-selected={tab===id} aria-controls={'wheel-panel-'+id} tabIndex={tab===id?0:-1} type="button" onClick={()=>setTab(id)} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const index=TABS.findIndex(([value])=>value===tab),next=e.key==='Home'?0:e.key==='End'?TABS.length-1:(index+(e.key==='ArrowRight'?1:TABS.length-1))%TABS.length;setTab(TABS[next][0]);requestAnimationFrame(()=>document.getElementById('wheel-tab-'+TABS[next][0])?.focus())}}>{label}</button>)}</div>
  <div id={'wheel-panel-'+tab} role="tabpanel" aria-labelledby={'wheel-tab-'+tab}>
   {tab==='campaign'?<fieldset className={styles.fields} disabled={locked}><label>Kampanya adı<input name="wheel-name" maxLength={160} value={draft.name} onChange={e=>change({name:e.target.value})}/></label><label>Durum<select name="wheel-enabled" value={draft.enabled?'active':'paused'} onChange={e=>change({enabled:e.target.value==='active'})}><option value="active" disabled={!canEnable}>Açık</option><option value="paused">Kapalı</option></select></label><label>Başlık<input name="wheel-heading" maxLength={120} value={draft.config.heading} onChange={e=>config({heading:e.target.value})}/></label><label>Kısa açıklama<textarea name="wheel-body" maxLength={1000} rows={3} value={draft.config.body} onChange={e=>config({body:e.target.value})}/></label><div className={styles.twoColumns}><label>Başlangıç<input type="datetime-local" value={draft.config.startsAt?isoToZonedLocalInput(draft.config.startsAt,timezone):''} onChange={e=>schedule('startsAt',e.target.value)}/></label><label>Bitiş<input type="datetime-local" value={draft.config.endsAt?isoToZonedLocalInput(draft.config.endsAt,timezone):''} onChange={e=>schedule('endsAt',e.target.value)}/></label></div><small>{timezone} · Kaydet seçilen durumu doğrudan uygular.</small></fieldset>:null}
   {tab==='appearance'?<fieldset className={styles.fields} disabled={locked}><div className={styles.twoColumns}>{([['sliceA','Birinci dilim'],['sliceB','İkinci dilim'],['background','Arka plan'],['accent','Vurgu']] as const).map(([key,label])=><label key={key}>{label}<input type="color" name={'wheel-color-'+key} value={draft.config.appearance[key]} onChange={e=>config({appearance:{...draft.config.appearance,[key]:e.target.value}})}/></label>)}</div><p>Tek tasarım. Yazı rengi okunabilirliğe göre belirlenir.</p></fieldset>:null}
   {tab==='prizes'?<fieldset className={styles.fields} disabled={locked}><label>Dilim sayısı<select name="wheel-prize-count" value={draft.config.prizes.length} onChange={e=>count(Number(e.target.value))}>{[4,5,6,7,8].map(n=><option key={n} value={n}>{n} dilim</option>)}</select></label><p className={styles.notice}>Toplam %{(draft.config.prizes.reduce((sum,p)=>sum+p.weightBps,0)/100).toLocaleString('tr-TR')} / %100</p>{draft.config.prizes.map((p,i)=>{const detail=details[p.promotionId],issued=campaign?.prizes.find(x=>x.id===p.id)?.issued??0;return <section key={p.id} className={styles.prize}><div className={styles.prizeHeading}><strong>{i+1}. {labels[i]}</strong><button type="button" disabled={!canReadCoupons&&!canCreateCoupon} onClick={e=>{pickerTrigger.current=e.currentTarget;setPicker(p.id)}}>{detail?'İndirimi değiştir':'İndirim seç'}</button></div><div className={styles.twoColumns}><label>Kazanma oranı (%)<input name={'wheel-weight-'+i} type="number" step="0.01" min="0.01" max="100" value={p.weightBps/100} onChange={e=>{const v=decimalToHundredths(e.target.value);prize(p.id,{weightBps:v??0})}}/></label><label>Toplam dağıtım sınırı<input name={'wheel-limit-'+i} type="number" min={Math.max(1,issued)} placeholder="Sınırsız" value={p.issuanceLimit??''} onChange={e=>prize(p.id,{issuanceLimit:e.target.value===''?null:Number(e.target.value)})}/></label></div>{issued?<small>{issued} kupon dağıtıldı. Sınır bu toplamı içerir.</small>:null}{detail?<details><summary>Gerçek indirim koşulları</summary><ul>{luckyWheelRewardConditions(detail.ruleDocument).map(c=><li key={c}>{c}</li>)}</ul></details>:null}</section>})}<small>Dilimler eşit görünür; kazanma oranları farklı olabilir. Bir dilimin sınırı dolarsa katılım kapanır.</small>{sourceLoading?<p role="status">İndirim koşulları yükleniyor…</p>:null}</fieldset>:null}
   {tab==='participation'?<fieldset className={styles.fields} disabled={locked}><label>Önce alınacak iletişim<select name="wheel-contact" value={draft.config.collectMode} onChange={e=>config({collectMode:e.target.value as LuckyWheelConfig['collectMode']})}><option value="either">E-posta veya telefon</option><option value="email">E-posta</option><option value="phone">Telefon</option></select></label><div className={styles.twoColumns}><label>Bu tarayıcıdan tekrar katılım (gün)<input name="wheel-repeat" type="number" min="1" max="90" value={draft.config.repeatDays} onChange={e=>config({repeatDays:Number(e.target.value)})}/></label><label>Kupon süresi (saat)<input name="wheel-coupon-hours" type="number" min="1" max="720" value={draft.config.couponHours} onChange={e=>config({couponHours:Number(e.target.value)})}/></label></div><label>Ayrı pazarlama izni metni<textarea name="wheel-consent" maxLength={240} value={draft.config.marketingOptInLabel} onChange={e=>config({marketingOptInLabel:e.target.value})}/></label><p>İzin başlangıçta işaretsizdir. İzin vermemek çevirme hakkını engellemez. Kupon ekranda sunulur.</p></fieldset>:null}
   {tab==='display'?<fieldset className={styles.fields} disabled={locked}><div className={styles.checks}>{([['desktop','Masaüstü'],['mobile','Mobil']] as const).map(([key,label])=><label key={key}><input name={'wheel-device-'+key} type="checkbox" checked={draft.config.devices[key]} onChange={e=>config({devices:{...draft.config.devices,[key]:e.target.checked}})}/>{label}</label>)}</div><label>İzin verilen sayfalar<input name="wheel-paths" placeholder="Tüm uygun sayfalar" value={draft.config.allowedPaths.join(', ')} onChange={e=>config({allowedPaths:e.target.value.split(',').map(p=>p.trim()).filter(Boolean)})}/><small>Virgülle ayırın: /, /collections. Ödeme ve hesap sayfaları hariç.</small></label><label>Kaydırma sonrası açılma (%)<input name="wheel-scroll" type="number" min="1" max="100" placeholder="Yalnız çark düğmesi" value={draft.config.scrollPercent??''} onChange={e=>config({scrollPercent:e.target.value===''?null:Number(e.target.value)})}/></label><p>Varsayılan küçük bir çark düğmesidir.</p></fieldset>:null}
  </div>{error?<p role="alert">{error}</p>:null}{conflict?<button type="button" disabled={busy} onClick={()=>void reloadVersion()}>Güncel sürümü yükle</button>:null}{discard?<div className={styles.notice}><p>Değişiklikler kaydedilmedi.</p><button type="button" onClick={onClose}>Değişiklikleri bırak</button><button type="button" onClick={()=>setDiscard(false)}>Düzenlemeye devam et</button></div>:null}
  </div><aside className={styles.previewColumn}><LuckyWheelPreview config={draft.config} labels={labels}/><p>Bu tarayıcıdan {draft.config.repeatDays} günde bir · {draft.config.couponHours} saat kupon süresi</p></aside></div>
 </DesignSettingsModal></>;
}
function MutationDialog({intent,campaign,recovery,api,onDone,onClose,returnFocusRef}:{intent:LuckyWheelPendingMutation;campaign:LuckyWheelCampaign|undefined;recovery:boolean;api:Api;onDone:(text:string)=>void;onClose:()=>void;returnFocusRef:RefObject<HTMLElement|null>}){
 const original=useRef(intent),writing=useRef(false);const [busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(recovery),[error,setError]=useState('');
 const close=useCallback(()=>{if(!writing.current&&!uncertain)onClose()},[uncertain,onClose]);
 async function apply(){if(writing.current)return;writing.current=true;setBusy(true);setError('');try{const {action,...input}=original.current;if(action==='delete'){await api.deleteCampaign(input);onDone('Çark silindi. Verilmiş kuponlar ve geçmiş korunur.')}else{const result=await api.revokeCoupons(input);onDone(`${result.revoked} kupon iptal edildi. ${result.held} kupon ödeme işlemi nedeniyle korunuyor.`)}setUncertain(false)}catch(reason){setUncertain(['unavailable','operation_mismatch','unresolved','storage_unavailable'].includes(code(reason))||api.hasUnresolved());setError(message(reason))}finally{writing.current=false;setBusy(false)}}
 const deleting=intent.action==='delete';
 return <DesignSettingsModal open surface={{label:deleting?'Çarkı sil':'Verilmiş kuponları iptal et',hint:'İşlemin etkisini doğrulayın'}} returnFocusRef={returnFocusRef} onClose={close} onApply={()=>void apply()} applying={busy} closeDisabled={uncertain} applyLabel={uncertain?'İşlemi doğrula':deleting?'Sil':'Kuponları iptal et'}><p><strong>{campaign?.name??'Bu çark'}</strong></p>{deleting?<p>Vitrinden ve yönetim listesinden kalkar. Yeni katılım durur. Verilmiş kuponlar ve geçmiş korunur.</p>:<><p>Kullanılmamış ve ödeme için ayrılmamış kuponlar iptal edilir. Başlamış ödeme ve geçmiş sipariş kayıtları korunur.</p><p>{campaign?`${campaign.stats.issued} dağıtıldı · ${campaign.stats.used} kullanıldı. `:''}Kesin iptal ve korunmuş ödeme sayısı işlem sonucunda gösterilir.</p></>}{error?<p role="alert">{error}</p>:null}</DesignSettingsModal>;
}
export function LuckyWheelStudio({initialCreate=false,campaignId,...permissions}:LuckyWheelPermissions & {initialCreate?:boolean;campaignId?:string}){
 const {storeSlug}=usePanelChromeModel(),api=useMemo(()=>scopedLuckyWheelApi(storeSlug),[storeSlug]);
 const [rows,setRows]=useState<readonly LuckyWheelCampaign[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[editor,setEditor]=useState<{campaign:LuckyWheelCampaign|null;recovery?:LuckyWheelSaveInput}|null>(null),[mutation,setMutation]=useState<LuckyWheelPendingMutation|null>(null),[recoveryMutation,setRecoveryMutation]=useState(false),[recovery,setRecovery]=useState<LuckyWheelSaveInput|null>(null),[pendingMutation,setPendingMutation]=useState<LuckyWheelPendingMutation|null>(null),[history,setHistory]=useState<{campaign:LuckyWheelCampaign;result:LuckyWheelHistoryResult|null;error:string}|null>(null),[legacy,setLegacy]=useState<LuckyWheelCampaign|null>(null);
 const trigger=useRef<HTMLElement|null>(null),entryOpened=useRef(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [campaigns,intent,pending]=await Promise.all([api.list(),api.pendingIntent(),api.pendingMutation()]);setRows(campaigns);setRecovery(intent);setPendingMutation(pending);return campaigns}catch(reason){setError(message(reason));return null}finally{setLoading(false)}},[api]);
 useEffect(()=>{let active=true;void load().then(campaigns=>{if(!active||entryOpened.current||!campaigns)return;entryOpened.current=true;if(initialCreate&&permissions.canManage&&!api.hasUnresolved())setEditor({campaign:null});else if(campaignId){const row=campaigns.find(c=>c.id===campaignId);if(row?.legacy)setLegacy(row);else if(row)setEditor({campaign:row});else setError('Çark bulunamadı.')}});return()=>{active=false}},[load,initialCreate,campaignId,permissions.canManage]);
 const visible=rows.filter(row=>(status==='all'||row.status===status)&&row.name.toLocaleLowerCase('tr-TR').includes(query.trim().toLocaleLowerCase('tr-TR')));
 const closeEditor=useCallback(()=>setEditor(null),[]),closeMutation=useCallback(()=>setMutation(null),[]),closeLegacy=useCallback(()=>setLegacy(null),[]),closeHistory=useCallback(()=>setHistory(null),[]);
 function open(row:LuckyWheelCampaign|null,event:React.MouseEvent<HTMLElement>){trigger.current=event.currentTarget;if(row?.legacy)setLegacy(row);else setEditor({campaign:row})}
 async function showHistory(row:LuckyWheelCampaign,event:React.MouseEvent<HTMLElement>){trigger.current=event.currentTarget;setHistory({campaign:row,result:null,error:''});try{const result=await api.history(row.id);setHistory(v=>v?.campaign.id===row.id?{...v,result}:v)}catch(reason){setHistory(v=>v?{...v,error:message(reason)}:v)}}
 const locked=Boolean(recovery||pendingMutation);
 return <PanelPageShell><h1 className={styles.srOnly}>Şans Çarkı</h1><PanelPageHeader title="Şans Çarkı" actions={permissions.canManage?<button className={styles.primary} type="button" disabled={loading||locked} onClick={e=>open(null,e)}>Çark ekle</button>:undefined}/>
 {notice?<p role="status" className={styles.notice}>{notice}</p>:null}{error?<div className={styles.notice}><p role="alert">{error}</p><button type="button" onClick={()=>void load()}>Tekrar dene</button></div>:null}
 {recovery?<button type="button" onClick={e=>{trigger.current=e.currentTarget;setEditor({campaign:rows.find(r=>r.id===recovery.campaignId)??null,recovery})}}>Önceki kaydı doğrula</button>:pendingMutation?<button type="button" onClick={e=>{trigger.current=e.currentTarget;setRecoveryMutation(true);setMutation(pendingMutation)}}>Önceki işlemi doğrula</button>:null}
 <div className={styles.toolbar}><label className={styles.search}><span className={styles.srOnly}>Çark ara</span><input type="search" name="wheel-search" placeholder="Çark ara" value={query} onChange={e=>setQuery(e.target.value)}/></label><label><span className={styles.srOnly}>Durum</span><select aria-label="Durum" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tümü</option><option value="active">Açık</option><option value="paused">Kapalı</option><option value="archived">Arşiv</option></select></label><button type="button" disabled={loading} onClick={()=>void load()}>Yenile</button></div>
 {loading?<p role="status">Çarklar yükleniyor…</p>:!error&&!visible.length?<div className={styles.empty}><p>{rows.length?'Aramanıza uygun çark yok.':'Henüz çark yok.'}</p>{rows.length?<button type="button" onClick={()=>{setQuery('');setStatus('all')}}>Filtreleri temizle</button>:null}</div>:<div className={styles.tableWrap}><table className={styles.table} aria-label="Şans çarkları"><thead><tr><th>Kampanya</th><th>Durum</th><th>Dağıtılan</th><th>Kullanılan</th><th>İndirim</th><th>Kuponlu satış</th><th><span className={styles.srOnly}>İşlemler</span></th></tr></thead><tbody>{visible.map(row=><tr key={row.id}><td data-label="Kampanya"><strong>{row.name}</strong><small>v{row.version}{row.legacy?' · Eski kayıt':''}</small></td><td data-label="Durum"><span>{row.status==='archived'?'Arşiv':row.status==='active'?'Açık':'Kapalı'}</span>{row.blockedReason?<small>{BLOCKED[row.blockedReason]}</small>:null}</td><td data-label="Dağıtılan">{row.stats.issued}</td><td data-label="Kullanılan">{row.stats.used}</td><td data-label="İndirim">{money(row.stats.discountMinor,row.stats.currency)}</td><td data-label="Kuponlu satış">{money(row.stats.revenueMinor,row.stats.currency)}</td><td className={styles.rowActions}><button type="button" disabled={locked} aria-label={row.name+(row.legacy?' görüntüle':' düzenle')} onClick={e=>open(row,e)}>{row.legacy?'Görüntüle':permissions.canManage?'Düzenle':'Görüntüle'}</button><button type="button" aria-label={row.name+' geçmişi'} onClick={e=>void showHistory(row,e)}>Geçmiş</button>{permissions.canDelete?<button type="button" disabled={locked} aria-label={row.name+' sil'} onClick={e=>{trigger.current=e.currentTarget;setRecoveryMutation(false);setMutation({action:'delete',campaignId:row.id,expectedVersion:row.version})}}>Sil</button>:null}{permissions.canRevoke&&!row.legacy?<button type="button" disabled={locked} aria-label={row.name+' kuponlarını iptal et'} onClick={e=>{trigger.current=e.currentTarget;setRecoveryMutation(false);setMutation({action:'revoke-coupons',campaignId:row.id,expectedVersion:row.version})}}>Kuponları iptal et</button>:null}</td></tr>)}</tbody></table></div>}
 <p className={styles.footnote}>Kuponlu satış, tamamlanmış sipariş toplamıdır; kısmi iadeler düşülmez.</p>
 {editor?<LuckyWheelEditor key={editor.recovery?'recovery':editor.campaign?.id??'new'} {...permissions} campaign={editor.campaign} recovery={editor.recovery} api={api} returnFocusRef={trigger} onClose={closeEditor} onReload={async id=>(await load())?.find(c=>c.id===id)??null} onSaved={saved=>{setRows(v=>[saved,...v.filter(c=>c.id!==saved.id)]);setEditor(null);setRecovery(null);setNotice('Kaydedildi. Seçilen durum mağazada uygulanır.')}}/>:null}
 {mutation?<MutationDialog intent={mutation} campaign={rows.find(r=>r.id===mutation.campaignId)} recovery={recoveryMutation} api={api} returnFocusRef={trigger} onClose={closeMutation} onDone={text=>{setMutation(null);setPendingMutation(null);setNotice(text);void load()}}/>:null}
 {history?<DesignSettingsModal open surface={{label:'İşlem geçmişi',hint:history.campaign.name}} returnFocusRef={trigger} onClose={closeHistory} applyLabel="Kapat" onApply={closeHistory}><p><strong>{history.campaign.name}</strong></p>{history.error?<p role="alert">{history.error}</p>:!history.result?<p role="status">Geçmiş yükleniyor…</p>:history.result.items.length?<><ul className={styles.history}>{history.result.items.map(item=><li key={item.id}><strong>{ACTIONS[item.action]} · v{item.version}</strong><span>{item.actorLabel}</span><time dateTime={item.at}>{new Date(item.at).toLocaleString('tr-TR',{timeZone:permissions.timezone??'Europe/Istanbul'})}</time></li>)}</ul>{history.result.hasMore?<p>Son 50 işlem gösteriliyor.</p>:null}</>:<p>Henüz işlem yok.</p>}</DesignSettingsModal>:null}
 {legacy?<DesignSettingsModal open surface={{label:'Eski çark kaydı',hint:legacy.name}} returnFocusRef={trigger} onClose={closeLegacy} applyLabel="Kapat" onApply={closeLegacy}><p><strong>{legacy.name}</strong></p><p>Eski metin ödülleri gerçek kupona dönüştürülmez. Yeni çark oluşturun.</p><dl>{Object.entries(legacy.legacyConfig??{}).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{typeof value==='string'||typeof value==='number'?String(value):JSON.stringify(value)}</dd></div>)}</dl></DesignSettingsModal>:null}
 </PanelPageShell>;
}
