'use client';
import {useCallback,useEffect,useMemo,useRef,useState,type RefObject} from 'react';
import {isLuckyWheelPromotionEligible,luckyWheelRewardLabel,luckyWheelRewardConditions,type PromotionAdminListItem,type PromotionDetail} from '@celebix/saas-contracts';
import {promotionApi,promotionErrorMessage} from '@/lib/promotion-ui/client';
import {usePanelChromeModel} from '@/components/panel/PanelLayoutClient';
import {createLuckyWheelPromotionApi} from '@/lib/lucky-wheel-ui/promotion-recovery';
import {createPromotionDraft,updatePromotionDraft,decimalToHundredths,type PromotionDraft} from '../../lib/promotion-ui/model';
import {DesignSettingsModal} from '../settings/design/DesignSettingsDrawer';
import styles from './lucky-wheel-studio.module.css';
type Props={canRead:boolean;canCreate:boolean;timezone:string;currency:string;returnFocusRef:RefObject<HTMLElement|null>;onClose:()=>void;onSelected:(promotion:PromotionDetail)=>void};
export function LuckyWheelPromotionPicker({canRead,canCreate,timezone,currency,returnFocusRef,onClose,onSelected}:Props){
 const {storeSlug}=usePanelChromeModel(),sourceApi=useMemo(()=>createLuckyWheelPromotionApi({scope:storeSlug}),[storeSlug]);
 const [rows,setRows]=useState<readonly PromotionAdminListItem[]>([]),[cursor,setCursor]=useState<string|null>(null),[search,setSearch]=useState(''),[selected,setSelected]=useState<PromotionDetail|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[creating,setCreating]=useState(false),[unknown,setUnknown]=useState(false);
 const [name,setName]=useState('Çark indirimi'),[kind,setKind]=useState<'percentage'|'fixed_amount'|'free_shipping'>('percentage'),[amount,setAmount]=useState('5'),[minimum,setMinimum]=useState('0');
 const [recovering,setRecovering]=useState(true);
 const intent=useRef<PromotionDraft|null>(null),writing=useRef(false),generation=useRef(0);
 const close=useCallback(()=>{if(!writing.current&&!unknown&&!recovering)onClose()},[onClose,unknown,recovering]);
 useEffect(()=>{let active=true;void sourceApi.pendingDraft().then(draft=>{if(!active||!draft)return;intent.current=draft;setCreating(true);setUnknown(true);setName(draft.name);const benefit=draft.benefit;if(benefit.kind==='percentage'||benefit.kind==='fixed_amount'||benefit.kind==='free_shipping'){setKind(benefit.kind);setAmount(String(benefit.kind==='percentage'?benefit.percentageBps/100:benefit.kind==='fixed_amount'?benefit.amountMinor/100:0));setMinimum(String(draft.minimumBasketMinor/100))}setError('Önceki oluşturma sonucu doğrulanamadı. Saklanan bilgilerle aynı işlemi doğrulayın.')}).catch(reason=>{if(active){setUnknown(true);setError(reason instanceof Error?reason.message:'İndirim sonucu doğrulanamadı.')}}).finally(()=>{if(active)setRecovering(false)});return()=>{active=false}},[sourceApi]);
 useEffect(()=>{if(!busy&&!unknown)return;const unload=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',unload);return()=>window.removeEventListener('beforeunload',unload)},[busy,unknown]);
 const load=useCallback(async(next?:string)=>{if(!canRead)return;setLoading(true);setError('');try{const page=await promotionApi.list({benefitKinds:['percentage','fixed_amount','free_shipping'],audienceModes:['everyone'],...(search.trim()?{search:search.trim()}:{}),...(next?{cursor:next}:{})});setRows(r=>next?[...r,...page.items]:page.items);setCursor(page.nextCursor)}catch{setError('İndirimler yüklenemedi.')}finally{setLoading(false)}},[canRead,search]);
 useEffect(()=>{void load()},[load]);
 async function select(id:string){const turn=++generation.current;setBusy(true);setError('');setSelected(null);try{const detail=await promotionApi.detail(id);if(turn!==generation.current)return;if(!['active','scheduled'].includes(detail.status)||!isLuckyWheelPromotionEligible(detail.ruleDocument)){setError('Herkese açık, kişi başı kullanım ve ortak kullanım/bütçe sınırı olmayan bir indirim seçin.');return}setSelected(detail)}catch{setError('İndirim koşulları yüklenemedi.')}finally{if(turn===generation.current)setBusy(false)}}
 async function create(){if(!canCreate||writing.current||recovering)return;let draft=intent.current;if(!draft){const value=decimalToHundredths(amount),min=decimalToHundredths(minimum);if(!name.trim()||min===undefined||(kind!=='free_shipping'&&(value===undefined||value<=0||kind==='percentage'&&value>10000))){setError('Adı, tutarı ve sepet alt sınırını kontrol edin.');return}const sourceCode='LW-SOURCE-'+crypto.randomUUID().replaceAll('-','').toUpperCase();draft=updatePromotionDraft(createPromotionDraft('custom',timezone),{name:name.trim(),benefit:kind==='percentage'?{kind,percentageBps:value!}:kind==='fixed_amount'?{kind,amountMinor:value!,currency}:{kind},audience:'everyone',perCustomerUsage:null,totalUsage:null,budgetMinor:null,salesChannels:['storefront'],minimumBasketMinor:min,triggerKind:'code',codeInput:sourceCode});intent.current=draft}writing.current=true;setBusy(true);setError('');try{const result=await sourceApi.apply(draft);if(result.kind!=='saved'){intent.current=null;setUnknown(sourceApi.hasUnresolved());setError(result.kind==='conflict'?result.message:'İndirim oluşturulamadı. Koşulları kontrol edin.');return}if(!isLuckyWheelPromotionEligible(result.promotion.ruleDocument))throw Error('promotion_unavailable');intent.current=null;setUnknown(false);onSelected(result.promotion)}catch(reason){const unresolved=sourceApi.hasUnresolved();setUnknown(unresolved);if(!unresolved)intent.current=null;setError(reason&&typeof reason==='object'&&'code'in reason&&reason instanceof Error?reason.message:promotionErrorMessage(reason instanceof Error?reason.message:'promotion_unavailable')||'İndirim sonucu belirsiz. Aynı işlemi doğrulayın.')}finally{writing.current=false;setBusy(false)}}
 return <DesignSettingsModal open surface={{label:creating?'İndirim oluştur':'İndirim seç',hint:'Çark ödülünün gerçek indirim koşulları'}} returnFocusRef={returnFocusRef} onClose={close} onApply={()=>creating?void create():selected&&onSelected(selected)} applying={busy} closeDisabled={unknown||recovering} applyDisabled={recovering||(creating?!canCreate:!selected)} applyLabel={creating?(unknown?'Oluşturmayı doğrula':'İndirim oluştur'):'İndirimi seç'} className={styles.picker}>
  <div className={styles.toolbar}><button type="button" disabled={busy||unknown||recovering} aria-pressed={!creating} onClick={()=>setCreating(false)}>Mevcut indirim</button>{canCreate?<button type="button" disabled={busy||unknown||recovering} aria-pressed={creating} onClick={()=>{setCreating(true);setError('')}}>Yeni indirim</button>:null}</div>
  {creating?<fieldset className={styles.fields} disabled={busy||unknown||recovering}><label>İndirim adı<input name="wheel-coupon-name" value={name} onChange={e=>setName(e.target.value)}/></label><label>Avantaj<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="percentage">Yüzde indirim</option><option value="fixed_amount">Sabit tutar</option><option value="free_shipping">Ücretsiz kargo</option></select></label>{kind!=='free_shipping'?<label>{kind==='percentage'?'İndirim (%)':`İndirim (${currency})`}<input name="wheel-coupon-amount" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label>:null}<label>Sepet alt sınırı ({currency})<input name="wheel-coupon-minimum" inputMode="decimal" value={minimum} onChange={e=>setMinimum(e.target.value)}/></label><p>Herkese açık; yalnız internet mağazasında. Kodla çalışır, sepetlere kendiliğinden uygulanmaz. Çark her katılıma ayrı kupon üretir. Kişi başı kullanım ve ortak kullanım/bütçe sınırı yok.</p></fieldset>:<><label>İndirim ara<input name="wheel-promotion-search" value={search} disabled={busy} onChange={e=>setSearch(e.target.value)}/></label>{loading?<p role="status">İndirimler yükleniyor…</p>:rows.length?<div className={styles.promotionRows}>{rows.map(row=><button key={row.id} type="button" disabled={busy} aria-pressed={selected?.id===row.id} onClick={()=>void select(row.id)}>{row.name}</button>)}</div>:<p>Uygun türde indirim bulunamadı.</p>}{cursor?<button type="button" disabled={busy||loading} onClick={()=>void load(cursor)}>Daha fazla indirim</button>:null}{selected?<div className={styles.notice}><strong>{luckyWheelRewardLabel(selected.ruleDocument)}</strong><ul>{luckyWheelRewardConditions(selected.ruleDocument).map(c=><li key={c}>{c}</li>)}</ul></div>:null}<p>Yüzde, sabit tutar veya ücretsiz kargo seçilebilir. Uygunluk, indirim koşulları açıldığında kontrol edilir.</p></>}
  {error?<p role="alert">{error}</p>:null}
 </DesignSettingsModal>;
}
