"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import type { PromotionCodeBatchListItem, PromotionDetail } from "@celebix/saas-contracts";
import { PanelLoadingState, PanelPageHeader, PanelStatusBadge } from "@/components/panel/PanelPageShell";
import { defaultPromotionBatchForm, preparePromotionBatchCreate } from "@/lib/promotion-ui/batch-form";
import { promotionApi, promotionErrorMessage } from "@/lib/promotion-ui/client";
import { zonedLocalInputToIso } from "@/lib/promotion-ui/model";
import styles from "./promotion-studio.module.css";
const BATCH_STATUS = { active: "Aktif", paused: "Duraklatıldı", revoked: "İptal edildi" } as const;

export function PromotionCodes({ promotionId, timezone, storefrontOrigin, canPublish, canExportCodes }: Readonly<{ promotionId: string; timezone: string; storefrontOrigin: string | null; canPublish: boolean; canExportCodes: boolean }>) {
  const [promotion, setPromotion] = useState<PromotionDetail | null>(null), [items, setItems] = useState<readonly PromotionCodeBatchListItem[]>([]);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState<readonly string[]>([]), [message, setMessage] = useState("");
  const [loadFailed, setLoadFailed] = useState(false), [nextCursor, setNextCursor] = useState<string | null>(null), [loadingMore, setLoadingMore] = useState(false), [appendFailed, setAppendFailed] = useState(false);
  const [count, setCount] = useState(defaultPromotionBatchForm.count), [prefix, setPrefix] = useState(defaultPromotionBatchForm.prefix), [codeLength, setCodeLength] = useState(defaultPromotionBatchForm.codeLength), [perCustomer, setPerCustomer] = useState(defaultPromotionBatchForm.perCustomerUsage), [expiresAt, setExpiresAt] = useState("");
  const loadGeneration = useRef(0);
  const load = (preserveMessage = false) => { const generation = ++loadGeneration.current; setLoading(true); setLoadFailed(false); setAppendFailed(false); setLoadingMore(false); if (!preserveMessage) setMessage(""); void Promise.all([promotionApi.detail(promotionId), promotionApi.listCodeBatches(promotionId)]).then(([detail, page]) => { if (generation !== loadGeneration.current) return; setPromotion(detail); setItems(page.items); setNextCursor(page.nextCursor); }).catch(() => { if (generation === loadGeneration.current) setLoadFailed(true); }).finally(() => { if (generation === loadGeneration.current) setLoading(false); }); };
  useEffect(() => { load(); return () => { loadGeneration.current += 1; }; }, [promotionId]);
  const loadMore = () => { if (!nextCursor || loadingMore) return; const generation = loadGeneration.current; setLoadingMore(true); setAppendFailed(false); void promotionApi.listCodeBatches(promotionId, nextCursor).then((page) => { if (generation !== loadGeneration.current) return; setItems((current) => [...current, ...page.items]); setNextCursor(page.nextCursor); }).catch(() => { if (generation === loadGeneration.current) setAppendFailed(true); }).finally(() => { if (generation === loadGeneration.current) setLoadingMore(false); }); };
  const create = () => {
    if (busy.includes("create") || !canPublish) return;
    let expiry: string | null = null; try { expiry = expiresAt ? zonedLocalInputToIso(expiresAt, timezone) : null; } catch { setMessage("Geçerli bir son kullanım zamanı seçin."); return; }
    const prepared = preparePromotionBatchCreate({ count, prefix, codeLength, perCustomerUsage: perCustomer, expiresAt: expiry });
    if (prepared.kind === "invalid") { setMessage(prepared.message); return; }
    setBusy((current) => [...current, "create"]); setMessage(""); void promotionApi.createCodeBatch(promotionId, prepared.value).then(() => { setMessage("Kupon grubu oluşturuldu."); load(true); }).catch((error: unknown) => setMessage(promotionErrorMessage(error instanceof Error ? error.message : "promotion_unavailable"))).finally(() => setBusy((current) => current.filter((id) => id !== "create")));
  };
  const transition = (batch: PromotionCodeBatchListItem, nextStatus: "active" | "paused" | "revoked") => { if (busy.includes(batch.id) || !canPublish) return; if (nextStatus === "revoked" && !window.confirm("Bu kupon grubu kalıcı olarak iptal edilsin mi?")) return; setBusy((current) => [...current, batch.id]); void promotionApi.updateCodeBatch(batch, nextStatus).then(() => { setMessage("Kupon grubu güncellendi."); load(true); }).catch((error: unknown) => setMessage(promotionErrorMessage(error instanceof Error ? error.message : "promotion_unavailable"))).finally(() => setBusy((current) => current.filter((id) => id !== batch.id))); };
  const batchActions = (batch: PromotionCodeBatchListItem) => <div className={styles.rowActions}>{canPublish && batch.status === "active" ? <button type="button" disabled={busy.includes(batch.id)} onClick={() => transition(batch, "paused")}>Duraklat</button> : null}{canPublish && batch.status === "paused" ? <button type="button" disabled={busy.includes(batch.id)} onClick={() => transition(batch, "active")}>Etkinleştir</button> : null}{canPublish && batch.status !== "revoked" ? <button type="button" disabled={busy.includes(batch.id)} onClick={() => transition(batch, "revoked")}>İptal et</button> : null}{canExportCodes ? <a href={`/api/promotions/code-batches/${batch.id}/csv`} download>CSV indir</a> : null}</div>;
  const primaryCode = promotion?.ruleDocument.trigger.kind === "code" ? promotion.ruleDocument.trigger.codes[0] ?? null : null;
  const shareUrl = storefrontOrigin && primaryCode ? `${storefrontOrigin}/cart/coupon?coupon=${encodeURIComponent(primaryCode)}` : null;
  return <section className={styles.list}>
    <PanelPageHeader title="Kampanya kuponları" />
    <header className={styles.pageHeader}><div><h1 className={styles.srOnly}>Kampanya kuponları</h1><strong className={styles.recordName}>{promotion?.name ?? "Kampanya"}</strong><p>Toplu kuponlar</p></div><Link href={`/discounts/${promotionId}`}>Kampanyaya dön</Link></header>
    {shareUrl ? <div className={styles.info}><strong>Paylaşılabilir kampanya bağlantısı</strong><p><a href={shareUrl} target="_blank" rel="noreferrer">{shareUrl}</a></p><button type="button" onClick={() => void navigator.clipboard.writeText(shareUrl).then(() => setMessage("Bağlantı kopyalandı.")).catch(() => setMessage("Bağlantı kopyalanamadı. Bağlantıyı seçip kopyalayabilirsiniz."))}>Bağlantıyı kopyala</button></div> : <p className={styles.info}>Paylaşılabilir bağlantı için kodlu kampanya ve doğrulanmış birincil mağaza alan adı gerekir.</p>}
    {canPublish ? <fieldset className={styles.batchForm}><legend>Yeni kupon grubu</legend><label>Kupon adedi<input inputMode="numeric" value={count} onChange={(event) => setCount(event.target.value)} /></label><label>Önek<input value={prefix} onChange={(event) => setPrefix(event.target.value.toUpperCase())} /></label><label>Toplam kod uzunluğu<input inputMode="numeric" value={codeLength} onChange={(event) => setCodeLength(event.target.value)} /></label><label>Müşteri başı kullanım<input inputMode="numeric" value={perCustomer} onChange={(event) => setPerCustomer(event.target.value)} /></label><label>Son kullanım (isteğe bağlı)<input type="datetime-local" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} /></label><button className={styles.primaryButton} disabled={busy.includes("create") || loading} type="button" onClick={create}>{busy.includes("create") ? "Oluşturuluyor…" : "Kuponları oluştur"}</button></fieldset> : null}
    {message ? <p role="status" className={styles.info}>{message}</p> : null}
    {loadFailed ? <div className={styles.error} role="alert">Kupon grupları yüklenemedi. <button className={styles.textButton} type="button" onClick={() => load()}>Yeniden dene</button></div> : null}
    {loading ? <PanelLoadingState label="Kupon grupları yükleniyor…" /> : loadFailed && items.length === 0 ? null : items.length === 0 ? <p className={styles.info}>Henüz toplu kupon grubu yok.</p> : <><div className={styles.desktopTable} role="region" aria-label="Kupon grupları tablosu" tabIndex={0}><table aria-label="Kupon grupları"><thead><tr><th scope="col">Önek</th><th scope="col">Durum</th><th scope="col">Toplam</th><th scope="col">Kullanılan</th><th scope="col">Bekleyen</th><th scope="col">Kalan</th><th scope="col">Aksiyonlar</th></tr></thead><tbody>{items.map((batch) => <tr key={batch.id}><td>{batch.prefix || "—"}</td><td><PanelStatusBadge tone={batch.status === "active" ? "success" : "neutral"}>{BATCH_STATUS[batch.status]}</PanelStatusBadge></td><td>{batch.count}</td><td>{batch.used}</td><td>{batch.held}</td><td>{batch.remaining}</td><td>{batchActions(batch)}</td></tr>)}</tbody></table></div><div className={styles.mobileCards} aria-label="Kupon grupları mobil liste">{items.map((batch) => <article key={batch.id}><div><strong>{batch.prefix || "Öneksiz grup"}</strong><PanelStatusBadge tone={batch.status === "active" ? "success" : "neutral"}>{BATCH_STATUS[batch.status]}</PanelStatusBadge></div><dl><div><dt>Toplam</dt><dd>{batch.count}</dd></div><div><dt>Kullanılan</dt><dd>{batch.used}</dd></div><div><dt>Bekleyen</dt><dd>{batch.held}</dd></div><div><dt>Kalan</dt><dd>{batch.remaining}</dd></div></dl>{batchActions(batch)}</article>)}</div></>}
    {appendFailed ? <p className={styles.error} role="alert">Diğer kupon grupları yüklenemedi. Mevcut liste korunuyor.</p> : null}
    {!loading && nextCursor ? <button className={styles.secondaryButton} type="button" disabled={loadingMore} onClick={loadMore}>{loadingMore ? "Yükleniyor…" : appendFailed ? "Yeniden dene" : "Daha fazla göster"}</button> : null}
  </section>;
}
