"use client";

import { useEffect, useRef, useState } from "react";
import type { PromotionSimulatorResponse } from "@celebix/saas-contracts";
import { promotionApi, promotionErrorMessage } from "@/lib/promotion-ui/client";
import { formatPromotionMinor, isoToZonedLocalInput, promotionDraftSnapshot, zonedLocalInputToIso, type PromotionDraft, type PromotionTarget } from "@/lib/promotion-ui/model";
import { PromotionPicker } from "./PromotionTargetPicker";
import styles from "./promotion-studio.module.css";

type Props = Readonly<{ draft: PromotionDraft; promotionId: string; expectedVersion: number | null }>;
const REJECTION: Readonly<Record<string, string>> = Object.freeze({ customer_identity_required: "Müşteri kullanım sınırı için bir test müşterisi seçin.", margin_unknown_cost: "Bu üründe maliyet bilgisi olmadığı için kâr koruması kesinleşemedi.", conditions_not_met: "Sepet kampanya koşullarını karşılamıyor.", not_combinable: "Daha avantajlı ve birlikte kullanılamayan başka bir kampanya seçildi.", not_eligible: "Seçilen müşteri veya sepet bu kampanyaya uygun değil.", order_line_limit: "Sepet satırı güvenli değerlendirme sınırını aşıyor." });

export function PromotionSimulator({ draft, promotionId, expectedVersion }: Props) {
  const [customer, setCustomer] = useState<readonly PromotionTarget[]>([]), [product, setProduct] = useState<readonly PromotionTarget[]>([]), [variant, setVariant] = useState<readonly PromotionTarget[]>([]);
  const [secondProduct, setSecondProduct] = useState<readonly PromotionTarget[]>([]), [secondVariant, setSecondVariant] = useState<readonly PromotionTarget[]>([]), [secondLine, setSecondLine] = useState(false);
  const [shipping, setShipping] = useState<readonly PromotionTarget[]>([]), [payment, setPayment] = useState<readonly PromotionTarget[]>([]), [abandonedCart, setAbandonedCart] = useState<readonly PromotionTarget[]>([]);
  const [quantity, setQuantity] = useState(1), [secondQuantity, setSecondQuantity] = useState(1), [coupon, setCoupon] = useState(draft.triggerKind === "code" ? draft.codeInput : ""), [salesChannel, setSalesChannel] = useState<"storefront" | "quick_order">("storefront");
  const [scenarioTime, setScenarioTime] = useState(() => isoToZonedLocalInput(new Date().toISOString(), draft.timezone));
  const [result, setResult] = useState<PromotionSimulatorResponse | null>(null), [phase, setPhase] = useState<"idle" | "loading" | "error">("idle"), [message, setMessage] = useState("");
  const controller = useRef<AbortController | null>(null), generation = useRef(0), lineId = useRef(crypto.randomUUID()), secondLineId = useRef(crypto.randomUUID());
  let scenarioIso: string | null = null; try { scenarioIso = zonedLocalInputToIso(scenarioTime, draft.timezone); } catch { /* invalid merchant wall-clock input */ }
  const complete = customer.length === 1 && product.length === 1 && variant.length === 1 && Number.isSafeInteger(quantity) && quantity >= 1 && (!secondLine || (secondProduct.length === 1 && secondVariant.length === 1 && Number.isSafeInteger(secondQuantity) && secondQuantity >= 1)) && scenarioIso !== null;
  const scenarioKey = JSON.stringify({ promotionId, expectedVersion, rule: promotionDraftSnapshot(draft), customer, product, variant, secondProduct, secondVariant, secondLine, shipping, payment, abandonedCart, quantity, secondQuantity, coupon, salesChannel, scenarioTime });
  useEffect(() => { generation.current += 1; controller.current?.abort(); setResult(null); setPhase("idle"); setMessage(""); }, [scenarioKey]);
  useEffect(() => () => controller.current?.abort(), []);
  const run = () => {
    if (!complete) { setMessage(scenarioIso === null ? "Test zamanı mağaza saat diliminde geçerli olmalı." : "Test için müşteri, ürün, varyant ve geçerli adet seçin."); return; }
    const next = new AbortController(); controller.current?.abort(); controller.current = next; const requestGeneration = ++generation.current; setPhase("loading"); setMessage(""); setResult(null);
    const lines = [{ lineId: lineId.current, position: 0, productId: product[0]!.id, variantId: variant[0]!.id, quantity, unitPriceMinor: 0, unitCostMinor: null, currency: "TRY", categoryIds: [], brandId: null, collectionIds: [] }];
    if (secondLine) lines.push({ lineId: secondLineId.current, position: 1, productId: secondProduct[0]!.id, variantId: secondVariant[0]!.id, quantity: secondQuantity, unitPriceMinor: 0, unitCostMinor: null, currency: "TRY", categoryIds: [], brandId: null, collectionIds: [] });
    const context = { customerId: customer[0]!.id, paidOrderCount: 0, customerSegmentIds: [], customerTagIds: [], cartLines: lines, shippingMethodId: shipping[0]?.id ?? null, paymentMethodId: payment[0]?.id ?? null, shippingBeforeDiscountMinor: 0, currency: "TRY", storeLocalTime: scenarioIso!, salesChannel, submittedCodes: coupon.trim() ? [coupon] : [], abandonedCart: abandonedCart[0] ? { id: abandonedCart[0].id } : null };
    void promotionApi.simulate(draft, { promotionId, expectedVersion, context }, next.signal).then((response) => { if (!next.signal.aborted && requestGeneration === generation.current) { setResult(response); setPhase("idle"); } }).catch((error: unknown) => { if (!next.signal.aborted && requestGeneration === generation.current) { setPhase("error"); setMessage(promotionErrorMessage(error instanceof Error ? error.message : "promotion_unavailable")); } });
  };
  return <section className={styles.simulator} aria-labelledby="promotion-simulator-title">
    <div><span className={styles.eyebrow}>Kampanya önizlemesi</span><h3 id="promotion-simulator-title">Gerçek mağaza kayıtlarıyla deneyin</h3><p>Fiyat, maliyet, müşteri geçmişi, segment, etiket ve ürün sınıfları PostgreSQL’den çözülür. Test veri değiştirmez.</p></div>
    <div className={styles.simulatorGrid}><div><PromotionPicker title="Test müşterisi" help="Kimlik bilgileri maskeli gösterilir." kinds={["masked_customer"]} selected={customer} onChange={(items) => setCustomer(items.slice(-1))} /><PromotionPicker title="Terk edilmiş sepet" help="Yalnız gerçekten terk edilmiş, kurtarılmamış sepetler listelenir." kinds={["abandoned_cart"]} selected={abandonedCart} onChange={(items) => setAbandonedCart(items.slice(-1))} /></div><div><PromotionPicker title="Test ürünü" help="Aktif katalog ürününü seçin." kinds={["product"]} selected={product} onChange={(items) => setProduct(items.slice(-1))} /><PromotionPicker title="Test varyantı" help="Aktif katalog varyantını seçin." kinds={["variant"]} selected={variant} onChange={(items) => setVariant(items.slice(-1))} /><div className={styles.fieldGrid}><label>Adet<input type="number" min="1" value={quantity} onChange={(event) => setQuantity(Number(event.target.value))} /></label><label>Kupon kodu<input value={coupon} onChange={(event) => setCoupon(event.target.value)} /></label><label>Satış kanalı<select value={salesChannel} onChange={(event) => setSalesChannel(event.target.value as "storefront" | "quick_order")}><option value="storefront">Online mağaza</option><option value="quick_order">Hızlı sipariş</option></select></label><label>Test zamanı<input type="datetime-local" value={scenarioTime} onChange={(event) => setScenarioTime(event.target.value)} /></label></div><label className={styles.checkLabel}><input type="checkbox" checked={secondLine} onChange={(event) => setSecondLine(event.target.checked)} /> İkinci ürün satırı ekle</label>{secondLine ? <div className={styles.secondaryLine}><PromotionPicker title="İkinci ürün" help="Çok ürünlü senaryolar için." kinds={["product"]} selected={secondProduct} onChange={(items) => setSecondProduct(items.slice(-1))} /><PromotionPicker title="İkinci varyant" help="Aktif varyantı seçin." kinds={["variant"]} selected={secondVariant} onChange={(items) => setSecondVariant(items.slice(-1))} /><label>İkinci ürün adedi<input type="number" min="1" value={secondQuantity} onChange={(event) => setSecondQuantity(Number(event.target.value))} /></label></div> : null}<PromotionPicker title="Kargo yöntemi" help="Kargo şartını gerçek kayıtla test edin." kinds={["shipping_method"]} selected={shipping} onChange={(items) => setShipping(items.slice(-1))} /><PromotionPicker title="Ödeme yöntemi" help="Ödeme şartını gerçek kayıtla test edin." kinds={["payment_method"]} selected={payment} onChange={(items) => setPayment(items.slice(-1))} /></div></div>
    <div className={styles.simulatorAction}><span>Sepet tutarı sunucudaki güncel fiyatlardan hesaplanır.</span><button type="button" className={styles.primaryButton} disabled={phase === "loading"} onClick={run}>{phase === "loading" ? "Kontrol ediliyor…" : "Senaryoyu kontrol et"}</button></div>
    {message ? <p role={phase === "error" ? "alert" : "status"}>{message}</p> : null}
    {result ? <div className={styles.simulatorResult} aria-live="polite"><h4>Sunucu sonucu</h4>{result.evaluation.appliedPromotions.length ? <ul>{result.evaluation.appliedPromotions.map((item) => <li key={item.promotionId}><strong>{item.name} uygulandı</strong><span>−{formatPromotionMinor(item.discountTotalMinor, result.evaluation.currency)}</span></li>)}</ul> : <p>Bu sepet için bir kampanya uygulanmadı.</p>}{result.evaluation.rejectedPromotions.length ? <details><summary>Uygulanmayan kampanyalar</summary><ul>{result.evaluation.rejectedPromotions.map((item) => <li key={`${item.promotionId}:${item.reason}`}>{REJECTION[item.reason] ?? "Kampanya koşulları sağlanmadı."}</li>)}</ul></details> : null}<dl><div><dt>Ürünler</dt><dd>{formatPromotionMinor(result.evaluation.subtotalBeforeDiscountMinor, result.evaluation.currency)}</dd></div><div><dt>Toplam indirim</dt><dd>−{formatPromotionMinor(result.evaluation.discountTotalMinor, result.evaluation.currency)}</dd></div><div><dt>Ödenecek</dt><dd>{formatPromotionMinor(result.evaluation.grandTotalMinor, result.evaluation.currency)}</dd></div></dl>{result.mutated === false ? <p className={styles.success}>Yalnızca önizleme yapıldı; mağaza verisi değiştirilmedi.</p> : null}</div> : null}
  </section>;
}
