import assert from 'node:assert/strict';
import test from 'node:test';

async function api(){const module=await import('./index.ts').catch(()=>null);assert.equal(typeof module?.parseStoreEngagementConfig,'function','engagement config parser must exist');return module!;}
const id='40000000-0000-4000-8000-000000000001';
const config={schemaVersion:1,template:'minimal',heading:'Merhaba',body:'',buttonLabel:'Devam et',delaySeconds:5,repeatDays:7,devices:{desktop:true,mobile:true},collectMode:'either'};
test('engagement config keeps only supported templates and owned media references',async()=>{const m=await api();assert.deepEqual(m.parseStoreEngagementConfig(config),config);assert.ok(Object.isFrozen(m.parseStoreEngagementConfig(config)));assert.deepEqual(m.parseStoreEngagementConfig({...config,image:{kind:'media',mediaId:id}}).image,{kind:'media',mediaId:id});for(const value of[{...config,image:{kind:'legacy_https',url:'https://evil.invalid/x'}},{...config,image:null},{...config,template:'html'},{...config,delaySeconds:121},{...config,repeatDays:0},{...config,devices:{desktop:false,mobile:false}},{...config,script:'<script>'}])assert.throws(()=>m.parseStoreEngagementConfig(value));});
test('contact capture normalizes supported addresses and rejects forged authority',async()=>{const m=await api();assert.equal(m.normalizeStoreEngagementEmail(' Ada@Example.COM '),'ada@example.com');assert.equal(m.normalizeStoreEngagementPhone('0530 209 96 28'),'+905302099628');assert.equal(m.normalizeStoreEngagementPhone('+44 7700 900123'),'+447700900123');for(const value of['x','a\n@b.com','a@localhost'])assert.throws(()=>m.normalizeStoreEngagementEmail(value));for(const value of['123','+900','053020996280'])assert.throws(()=>m.normalizeStoreEngagementPhone(value));assert.throws(()=>m.parseStoreEngagementCaptureRequest({operationId:id,campaignId:id,email:'ada@example.com',marketingConsent:false,customerId:id}));assert.throws(()=>m.parseStoreEngagementCaptureRequest({operationId:id,campaignId:id,marketingConsent:false}));assert.deepEqual(m.parseStoreEngagementCaptureRequest({operationId:id,campaignId:id,email:'ADA@EXAMPLE.COM',marketingConsent:false}),{operationId:id,campaignId:id,email:'ada@example.com',marketingConsent:false});});
test('public campaign projection requires server-resolved media and coupon fields',async()=>{const m=await api();const campaign={id,kind:'popup',name:'Karşılama',enabled:true,version:1,config,updatedAt:'2026-10-04T10:00:00.000Z'};assert.deepEqual(m.parseStoreEngagementCampaign(campaign),campaign);assert.deepEqual(m.parseStoreEngagementPublicSettings({popups:[{...campaign,imageUrl:null,couponCode:'HOSGELDIN3'}],cartCapture:null}).popups[0]?.couponCode,'HOSGELDIN3');assert.throws(()=>m.parseStoreEngagementPublicSettings({popups:[{...campaign,imageUrl:'javascript:alert(1)',couponCode:null}],cartCapture:null}));assert.throws(()=>m.parseStoreEngagementPublicSettings({popups:[],cartCapture:{...campaign,kind:'cart_capture',imageUrl:null,couponCode:'SECRET'}}));});
