import type {EmailMarketingProviderAdapter,EmailMarketingContactState,EmailMarketingProfile} from '../provider.ts';
import {createEmailMarketingTransport,type EmailMarketingTransportOptions} from '../transport.ts';
import {EmailMarketingError} from '../errors.ts';
import * as check from './common.ts';
export function createBrevoEmailMarketingAdapter(options:EmailMarketingTransportOptions):EmailMarketingProviderAdapter{
 const transport=createEmailMarketingTransport('brevo',options),now=options.now??(()=>new Date());
 function state(value:unknown):EmailMarketingContactState{const c=check.object(value),lists=check.array(c.listIds??[],1000).map(check.id),denied=c.emailBlacklisted===true;return Object.freeze({kind:'known',profileId:check.id(c.id),marketingStatus:denied?'suppressed':check.date(check.object(c.attributes??{}).CELEBIX_CONSENT_AT)?'subscribed':'unknown',listIds:Object.freeze(lists),suppressionReasons:Object.freeze(denied?['email_blacklisted']:[]),unsubscribedListIds:Object.freeze(check.array(c.listUnsubscribed??[],1000).map(check.id)),consentUpdatedAt:check.date(check.object(c.attributes??{}).CELEBIX_CONSENT_AT),observedAt:now().toISOString()});}
 async function byId(key:string,profileId:string){check.numericId(profileId);const r=await transport.request(key,`contacts/${profileId}`,{allowNotFound:true});return r.status===404?check.absent(now()):state(r.data);}
 async function attributes(key:string,p:EmailMarketingProfile){const r=check.object((await transport.request(key,'contacts/attributes')).data);const names=new Set(check.array(r.attributes,1000).map(a=>check.text(check.object(a).name,160)));return {...(p.firstName&&(names.has('FIRSTNAME')||names.has('FNAME'))?{[names.has('FIRSTNAME')?'FIRSTNAME':'FNAME']:p.firstName}:{}),...(p.lastName&&(names.has('LASTNAME')||names.has('LNAME'))?{[names.has('LASTNAME')?'LASTNAME':'LNAME']:p.lastName}:{})};}
 async function membership(key:string,profileId:string,listId:string,add:boolean){check.numericId(profileId);check.numericId(listId);const current=await byId(key,profileId);if(current.kind==='absent'||current.listIds.includes(listId)===add)return {kind:'verified' as const,value:null};const r=await transport.request(key,`contacts/lists/${listId}/contacts/${add?'add':'remove'}`,{method:'POST',body:{ids:[check.numericId(profileId)]}});if(r.status===202)return {kind:'accepted' as const};const after=await byId(key,profileId);return after.kind==='known'&&after.listIds.includes(listId)===add?{kind:'verified' as const,value:null}:{kind:'unknown' as const};}
 const adapter:EmailMarketingProviderAdapter={
 capabilities:Object.freeze({delta:false,webhook:true,senderChecking:false}),
 async account(key){const a=check.object((await transport.request(key,'account')).data);return {id:check.id(a.organization_id),name:check.text(a.companyName??'Brevo',160),senderStatus:'unknown'};},
 async lists(key,cursor){if(cursor!==undefined&&!/^[0-9]{1,8}$/.test(cursor))throw new EmailMarketingError('invalid_input');const offset=Number(cursor??0),data=check.object((await transport.request(key,`contacts/lists?limit=50&offset=${offset}`)).data),items=check.array(data.lists,50).map(v=>{const l=check.object(v);return {id:check.id(l.id),name:check.text(l.name,160)};});return {items,...(items.length===50?{nextCursor:String(offset+50)}:{})};},
 async createList(key,name){check.text(name,160);const data=check.object((await transport.request(key,'contacts/folders?limit=50&offset=0')).data),folders=check.array(data.folders,50);if(!folders.length)throw new EmailMarketingError('provider_forbidden');const folderId=check.numericId(check.id(check.object(folders[0]).id));const result=await transport.request(key,'contacts/lists',{method:'POST',body:{name,folderId}});if(result.status===202)return {kind:'accepted'};return {kind:'verified',value:{id:check.id(check.object(result.data).id),name}};},
 async contact(key,address){address=check.email(address);const r=await transport.request(key,`contacts/${encodeURIComponent(address)}`,{allowNotFound:true});if(r.status===404)return check.absent(now());const c=check.object(r.data);if(check.email(c.email)!==address)throw new EmailMarketingError('provider_invalid_response');return state(c);},
 async updateProfile(key,profileId,input){const p=check.profile(input),before=await byId(key,profileId);if(before.kind!=='known')throw new EmailMarketingError('provider_forbidden');const fields=await attributes(key,p);if(Object.keys(fields).length)await transport.request(key,`contacts/${profileId}`,{method:'PUT',body:{attributes:fields}});return {kind:'verified',value:await byId(key,profileId)};},
 addMembership:(key,p,l)=>membership(key,p,l,true),removeMembership:(key,p,l)=>membership(key,p,l,false),
 async subscribeNew(key,input,proof,listId){const p=check.profile(input),e=check.evidence(proof,now()),cutoff=now();cutoff.setUTCFullYear(cutoff.getUTCFullYear()-2);if(Date.parse(e.consentedAt)<cutoff.getTime())throw new EmailMarketingError('provider_forbidden');check.numericId(listId);if((await adapter.contact(key,p.email)).kind!=='absent')throw new EmailMarketingError('provider_forbidden');
  const data=check.object((await transport.request(key,'contacts/attributes')).data),names=new Set(check.array(data.attributes,1000).map(a=>check.text(check.object(a).name,160)));
  for(const name of ['CELEBIX_CONSENT_AT','CELEBIX_CONSENT_SOURCE','CELEBIX_CONSENT_VERSION'])if(!names.has(name))await transport.request(key,`contacts/attributes/normal/${name}`,{method:'POST',body:{type:'text'}});
  const fields={...(p.firstName&&(names.has('FIRSTNAME')||names.has('FNAME'))?{[names.has('FIRSTNAME')?'FIRSTNAME':'FNAME']:p.firstName}:{}),...(p.lastName&&(names.has('LASTNAME')||names.has('LNAME'))?{[names.has('LASTNAME')?'LASTNAME':'LNAME']:p.lastName}:{}),CELEBIX_CONSENT_AT:e.consentedAt,CELEBIX_CONSENT_SOURCE:e.source,CELEBIX_CONSENT_VERSION:e.version};
  const result=await transport.request(key,'contacts',{method:'POST',body:{email:p.email,attributes:fields,listIds:[check.numericId(listId)],updateEnabled:false}});return {kind:'accepted',...(result.data?{providerReference:check.id(check.object(result.data).id)}:{})};
 },
 async unsubscribe(key,profileId,scope){if(scope.kind==='list')return membership(key,profileId,scope.listId,false);const before=await byId(key,profileId);if(before.kind==='absent'||before.marketingStatus==='suppressed')return {kind:'verified',value:null};await transport.request(key,`contacts/${profileId}`,{method:'PUT',body:{emailBlacklisted:true}});const after=await byId(key,profileId);return after.kind==='known'&&after.marketingStatus==='suppressed'?{kind:'verified',value:null}:{kind:'unknown'};},
 async suppressionPage(key,cursor,_watermark){if(cursor!==undefined&&!/^[0-9]{1,8}$/.test(cursor))throw new EmailMarketingError('invalid_input');const offset=Number(cursor??0),r=check.object((await transport.request(key,`contacts?limit=100&offset=${offset}&sort=asc`)).data),rows=check.array(r.contacts,100),observedAt=now().toISOString();return {items:rows.flatMap(v=>{const c=check.object(v);return [...(c.emailBlacklisted===true?[check.event(check.id(c.id),check.email(c.email),'suppressed',null,observedAt)]:[]),...check.array(c.listUnsubscribed??[],1000).map(l=>check.event(check.id(c.id),check.email(c.email),'unsubscribe',null,observedAt,check.id(l)))];}),...(rows.length===100?{nextCursor:String(offset+100)}:{}),completedThrough:rows.length<100?observedAt:null};},
 async createWebhook(key,url,secret){let u:URL;try{u=new URL(url);}catch{throw new EmailMarketingError('invalid_input');}if(u.protocol!=='https:'||u.username||u.password||u.hash||u.search||!/^\/api\/marketing\/email-connections\/webhooks\/brevo\/[0-9a-f-]{36}$/.test(u.pathname)||u.hostname!=='panel.saas-staging.celebix.net')throw new EmailMarketingError('invalid_input');check.text(secret,160);const r=await transport.request(key,'webhooks',{method:'POST',body:{url,type:'marketing',events:['unsubscribed','spam','hardBounce','contactUpdated'],auth:{type:'bearer',token:secret}}});return r.status===202?{kind:'accepted'}:{kind:'verified',value:check.id(check.object(r.data).id)};},
 async deleteWebhook(key,webhookId){check.numericId(webhookId);await transport.request(key,`webhooks/${webhookId}`,{method:'DELETE',allowNotFound:true});return {kind:'verified',value:null};}
 };return Object.freeze(adapter);
}
