import type {EmailMarketingProviderAdapter,EmailMarketingContactState} from '../provider.ts';
import {createEmailMarketingTransport,type EmailMarketingTransportOptions} from '../transport.ts';
import {EmailMarketingError} from '../errors.ts';
import * as check from './common.ts';
export function createKlaviyoEmailMarketingAdapter(options:EmailMarketingTransportOptions):EmailMarketingProviderAdapter{
 const transport=createEmailMarketingTransport('klaviyo',options),now=options.now??(()=>new Date());
 function state(value:unknown,listIds:readonly string[]):EmailMarketingContactState{const p=check.object(value),a=check.object(p.attributes),subscriptions=check.object(a.subscriptions??{}),em=check.object(subscriptions.email??{}),marketing=check.object(em.marketing??{}),suppression=check.array(marketing?.suppression??[],100).map(v=>check.text(check.object(v).reason,160)),listSuppression=check.array(marketing?.list_suppressions??[],1000).map(v=>check.text(check.object(v).reason,160));return Object.freeze({kind:'known',firstName:typeof a.first_name==='string'&&a.first_name?check.text(a.first_name,120):null,lastName:typeof a.last_name==='string'&&a.last_name?check.text(a.last_name,120):null,profileId:check.id(p.id),marketingStatus:suppression.length?'suppressed':marketing?.consent==='SUBSCRIBED'?'subscribed':marketing?.consent==='UNSUBSCRIBED'?'unsubscribed':'unknown',listIds:Object.freeze([...listIds]),suppressionReasons:Object.freeze([...suppression,...listSuppression]),unsubscribedListIds:Object.freeze(check.array(marketing?.list_suppressions??[],1000).map(v=>check.id(check.object(v).list_id))),consentUpdatedAt:check.date(marketing?.consent_timestamp),observedAt:now().toISOString()});}
 async function membershipIds(key:string,profileId:string){const r=check.object((await transport.request(key,`profiles/${check.id(profileId)}/lists`,{budget:'klaviyo_membership_read'})).data);if(check.nextLink(check.object(r.links??{}).next,'lists'))throw new EmailMarketingError('provider_invalid_response');return check.array(r.data,100).map(v=>check.id(check.object(v).id));}
 async function byId(key:string,profileId:string){const r=await transport.request(key,`profiles/${check.id(profileId)}?additional-fields[profile]=subscriptions`,{allowNotFound:true});if(r.status===404)return {state:check.absent(now()),email:null};const p=check.object(check.object(r.data).data);return {state:state(p,await membershipIds(key,profileId)),email:check.email(check.object(p.attributes).email)};}
 async function membership(key:string,profileId:string,listId:string,add:boolean){check.id(profileId);check.id(listId);const before=await byId(key,profileId);if(before.state.kind==='absent'||before.state.listIds.includes(listId)===add)return {kind:'verified' as const,value:null};await transport.request(key,`lists/${listId}/relationships/profiles`,{method:add?'POST':'DELETE',body:{data:[{type:'profile',id:profileId}]},budget:'klaviyo_membership_write'});const lists=await membershipIds(key,profileId);return lists.includes(listId)===add?{kind:'verified' as const,value:null}:{kind:'unknown' as const};}
 const adapter:EmailMarketingProviderAdapter={
 capabilities:Object.freeze({delta:true,webhook:false,senderChecking:false}),
 async account(key){const r=check.object((await transport.request(key,'accounts',{budget:'klaviyo_accounts'})).data),rows=check.array(r.data,1);if(rows.length!==1)throw new EmailMarketingError('provider_invalid_response');const a=check.object(rows[0]),attrs=check.object(a.attributes),info=check.object(attrs.contact_information);return {id:check.id(a.id),name:check.text(info.organization_name??'Klaviyo',160),senderStatus:'unknown'};},
 async lists(key,cursor){if(cursor!==undefined)check.text(cursor,2048);const r=check.object((await transport.request(key,`lists?page[size]=10${cursor?`&page[cursor]=${encodeURIComponent(cursor)}`:''}`,{budget:'klaviyo_lists'})).data),items=check.array(r.data,10).map(v=>{const l=check.object(v);return {id:check.id(l.id),name:check.text(check.object(l.attributes).name,160)};}),nextCursor=check.nextLink(check.object(r.links??{}).next,'lists');return {items,...(nextCursor?{nextCursor}:{})};},
 async createList(key,name){check.text(name,160);const r=await transport.request(key,'lists',{method:'POST',body:{data:{type:'list',attributes:{name}}},budget:'klaviyo_list_create'});if(r.status===202)return {kind:'accepted'};const l=check.object(check.object(r.data).data);return {kind:'verified',value:{id:check.id(l.id),name:check.text(check.object(l.attributes).name,160)}};},
 async contact(key,address){address=check.email(address);const filter=encodeURIComponent(`equals(email,${JSON.stringify(address)})`),r=check.object((await transport.request(key,`profiles?filter=${filter}&additional-fields[profile]=subscriptions`)).data),rows=check.array(r.data,1);if(!rows.length)return check.absent(now());const p=check.object(rows[0]);if(check.email(check.object(p.attributes).email)!==address)throw new EmailMarketingError('provider_invalid_response');return state(p,await membershipIds(key,check.id(p.id)));},
 async updateProfile(key,profileId,input){const p=check.profile(input),before=await byId(key,profileId);if(before.state.kind!=='known'||before.email!==p.email)throw new EmailMarketingError('provider_forbidden');const attrs={...(p.firstName?{first_name:p.firstName}:{}),...(p.lastName?{last_name:p.lastName}:{})};if(Object.keys(attrs).length)await transport.request(key,`profiles/${profileId}`,{method:'PATCH',body:{data:{type:'profile',id:profileId,attributes:attrs}}});return {kind:'verified',value:(await byId(key,profileId)).state};},
 addMembership:(key,p,l)=>membership(key,p,l,true),removeMembership:(key,p,l)=>membership(key,p,l,false),
 async subscribeNew(key,input,proof,listId,historical){const p=check.profile(input),e=check.evidence(proof,now());check.id(listId);if((await adapter.contact(key,p.email)).kind!=='absent')throw new EmailMarketingError('provider_forbidden');const subscriptions={email:{marketing:{consent:'SUBSCRIBED',...(historical?{consented_at:e.consentedAt}:{})}}};
  const r=await transport.request(key,'profile-subscription-bulk-create-jobs',{method:'POST',body:{data:{type:'profile-subscription-bulk-create-job',attributes:{custom_source:`Celebix ${e.source}`,historical_import:historical,profiles:{data:[{type:'profile',attributes:{email:p.email,subscriptions}}]}},relationships:{list:{data:{type:'list',id:listId}}}}},budget:'klaviyo_subscription'});if(r.status!==202)throw new EmailMarketingError('outcome_unknown');return {kind:'accepted'};
 },
 async unsubscribe(key,profileId,scope){if(scope.kind==='list')return membership(key,profileId,scope.listId,false);const before=await byId(key,profileId);if(before.state.kind==='absent')throw new EmailMarketingError('provider_forbidden');if(before.state.marketingStatus==='unsubscribed'||before.state.marketingStatus==='suppressed')return {kind:'verified',value:null};const r=await transport.request(key,'profile-subscription-bulk-delete-jobs',{method:'POST',body:{data:{type:'profile-subscription-bulk-delete-job',attributes:{profiles:{data:[{type:'profile',attributes:{email:before.email,subscriptions:{email:{marketing:{consent:'UNSUBSCRIBED'}}}}}]}}}},budget:'klaviyo_subscription'});if(r.status!==202)throw new EmailMarketingError('outcome_unknown');return {kind:'accepted'};},
 async suppressionPage(key,cursor,watermark){if(cursor!==undefined)check.text(cursor,2048);if(watermark!==null&&!check.date(watermark))throw new EmailMarketingError('invalid_input');const since=watermark?encodeURIComponent(`greater-than(updated,${watermark})`):null,r=check.object((await transport.request(key,`profiles?page[size]=100&additional-fields[profile]=subscriptions${since?`&filter=${since}`:''}${cursor?`&page[cursor]=${encodeURIComponent(cursor)}`:''}`)).data),rows=check.array(r.data,100),observedAt=now().toISOString(),nextCursor=check.nextLink(check.object(r.links??{}).next,'profiles');const items=rows.flatMap(v=>{const p=check.object(v),a=check.object(p.attributes),s=state(p,[]),em=check.object(check.object(check.object(a.subscriptions??{}).email??{}).marketing??{});const listEvents=check.array(em.list_suppressions??[],1000).map(v=>{const l=check.object(v);return check.event(s.profileId!,check.email(a.email),'suppressed',check.date(l.timestamp),observedAt,check.id(l.list_id));});if(s.marketingStatus==='unsubscribed')return [check.event(s.profileId!,check.email(a.email),'unsubscribe',check.date(em.consent_timestamp),observedAt),...listEvents];if(s.marketingStatus==='suppressed'){const times=check.array(em.suppression??[],100).map(v=>check.date(check.object(v).timestamp)).filter((v):v is string=>!!v).sort();return [check.event(s.profileId!,check.email(a.email),'suppressed',times.at(-1)??null,observedAt),...listEvents];}return listEvents;});return {items,...(nextCursor?{nextCursor}:{}),completedThrough:nextCursor?null:observedAt};}
 };return Object.freeze(adapter);
}
