import assert from "node:assert/strict";
import { accessSync, constants, mkdtempSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync, chmodSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { spawn, spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../../");
const SQL = path.join(ROOT, "apps/owner/scripts/sql/saas");
const PG16 = "/Users/Celebix/.codex/tmp/postgresql-16.14-install/bin";
const DB = "catalog_collections_182";
const STORE = "10000000-0000-4000-8000-000000000001";
const STORE_B = "10000000-0000-4000-8000-000000000002";
const PLAN = "00000000-0000-4000-8000-000000000001";
const OWNER = "20000000-0000-4000-8000-000000000001";
const EDITOR = "20000000-0000-4000-8000-000000000002";
const ANALYST = "20000000-0000-4000-8000-000000000003";
const MO = "30000000-0000-4000-8000-000000000001";
const ME = "30000000-0000-4000-8000-000000000002";
const MA = "30000000-0000-4000-8000-000000000003";
const MB = "30000000-0000-4000-8000-000000000004";
const PRODUCT = "40000000-0000-4000-8000-000000000001";
const PRODUCT_B = "40000000-0000-4000-8000-000000000002";
const RESOURCE = "50000000-0000-4000-8000-000000000001";
const REVIEW = "60000000-0000-4000-8000-000000000001";
const NOW = "2026-09-30T18:00:00.000Z";
const prior = ["202607110001_roles.up.sql","202607110002_foundation.up.sql","202607110003_free_starter.seed.sql","202607110003_plan_versions.freeze.sql","202607110004_grants.sql","202607110005_catalog_assertions.sql","202607110007_identity_roles.up.sql","202607110008_identity_persistence.up.sql","202607110009_identity_grants.sql","202607110010_identity_catalog_assertions.sql","202607120012_verified_identity_snapshot.up.sql","202607120013_verified_identity_grants.sql","202607120014_verified_identity_catalog_assertions.sql","202607140015_panel_sessions.up.sql","202607140016_panel_session_handoffs.up.sql","202607140017_panel_browser_bindings.up.sql","202607160018_product_catalog.up.sql","202607160018_product_catalog_assertions.sql","202607160019_product_catalog_api.up.sql","202607160019_product_catalog_api_assertions.sql","202607160020_pilot_storefront_media_domains.up.sql","202607160020_pilot_storefront_media_domains_assertions.sql","202607200021_catalog_dashboard_summary.up.sql","202607200021_catalog_dashboard_summary_assertions.sql","202607210022_order_management.up.sql","202607210022_order_management_assertions.sql","202607210023_order_management_api.up.sql","202607210023_order_management_api_assertions.sql","202607220024_quick_order_links.up.sql","202607220024_quick_order_links_assertions.sql","202607220025_quick_order_links_api.up.sql","202607220025_quick_order_links_api_assertions.sql","202607220026_quick_order_checkout_runtime.up.sql","202607220026_quick_order_checkout_runtime_assertions.sql","202607220027_quick_order_checkout_api.up.sql","202607220027_quick_order_checkout_api_assertions.sql","202607220028_quick_order_redemption_expiry_authority.up.sql","202607220028_quick_order_redemption_expiry_authority_assertions.sql","202607220029_quick_order_settlement_authority.up.sql","202607220029_quick_order_settlement_authority_assertions.sql","202607220030_abandoned_carts.up.sql","202607220030_abandoned_carts_assertions.sql","202607220031_abandoned_cart_api.up.sql","202607220031_abandoned_cart_api_assertions.sql","202607220032_abandoned_cart_capture.up.sql","202607220032_abandoned_cart_capture_assertions.sql","202607220033_customer_management.up.sql","202607220033_customer_management_assertions.sql","202607220034_customer_management_api.up.sql","202607220034_customer_management_api_assertions.sql"];

function executable(name) { for (const directory of [PG16, ...(process.env.PATH ?? "").split(path.delimiter)]) { if (!directory) continue; const candidate = path.join(directory, name); try { accessSync(candidate, constants.X_OK); return candidate; } catch {} } throw new Error("DISPOSABLE_DB_EXECUTION_BLOCKED"); }
function command(program, args, options = {}) { const result = spawnSync(program, args, { cwd: ROOT, encoding: "utf8", input: options.input, env: { ...process.env, LC_ALL: "C", LANG: "C" }, maxBuffer: 64 * 1024 * 1024 }); if (result.error) throw result.error; if (!options.allowFailure && result.status !== 0) throw new Error(`${path.basename(program)} failed\n${result.stderr}`); return result; }
function start() { const executables = Object.fromEntries(["initdb", "pg_ctl", "psql"].map((name) => [name, executable(name)])); const root = mkdtempSync(path.join(tmpdir(), "celebix-catalog-admin-")); const data = path.join(root, "data"); const socket = path.join(root, "socket"); const port = 20000 + Math.floor(Math.random() * 15000); mkdirSync(socket, { mode: 0o700 }); command(executables.initdb, ["-D", data, "--auth=trust", "--username=postgres", "--no-locale", "--encoding=UTF8"]); command(executables.pg_ctl, ["-D", data, "-o", `-k ${socket} -p ${port} -h ''`, "-l", path.join(root, "postgres.log"), "start"]); return { executables, root, data, socket, port }; }
function stop(box) { if (!box) return; command(box.executables.pg_ctl, ["-D", box.data, "-m", "fast", "stop"], { allowFailure: true }); rmSync(box.root, { recursive: true, force: true }); }
function psql(box, source, database = DB, options = {}) { return command(box.executables.psql, ["-h", box.socket, "-p", String(box.port), "-X", "-qAt", "-v", "ON_ERROR_STOP=1", "-U", "postgres", "-d", database], { input: "SET statement_timeout='45s';\n"+source, allowFailure: options.allowFailure }); }
function psqlAsync(box, source, database = DB) { return new Promise((resolve, reject) => { const child = spawn(box.executables.psql, ["-h", box.socket, "-p", String(box.port), "-X", "-qAt", "-v", "ON_ERROR_STOP=1", "-U", "postgres", "-d", database], { cwd: ROOT, env: { ...process.env, LC_ALL: "C", LANG: "C" } }); let stdout = "", stderr = ""; child.stdout.setEncoding("utf8").on("data", (value) => { stdout += value; }); child.stderr.setEncoding("utf8").on("data", (value) => { stderr += value; }); child.once("error", reject); child.once("close", (status) => status === 0 ? resolve({ stdout, stderr }) : reject(new Error(`psql failed\n${stderr}`))); child.stdin.end(source); }); }
function apply(box, file) { psql(box, readFileSync(path.join(SQL, file), "utf8")); }
function authority({ store = STORE, principal = OWNER, membership = MO } = {}) { return `'${store}'::uuid,'${principal}'::uuid,'${membership}'::uuid,'${PLAN}'::uuid,'free_starter',1,'${NOW}'::timestamptz`; }
function api(box, name, extra = "", actor = {}) { const output = psql(box, `SET ROLE celebix_saas_app;SELECT jsonb_build_object('outcome',outcome,'result',result_payload) FROM saas.${name}(${authority(actor)}${extra ? `,${extra}` : ""});`).stdout.trim(); return JSON.parse(output); }
async function apiAsync(box, name, extra = "", actor = {}) { const output = await psqlAsync(box, `SET ROLE celebix_saas_app;SELECT jsonb_build_object('outcome',outcome,'result',result_payload) FROM saas.${name}(${authority(actor)}${extra ? `,${extra}` : ""});`); return JSON.parse(output.stdout.trim()); }
function importRows(rows) { return JSON.stringify(rows).replaceAll("'", "''"); }
function importInput({ limit = 100, operationId, fingerprint, jobId, fileName, rows }) { return `${limit},'${operationId}','${fingerprint}','${jobId}','${fileName}','${importRows(rows)}'::jsonb`; }
function richImportInput({ limit = 100, operationId, fingerprint, jobId, fileName, products }) { return `${limit},'${operationId}','${fingerprint}','${jobId}','${fileName}','${importRows(products)}'::jsonb`; }
function seed(box) { psql(box, `BEGIN;SET LOCAL ROLE celebix_saas_owner;
INSERT INTO saas.principals(id,issuer,subject,email,email_verified,created_at,updated_at) VALUES('${OWNER}','https://id.test/oidc','owner','owner@test.invalid',true,'2026-01-01','2026-01-01'),('${EDITOR}','https://id.test/oidc','editor','editor@test.invalid',true,'2026-01-01','2026-01-01'),('${ANALYST}','https://id.test/oidc','analyst','analyst@test.invalid',true,'2026-01-01','2026-01-01');
INSERT INTO saas.stores(id,name,slug,status,locale,currency,theme_key,created_at,updated_at) VALUES('${STORE}','Catalog A','catalog-a','active','tr','TRY','default','2026-01-01','2026-01-01'),('${STORE_B}','Catalog B','catalog-b','active','tr','TRY','default','2026-01-01','2026-01-01');
INSERT INTO saas.memberships(id,principal_id,store_id,role,status,created_at,updated_at) VALUES('${MO}','${OWNER}','${STORE}','store_owner','active','2026-01-01','2026-01-01'),('${ME}','${EDITOR}','${STORE}','editor','active','2026-01-01','2026-01-01'),('${MA}','${ANALYST}','${STORE}','analyst','active','2026-01-01','2026-01-01'),('${MB}','${OWNER}','${STORE_B}','store_owner','active','2026-01-01','2026-01-01');
INSERT INTO saas.subscriptions(id,store_id,plan_id,plan_code,plan_version,status,valid_from,created_at,updated_at) VALUES('70000000-0000-4000-8000-000000000001','${STORE}','${PLAN}','free_starter',1,'active','2026-01-01','2026-01-01','2026-01-01'),('70000000-0000-4000-8000-000000000002','${STORE_B}','${PLAN}','free_starter',1,'active','2026-01-01','2026-01-01','2026-01-01');
INSERT INTO saas.products(id,store_id,slug,title,status,currency,version,created_at,updated_at) VALUES('${PRODUCT}','${STORE}','keten-gomlek','Keten Gomlek','active','TRY',1,'2026-01-01','2026-01-01'),('${PRODUCT_B}','${STORE_B}','baska-urun','Baska Urun','active','TRY',1,'2026-01-01','2026-01-01');
INSERT INTO saas.product_reviews(id,store_id,product_id,reviewer_name,rating,review_title,review_body,status,version,created_at,updated_at) VALUES('${REVIEW}','${STORE}','${PRODUCT}','Ada',5,'Harika','Cok memnun kaldim.','pending',1,'2026-01-02','2026-01-02');COMMIT;`); }

function chain() {
  const accepted=/(?:[.]up|[.]seed|[.]freeze|_grants|_assertions|catalog_assertions)[.]sql$/;
  return readdirSync(SQL).filter(file=>/^2026\d{8}_.+[.]sql$/.test(file)&&!file.includes('.down.')&&!file.includes('rollback')&&!file.includes('forward_recovery')&&file!=='202607300073_seed_guzide_pilot_admin_domain.up.sql'&&![148,161,166].includes(Number(file.slice(8,12)))&&Number(file.slice(8,12))<=181&&(Number(file.slice(8,12))<=71?accepted.test(file):file.endsWith('.up.sql'))).sort((a,b)=>Number(a.slice(8,12))-Number(b.slice(8,12))||((a.includes('assertions')?3:a.includes('freeze')||a.includes('grants')?2:1)-(b.includes('assertions')?3:b.includes('freeze')||b.includes('grants')?2:1))||a.localeCompare(b));
}
const ARTIFACT_DIR=process.env.COLLECTION_ARTIFACT_DIR??'/Users/Celebix/.codex/tmp/collection-sql-native';
function artifact(name,data){mkdirSync(ARTIFACT_DIR,{recursive:true,mode:0o700});chmodSync(ARTIFACT_DIR,0o700);const file=path.join(ARTIFACT_DIR,name);writeFileSync(file,JSON.stringify(data,null,2)+'\n',{mode:0o600});chmodSync(file,0o600);}
function inventory(box,table){const identity=table.includes('design')?'signature':'identity',settings=table.includes('design')?'config':'settings';return JSON.parse(psql(box,`SELECT COALESCE(jsonb_agg(jsonb_build_object('identity',b.${identity},'definition',b.definition,'owner',r.rolname,'acl',b.acl,'settings',b.${settings},'securityDefiner',b.security_definer) ORDER BY b.${identity}),'[]'::jsonb) FROM saas.${table} b JOIN pg_roles r ON r.oid=b.owner_id WHERE b.${identity} NOT LIKE 'constraint:%';`).stdout.trim()).map(({definition,...row})=>({...row,sha256:createHash('sha256').update(definition).digest('hex')}));}
let passed=0;
function check(name,fn){fn();passed++;console.log(`PASS ${passed} ${name}`);}
const config={schemaVersion:1,mode:'manual',published:false,featured:false,match:'all',rules:[],sort:'custom'};
const encoded=value=>`'${JSON.stringify(value).replaceAll("'","''")}'::jsonb`;
async function main(){let box;try{box=start();psql(box,`CREATE DATABASE ${DB};`,'postgres');for(const file of chain())apply(box,file);seed(box);
 check('collection migration applies',()=>{const atomicFiles=['202609300182_catalog_collections.up.sql','202609300182_catalog_collections_assertions.sql','202609300183_catalog_collection_design_navigation.up.sql','202609300183_catalog_collection_design_navigation_assertions.sql'];const atomicSource=atomicFiles.map(file=>readFileSync(path.join(SQL,file),'utf8').split('\n').filter(line=>!['BEGIN;','COMMIT;'].includes(line.trim())).join('\n')).join('\n');psql(box,'BEGIN;\n'+atomicSource+'\nROLLBACK;');assert.equal(psql(box,`SELECT to_regclass('saas.catalog_collections_182_backup') IS NULL AND to_regclass('saas.catalog_collection_design_backup_183') IS NULL;`).stdout.trim(),'t');apply(box,'202609300182_catalog_collections.up.sql');apply(box,'202609300182_catalog_collections_assertions.sql');});
 check('exact rollback and reapply preserve original function bodies and authority',()=>{const snapshots=psql(box,`SELECT jsonb_agg(jsonb_build_object('identity',identity,'definition',definition,'owner',owner_id,'acl',acl,'settings',settings,'security',security_definer) ORDER BY identity) FROM saas.catalog_collections_182_backup WHERE identity NOT LIKE 'constraint:%';`).stdout.trim();apply(box,'202609300182_catalog_collections.down.sql');for(const row of JSON.parse(snapshots)){const value=JSON.parse(psql(box,`SELECT jsonb_build_object('definition',pg_get_functiondef(oid),'owner',proowner,'acl',proacl,'settings',proconfig,'security',prosecdef) FROM pg_proc WHERE oid='${row.identity}'::regprocedure;`).stdout.trim());assert.deepEqual(value,{definition:row.definition,owner:row.owner,acl:row.acl,settings:row.settings,security:row.security});}apply(box,'202609300182_catalog_collections.up.sql');apply(box,'202609300182_catalog_collections_assertions.sql');});
 check('183 design navigation migration applies after182',()=>{apply(box,'202609300183_catalog_collection_design_navigation.up.sql');apply(box,'202609300183_catalog_collection_design_navigation_assertions.sql');artifact('predecessor-functions.json',{baseline:'b910b1c854f79d3942ce1af975b9ee62411c608d',migrations:[{id:182,functions:inventory(box,'catalog_collections_182_backup')},{id:183,functions:inventory(box,'catalog_collection_design_backup_183')}]});});
 check('manual config validates with durable tenant guards',()=>assert.equal(psql(box,`SET ROLE celebix_saas_owner;SELECT saas.catalog_collection_config_valid('${STORE}',${encoded(config)});`).stdout.trim(),'t'));
 const CAT='57000000-0000-4000-8000-000000000001', CHILD='57000000-0000-4000-8000-000000000002', BRAND='57000000-0000-4000-8000-000000000003', TAG='57000000-0000-4000-8000-000000000004', MANUAL='57000000-0000-4000-8000-000000000005', AUTO='57000000-0000-4000-8000-000000000006', OTHER='57000000-0000-4000-8000-000000000007', COVER='58000000-0000-4000-8000-000000000001';
 const ids=Array.from({length:1187},(_,i)=>`45000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`),A=ids[403],B=ids[404],C=ids[405],D=ids[406];
 const array=values=>`ARRAY[${values.map(id=>`'${id}'::uuid`).join(',')}]::uuid[]`;
 let operation=0;
 const op=()=>`89000000-0000-4000-8000-${String(++operation).padStart(12,'0')}`;
 const saveArgs=(resource,version,cfg,values=[],name='Sonbahar',slug='',description=null)=>`'${op()}','${'a'.repeat(64)}','${resource}',${version===null?'NULL':version},'collection','${name}','${slug}',${description===null?'NULL':`'${description.replaceAll("'","''")}'`},${encoded(cfg)},${array(values)}`;
 const save=(...args)=>api(box,'catalog_admin_save_resource',saveArgs(...args));
 const detail=id=>api(box,'catalog_admin_get_collection',`'${id}'`).result;
 const members=(id,cfg,query={page:1,pageSize:2,mode:'members'})=>api(box,'catalog_admin_collection_members',`${id?`'${id}'`:'NULL'},${cfg?encoded(cfg):'NULL'},${encoded(query)}`);
 const publicQuery=(slug,order='featured',offset=0,filter='all',host='catalog-a.saas-staging.celebix.site')=>JSON.parse(psql(box,`SET ROLE celebix_saas_host_resolver;SELECT jsonb_build_object('outcome',outcome,'result',result_payload) FROM saas.public_catalog_collection_query('${host}','${NOW}','${slug}','','${filter}','${order}',2,${offset});`).stdout.trim());
 psql(box,`BEGIN;SET LOCAL ROLE celebix_saas_owner;
 -- Bulk fixture generation bypasses unrelated per-row SEO notifications only. Runtime functions and all durable authority remain real.
 ALTER TABLE saas.products DISABLE TRIGGER seo_resource_notification;
 ALTER TABLE saas.catalog_categories DISABLE TRIGGER seo_resource_notification;
 ALTER TABLE saas.product_variants DISABLE TRIGGER seo_resource_notification;
 INSERT INTO saas.products(id,store_id,slug,title,status,currency,version,created_at,updated_at,archived_at) SELECT ('45000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'${STORE}','collection-product-'||lpad(n::text,5,'0'),'Urun '||lpad(n::text,5,'0'),CASE WHEN n<=6 THEN 'archived' WHEN n<=403 THEN 'draft' ELSE 'active' END,'TRY',1,'2026-01-01','2026-01-01',CASE WHEN n<=6 THEN '2026-01-01'::timestamptz END FROM generate_series(1,1187) n;
 INSERT INTO saas.catalog_categories(id,store_id,parent_id,name,slug,position,depth,status,version,created_at,updated_at) VALUES('${CAT}','${STORE}',NULL,'Yeni','yeni',0,1,'active',1,'2026-01-01','2026-01-01'),('${CHILD}','${STORE}','${CAT}','Alt','alt',0,2,'active',1,'2026-01-01','2026-01-01');
 INSERT INTO saas.catalog_admin_resources(id,store_id,resource_kind,name,slug,config,status,version,created_at,updated_at) VALUES('${BRAND}','${STORE}','brand','Marka','marka','{}','active',1,'2026-01-01','2026-01-01'),('${TAG}','${STORE}','tag','Etiket','etiket','{}','active',1,'2026-01-01','2026-01-01'),('${MANUAL}','${STORE}','collection','Guzide','guzide','{"featured":true}','active',1,'2026-01-01','2026-01-01'),('${OTHER}','${STORE_B}','brand','Yabanci','yabanci','{}','active',1,'2026-01-01','2026-01-01');
 INSERT INTO saas.catalog_admin_resource_products(store_id,resource_id,product_id,position) SELECT '${STORE}','${MANUAL}',id,ordinality-1 FROM unnest(${array(ids)}) WITH ORDINALITY x(id,ordinality);
 INSERT INTO saas.catalog_admin_resource_products(store_id,resource_id,product_id,position) VALUES('${STORE}','${BRAND}','${A}',0),('${STORE}','${BRAND}','${B}',1),('${STORE}','${TAG}','${B}',0),('${STORE}','${TAG}','${C}',1);
 INSERT INTO saas.catalog_product_categories(store_id,product_id,category_id,position) VALUES('${STORE}','${A}','${CHILD}',0),('${STORE}','${C}','${CHILD}',0);
 ALTER TABLE saas.product_variants DISABLE TRIGGER product_variants_inventory_reconcile;
 INSERT INTO saas.product_variants(id,product_id,store_id,title,sku,price_cents,compare_at_cents,stock_tracking,stock_quantity,status,created_at,updated_at) VALUES('${A}','${A}','${STORE}','A','SKU-A',300,600,false,0,'active','2026-01-01','2026-01-01'),('${B}','${B}','${STORE}','B','SKU-B',200,NULL,false,0,'active','2026-01-01','2026-01-01'),('${C}','${C}','${STORE}','C','SKU-C',100,NULL,false,0,'active','2026-01-01','2026-01-01'),('${D}','${D}','${STORE}','D','SKU-D',400,NULL,false,0,'active','2026-01-02','2026-01-02');
 ALTER TABLE saas.product_variants ENABLE TRIGGER product_variants_inventory_reconcile;
 INSERT INTO saas.store_domains(id,store_id,hostname,hostname_type,status,is_primary,verified_at,created_at,updated_at,version) VALUES('${COVER}','${STORE}','catalog-a.saas-staging.celebix.site','platform_subdomain','active',true,'2026-01-01','2026-01-01','2026-01-01',1);
 ALTER TABLE saas.products ENABLE TRIGGER seo_resource_notification;
 ALTER TABLE saas.catalog_categories ENABLE TRIGGER seo_resource_notification;
 ALTER TABLE saas.product_variants ENABLE TRIGGER seo_resource_notification;
 COMMIT;`);
 check('legacy collections normalize manual unpublished without changing links',()=>{const row=detail(MANUAL);assert.equal(row.config.mode,'manual');assert.equal(row.config.published,false);assert.equal(row.productCount,1187);assert.deepEqual(row.productIds,ids);});
 check('all1187 links including six archived are retained in a versioned collection save',()=>{assert.equal(save(MANUAL,1,config,ids,'Guzide','','Ilk satir\nIkinci satir').outcome,'saved');assert.deepEqual(detail(MANUAL).productIds,ids);assert.equal(detail(MANUAL).description,'Ilk satir\nIkinci satir');assert.equal(detail(MANUAL).slug,'guzide');});
 check('new archived duplicate and cross-store collection links remain denied',()=>{for(const values of [[ids[0]],[A,A],[PRODUCT_B]])assert.equal(save('57000000-0000-4000-8000-000000000008',null,config,values).outcome,'invalid_input');assert.equal(save(MANUAL,2,config,[...ids,PRODUCT_B],'Guzide').outcome,'invalid_input');});
 check('control characters other than description line breaks are denied',()=>assert.equal(save(MANUAL,2,config,ids,'Guzide','',String.fromCharCode(9)+'bad').outcome,'invalid_input'));
 const storage=Number(psql(box,`SELECT effective_limit FROM saas.plan_limits WHERE plan_id='${PLAN}' AND limit_key='storageBytes';`).stdout.trim());
 check('dedicated collection asset follows existing media authority and object-key policy',()=>{const object=`stores/${STORE}/storefront/collection/${COVER}.webp`;const extra=`${storage},'${NOW}','${op()}','${'b'.repeat(64)}','${COVER}','collection','${object}','https://media.saas-staging.celebix.site/${object}','image/webp','Sonbahar',600,800,1024`;const result=JSON.parse(psql(box,`SET ROLE celebix_saas_app;SELECT jsonb_build_object('outcome',outcome,'result',result_payload) FROM saas.storefront_asset_create('${STORE}','${OWNER}','${MO}','${PLAN}','free_starter',1,${extra});`).stdout.trim());assert.equal(result.outcome,'committed');});
 check('cover saves only active same-store collection assets',()=>{assert.equal(save(MANUAL,2,{...config,coverAssetId:COVER},ids,'Guzide').outcome,'saved');assert.equal(detail(MANUAL).cover.url,`https://media.saas-staging.celebix.site/stores/${STORE}/storefront/collection/${COVER}.webp`);for(const coverAssetId of [OTHER,PRODUCT_B])assert.equal(save(MANUAL,3,{...config,coverAssetId},ids,'Guzide').outcome,'invalid_input');});
 const catRule={kind:'category',resourceId:CAT},brandRule={kind:'brand',resourceId:BRAND},tagRule={kind:'tag',resourceId:TAG};
 const auto={...config,mode:'automatic',rules:[catRule,brandRule],published:true};
 check('automatic all rules include category descendants and ignore nonmatching pins',()=>{assert.equal(save(AUTO,null,auto,[C,B]).outcome,'saved');const result=members(AUTO,null);assert.equal(result.outcome,'listed');assert.equal(result.result.totalCount,1);assert.deepEqual(result.result.orderedIds,[A]);});
 check('automatic any rules preview uses the same membership without durable writes',()=>{const result=members(AUTO,{...auto,match:'any'});assert.equal(result.result.totalCount,3);assert.deepEqual(result.result.orderedIds,[C,B,A]);assert.equal(detail(AUTO).config.match,'all');});
 check('automatic tag rules and server SKU search work with paginated catalog selection',()=>{assert.equal(members(null,{...auto,rules:[tagRule]}).result.totalCount,2);const result=members(null,config,{page:1,pageSize:2,mode:'catalog',search:'SKU-C'});assert.deepEqual(result.result.items.map(p=>p.id),[C]);});
 check('empty unknown duplicate and cross-store rule references are rejected',()=>{for(const cfg of [{...auto,rules:[]},{...auto,rules:[{kind:'tag',resourceId:OTHER}]},{...auto,rules:[catRule,catRule]},{...auto,rules:Array.from({length:11},()=>catRule)},{...auto,rules:[{kind:'supplier',resourceId:BRAND}]}])assert.equal(save('57000000-0000-4000-8000-000000000009',null,cfg,[]).outcome,'invalid_input');});
 check('saved mode remains immutable and automatic preview override cannot force membership',()=>{assert.equal(save(AUTO,1,config,[A]).outcome,'invalid_transition');const result=members(AUTO,null,{page:1,pageSize:2,mode:'members',productIds:[B,C]});assert.deepEqual(result.result.orderedIds,[A]);});
 check('automatic order pins precede stable new matches and survive page filters',()=>{assert.equal(save(AUTO,1,{...auto,rules:[catRule]},[C,B]).outcome,'saved');let result=members(AUTO,null,{page:1,pageSize:1,mode:'members',search:'Urun 00406'});assert.deepEqual(result.result.orderedIds,[C,A]);psql(box,`SET ROLE celebix_saas_owner;INSERT INTO saas.catalog_product_categories(store_id,product_id,category_id,position) VALUES('${STORE}','${D}','${CHILD}',0);`);result=members(AUTO,null);assert.deepEqual(result.result.orderedIds,[C,A,D]);});
 check('manual custom ordering spans pages and keeps unseen archived links',()=>{const reversed=[...ids].reverse();assert.equal(save(MANUAL,3,{...config,coverAssetId:COVER},reversed,'Guzide').outcome,'saved');const page=members(MANUAL,null,{page:2,pageSize:50,mode:'members'}).result;assert.equal(page.items.length,50);assert.deepEqual(page.orderedIds,reversed);assert.equal(page.items[0].id,reversed[50]);assert.equal(page.totalCount,1187);});
 check('collection list has truthful state counts and paginates without product ID payloads',()=>{const result=api(box,'catalog_admin_list_collections',encoded({page:1,pageSize:1,state:'all',sort:'updated'}));assert.equal(result.outcome,'listed');assert.equal(result.result.items.length,1);assert.equal(result.result.totalCount,2);assert.deepEqual(result.result.counts,{all:2,published:1,draft:1,archived:0});assert.equal('productIds' in result.result.items[0],false);});
 check('automatic collection memberships match promotion reference facts',()=>{for(const id of [A,C,D])assert.equal(psql(box,`SET ROLE celebix_saas_owner;SELECT saas.promotion_catalog_reference_matches_variant_v1('${STORE}','{"kind":"collection","id":"${AUTO}"}','${id}','${id}');`).stdout.trim(),'t');assert.equal(psql(box,`SET ROLE celebix_saas_owner;SELECT saas.promotion_catalog_reference_matches_variant_v1('${STORE}','{"kind":"collection","id":"${AUTO}"}','${B}','${B}');`).stdout.trim(),'f');});
 check('promotion materialized checkout lines include automatic matches and exclude pins',()=>{const context={salesChannel:'storefront',cartLines:[{lineId:A,position:0,productId:A,variantId:A,quantity:1,unitPriceMinor:300,unitCostMinor:null,currency:'TRY',categoryIds:[],brandId:null,collectionIds:[]}]};const lines=JSON.parse(psql(box,`SET ROLE celebix_saas_owner;SELECT saas.promotion_evaluator_materialize_lines('${STORE}','TRY',${encoded(context)},'${NOW}');`).stdout.trim());assert.ok(lines[0].collectionIds.includes(AUTO));});
 check('paginated product filters use automatic membership',()=>{const result=JSON.parse(psql(box,`SET ROLE celebix_saas_app;SELECT jsonb_build_object('outcome',outcome,'result',result_payload) FROM saas.catalog_list_products_v5('${STORE}','${OWNER}','${MO}','${PLAN}','free_starter',1,100,'${NOW}',NULL,NULL,NULL,NULL,NULL,'${AUTO}','created-desc',50,NULL,NULL,NULL);`).stdout.trim());assert.equal(result.outcome,'listed');assert.deepEqual(result.result.items.map(p=>p.id).sort(),[A,C,D].sort());});
 check('public collection shows published visible products and preserves custom order across pages',()=>{const result=publicQuery(detail(AUTO).slug);assert.equal(result.outcome,'found');assert.equal(result.result.total,3);assert.deepEqual(result.result.items.map(p=>p.id),[C,A]);assert.equal(result.result.nextOffset,2);assert.deepEqual(publicQuery(detail(AUTO).slug,'featured',2).result.items.map(p=>p.id),[D]);assert.equal(publicQuery('guzide').outcome,'not_found');assert.equal(publicQuery(detail(AUTO).slug,'featured',0,'all','unknown.saas-staging.celebix.site').outcome,'not_found');});
 check('public title price and discount filters use existing price projections',()=>{assert.deepEqual(publicQuery(detail(AUTO).slug,'price-desc').result.items.map(p=>p.id),[D,A]);assert.deepEqual(publicQuery(detail(AUTO).slug,'featured',0,'discounted').result.items.map(p=>p.id),[A]);});
 check('name-derived URL handles collision and retains URL after rename',()=>{const id='57000000-0000-4000-8000-000000000010';assert.equal(save(id,null,config,[],detail(AUTO).name).outcome,'saved');const original=detail(id).slug;assert.equal(original,detail(AUTO).slug+'-2');assert.equal(save(id,1,config,[],'Baska').outcome,'saved');assert.equal(detail(id).slug,original);});
 check('durable replay mismatch and version authority are preserved',()=>{const args=saveArgs(AUTO,2,{...auto,rules:[catRule]},[C,B]);assert.equal(api(box,'catalog_admin_save_resource',args).outcome,'saved');assert.equal(api(box,'catalog_admin_save_resource',args).outcome,'operation_replayed');assert.equal(api(box,'catalog_admin_save_resource',args.replace('a'.repeat(64),'b'.repeat(64))).outcome,'operation_mismatch');assert.equal(save(AUTO,2,{...auto,rules:[catRule]},[C,B]).outcome,'version_conflict');assert.equal(api(box,'catalog_admin_save_resource',saveArgs(AUTO,3,{...auto,rules:[catRule]},[C,B]),{principal:ANALYST,membership:MA}).outcome,'membership_denied');});
 check('V4/direct Apply supports typed collection roots footer and banners without changing previous draft',()=>{psql(box,readFileSync(path.join(ROOT,'tests/saas-phase3/catalog-collections/design-navigation-scenarios.sql'),'utf8'));});
 artifact('dto-fixtures.json',{summary:api(box,'catalog_admin_list_collections',encoded({page:1,pageSize:10,state:'all',sort:'title'})).result,detail:detail(MANUAL),members:members(MANUAL,null,{page:1,pageSize:2,mode:'members'}).result,automaticMembers:members(AUTO,null).result,public:publicQuery(detail(AUTO).slug).result});
 check('archive and restore are versioned replayable and restore as draft',()=>{const archived=api(box,'catalog_admin_archive_resource',`'${op()}','${'c'.repeat(64)}','${AUTO}',3`);assert.equal(archived.outcome,'archived');assert.equal(publicQuery(detail(AUTO).slug).outcome,'not_found');const args=`'${op()}','${'d'.repeat(64)}','${AUTO}',4`;assert.equal(api(box,'catalog_admin_restore_collection',args).outcome,'restored');assert.equal(api(box,'catalog_admin_restore_collection',args).outcome,'operation_replayed');assert.equal(detail(AUTO).config.published,false);assert.deepEqual(detail(AUTO).productIds,[C,B]);assert.equal(api(box,'catalog_admin_restore_collection',`'${op()}','${'d'.repeat(64)}','${AUTO}',5`).outcome,'invalid_transition');});
 check('same-store and role authority protect all new reads and restores',()=>{assert.equal(api(box,'catalog_admin_get_collection',`'${AUTO}'`,{store:STORE_B,membership:MB}).outcome,'resource_not_found');assert.equal(api(box,'catalog_admin_list_collections',encoded({page:1,pageSize:2,state:'all',sort:'title'}),{principal:ANALYST,membership:MA}).outcome,'listed');assert.equal(api(box,'catalog_admin_restore_collection',`'${op()}','${'e'.repeat(64)}','${AUTO}',5`,{principal:EDITOR,membership:ME}).outcome,'membership_denied');});
 check('individual product options exclude automatic collections',()=>{const result=JSON.parse(psql(box,`SET ROLE celebix_saas_app;SELECT jsonb_build_object('outcome',outcome,'result',result_payload) FROM saas.catalog_get_onboarding_options('${STORE}','${OWNER}','${MO}','${PLAN}','free_starter',1,100,'${NOW}');`).stdout.trim());assert.equal(result.outcome,'found');assert.equal(result.result.resources.some(r=>r.id===AUTO),false);assert.equal(result.result.resources.some(r=>r.id===MANUAL),true);});
 check('rollback refuses feature-written data without touching rows',()=>{const before=detail(MANUAL);const result=psql(box,readFileSync(path.join(SQL,'202609300182_catalog_collections.down.sql'),'utf8'),DB,{allowFailure:true});assert.notEqual(result.status,0);assert.match(result.stderr,/COLLECTION_ROLLBACK_REQUIRES_FEATURE_DATA_RECOVERY/);assert.deepEqual(detail(MANUAL),before);});

 check('typed query and config nulls cannot bypass durable validation',()=>{for(const cfg of [null,{...config,mode:null},{...config,sort:null},{...config,match:null}])assert.equal(psql(box,`SET ROLE celebix_saas_owner;SELECT saas.catalog_collection_config_valid('${STORE}',${cfg===null?'NULL':encoded(cfg)});`).stdout.trim(),'f');assert.equal(api(box,'catalog_admin_list_collections',`NULL`).outcome,'invalid_input');assert.equal(api(box,'catalog_admin_list_collections',encoded({page:'1',pageSize:2,state:'all',sort:'title'})).outcome,'invalid_input');});
 check('a referenced cover cannot be archived',()=>{const result=JSON.parse(psql(box,`SET ROLE celebix_saas_app;SELECT jsonb_build_object('outcome',outcome,'result',result_payload) FROM saas.storefront_asset_archive('${STORE}','${OWNER}','${MO}','${PLAN}','free_starter',1,${storage},'${NOW}','${op()}','${'a'.repeat(64)}','${COVER}',1);`).stdout.trim());assert.equal(result.outcome,'version_conflict');});
 const capacityIds=Array.from({length:10001},(_,i)=>`46000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`),BIGMANUAL='57000000-0000-4000-8000-000000000011',BIGAUTO='57000000-0000-4000-8000-000000000012';
 psql(box,`BEGIN;SET LOCAL ROLE celebix_saas_owner;ALTER TABLE saas.products DISABLE TRIGGER seo_resource_notification;INSERT INTO saas.products(id,store_id,slug,title,status,currency,created_at,updated_at) SELECT ('46000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'${STORE}','capacity-product-'||lpad(n::text,5,'0'),'Capacity '||lpad(n::text,5,'0'),'active','TRY','2026-01-02','2026-01-02' FROM generate_series(1,10001) n;ALTER TABLE saas.products ENABLE TRIGGER seo_resource_notification;COMMIT;`);
 check('ten thousand manual products save atomically and10001 remain denied',()=>{assert.equal(save(BIGMANUAL,null,config,capacityIds.slice(0,10000),'Buyuk').outcome,'saved');assert.equal(save(BIGMANUAL,1,config,capacityIds,'Buyuk').outcome,'invalid_input');assert.equal(psql(box,`SET ROLE celebix_saas_owner;SELECT count(*) FROM saas.catalog_admin_resource_products WHERE resource_id='${BIGMANUAL}';`).stdout.trim(),'10000');});
 check('automatic ordering supports more than10000 pins without changing membership',()=>{assert.equal(save(BIGAUTO,null,{...auto,rules:[catRule]},capacityIds,'Buyuk otomatik').outcome,'saved');assert.equal(psql(box,`SET ROLE celebix_saas_owner;SELECT max(position) FROM saas.catalog_admin_resource_products WHERE resource_id='${BIGAUTO}';`).stdout.trim(),'10000');assert.equal(psql(box,`SET ROLE celebix_saas_owner;SELECT saas.catalog_collection_matches_product('${STORE}','${BIGAUTO}','${capacityIds[0]}');`).stdout.trim(),'f');});
 check('nonautomatic resources retain their original ten thousand position bound',()=>{const result=psql(box,`SET ROLE celebix_saas_owner;INSERT INTO saas.catalog_admin_resource_products(store_id,resource_id,product_id,position) VALUES('${STORE}','${BIGMANUAL}','${capacityIds[10000]}',10000);`,DB,{allowFailure:true});assert.notEqual(result.status,0);assert.match(result.stderr,/CATALOG_RESOURCE_POSITION_LIMIT_EXCEEDED/);});
 check('catalog plan feature and membership status guard new paginated reads',()=>{const query=encoded({page:1,pageSize:2,state:'all',sort:'title'});const rows=psql(box,`BEGIN;SET LOCAL ROLE celebix_saas_owner;UPDATE saas.memberships SET status='revoked',updated_at='${NOW}' WHERE id='${MO}';SET LOCAL ROLE celebix_saas_app;SELECT outcome FROM saas.catalog_admin_list_collections(${authority()},${query});ROLLBACK;`).stdout.trim();assert.equal(rows,'membership_denied');const feature=psql(box,`BEGIN;SET LOCAL ROLE celebix_saas_owner;ALTER TABLE saas.plan_features DISABLE TRIGGER plan_features_immutable;UPDATE saas.plan_features SET enabled=false WHERE plan_id='${PLAN}' AND feature_key='catalog';SET LOCAL ROLE celebix_saas_app;SELECT outcome FROM saas.catalog_admin_list_collections(${authority()},${query});ROLLBACK;`).stdout.trim();assert.equal(feature,'feature_not_enabled');});
 const cartIds=capacityIds.slice(0,20);
 psql(box,`BEGIN;SET LOCAL ROLE celebix_saas_owner;ALTER TABLE saas.product_variants DISABLE TRIGGER seo_resource_notification;ALTER TABLE saas.product_variants DISABLE TRIGGER product_variants_inventory_reconcile;INSERT INTO saas.product_variants(id,store_id,product_id,title,sku,price_cents,stock_tracking,stock_quantity,status,created_at,updated_at) SELECT id,'${STORE}',id,'Cart product','CART-'||ordinality,300,false,0,'active','2026-01-01','2026-01-01' FROM unnest(${array(cartIds)}) WITH ORDINALITY x(id,ordinality);ALTER TABLE saas.product_variants ENABLE TRIGGER seo_resource_notification;ALTER TABLE saas.product_variants ENABLE TRIGGER product_variants_inventory_reconcile;INSERT INTO saas.catalog_product_categories(store_id,product_id,category_id,position) SELECT '${STORE}',id,'${CHILD}',0 FROM unnest(${array(cartIds)}) id;COMMIT;`);
 check('paginated ten thousand manual member reads enrich only the visible fifty products',()=>{const started=performance.now();const result=members(BIGMANUAL,null,{page:1,pageSize:50,mode:'members'}).result;const elapsed=performance.now()-started;assert.equal(result.items.length,50);assert.equal(result.orderedIds.length,10000);console.log(JSON.stringify({benchmark:'manual_10000_members_page50',elapsedMs:elapsed}));assert.ok(elapsed<2000);});
 check('twenty checkout lines materialize shared automatic membership within measured budget',()=>{const context={salesChannel:'storefront',cartLines:Array.from({length:20},(_,i)=>({lineId:`47000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`,position:i,productId:cartIds[i],variantId:cartIds[i],quantity:1,unitPriceMinor:300,unitCostMinor:null,currency:'TRY',categoryIds:[],brandId:null,collectionIds:[]}))};const timings=JSON.parse(psql(box,`SET ROLE celebix_saas_owner;CREATE TEMP TABLE collection_timings(n integer,elapsed double precision);DO $bench$ DECLARE n integer;started timestamptz;BEGIN FOR n IN 1..11 LOOP started:=clock_timestamp();PERFORM saas.promotion_evaluator_materialize_lines('${STORE}','TRY',${encoded(context)},'${NOW}');INSERT INTO collection_timings VALUES(n,extract(epoch FROM clock_timestamp()-started)*1000);END LOOP;END $bench$;SELECT jsonb_agg(elapsed ORDER BY n) FROM collection_timings;`).stdout.trim());const cold=timings[0],warm=[...timings.slice(1)].sort((a,b)=>a-b),p95=warm[Math.ceil(warm.length*.95)-1];console.log(JSON.stringify({benchmark:'collection_membership_20_lines_11189_products',coldMs:cold,warmP95Ms:p95}));assert.ok(cold<=250,`Cold membership materialization exceeded250ms:${cold}`);assert.ok(p95<=100,`Warm membership materialization exceeded100ms:${p95}`);});

 artifact('receipt.json',{passed,migrations:[182,183],baseline:'b910b1c854f79d3942ce1af975b9ee62411c608d'});console.log(`${passed}/${passed} PASS`);
}finally{stop(box);}}
main().catch(error=>{console.error(error);process.exitCode=1;});
