import type { PublicImageMediaType } from "../../../../packages/saas-contracts/src/storefront/index.ts";
const MAX_BYTES = 5_242_880;
const EXTENSIONS: Readonly<Record<PublicImageMediaType, string>> = Object.freeze({ "image/jpeg": "jpg", "image/png": "png", "image/webp": "webp" });
function invalid(): never { throw new Error("product_media_image_invalid"); }
function dimensionsPng(bytes: Uint8Array): [number, number] | null { if (bytes.length < 24 || !Buffer.from(bytes.subarray(0, 8)).equals(Buffer.from("89504e470d0a1a0a", "hex")) || Buffer.from(bytes.subarray(12, 16)).toString("ascii") !== "IHDR") return null; const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength); return [view.getUint32(16), view.getUint32(20)]; }
function dimensionsJpeg(bytes: Uint8Array): [number, number] | null { if (bytes.length < 4 || bytes[0] !== 0xff || bytes[1] !== 0xd8) return null; let offset = 2; while (offset + 9 < bytes.length) { if (bytes[offset] !== 0xff) return null; const marker = bytes[offset + 1]!; if (marker === 0xd9 || marker === 0xda) break; const length = (bytes[offset + 2]! << 8) | bytes[offset + 3]!; if (length < 2 || offset + 2 + length > bytes.length) return null; if ([0xc0, 0xc1, 0xc2].includes(marker)) return [(bytes[offset + 7]! << 8) | bytes[offset + 8]!, (bytes[offset + 5]! << 8) | bytes[offset + 6]!]; offset += 2 + length; } return null; }
function dimensionsWebp(bytes: Uint8Array): [number, number] | null { if (bytes.length < 30 || Buffer.from(bytes.subarray(0, 4)).toString("ascii") !== "RIFF" || Buffer.from(bytes.subarray(8, 12)).toString("ascii") !== "WEBP") return null; const chunk = Buffer.from(bytes.subarray(12, 16)).toString("ascii"); if (chunk === "VP8X") return [1 + bytes[24]! + (bytes[25]! << 8) + (bytes[26]! << 16), 1 + bytes[27]! + (bytes[28]! << 8) + (bytes[29]! << 16)]; if (chunk === "VP8 " && bytes.length >= 30 && bytes[23] === 0x9d && bytes[24] === 0x01 && bytes[25] === 0x2a) return [((bytes[27]! << 8) | bytes[26]!) & 0x3fff, ((bytes[29]! << 8) | bytes[28]!) & 0x3fff]; return null; }
export function validateProductImage(input: Readonly<{ bytes: Uint8Array; mediaType: string; fileName: string }>): Readonly<{ mediaType: PublicImageMediaType; extension: string; width: number; height: number; byteSize: number }> {
  if (!input || !(input.bytes instanceof Uint8Array) || input.bytes.byteLength < 24 || input.bytes.byteLength > MAX_BYTES || !Object.hasOwn(EXTENSIONS, input.mediaType) || typeof input.fileName !== "string") invalid();
  const mediaType = input.mediaType as PublicImageMediaType, extension = EXTENSIONS[mediaType]; const normalizedExtension = input.fileName.toLowerCase().split(".").at(-1); if (normalizedExtension !== extension && !(mediaType === "image/jpeg" && normalizedExtension === "jpeg")) invalid();
  const dimensions = mediaType === "image/png" ? dimensionsPng(input.bytes) : mediaType === "image/jpeg" ? dimensionsJpeg(input.bytes) : dimensionsWebp(input.bytes); if (!dimensions || dimensions[0] < 1 || dimensions[1] < 1 || dimensions[0] > 8192 || dimensions[1] > 8192) invalid();
  return Object.freeze({ mediaType, extension, width: dimensions[0], height: dimensions[1], byteSize: input.bytes.byteLength });
}
