'use client';
import{useState}from'react';
import{parseContentResearchResult,type ContentResearchResult,type ContentResearchSafeSource,type ContentResourceTarget}from'@celebix/saas-contracts';
type Props=Readonly<{target:ContentResourceTarget;onCompleted(operationId:string|null,sources?:readonly ContentResearchSafeSource[]):void}>;
/** Fetches only merchant-entered HTTPS URLs through the server's bounded private research API. */
export function ContentResearchPanel({target,onCompleted}:Props){
 const[urls,setUrls]=useState(''),[operationId,setOperationId]=useState<string|null>(null),[current,setCurrent]=useState<ContentResearchResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function read(response:Response){let body:unknown;try{body=await response.json();}catch{throw Error();}if(!response.ok)throw Error();return parseContentResearchResult(body);}
 async function submit(){if(busy)return;setBusy(true);setError('');onCompleted(null);setCurrent(null);try{const selected=urls.split(/\r?\n/).map(url=>url.trim()).filter(Boolean);if(selected.length<1||selected.length>3||selected.some(url=>{try{return new URL(url).protocol!=='https:';}catch{return true;}}))throw Error();const id=crypto.randomUUID();setOperationId(id);const response=await fetch('/api/content-research',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json','idempotency-key':id},body:JSON.stringify({target,urls:selected})});const value=await read(response);setCurrent(value);if(value.status==='completed')onCompleted(value.operationId,value.sources);}catch{setError('Kaynak araştırması tamamlanamadı. URL’leri kontrol edin; mevcut taslağınız korunuyor.');}finally{setBusy(false);}}
 async function refresh(){if(!operationId||busy)return;setBusy(true);setError('');try{const value=await read(await fetch(`/api/content-research/${encodeURIComponent(operationId)}`,{credentials:'same-origin'}));setCurrent(value);if(value.status==='completed')onCompleted(value.operationId,value.sources);}catch{setError('Araştırma durumu alınamadı.');}finally{setBusy(false);}}
 return <section aria-label="İsteğe bağlı kaynak araştırması" style={{border:'1px solid #ddd',borderRadius:8,padding:12}}><h3>Kaynak araştırması (isteğe bağlı)</h3><p>En fazla üç HTTPS adresini siz seçin. Sayfa içeriği özel araştırma kaydına alınır; metne otomatik yayınlanmaz.</p><label>Kaynak adresleri, her satıra bir URL<textarea aria-label="Kaynak adresleri" value={urls} onChange={event=>{setUrls(event.currentTarget.value);setCurrent(null);setOperationId(null);onCompleted(null);}} placeholder={'https://...\nhttps://...'}/></label><div style={{display:'flex',gap:8}}><button type="button" disabled={busy} onClick={()=>void submit()}>{busy?'Araştırılıyor…':'Kaynakları getir'}</button>{current?.status==='pending'||current?.status==='unknown'?<button type="button" disabled={busy} onClick={()=>void refresh()}>Durumu yenile</button>:null}</div>{current?<div role="status"><p>Durum: {current.status==='completed'?'Tamamlandı':current.status==='pending'?'Sürüyor':current.status==='unknown'?'Belirsiz':'Başarısız'}. {current.usage?`${current.usage.sourcesAttempted} adres, ${current.usage.fetchedBytes} alınan bayt, ${current.usage.extractedBytes} çıkarılan metin baytı, ${current.usage.elapsedMs} ms.`:'Ölçüm bilinmiyor.'}</p>{current.sources.length?<ul>{current.sources.map(source=><li key={source.id}>{source.title} — {source.originalUrl!==source.finalUrl?`${source.originalUrl} → `:''}{source.finalUrl} — <time dateTime={source.fetchedAt}>{source.fetchedAt}</time></li>)}</ul>:null}</div>:null}{error?<p role="alert">{error}</p>:null}</section>;
}
