'use client';
import{useEffect,useId,useRef,useState}from'react';
import type{ContentOutline,ContentResearchSafeSource,ContentResourceAuthoringRequest,ContentResourceGenerationView,ContentResourceTarget,MerchantContentField,MerchantContentValues}from'@celebix/saas-contracts';
import{contentResourceAuthoringClient,ContentResourceAuthoringApiError}from'@/lib/content-resource-authoring-ui/client';
import{captureContentResourceApplyContext}from'@/lib/content-resource-authoring-ui/controller';
import{clearContentResourceRecovery,readContentResourceRecovery,writeContentResourceRecovery,type ContentResourceRecoveryScope,type ContentResourceRecoveryReceipt}from'@/lib/content-resource-authoring-ui/recovery';
import{ContentResearchPanel}from'./ContentResearchPanel';

type DraftAction='article'|'improve'|'shorten'|'rewrite_selection'|'seo';
export type ContentResourceApplyInput=Readonly<{context:string;currentRequest:ContentResourceAuthoringRequest;generation:ContentResourceGenerationView;selectedFields:readonly MerchantContentField[]}>;
type Props=Readonly<{storeId:string;recoveryLocale?:string|null;target:ContentResourceTarget;values:MerchantContentValues;selectionText:string|null;researchEnabled:boolean;onOperationLockChange?(locked:boolean):void;onApply(input:ContentResourceApplyInput):void}>;
type Pending=Readonly<{id:string;stage:'outline'|'draft';context:string|null;scope:ContentResourceRecoveryScope;status:'unresolved'|'failed'|'unknown';safeCode:string|null}>;
const OPTIONS:readonly Readonly<{field:MerchantContentField;label:string}>[]=[{field:'body',label:'Metin'},{field:'name',label:'Başlık'},{field:'excerpt',label:'Özet'},{field:'seoTitle',label:'SEO başlığı'},{field:'seoDescription',label:'SEO açıklaması'}];
const message=(error:unknown)=>error instanceof ContentResourceAuthoringApiError?`İşlem tamamlanamadı (${error.code}). Taslağınız korunuyor.`:'İşlem tamamlanamadı. Taslağınız korunuyor.';
const identityHint='Başlamadan önce içerik adı, küçük harfli URL anahtarı ve geçerli dili girin.';
export function ContentResourceAuthoringPanel({storeId,recoveryLocale,target,values,selectionText,researchEnabled,onOperationLockChange,onApply}:Props){
 const hintId=useId();
 const[initial]=useState(()=>{try{return{receipt:readContentResourceRecovery(window.sessionStorage,{storeId,target,locale:recoveryLocale??values.locale}),error:''};}catch{return{receipt:null,error:'İşlem kurtarma kaydı okunamadı. Yeni üretim başlatılamaz.'};}});
 const[open,setOpen]=useState(Boolean(initial.receipt)),[busy,setBusy]=useState(false),[error,setError]=useState(initial.error),[topic,setTopic]=useState(''),[purpose,setPurpose]=useState(''),[tone,setTone]=useState<'neutral'|'friendly'|'professional'>('neutral'),[length,setLength]=useState<'short'|'medium'|'long'>('medium'),[note,setNote]=useState(''),[brandVoice,setBrandVoice]=useState(''),[action,setAction]=useState<DraftAction>('article'),[fields,setFields]=useState<readonly MerchantContentField[]>(['body']),[outline,setOutline]=useState<ContentOutline|null>(null),[outlineGenerationId,setOutlineGenerationId]=useState<string|null>(null),[researchOperationId,setResearchOperationId]=useState<string|null>(null),[researchSources,setResearchSources]=useState<readonly ContentResearchSafeSource[]>([]),[generation,setGeneration]=useState<ContentResourceGenerationView|null>(null),[context,setContext]=useState(''),[selected,setSelected]=useState<readonly MerchantContentField[]>([]),[pending,setPending]=useState<Pending|null>(initial.receipt?{id:initial.receipt.operationId,stage:initial.receipt.stage,context:null,scope:{storeId:initial.receipt.storeId,target:initial.receipt.target,locale:initial.receipt.locale},status:initial.receipt.status,safeCode:initial.receipt.safeCode}:null),[recovered,setRecovered]=useState(false);
 const locked=useRef(Boolean(initial.receipt));
 useEffect(()=>{onOperationLockChange?.(Boolean(initial.receipt&&initial.receipt.status!=='failed'));},[onOperationLockChange,initial]);
 const identityReady=Boolean(values.name.trim())&&new TextEncoder().encode(values.name).length<=160&&values.slug.length<=100&&/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(values.slug)&&/^[a-z]{2,3}(?:-[A-Z]{2})?$/.test(values.locale);
 const common=()=>({target,currentDraft:values,locale:values.locale,tone,length,note,brandVoice:brandVoice||null,researchOperationId});
 const outlineRequest=():ContentResourceAuthoringRequest=>({...common(),stage:'outline',topic:topic.trim(),purpose:purpose.trim()});
 const draftRequest=():ContentResourceAuthoringRequest=>({...common(),stage:'draft',action,fields:action==='rewrite_selection'?fields.filter(field=>field==='body'):action==='seo'?fields.filter(field=>field==='seoTitle'||field==='seoDescription'):fields,reviewedOutline:action==='article'?outline:null,outlineGenerationId:action==='article'?outlineGenerationId:null,selection:action==='rewrite_selection'&&selectionText?{field:'body',text:selectionText}:null});
 const latestRequest=useRef<{outline:()=>ContentResourceAuthoringRequest;draft:()=>ContentResourceAuthoringRequest}|null>(null);
 latestRequest.current={outline:outlineRequest,draft:draftRequest};
 function receipt(operation:Pending):ContentResourceRecoveryReceipt{return{...operation.scope,operationId:operation.id,stage:operation.stage,status:operation.status,safeCode:operation.safeCode};}
 function receive(result:ContentResourceGenerationView,operation:Pending){
  if(result.id!==operation.id||result.stage!==operation.stage||JSON.stringify(result.target)!==JSON.stringify(operation.scope.target)){setError('İşlem yanıtı beklenen taslakla eşleşmedi. Yeni üretim başlatılamaz.');return;}
  if(result.status==='pending'){setError('İşlem sürüyor. Durumu yenileyebilirsiniz.');return;}
  if(result.status==='unknown'||result.status==='failed'){
   const next={...operation,status:result.status,safeCode:result.safeCode};
   try{writeContentResourceRecovery(window.sessionStorage,receipt(next));setPending(next);onOperationLockChange?.(result.status==='unknown');}catch{setError('İşlem durumu güvenle saklanamadı. Yeni üretim başlatılamaz.');return;}
   setError(result.status==='unknown'?'İşlem sonucu belirsiz. Yalnız durumunu yenileyin; yeni üretim başlatmayın.':`Üretim tamamlanamadı (${result.safeCode??result.status}). Taslağınız korunuyor.`);return;
  }
  try{clearContentResourceRecovery(window.sessionStorage,operation.scope);}catch{setError('Tamamlanan işlem kaydı temizlenemedi. Yeni üretim başlatılamaz.');return;}
  setPending(null);locked.current=false;onOperationLockChange?.(false);
  if(operation.context===null){setRecovered(true);if(operation.stage==='outline'&&result.outline)setOutline(result.outline);else if(operation.stage==='draft'&&result.draft){setGeneration(result);setSelected([]);}setError('Önceki işlem getirildi. Yerel taslak kaybolduğu için sonuç yalnız incelenebilir.');return;}
  try{const current=operation.stage==='outline'?latestRequest.current!.outline():latestRequest.current!.draft();if(captureContentResourceApplyContext(current)!==operation.context)throw Error('stale');}
  catch{setError('Form üretim sırasında değişti. Yeni bir önizleme oluşturun.');return;}
  if(operation.stage==='outline'&&result.outline){setOutline(result.outline);setOutlineGenerationId(result.id);setAction('article');setError('');}
  else if(operation.stage==='draft'&&result.draft){setGeneration(result);setContext(operation.context);setSelected(Object.keys(result.draft.values)as MerchantContentField[]);setError('');}
  else setError('Üretim yanıtı kullanılamıyor. Taslağınız korunuyor.');
 }
 async function generate(stage:'outline'|'draft'){
  if(busy||pending||locked.current||initial.error)return;
  if(!identityReady){setError(identityHint);return;}
  let request:ContentResourceAuthoringRequest,captured:string;
  try{request=stage==='outline'?outlineRequest():draftRequest();captured=captureContentResourceApplyContext(request);}catch(caught){setError(message(caught));return;}
  const operation:Pending={id:crypto.randomUUID(),stage,context:captured,scope:{storeId,target,locale:values.locale},status:'unresolved',safeCode:null};
  try{writeContentResourceRecovery(window.sessionStorage,receipt(operation));}catch{locked.current=true;onOperationLockChange?.(true);setError('İşlem kimliği güvenle saklanamadı. Yeni üretim başlatılamaz.');return;}
  locked.current=true;onOperationLockChange?.(true);setPending(operation);setBusy(true);setError('');setGeneration(null);setRecovered(false);
  try{receive(await contentResourceAuthoringClient.generate(request,operation.id),operation);}
  catch(caught){setError(`${message(caught)} İşlem kimliğiyle yalnız durumunu yenileyin.`);}finally{setBusy(false);}
 }
 async function refresh(){if(!pending||busy)return;setBusy(true);try{receive(await contentResourceAuthoringClient.get(pending.id),pending);}catch(caught){setError(`${message(caught)} İşlem kimliğiyle yeniden durum sorgulayın; yeni üretim başlatmayın.`);}finally{setBusy(false);}}
 function prepareNewAttempt(){if(!pending||pending.status!=='failed')return;try{clearContentResourceRecovery(window.sessionStorage,pending.scope);setPending(null);locked.current=false;onOperationLockChange?.(false);setError('Önceki başarısız işlem kaydedildi. Yeni bir işlem başlatabilirsiniz.');}catch{setError('İşlem kaydı temizlenemedi. Yeni üretim başlatılamaz.');}}
 function changeOutlineSection(index:number,heading:string){setOutline(previous=>previous?{...previous,sections:previous.sections.map((section,i)=>i===index?{...section,heading}:section)}:previous);}
 function apply(){if(!generation?.draft)return;try{const currentRequest=draftRequest();if(captureContentResourceApplyContext(currentRequest)!==context)throw Error('stale');onApply({context,currentRequest,generation,selectedFields:selected});setGeneration(null);setError('');}catch{setError('Form veya seçenekler üretimden sonra değişti. Yeni bir önizleme oluşturun.');}}
 return <section aria-label="Yapay zekâ ile içerik yazma" style={{border:'1px solid #dedbd7',borderRadius:12,padding:16,marginBlock:16}}>
  <button type="button" onClick={()=>setOpen(value=>!value)} aria-expanded={open}>{open?'Yapay zekâ yardımını kapat':'Yapay zekâ ile yaz'}</button>
  {open?<div style={{display:'grid',gap:12,marginTop:14}}>
   <p>Önce planı inceleyin; sonra metin oluşturup istediğiniz alanları seçerek taslağa uygulayın. Yayın ve kayıt için sayfanın Kaydet düğmesini kullanın.</p>
   {!identityReady?<p id={hintId} role="status">{identityHint}</p>:null}
   <label>Konu<input aria-label="Yazı konusu" value={topic} maxLength={500} onChange={event=>setTopic(event.currentTarget.value)}/></label>
   <label>Amaç<input aria-label="Yazı amacı" value={purpose} maxLength={1000} onChange={event=>setPurpose(event.currentTarget.value)}/></label>
   <div style={{display:'flex',gap:10,flexWrap:'wrap'}}><label>Üslup<select aria-label="Yazı üslubu" value={tone} onChange={event=>setTone(event.currentTarget.value as typeof tone)}><option value="neutral">Nötr</option><option value="friendly">Samimi</option><option value="professional">Profesyonel</option></select></label><label>Uzunluk<select aria-label="Yazı uzunluğu" value={length} onChange={event=>setLength(event.currentTarget.value as typeof length)}><option value="short">Kısa</option><option value="medium">Orta</option><option value="long">Uzun</option></select></label></div>
   <label>Marka yazım tonu (isteğe bağlı)<input aria-label="Marka yazım tonu" value={brandVoice} maxLength={160} onChange={event=>setBrandVoice(event.currentTarget.value)}/></label>
   <label>Ek not (isteğe bağlı)<textarea aria-label="Yazı notu" value={note} maxLength={2000} onChange={event=>setNote(event.currentTarget.value)}/></label>
   {researchEnabled?<ContentResearchPanel target={target} onCompleted={(id,sources)=>{setResearchOperationId(id);setResearchSources(sources??[]);}}/>:null}
   <div><button type="button" aria-describedby={!identityReady?hintId:undefined} disabled={busy||!!pending||locked.current||!!initial.error||!identityReady||!topic.trim()||!purpose.trim()} onClick={()=>void generate('outline')}>{busy?'Hazırlanıyor…':'1. Yazı planı oluştur'}</button>{pending?<button type="button" disabled={busy} onClick={()=>void refresh()}>Üretim durumunu yenile</button>:null}</div>
   {pending?<p role="status">İşlem kimliği: <code>{pending.id}</code> · {pending.status==='failed'?'Başarısız':pending.status==='unknown'?'Sonuç belirsiz':'Sonuç bekleniyor'}{pending.safeCode?` (${pending.safeCode})`:''}</p>:null}
   {pending?.status==='failed'?<button type="button" disabled={busy} onClick={prepareNewAttempt}>Yeni denemeye hazırlan</button>:null}
   {outline?<section aria-label="İncelenecek yazı planı" style={{border:'1px solid #ddd',borderRadius:8,padding:12}}><h3>Yazı planı</h3><p>Başlıkları ve maddeleri inceleyip düzenleyin.</p><label>Plan başlığı<input aria-label="Plan başlığı" value={outline.title} onChange={event=>setOutline({...outline,title:event.currentTarget.value})}/></label>{outline.sections.map((section,index)=><div key={index}><label>Bölüm {index+1}<input aria-label={`Bölüm ${index+1}`} value={section.heading} onChange={event=>changeOutlineSection(index,event.currentTarget.value)}/></label><label>Bölüm maddeleri<textarea aria-label={`Bölüm ${index+1} maddeleri`} value={section.points.join('\n')} onChange={event=>{const points=event.currentTarget.value.split('\n').filter(Boolean);setOutline(previous=>previous?{...previous,sections:previous.sections.map((item,i)=>i===index?{...item,points}:item)}:previous);}}/></label></div>)}</section>:null}
   <label>İşlem<select aria-label="Yazı işlemi" value={action} onChange={event=>setAction(event.currentTarget.value as DraftAction)}><option value="article">Plandan yazı oluştur</option><option value="improve">Mevcut metni geliştir</option><option value="shorten">Kısalt</option><option value="rewrite_selection">Seçili metni yeniden yaz</option><option value="seo">SEO alanları oluştur</option></select></label>
   <fieldset><legend>Üretilecek alanlar</legend>{OPTIONS.filter(option=>action==='seo'?option.field==='seoTitle'||option.field==='seoDescription':action==='rewrite_selection'?option.field==='body':true).map(option=><label key={option.field} style={{display:'inline-flex',alignItems:'center',gap:4,marginRight:12}}><input type="checkbox" checked={fields.includes(option.field)} onChange={event=>{const checked=event.currentTarget.checked;setFields(current=>checked?[...current,option.field]:current.filter(field=>field!==option.field));}}/>{option.label}</label>)}</fieldset>
   <button type="button" aria-describedby={!identityReady?hintId:undefined} disabled={busy||!!pending||locked.current||!!initial.error||!identityReady||(action==='article'&&!outlineGenerationId)||(action==='rewrite_selection'&&(!selectionText||!fields.includes('body')))||(action==='seo'&&!fields.some(field=>field==='seoTitle'||field==='seoDescription'))||!fields.length} onClick={()=>void generate('draft')}>{busy?'Hazırlanıyor…':'2. Önizleme oluştur'}</button>
   {generation?.draft?<section aria-label="Yapay zekâ içerik önizlemesi" style={{border:'1px solid #ddd',borderRadius:8,padding:12}}><h3>Önizleme</h3>{recovered?<p>Bu sonuç yalnız incelenebilir; önceki yerel taslağa uygulanamaz.</p>:null}{OPTIONS.filter(option=>Object.hasOwn(generation.draft!.values,option.field)).map(option=><div key={option.field}><label><input type="checkbox" checked={selected.includes(option.field)} disabled={recovered} onChange={event=>{const checked=event.currentTarget.checked;setSelected(current=>checked?[...current,option.field]:current.filter(field=>field!==option.field));}}/>{option.label} alanını uygula</label>{option.field==='body'?<div style={{overflowWrap:'anywhere'}} dangerouslySetInnerHTML={{__html:generation.draft!.values.body??''}}/>:<p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{generation.draft!.values[option.field]}</p>}</div>)}{generation.draft.citations.length?<details><summary>Kaynak alıntıları</summary><ul>{generation.draft.citations.map((citation,index)=>{const source=researchSources.find(item=>item.id===citation.sourceId);return <li key={`${citation.sourceId}-${index}`}>{source?`${source.title} — ${source.finalUrl}: `:''}{citation.quote}</li>;})}</ul></details>:null}{generation.draft.suggestions.length?<details><summary>İnceleme notları</summary><ul>{generation.draft.suggestions.map((suggestion,index)=><li key={index}>{suggestion}</li>)}</ul></details>:null}<p>{generation.usage?`${generation.usage.inputTokens} giriş + ${generation.usage.outputTokens} çıkış token`: 'Sağlayıcı kullanım bilgisi göndermedi.'}</p><button type="button" disabled={!selected.length||recovered} onClick={apply}>Seçilenleri taslağa uygula</button></section>:null}
   {error?<p role="alert">{error}</p>:null}
  </div>:null}
 </section>;
}
