import assert from 'node:assert/strict';
import test from 'node:test';
import { createSeoHttpHandlers } from './handler.ts';

const ORIGIN='https://panel.saas-staging.celebix.site', ID='11111111-1111-4111-8111-111111111111', OP='22222222-2222-4222-8222-222222222222', REQUEST='33333333-3333-4333-8333-333333333333';
const NOW=new Date('2026-09-30T12:00:00Z');
const COOKIE=`v1.panel.current.${Buffer.alloc(32,1).toString('base64url')}`;
const tenant=(role='store_owner')=>({schemaVersion:1,requestId:REQUEST,principal:{id:ID,issuer:'https://id.test/oidc',subject:'x'},store:{id:ID,slug:'store',status:'active'},membership:{id:ID,role,status:'active'},entitlements:{schemaVersion:1,planId:ID,planCode:'growth',version:2,status:'active',features:['catalog'],limits:{products:100,staff:5,storageBytes:100},validFrom:'2026-01-01T00:00:00.000Z'},locale:'tr-TR'});
function request(path:string, method='GET', body?:unknown, extra:Record<string,string>={}){return new Request(`http://internal:3400${path}`,{method,headers:{cookie:`__Host-celebix_panel=${COOKIE}`,...(method==='GET'?{}:{origin:ORIGIN,'content-type':'application/json','idempotency-key':OP}),...extra},body:body===undefined?undefined:JSON.stringify(body)});}
function setup(seo:Record<string,unknown>,role='store_owner'){return createSeoHttpHandlers({resolveRuntime:async()=>({seo,access:{readiness:{mode:'approved_staging'},panelOrigin:ORIGIN,resolveCredential:async()=>({kind:'authenticated',tenantContext:tenant(role)})}} as never),now:()=>NOW,requestId:()=>REQUEST});}
const save={expectedVersion:3,expectedSeoVersion:0,title:'Yeni başlık',description:null,canonicalPath:null,indexing:'inherit'};
test('resources read binds tenant and bounded filters; rejects unknown duplicate and privileged input',async()=>{const calls:any[]=[];const h=setup({resources:async(input:unknown)=>{calls.push(input);return {items:[],nextCursor:null,total:0};}});assert.equal((await h.get(request('/api/seo/resources?kind=product&query=yuzuk&missing=1&limit=50'),'resources')).status,200);assert.equal(calls[0].tenantContext.store.id,ID);assert.equal(calls[0].kind,'product');assert.equal(calls[0].missing,true);for(const path of ['/api/seo/resources?storeId='+ID,'/api/seo/resources?kind=product&kind=blog','/api/seo/resources?limit=101'])assert.equal((await h.get(request(path),'resources')).status,400);assert.equal((await h.get(request('/api/seo/resources','GET',undefined,{'x-store-id':ID}),'resources')).status,400);assert.equal(calls.length,1);});
test('save binds exact route/id version and replay key once',async()=>{const calls:any[]=[];const h=setup({saveResource:async(input:unknown)=>{calls.push(input);return {resource:{id:ID},replayed:false};}});const response=await h.saveResource(request(`/api/seo/resources/product/${ID}`,'PATCH',save),'product',ID);assert.equal(response.status,200);assert.equal(calls[0].operationId,OP);assert.equal(calls[0].request.kind,'product');assert.equal(calls[0].request.id,ID);assert.equal(calls[0].request.expectedVersion,3);assert.equal(calls.length,1);});
test('writes reject origin, malformed key, extra tenant input, and viewer before repository',async()=>{let calls=0;const h=setup({saveResource:async()=>{calls++;}});const path=`/api/seo/resources/product/${ID}`;assert.equal((await h.saveResource(request(path,'PATCH',save,{origin:'https://evil.test'}),'product',ID)).status,403);assert.equal((await h.saveResource(request(path,'PATCH',save,{'idempotency-key':'bad'}),'product',ID)).status,400);assert.equal((await h.saveResource(request(path,'PATCH',{...save,storeId:ID}),'product',ID)).status,400);const readOnly=setup({saveResource:async()=>{calls++;}},'analyst');assert.equal((await readOnly.saveResource(request(path,'PATCH',save),'product',ID)).status,403);assert.equal(calls,0);});
test('checks and notifications are explicit authorized writes and queue selected resources',async()=>{const calls:any[]=[];const h=setup({startCheck:async(input:unknown)=>{calls.push(input);return{checked:0,total:5,status:'running',replayed:false};},notify:async(input:unknown)=>{calls.push(input);return{queued:1,replayed:false};}});assert.equal((await h.save(request('/api/seo/checks','POST',{}),'checks')).status,200);assert.equal((await h.save(request('/api/seo/notifications','POST',{resources:[{kind:'product',id:ID}]}),'notifications')).status,200);assert.equal(calls[1].request.resources[0].id,ID);assert.equal(calls.length,2);});
test('unavailable runtime and unauthenticated sessions never read data',async()=>{const h=createSeoHttpHandlers({resolveRuntime:async()=>null,now:()=>NOW,requestId:()=>REQUEST});assert.equal((await h.get(request('/api/seo/overview'),'overview')).status,503);const real=setup({overview:async()=>{throw Error('unexpected')}});const noCookie=new Request('http://internal:3400/api/seo/overview');assert.equal((await real.get(noCookie,'overview')).status,401);});
