import assert from "node:assert/strict";import test from "node:test";import { AnalyticsRepositoryError,PostgresAnalyticsOutboxRepository } from "./index.ts";
const EVENT="90000000-0000-4000-8000-000000000001",WEBSITE="50000000-0000-4000-8000-000000000001",TOKEN="a".repeat(64),NOW=new Date("2026-07-26T12:00:00.000Z");
type Responder=(text:string,values:unknown[])=>Record<string,unknown>[];class Client{calls:Array<{text:string;values:unknown[]}>=[];releases:unknown[]=[];private responder:Responder;constructor(responder:Responder=()=>[]){this.responder=responder}async query(text:string,values:unknown[]=[]){this.calls.push({text,values});const rows=this.responder(text,values);return{rows,rowCount:rows.length,command:"",oid:0,fields:[]}}release(value?:unknown){this.releases.push(value)}}class Pool{private clients:Client[];constructor(clients:Client[]){this.clients=clients}async connect(){const value=this.clients.shift();if(!value)throw Error("checkout");return value}}function repo(pool:Pool){return new PostgresAnalyticsOutboxRepository({pool,role:"celebix_saas_workflow",timeouts:{poolCheckoutMs:100,statementMs:500,lockMs:300,idleTransactionMs:700}})}function claim(){return{eventId:EVENT,leaseToken:TOKEN,websiteId:WEBSITE,hostname:"store.example.test",attemptCount:1,payload:{name:"purchase",valueCents:10000,currency:"TRY",source:"storefront"}}}
test("claim is bounded, uses the worker role, and copies the lease",async()=>{const client=new Client((text)=>text.includes("analytics_outbox_claim")?[{outcome:"claimed",result_payload:[claim()]}]:[]);const result=await repo(new Pool([client])).claim({now:NOW,limit:10,leaseMs:30000});const sql=client.calls.find((entry)=>entry.text.includes("analytics_outbox_claim"));assert.deepEqual(sql?.values,[NOW,10,"30000 milliseconds"]);assert.equal(client.calls.some((entry)=>entry.text==="SET LOCAL ROLE celebix_saas_workflow"),true);assert.notEqual(result[0],claim())});
test("claims and nested purchase payloads are deeply frozen",async()=>{const source=claim();const client=new Client((text)=>text.includes("analytics_outbox_claim")?[{outcome:"claimed",result_payload:[source]}]:[]);const result=await repo(new Pool([client])).claim({now:NOW,limit:1,leaseMs:30000});assert.equal(Object.isFrozen(result),true);assert.equal(Object.isFrozen(result[0]),true);assert.equal(Object.isFrozen(result[0]?.payload),true);source.payload.valueCents=1;assert.equal(result[0]?.payload.name,"purchase");if(result[0]?.payload.name==="purchase")assert.equal(result[0].payload.valueCents,10000)});
test("manual order purchases are accepted as truthful analytics claims",async()=>{const manual={...claim(),payload:{...claim().payload,source:"manual"}};const client=new Client((text)=>text.includes("analytics_outbox_claim")?[{outcome:"claimed",result_payload:[manual]}]:[]);const result=await repo(new Pool([client])).claim({now:NOW,limit:1,leaseMs:30000});assert.equal(result[0]?.payload.name,"purchase");if(result[0]?.payload.name==="purchase")assert.equal(result[0].payload.source,"manual")});
test("delivered uses exact lease fencing",async()=>{const client=new Client((text)=>text.includes("analytics_outbox_mark_delivered")?[{outcome:"delivered",result_payload:{}}]:[]);await repo(new Pool([client])).delivered({eventId:EVENT,leaseToken:TOKEN,now:NOW});const sql=client.calls.find((entry)=>entry.text.includes("analytics_outbox_mark_delivered"));assert.deepEqual(sql?.values,[EVENT,TOKEN,NOW])});
test("failed copies retry time and terminal authority",async()=>{const retry=new Date("2026-07-26T12:10:00.000Z"),client=new Client((text)=>text.includes("analytics_outbox_mark_failed")?[{outcome:"retry_scheduled",result_payload:{}}]:[]);await repo(new Pool([client])).failed({eventId:EVENT,leaseToken:TOKEN,now:NOW,errorCode:"collector_unavailable",retryAt:retry,terminal:false});const sql=client.calls.find((entry)=>entry.text.includes("analytics_outbox_mark_failed"));assert.deepEqual(sql?.values,[EVENT,TOKEN,NOW,"collector_unavailable",retry,false])});
test("dead-letter requeue is an explicit event-scoped workflow operation",async()=>{const client=new Client((text)=>text.includes("analytics_outbox_requeue_dead_letter")?[{outcome:"requeued",result_payload:{}}]:[]);await repo(new Pool([client])).requeue({eventId:EVENT,now:NOW});const sql=client.calls.find((entry)=>entry.text.includes("analytics_outbox_requeue_dead_letter"));assert.deepEqual(sql?.values,[EVENT,NOW]);assert.equal(client.calls.some((entry)=>entry.text==="SET LOCAL ROLE celebix_saas_workflow"),true)});
test("invalid outbox payload is rejected as corruption",async()=>{const invalid={...claim(),payload:{name:"purchase",valueCents:-1,currency:"TRY",source:"storefront"}};const client=new Client((text)=>text.includes("analytics_outbox_claim")?[{outcome:"claimed",result_payload:[invalid]}]:[]);await assert.rejects(()=>repo(new Pool([client])).claim({now:NOW,limit:1,leaseMs:30000}),(error:unknown)=>error instanceof AnalyticsRepositoryError&&error.code==="unavailable")});
test("generalized worker uses v2 and parses one safe cart lifecycle event",async()=>{const lifecycle={...claim(),payload:{name:"cart_abandoned",schemaVersion:1,currency:"TRY",valueMinor:10000}};const client=new Client((text)=>text.includes("analytics_outbox_claim_v2")?[{outcome:"claimed",result_payload:[lifecycle]}]:[]);const claims=await repo(new Pool([client])).claim({now:NOW,limit:1,leaseMs:30000});assert.deepEqual(claims[0]?.payload,lifecycle.payload);assert.match(client.calls.find(({text})=>text.includes("outbox_claim"))?.text??"",/analytics_outbox_claim_v2/)});
test("worker repository rejects role substitution and acquisition failure",async()=>{assert.throws(()=>new PostgresAnalyticsOutboxRepository({pool:new Pool([]),role:"celebix_saas_app" as never,timeouts:{poolCheckoutMs:100,statementMs:500,lockMs:300,idleTransactionMs:700}}),(error:unknown)=>error instanceof AnalyticsRepositoryError&&error.code==="unavailable");await assert.rejects(()=>repo(new Pool([])).claim({now:NOW,limit:1,leaseMs:30000}),(error:unknown)=>error instanceof AnalyticsRepositoryError&&error.code==="unavailable")});
