import { createHash } from "node:crypto";
import type { AnalyticsConnectionMutationResult, AnalyticsConnectionView, TenantContext } from "@celebix/saas-contracts";
import { acquirePostgresClient, type PostgresClientLike } from "../postgres/pool.ts";
import { ANALYTICS_ERROR_CODES, AnalyticsRepositoryError, type AnalyticsErrorCode } from "./errors.ts";
import type { AnalyticsConnectionAuthority, AnalyticsPendingAuthority, AnalyticsRepository, PostgresAnalyticsRepositoryOptions } from "./types.ts";
import { authority, authorityValues, connectionAuthority, connectionView, date, exact, hostname, mutation, pending, positive, projectConnection, uuid, type AnalyticsAuthority } from "./validation.ts";

type Spec=Readonly<{text:string;values:unknown[]}>;type Result=Readonly<{outcome:string;payload:unknown}>;
const CODES=new Set<string>(ANALYTICS_ERROR_CODES);function unavailable(){return new AnalyticsRepositoryError("unavailable")}function timeout(value:number){if(!Number.isSafeInteger(value)||value<1||value>60000)throw unavailable();return`${value}ms`}function release(c:PostgresClientLike,destroy=false){try{c.release(destroy||undefined)}catch{}}
function row(result:Readonly<{rows:unknown[];rowCount?:number|null}>):Result{if(result.rowCount!==1||result.rows.length!==1)throw unavailable();const p=exact(result.rows[0],["outcome","result_payload"],"unavailable");if(typeof p.outcome!=="string")throw unavailable();return{outcome:p.outcome,payload:p.result_payload}}
function fingerprint(kind:string,storeId:string,payload:unknown){return createHash("sha256").update(JSON.stringify({kind,storeId,payload})).digest("hex")}
export class PostgresAnalyticsRepository implements AnalyticsRepository{
  private options:PostgresAnalyticsRepositoryOptions;
  constructor(options:PostgresAnalyticsRepositoryOptions){try{if(!options||typeof options!=="object"||Array.isArray(options)||Object.keys(options).sort().join(",")!=="audit,pool,role,timeouts,uuid"||options.role!=="celebix_saas_app"||typeof options.uuid!=="function"||typeof options.audit!=="function"||!options.timeouts||Object.keys(options.timeouts).sort().join(",")!=="idleTransactionMs,lockMs,poolCheckoutMs,statementMs")throw unavailable();for(const value of Object.values(options.timeouts))timeout(value);this.options=Object.freeze({...options,timeouts:Object.freeze({...options.timeouts})})}catch(error){if(error instanceof AnalyticsRepositoryError)throw error;throw unavailable()}}
  private async acquire(){try{return await acquirePostgresClient(this.options.pool,this.options.timeouts.poolCheckoutMs)}catch{throw unavailable()}}
  private async configure(c:PostgresClientLike){await c.query("SELECT pg_catalog.set_config('statement_timeout', $1, true)",[timeout(this.options.timeouts.statementMs)]);await c.query("SELECT pg_catalog.set_config('lock_timeout', $1, true)",[timeout(this.options.timeouts.lockMs)]);await c.query("SELECT pg_catalog.set_config('idle_in_transaction_session_timeout', $1, true)",[timeout(this.options.timeouts.idleTransactionMs)]);await c.query("SET LOCAL ROLE celebix_saas_app")}
  private error(outcome:string){return CODES.has(outcome)?new AnalyticsRepositoryError(outcome as AnalyticsErrorCode):undefined}
  private async rollback(c:PostgresClientLike){try{await c.query("ROLLBACK");release(c)}catch{release(c,true)}}
  private async read(spec:Spec,allowed:readonly string[]):Promise<Result>{const c=await this.acquire();let began=false,terminal=false;try{await c.query("BEGIN READ ONLY");began=true;await this.configure(c);const result=row(await c.query(spec.text,spec.values));const error=this.error(result.outcome);if(error&&!allowed.includes(result.outcome))throw error;if(!allowed.includes(result.outcome))throw unavailable();try{await c.query("COMMIT");terminal=true;release(c)}catch{terminal=true;release(c,true);throw unavailable()}return result}catch(error){if(began&&!terminal)await this.rollback(c);else if(!began&&!terminal)release(c,true);if(error instanceof AnalyticsRepositoryError)throw error;throw unavailable()}}
  private audit(){try{const result=this.options.audit({type:"analytics_commit_unknown"});if(result)void result.catch(()=>undefined)}catch{}}
  private recover(a:AnalyticsAuthority,operationId:string,digest:string,parser:(value:unknown,replayed:boolean)=>AnalyticsConnectionMutationResult|AnalyticsPendingAuthority){return this.read({text:"SELECT outcome,result_payload FROM saas.analytics_connection_recover_operation($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text)",values:[...authorityValues(a),operationId,digest]},["operation_recovered"]).then((result)=>parser(result.payload,true))}
  private async mutate<T extends AnalyticsConnectionMutationResult|AnalyticsPendingAuthority>(a:AnalyticsAuthority,operationId:string,digest:string,expected:readonly string[],spec:Spec,parser:(value:unknown,replayed:boolean,outcome:string)=>T):Promise<T>{const c=await this.acquire();let began=false,terminal=false;try{await c.query("BEGIN ISOLATION LEVEL READ COMMITTED");began=true;await this.configure(c);const result=row(await c.query(spec.text,spec.values));const error=this.error(result.outcome);if(error&&!expected.includes(result.outcome)&&result.outcome!=="operation_replayed")throw error;if(!expected.includes(result.outcome)&&result.outcome!=="operation_replayed")throw unavailable();const parsed=parser(result.payload,result.outcome==="operation_replayed",result.outcome);try{await c.query("COMMIT");terminal=true;release(c);return parsed}catch{terminal=true;release(c,true);this.audit();return await this.recover(a,operationId,digest,(value,replayed)=>parser(value,replayed,"operation_recovered")) as T}}catch(error){if(began&&!terminal)await this.rollback(c);else if(!began&&!terminal)release(c,true);if(error instanceof AnalyticsRepositoryError)throw error;throw unavailable()}}
  private input(value:unknown,keys:readonly string[]){const p=exact(value,keys);return{p,a:authority(p.tenantContext as TenantContext,p.now as Date)}}
  private getSpec(a:AnalyticsAuthority):Spec{return{text:"SELECT outcome,result_payload FROM saas.analytics_connection_get($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz)",values:authorityValues(a)}}
  async getConnection(input:Readonly<{tenantContext:TenantContext;now:Date}>):Promise<AnalyticsConnectionView>{const{a}=this.input(input,["tenantContext","now"]);const result=await this.read(this.getSpec(a),["found","not_configured"]);return result.outcome==="not_configured"?connectionView(result.payload):projectConnection(result.payload)}
  async getConnectionAuthority(input:Readonly<{tenantContext:TenantContext;now:Date}>):Promise<AnalyticsConnectionAuthority>{const{a}=this.input(input,["tenantContext","now"]);return connectionAuthority((await this.read(this.getSpec(a),["found"])).payload)}
  async beginConnection(input:Readonly<{tenantContext:TenantContext;now:Date;operationId:string;connectionId:string;websiteId:string}>):Promise<AnalyticsPendingAuthority>{const{p,a}=this.input(input,["tenantContext","now","operationId","connectionId","websiteId"]),operationId=uuid(p.operationId),connectionId=uuid(p.connectionId),websiteId=uuid(p.websiteId),digest=fingerprint("begin",a.storeId,{connectionId,websiteId});return this.mutate(a,operationId,digest,["pending","active"],{text:"SELECT outcome,result_payload FROM saas.analytics_connection_begin($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text,$10::uuid,$11::uuid)",values:[...authorityValues(a),operationId,digest,connectionId,websiteId]},(value,replayed,outcome)=>pending(value,outcome==="active"?"active":"pending",replayed))}
  async activateConnection(input:Readonly<{tenantContext:TenantContext;now:Date;operationId:string;connectionId:string;websiteId:string;verifiedHostname:string}>):Promise<AnalyticsConnectionMutationResult>{const{p,a}=this.input(input,["tenantContext","now","operationId","connectionId","websiteId","verifiedHostname"]),operationId=uuid(p.operationId),connectionId=uuid(p.connectionId),websiteId=uuid(p.websiteId),verifiedHostname=hostname(p.verifiedHostname),digest=fingerprint("activate",a.storeId,{connectionId,websiteId,verifiedHostname});return this.mutate(a,operationId,digest,["active"],{text:"SELECT outcome,result_payload FROM saas.analytics_connection_activate($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text,$10::uuid,$11::uuid,$12::text)",values:[...authorityValues(a),operationId,digest,connectionId,websiteId,verifiedHostname]},(value,replayed)=>mutation(value,replayed))}
  async disableConnection(input:Readonly<{tenantContext:TenantContext;now:Date;operationId:string;expectedVersion:number}>):Promise<AnalyticsConnectionMutationResult>{const{p,a}=this.input(input,["tenantContext","now","operationId","expectedVersion"]),operationId=uuid(p.operationId),expectedVersion=positive(p.expectedVersion),current=await this.getConnectionAuthority({tenantContext:p.tenantContext as TenantContext,now:date(p.now)}),digest=fingerprint("disable",a.storeId,{connectionId:current.connectionId,expectedVersion});return this.mutate(a,operationId,digest,["disabled"],{text:"SELECT outcome,result_payload FROM saas.analytics_connection_disable($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text,$10::uuid,$11::bigint)",values:[...authorityValues(a),operationId,digest,current.connectionId,expectedVersion]},(value,replayed)=>mutation(value,replayed))}
}
