import { parsePriceList, parsePriceListItem, parsePriceListRule, type PriceList, type PriceListItem, type PriceListRule } from "@celebix/saas-contracts";
export type PricingApiErrorCode = "invalid_input" | "conflict" | "forbidden" | "not_found" | "unauthenticated" | "method_not_allowed" | "unavailable";
export class PricingApiError extends Error { readonly code: PricingApiErrorCode; readonly status: number; constructor(code: PricingApiErrorCode, status: number) { super(code); this.name = "PricingApiError"; this.code = code; this.status = status; Object.freeze(this); } }
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const CODES = ["invalid_input", "conflict", "forbidden", "not_found", "unauthenticated", "method_not_allowed", "unavailable"] as const;
type Fetch = typeof fetch;
export interface SavePriceListIntent { readonly priceListId?: string; readonly expectedVersion?: number; readonly name: string; readonly items: readonly PriceListItem[]; readonly rules: readonly PriceListRule[] }
function invalid(): never { throw new TypeError("pricing_client_invalid"); }
function id(value: unknown): string { if (typeof value !== "string" || !UUID.test(value)) return invalid(); return value; }
function version(value: unknown): number { if (!Number.isSafeInteger(value) || (value as number) < 1 || (value as number) >= Number.MAX_SAFE_INTEGER) return invalid(); return value as number; }
function exact(value: unknown, required: readonly string[], optional: readonly string[] = []) { if (typeof value !== "object" || value === null || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype) return invalid(); const keys = Object.keys(value), allowed = new Set([...required, ...optional]); if (required.some((key) => !Object.hasOwn(value, key)) || keys.some((key) => !allowed.has(key))) return invalid(); return value as Record<string, unknown>; }
async function read(response: Response): Promise<unknown> {
  const contentType = response.headers.get("content-type")?.split(";", 1)[0]?.trim(); if (contentType !== "application/json") throw new PricingApiError("unavailable", 503);
  const declared = response.headers.get("content-length"); if (declared !== null && (!/^(?:0|[1-9]\d*)$/.test(declared) || Number(declared) > 1_048_576)) throw new PricingApiError("unavailable", 503);
  const reader = response.body?.getReader(); if (!reader) throw new PricingApiError("unavailable", 503); const chunks: Uint8Array[] = []; let total = 0;
  try { for (;;) { const next = await reader.read(); if (next.done) break; total += next.value.byteLength; if (total > 1_048_576) { await reader.cancel().catch(() => undefined); throw new PricingApiError("unavailable", 503); } chunks.push(next.value); } } catch (error) { if (error instanceof PricingApiError) throw error; if (error instanceof DOMException && error.name === "AbortError") throw error; throw new PricingApiError("unavailable", 503); }
  if (declared !== null && Number(declared) !== total) throw new PricingApiError("unavailable", 503); const bytes = new Uint8Array(total); let offset = 0; for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.length; }
  try { return JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(bytes)); } catch { throw new PricingApiError("unavailable", 503); }
}
function apiError(value: unknown, status: number) { try { const parsed = exact(value, ["code"]); if (typeof parsed.code !== "string" || !CODES.includes(parsed.code as never)) throw new Error(); const code = parsed.code as PricingApiErrorCode; const expected: Record<PricingApiErrorCode, number> = { invalid_input: 400, conflict: 409, forbidden: 403, not_found: 404, unauthenticated: 401, method_not_allowed: 405, unavailable: 503 }; return new PricingApiError(expected[code] === status ? code : "unavailable", expected[code] === status ? status : 503); } catch { return new PricingApiError("unavailable", 503); } }
function items(value: unknown): readonly PriceList[] { const parsed = exact(value, ["items"]); if (!Array.isArray(parsed.items) || parsed.items.length > 500) return invalid(); try { return Object.freeze(parsed.items.map(parsePriceList)); } catch { return invalid(); } }
export function createPricingApi(fetcher: Fetch = fetch, uuid: () => string = () => crypto.randomUUID()) {
  if (typeof fetcher !== "function" || typeof uuid !== "function") invalid();
  async function request<T>(path: string, parser: (value: unknown) => T, body?: unknown, signal?: AbortSignal): Promise<T> { try { const response = await fetcher(path, { credentials: "same-origin", cache: "no-store", ...(signal ? { signal } : {}), ...(body === undefined ? {} : { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }) }); const value = await read(response); if (!response.ok) throw apiError(value, response.status); try { return parser(value); } catch (error) { if (error instanceof PricingApiError) throw error; throw new PricingApiError("unavailable", 503); } } catch (error) { if (error instanceof PricingApiError || (error instanceof DOMException && error.name === "AbortError")) throw error; throw new PricingApiError("unavailable", 503); } }
  function operation() { return id(uuid()); }
  return Object.freeze({
    list: (signal?: AbortSignal) => request("/api/pricing/price-lists", items, undefined, signal),
    get: (priceListId: string, signal?: AbortSignal) => request(`/api/pricing/price-lists/${id(priceListId)}`, parsePriceList, undefined, signal),
    save(value: SavePriceListIntent, signal?: AbortSignal) { const parsed = exact(value, ["name", "items", "rules"], ["priceListId", "expectedVersion"]); if (typeof parsed.name !== "string" || !Array.isArray(parsed.items) || !Array.isArray(parsed.rules) || ((parsed.priceListId === undefined) !== (parsed.expectedVersion === undefined))) invalid(); let safeItems: readonly PriceListItem[], safeRules: readonly PriceListRule[]; try { safeItems = Object.freeze(parsed.items.map(parsePriceListItem)); safeRules = Object.freeze(parsed.rules.map(parsePriceListRule)); } catch { return invalid(); } return request("/api/pricing/price-lists", parsePriceList, { operationId: operation(), ...(parsed.priceListId === undefined ? {} : { priceListId: id(parsed.priceListId), expectedVersion: version(parsed.expectedVersion) }), name: parsed.name, items: safeItems, rules: safeRules }, signal); },
    activate: (priceListId: string, expectedVersion: number, signal?: AbortSignal) => request(`/api/pricing/price-lists/${id(priceListId)}/activate`, parsePriceList, { operationId: operation(), expectedVersion: version(expectedVersion) }, signal),
    archive: (priceListId: string, expectedVersion: number, signal?: AbortSignal) => request(`/api/pricing/price-lists/${id(priceListId)}/archive`, parsePriceList, { operationId: operation(), expectedVersion: version(expectedVersion) }, signal),
  });
}
export const pricingApi = createPricingApi();
