export interface PromotionAllocationLine { readonly lineId: string; readonly position: number; readonly currency: string; readonly eligibleMinor: number; readonly paidNetMinor: number; readonly kind: "sale" | "gift" | "buy_x_get_y_free" }
export interface AllocatePromotionDiscountInput { readonly currency: string; readonly discountMinor: number; readonly lines: readonly PromotionAllocationLine[]; readonly orderMaximumMinor?: number }
export interface PromotionDiscountAllocation { readonly lineAllocations: readonly { readonly lineId: string; readonly discountMinor: number }[]; readonly appliedDiscountMinor: number; readonly unallocatedMinor: number }
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const MAX_MINOR = 8_000_000_000;
function invalid(): never { throw new TypeError("promotion_allocation_invalid"); }
function integer(value: unknown, min: number, max: number): number { if (!Number.isSafeInteger(value) || (value as number) < min || (value as number) > max) invalid(); return value as number; }
function currency(value: unknown): string { if (typeof value !== "string" || !/^[A-Z]{3}$/.test(value)) invalid(); return value; }
function line(value: unknown): PromotionAllocationLine { if (typeof value !== "object" || value === null || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype) invalid(); const row = value as Record<string, unknown>; if (Object.keys(row).length !== 6 || !["lineId", "position", "currency", "eligibleMinor", "paidNetMinor", "kind"].every((key) => Object.hasOwn(row, key))) invalid(); if (typeof row.lineId !== "string" || !UUID.test(row.lineId) || (row.kind !== "sale" && row.kind !== "gift" && row.kind !== "buy_x_get_y_free")) invalid(); const submittedEligibleMinor = integer(row.eligibleMinor, 0, MAX_MINOR); const paidNetMinor = integer(row.paidNetMinor, 0, MAX_MINOR); if ((row.kind !== "sale" && paidNetMinor !== 0) || (row.kind === "sale" && submittedEligibleMinor > paidNetMinor)) invalid(); const eligibleMinor = row.kind === "sale" ? submittedEligibleMinor : 0; return { lineId: row.lineId, position: integer(row.position, 0, 1_000_000), currency: currency(row.currency), eligibleMinor, paidNetMinor, kind: row.kind }; }
export function allocatePromotionDiscount(input: AllocatePromotionDiscountInput): PromotionDiscountAllocation { if (typeof input !== "object" || input === null) invalid(); const requested = integer(input.discountMinor, 0, MAX_MINOR); const requestCurrency = currency(input.currency); const lines = input.lines; if (!Array.isArray(lines) || lines.length > 100) invalid(); const parsed = lines.map(line); if (new Set(parsed.map((entry) => entry.lineId)).size !== parsed.length || parsed.some((entry) => entry.currency !== requestCurrency)) invalid(); const orderMaximum = input.orderMaximumMinor === undefined ? MAX_MINOR : integer(input.orderMaximumMinor, 0, MAX_MINOR); const eligibleTotal = parsed.reduce((sum, entry) => { const next = sum + entry.eligibleMinor; if (!Number.isSafeInteger(next)) invalid(); return next; }, 0); const applied = Math.min(requested, orderMaximum, eligibleTotal); const ranked = [...parsed].sort((a, b) => a.position - b.position || (a.lineId < b.lineId ? -1 : a.lineId > b.lineId ? 1 : 0)); const allocations = new Map<string, number>(); let allocated = 0; for (const entry of ranked) { const share = eligibleTotal === 0 ? 0 : Number((BigInt(applied) * BigInt(entry.eligibleMinor)) / BigInt(eligibleTotal)); allocations.set(entry.lineId, share); allocated += share; } let remaining = applied - allocated; for (const entry of ranked) { if (remaining === 0) break; if (entry.eligibleMinor === 0) continue; allocations.set(entry.lineId, allocations.get(entry.lineId)! + 1); remaining -= 1; } const lineAllocations = Object.freeze(ranked.map((entry) => Object.freeze({ lineId: entry.lineId, discountMinor: allocations.get(entry.lineId)! }))); return Object.freeze({ lineAllocations, appliedDiscountMinor: applied, unallocatedMinor: requested - applied }); }
export function refundablePromotionAmount(input: { readonly paidNetMinor: number; readonly allocatedDiscountMinor: number; readonly alreadyRefundedMinor: number; readonly requestedRefundMinor: number }): number { const paid = integer(input.paidNetMinor, 0, MAX_MINOR); const allocated = integer(input.allocatedDiscountMinor, 0, MAX_MINOR); const already = integer(input.alreadyRefundedMinor, 0, MAX_MINOR); const requested = integer(input.requestedRefundMinor, 0, MAX_MINOR); if (allocated > paid || already > allocated) invalid(); return Math.min(requested, allocated - already, paid - already); }
