export interface PromotionAllocationLine { readonly lineId: string; readonly position: number; readonly currency: string; readonly eligibleMinor: number; readonly paidNetMinor: number; readonly kind: "sale" | "gift" | "buy_x_get_y_free" }
export interface AllocatePromotionDiscountInput { readonly currency: string; readonly discountMinor: number; readonly lines: readonly PromotionAllocationLine[]; readonly orderMaximumMinor?: number }
export interface PromotionDiscountAllocation { readonly lineAllocations: readonly { readonly lineId: string; readonly discountMinor: number }[]; readonly appliedDiscountMinor: number; readonly unallocatedMinor: number }
export type PromotionCapturedRefundKind = "sale" | "gift" | "buy_x_get_y";
export interface PromotionCapturedRefundRange { readonly startOrdinal: number; readonly quantity: number; readonly grossUnitMinor: number; readonly discountUnitMinor: number; readonly kind: PromotionCapturedRefundKind }
export interface PromotionReturnedRange { readonly startOrdinal: number; readonly quantity: number }
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const MAX_MINOR = 8_000_000_000;
function invalid(): never { throw new TypeError("promotion_allocation_invalid"); }
function integer(value: unknown, min: number, max: number): number { if (!Number.isSafeInteger(value) || (value as number) < min || (value as number) > max) invalid(); return value as number; }
function currency(value: unknown): string { if (typeof value !== "string" || !/^[A-Z]{3}$/.test(value)) invalid(); return value; }
function line(value: unknown): PromotionAllocationLine { if (typeof value !== "object" || value === null || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype) invalid(); const row = value as Record<string, unknown>; if (Object.keys(row).length !== 6 || !["lineId", "position", "currency", "eligibleMinor", "paidNetMinor", "kind"].every((key) => Object.hasOwn(row, key))) invalid(); if (typeof row.lineId !== "string" || !UUID.test(row.lineId) || (row.kind !== "sale" && row.kind !== "gift" && row.kind !== "buy_x_get_y_free")) invalid(); const submittedEligibleMinor = integer(row.eligibleMinor, 0, MAX_MINOR); const paidNetMinor = integer(row.paidNetMinor, 0, MAX_MINOR); if ((row.kind !== "sale" && paidNetMinor !== 0) || (row.kind === "sale" && submittedEligibleMinor > paidNetMinor)) invalid(); const eligibleMinor = row.kind === "sale" ? submittedEligibleMinor : 0; return { lineId: row.lineId, position: integer(row.position, 0, 1_000_000), currency: currency(row.currency), eligibleMinor, paidNetMinor, kind: row.kind }; }
export function allocatePromotionDiscount(input: AllocatePromotionDiscountInput): PromotionDiscountAllocation { if (typeof input !== "object" || input === null) invalid(); const requested = integer(input.discountMinor, 0, MAX_MINOR); const requestCurrency = currency(input.currency); const lines = input.lines; if (!Array.isArray(lines) || lines.length > 100) invalid(); const parsed = lines.map(line); if (new Set(parsed.map((entry) => entry.lineId)).size !== parsed.length || parsed.some((entry) => entry.currency !== requestCurrency)) invalid(); const orderMaximum = input.orderMaximumMinor === undefined ? MAX_MINOR : integer(input.orderMaximumMinor, 0, MAX_MINOR); const eligibleTotal = parsed.reduce((sum, entry) => { const next = sum + entry.eligibleMinor; if (!Number.isSafeInteger(next)) invalid(); return next; }, 0); const applied = Math.min(requested, orderMaximum, eligibleTotal); const ranked = [...parsed].sort((a, b) => a.position - b.position || (a.lineId < b.lineId ? -1 : a.lineId > b.lineId ? 1 : 0)); const allocations = new Map<string, number>(); let allocated = 0; for (const entry of ranked) { const share = eligibleTotal === 0 ? 0 : Number((BigInt(applied) * BigInt(entry.eligibleMinor)) / BigInt(eligibleTotal)); allocations.set(entry.lineId, share); allocated += share; } let remaining = applied - allocated; for (const entry of [...ranked].reverse()) { if (remaining === 0) break; if (entry.eligibleMinor === 0) continue; allocations.set(entry.lineId, allocations.get(entry.lineId)! + 1); remaining -= 1; } const lineAllocations = Object.freeze(ranked.map((entry) => Object.freeze({ lineId: entry.lineId, discountMinor: allocations.get(entry.lineId)! }))); return Object.freeze({ lineAllocations, appliedDiscountMinor: applied, unallocatedMinor: requested - applied }); }
export function refundablePromotionAmount(input: { readonly paidNetMinor: number; readonly allocatedDiscountMinor: number; readonly alreadyRefundedMinor: number; readonly requestedRefundMinor: number }): number { const paid = integer(input.paidNetMinor, 0, MAX_MINOR); const allocated = integer(input.allocatedDiscountMinor, 0, MAX_MINOR); const already = integer(input.alreadyRefundedMinor, 0, MAX_MINOR); const requested = integer(input.requestedRefundMinor, 0, MAX_MINOR); if (allocated > paid || already > allocated) invalid(); return Math.min(requested, allocated - already, paid - already); }
export function cappedPaidLineRefundMinor(input: { readonly lineKind: PromotionAllocationLine["kind"]; readonly capturedPaidNetMinor: number; readonly alreadyRefundedMinor: number; readonly requestedCashRefundMinor: number }): number { const captured = integer(input.capturedPaidNetMinor, 0, MAX_MINOR); const already = integer(input.alreadyRefundedMinor, 0, MAX_MINOR); const requested = integer(input.requestedCashRefundMinor, 0, MAX_MINOR); if (input.lineKind !== "sale" && input.lineKind !== "gift" && input.lineKind !== "buy_x_get_y_free") invalid(); if (input.lineKind !== "sale") { if (captured !== 0 || already !== 0) invalid(); return 0; } if (already > captured) invalid(); return Math.min(requested, captured - already); }
function exactKeys(value: unknown, keys: readonly string[]): Record<string, unknown> { if (typeof value !== "object" || value === null || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype) invalid(); const row = value as Record<string, unknown>; if (Object.keys(row).length !== keys.length || !keys.every((key) => Object.hasOwn(row, key))) invalid(); return row; }
function capturedRefundRange(value: unknown): PromotionCapturedRefundRange { const row = exactKeys(value, ["startOrdinal", "quantity", "grossUnitMinor", "discountUnitMinor", "kind"]); if (row.kind !== "sale" && row.kind !== "gift" && row.kind !== "buy_x_get_y") invalid(); const startOrdinal = integer(row.startOrdinal, 0, 999_999); const quantity = integer(row.quantity, 1, 1_000_000); if (startOrdinal + quantity > 1_000_000) invalid(); const grossUnitMinor = integer(row.grossUnitMinor, 0, MAX_MINOR); const discountUnitMinor = integer(row.discountUnitMinor, 0, MAX_MINOR); if (discountUnitMinor > grossUnitMinor || (row.kind === "gift" && discountUnitMinor !== grossUnitMinor)) invalid(); return { startOrdinal, quantity, grossUnitMinor, discountUnitMinor, kind: row.kind }; }
function returnedRange(value: unknown): PromotionReturnedRange { const row = exactKeys(value, ["startOrdinal", "quantity"]); const startOrdinal = integer(row.startOrdinal, 0, 999_999); const quantity = integer(row.quantity, 1, 1_000_000); if (startOrdinal + quantity > 1_000_000) invalid(); return { startOrdinal, quantity }; }
export function cappedCapturedUnitRefundMinor(input: { readonly capturedRangeSets: readonly (readonly PromotionCapturedRefundRange[])[]; readonly previouslyReturnedRanges: readonly PromotionReturnedRange[]; readonly returnedRanges: readonly PromotionReturnedRange[]; readonly linePaidNetMinor: number; readonly alreadyRefundedMinor: number; readonly requestedCashRefundMinor: number }): number {
  const root = exactKeys(input, ["capturedRangeSets", "previouslyReturnedRanges", "returnedRanges", "linePaidNetMinor", "alreadyRefundedMinor", "requestedCashRefundMinor"]);
  if (!Array.isArray(input.capturedRangeSets) || input.capturedRangeSets.length < 1 || input.capturedRangeSets.length > 100 || !Array.isArray(input.previouslyReturnedRanges) || input.previouslyReturnedRanges.length > 2_000 || !Array.isArray(input.returnedRanges) || input.returnedRanges.length < 1 || input.returnedRanges.length > 2_000) invalid();
  const capturedSets = input.capturedRangeSets.map((set) => { if (!Array.isArray(set) || set.length < 1 || set.length > 64) invalid(); return set.map(capturedRefundRange); });
  if (capturedSets.reduce((total, set) => total + set.length, 0) > 6_400) invalid();
  let lineQuantity: number | undefined;
  for (const captured of capturedSets) { let end = 0; let previous: PromotionCapturedRefundRange | undefined; for (const range of captured) { if (range.startOrdinal !== end || (previous && previous.kind === range.kind && previous.grossUnitMinor === range.grossUnitMinor && previous.discountUnitMinor === range.discountUnitMinor)) invalid(); end += range.quantity; previous = range; } if (lineQuantity === undefined) lineQuantity = end; else if (lineQuantity !== end) invalid(); }
  const parseSelections = (values: readonly PromotionReturnedRange[], allowEmpty: boolean) => { if (!allowEmpty && values.length === 0) invalid(); const parsed = values.map(returnedRange); let end = 0; let total = 0; for (const range of parsed) { if (range.startOrdinal < end || range.startOrdinal + range.quantity > lineQuantity!) invalid(); end = range.startOrdinal + range.quantity; total += range.quantity; if (total > 1_000_000) invalid(); } return parsed; };
  const previousReturned = parseSelections(input.previouslyReturnedRanges, true);
  const returned = parseSelections(input.returnedRanges, false);
  if (previousReturned.some((previous) => returned.some((current) => Math.max(previous.startOrdinal, current.startOrdinal) < Math.min(previous.startOrdinal + previous.quantity, current.startOrdinal + current.quantity)))) invalid();
  const entitlement = (selections: readonly PromotionReturnedRange[]) => {
    let paid = 0n;
    for (const selection of selections) {
      const selectionEnd = selection.startOrdinal + selection.quantity;
      const boundaries = new Set<number>([selection.startOrdinal, selectionEnd]);
      for (const set of capturedSets) for (const range of set) { const start = Math.max(selection.startOrdinal, range.startOrdinal); const end = Math.min(selectionEnd, range.startOrdinal + range.quantity); if (start < end) { boundaries.add(start); boundaries.add(end); } }
      const ordered = [...boundaries].sort((left, right) => left - right);
      for (let index = 1; index < ordered.length; index += 1) {
        const start = ordered[index - 1]!, end = ordered[index]!;
        const covering = capturedSets.map((set) => set.find((range) => range.startOrdinal <= start && range.startOrdinal + range.quantity >= end));
        if (covering.some((range) => range === undefined)) invalid();
        const gross = covering[0]!.grossUnitMinor;
        if (covering.some((range) => range!.grossUnitMinor !== gross)) invalid();
        const totalDiscount = covering.reduce((sum, range) => sum + BigInt(range!.discountUnitMinor), 0n);
        if (totalDiscount > BigInt(gross)) invalid();
        paid += BigInt(end - start) * (BigInt(gross) - totalDiscount);
        if (paid > BigInt(MAX_MINOR)) invalid();
      }
    }
    return Number(paid);
  };
  const previousEntitlementMinor = entitlement(previousReturned);
  const returnedEntitlementMinor = entitlement(returned);
  const linePaidNetMinor = integer(input.linePaidNetMinor, 0, MAX_MINOR);
  const already = integer(input.alreadyRefundedMinor, 0, MAX_MINOR);
  const requested = integer(input.requestedCashRefundMinor, 0, MAX_MINOR);
  if (already > previousEntitlementMinor || already > linePaidNetMinor) invalid();
  return Math.min(requested, returnedEntitlementMinor, linePaidNetMinor - already);
}
