import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import { accessSync, chmodSync, constants, existsSync, mkdtempSync, mkdirSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { createServer as createHttpServer, request as httpRequest } from "node:http";
import { connect, createServer } from "node:net";
import { homedir, tmpdir } from "node:os";
import path from "node:path";
import { spawn, spawnSync } from "node:child_process";
import { createServer as createTlsServer } from "node:tls";
import { parsePublicStorefront } from "@celebix/saas-contracts";

const ROOT=path.resolve(import.meta.dirname,"../../.."),SQL=path.join(ROOT,"apps/owner/scripts/sql/saas"),DB="starter_retail_experience",RESTORE="starter_retail_restore";
const UP="202608020075_complete_starter_retail_experience.up.sql",DOWN="202608020075_complete_starter_retail_experience.down.sql",ASSERTIONS="202608020075_complete_starter_retail_experience_assertions.sql";
const STORE_A="10000000-0000-4000-8000-000000000075",STORE_B="10000000-0000-4000-8000-000000000076",HOST_A="retail-a.example.test",HOST_PLATFORM="retail-a.saas-staging.celebix.site",HOST_B="retail-b.example.test",PLAN="00000000-0000-4000-8000-000000000001";
const PRINCIPAL_A="20000000-0000-4000-8000-000000000075",PRINCIPAL_B="20000000-0000-4000-8000-000000000076",MEMBERSHIP_A="30000000-0000-4000-8000-000000000075",MEMBERSHIP_B="30000000-0000-4000-8000-000000000076";
const PRODUCT="40000000-0000-4000-8000-000000000075",INACTIVE_PRODUCT="40000000-0000-4000-8000-000000000076",VARIANT="50000000-0000-4000-8000-000000000075",COMPOSITION="60000000-0000-4000-8000-000000000075",NOW="2026-08-02T09:00:00.000Z";
const BUILT_BROWSER=process.env.STARTER_RETAIL_BUILT_BROWSER==="1";
let completed=0;const TOTAL=20;

function executable(name){const candidates=[process.env.POSTGRES_BIN,...(process.env.PATH??"").split(path.delimiter)];try{for(const entry of readdirSync(path.join(homedir(),".codex","tmp"),{withFileTypes:true}))if(entry.isDirectory()&&/^postgresql-16[.]/.test(entry.name))candidates.push(path.join(homedir(),".codex","tmp",entry.name,"bin"));}catch{}for(const directory of candidates){if(!directory)continue;const candidate=path.join(directory,name);try{accessSync(candidate,constants.X_OK);return candidate;}catch{}}throw new Error(`DISPOSABLE_DB_EXECUTION_BLOCKED: missing ${name}`);}
function command(program,args,input="",allowFailure=false,environment={}){const result=spawnSync(program,args,{cwd:ROOT,input,encoding:"utf8",env:{...process.env,...environment,LC_ALL:"C",LANG:"C"},maxBuffer:128*1024*1024});if(result.error)throw result.error;if(!allowFailure&&result.status!==0)throw new Error(`${path.basename(program)} failed\n${result.stderr}`);return result;}
function asyncCommand(program,args,input="",environment={}){return new Promise((resolve,reject)=>{const child=spawn(program,args,{cwd:ROOT,env:{...process.env,...environment,LC_ALL:"C",LANG:"C"}});let stdout="",stderr="";child.stdout.setEncoding("utf8");child.stderr.setEncoding("utf8");child.stdout.on("data",chunk=>stdout+=chunk);child.stderr.on("data",chunk=>stderr+=chunk);child.on("error",reject);child.on("close",status=>status===0?resolve({stdout,stderr,status}):reject(new Error(`${path.basename(program)} failed\n${stderr}`)));child.stdin.end(input);});}
function start(){const tools=Object.fromEntries(["initdb","pg_ctl","psql","pg_dump","pg_restore"].map(name=>[name,executable(name)])),root=mkdtempSync(path.join(tmpdir(),"celebix-starter-retail-")),data=path.join(root,"data"),socket=path.join(root,"socket"),port=20000+Math.floor(Math.random()*15000);mkdirSync(socket,{mode:0o700});command(tools.initdb,["-D",data,"--auth=trust","--username=postgres","--no-locale","--encoding=UTF8"]);let options=`-k ${socket} -p ${port} -h ''`,certificate=null,key=null;if(BUILT_BROWSER){certificate=path.join(root,"server.crt");key=path.join(root,"server.key");const openssl=["/usr/bin/openssl","/opt/homebrew/bin/openssl"].find(existsSync);assert.ok(openssl,"openssl_required_for_built_browser");command(openssl,["req","-new","-x509","-nodes","-days","1","-subj","/CN=localhost","-addext","subjectAltName=DNS:localhost,IP:127.0.0.1","-out",certificate,"-keyout",key]);chmodSync(key,0o600);options=`-k ${socket} -p ${port} -h 127.0.0.1`;}command(tools.pg_ctl,["-D",data,"-o",options,"-l",path.join(root,"postgres.log"),"start"]);return{tools,root,data,socket,port,certificate,key};}
function stop(box){if(!box)return;command(box.tools.pg_ctl,["-D",box.data,"-m","fast","stop"],"",true);rmSync(box.root,{recursive:true,force:true});}
function psql(box,source,database=DB,allowFailure=false){return command(box.tools.psql,["-h",box.socket,"-p",String(box.port),"-X","-qAt","-v","ON_ERROR_STOP=1","-U","postgres","-d",database],source,allowFailure);}
function psqlAsync(box,source,database=DB){return asyncCommand(box.tools.psql,["-h",box.socket,"-p",String(box.port),"-X","-qAt","-v","ON_ERROR_STOP=1","-U","postgres","-d",database],source);}
function apply(box,file,database=DB){psql(box,readFileSync(path.join(SQL,file),"utf8"),database);}
function migrations(){const accepted=/(?:[.]up|[.]seed|[.]freeze|_grants|_assertions|catalog_assertions)[.]sql$/;return readdirSync(SQL).filter(file=>{const sequence=Number.parseInt(file.slice(8,12),10);return Number.isSafeInteger(sequence)&&sequence<=71&&accepted.test(file)&&!file.includes(".down.");}).sort((left,right)=>{const a=Number.parseInt(left.slice(8,12),10),b=Number.parseInt(right.slice(8,12),10);if(a!==b)return a-b;const weight=value=>value.includes("assertions")?3:value.includes("freeze")||value.includes("grants")?2:1;return weight(left)-weight(right)||left.localeCompare(right);});}
function authority(store=STORE_A,principal=PRINCIPAL_A,membership=MEMBERSHIP_A){return `'${store}','${principal}','${membership}','${PLAN}','free_starter',1`;}
function config(overrides={}){return{schemaVersion:2,visual:{colorScheme:"neutral",headingStyle:"serif",cornerStyle:"soft",headerStyle:"overlay",productCardStyle:"editorial",productImageRatio:"portrait",headerWidth:"wide",sectionSpacing:"balanced"},announcement:{enabled:false,items:[]},navigation:{rootCategoryIds:[]},sections:[{kind:"product_row",enabled:true,heading:"Yeni ürünler",source:"latest",limit:8},{kind:"value_propositions",enabled:true,items:[{icon:"sparkles",heading:"Özenli seçki",body:"Mağaza tarafından hazırlanan ürünler."},{icon:"heart",heading:"Güvenli deneyim",body:"Kalıcı mağaza verileriyle sunulur."}]},{kind:"testimonials",enabled:true,heading:"Müşterilerimiz anlatıyor",source:"approved_product_reviews",limit:3,minimumRating:4}],productDetail:{galleryStyle:"rail",showSku:true,showBrand:true,showBreadcrumbs:true,showRelatedProducts:true,showApprovedReviews:true,mobileStickyPurchase:true,showSizeGuide:true,informationSections:["description","materials_and_care","certifications","shipping_and_returns"]},cart:{showCheckoutReadiness:true,showShippingProgress:true},footer:{tone:"dark",groups:[{heading:"Mağaza",links:[{kind:"system",destination:"/"},{kind:"system",destination:"/products"}]},{heading:"Hesap",links:[{kind:"system",destination:"/account"}]}],newsletter:{enabled:true,heading:"Bültene katılın",body:"Yeni ürünleri ilk siz öğrenin.",consentLabel:"E-posta iletişimine izin veriyorum."},social:[]},...overrides};}
function save(box,value=config(),operation="70000000-0000-4000-8000-000000000075",allowFailure=false){return psql(box,`BEGIN;SET LOCAL ROLE celebix_saas_app;SELECT outcome FROM saas.merchant_admin_save(${authority()},'${NOW}','${operation}','${"a".repeat(64)}','${COMPOSITION}',NULL,'starter_theme_composition','Starter','${JSON.stringify(value).replaceAll("'","''")}'::jsonb,'active');COMMIT;`,DB,allowFailure);}
function result(box,call,database=DB){const output=psql(box,`BEGIN;SET LOCAL ROLE celebix_saas_host_resolver;SELECT outcome||'|'||COALESCE(result_payload::text,'null') FROM ${call};COMMIT;`,database).stdout.trim().split("\n").at(-1),separator=output.indexOf("|");return{outcome:output.slice(0,separator),payload:JSON.parse(output.slice(separator+1))};}
async function scenario(name,run){await run();completed+=1;console.log(`PASS ${completed}/${TOTAL} ${name}`);}

function freePort(){return new Promise((resolve,reject)=>{const server=createServer();server.once("error",reject);server.listen(0,"127.0.0.1",()=>{const address=server.address();server.close(error=>error?reject(error):resolve(typeof address==="object"&&address?address.port:0));});});}
async function stopChild(child){if(child.exitCode!==null)return;child.kill("SIGTERM");await Promise.race([new Promise(resolve=>child.once("exit",resolve)),new Promise(resolve=>setTimeout(resolve,2_000))]);if(child.exitCode===null)child.kill("SIGKILL");}
async function startPostgresTlsProxy(box){
 assert.ok(box.certificate&&box.key,"tls_proxy_certificate_required");const port=await freePort(),sockets=new Set(),tlsServer=createTlsServer({cert:readFileSync(box.certificate),key:readFileSync(box.key)},secure=>{sockets.add(secure);const upstream=connect(box.port,"127.0.0.1");sockets.add(upstream);secure.on("error",()=>upstream.destroy());upstream.on("error",()=>secure.destroy());secure.on("close",()=>{sockets.delete(secure);upstream.destroy();});upstream.on("close",()=>{sockets.delete(upstream);secure.destroy();});secure.pipe(upstream).pipe(secure);}),server=createServer(socket=>{socket.once("data",header=>{if(header.byteLength!==8||header.readInt32BE(0)!==8||header.readInt32BE(4)!==80877103){socket.destroy();return;}socket.write("S",()=>tlsServer.emit("connection",socket));});});
 await new Promise((resolve,reject)=>{server.once("error",reject);server.listen(port,"127.0.0.1",resolve);});return{port,async close(){for(const socket of sockets)socket.destroy();await new Promise(resolve=>server.close(()=>resolve()));}};
}
async function startStorefrontAuthorityProxy(targetOrigin,publicOrigin,proxyToken){
 const port=await freePort(),publicHostname=new URL(publicOrigin).hostname,server=createHttpServer((request,response)=>{const headers={};
  for(const[name,value]of Object.entries(request.headers)){if(value===undefined)continue;const lower=name.toLowerCase();if(["connection","host","keep-alive","origin","proxy-authenticate","proxy-authorization","te","trailer","transfer-encoding","upgrade","x-forwarded-host","x-forwarded-proto","x-celebix-storefront-proxy"].includes(lower))continue;headers[name]=value;}
  headers["x-forwarded-host"]=publicHostname;headers["x-forwarded-proto"]="https";headers["x-celebix-storefront-proxy"]=`p1.${proxyToken}`;
  if(!["GET","HEAD"].includes(request.method??"GET"))headers.origin=publicOrigin;
  const upstream=httpRequest(new URL(request.url??"/",targetOrigin),{method:request.method,headers},upstreamResponse=>{response.writeHead(upstreamResponse.statusCode??502,upstreamResponse.headers);upstreamResponse.pipe(response);});
  upstream.on("error",()=>{if(!response.headersSent)response.writeHead(502);response.end("authority_proxy_unavailable");});request.pipe(upstream);
 });
 await new Promise((resolve,reject)=>{server.once("error",reject);server.listen(port,"127.0.0.1",resolve);});return{origin:`http://127.0.0.1:${port}`,async close(){server.closeAllConnections();await new Promise(resolve=>server.close(()=>resolve()));}};
}
async function runBuiltBrowserAcceptance(box){
 const database="starter_retail_staging",role="starter_retail_browser_runtime",password=randomBytes(24).toString("base64url"),proxyToken=Buffer.alloc(32,0x51).toString("base64url"),commerceKey=Buffer.alloc(32,0x52).toString("base64url");
 psql(box,`CREATE DATABASE ${database} TEMPLATE ${DB};CREATE ROLE ${role} LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS PASSWORD '${password}';GRANT celebix_saas_host_resolver,celebix_saas_workflow TO ${role};`,"postgres");
 const tlsProxy=await startPostgresTlsProxy(box),databaseUrl=new URL("postgresql://127.0.0.1");databaseUrl.username=role;databaseUrl.password=password;databaseUrl.port=String(tlsProxy.port);databaseUrl.pathname=`/${database}`;databaseUrl.searchParams.set("sslmode","require");
 const port=await freePort(),base=`http://127.0.0.1:${port}`,publicOrigin=`https://${HOST_A}`,environment={NODE_ENV:"production",NODE_EXTRA_CA_CERTS:box.certificate,NEXT_TELEMETRY_DISABLED:"1",CELEBIX_DEPLOYMENT_TIER:"staging",CELEBIX_STOREFRONT_DATA_MODE:"approved_staging",CELEBIX_SAAS_DATABASE_NAME:database,CELEBIX_SAAS_DATABASE_URL:databaseUrl.toString(),CELEBIX_R2_MEDIA_ENVIRONMENT:"staging",CELEBIX_R2_PUBLIC_ORIGIN:"https://media.saas-staging.celebix.site",CELEBIX_STOREFRONT_PROXY_MODE:"approved_staging",CELEBIX_STOREFRONT_PROXY_TOKEN_B64URL:proxyToken,CELEBIX_STOREFRONT_COMMERCE_CREDENTIALS_MODE:"approved_staging",CELEBIX_STOREFRONT_COMMERCE_ACTIVE_KEY_ID:"current_01",CELEBIX_STOREFRONT_COMMERCE_KEYS:JSON.stringify([{keyId:"current_01",key:commerceKey}])};
 assert.equal(existsSync(path.join(ROOT,"apps/storefront-shared/.next/BUILD_ID")),true,"storefront_production_build_required");
 const child=spawn(process.execPath,[path.join(ROOT,"node_modules/next/dist/bin/next"),"start",path.join(ROOT,"apps/storefront-shared"),"-H","127.0.0.1","-p",String(port)],{cwd:ROOT,env:{...process.env,...environment},stdio:["ignore","pipe","pipe"]});let output="";child.stdout.on("data",value=>output=`${output}${String(value)}`.slice(-20_000));child.stderr.on("data",value=>output=`${output}${String(value)}`.slice(-20_000));
 let authorityProxy;try{const deadline=Date.now()+30_000;let ready=false;while(Date.now()<deadline){try{const response=await fetch(base,{headers:{"x-forwarded-host":HOST_A,"x-forwarded-proto":"https","x-celebix-storefront-proxy":`p1.${proxyToken}`}});if(response.status===200){ready=true;break;}}catch{}await new Promise(resolve=>setTimeout(resolve,100));}if(!ready)throw new Error(`built_storefront_start_failed\n${output}`);authorityProxy=await startStorefrontAuthorityProxy(base,publicOrigin,proxyToken);const proxyReady=await fetch(authorityProxy.origin);assert.equal(proxyReady.status,200,`authority_proxy_status:${proxyReady.status}:${(await proxyReady.text()).slice(0,120)}`);
  let browser;try{browser=await asyncCommand(process.execPath,[path.join(ROOT,"tests/saas-phase3/starter-retail-experience/browser-acceptance.mjs")],"",{...environment,STOREFRONT_ACCEPTANCE_MODE:"built",STOREFRONT_BASE_URL:`${authorityProxy.origin}/`,STOREFRONT_PUBLIC_ORIGIN:publicOrigin});}catch(error){throw new Error(`${error.message}\n${output}`);}process.stdout.write(browser.stdout);
  assert.equal(psql(box,"SELECT count(*) FROM saas.storefront_carts;",database).stdout.trim(),"1");assert.equal(psql(box,"SELECT count(*) FROM saas.storefront_newsletter_subscribers WHERE normalized_email='browser@example.test';",database).stdout.trim(),"1");console.log("PASS built storefront + disposable PostgreSQL browser authority");
 }finally{await authorityProxy?.close();await stopChild(child);await tlsProxy.close();}
}

async function main(){let box;try{
 for(const file of [UP,DOWN,ASSERTIONS])assert.equal(existsSync(path.join(SQL,file)),true,file);box=start();psql(box,`CREATE DATABASE ${DB};`,"postgres");for(const file of migrations())apply(box,file);for(const file of ["202607310072_storefront_cart_checkout.up.sql","202608010073_storefront_checkout_readiness.up.sql","202608010073_storefront_checkout_readiness_assertions.sql","202608010074_campaign_starter_composition.up.sql","202608010074_campaign_starter_composition_assertions.sql"])apply(box,file);apply(box,UP);apply(box,ASSERTIONS);
 await scenario("PostgreSQL 16 installs migration 075",()=>assert.match(psql(box,"SHOW server_version;").stdout,/^16[.]/));
 await scenario("v1 remains valid and v2 is exact",()=>{assert.equal(psql(box,`SELECT saas.campaign_starter_composition_valid('${JSON.stringify(config())}'::jsonb);`).stdout.trim(),"t");assert.equal(psql(box,`SELECT saas.campaign_starter_composition_valid('${JSON.stringify({...config(),storeId:STORE_A})}'::jsonb);`).stdout.trim(),"f");});
 psql(box,`BEGIN;SET LOCAL ROLE celebix_saas_owner;
 INSERT INTO saas.stores(id,name,slug,status,locale,currency,theme_key,created_at,updated_at) VALUES('${STORE_A}','Retail A','retail-a','active','tr','TRY','starter','2026-01-01','2026-01-01'),('${STORE_B}','Retail B','retail-b','active','tr','TRY','starter','2026-01-01','2026-01-01');
 INSERT INTO saas.principals(id,issuer,subject,email,email_verified,created_at,updated_at) VALUES('${PRINCIPAL_A}','https://identity.example.test/oidc','a','a@example.test',true,'2026-01-01','2026-01-01'),('${PRINCIPAL_B}','https://identity.example.test/oidc','b','b@example.test',true,'2026-01-01','2026-01-01');
 INSERT INTO saas.memberships(id,principal_id,store_id,role,status,created_at,updated_at) VALUES('${MEMBERSHIP_A}','${PRINCIPAL_A}','${STORE_A}','store_owner','active','2026-01-01','2026-01-01'),('${MEMBERSHIP_B}','${PRINCIPAL_B}','${STORE_B}','store_owner','active','2026-01-01','2026-01-01');
 INSERT INTO saas.subscriptions(id,store_id,plan_id,plan_code,plan_version,status,valid_from,created_at,updated_at) VALUES('71000000-0000-4000-8000-000000000075','${STORE_A}','${PLAN}','free_starter',1,'active','2026-01-01','2026-01-01','2026-01-01'),('71000000-0000-4000-8000-000000000076','${STORE_B}','${PLAN}','free_starter',1,'active','2026-01-01','2026-01-01','2026-01-01');
 INSERT INTO saas.store_domains(id,store_id,hostname,hostname_type,status,is_primary,verified_at,created_at,updated_at,version) VALUES('72000000-0000-4000-8000-000000000075','${STORE_A}','${HOST_A}','custom_domain','active',true,'2026-01-01','2026-01-01','2026-01-01',1),('72000000-0000-4000-8000-000000000074','${STORE_A}','${HOST_PLATFORM}','platform_subdomain','active',false,'2026-01-01','2026-01-01','2026-01-01',1),('72000000-0000-4000-8000-000000000076','${STORE_B}','${HOST_B}','custom_domain','active',true,'2026-01-01','2026-01-01','2026-01-01',1);
 INSERT INTO saas.products(id,store_id,slug,title,description,status,currency,version,archived_at,created_at,updated_at) VALUES('${PRODUCT}','${STORE_A}','keten-etek','Keten Etek','**Yumuşak** dokulu.','active','TRY',1,NULL,'2026-01-01','2026-01-01'),('${INACTIVE_PRODUCT}','${STORE_A}','arsiv-urun','Arşiv Ürün',NULL,'archived','TRY',1,'2026-01-01','2026-01-01','2026-01-01');
 SELECT pg_catalog.set_config('saas.inventory.source_marker','catalog_adjustment',true);SELECT pg_catalog.set_config('saas.inventory.source_id','73000000-0000-4000-8000-000000000075',true);SELECT pg_catalog.set_config('saas.inventory.source_time','${NOW}',true);
 INSERT INTO saas.product_variants(id,product_id,store_id,title,sku,barcode,price_cents,compare_at_cents,cost_cents,stock_tracking,stock_quantity,status,attributes,version,archived_at,created_at,updated_at) VALUES('${VARIANT}','${PRODUCT}','${STORE_A}','Standart','RETAIL-1',NULL,11200,NULL,NULL,true,5,'active','{}',1,NULL,'2026-01-01','2026-01-01');
 SELECT pg_catalog.set_config('saas.inventory.source_marker','',true);SELECT pg_catalog.set_config('saas.inventory.source_id','',true);SELECT pg_catalog.set_config('saas.inventory.source_time','',true);
 INSERT INTO saas.product_reviews(id,store_id,product_id,reviewer_name,rating,review_title,review_body,status,merchant_reply,version,created_at,updated_at) VALUES('74000000-0000-4000-8000-000000000075','${STORE_A}','${PRODUCT}','Ada',5,'Harika','Çok memnun kaldım.','approved','Teşekkür ederiz.',1,'2026-02-01','2026-02-01'),('74000000-0000-4000-8000-000000000076','${STORE_A}','${PRODUCT}','Ece',5,NULL,'Gizli bekleyen yorum.','pending',NULL,1,'2026-02-02','2026-02-02'),('74000000-0000-4000-8000-000000000077','${STORE_A}','${INACTIVE_PRODUCT}','Can',5,NULL,'Arşiv ürün yorumu.','approved',NULL,1,'2026-02-03','2026-02-03');
 INSERT INTO saas.merchant_admin_records(id,store_id,record_kind,name,config,status,version,created_at,updated_at) VALUES('77000000-0000-4000-8000-000000000075','${STORE_A}','seo_control','SEO','{"metaTitle":"Retail A","metaDescription":"Retail A ürünleri","allowIndex":true}','active',1,'2026-01-01','2026-01-01');
 INSERT INTO saas.catalog_admin_resources(id,store_id,resource_kind,name,slug,config,status,version,created_at,updated_at) VALUES('75000000-0000-4000-8000-000000000075','${STORE_A}','definition','Özellik','ozellik','{"role":"highlight","text":"Nefes alan dokuma"}','active',1,'2026-01-01','2026-01-01'),('75000000-0000-4000-8000-000000000076','${STORE_A}','attribute','Bakım','bakim','{"role":"materials_and_care","body":"Elde nazikçe yıkayın."}','active',1,'2026-01-01','2026-01-01'),('75000000-0000-4000-8000-000000000077','${STORE_A}','extra','Sertifika','sertifika','{"role":"certification","label":"Sorumlu üretim"}','active',1,'2026-01-01','2026-01-01');
 INSERT INTO saas.catalog_admin_resource_products(store_id,resource_id,product_id,position) VALUES('${STORE_A}','75000000-0000-4000-8000-000000000075','${PRODUCT}',0),('${STORE_A}','75000000-0000-4000-8000-000000000076','${PRODUCT}',0),('${STORE_A}','75000000-0000-4000-8000-000000000077','${PRODUCT}',0);COMMIT;`);
 await scenario("fixture creates two isolated active stores",()=>assert.equal(psql(box,"SELECT count(*) FROM saas.stores WHERE status='active';").stdout.trim(),"2"));
 await scenario("cross-store footer references reject publication",()=>{const category="76000000-0000-4000-8000-000000000075";psql(box,`SET ROLE celebix_saas_owner;INSERT INTO saas.catalog_categories(id,store_id,parent_id,name,slug,position,status,version,created_at,updated_at) VALUES('${category}','${STORE_B}',NULL,'Other','other',0,'active',1,'2026-01-01','2026-01-01');`);const value=config();value.footer.groups[0].links[0]={kind:"category",categoryId:category};assert.notEqual(save(box,value,"70000000-0000-4000-8000-000000000076",true).status,0);assert.equal(psql(box,"SELECT count(*) FROM saas.campaign_starter_publications;").stdout.trim(),"0");});
 await scenario("valid v2 publication commits once",()=>{assert.equal(save(box).stdout.trim().split("\n").at(-1),"saved");assert.equal(psql(box,"SELECT count(*) FROM saas.campaign_starter_publications;").stdout.trim(),"1");});
 await scenario("public retail home and storefront envelope preserve verified-domain indexing authority",()=>{const home=result(box,`saas.public_starter_retail_home('${STORE_A}','${HOST_A}','${NOW}')`),storefront=result(box,`saas.resolve_public_storefront('${HOST_A}','${NOW}')`),platformHome=result(box,`saas.public_starter_retail_home('${STORE_A}','${HOST_PLATFORM}','${NOW}')`),platformStorefront=result(box,`saas.resolve_public_storefront('${HOST_PLATFORM}','${NOW}')`);assert.equal(home.outcome,"found");assert.equal(home.payload.presentation.schemaVersion,3);assert.equal(home.payload.presentation.seo.allowIndex,true);assert.notEqual(home.payload.presentation.hero.body,"");assert.equal(storefront.outcome,"found");assert.equal(storefront.payload.presentation.schemaVersion,3);assert.equal(storefront.payload.presentation.seo.allowIndex,true);assert.deepEqual(storefront.payload.presentation,home.payload.presentation);assert.deepEqual(parsePublicStorefront(storefront.payload),storefront.payload);assert.equal(platformHome.outcome,"found");assert.equal(platformHome.payload.presentation.seo.allowIndex,false);assert.equal(platformStorefront.outcome,"found");assert.equal(platformStorefront.payload.presentation.seo.allowIndex,false);assert.equal(home.payload.presentation.sections.find(section=>section.kind==="testimonials").items.length,1);assert.doesNotMatch(JSON.stringify(home.payload),/storeId|reviewId|productId/);});
 await scenario("wrong hostname cannot read the published home",()=>assert.equal(result(box,`saas.public_starter_retail_home('${STORE_A}','${HOST_B}','${NOW}')`).outcome,"not_found"));
 await scenario("product detail bounds and deduplicates same-store reviewed merchandising",()=>{psql(box,`SET ROLE celebix_saas_owner;
 INSERT INTO saas.product_reviews(id,store_id,product_id,reviewer_name,rating,review_body,status,version,created_at,updated_at) SELECT pg_catalog.md5('retail-review-'||i)::uuid,'${STORE_A}','${PRODUCT}','Reviewer '||i,5,'Approved review '||i,'approved',1,'2026-03-01'::timestamptz+pg_catalog.make_interval(secs=>i),'2026-03-01'::timestamptz+pg_catalog.make_interval(secs=>i) FROM pg_catalog.generate_series(1,21) i;
 INSERT INTO saas.catalog_admin_resources(id,store_id,resource_kind,name,slug,config,status,version,created_at,updated_at) SELECT pg_catalog.md5('retail-highlight-'||i)::uuid,'${STORE_A}'::uuid,'definition','Highlight '||pg_catalog.lpad(i::text,2,'0'),'highlight-'||i,pg_catalog.jsonb_build_object('role','highlight','text','Highlight '||LEAST(i,12)),'active',1,'2026-01-01'::timestamptz,'2026-01-01'::timestamptz FROM pg_catalog.generate_series(1,13) i UNION ALL SELECT pg_catalog.md5('retail-certification-'||i)::uuid,'${STORE_A}'::uuid,'extra','Certification '||pg_catalog.lpad(i::text,2,'0'),'certification-'||i,pg_catalog.jsonb_build_object('role','certification','label','Certification '||LEAST(i,12)),'active',1,'2026-01-01'::timestamptz,'2026-01-01'::timestamptz FROM pg_catalog.generate_series(1,13) i;
 INSERT INTO saas.catalog_admin_resource_products(store_id,resource_id,product_id,position) SELECT '${STORE_A}',id,'${PRODUCT}',0 FROM saas.catalog_admin_resources WHERE store_id='${STORE_A}' AND (slug LIKE 'highlight-%' OR slug LIKE 'certification-%');`);const detail=result(box,`saas.public_starter_product_detail('${STORE_A}','${HOST_A}','${NOW}','keten-etek')`);assert.equal(detail.outcome,"found");assert.equal(detail.payload.merchandising.highlights.length,12);assert.equal(new Set(detail.payload.merchandising.highlights).size,12);assert.equal(detail.payload.merchandising.certifications.length,12);assert.equal(new Set(detail.payload.merchandising.certifications).size,12);assert.equal(detail.payload.reviews.length,20);assert.equal(detail.payload.reviews[0].reviewerName,"Reviewer 21");});
 await scenario("inactive products cannot receive a public detail",()=>assert.equal(result(box,`saas.public_starter_product_detail('${STORE_A}','${HOST_A}','${NOW}','arsiv-urun')`).outcome,"not_found"));
 await scenario("public newsletter subscribe stores normalized tenant data",()=>{const subscribed=result(box,`saas.public_newsletter_subscribe('${HOST_A}','${NOW}','Ada@Example.Test','starter-v1')`);assert.deepEqual(subscribed,{outcome:"subscribed",payload:{outcome:"subscribed"}});assert.equal(psql(box,`SELECT normalized_email FROM saas.storefront_newsletter_subscribers WHERE store_id='${STORE_A}';`).stdout.trim(),"ada@example.test");});
 await scenario("repeat subscribe is idempotent",()=>{result(box,`saas.public_newsletter_subscribe('${HOST_A}','${NOW}','ada@example.test','starter-v1')`);assert.equal(psql(box,`SELECT count(*)||'|'||version FROM saas.storefront_newsletter_subscribers WHERE store_id='${STORE_A}' GROUP BY version;`).stdout.trim(),"1|1");});
 await scenario("concurrent double submit persists one row",async()=>{const sql=`BEGIN;SET LOCAL ROLE celebix_saas_host_resolver;SELECT outcome FROM saas.public_newsletter_subscribe('${HOST_A}','${NOW}','race@example.test','starter-v1');COMMIT;`;await Promise.all([psqlAsync(box,sql),psqlAsync(box,sql)]);assert.equal(psql(box,`SELECT count(*) FROM saas.storefront_newsletter_subscribers WHERE store_id='${STORE_A}' AND normalized_email='race@example.test';`).stdout.trim(),"1");});
 await scenario("same email is independently tenant scoped",()=>{result(box,`saas.public_newsletter_subscribe('${HOST_B}','${NOW}','ada@example.test','starter-v1')`);assert.equal(psql(box,"SELECT count(DISTINCT store_id) FROM saas.storefront_newsletter_subscribers WHERE normalized_email='ada@example.test';").stdout.trim(),"2");});
 await scenario("unknown host discloses no store existence",()=>{assert.deepEqual(result(box,`saas.public_newsletter_subscribe('unknown.example.test','${NOW}','nobody@example.test','starter-v1')`),{outcome:"subscribed",payload:{outcome:"subscribed"}});assert.equal(psql(box,"SELECT count(*) FROM saas.storefront_newsletter_subscribers WHERE normalized_email='nobody@example.test';").stdout.trim(),"0");});
 await scenario("merchant list is durable-authority tenant bound",()=>{const output=psql(box,`BEGIN;SET LOCAL ROLE celebix_saas_app;SELECT outcome||'|'||result_payload::text FROM saas.merchant_newsletter_list(${authority()},'${NOW}',200);COMMIT;`).stdout.trim().split("\n").at(-1);assert.match(output,/^listed[|]/);const payload=JSON.parse(output.slice(output.indexOf("|")+1));assert.equal(payload.items.every(item=>["ada@example.test","race@example.test"].includes(item.email)),true);});
 await scenario("forced RLS and zero direct table grants remain intact",()=>{assert.equal(psql(box,"SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid='saas.storefront_newsletter_subscribers'::regclass;").stdout.trim(),"t");assert.notEqual(psql(box,"SET ROLE celebix_saas_app;SELECT count(*) FROM saas.storefront_newsletter_subscribers;",DB,true).status,0);assert.notEqual(psql(box,"SET ROLE celebix_saas_host_resolver;INSERT INTO saas.storefront_newsletter_subscribers VALUES(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);",DB,true).status,0);});
 await scenario("backup and restore preserve rows functions ACL and RLS",()=>{const dump=path.join(box.root,"retail.dump");command(box.tools.pg_dump,["-h",box.socket,"-p",String(box.port),"-U","postgres","-Fc","-f",dump,DB]);psql(box,`CREATE DATABASE ${RESTORE};`,"postgres");command(box.tools.pg_restore,["-h",box.socket,"-p",String(box.port),"-U","postgres","-d",RESTORE,dump]);assert.equal(psql(box,"SELECT count(*) FROM saas.storefront_newsletter_subscribers;",RESTORE).stdout.trim(),psql(box,"SELECT count(*) FROM saas.storefront_newsletter_subscribers;").stdout.trim());assert.equal(result(box,`saas.public_starter_product_detail('${STORE_A}','${HOST_A}','${NOW}','keten-etek')`,RESTORE).outcome,"found");assert.equal(psql(box,"SELECT relrowsecurity AND relforcerowsecurity FROM pg_class WHERE oid='saas.storefront_newsletter_subscribers'::regclass;",RESTORE).stdout.trim(),"t");});
 await scenario("rollback restores migration 074 after guarded v2 cleanup",()=>{psql(box,"SET ROLE celebix_saas_owner;DELETE FROM saas.campaign_starter_publications;ALTER TABLE saas.merchant_admin_events DISABLE TRIGGER merchant_admin_events_immutable;ALTER TABLE saas.merchant_admin_operations DISABLE TRIGGER merchant_admin_operations_immutable;DELETE FROM saas.merchant_admin_operations WHERE result_payload->>'kind'='starter_theme_composition';DELETE FROM saas.merchant_admin_events WHERE record_kind='starter_theme_composition';DELETE FROM saas.merchant_admin_records WHERE record_kind='starter_theme_composition';ALTER TABLE saas.merchant_admin_operations ENABLE TRIGGER merchant_admin_operations_immutable;ALTER TABLE saas.merchant_admin_events ENABLE TRIGGER merchant_admin_events_immutable;",RESTORE);apply(box,DOWN,RESTORE);assert.equal(psql(box,"SELECT to_regprocedure('saas.public_starter_retail_home(uuid,text,timestamp with time zone)') IS NULL;",RESTORE).stdout.trim(),"t");assert.equal(psql(box,"SELECT to_regclass('saas.storefront_newsletter_subscribers') IS NULL;",RESTORE).stdout.trim(),"t");});
 await scenario("reapply restores migration 075 and assertions",()=>{apply(box,UP,RESTORE);apply(box,ASSERTIONS,RESTORE);assert.equal(psql(box,"SELECT to_regprocedure('saas.public_starter_retail_home(uuid,text,timestamp with time zone)') IS NOT NULL;",RESTORE).stdout.trim(),"t");});
 await scenario("cleanup precondition has no leaked database sessions",()=>assert.equal(psql(box,"SELECT count(*) FROM pg_stat_activity WHERE datname=current_database() AND pid<>pg_backend_pid();").stdout.trim(),"0"));
 if(BUILT_BROWSER)await runBuiltBrowserAcceptance(box);
 assert.equal(completed,TOTAL);console.log(JSON.stringify({status:"PASS",postgresql:"16",scenarios:`${completed}/${TOTAL}`,backupRestore:"PASS",rollbackReapply:"PASS",concurrency:"PASS",rlsAcl:"PASS",externalConnections:0,cleanup:"PASS"}));
}finally{stop(box);}}
await main();
