export type DonorParityStatus = "complete" | "route_depth" | "provider_gated" | "legacy_rejected";
export type DonorParityAuthority = "orders" | "customers" | "catalog_admin" | "merchant_admin" | "analytics";
export const DONOR_PARITY_ACTIONS = Object.freeze([
  "read_dashboard",
  "open_supported_destination",
  "view_disabled_auth",
  "legacy_rejected",
  "list_records",
  "read_exact_record",
  "export_records",
  "create_record",
  "update_record",
  "archive_record",
  "transition_record",
  "add_customer_note",
  "set_customer_tags",
  "set_customer_segments",
  "update_order_shipping",
  "add_internal_order_note",
  "archive_internal_order_note",
  "cancel_payment_link",
  "copy_payment_link",
  "open_payment_link",
  "duplicate_payment_link",
  "reveal_payment_link_url",
  "prepare_payment_provider",
  "manage_product_variants",
  "manage_product_media",
  "moderate_product_review",
  "reply_to_product_review",
  "manage_inventory_locations",
  "transition_purchase_order",
  "transition_inventory_count",
  "transition_inventory_transfer",
  "preview_price",
  "read_preview",
  "print_snapshot",
  "prepare_provider_action",
  "cancel_provider_preparation",
  "prepare_import",
  "commit_import",
  "print_labels",
] as const);
export type DonorParityAction = (typeof DONOR_PARITY_ACTIONS)[number];
export type DonorParityEntry = Readonly<{
  donorPath: string;
  targetPath: string;
  status: DonorParityStatus;
  authority: DonorParityAuthority;
  evidenceTest: string;
  actionSet: readonly DonorParityAction[];
  rejectionRationale?: string;
}>;

const EVIDENCE = Object.freeze({
  dashboard: "apps/customer-panel/lib/panel-shell.test.ts#dashboard renders safe chrome, catalog, and durable order facts with truthful working actions",
  login: "apps/customer-panel/lib/routes.test.ts#login and logout remain disabled without a persistent session adapter",
  ordersList: "apps/customer-panel/lib/order-console.test.ts#order client performs strict frozen same-origin summary, list, and detail reads",
  orderDetail: "apps/customer-panel/lib/order-console.test.ts#order client mutations use exact relative paths, JSON, idempotency, and safe frozen results",
  orderPrint: "apps/customer-panel/lib/order-console.test.ts#order print route projects immutable order snapshots without panel authority",
  quickLinks: "apps/customer-panel/lib/quick-link-ui/client.test.ts#quick-link client uses exact same-origin routes, idempotency, and allowed create intent",
  abandonedCarts: "apps/customer-panel/lib/abandoned-cart-ui/client.test.ts#client performs exact same-origin summary list and detail reads",
  customer: "apps/customer-panel/lib/customer-ui/route-behavior.test.ts#customer route matrix invokes actual list detail edit and new pages through real clients and handlers",
  customerTaxonomy: "apps/customer-panel/lib/customer-ui/taxonomy-route-behavior.test.ts#customer taxonomy routes invoke actual pages, production consoles, clients, and handlers across truth and mutation states",
  productList: "apps/customer-panel/lib/product-console.test.ts#create, archive, variant and conflict flows keep rendered versions and navigate safely",
  productDetail: "apps/customer-panel/lib/catalog-ui/client.test.ts#every mutation uses an exact UUID idempotency key and JSON without store authority",
  catalogResource: "apps/customer-panel/lib/catalog-admin-ui/client.test.ts#catalog resource family client executes exact CRUD for every finite resource kind",
  catalogPreview: "apps/customer-panel/lib/catalog-admin-ui/resource-route.test.ts#extra preview renders untrusted option text and minor-unit prices without unsafe HTML",
  catalogReviews: "apps/customer-panel/lib/catalog-admin-ui/client.test.ts#client executes review list moderation with reply and durable import reads",
  catalogImport: "apps/customer-panel/lib/catalog-admin-import-preparation.test.ts#prepares persisted rows before an explicit versioned commit and refreshes the original preview ID",
  catalogLabels: "apps/customer-panel/lib/catalog-admin-console.test.ts#tag and barcode consoles are fixed read-only catalog surfaces",
  pricing: "apps/customer-panel/lib/pricing-ui/client.test.ts#pricing client exposes only five finite same-origin operations with one generated operation ID per mutation",
  purchasing: "apps/customer-panel/lib/inventory-console.test.ts#empty-store form submission creates canonical purchase and can continue its real lifecycle",
  counting: "apps/customer-panel/lib/inventory-console.test.ts#shared form boundary owns empty-store count create start and commit without duplicate mutations",
  transfers: "apps/customer-panel/lib/inventory-console.test.ts#shared form boundary owns empty-store transfer create dispatch and receive without duplicate mutations",
  legacy: "apps/customer-panel/lib/panel-ui/navigation.test.ts#legacy donor spellings stay inert while canonical safe targets remain navigable",
  merchantHub: "apps/customer-panel/lib/merchant-admin-ui/route-behavior.test.ts#static merchant hubs invoke actual pages and expose only canonical destination links",
  merchant: "apps/customer-panel/lib/merchant-admin-ui/route-behavior.test.ts#merchant route matrix invokes every actual page, production console, client, and handler across truth and mutation states",
  merchantRecord: "apps/customer-panel/lib/merchant-admin-ui/route-behavior.test.ts#merchant non-default route matrix invokes nine actual pages and exact create update handlers across success conflict and replay",
  paymentSettings: "apps/customer-panel/lib/routes.test.ts#dedicated payment settings route validates hints and retires generic editors",
  marketing: "apps/customer-panel/lib/merchant-admin-ui/route-behavior.test.ts#merchant route matrix invokes every actual page, production console, client, and handler across truth and mutation states",
  provider: "apps/customer-panel/lib/merchant-admin-ui/route-behavior.test.ts#merchant route matrix invokes every actual page, production console, client, and handler across truth and mutation states",
  seo: "apps/customer-panel/lib/merchant-admin-ui/route-behavior.test.ts#merchant route matrix invokes every actual page, production console, client, and handler across truth and mutation states",
  ai: "apps/customer-panel/lib/merchant-admin-ui/route-behavior.test.ts#merchant route matrix invokes every actual page, production console, client, and handler across truth and mutation states",
});

const ACTIONS = Object.freeze({
  dashboard: Object.freeze(["read_dashboard", "open_supported_destination"] as const),
  disabledAuth: Object.freeze(["view_disabled_auth"] as const),
  legacy: Object.freeze(["legacy_rejected"] as const),
  staticHub: Object.freeze(["open_supported_destination"] as const),
  recordHub: Object.freeze(["list_records", "open_supported_destination"] as const),
  create: Object.freeze(["create_record"] as const),
  editNoArchive: Object.freeze(["read_exact_record", "update_record"] as const),
  crud: Object.freeze(["list_records", "read_exact_record", "create_record", "update_record", "archive_record"] as const),
  orderList: Object.freeze(["list_records", "read_exact_record"] as const),
  orderDetail: Object.freeze(["read_exact_record", "transition_record", "update_order_shipping", "add_internal_order_note", "archive_internal_order_note"] as const),
  quickLinks: Object.freeze(["list_records", "create_record", "cancel_payment_link", "copy_payment_link", "open_payment_link", "duplicate_payment_link", "reveal_payment_link_url", "prepare_payment_provider"] as const),
  abandonedCarts: Object.freeze(["list_records", "read_exact_record"] as const),
  provider: Object.freeze(["list_records", "read_exact_record", "create_record", "update_record", "archive_record", "prepare_provider_action", "cancel_provider_preparation"] as const),
  customerList: Object.freeze(["list_records", "read_exact_record", "create_record", "export_records"] as const),
  customerDetail: Object.freeze(["read_exact_record", "update_record", "archive_record", "add_customer_note", "set_customer_tags", "set_customer_segments"] as const),
  customerTaxonomy: Object.freeze(["list_records", "create_record"] as const),
  productList: Object.freeze(["list_records", "read_exact_record", "create_record", "archive_record"] as const),
  productDetail: Object.freeze(["read_exact_record", "update_record", "manage_product_variants", "manage_product_media"] as const),
  reviews: Object.freeze(["list_records", "moderate_product_review", "reply_to_product_review"] as const),
  pricing: Object.freeze(["list_records", "read_exact_record", "create_record", "update_record", "archive_record", "transition_record", "preview_price"] as const),
  purchasing: Object.freeze(["list_records", "read_exact_record", "create_record", "update_record", "transition_purchase_order"] as const),
  counting: Object.freeze(["list_records", "read_exact_record", "create_record", "update_record", "transition_inventory_count"] as const),
  transfers: Object.freeze(["list_records", "read_exact_record", "create_record", "update_record", "manage_inventory_locations", "transition_inventory_transfer"] as const),
  preview: Object.freeze(["read_exact_record", "read_preview"] as const),
  print: Object.freeze(["read_exact_record", "print_snapshot"] as const),
  import: Object.freeze(["prepare_import", "commit_import"] as const),
  labels: Object.freeze(["list_records", "print_labels"] as const),
});

function entry(
  donorPath: string,
  targetPath: string,
  status: DonorParityStatus,
  authority: DonorParityAuthority,
  actionSet: readonly DonorParityAction[],
  evidenceTest: string,
): DonorParityEntry {
  const rejectionRationale = donorPath === "/ayarlar/ana-sayfa-vitrini"
    ? "duplicate storefront showcase; collections is the canonical safe target"
    : donorPath === "/muhasabe"
      ? "typo spelling; accounting is the canonical safe target"
      : donorPath === "/pazarlama/lucky-wheel"
        ? "duplicate lucky-wheel workflow; discounts is the canonical safe target"
        : undefined;
  return Object.freeze({ donorPath, targetPath, status, authority, evidenceTest, actionSet, ...(rejectionRationale ? { rejectionRationale } : {}) });
}

export const HEMENAKU_DONOR_PARITY = Object.freeze([
  entry("", "/", "complete", "catalog_admin", ACTIONS.dashboard, EVIDENCE.dashboard),
  entry("/ayarlar", "/settings", "complete", "merchant_admin", ACTIONS.staticHub, EVIDENCE.merchantHub),
  entry("/ayarlar/ana-sayfa-vitrini", "/products/collections", "legacy_rejected", "catalog_admin", ACTIONS.legacy, EVIDENCE.legacy),
  entry("/ayarlar/bildirimler", "/settings/notifications", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.merchant),
  entry("/ayarlar/dil", "/settings/language", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.merchant),
  entry("/ayarlar/genel", "/settings/general", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.merchant),
  entry("/ayarlar/hero-banner", "/settings/hero-banner", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.merchant),
  entry("/ayarlar/kargo", "/settings/shipping", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.merchant),
  entry("/ayarlar/marquee", "/settings/marquee", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.merchant),
  entry("/ayarlar/odeme", "/settings/payment", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.paymentSettings),
  entry("/ayarlar/odeme/[id]/duzenle", "/settings/payment/[recordId]/edit", "complete", "merchant_admin", ACTIONS.editNoArchive, EVIDENCE.paymentSettings),
  entry("/ayarlar/odeme/yeni", "/settings/payment/new", "complete", "merchant_admin", ACTIONS.create, EVIDENCE.paymentSettings),
  entry("/ayarlar/promosyon-banner", "/settings/promotion-banner", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.merchant),
  entry("/ayarlar/tasarim", "/settings/design", "complete", "merchant_admin", ACTIONS.staticHub, EVIDENCE.merchantHub),
  entry("/ayarlar/yapay-zeka", "/settings/artificial-intelligence", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.ai),
  entry("/cms", "/content", "complete", "merchant_admin", ACTIONS.staticHub, EVIDENCE.merchantHub),
  entry("/cms/blog", "/content/blog", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.merchant),
  entry("/cms/blog/[id]", "/content/blog/[recordId]/edit", "complete", "merchant_admin", ACTIONS.editNoArchive, EVIDENCE.merchantRecord),
  entry("/cms/blog/yeni", "/content/blog/new", "complete", "merchant_admin", ACTIONS.create, EVIDENCE.merchantRecord),
  entry("/cms/politikalar", "/content/policies", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.merchant),
  entry("/cms/politikalar/[slug]", "/content/policies/[recordId]/edit", "complete", "merchant_admin", ACTIONS.editNoArchive, EVIDENCE.merchantRecord),
  entry("/cms/sayfalar", "/content/pages", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.merchant),
  entry("/cms/sayfalar/[id]", "/content/pages/[recordId]/edit", "complete", "merchant_admin", ACTIONS.editNoArchive, EVIDENCE.merchantRecord),
  entry("/cms/sayfalar/yeni", "/content/pages/new", "complete", "merchant_admin", ACTIONS.create, EVIDENCE.merchantRecord),
  entry("/indirimler", "/discounts", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.merchant),
  entry("/indirimler/[id]/duzenle", "/discounts/[recordId]/edit", "complete", "merchant_admin", ACTIONS.editNoArchive, EVIDENCE.merchantRecord),
  entry("/indirimler/sans-carki", "/discounts/lucky-wheel", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.merchant),
  entry("/indirimler/yeni", "/discounts/new", "complete", "merchant_admin", ACTIONS.create, EVIDENCE.merchantRecord),
  entry("/login", "/login", "complete", "merchant_admin", ACTIONS.disabledAuth, EVIDENCE.login),
  entry("/markets", "/marketplaces", "provider_gated", "merchant_admin", ACTIONS.provider, EVIDENCE.provider),
  entry("/muhasabe", "/accounting", "legacy_rejected", "merchant_admin", ACTIONS.legacy, EVIDENCE.legacy),
  entry("/muhasebe", "/accounting", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.merchant),
  entry("/muhasebe/fatura-entegrasyonu", "/accounting/invoicing-integration", "provider_gated", "merchant_admin", ACTIONS.provider, EVIDENCE.provider),
  entry("/musteriler", "/customers", "complete", "customers", ACTIONS.customerList, EVIDENCE.customer),
  entry("/musteriler/[id]", "/customers/[customerId]", "complete", "customers", ACTIONS.customerDetail, EVIDENCE.customer),
  entry("/musteriler/[id]/duzenle", "/customers/[customerId]/edit", "complete", "customers", ACTIONS.editNoArchive, EVIDENCE.customer),
  entry("/musteriler/etiketler", "/customers/tags", "complete", "customers", ACTIONS.customerTaxonomy, EVIDENCE.customerTaxonomy),
  entry("/musteriler/segmentler", "/customers/segments", "complete", "customers", ACTIONS.customerTaxonomy, EVIDENCE.customerTaxonomy),
  entry("/musteriler/yeni", "/customers/new", "complete", "customers", ACTIONS.create, EVIDENCE.customer),
  entry("/pazarlama", "/marketing", "complete", "merchant_admin", ACTIONS.recordHub, EVIDENCE.marketing),
  entry("/pazarlama/email", "/marketing/email", "provider_gated", "merchant_admin", ACTIONS.provider, EVIDENCE.provider),
  entry("/pazarlama/lucky-wheel", "/discounts/lucky-wheel", "legacy_rejected", "merchant_admin", ACTIONS.legacy, EVIDENCE.legacy),
  entry("/pazarlama/phone", "/marketing/phone", "provider_gated", "merchant_admin", ACTIONS.provider, EVIDENCE.provider),
  entry("/pazarlama/whatsapp", "/marketing/whatsapp", "provider_gated", "merchant_admin", ACTIONS.provider, EVIDENCE.provider),
  entry("/seo-killer", "/seo", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.seo),
  entry("/seo-killer/geo-optimizasyon", "/seo/geo-optimization", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.seo),
  entry("/seo-killer/hizli-index", "/seo/fast-indexing", "provider_gated", "merchant_admin", ACTIONS.provider, EVIDENCE.provider),
  entry("/seo-killer/ic-linkleme", "/seo/internal-linking", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.seo),
  entry("/seo-killer/icerikler", "/seo/content", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.seo),
  entry("/seo-killer/kategoriler", "/seo/categories", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.seo),
  entry("/seo-killer/kod-entegrasyonlari", "/seo/code-integrations", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.seo),
  entry("/seo-killer/sayfalar", "/seo/pages", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.seo),
  entry("/seo-killer/sitemap", "/seo/sitemap", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.seo),
  entry("/seo-killer/sosyal-onizleme", "/seo/social-preview", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.seo),
  entry("/seo-killer/urunler", "/seo/products", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.seo),
  entry("/siparisler", "/orders", "complete", "orders", ACTIONS.orderList, EVIDENCE.ordersList),
  entry("/siparisler/[id]", "/orders/[orderId]", "complete", "orders", ACTIONS.orderDetail, EVIDENCE.orderDetail),
  entry("/siparisler/[id]/yazdir", "/orders/[orderId]/print", "complete", "orders", ACTIONS.print, EVIDENCE.orderPrint),
  entry("/siparisler/hizli-siparis", "/orders/quick-links", "complete", "orders", ACTIONS.quickLinks, EVIDENCE.quickLinks),
  entry("/siparisler/sepet-terk", "/orders/abandoned-carts", "complete", "orders", ACTIONS.abandonedCarts, EVIDENCE.abandonedCarts),
  entry("/urunler", "/products", "complete", "catalog_admin", ACTIONS.productList, EVIDENCE.productList),
  entry("/urunler/[id]/duzenle", "/products/[productId]", "complete", "catalog_admin", ACTIONS.productDetail, EVIDENCE.productDetail),
  entry("/urunler/barkod-etiketleri", "/products/barcode-labels", "complete", "catalog_admin", ACTIONS.labels, EVIDENCE.catalogLabels),
  entry("/urunler/ekstralar", "/products/extras", "complete", "catalog_admin", ACTIONS.crud, EVIDENCE.catalogResource),
  entry("/urunler/ekstralar/[id]", "/products/extras/[resourceId]/edit", "complete", "catalog_admin", ACTIONS.editNoArchive, EVIDENCE.catalogResource),
  entry("/urunler/ekstralar/[id]/onizleme", "/products/extras/[resourceId]/preview", "complete", "catalog_admin", ACTIONS.preview, EVIDENCE.catalogPreview),
  entry("/urunler/ekstralar/yeni", "/products/extras/new", "complete", "catalog_admin", ACTIONS.create, EVIDENCE.catalogResource),
  entry("/urunler/etiketler", "/products/tags", "complete", "catalog_admin", ACTIONS.crud, EVIDENCE.catalogResource),
  entry("/urunler/fiyat-listeleri", "/products/price-lists", "complete", "catalog_admin", ACTIONS.pricing, EVIDENCE.pricing),
  entry("/urunler/koleksiyonlar", "/products/collections", "complete", "catalog_admin", ACTIONS.crud, EVIDENCE.catalogResource),
  entry("/urunler/koleksiyonlar/[id]/duzenle", "/products/collections/[resourceId]/edit", "complete", "catalog_admin", ACTIONS.editNoArchive, EVIDENCE.catalogResource),
  entry("/urunler/koleksiyonlar/yeni", "/products/collections/new", "complete", "catalog_admin", ACTIONS.create, EVIDENCE.catalogResource),
  entry("/urunler/markalar", "/products/brands", "complete", "catalog_admin", ACTIONS.crud, EVIDENCE.catalogResource),
  entry("/urunler/nitelikler", "/products/attributes", "complete", "catalog_admin", ACTIONS.crud, EVIDENCE.catalogResource),
  entry("/urunler/nitelikler/[id]/duzenle", "/products/attributes/[resourceId]/edit", "complete", "catalog_admin", ACTIONS.editNoArchive, EVIDENCE.catalogResource),
  entry("/urunler/nitelikler/yeni", "/products/attributes/new", "complete", "catalog_admin", ACTIONS.create, EVIDENCE.catalogResource),
  entry("/urunler/otomatik-yukle", "/products/auto-import", "complete", "catalog_admin", ACTIONS.import, EVIDENCE.catalogImport),
  entry("/urunler/satin-alma", "/products/purchasing", "complete", "catalog_admin", ACTIONS.purchasing, EVIDENCE.purchasing),
  entry("/urunler/shopify-donusturucu", "/products/shopify-converter", "complete", "catalog_admin", ACTIONS.import, EVIDENCE.catalogImport),
  entry("/urunler/stok-sayimi", "/products/inventory-counts", "complete", "catalog_admin", ACTIONS.counting, EVIDENCE.counting),
  entry("/urunler/tanimlamalar", "/products/definitions", "complete", "catalog_admin", ACTIONS.crud, EVIDENCE.catalogResource),
  entry("/urunler/toplu-yukle", "/products/bulk-upload", "complete", "catalog_admin", ACTIONS.import, EVIDENCE.catalogImport),
  entry("/urunler/transferler", "/products/transfers", "complete", "catalog_admin", ACTIONS.transfers, EVIDENCE.transfers),
  entry("/urunler/yeni", "/products/new", "complete", "catalog_admin", ACTIONS.create, EVIDENCE.productList),
  entry("/urunler/yorumlar", "/products/reviews", "complete", "catalog_admin", ACTIONS.reviews, EVIDENCE.catalogReviews),
  entry("/yoneticiler", "/settings/administrators", "complete", "merchant_admin", ACTIONS.crud, EVIDENCE.merchant),
] as const satisfies readonly DonorParityEntry[]);

export function getDonorParityEntry(donorPath: string) {
  return HEMENAKU_DONOR_PARITY.find((candidate) => candidate.donorPath === donorPath);
}
