export const GOOGLE_MARKETING_SERVICES = ['gtm','ads','search_console'] as const;
export type GoogleMarketingService = typeof GOOGLE_MARKETING_SERVICES[number];
export type GoogleMarketingSelection = Readonly<{accountId:string;resourceId:string;resourceName:string;tagId?:string;conversionLabel?:string;create?:boolean}>;
export type GoogleMarketingConnection = Readonly<{service:GoogleMarketingService;version:number;status:'disconnected'|'connected'|'needs_reconnect'|'error';googleEmail:string|null;selection:GoogleMarketingSelection|null;lastCheckedAt:string|null;errorCode:string|null}>;
export type GoogleMarketingResourceOption = Readonly<{id:string;name:string;parentId?:string;tagId?:string;conversionLabel?:string}>;
export type GoogleMarketingResources = Readonly<{accounts:readonly GoogleMarketingResourceOption[];resources:readonly GoogleMarketingResourceOption[];nextPageToken?:string}>;
export type GoogleMarketingOverview = Readonly<{storeDomain:string;oauthConfigured:boolean;connections:readonly GoogleMarketingConnection[]}>;
export type PublicGoogleMarketingProjection = Readonly<{gtmContainerId:string|null;ads:Readonly<{tagId:string;conversionLabel:string}>|null;verificationToken:string|null}>;
function invalid():never {throw new TypeError('google_marketing_invalid');}
function object(value:unknown,required:readonly string[],optional:readonly string[]=[]):Record<string,unknown>{
 if(!value||typeof value!=='object'||Array.isArray(value))invalid();const descriptors=Object.getOwnPropertyDescriptors(value);const keys=Reflect.ownKeys(value);
 if(keys.some(k=>typeof k!=='string'||![...required,...optional].includes(k))||required.some(k=>!Object.hasOwn(descriptors,k)))invalid();
 const out:Record<string,unknown>={};for(const key of keys){if(typeof key!=='string')invalid();const descriptor=descriptors[key];if(!descriptor||!('value'in descriptor)||!descriptor.enumerable)invalid();out[key]=descriptor.value;}return out;
}
function text(value:unknown,max=300):string {if(typeof value!=='string'||!value.trim()||value.length>max||/[\x00-\x1f\x7f<>]/u.test(value))invalid();return value;}
function tag(value:unknown):string {const str=text(value,40);if(!/^(GTM-[A-Z0-9]{4,24}|AW-[0-9]{4,20})$/.test(str))invalid();return str;}
function label(value:unknown):string {const str=text(value,128);if(!/^[A-Za-z0-9_-]{1,128}$/.test(str))invalid();return str;}
export function parseGoogleMarketingService(value:unknown):GoogleMarketingService {if(!GOOGLE_MARKETING_SERVICES.includes(value as GoogleMarketingService))invalid();return value as GoogleMarketingService;}
export function parseGoogleMarketingSelection(value:unknown):GoogleMarketingSelection {const v=object(value,['accountId','resourceId','resourceName'],['tagId','conversionLabel','create']);return Object.freeze({accountId:text(v.accountId,160),resourceId:text(v.resourceId,512),resourceName:text(v.resourceName,160),...(v.tagId!==undefined?{tagId:tag(v.tagId)}:{}),...(v.conversionLabel!==undefined?{conversionLabel:label(v.conversionLabel)}:{}),...(v.create!==undefined?{create:typeof v.create==='boolean'?v.create:invalid()}:{} )});}
export function parseGoogleMarketingConnection(value:unknown):GoogleMarketingConnection {const v=object(value,['service','version','status','googleEmail','selection','lastCheckedAt','errorCode']);if(!Number.isSafeInteger(v.version)||(v.version as number)<0||!['disconnected','connected','needs_reconnect','error'].includes(v.status as string))invalid();return Object.freeze({service:parseGoogleMarketingService(v.service),version:v.version as number,status:v.status as GoogleMarketingConnection['status'],googleEmail:v.googleEmail===null?null:text(v.googleEmail,254),selection:v.selection===null?null:parseGoogleMarketingSelection(v.selection),lastCheckedAt:v.lastCheckedAt===null?null:(typeof v.lastCheckedAt==='string'&&Number.isFinite(Date.parse(v.lastCheckedAt))?v.lastCheckedAt:invalid()),errorCode:v.errorCode===null?null:label(v.errorCode)});}
export function parsePublicGoogleMarketingProjection(value:unknown):PublicGoogleMarketingProjection {const v=object(value,['gtmContainerId','ads','verificationToken']);let ads:PublicGoogleMarketingProjection['ads']=null;if(v.ads!==null){const a=object(v.ads,['tagId','conversionLabel']);const id=tag(a.tagId);if(!id.startsWith('AW-'))invalid();ads=Object.freeze({tagId:id,conversionLabel:label(a.conversionLabel)});}const gtm=v.gtmContainerId===null?null:tag(v.gtmContainerId);if(gtm&&!gtm.startsWith('GTM-'))invalid();return Object.freeze({gtmContainerId:gtm,ads,verificationToken:v.verificationToken===null?null:label(v.verificationToken)});}
