import { randomBytes } from 'node:crypto';
import { normalizeRestockEmail,parseRestockAlertsConfig,type RestockAlertsConfig } from '../../../saas-contracts/src/restock-alerts/index.ts';
import type { TenantContext } from '@celebix/saas-contracts';
import { acquirePostgresClient,type PostgresPoolLike,type PostgresTimeoutOptions } from '../postgres/pool.ts';
import { catalogAuthority } from '../catalog/validation.ts';

export type RestockRepositoryOptions=Readonly<{pool:PostgresPoolLike;role:'celebix_saas_host_resolver'|'celebix_saas_workflow'|'celebix_saas_app';timeouts:PostgresTimeoutOptions}>;
export type RestockDelivery=Readonly<{id:string;leaseId:string;to:string;storeName:string;kind:'confirmation'|'stock';productTitle:string;variantTitle:string;productUrl:string;confirmUrl:string;cancelUrl:string;idempotencyKey:string}>;
export type RestockClaim=Readonly<{id:string;leaseId:string}>;
export type RestockStats=Readonly<{awaitingConfirmation:number;pendingConfirmed:number;sent:number;failed:number;recent:readonly Readonly<{productTitle:string;variantTitle:string;emailMask:string;status:string;error:string|null;createdAt:string}>[]}>;
export interface RestockWorkerRepository {claim(input:Readonly<{now:Date;workerId:string;limit:number}>):Promise<readonly RestockClaim[]>;authorize(input:Readonly<{id:string;leaseId:string;workerId:string;now:Date}>):Promise<RestockDelivery|null>;finish(input:Readonly<{id:string;leaseId:string;workerId:string;now:Date;result:'accepted'|'retry'|'failed';error:string|null}>):Promise<void>}
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u,TOKEN=/^[A-Za-z0-9_-]{43}$/u,DIGEST=/^[a-f0-9]{64}$/u,WORKER=/^[A-Za-z0-9._-]{1,128}$/u;
function valid(value:unknown,expression:RegExp):string{if(typeof value!=='string'||!expression.test(value))throw Error('restock_invalid_input');return value;}
function date(value:Date){if(!(value instanceof Date)||!Number.isFinite(value.getTime()))throw Error('restock_invalid_input');return value;}
function hostname(value:string){if(typeof value!=='string'||value!==value.toLowerCase()||value.length>253||!/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/u.test(value))throw Error('restock_invalid_input');return value;}
class Repository{
  constructor(protected options:RestockRepositoryOptions,role:RestockRepositoryOptions['role']){if(options.role!==role||typeof options.pool?.connect!=='function'||Object.values(options.timeouts).some(x=>!Number.isSafeInteger(x)||x<1||x>60000))throw Error('restock_unavailable');}
  protected async query(name:string,args:readonly unknown[],casts:readonly string[]):Promise<unknown>{const client=await acquirePostgresClient(this.options.pool,this.options.timeouts.poolCheckoutMs);let began=false,destroy=false;try{await client.query('BEGIN');began=true;for(const[key,value]of [['statement_timeout',this.options.timeouts.statementMs],['lock_timeout',this.options.timeouts.lockMs],['idle_in_transaction_session_timeout',this.options.timeouts.idleTransactionMs]] as const)await client.query('SELECT pg_catalog.set_config($1,$2,true)',[key,`${value}ms`]);await client.query(`SET LOCAL ROLE ${this.options.role}`);const selected=await client.query(`SELECT outcome,result_payload FROM saas.${name}(${casts.map((type,index)=>`$${index+1}::${type}`).join(',')})`,[...args]);if(selected.rows.length!==1||selected.rowCount!==1)throw Error('restock_unavailable');const row=selected.rows[0] as {outcome:string;result_payload:unknown};if(row.outcome!=='ok')throw Error(`restock_${row.outcome}`);await client.query('COMMIT');began=false;return row.result_payload;}catch(error){if(began)try{await client.query('ROLLBACK');}catch{destroy=true;}throw error;}finally{client.release(destroy||undefined);}}
}
export class PostgresPublicRestockRepository extends Repository{
 constructor(options:RestockRepositoryOptions){super(options,'celebix_saas_host_resolver');}
 async getForHost(input:Readonly<{hostname:string;now:Date}>):Promise<Readonly<{storeId:string;config:RestockAlertsConfig|null}>>{const row=await this.query('public_restock_alerts_get',[hostname(input.hostname),date(input.now)],['text','timestamptz']) as {storeId:string;config:unknown};return Object.freeze({storeId:valid(row.storeId,UUID),config:row.config===null?null:parseRestockAlertsConfig(row.config)});}
 async subscribe(input:Readonly<{hostname:string;variantId:string;email:string;consent:true;clientHash:string;now:Date}>):Promise<Readonly<{outcome:'accepted'}>>{if(input.consent!==true)throw Error('restock_invalid_input');await this.query('restock_subscribe',[hostname(input.hostname),valid(input.variantId,UUID),normalizeRestockEmail(input.email),valid(input.clientHash,DIGEST),randomBytes(32).toString('base64url'),randomBytes(32).toString('base64url'),date(input.now)],['text','uuid','text','text','text','text','timestamptz']);return Object.freeze({outcome:'accepted'});}
 async manage(input:Readonly<{hostname:string;token:string;action:'confirm'|'cancel';now:Date}>):Promise<void>{if(!['confirm','cancel'].includes(input.action))throw Error('restock_invalid_input');await this.query('restock_manage',[hostname(input.hostname),valid(input.token,TOKEN),input.action,date(input.now)],['text','text','text','timestamptz']);}
}
export class PostgresRestockWorkerRepository extends Repository implements RestockWorkerRepository{
 constructor(options:RestockRepositoryOptions){super(options,'celebix_saas_workflow');}
 async claim(input:Readonly<{now:Date;workerId:string;limit:number}>):Promise<readonly RestockClaim[]>{if(!Number.isSafeInteger(input.limit)||input.limit<1||input.limit>25)throw Error('restock_invalid_input');const result=await this.query('restock_claim',[date(input.now),valid(input.workerId,WORKER),input.limit],['timestamptz','text','integer']);if(!Array.isArray(result)||result.length>input.limit)throw Error('restock_unavailable');return Object.freeze(result.map(row=>Object.freeze({id:valid(row.id,UUID),leaseId:valid(row.leaseId,UUID)})));}
 async authorize(input:Readonly<{id:string;leaseId:string;workerId:string;now:Date}>):Promise<RestockDelivery|null>{const row=await this.query('restock_authorize',[valid(input.id,UUID),valid(input.leaseId,UUID),valid(input.workerId,WORKER),date(input.now)],['uuid','uuid','text','timestamptz']);if(row===null)return null;const value=row as RestockDelivery;if(valid(value.id,UUID)!==input.id||valid(value.leaseId,UUID)!==input.leaseId||!['confirmation','stock'].includes(value.kind))throw Error('restock_unavailable');normalizeRestockEmail(value.to);for(const link of[value.productUrl,value.confirmUrl,value.cancelUrl]){const url=new URL(link);if(url.protocol!=='https:'||url.username||url.password||url.port)throw Error('restock_unavailable');}if(new URL(value.confirmUrl).origin!==new URL(value.cancelUrl).origin||new URL(value.productUrl).origin!==new URL(value.cancelUrl).origin||value.idempotencyKey!==`restock-${value.kind}/v1/${value.id}`)throw Error('restock_unavailable');return Object.freeze({...value});}
 async finish(input:Readonly<{id:string;leaseId:string;workerId:string;now:Date;result:'accepted'|'retry'|'failed';error:string|null}>):Promise<void>{if(!['accepted','retry','failed'].includes(input.result)||input.error!==null&&!/^[a-z0-9_]{1,64}$/u.test(input.error))throw Error('restock_invalid_input');await this.query('restock_finish',[valid(input.id,UUID),valid(input.leaseId,UUID),valid(input.workerId,WORKER),date(input.now),input.result,input.error],['uuid','uuid','text','timestamptz','text','text']);}
}
export class PostgresRestockAdminRepository extends Repository{
 constructor(options:RestockRepositoryOptions){super(options,'celebix_saas_app');}
 async getStats(input:Readonly<{tenantContext:TenantContext;now:Date}>):Promise<RestockStats>{const a=catalogAuthority(input.tenantContext,input.now),value=await this.query('restock_alerts_stats',[a.storeId,a.principalId,a.membershipId,a.planId,a.planCode,a.planVersion,a.now],['uuid','uuid','uuid','uuid','text','bigint','timestamptz']) as RestockStats;if([value.awaitingConfirmation,value.pendingConfirmed,value.sent,value.failed].some(x=>!Number.isSafeInteger(x)||x<0)||!Array.isArray(value.recent)||value.recent.length>20||value.recent.some(x=>!x.emailMask.includes('•••')||x.emailMask.split('@')[0]!.length>4))throw Error('restock_unavailable');return Object.freeze({...value,recent:Object.freeze(value.recent.map(x=>Object.freeze({...x})))});}
}
