import { parseCatalogAdminImportJob, parseCatalogAdminMutationResult, parseCatalogAdminResource, parseCatalogImportPreview, parseProductReview, type CatalogAdminImportJob, type CatalogAdminMutationResult, type CatalogAdminResource, type CatalogImportPreview, type ProductReview, type TenantContext } from "@celebix/saas-contracts";
import { acquirePostgresClient, type PostgresClientLike } from "../postgres/pool.ts";
import type { ValidatedCatalogAuthority } from "../catalog/validation.ts";
import { catalogAdminFingerprint } from "./canonical.ts";
import { CATALOG_ADMIN_ERROR_CODES, CatalogAdminRepositoryError, type CatalogAdminErrorCode } from "./errors.ts";
import type { ArchiveCatalogAdminResourceInput, CatalogAdminAuthorityInput, CatalogAdminRepository, CommitCatalogImportPreviewInput, GetCatalogAdminResourceInput, GetCatalogImportPreviewInput, ImportCatalogProductsInput, ListCatalogAdminResourcesInput, ListProductReviewsInput, ModerateProductReviewInput, PostgresCatalogAdminRepositoryOptions, PrepareCatalogImportPreviewInput, SaveCatalogAdminResourceInput } from "./types.ts";
import { catalogAdminConfig, catalogAdminImportRows, catalogAdminKind, catalogAdminReviewStatus, catalogAdminSlug, catalogAdminText, catalogAdminUuid, catalogAdminVersion, catalogAuthority, catalogImportDigest, catalogImportFormat, exactCatalogAdminInput, uniqueCatalogIds } from "./validation.ts";

type Spec = Readonly<{ text: string; values: unknown[] }>;
type RecoverParser<T> = (value: unknown, replayed: boolean) => T;
const CODES = new Set<string>(CATALOG_ADMIN_ERROR_CODES);
function unavailable(): CatalogAdminRepositoryError { return new CatalogAdminRepositoryError("unavailable"); }
function timeout(value: number) { if (!Number.isSafeInteger(value) || value < 1 || value > 60_000) throw unavailable(); return `${value}ms`; }
function release(client: PostgresClientLike, destroy = false) { try { client.release(destroy || undefined); } catch {} }
function payload(value: unknown, keys: readonly string[]) { if (typeof value !== "object" || value === null || Array.isArray(value)) throw unavailable(); const result = value as Record<string, unknown>; if (Object.keys(result).sort().join(",") !== [...keys].sort().join(",")) throw unavailable(); return result; }
function row(value: Readonly<{ rows: unknown[]; rowCount?: number | null }>) { if (value.rowCount !== 1 || value.rows.length !== 1) throw unavailable(); const parsed = payload(value.rows[0], ["outcome", "result_payload"]); if (typeof parsed.outcome !== "string") throw unavailable(); return { outcome: parsed.outcome, result: parsed.result_payload }; }
function authorityValues(authority: ValidatedCatalogAuthority) { return [authority.storeId, authority.principalId, authority.membershipId, authority.planId, authority.planCode, authority.planVersion, authority.now]; }

export class PostgresCatalogAdminRepository implements CatalogAdminRepository {
  private readonly options: PostgresCatalogAdminRepositoryOptions;
  constructor(options: PostgresCatalogAdminRepositoryOptions) {
    try {
      if (!options || typeof options !== "object" || Array.isArray(options) || Object.keys(options).sort().join(",") !== "audit,pool,role,timeouts,uuid" || options.role !== "celebix_saas_app" || typeof options.audit !== "function" || typeof options.uuid !== "function" || !options.timeouts || Object.keys(options.timeouts).sort().join(",") !== "idleTransactionMs,lockMs,poolCheckoutMs,statementMs") throw unavailable();
      for (const value of Object.values(options.timeouts)) timeout(value);
      this.options = Object.freeze({ ...options, timeouts: Object.freeze({ ...options.timeouts }) });
    } catch (error) { if (error instanceof CatalogAdminRepositoryError) throw error; throw unavailable(); }
  }
  private async acquire() { try { return await acquirePostgresClient(this.options.pool, this.options.timeouts.poolCheckoutMs); } catch { throw unavailable(); } }
  private async configure(client: PostgresClientLike) { await client.query("SELECT pg_catalog.set_config('statement_timeout', $1, true)", [timeout(this.options.timeouts.statementMs)]); await client.query("SELECT pg_catalog.set_config('lock_timeout', $1, true)", [timeout(this.options.timeouts.lockMs)]); await client.query("SELECT pg_catalog.set_config('idle_in_transaction_session_timeout', $1, true)", [timeout(this.options.timeouts.idleTransactionMs)]); await client.query("SET LOCAL ROLE celebix_saas_app"); }
  private expected(outcome: string) { return CODES.has(outcome) ? new CatalogAdminRepositoryError(outcome as CatalogAdminErrorCode) : undefined; }
  private async rollback(client: PostgresClientLike) { try { await client.query("ROLLBACK"); release(client); } catch { release(client, true); } }
  private async read<T>(spec: Spec, expected: string, parser: (value: unknown) => T) { const client = await this.acquire(); let began = false; let terminal = false; try { await client.query("BEGIN READ ONLY"); began = true; await this.configure(client); const result = row(await client.query(spec.text, spec.values)); const error = this.expected(result.outcome); if (error) throw error; if (result.outcome !== expected) throw unavailable(); const parsed = parser(result.result); try { await client.query("COMMIT"); terminal = true; release(client); } catch { terminal = true; release(client, true); throw unavailable(); } return parsed; } catch (error) { if (began && !terminal) await this.rollback(client); else if (!began && !terminal) release(client, true); if (error instanceof CatalogAdminRepositoryError) throw error; throw unavailable(); } }
  private audit() { try { const pending = this.options.audit({ type: "catalog_admin_commit_unknown" }); if (pending) void pending.catch(() => undefined); } catch {} }
  private recover<T>(authority: ValidatedCatalogAuthority, operationId: string, fingerprint: string, parser: RecoverParser<T>, recoveryFunction = "catalog_admin_recover_operation") { return this.read({ text: `SELECT outcome,result_payload FROM saas.${recoveryFunction}($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text)`, values: [...authorityValues(authority), operationId, fingerprint] }, "operation_replayed", (value) => parser(value, true)); }
  private async mutate<T>(authority: ValidatedCatalogAuthority, operationId: string, fingerprint: string, expected: string, spec: Spec, parser: RecoverParser<T>, recoveryFunction?: string) { const client = await this.acquire(); let began = false; let terminal = false; try { await client.query("BEGIN ISOLATION LEVEL READ COMMITTED"); began = true; await this.configure(client); const result = row(await client.query(spec.text, spec.values)); const error = this.expected(result.outcome); if (error) throw error; if (result.outcome !== expected && result.outcome !== "operation_replayed") throw unavailable(); const parsed = parser(result.result, result.outcome === "operation_replayed"); try { await client.query("COMMIT"); terminal = true; release(client); return parsed; } catch { terminal = true; release(client, true); this.audit(); return await this.recover(authority, operationId, fingerprint, parser, recoveryFunction); } } catch (error) { if (began && !terminal) await this.rollback(client); else if (!began && !terminal) release(client, true); if (error instanceof CatalogAdminRepositoryError) throw error; throw unavailable(); } }
  private authority(input: unknown, required: readonly string[], optional: readonly string[] = []) { const parsed = exactCatalogAdminInput(input, required, optional); return { parsed, authority: catalogAuthority(parsed.tenantContext as TenantContext, parsed.now as Date) }; }
  private uuid() { try { return catalogAdminUuid(this.options.uuid()); } catch { throw unavailable(); } }
  private mutation(value: unknown, replayed: boolean) { try { return parseCatalogAdminMutationResult({ ...payload(value, ["id", "version", "status", "updatedAt"]), replayed }); } catch { throw unavailable(); } }
  private preview(value: unknown, previewId: string) { try { const result=parseCatalogImportPreview(value); if(result.id!==previewId) throw unavailable(); return result; } catch(error) { if(error instanceof CatalogAdminRepositoryError) throw error; throw unavailable(); } }
  async listResources(input: ListCatalogAdminResourcesInput): Promise<readonly CatalogAdminResource[]> { const { parsed, authority } = this.authority(input, ["tenantContext", "now", "kind"]); const kind = catalogAdminKind(parsed.kind); return this.read({ text: "SELECT outcome,result_payload FROM saas.catalog_admin_list_resources($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::text)", values: [...authorityValues(authority), kind] }, "listed", (value) => { const result = payload(value, ["items"]); if (!Array.isArray(result.items) || result.items.length > 200) throw unavailable(); try { return Object.freeze(result.items.map(parseCatalogAdminResource)); } catch { throw unavailable(); } }); }
  async getResource(input: GetCatalogAdminResourceInput): Promise<CatalogAdminResource> { const { parsed, authority } = this.authority(input, ["tenantContext", "now", "kind", "resourceId"]); const kind = catalogAdminKind(parsed.kind); const resourceId = catalogAdminUuid(parsed.resourceId); return this.read({ text: "SELECT outcome,result_payload FROM saas.catalog_admin_get_resource($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::text,$9::uuid)", values: [...authorityValues(authority), kind, resourceId] }, "found", (value) => { try { const result = parseCatalogAdminResource(value); if (result.id !== resourceId || result.kind !== kind) throw unavailable(); return result; } catch (error) { if (error instanceof CatalogAdminRepositoryError) throw error; throw unavailable(); } }); }
  async saveResource(input: SaveCatalogAdminResourceInput): Promise<CatalogAdminMutationResult> { const { parsed, authority } = this.authority(input, ["tenantContext", "now", "operationId", "kind", "name", "slug", "config", "productIds"], ["resourceId", "expectedVersion", "description"]); const operationId = catalogAdminUuid(parsed.operationId); const existingId = parsed.resourceId === undefined ? undefined : catalogAdminUuid(parsed.resourceId); const expectedVersion = parsed.expectedVersion === undefined ? undefined : catalogAdminVersion(parsed.expectedVersion); if ((existingId === undefined) !== (expectedVersion === undefined)) throw new CatalogAdminRepositoryError("invalid_input"); const resourceId = existingId ?? this.uuid(); const kind = catalogAdminKind(parsed.kind); const name = catalogAdminText(parsed.name, 1, 120); const slug = catalogAdminSlug(parsed.slug); const description = parsed.description === undefined ? undefined : catalogAdminText(parsed.description, 1, 2000); const config = catalogAdminConfig(parsed.config); const productIds = uniqueCatalogIds(parsed.productIds); const fingerprint = catalogAdminFingerprint("save_resource", authority.storeId, { resourceId: existingId ?? null, expectedVersion: expectedVersion ?? null, kind, name, slug, description: description ?? null, config, productIds }); return this.mutate(authority, operationId, fingerprint, "saved", { text: "SELECT outcome,result_payload FROM saas.catalog_admin_save_resource($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text,$10::uuid,$11::bigint,$12::text,$13::text,$14::text,$15::text,$16::jsonb,$17::uuid[])", values: [...authorityValues(authority), operationId, fingerprint, resourceId, expectedVersion ?? null, kind, name, slug, description ?? null, JSON.stringify(config), productIds] }, (value, replayed) => { const result = this.mutation(value, replayed); if (!replayed && result.id !== resourceId) throw unavailable(); return result; }); }
  async archiveResource(input: ArchiveCatalogAdminResourceInput) { const { parsed, authority } = this.authority(input, ["tenantContext", "now", "operationId", "resourceId", "expectedVersion"]); const operationId = catalogAdminUuid(parsed.operationId); const resourceId = catalogAdminUuid(parsed.resourceId); const expectedVersion = catalogAdminVersion(parsed.expectedVersion); const fingerprint = catalogAdminFingerprint("archive_resource", authority.storeId, { resourceId, expectedVersion }); return this.mutate(authority, operationId, fingerprint, "archived", { text: "SELECT outcome,result_payload FROM saas.catalog_admin_archive_resource($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text,$10::uuid,$11::bigint)", values: [...authorityValues(authority), operationId, fingerprint, resourceId, expectedVersion] }, (value, replayed) => { const result = this.mutation(value, replayed); if (result.id !== resourceId || result.status !== "archived") throw unavailable(); return result; }); }
  async listReviews(input: ListProductReviewsInput): Promise<readonly ProductReview[]> { const { parsed, authority } = this.authority(input, ["tenantContext", "now"], ["status"]); const status = parsed.status === undefined ? undefined : catalogAdminReviewStatus(parsed.status); return this.read({ text: "SELECT outcome,result_payload FROM saas.catalog_admin_list_reviews($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::text)", values: [...authorityValues(authority), status ?? null] }, "listed", (value) => { const result = payload(value, ["items"]); if (!Array.isArray(result.items) || result.items.length > 200) throw unavailable(); try { return Object.freeze(result.items.map(parseProductReview)); } catch { throw unavailable(); } }); }
  async moderateReview(input: ModerateProductReviewInput) { const { parsed, authority } = this.authority(input, ["tenantContext", "now", "operationId", "reviewId", "expectedVersion", "status"], ["reply"]); const operationId = catalogAdminUuid(parsed.operationId); const reviewId = catalogAdminUuid(parsed.reviewId); const expectedVersion = catalogAdminVersion(parsed.expectedVersion); const status = catalogAdminReviewStatus(parsed.status, false); const reply = parsed.reply === undefined ? undefined : catalogAdminText(parsed.reply, 1, 2000); const fingerprint = catalogAdminFingerprint("moderate_review", authority.storeId, { reviewId, expectedVersion, status, reply: reply ?? null }); return this.mutate(authority, operationId, fingerprint, "moderated", { text: "SELECT outcome,result_payload FROM saas.catalog_admin_moderate_review($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid,$9::text,$10::uuid,$11::bigint,$12::text,$13::text)", values: [...authorityValues(authority), operationId, fingerprint, reviewId, expectedVersion, status, reply ?? null] }, (value, replayed) => { const result = this.mutation(value, replayed); if (result.id !== reviewId) throw unavailable(); return result; }); }
  async listImports(input: CatalogAdminAuthorityInput): Promise<readonly CatalogAdminImportJob[]> { const { authority } = this.authority(input, ["tenantContext", "now"]); return this.read({ text: "SELECT outcome,result_payload FROM saas.catalog_admin_list_imports($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz)", values: authorityValues(authority) }, "listed", (value) => { const result = payload(value, ["items"]); if (!Array.isArray(result.items) || result.items.length > 100) throw unavailable(); try { return Object.freeze(result.items.map(parseCatalogAdminImportJob)); } catch { throw unavailable(); } }); }
  async importProducts(input: ImportCatalogProductsInput) { const { parsed, authority } = this.authority(input, ["tenantContext", "now", "operationId", "fileName", "rows"]); const operationId = catalogAdminUuid(parsed.operationId); const fileName = catalogAdminText(parsed.fileName, 1, 200); const rows = catalogAdminImportRows(parsed.rows); const jobId = this.uuid(); const persistedRows = rows.map((entry) => ({ productId: this.uuid(), variantId: this.uuid(), title: entry.title, slug: entry.slug, priceCents: entry.priceCents, sku: entry.sku ?? null, stockQuantity: entry.stockQuantity })); const fingerprint = catalogAdminFingerprint("import_products", authority.storeId, { fileName, rows }); return this.mutate(authority, operationId, fingerprint, "imported", { text: "SELECT outcome,result_payload FROM saas.catalog_admin_import_products($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::bigint,$9::uuid,$10::text,$11::uuid,$12::text,$13::jsonb)", values: [...authorityValues(authority), authority.productsLimit, operationId, fingerprint, jobId, fileName, JSON.stringify(persistedRows)] }, (value, replayed) => { const result = this.mutation(value, replayed); if (!replayed && result.id !== jobId) throw unavailable(); return result; }); }
  async prepareImport(input: PrepareCatalogImportPreviewInput): Promise<CatalogImportPreview> { const { parsed, authority } = this.authority(input, ["tenantContext", "now", "operationId", "previewId", "format", "fileName", "digest", "rows"]); const operationId=catalogAdminUuid(parsed.operationId); const previewId=catalogAdminUuid(parsed.previewId); const format=catalogImportFormat(parsed.format); const fileName=catalogAdminText(parsed.fileName,1,200); const digest=catalogImportDigest(parsed.digest); const rows=catalogAdminImportRows(parsed.rows); const fingerprint=catalogAdminFingerprint("prepare_import_preview",authority.storeId,{previewId,format,fileName,digest,rows}); return this.mutate(authority,operationId,fingerprint,"prepared",{text:"SELECT outcome,result_payload FROM saas.catalog_admin_prepare_import_preview($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::bigint,$9::uuid,$10::text,$11::uuid,$12::text,$13::text,$14::text,$15::jsonb)",values:[...authorityValues(authority),authority.productsLimit,operationId,fingerprint,previewId,format,fileName,digest,JSON.stringify(rows)]},(value)=>{try{const result=parseCatalogImportPreview(value);if(result.id!==previewId)throw unavailable();return result;}catch(error){if(error instanceof CatalogAdminRepositoryError)throw error;throw unavailable();}},"catalog_admin_recover_import_preview_operation"); }
  async getImportPreview(input: GetCatalogImportPreviewInput): Promise<CatalogImportPreview> { const {parsed,authority}=this.authority(input,["tenantContext","now","previewId"]); const previewId=catalogAdminUuid(parsed.previewId); return this.read({text:"SELECT outcome,result_payload FROM saas.catalog_admin_get_import_preview($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid)",values:[...authorityValues(authority),previewId]},"found",(value)=>this.preview(value,previewId)); }
  async commitImportPreview(input: CommitCatalogImportPreviewInput): Promise<CatalogAdminMutationResult> {
    const {parsed,authority}=this.authority(input,["tenantContext","now","operationId","previewId","expectedVersion"]);
    const operationId=catalogAdminUuid(parsed.operationId),previewId=catalogAdminUuid(parsed.previewId),expectedVersion=catalogAdminVersion(parsed.expectedVersion),jobId=this.uuid();
    const client=await this.acquire(); let began=false,terminal=false;
    let fingerprint="";
    const parseMutation=(value:unknown,replayed:boolean)=>{const result=this.mutation(value,replayed);if(!replayed&&result.id!==jobId)throw unavailable();return result;};
    try {
      await client.query("BEGIN ISOLATION LEVEL READ COMMITTED"); began=true; await this.configure(client);
      const snapshot=row(await client.query("SELECT outcome,result_payload FROM saas.catalog_admin_get_import_preview($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::uuid)",[...authorityValues(authority),previewId]));
      const snapshotError=this.expected(snapshot.outcome); if(snapshotError)throw snapshotError; if(snapshot.outcome!=="found")throw unavailable();
      const persisted=this.preview(snapshot.result,previewId);
      fingerprint=catalogAdminFingerprint("commit_import_preview",authority.storeId,{previewId,expectedVersion,format:persisted.format,digest:persisted.digest,rows:persisted.rows});
      const result=row(await client.query("SELECT outcome,result_payload FROM saas.catalog_admin_commit_import_preview($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text,$6::bigint,$7::timestamptz,$8::bigint,$9::uuid,$10::text,$11::uuid,$12::bigint,$13::text,$14::text,$15::jsonb,$16::uuid)",[...authorityValues(authority),authority.productsLimit,operationId,fingerprint,previewId,expectedVersion,persisted.format,persisted.digest,JSON.stringify(persisted.rows),jobId]));
      const mutationError=this.expected(result.outcome); if(mutationError)throw mutationError; if(result.outcome!=="imported"&&result.outcome!=="operation_replayed")throw unavailable();
      const projected=parseMutation(result.result,result.outcome==="operation_replayed");
      try { await client.query("COMMIT"); terminal=true; release(client); return projected; }
      catch { terminal=true; release(client,true); this.audit(); return await this.recover(authority,operationId,fingerprint,parseMutation,"catalog_admin_recover_import_preview_operation"); }
    } catch(error) { if(began&&!terminal)await this.rollback(client); else if(!began&&!terminal)release(client,true); if(error instanceof CatalogAdminRepositoryError)throw error; throw unavailable(); }
  }
}
