"use client";

import type { StorefrontAccountAddress } from "@celebix/saas-contracts";
import { useState } from "react";

function csrf() { return document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("__Host-celebix_account_csrf="))?.slice("__Host-celebix_account_csrf=".length) ?? ""; }
type AddressForm = { label: string; recipientName: string; line1: string; city: string; district: string; postalCode: string; isDefault: boolean };
const EMPTY: Readonly<AddressForm> = Object.freeze({ label: "", recipientName: "", line1: "", city: "", district: "", postalCode: "", isDefault: false });

export function AccountAddresses({ addresses }: Readonly<{ addresses: readonly StorefrontAccountAddress[] }>) {
  const [editing, setEditing] = useState<StorefrontAccountAddress | null>(null); const [form, setForm] = useState<AddressForm>({ ...EMPTY }); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false);
  function change(key: keyof AddressForm, value: string | boolean) { setForm((current) => ({ ...current, [key]: value })); }
  function select(address: StorefrontAccountAddress) { setEditing(address); setForm({ label: address.label, recipientName: address.recipientName, line1: address.line1, city: address.city, district: address.district ?? "", postalCode: address.postalCode ?? "", isDefault: address.isDefault }); setStatus(""); }
  async function save(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setStatus(""); const id = editing?.id ?? crypto.randomUUID(); const expectedVersion = editing?.version ?? 0;
    try { const response = await fetch("/api/account/addresses/save", { method: "POST", credentials: "same-origin", cache: "no-store", headers: { "content-type": "application/json", "x-celebix-account-csrf": csrf() }, body: JSON.stringify({ operationId: crypto.randomUUID(), expectedVersion, address: { id, label: form.label, recipientName: form.recipientName, line1: form.line1, city: form.city, ...(form.district ? { district: form.district } : {}), ...(form.postalCode ? { postalCode: form.postalCode } : {}), country: "TR", isDefault: form.isDefault, version: Math.max(1, expectedVersion) } }) }); const payload = await response.json().catch(() => null) as { message?: string } | null; if (!response.ok) throw new Error(payload?.message || "Adres kaydedilemedi."); window.location.reload(); } catch (error) { setStatus(error instanceof Error ? error.message : "Adres kaydedilemedi."); setBusy(false); }
  }
  async function remove(address: StorefrontAccountAddress) { if (busy) return; setBusy(true); setStatus(""); try { const response = await fetch("/api/account/addresses/delete", { method: "POST", credentials: "same-origin", cache: "no-store", headers: { "content-type": "application/json", "x-celebix-account-csrf": csrf() }, body: JSON.stringify({ operationId: crypto.randomUUID(), addressId: address.id, expectedVersion: address.version }) }); if (!response.ok) throw new Error(); window.location.reload(); } catch { setStatus("Adres silinemedi."); setBusy(false); } }
  return <div className="account-address-layout"><div className="account-address-list">{addresses.map((address) => <article key={address.id}><div><strong>{address.label}</strong>{address.isDefault ? <span>Varsayılan</span> : null}</div><p>{address.recipientName}<br />{address.line1}<br />{address.district ? `${address.district}, ` : ""}{address.city}</p><footer><button type="button" onClick={() => select(address)}>Düzenle</button><button type="button" onClick={() => void remove(address)}>Sil</button></footer></article>)}{addresses.length === 0 ? <p className="account-inline-empty">Kayıtlı adresiniz yok.</p> : null}</div><form className="account-address-form" onSubmit={save}><h2>{editing ? "Adresi düzenle" : "Yeni adres"}</h2><label><span>Adres adı</span><input required value={form.label} onChange={(e) => change("label", e.currentTarget.value)} placeholder="Ev" /></label><label><span>Alıcı</span><input required autoComplete="name" value={form.recipientName} onChange={(e) => change("recipientName", e.currentTarget.value)} /></label><label><span>Adres</span><textarea required autoComplete="street-address" value={form.line1} onChange={(e) => change("line1", e.currentTarget.value)} /></label><div><label><span>İlçe</span><input value={form.district} onChange={(e) => change("district", e.currentTarget.value)} /></label><label><span>Şehir</span><input required autoComplete="address-level1" value={form.city} onChange={(e) => change("city", e.currentTarget.value)} /></label></div><label><span>Posta kodu</span><input inputMode="numeric" autoComplete="postal-code" value={form.postalCode} onChange={(e) => change("postalCode", e.currentTarget.value)} /></label><label className="account-check"><input type="checkbox" checked={form.isDefault} onChange={(e) => change("isDefault", e.currentTarget.checked)} /><span>Varsayılan adres yap</span></label><button className="store-button" disabled={busy} type="submit">{busy ? "Kaydediliyor…" : "Kaydet"}</button>{editing ? <button className="account-text-action" type="button" onClick={() => { setEditing(null); setForm({ ...EMPTY }); }}>Vazgeç</button> : null}<p role="status" className="account-form-status">{status}</p></form></div>;
}
